function Get-WsmTestEvidencePhase([string]$Check) {
    switch -CaseSensitive ($Check) {
        {$_ -in @('SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval')} { return 'CutoverReady' }
        ManualRestore { return 'StagedDependencyVerified' }
        BusinessStaged { return 'CutoverReady' }
        RollbackReconcile { return 'RollbackReady' }
        {$_ -in @('BackupRestore','LongCycleJobs','Observation','RetirementRetention','ExternalConsumerOldPathDrained','SpecialProductDisposition','DataRetentionHandoff','CredentialHandoff','CertificateHandoff','CMDBHandoff','DNSHandoff','LicenseHandoff','MonitoringHandoff','RollbackCutoffAndDeletionOwner')} { return 'RetirementReady' }
        default { return 'FinalAccepted' }
    }
}
function New-WsmSourceFreezeEvidenceFixture {
    param([Parameter(Mandatory)]$Plan,[Parameter(Mandatory)][string]$PlanHash,[Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][string]$Owner,[string]$FreezeEpoch=([Guid]::NewGuid().ToString('D')),[bool]$AllStopped=$true)
    $directory=Join-Path $Root 'source-freeze-evidence';if(-not [IO.Directory]::Exists($directory)){[void][IO.Directory]::CreateDirectory($directory)}
    $id=[Guid]::NewGuid().ToString('D');$writers=@([pscustomobject][ordered]@{WriterId='fixture-writer-1';Owner=$Owner;Scope='pair-wide business writer';Kind='External';Stopped=$AllStopped;OwnershipReviewed=$true;EvidenceId=$id})
    $writerJson=ConvertTo-Json -InputObject @($writers) -Depth 8 -Compress;$sha=[Security.Cryptography.SHA256]::Create();try{$writerBytes=[Text.Encoding]::UTF8.GetBytes($writerJson);$writerHash=([BitConverter]::ToString($sha.ComputeHash($writerBytes))).Replace('-','')}finally{$sha.Dispose()}
    $facts=[ordered]@{WriterSetEnumerated=$true;WriterOwnershipReviewed=$true;AllWritersStopped=$AllStopped;OwnerAccepted=$true};$artifact=Join-Path $directory ($id+'.payload.json');$payload=[pscustomobject]@{WriterInventory=$writers;WriterSetHash=$writerHash;Observation='Fixture only; no external writer or production state was inspected.'};$payloadBytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($payload|ConvertTo-Json -Depth 8 -Compress));[IO.File]::WriteAllBytes($artifact,$payloadBytes);$artifactHash=(Get-FileHash -LiteralPath $artifact -Algorithm SHA256).Hash.ToLowerInvariant()
    $record=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$Plan.ToolVersion;Kind='ExternalReadinessEvidence';EvidenceId=$id;PairId=$Plan.PairId;SourceFingerprint=$Plan.Source.Fingerprint;TargetFingerprint=$Plan.Target.Fingerprint;ToolFingerprint=$Plan.ToolFingerprint;PlanHash=$PlanHash;ManifestHash='';Phase='SourceFreezeReady';Check='SourceWritersFenced';ItemId='';Context=[pscustomobject][ordered]@{Scope='Pair';ItemId='';ContextType='Cutover';ConsumerId='pair-level'};Owner=$Owner;ObservedUtc=[DateTime]::UtcNow.ToString('o');ExpiresUtc=[DateTime]::UtcNow.AddHours(2).ToString('o');PayloadArtifact=[pscustomobject]@{Path=[IO.Path]::GetFullPath($artifact);SHA256=$artifactHash};FreezeEpoch=$FreezeEpoch;SourceWriterInventory=$writers;WriterSetHash=$writerHash;TypedResults=[pscustomobject][ordered]@{Outcome=$(if($AllStopped){'Pass'}else{'Fail'});TestId='fixture-source-writers';Method='FixtureMock';Expected='All enumerated writer scopes stopped and owner-reviewed';Observed=$(if($AllStopped){'Fixture records the finite writer set'}else{'A fixture writer remains active'});Facts=[pscustomobject]$facts;NotApplicableReasons=[pscustomobject]@{}}}
    $path=Join-Path $directory ($id+'.json');$bytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($record|ConvertTo-Json -Depth 20)+[Environment]::NewLine);[IO.File]::WriteAllBytes($path,$bytes)
    [pscustomobject]@{Path=[IO.Path]::GetFullPath($path);SHA256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant();FreezeEpoch=$FreezeEpoch;Evidence=$record}
}
function New-WsmSourceResumeEvidenceFixture {
    param([Parameter(Mandatory)]$Plan,[Parameter(Mandatory)][string]$PlanHash,[Parameter(Mandatory)][string]$AttemptId,[Parameter(Mandatory)][string]$AttemptHash,[Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][string]$Owner,[bool]$AllFacts=$true)
    $directory=Join-Path $Root 'source-resume-evidence';if(-not [IO.Directory]::Exists($directory)){[void][IO.Directory]::CreateDirectory($directory)};$id=[Guid]::NewGuid().ToString('D');$artifact=Join-Path $directory ($id+'.payload.json');$payload=[pscustomobject]@{SourceAttemptId=$AttemptId;SourceAttemptHash=$AttemptHash;Observation='Fixture only; no target system was inspected.'};$payloadBytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($payload|ConvertTo-Json -Compress));[IO.File]::WriteAllBytes($artifact,$payloadBytes);$artifactHash=(Get-FileHash -LiteralPath $artifact -Algorithm SHA256).Hash.ToLowerInvariant()
    $facts=[ordered]@{TargetWritersStopped=$AllFacts;LatestTargetPreserved=$AllFacts;ReconciliationCompleted=$AllFacts;SourceExclusiveWriteOwner=$AllFacts;OwnerAccepted=$true};$record=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$Plan.ToolVersion;Kind='ExternalReadinessEvidence';EvidenceId=$id;PairId=$Plan.PairId;SourceFingerprint=$Plan.Source.Fingerprint;TargetFingerprint=$Plan.Target.Fingerprint;ToolFingerprint=$Plan.ToolFingerprint;PlanHash=$PlanHash;ManifestHash='';Phase='SourceResumeReady';Check='SourceOwnershipRestored';ItemId='';Context=[pscustomobject][ordered]@{Scope='Pair';ItemId='';ContextType='Rollback';ConsumerId='pair-level'};Owner=$Owner;ObservedUtc=[DateTime]::UtcNow.ToString('o');ExpiresUtc=[DateTime]::UtcNow.AddHours(2).ToString('o');PayloadArtifact=[pscustomobject]@{Path=[IO.Path]::GetFullPath($artifact);SHA256=$artifactHash};SourceAttemptId=$AttemptId;SourceAttemptHash=$AttemptHash;TypedResults=[pscustomobject][ordered]@{Outcome=$(if($AllFacts){'Pass'}else{'Fail'});TestId='fixture-source-resume';Method='FixtureMock';Expected='Target stopped, latest target preserved and writes reconciled';Observed='Fixture only';Facts=[pscustomobject]$facts;NotApplicableReasons=[pscustomobject]@{}}}
    $path=Join-Path $directory ($id+'.json');$bytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($record|ConvertTo-Json -Depth 12)+[Environment]::NewLine);[IO.File]::WriteAllBytes($path,$bytes);[pscustomobject]@{Path=[IO.Path]::GetFullPath($path);SHA256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant();Evidence=$record}
}
function Get-WsmTestEvidenceFactNames([string]$Check) {
    $map=@{
        ManualRestore=@('NativeReadbackPerformed','ExpectedStateMatched','OwnerAccepted');BusinessStaged=@('ConsumerExecuted','ExpectedResultMatched','OwnerAccepted');BusinessFinal=@('ConsumerExecuted','ExpectedResultMatched','OwnerAccepted')
        DNS=@('ForwardResolutionMatched','ReverseResolutionMatched','OwnerAccepted');Kerberos=@('TicketObtained','ServicePrincipalMatched','OwnerAccepted');ExternalConnectivity=@('EndpointReachable','ExpectedIdentityMatched','OwnerAccepted');Monitoring=@('SignalObserved','AlertRouteConfirmed','OwnerAccepted')
        BackupRestore=@('BackupRestored','IntegrityVerified','OwnerAccepted');LongCycleJobs=@('LongCycleRunCompleted','ResultVerified','OwnerAccepted');SecurityAgent=@('AgentHealthy','PolicyConfirmed','OwnerAccepted');License=@('EntitlementVerified','UsageWithinTerms','OwnerAccepted');UserAcceptance=@('UserWorkflowPassed','OwnerAccepted');Observation=@('WindowCompleted','AlertReviewPassed','OwnerAccepted');RetirementRetention=@('RetentionTermRecorded','OwnerAccepted')
        RollbackReconcile=@('WritersStopped','LatestTargetPreserved','DataReconciled','ProductSynchronizationComplete','OwnerAccepted');SourceIdentityReleased=@('HostnameReleased','IpReleased','DomainIdentityReleased','OwnerAccepted');SourceWritersFenced=@('SourceWritersStopped','ExternalWritersFenced','OwnerAccepted');TargetIsolationConfirmed=@('TargetIsolated','TemporaryIdentityVerified','OwnerAccepted');ExternalNetworkFencing=@('DnsPtrFenced','SpnFenced','DhcpFenced','LoadBalancerFenced','OwnerAccepted');NetworkOwnerApproval=@('FinalNameApproved','FinalIpApproved','DnsApproved','RollbackProcedureApproved','OwnerAccepted')
        ExternalConsumerOldPathDrained=@('OldPathTrafficZero','ObservationWindowComplete','OwnerAccepted');SpecialProductDisposition=@('ProductOwnerDispositionComplete','VendorProcedureComplete','OwnerAccepted');DataRetentionHandoff=@('RetentionTermRecorded','DataOwnerAccepted','OwnerAccepted');CredentialHandoff=@('CredentialOwnersUpdated','OldCredentialsRevoked','OwnerAccepted');CertificateHandoff=@('CertificateOwnersUpdated','OldCertificatesRevoked','OwnerAccepted');CMDBHandoff=@('CIRelationshipsUpdated','OwnerAccepted');DNSHandoff=@('OldRecordsRetired','NewRecordsOwned','OwnerAccepted');LicenseHandoff=@('LicenseTransferred','OldEntitlementReleased','OwnerAccepted');MonitoringHandoff=@('MonitoringOwnerUpdated','AlertRouteTested','OwnerAccepted');RollbackCutoffAndDeletionOwner=@('RollbackDeadlineRecorded','IrrevocablePointRecorded','DeletionOwnerAuthorized','OwnerAccepted')
    }
    @($map[$Check])
}
function New-WsmExternalReadinessEvidenceFixture {
    param([Parameter(Mandatory)]$Package,[Parameter(Mandatory)][string]$Root,[Parameter(Mandatory)][string]$Check,[string]$ItemId='', [bool]$Passed=$true,[string]$BindingOverride='',[string]$ExpiryOverride='')
    $directory=Join-Path $Root 'external-evidence';if(-not [IO.Directory]::Exists($directory)){[void][IO.Directory]::CreateDirectory($directory)}
    $id=[Guid]::NewGuid().ToString('D');$artifact=Join-Path $directory ($id+'.payload.txt');[IO.File]::WriteAllText($artifact,('Fixture native fact payload for '+$Check+' '+$id),(New-Object Text.UTF8Encoding($false)));$artifactHash=(Get-FileHash -LiteralPath $artifact -Algorithm SHA256).Hash.ToLowerInvariant()
    $facts=[ordered]@{};foreach($name in (Get-WsmTestEvidenceFactNames $Check)){$facts[$name]=($name -eq 'OwnerAccepted' -or $Passed)}
    $context=[pscustomobject][ordered]@{Scope=$(if($ItemId){'Item'}else{'Pair'});ItemId=$ItemId;ContextType=$(if($ItemId){'Consumer'}elseif($Check -eq 'RollbackReconcile'){'Rollback'}elseif($Check -match 'Handoff|Retirement|Observation|LongCycle|BackupRestore'){'Retirement'}elseif($Check -in @('SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval')){'Cutover'}else{'Acceptance'});ConsumerId=$(if($ItemId){$ItemId}else{'pair-level'})}
    $observed=[DateTime]::UtcNow.ToString('o');$expires=[DateTime]::UtcNow.AddHours(2).ToString('o');if($ExpiryOverride){$expires=$ExpiryOverride}
    $record=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$Package.Manifest.ToolVersion;Kind='ExternalReadinessEvidence';EvidenceId=$id;PairId=$Package.Manifest.PairId;SourceFingerprint=$Package.Manifest.Source.Fingerprint;TargetFingerprint=$Package.Manifest.Target.Fingerprint;ToolFingerprint=$Package.Plan.ToolFingerprint;PlanHash=$Package.Manifest.PlanHash;ManifestHash=$Package.SHA256;Phase=(Get-WsmTestEvidencePhase $Check);Check=$Check;ItemId=$ItemId;Context=$context;Owner='Fixture independent owner';ObservedUtc=$observed;ExpiresUtc=$expires;PayloadArtifact=[pscustomobject]@{Path=[IO.Path]::GetFullPath($artifact);SHA256=$artifactHash};TypedResults=[pscustomobject][ordered]@{Outcome=$(if($Passed){'Pass'}else{'Fail'});TestId=('fixture-'+$Check);Method='FixtureMock';Expected='Reviewed expected value';Observed=$(if($Passed){'Expected value observed in fixture'}else{'Mismatch observed in fixture'});Facts=[pscustomobject]$facts;NotApplicableReasons=[pscustomobject]@{}}}
    if($BindingOverride){$record.PairId=$BindingOverride}
    $path=Join-Path $directory ($id+'.json');$json=$record|ConvertTo-Json -Depth 20;$bytes=(New-Object Text.UTF8Encoding($false)).GetBytes($json+[Environment]::NewLine);[IO.File]::WriteAllBytes($path,$bytes)
    [pscustomobject]@{Path=[IO.Path]::GetFullPath($path);SHA256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant();Check=$Check;ItemId=$ItemId;Evidence=$record}
}
function Set-WsmExternalFixtureValidationEvidence {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[string]$ItemId,[string]$Check,[string]$Owner,[string]$Evidence,[bool]$Passed,[ValidateRange(1,720)][int]$ValidHours=24)
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;$tempRoot=Join-Path $StateDirectory 'external-readiness-fixtures';if(-not [IO.Directory]::Exists($tempRoot)){[void][IO.Directory]::CreateDirectory($tempRoot)}
    $reference=New-WsmExternalReadinessEvidenceFixture -Package $package -Root $tempRoot -Check $Check -ItemId $ItemId -Passed $Passed;Set-WsmValidationEvidence -ManifestPath $ManifestPath -ExpectedHash $ExpectedHash -StateDirectory $StateDirectory -ItemId $ItemId -Check $Check -Owner 'Fixture independent owner' -Evidence $Evidence -Passed $Passed -ValidHours $ValidHours -ExternalEvidencePath $reference.Path -ExternalEvidenceHash $reference.SHA256
}
function New-WsmCutoverEvidenceFixtureReferences {
    param([Parameter(Mandatory)]$Package,[Parameter(Mandatory)][string]$Root)
    foreach($check in @('SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval')){$fixture=New-WsmExternalReadinessEvidenceFixture -Package $Package -Root $Root -Check $check;[pscustomobject][ordered]@{Path=$fixture.Path;SHA256=$fixture.SHA256;Check=$check}}
}
