#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
& $module {
    . (Join-Path $PSScriptRoot 'Helper-Fixtures.ps1')
    function script:Get-WsmServiceSupplementState {param($Name)$script:fixtureServices[$Name].Supplement}
    function script:Set-WsmServiceSupplement {param($Name,$Supplement,$Phase)$script:fixtureServices[$Name] | Add-Member NoteProperty Supplement (Get-WsmServiceSupplementForPhase $Supplement $Phase) -Force}
    $script:fixtureTasks=@{};$script:fixtureServices=@{};$script:fixtureFeatures=@{}
    $script:fixtureFolders=@{};$script:fixtureRootSddl='O:SYG:SYD:(A;;FA;;;SY)';$script:fixtureFolderSddl='O:SYG:SYD:(A;;FA;;;BA)'
    function script:New-WsmFixtureTaskFolder([string]$Path,[string]$Sddl){$folder=[pscustomobject]@{Path=$Path;SecuritySddl=$Sddl};$folder | Add-Member ScriptMethod GetSecurityDescriptor {param($Flags)$this.SecuritySddl};$folder | Add-Member ScriptMethod GetFolder {param($Name)$path=$this.Path;if($path -cne '\'){$path=$path+$Name+'\'}else{$path='\'+$Name+'\'};if(-not $script:fixtureFolders.ContainsKey($path)){throw (New-Object System.Runtime.InteropServices.COMException('Not found',-2147024894))};$script:fixtureFolders[$path]};$folder | Add-Member ScriptMethod CreateFolder {param($Name,$Sddl)$path=$this.Path;if($path -cne '\'){$path=$path+$Name+'\'}else{$path='\'+$Name+'\'};if($script:fixtureFolders.ContainsKey($path)){throw 'Already exists'};$created=New-WsmFixtureTaskFolder $path $Sddl;$script:fixtureFolders[$path]=$created;$created};$folder | Add-Member ScriptMethod GetTask {param($Name)$script:fixtureTasks[$this.Path+$Name]};$folder | Add-Member ScriptMethod GetTasks {param($Flags)@($script:fixtureTasks.Keys | Where-Object {$_.StartsWith($this.Path,[StringComparison]::OrdinalIgnoreCase) -and $_.Substring($this.Path.Length).IndexOf('\') -lt 0} | ForEach-Object {$script:fixtureTasks[$_]})};$folder | Add-Member ScriptMethod GetFolders {param($Flags)@($script:fixtureFolders.Values | Where-Object {$_.Path -ne $this.Path -and $_.Path.StartsWith($this.Path,[StringComparison]::OrdinalIgnoreCase) -and $_.Path.Substring($this.Path.Length).Trim('\').IndexOf('\') -lt 0})};$folder | Add-Member ScriptMethod DeleteFolder {param($Name,$Flags)$path=$this.Path+$Name+'\';$script:fixtureFolders.Remove($path)};$folder}
    $script:fixtureFolders['\']=New-WsmFixtureTaskFolder '\' $script:fixtureRootSddl
    $script:fixtureScheduler=[pscustomobject]@{};$script:fixtureScheduler | Add-Member ScriptMethod GetFolder {param($Path)if($Path -eq '\'){return $script:fixtureFolders['\']};$canonical='\'+$Path.Trim('\')+'\';if(-not $script:fixtureFolders.ContainsKey($canonical)){throw (New-Object System.Runtime.InteropServices.COMException('Not found',-2147024894))};$script:fixtureFolders[$canonical]}
    function script:New-WsmTaskScheduler {$script:fixtureScheduler}
    function script:Register-ScheduledTask {param($TaskName,$TaskPath,$Xml,$User,$Password,$ErrorAction)$doc=Read-WsmXml $Xml;$enabled=$doc.SelectSingleNode("//*[local-name()='Settings']/*[local-name()='Enabled']");if(-not $enabled -or $enabled.InnerText -ne 'false'){throw 'Fixture observed registration with enabled=true; dual-running risk.'};$task=[pscustomobject]@{Xml=$Xml;SecuritySddl='O:SYG:SYD:(A;;FA;;;SY)';Settings=[pscustomobject]@{Enabled=$false}};$task | Add-Member ScriptMethod SetSecurityDescriptor {param($Sddl,$Flags)$this.SecuritySddl=$Sddl};$task | Add-Member ScriptMethod GetSecurityDescriptor {param($Flags)$this.SecuritySddl};$script:fixtureTasks[$TaskPath+$TaskName]=$task}
    function script:Get-ScheduledTask {param($TaskName,$TaskPath,$ErrorAction)$script:fixtureTasks[$TaskPath+$TaskName]}
    function script:Export-ScheduledTask {param($TaskName,$TaskPath)$script:fixtureTasks[$TaskPath+$TaskName].Xml}
    function script:Enable-ScheduledTask {param($TaskName,$TaskPath)$t=$script:fixtureTasks[$TaskPath+$TaskName];$doc=Read-WsmXml $t.Xml;$doc.SelectSingleNode("//*[local-name()='Settings']/*[local-name()='Enabled']").InnerText='true';$t.Xml=$doc.OuterXml;$t.Settings.Enabled=$true}
    function script:Disable-ScheduledTask {param($TaskName,$TaskPath)$t=$script:fixtureTasks[$TaskPath+$TaskName];$doc=Read-WsmXml $t.Xml;$doc.SelectSingleNode("//*[local-name()='Settings']/*[local-name()='Enabled']").InnerText='false';$t.Xml=$doc.OuterXml;$t.Settings.Enabled=$false}
    function script:New-Service {[CmdletBinding(SupportsShouldProcess)]param($Name,$BinaryPathName,$StartupType,$DisplayName,[string]$Description='',[string[]]$DependsOn=@(),$Credential)if($StartupType -ne 'Disabled'){throw 'Service was created active.'};$script:fixtureServices[$Name]=[pscustomobject]@{Name=$Name;DisplayName=$DisplayName;PathName=$BinaryPathName;StartMode='Disabled';StartName=$(if($Credential){$Credential.UserName}else{'LocalSystem'});State='Stopped';Description=$Description;Dependencies=@($DependsOn)}}
    function script:Get-WsmServiceDependencies {param($Name) @($script:fixtureServices[$Name].Dependencies)}
    function script:Get-CimInstance {param($ClassName)if($ClassName -ne 'Win32_Service'){throw 'Unexpected CIM probe.'};$script:fixtureServices.Values}
    function script:Set-Service {param($Name,$StartupType)$mode=$StartupType;if($mode -eq 'Automatic'){$mode='Auto'};$script:fixtureServices[$Name].StartMode=$mode}
    function script:Start-Service {param($Name)$script:fixtureServices[$Name].State='Running'}
    function script:Stop-Service {param($Name,$ErrorAction)$script:fixtureServices[$Name].State='Stopped'}
    function script:Get-WindowsFeature {param($Name,$ErrorAction)[pscustomobject]@{Name=$Name;Installed=$script:fixtureFeatures.ContainsKey($Name)}}
    function script:Get-WsmInstallerSnapshot {[pscustomobject]@{Items=@();Utc=(Get-WsmUtc)}}
    function script:Install-WindowsFeature {param($Name,$Source,$ErrorAction)$script:fixtureFeatures[$Name]=$true;[pscustomobject]@{Success=$true;RestartNeeded='Yes';ExitCode='SuccessRestart'}}
    $task=[pscustomobject]@{Adapter='ScheduledTask';CatchUpPolicy='PreserveSourceSettings';Owner='fixture';Evidence='fixture-reviewed';DesiredFinalState='Enabled';Desired=[pscustomobject]@{TaskName='FixtureTask';TaskPath='\Fixture\';Xml='<Task xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"><Principals><Principal><UserId>SYSTEM</UserId><LogonType>ServiceAccount</LogonType></Principal></Principals><Triggers><BootTrigger><Enabled>true</Enabled></BootTrigger></Triggers><Settings><Enabled>true</Enabled><MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy></Settings><Actions><Exec><Command>C:\Fixture\worker.exe</Command></Exec></Actions></Task>';User='SYSTEM';SecuritySddl='O:SYG:SYD:(A;;FA;;;SY)';FolderSecurity=@([pscustomobject]@{Path='\';SecuritySddl=$script:fixtureRootSddl;ExistingPolicy='VerifyExact'},[pscustomobject]@{Path='\Fixture\';SecuritySddl=$script:fixtureFolderSddl;ExistingPolicy='CreateOnly'})}}
    Assert-WsmMigrationSpec $task;$folderReceipts=New-Object 'System.Collections.Generic.List[object]';$taskResult=Invoke-WsmAdapterRestore $task @{} $null {param($intent)} {param($receipt)$folderReceipts.Add($receipt)}
    if(-not (Test-WsmAdapterConfiguration $task Staged $taskResult.AuxiliaryOwnership).Passed){throw 'Disabled task registration did not verify.'}
    $t=$script:fixtureTasks['\Fixture\FixtureTask'];$old=$t.Xml;$t.Xml=$t.Xml.Replace('IgnoreNew','Parallel');if((Test-WsmAdapterConfiguration $task Staged).Passed){throw 'Task concurrency drift ignored.'};$t.Xml=$old
    Invoke-WsmAdapterActivation $task $true;if(-not (Test-WsmAdapterConfiguration $task Final $taskResult.AuxiliaryOwnership).Passed){throw 'Final task activation did not verify.'};if((Test-WsmAdapterConfiguration $task Staged $taskResult.AuxiliaryOwnership).Passed){throw 'Activated task accepted as staged.'}
    $task.CatchUpPolicy='ReviewRequired';$blocked=$false;try{Assert-WsmMigrationSpec $task}catch{$blocked=$true};if(-not $blocked){throw 'Unreviewed task catch-up policy allowed'}
    $task.Desired.Xml=$task.Desired.Xml.Replace('<MultipleInstancesPolicy>','<StartWhenAvailable>true</StartWhenAvailable><MultipleInstancesPolicy>')
    foreach($policy in @('SkipMissedRuns','DedicatedManualCatchUp')){$task.CatchUpPolicy=$policy;Assert-WsmMigrationSpec $task;$doc=Read-WsmXml (ConvertTo-WsmDisabledTaskXml $task);if($doc.SelectSingleNode("//*[local-name()='StartWhenAvailable']").InnerText -cne 'false'){throw 'Missed task runs remained automatically enabled'}}
    $task.CatchUpPolicy='PreserveSourceSettings';$doc=Read-WsmXml (ConvertTo-WsmDisabledTaskXml $task);if($doc.SelectSingleNode("//*[local-name()='StartWhenAvailable']").InnerText -cne 'true'){throw 'Explicit source catch-up setting was lost'}
    $service=[pscustomobject]@{Adapter='Service';Owner='fixture';Evidence='fixture-reviewed';DesiredFinalState='Automatic';Desired=[pscustomobject]@{Name='FixtureSvc';Supplement=(New-WsmFixtureServiceSupplement);DisplayName='Fixture service';BinaryPathName='C:\Fixture\service.exe';Account='LocalSystem';Dependencies=@();Description='fixture'}}
    Assert-WsmMigrationSpec $service;Invoke-WsmAdapterRestore $service @{} $null | Out-Null;if(-not (Test-WsmAdapterConfiguration $service Staged).Passed){throw 'Disabled service did not verify.'};Invoke-WsmAdapterActivation $service $true;if(-not (Test-WsmAdapterConfiguration $service Final).Passed){throw 'Final service state did not verify.'};$script:fixtureServices.FixtureSvc.PathName='C:\Wrong.exe';if((Test-WsmAdapterConfiguration $service Final).Passed){throw 'Service binary drift ignored.'}
    foreach($account in @('S-1-5-19','NT AUTHORITY\NetworkService')){$builtin=$service.PSObject.Copy();$builtin.Desired=$service.Desired.PSObject.Copy();$builtin.Desired.Name='FixtureBuiltin'+$script:fixtureServices.Count;$builtin.Desired.Account=$account;$builtin.Desired.Description='';Assert-WsmMigrationSpec $builtin;Invoke-WsmAdapterRestore $builtin @{} $null | Out-Null;if(-not (Test-WsmAdapterConfiguration $builtin Staged).Passed){throw 'Builtin service identity or empty description did not restore through actual adapter'}}
    $managed=$service.PSObject.Copy();$managed.Desired=$service.Desired.PSObject.Copy();$managed.Desired.Name='FixtureManaged';$managed.Desired.Account='DOMAIN\fixturemsa$';$managed.Desired.Dependencies=@('FixtureBase','+FixtureGroup');$managed | Add-Member NoteProperty AccountMode 'ManagedServiceAccount';$managed | Add-Member NoteProperty ManagedAccountEvidence 'fixture account retrieval readiness reviewed'
    function script:Test-ADServiceAccount {[CmdletBinding()]param($Identity);$true}
    $script:WsmServiceIdentityNativeCallback={param($Request)if($Request.PasswordPointer -ne [IntPtr]::Zero -or $Request.StartTypeValue -ne 4){throw 'Adapter violated managed NULL password or disabled mode'};$script:fixtureServices[$Request.Name]=[pscustomobject]@{Name=$Request.Name;DisplayName=$Request.DisplayName;PathName=$Request.BinaryPathName;StartMode='Disabled';StartName=$Request.Account;State='Stopped';Description=$Request.Description;Dependencies=@($Request.Dependencies)};[pscustomobject]@{Created=$true}}
    Assert-WsmMigrationSpec $managed;Invoke-WsmAdapterRestore $managed @{} $null | Out-Null;if(-not (Test-WsmAdapterConfiguration $managed Staged).Passed){throw 'Managed service account did not restore through actual typed adapter and injected native boundary'};$script:WsmServiceIdentityNativeCallback=$null
    $feature=[pscustomobject]@{Adapter='WindowsFeature';Owner='fixture';Evidence='fixture-reviewed';Desired=[pscustomobject]@{Name='Web-Server';Source='';IsolationEvidence='fixture isolated maintenance';SideEffects=@()}};$result=Invoke-WsmAdapterRestore $feature @{} $null;if(-not $result.RebootRequired){throw 'Feature reboot result lost.'}
    foreach($exit in @('Success','NoChangeNeeded','SuccessRestart')){function script:Install-WindowsFeature {param($Name,$Source,$ErrorAction)[pscustomobject]@{Success=$true;RestartNeeded='No';ExitCode=$exit}};$result=Invoke-WsmAdapterRestore $feature @{} $null;if($result.NativeResult -cne $exit -or $result.RebootRequired -ne ($exit -ceq 'SuccessRestart')){throw 'Feature native enum or conservative reboot decision lost'}}
    foreach($exit in @('Failed','Unknown','')){function script:Install-WindowsFeature {param($Name,$Source,$ErrorAction)[pscustomobject]@{Success=$true;RestartNeeded='No';ExitCode=$exit}};$blocked=$false;try{Invoke-WsmAdapterRestore $feature @{} $null | Out-Null}catch{$blocked=$true;$details=Get-WsmFailureDetails $_;if($details.NativeResult -cne $exit -or $details.NativeTool -cne 'Install-WindowsFeature'){throw 'Rejected feature result lost native enum'}};if(-not $blocked){throw 'Unknown or failed feature native result accepted'}}
    $bad=$false;try{$feature.Desired.Name='AD-Domain-Services';Assert-WsmAdapterDesired $feature}catch{$bad=$true};if(-not $bad){throw 'Identity role generic installation accepted.'}
    function script:Get-LocalUser {param($Name,$ErrorAction)throw [UnauthorizedAccessException]::new('fixture access denied')}
    $denied=$false;try{Get-WsmAdapterState ([pscustomobject]@{Adapter='LocalUser';Desired=[pscustomobject]@{Name='missing'}}) | Out-Null}catch{$denied=$_.Exception -is [UnauthorizedAccessException]};if(-not $denied){throw 'Local account access denied was treated as absence.'}
    function script:Get-NetFirewallRule {param($Name,$ErrorAction)throw [UnauthorizedAccessException]::new('fixture access denied')}
    $denied=$false;try{Get-WsmAdapterState ([pscustomobject]@{Adapter='FirewallRule';Desired=[pscustomobject]@{Name='missing'}}) | Out-Null}catch{$denied=$_.Exception -is [UnauthorizedAccessException]};if(-not $denied){throw 'Firewall provider access denied was treated as absence.'}
    foreach($path in @('..\escape','folder\\same','folder\','C:\absolute','folder:stream','NUL.txt')){$bad=$false;try{Assert-WsmRelativePath $path}catch{$bad=$true};if(-not $bad){throw 'Unsafe/colliding artifact path accepted.'}}
    if((ConvertTo-WsmWindowsArgument 'a b') -cne '"a b"' -or (ConvertTo-WsmWindowsArgument '') -cne '""' -or (ConvertTo-WsmWindowsArgument 'a"b') -cne '"a\"b"'){throw 'Windows native argument quoting incorrect.'}
    Initialize-WsmNativeReader;$reader=New-Object IO.StringReader(('x'*200000)+'tail');try{$captured=[WsmNativeBoundedReader]::Drain($reader,65536).GetAwaiter().GetResult();if(-not $captured.Truncated -or $captured.Text.Length -ne 65536 -or -not $captured.Text.EndsWith('tail')){throw 'Native output drain was not bounded'}}finally{$reader.Dispose()}
    $script:bootStamp='before';function script:Get-WsmBootStamp {$script:bootStamp};$blocked=$false;try{Assert-WsmRebootCompleted ([pscustomobject]@{BootBefore='before'})}catch{$blocked=$true};if(-not $blocked){throw 'Required installer reboot bypassed'};$script:bootStamp='after';Assert-WsmRebootCompleted ([pscustomobject]@{BootBefore='before'})
    Write-Host 'PASS: task disabled at registration, Settings drift, activation/staging separation, service creation/binary/final state, feature reboot, protected role, path collisions and native quoting.'
}
