#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$script:ToolVersion='0.4.0'
. (Join-Path $PSScriptRoot 'ExternalReadinessEvidenceFixtures.ps1')
$formSource=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\src\AssistiveReviewForms.ps1'))
& $module {param($path) . $path;foreach($function in @(Get-Command -CommandType Function | Where-Object {$_.Name -match '^(Get-WsmAssistiveReviewItem|ConvertTo-WsmAssistiveSafeValue|Get-WsmAssistiveSafeIisChanges|Get-WsmAssistiveSpecReview|Set-WsmAssistiveReviewXmlValue|Set-WsmAssistiveIisConfigReview|Submit-WsmAssistiveSpecReview|Export-WsmAssistiveTargetDecisionReceipt)$'})){Set-Item -Path ('Function:\script:'+ $function.Name) -Value $function.ScriptBlock}} $formSource
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-review-forms-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
$passed=0
function Check([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message};$script:passed++}
function Reject([scriptblock]$Action,[string]$Message){$rejected=$false;try{& $Action | Out-Null}catch{$rejected=$true};Check $rejected $Message}
function SaveJson($Data,[string]$Name){$path=Join-Path $root $Name;[IO.File]::WriteAllText($path,($Data|ConvertTo-Json -Depth 40),(New-Object Text.UTF8Encoding($false)));$path}
function CallModule([scriptblock]$Block,[object[]]$Arguments=@()){& $script:module $Block @Arguments}
try {
    $source=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=('a'*64);Name='review-fixture-source'}
    $runtime=CallModule {param($host) New-WsmItem $host Runtime App 'Fixture runtime' 'fixture-runtime' @{Version='1.0'}} @($source.HostId)
    $xml='<Task><Principals><Principal><UserId>DOMAIN\service</UserId></Principal></Principals><Triggers/><Actions><Exec><Command>C:\private\job.exe</Command><Arguments>--password hidden-value</Arguments><WorkingDirectory>C:\private</WorkingDirectory></Exec></Actions><Settings><Enabled>true</Enabled></Settings></Task>'
    $taskSecurity=CallModule {param($sddl) $folders=@(Get-WsmTaskSecurityFolderAncestors '\Fixture\' | ForEach-Object {[pscustomobject]@{Path=$_;SecuritySddl=$sddl;SecurityHash=(Get-WsmHashText $sddl)}});[pscustomobject]@{TaskSecurityCapture=[pscustomobject]@{Kind='TaskSecurityCapture';SchemaVersion=1;TaskName='Job';TaskPath='\Fixture\';TaskFullPath='\Fixture\Job';TaskSecuritySddl=$sddl;TaskSecurityHash=(Get-WsmHashText $sddl);Folders=$folders};TaskSecurityCaptureStatus='Captured'}} @('O:SYG:SYD:(A;;FA;;;SY)')
    $taskSettings=@{TaskName='Job';TaskPath='\Fixture\';Xml=$xml;TaskSecurityCapture=$taskSecurity.TaskSecurityCapture;TaskSecurityCaptureStatus=$taskSecurity.TaskSecurityCaptureStatus}
    $task=CallModule {param($host,$settings) New-WsmItem $host Tasks ScheduledTask 'Fixture task' '\Fixture\Job' $settings} @($source.HostId,$taskSettings)
    $iisXml='<site name="FixtureSite" id="1" serverAutoStart="true"><bindings><binding protocol="http" bindingInformation="*:8080:fixture.example" certificateHash="" certificateStoreName="" sslFlags="0" /></bindings><application path="/" applicationPool="FixturePool"><virtualDirectory path="/" physicalPath="C:\Sites\Fixture" /></application></site>'
    $iisSite=CallModule {param($host,$xml) New-WsmItem $host Web IISSite 'Fixture IIS site' 'FixtureSite' @{Xml=$xml;ConfigurationFile='fixture applicationHost.config';CaptureScope='Site and nested applications/virtual directories';StartupConfiguration=[pscustomobject]@{Enabled='Unknown';SourceAutoStart='Unknown'};ObservedRuntime=[pscustomobject]@{State='NotObserved';Evidence='isolated fixture'}}} @($source.HostId,$iisXml)
    $iisPoolXml='<add name="FixturePool" managedRuntimeVersion="v4.0" managedPipelineMode="Integrated" enable32BitAppOnWin64="false" startMode="OnDemand" queueLength="1000" autoStart="false" />'
    $iisPool=CallModule {param($host,$xml) New-WsmItem $host Web IISPool 'Fixture IIS pool' 'FixturePool' @{Xml=$xml;ConfigurationFile='fixture applicationHost.config';CaptureScope='Application pool';StartupConfiguration=[pscustomobject]@{Enabled='Unknown';SourceAutoStart='Unknown'};ObservedRuntime=[pscustomobject]@{State='NotObserved';Evidence='isolated fixture'}}} @($source.HostId,$iisPoolXml)
    $inventory=CallModule {param($source,$items) New-WsmInventory $source 1 $items} @($source,@($runtime,$task,$iisSite,$iisPool))
    $inventory | Add-Member NoteProperty SoftwareCatalog (CallModule {param($inv) $software=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion='0.4.0';Kind='SoftwareCatalog';Source=[pscustomobject][ordered]@{HostId=$inv.Source.HostId;Fingerprint=$inv.Source.Fingerprint;Name=$inv.Source.Name;InventoryRevision=[int]$inv.Revision;InventoryProjectionHash=(Get-WsmSoftwareInventoryProjectionHash $inv)};CaptureContext=[pscustomobject][ordered]@{CapturedUtc=(Get-WsmUtc);CaptureIdentity='fixture';AccountContext='Unknown';CaptureHost='fixture';PowerShellVersion='5.1';RequestedPortableRoots=@()};Entries=@();Coverage=@([pscustomobject][ordered]@{Probe='Uninstall';Scope='Machine';SID='';View='Registry64';Status='Success';EvidenceKind='Registry';Count=0;Budget=[pscustomobject]@{MaxEntries=100};ErrorKind=$null;ObservedUtc='2026-10-10T00:00:00Z'});PreparationRequirements=@();CatalogProjectionHash=('0'*64)};$software.CatalogProjectionHash=Get-WsmSoftwareCatalogProjectionHash $software;Assert-WsmSoftwareCatalog $software -SourceInventory $inv | Out-Null;$software} @($inventory)) -Force
    $inventory | Add-Member NoteProperty WorkloadDiscovery (CallModule {param($inv) Get-WsmWorkloadDiscovery $inv} @($inventory)) -Force
    $inventoryPath=SaveJson $inventory 'source-inventory.json';$inventoryHash=(Get-FileHash -LiteralPath $inventoryPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $workspace=Join-Path $root 'manager';CallModule {param($path) Initialize-WsmWorkspace $path | Out-Null} @($workspace)
    $catalog=CallModule {param($w,$path,$hash) Import-WsmInventory $w $path $hash 'review target'} @($workspace,$inventoryPath,$inventoryHash)
    $catalog=CallModule {param($w,$pair,$revision) Enable-WsmAssistiveMode $w $pair $revision} @($workspace,$catalog.PairId,$catalog.DecisionRevision)

    $review=CallModule {param($w,$pair,$id) Get-WsmAssistiveSpecReview $w $pair $id} @($workspace,$catalog.PairId,$runtime.ItemId)
    Check ($review.RawXmlIncluded -eq $false -and $review.SecretsIncluded -eq $false -and $review.Adapter -eq 'ManualWorkflow') 'Safe form projection included protected material or lost typed adapter.'
    Check (-not ($review | ConvertTo-Json -Depth 30 -Compress).Contains('hidden-value') -and -not ($review | ConvertTo-Json -Depth 30 -Compress).Contains('<Task>')) 'Safe form projection leaked raw XML or a task secret.'
    Reject {CallModule {param($w,$pair,$id) Get-WsmAssistiveSpecReview $w $pair $id} @($workspace,$catalog.PairId,('0'*64))} 'Unknown review item was accepted.'
    Reject {CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$owner,$evidence,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner $owner -Evidence $evidence -Fields $fields} @($workspace,$catalog.PairId,$runtime.ItemId,$catalog.DecisionRevision,($catalog.Assistive.Revision-1),$catalog.Assistive.Selections.Revision,'owner','reviewed fixture',@{})} 'Stale Assistive revision CAS was accepted.'
    Reject {CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner 'owner' -Evidence 'reviewed fixture' -Fields $fields} @($workspace,$catalog.PairId,$runtime.ItemId,$catalog.DecisionRevision,$catalog.Assistive.Revision,$catalog.Assistive.Selections.Revision,@{Unexpected='unsafe arbitrary spec injection'})} 'Unknown untyped specification field was accepted.'
    Reject {CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner 'owner' -Evidence 'reviewed fixture' -Fields $fields} @($workspace,$catalog.PairId,$runtime.ItemId,$catalog.DecisionRevision,$catalog.Assistive.Revision,$catalog.Assistive.Selections.Revision,@{SourcePath='C:\outside-discovery'})} 'Unreviewed source scope field was accepted.'
    $saved=CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner 'fixture owner' -Evidence 'Reviewed runtime disposition and procedure' -Fields $fields} @($workspace,$catalog.PairId,$runtime.ItemId,$catalog.DecisionRevision,$catalog.Assistive.Revision,$catalog.Assistive.Selections.Revision,@{Product='Fixture runtime';Procedure='Owner installs and verifies runtime'})
    Check ([IO.File]::Exists($saved.SpecPath) -and (Get-FileHash -LiteralPath $saved.SpecPath -Algorithm SHA256).Hash -ieq $saved.SpecHash -and $saved.RawXmlReturned -eq $false) 'Typed spec form did not save a protected integrity-bound artifact.'
    $after=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId)
    Check ($after.DecisionRevision -eq ($catalog.DecisionRevision+1) -and $after.Items.Where({$_.ItemId -ceq $runtime.ItemId})[0].MigrationSpec.Evidence -eq 'Reviewed runtime disposition and procedure') 'Typed spec submission bypassed or failed normal catalog mutation/CAS behavior.'

    $taskReview=CallModule {param($w,$pair,$id) Get-WsmAssistiveSpecReview $w $pair $id} @($workspace,$catalog.PairId,$task.ItemId)
    Check ($taskReview.WorkloadActions.Count -eq 1 -and $taskReview.WorkloadActions[0].ValuesWithheld -and -not ($taskReview | ConvertTo-Json -Depth 30 -Compress).Contains('hidden-value')) 'Task form did not expose a redacted action shape.'
    $selected=CallModule {param($w,$pair,$id,$revision) Set-WsmDecision -Workspace $w -PairId $pair -ItemId $id -Decision Include -Reason 'reviewed fixture workload' -ExpectedRevision $revision} @($workspace,$catalog.PairId,$task.ItemId,$after.DecisionRevision)
    $catalog=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId)
    $fields=@{WorkloadFieldReviews=@([pscustomobject]@{FieldPointer='Task/Actions/Action[0]/Command';Value='C:\target\job.exe'},[pscustomobject]@{FieldPointer='Task/Actions/Action[0]/Arguments';Value='--mode reviewed'},[pscustomobject]@{FieldPointer='Task/Actions/Action[0]/WorkingDirectory';Value='C:\target'});CatchUpPolicy='SkipMissedRuns';ActivationOwner='task owner';ActivationReason='Reviewed target execution remains disabled until cutover.';DesiredFinalState='Disabled'}
    Reject {CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner 'task owner' -Evidence 'reviewed fields' -Fields $fields} @($workspace,$catalog.PairId,$task.ItemId,$catalog.DecisionRevision,$catalog.Assistive.Revision,$catalog.Assistive.Selections.Revision,@{WorkloadFieldReviews=@([pscustomobject]@{FieldPointer='Task/Actions/Action[0]/Command';Value='C:\target\job.exe'});ActivationOwner='task owner';ActivationReason='Review reason';DesiredFinalState='Enabled'})} 'Incomplete task action review or unsafe activation was accepted.'
    $taskSaved=CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner 'task owner' -Evidence 'Typed target command and opaque arguments reviewed' -Fields $fields} @($workspace,$catalog.PairId,$task.ItemId,$catalog.DecisionRevision,$catalog.Assistive.Revision,$catalog.Assistive.Selections.Revision,$fields)
    $taskCatalog=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId);$taskSpec=@($taskCatalog.Items|Where-Object ItemId -CEQ $task.ItemId)[0].MigrationSpec
    Check ($taskSpec.DesiredFinalState -eq 'Disabled' -and $taskSpec.StagedDisabled -and $taskSpec.Desired.Xml -match '<Command>C:\\target\\job.exe</Command>' -and $taskSpec.Desired.Xml -match '<Arguments>--mode reviewed</Arguments>' -and $taskSpec.Desired.Xml -match '<WorkingDirectory>C:\\target</WorkingDirectory>' -and $taskSpec.ReviewedActivation.Owner -eq 'task owner') 'Typed task action reviews did not create a staged disabled target XML from protected source.'
    Check ([IO.File]::Exists($taskSaved.SpecPath) -and $taskSaved.SpecHash -match '^[a-f0-9]{64}$') 'Typed task review did not persist a protected spec artifact.'

    $siteReview=CallModule {param($w,$pair,$id) Get-WsmAssistiveSpecReview $w $pair $id} @($workspace,$catalog.PairId,$iisSite.ItemId)
    $siteProjection=$siteReview|ConvertTo-Json -Depth 30 -Compress
    Check ($siteReview.Adapter -eq 'IISSite' -and $siteReview.TypedFields.IisBindings.Count -eq 1 -and $siteReview.TypedFields.IisBindings[0].Index -eq 0 -and $siteReview.TypedFields.IisBindings[0].BindingInformation -ceq '*:8080:fixture.example' -and $siteReview.TypedFields.IisBindings[0].CertificateStoreName -ceq '' -and $siteReview.TypedFields.IisApplicationPools.Count -eq 1 -and $siteReview.TypedFields.IisApplicationPools[0].ApplicationPath -ceq '/' -and $siteReview.TypedFields.IisApplicationPools[0].PoolName -ceq 'FixturePool') 'IIS site review projection did not expose exact safe typed binding/application rows including the captured empty store value.'
    Check (-not $siteProjection.Contains('<site') -and -not $siteProjection.Contains('applicationHost.config') -and -not $siteProjection.Contains('private-key-secret')) 'IIS site form projection leaked raw XML or protected source metadata.'
    $catalog=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId)
    $siteSelected=CallModule {param($w,$pair,$id,$revision) Set-WsmDecision -Workspace $w -PairId $pair -ItemId $id -Decision Include -Reason 'reviewed IIS fixture' -ExpectedRevision $revision} @($workspace,$catalog.PairId,$iisSite.ItemId,$catalog.DecisionRevision)
    $catalog=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId)
    $iisFields=@{IisBindings=@($siteReview.TypedFields.IisBindings);IisApplicationPools=@($siteReview.TypedFields.IisApplicationPools);WorkloadFieldReviews=@([pscustomobject]@{FieldPointer='IIS/site/FixtureSite/application[0]/virtualDirectory[0]/@physicalPath';Value='C:\Sites\Fixture'});ActivationOwner='IIS owner';ActivationReason='Keep the reviewed site staged disabled until the owner approves cutover.';DesiredFinalState='Disabled'}
    $badIisFields=@{IisBindings=@([pscustomobject]@{Index=1;Protocol='http';BindingInformation='*:8080:fixture.example';CertificateHash='';CertificateStoreName='';SslFlags='0'});IisApplicationPools=@($siteReview.TypedFields.IisApplicationPools);WorkloadFieldReviews=@([pscustomobject]@{FieldPointer='IIS/site/FixtureSite/application[0]/virtualDirectory[0]/@physicalPath';Value='C:\Sites\Fixture'});ActivationOwner='IIS owner';ActivationReason='Reviewed site mapping';DesiredFinalState='Disabled'}
    Reject {CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner 'IIS owner' -Evidence 'Reviewed captured site binding and application mapping' -Fields $fields} @($workspace,$catalog.PairId,$iisSite.ItemId,$catalog.DecisionRevision,$catalog.Assistive.Revision,$catalog.Assistive.Selections.Revision,$badIisFields)} 'IIS typed review accepted an edited source-row index.'
    $siteSaved=CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner 'IIS owner' -Evidence 'Reviewed captured site binding and application mapping' -Fields $fields} @($workspace,$catalog.PairId,$iisSite.ItemId,$catalog.DecisionRevision,$catalog.Assistive.Revision,$catalog.Assistive.Selections.Revision,$iisFields)
    $catalog=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId);$savedSite=@($catalog.Items|Where-Object ItemId -CEQ $iisSite.ItemId)[0].MigrationSpec
    Check ($savedSite.Adapter -eq 'IISSite' -and $savedSite.Desired.Xml -match 'bindingInformation="\*:8080:fixture.example"' -and $savedSite.Desired.Xml -match 'applicationPool="FixturePool"' -and [IO.File]::Exists($siteSaved.SpecPath) -and -not $siteSaved.RawXmlReturned) 'IIS site review did not persist the exact typed site fields as a protected spec artifact.'
    $siteExcluded=CallModule {param($w,$pair,$id,$revision) Set-WsmDecision -Workspace $w -PairId $pair -ItemId $id -Decision Exclude -Reason 'isolated IIS site is reviewed separately from this migration plan fixture' -ExpectedRevision $revision} @($workspace,$catalog.PairId,$iisSite.ItemId,$catalog.DecisionRevision)
    $poolReview=CallModule {param($w,$pair,$id) Get-WsmAssistiveSpecReview $w $pair $id} @($workspace,$catalog.PairId,$iisPool.ItemId)
    $poolKeys=@($poolReview.TypedFields.IisPoolSettings.PSObject.Properties.Name | Sort-Object)
    Check (($poolKeys -join '|') -ceq 'enable32BitAppOnWin64|managedPipelineMode|managedRuntimeVersion|queueLength|startMode' -and $poolReview.TypedFields.IisPoolSettings.managedRuntimeVersion -ceq 'v4.0' -and $poolReview.TypedFields.IisPoolSettings.startMode -ceq 'OnDemand') 'IIS pool review prefill included non-editable identity/activation values or omitted supported typed settings.'
    $catalog=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId)
    $poolSettingMap=@{};foreach($property in $poolReview.TypedFields.IisPoolSettings.PSObject.Properties){$poolSettingMap[$property.Name]=$property.Value}
    $poolFields=@{IisPoolSettings=$poolSettingMap;ActivationOwner='IIS pool owner';ActivationReason='Keep the reviewed pool staged disabled until the owner approves activation.';DesiredFinalState='Disabled'}
    $poolSaved=CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner 'IIS pool owner' -Evidence 'Reviewed safe IIS pool settings' -Fields $fields} @($workspace,$catalog.PairId,$iisPool.ItemId,$catalog.DecisionRevision,$catalog.Assistive.Revision,$catalog.Assistive.Selections.Revision,$poolFields)
    $catalog=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId);$savedPool=@($catalog.Items|Where-Object ItemId -CEQ $iisPool.ItemId)[0].MigrationSpec
    Check ($savedPool.Desired.Xml -match 'managedRuntimeVersion="v4.0"' -and $savedPool.Desired.Xml -match 'queueLength="1000"' -and [IO.File]::Exists($poolSaved.SpecPath)) 'IIS pool typed settings did not produce a protected reviewed spec.'
    $poolExcluded=CallModule {param($w,$pair,$id,$revision) Set-WsmDecision -Workspace $w -PairId $pair -ItemId $id -Decision Exclude -Reason 'isolated IIS pool is reviewed separately from this migration plan fixture' -ExpectedRevision $revision} @($workspace,$catalog.PairId,$iisPool.ItemId,$catalog.DecisionRevision)

    $iisSource='<access sslFlags="None"><rule name="private-fixture-key" enabled="true" /></access>'
    $iisSpec=[pscustomobject]@{Adapter='IISSection';Owner='IIS owner';Evidence='Typed IIS fixture review';SourceXml=$iisSource;SourceAutoStart='Unknown';StagedDisabled=$true;DesiredFinalState='Disabled';ActivationPolicyFieldPointer="/access/rule[@name='private-fixture-key']/@enabled";ReviewedActivation=$null;Desired=[pscustomobject]@{SectionPath='system.webServer/security/access';LocationPath='';Xml=$iisSource;Changes=@()}}
    $iisChanges=@([pscustomobject][ordered]@{FieldPointer='/access/@sslFlags';Operation='SetAttribute';ElementName='access';KeyAttributes=@();AttributeName='sslFlags';BeforeValue='None';AfterValue='Sni'},[pscustomobject][ordered]@{FieldPointer="/access/rule[@name='private-fixture-key']/@enabled";Operation='SetAttribute';ElementName='rule';KeyAttributes=@([pscustomobject]@{Name='name';Value='private-fixture-key'});AttributeName='enabled';BeforeValue='true';AfterValue='false'})
    CallModule {param($spec,$changes) Set-WsmAssistiveIisConfigReview $spec @{ActivationPolicyFieldPointer=$spec.ActivationPolicyFieldPointer;IisConfigChanges=$changes;DesiredFinalState='Enabled';ActivationOwner='IIS owner';ActivationReason='Keep the staged rule disabled until its business owner approves activation.'}} @($iisSpec,$iisChanges)
    CallModule {param($spec) Assert-WsmMigrationSpec $spec -Assistive} @($iisSpec)
    $iisPublicRows=& $module {param($spec) @(Get-WsmAssistiveSafeIisChanges $spec.Desired.Changes)} $iisSpec
    $iisProjection=ConvertTo-Json -InputObject $iisPublicRows -Depth 15 -Compress
    Check ($iisSpec.ReviewedActivation.FieldPointer -ceq $iisSpec.ActivationPolicyFieldPointer -and $iisSpec.ReviewedActivation.StagedValue -ceq 'false' -and $iisSpec.Desired.Xml -match 'sslFlags="Sni"' -and $iisPublicRows.Count -eq 2 -and -not $iisProjection.Contains('private-fixture-key') -and -not $iisProjection.Contains('BeforeValue":"None')) ('IIS section form failed: '+$iisProjection+'; projectedCount='+$iisPublicRows.Count+'; desiredChanges='+@($iisSpec.Desired.Changes).Count+'; staged='+[string]$iisSpec.ReviewedActivation.StagedValue+'; desired='+[string]$iisSpec.Desired.Xml)
    $badIisRows=@($iisChanges);$badIisRows[0]=$iisChanges[0].PSObject.Copy();$badIisRows[0].AttributeName='protocol'
    Reject {CallModule {param($spec,$changes) Set-WsmAssistiveIisConfigReview $spec @{ActivationPolicyFieldPointer=$spec.ActivationPolicyFieldPointer;IisConfigChanges=$changes;ActivationOwner='IIS owner';ActivationReason='Reviewed activation owner reason.'}} @($iisSpec,$badIisRows)} 'Mismatched IIS typed row attribute/pointer was accepted.'

    $taskCatalog=CallModule {param($w,$pair,$revision) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId)
    $principalFields=@{PrincipalUser='DOMAIN\target-service';ActivationOwner='task owner';ActivationReason='Keep target task disabled while business owner verifies the new principal.';DesiredFinalState='Disabled'}
    $principalSaved=CallModule {param($w,$pair,$id,$decision,$assistive,$selection,$fields) Submit-WsmAssistiveSpecReview -Workspace $w -PairId $pair -ItemId $id -ExpectedDecisionRevision $decision -ExpectedAssistiveRevision $assistive -ExpectedSelectionRevision $selection -Owner 'task owner' -Evidence 'Reviewed task principal' -Fields $fields} @($workspace,$taskCatalog.PairId,$task.ItemId,$taskCatalog.DecisionRevision,$taskCatalog.Assistive.Revision,$taskCatalog.Assistive.Selections.Revision,$principalFields)
    $principalCatalog=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId);$principalSpec=@($principalCatalog.Items|Where-Object ItemId -CEQ $task.ItemId)[0].MigrationSpec
    Check ($principalSpec.Desired.Xml -match '<UserId>DOMAIN\\target-service</UserId>' -and $principalSpec.Desired.User -ceq 'DOMAIN\target-service') 'PrincipalUser-only review did not update the protected desired task XML.'

    $taskCatalog=CallModule {param($w,$pair,$id,$revision) Set-WsmDecision -Workspace $w -PairId $pair -ItemId $id -Decision Exclude -Reason 'task folder dependency is a separate manual fixture scope' -ExpectedRevision $revision} @($workspace,$catalog.PairId,$task.ItemId,$principalCatalog.DecisionRevision)
    $taskCatalog=CallModule {param($w,$pair,$id,$revision) Set-WsmDecision -Workspace $w -PairId $pair -ItemId $id -Decision Include -Reason 'reviewed runtime item selected for subset fixture' -ExpectedRevision $revision} @($workspace,$catalog.PairId,$runtime.ItemId,$taskCatalog.DecisionRevision)
    $target=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=('b'*64);Name='review-fixture-target'}
    $identity=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion='0.4.0';Kind='TargetIdentity';HostId=$target.HostId;Fingerprint=$target.Fingerprint;Name=$target.Name;OS='Windows Server';Version='2025';CreatedUtc='2026-10-10T00:00:00Z'}
    $identityPath=SaveJson $identity 'target-identity.json';$identityHash=(Get-FileHash -LiteralPath $identityPath -Algorithm SHA256).Hash.ToLowerInvariant();$planPath=Join-Path $root 'sealed-plan.json'
    $openReview=CallModule {param($w,$pair) @(Get-WsmReviewIssues $w $pair | Where-Object Gate -EQ ReviewComplete)} @($workspace,$catalog.PairId);if($openReview.Count){throw ('Fixture plan has incomplete review: '+(($openReview | ForEach-Object {([string]$_.ItemId)+':'+[string]$_.Issue}) -join '; '))}
    $approval=CallModule {param($w,$pair,$targetPath,$hash,$path,$revision) Approve-WsmMigrationPlan -Workspace $w -PairId $pair -TargetIdentityPath $targetPath -TargetIdentityHash $hash -Path $path -ExpectedRevision $revision -PilotAcknowledgement 'ISOLATED-PILOT'} @($workspace,$catalog.PairId,$identityPath,$identityHash,$planPath,$taskCatalog.DecisionRevision)
    $sealed=CallModule {param($path,$hash) Read-WsmMigrationPlan $path $hash} @($approval.Path,$approval.SHA256)
    Reject {CallModule {param($path,$hash,$selection) New-WsmAssistiveTargetDecisionReceipt -PlanPath $path -PlanHash $hash -ManifestHash ('c'*64) -Generation 1 -TargetSnapshotHash ('d'*64) -ComparisonRevision 1 -SelectionRevision $selection -Decision RestoreNow -Owner 'target owner' -Reason 'reviewed target subset' -SelectedItemIds @(('0'*64)) -Comparison ([pscustomobject]@{})} @($approval.Path,$approval.SHA256,$sealed.Assistive.SourceSelectionsVersion)} 'Target receipt accepted an item outside the sealed approved subset.'

    $targetInventory=CallModule {param($host) New-WsmInventory $host 1 @()} @($target)
    $targetInventory | Add-Member NoteProperty SoftwareCatalog (CallModule {param($inv) $software=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion='0.4.0';Kind='SoftwareCatalog';Source=[pscustomobject][ordered]@{HostId=$inv.Source.HostId;Fingerprint=$inv.Source.Fingerprint;Name=$inv.Source.Name;InventoryRevision=[int]$inv.Revision;InventoryProjectionHash=(Get-WsmSoftwareInventoryProjectionHash $inv)};CaptureContext=[pscustomobject][ordered]@{CapturedUtc=(Get-WsmUtc);CaptureIdentity='fixture';AccountContext='Unknown';CaptureHost='fixture';PowerShellVersion='5.1';RequestedPortableRoots=@()};Entries=@();Coverage=@([pscustomobject][ordered]@{Probe='Uninstall';Scope='Machine';SID='';View='Registry64';Status='Success';EvidenceKind='Registry';Count=0;Budget=[pscustomobject]@{MaxEntries=100};ErrorKind=$null;ObservedUtc='2026-10-10T00:00:00Z'});PreparationRequirements=@();CatalogProjectionHash=('0'*64)};$software.CatalogProjectionHash=Get-WsmSoftwareCatalogProjectionHash $software;Assert-WsmSoftwareCatalog $software -SourceInventory $inv | Out-Null;$software} @($targetInventory)) -Force
    $targetInventoryPath=SaveJson $targetInventory 'target-final.json';$targetInventoryHash=(Get-FileHash -LiteralPath $targetInventoryPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $catalog=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId)
    $catalog=CallModule {param($w,$pair,$path,$hash,$revision) Update-WsmAssistiveTargetSnapshot $w $pair $path $hash $revision} @($workspace,$catalog.PairId,$targetInventoryPath,$targetInventoryHash,$catalog.Assistive.Revision)
    $comparison=CallModule {param($w,$pair,$revision) Update-WsmAssistiveComparison $w $pair $revision} @($workspace,$catalog.PairId,$catalog.Assistive.Revision)
    $sourceState=Join-Path $root 'source-state';$packages=Join-Path $root 'packages';[void][IO.Directory]::CreateDirectory($sourceState)
    CallModule {param($inventoryPath,$fingerprint) $script:fixtureInventoryPath=$inventoryPath;$script:fixtureFingerprint=$fingerprint;function script:Get-WsmMachineIdentity {[pscustomobject]@{Fingerprint=$script:fixtureFingerprint;Name='fixture';OS='Fixture Server';Version='10.0.fixture';IsServer=$true;Administrator=$true;Is64Bit=$true}};function script:Export-WsmInventory {param($OutputDirectory)[pscustomobject]@{Path=$script:fixtureInventoryPath;SHA256=(Get-FileHash -LiteralPath $script:fixtureInventoryPath).Hash}};function script:Get-WsmSourceRuntime {param($Item)[pscustomobject]@{Running=$false}}} @($inventoryPath,$source.Fingerprint)
    $package=CallModule {param($plan,$hash,$state,$output) Export-WsmMigrationPackage $plan $hash $state $output -ChunkBytes 65536} @($approval.Path,$approval.SHA256,$sourceState,$packages)
    $approvedPlan=CallModule {param($path,$hash) Read-WsmMigrationPlan $path $hash} @($approval.Path,$approval.SHA256)
    $freezeProof=New-WsmSourceFreezeEvidenceFixture -Plan $approvedPlan -PlanHash $approval.SHA256 -Root $root -Owner 'fixture source owner'
    $freezePath=Join-Path $root 'freeze.json';try{$freeze=CallModule {param($plan,$hash,$path,$state,$proof) Export-WsmFreezeRecord $plan $hash $path 'fixture source owner' 'isolated fixture writer fence' OWNER-CONFIRMED-QUIESCENCE -SourceStateDirectory $state -FreezeExternalEvidencePath $proof.Path -FreezeExternalEvidenceHash $proof.SHA256 -FreezeEpoch $proof.FreezeEpoch} @($approval.Path,$approval.SHA256,$freezePath,$sourceState,$freezeProof)}catch{Write-Host ('Freeze fixture detail: '+$_.Exception.InnerException.Message);throw}
    $finalPackage=CallModule {param($plan,$hash,$state,$output,$basePath,$baseHash,$freezePath,$freezeHash,$proof) Export-WsmMigrationPackage $plan $hash $state $output -ChunkBytes 65536 -BaseManifestPath $basePath -BaseManifestHash $baseHash -FreezePath $freezePath -FreezeHash $freezeHash -FreezeExternalEvidencePath $proof.Path -FreezeExternalEvidenceHash $proof.SHA256} @($approval.Path,$approval.SHA256,$sourceState,$packages,$package.ManifestPath,$package.SHA256,$freezePath,$freeze.SHA256,$freezeProof)
    Check ($package.Sealed -and $package.Files -eq 0 -and $finalPackage.Final -and (CallModule {param($path,$hash) (Test-WsmMigrationPackage $path $hash).Valid} @($finalPackage.ManifestPath,$finalPackage.SHA256))) 'Zero-C fixture did not produce a complete verified final migration package.'
    $latest=CallModule {param($w,$pair) Get-WsmCatalog $w $pair} @($workspace,$catalog.PairId)
    $currentSelection=CallModule {param($c) Get-WsmAssistiveCurrentSelections $c} @($latest);$approvedIds=@{};foreach($id in $sealed.Assistive.ApprovedItemIds){$approvedIds[[string]$id]=$true};$selectedIds=@($currentSelection.Items|Where-Object {$_.Selected -and $approvedIds.ContainsKey([string]$_.ItemId)}|ForEach-Object {[string]$_.ItemId})
    $exportArgs=@{Workspace=$workspace;PairId=$catalog.PairId;PlanPath=$approval.Path;PlanHash=$approval.SHA256;ManifestPath=$finalPackage.ManifestPath;ManifestHash=$finalPackage.SHA256;Generation=$finalPackage.Generation;TargetSnapshotHash=$targetInventoryHash;ComparisonRevision=$latest.Assistive.Comparison.Revision;SelectionRevision=$sealed.Assistive.SourceSelectionsVersion;Decision='RestoreNow';Owner='fixture target owner';Reason='Owner reviewed the verified final target comparison.';SelectedItemIds=$selectedIds;ExpectedDecisionRevision=$latest.DecisionRevision}
    $receipt=CallModule {param($arguments) Export-WsmAssistiveTargetDecisionReceipt @arguments} @($exportArgs)
    $receiptRecord=CallModule {param($path,$hash) Assert-WsmAssistiveTargetDecisionReceipt (Read-WsmTrustedJson $path $hash)} @($receipt.ReceiptPath,$receipt.ReceiptHash)
    Check ($receiptRecord -and $receipt.SelectedItemIds.Count -eq $selectedIds.Count -and $receipt.SelectedItemIds -join '|' -ceq ($selectedIds|Sort-Object) -join '|' ) 'Target receipt export did not preserve the exact current selected subset.'
    $receiptData=CallModule {param($path,$hash) Read-WsmTrustedJson $path $hash} @($receipt.ReceiptPath,$receipt.ReceiptHash)
    Check ($receiptData.ComparisonHash -eq (CallModule {param($value) Get-WsmHashText ($value|ConvertTo-Json -Depth 100 -Compress)} @($latest.Assistive.Comparison)) -and $receiptData.Comparison.Revision -eq $latest.Assistive.Comparison.Revision) 'Exported target receipt omitted its integrity-bound comparison snapshot.'
    $staleComparison=$exportArgs.Clone();$staleComparison.ComparisonRevision--
    Reject {CallModule {param($arguments) Export-WsmAssistiveTargetDecisionReceipt @arguments} @($staleComparison)} 'Target receipt accepted a stale comparison revision.'
    $staleSnapshot=$exportArgs.Clone();$staleSnapshot.TargetSnapshotHash='e'*64
    Reject {CallModule {param($arguments) Export-WsmAssistiveTargetDecisionReceipt @arguments} @($staleSnapshot)} 'Target receipt accepted a stale target snapshot.'
    $wrongSelection=$exportArgs.Clone();$wrongSelection.SelectedItemIds=@()
    Reject {CallModule {param($arguments) Export-WsmAssistiveTargetDecisionReceipt @arguments} @($wrongSelection)} 'Target receipt accepted a selection that differs from current target choices.'
    $tamperedManifest=Join-Path $root 'tampered-manifest.json';[IO.File]::WriteAllText($tamperedManifest,(Get-Content -LiteralPath $finalPackage.ManifestPath -Raw).Replace($finalPackage.SHA256,'0'*64),(New-Object Text.UTF8Encoding($false)));$tampered=$exportArgs.Clone();$tampered.ManifestPath=$tamperedManifest
    Reject {CallModule {param($arguments) Export-WsmAssistiveTargetDecisionReceipt @arguments} @($tampered)} 'Target receipt accepted a tampered final package manifest.'

    Write-Host ('PASS: '+$passed+' Assistive review form checks.')
} finally {Remove-Item -LiteralPath $root -Recurse -Force}
