#requires -Version 5.1
$ErrorActionPreference='Stop'
$repo=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-native-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
$fixturePid=$null;$grandchildPid=$null
try {
    $helperPath=Join-Path $root 'native-helper.ps1';$tokenPath=Join-Path $root 'token.json'
    $helperLines=@(
        'param([string]$Repo,[string]$Mode,[string]$ReadyPath,[string]$GrandchildPidPath,[string]$TokenPath)',
        '$ErrorActionPreference=''Stop'';[IO.File]::WriteAllText($ReadyPath,([string]$PID+''|''+[string][DateTime]::UtcNow.Ticks))',
        'if($Mode -eq ''Burst''){for($i=0;$i -lt 512;$i++){[Console]::Out.Write((''SECRET-OUT-''+(''x''*2048)));[Console]::Error.Write((''SECRET-ERR-''+(''y''*2048)))};exit 0}',
        'if($Mode -eq ''Silent''){Start-Sleep -Seconds 6;exit 0}',
        'if($Mode -eq ''HungPipe''){$exe=[Diagnostics.Process]::GetCurrentProcess().MainModule.FileName;$si=New-Object Diagnostics.ProcessStartInfo;$si.FileName=$exe;$si.Arguments=''-NoProfile -Command Start-Sleep -Seconds 15'';$si.UseShellExecute=$false;$si.CreateNoWindow=$true;$child=[Diagnostics.Process]::Start($si);[IO.File]::WriteAllText($GrandchildPidPath,[string]$child.Id);[Console]::Out.Write(''SECRET-PARENT-OUTPUT'');[Console]::Error.Write(''SECRET-PARENT-ERROR'');exit 0}',
        'if($Mode -eq ''Cancel''){. (Join-Path $Repo ''src\Core.ps1'');. (Join-Path $Repo ''src\MigrationContracts.ps1'');. (Join-Path $Repo ''src\Cancellation.ps1'');function Protect-WsmDirectory([string]$Path){$t=Read-WsmJson $TokenPath;$expected=Join-Path $t.StateDirectory $t.PairId;if([IO.Path]::GetFullPath($Path) -ine [IO.Path]::GetFullPath($expected)){throw ''Fixture ACL seam rejected a path outside its operation temp root.''}};function Assert-WsmCancellationDirectoryProtection([string]$Path){$t=Read-WsmJson $TokenPath;$expected=Join-Path $t.StateDirectory $t.PairId;if([IO.Path]::GetFullPath($Path) -ine [IO.Path]::GetFullPath($expected)){throw ''Fixture ACL verifier rejected a path outside its operation temp root.''}};$token=Read-WsmJson $TokenPath;Start-Sleep -Milliseconds 500;Request-WsmCancellation $token ''Fixture owner'' ''native helper cancellation fixture''|Out-Null}',
        'while($true){[Console]::Out.Write(''SECRET-LONG-OUTPUT`n'');[Console]::Error.Write(''SECRET-LONG-ERROR`n'');Start-Sleep -Milliseconds 50}'
    )
    [IO.File]::WriteAllText($helperPath,($helperLines -join "`r`n"),(New-Object Text.UTF8Encoding($true)))
    $module=Import-Module (Join-Path $repo 'src\WindowsServerMigration.psd1') -Force -PassThru
    & $module {
        param($Root,$Repo)
        . (Join-Path $Repo 'src\Cancellation.ps1')
        # The isolated temp fixture cannot install the production ACL without
        # SeSecurityPrivilege; marker tests retain strict temp-path validation.
        $script:nativeFixtureRoot=$Root
        function Protect-WsmDirectory([string]$Path) { $full=[IO.Path]::GetFullPath($Path);if(-not $full.StartsWith(([IO.Path]::GetFullPath($script:nativeFixtureRoot).TrimEnd('\')+'\'),[StringComparison]::OrdinalIgnoreCase)){throw 'Fixture ACL seam rejected a path outside its temp root.'} }
        function Assert-WsmCancellationDirectoryProtection([string]$Path) { $full=[IO.Path]::GetFullPath($Path);if(-not $full.StartsWith(([IO.Path]::GetFullPath($script:nativeFixtureRoot).TrimEnd('\')+'\'),[StringComparison]::OrdinalIgnoreCase)){throw 'Fixture ACL verification seam rejected a path outside its temp root.'} }
        $stateRoot=Join-Path $Root 'state';[void][IO.Directory]::CreateDirectory($stateRoot)
        $pair=[Guid]::NewGuid().ToString();$plan='a'*64;$manifest='b'*64;$operation=[Guid]::NewGuid().ToString();$token=New-WsmCancellationToken $pair $plan $manifest $operation $stateRoot
        $script:nativeRoot=$Root;$script:nativeRepo=$Repo;$script:nativeMode='Burst';$script:nativeReady=Join-Path $Root 'ready.txt';$script:nativeGrandchild=Join-Path $Root 'grandchild.txt';$script:nativeTokenPath=Join-Path $Root 'token.json';$script:nativeFactoryCalls=0
        function script:New-WsmNativeOwnedProcess($StartInfo){$script:nativeFactoryCalls++;$info=New-Object Diagnostics.ProcessStartInfo;$info.FileName=[Diagnostics.Process]::GetCurrentProcess().MainModule.FileName;$values=@('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $script:nativeRoot 'native-helper.ps1'),$script:nativeRepo,$script:nativeMode,$script:nativeReady,$script:nativeGrandchild,$script:nativeTokenPath);$info.Arguments=(@($values|ForEach-Object {ConvertTo-WsmWindowsArgument ([string]$_)}) -join ' ');$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true;$process=New-Object Diagnostics.Process;$process.StartInfo=$info;$process}
        function script:Wait-NativeReady([string]$Path,[int]$TimeoutMilliseconds=5000){$watch=[Diagnostics.Stopwatch]::StartNew();while(-not [IO.File]::Exists($Path) -and $watch.ElapsedMilliseconds -lt $TimeoutMilliseconds){Start-Sleep -Milliseconds 25};if(-not [IO.File]::Exists($Path)){throw 'Native helper did not reach its started boundary.'};$parts=[IO.File]::ReadAllText($Path).Split('|');[pscustomobject]@{ProcessId=[int]$parts[0];StartedUtc=(New-Object DateTime([long]$parts[1],[DateTimeKind]::Utc))}}
        function script:Assert-NativePidExited([int]$Id){$running=$false;try{$p=[Diagnostics.Process]::GetProcessById($Id);$running=-not $p.HasExited;$p.Dispose()}catch{};if($running){throw 'Owned native helper remained running after cancellation/timeout.'}}

        # A request already present at process start prevents even the process factory from running.
        Request-WsmCancellation $token 'Fixture owner' 'cancel before native start'|Out-Null;$script:nativeFactoryCalls=0;$beforeError=$null;try{Invoke-WsmNativeTool 'sc.exe' @('fixture') -CancellationToken $token|Out-Null}catch{$beforeError=$_.Exception};if($beforeError -isnot [OperationCanceledException] -or $script:nativeFactoryCalls -ne 0){throw 'Pre-start cancellation reached the native process factory.'}

        # Bounded capture returns only counts and hashes, never potentially secret output.
        $burst=Invoke-WsmNativeTool 'sc.exe' @('fixture') -TimeoutSeconds 10
        if(-not $burst.Succeeded -or -not $burst.OutputTruncated -or $burst.StdOutCharacters -lt 65536 -or $burst.RawOutputIncluded -or $burst.PSObject.Properties['Output'] -or $burst.StdOutSha256 -notmatch '^[a-f0-9]{64}$'){throw 'Native output was not bounded, hashed and removed from returned metadata.'}

        # Cancel starts from a separate helper after process start, while the owned tool process is streaming.
        $script:nativeMode='Cancel';Remove-Item -LiteralPath $script:nativeReady -Force -ErrorAction SilentlyContinue;$token=New-WsmCancellationToken $pair $plan $manifest ([Guid]::NewGuid().ToString()) $stateRoot;Write-WsmJson $script:nativeTokenPath $token
        $cancelError=$null;try{Invoke-WsmNativeTool 'sc.exe' @('fixture') -TimeoutSeconds 8 -CancellationToken $token|Out-Null}catch{$cancelError=$_.Exception}
        $fixturePid=(Wait-NativeReady $script:nativeReady).ProcessId
        if($cancelError -isnot [OperationCanceledException]){throw ('Native owner-cancel did not produce the typed cancellation exception: '+$(if($cancelError){$cancelError.GetType().FullName}else{'<none>'})+' message='+$(if($cancelError){$cancelError.Message}else{''})+' NativeResult='+$(if($cancelError.Data){$cancelError.Data['NativeResult']}else{''})+' NativeCode='+$(if($cancelError.Data){$cancelError.Data['NativeCode']}else{''})+' stderrDigest='+$(if($cancelError.Data){$cancelError.Data['StdErrSha256']}else{''})+'.')}
        $cancelDetails=Get-WsmCancellationFailureDetails $cancelError
        if($cancelError -isnot [OperationCanceledException] -or $cancelError.Data['NativeResult'] -cne 'Cancelled' -or -not $cancelError.Data['ProcessKillAttempted'] -or -not $cancelError.Data['ProcessExitObserved'] -or -not $cancelError.Data['ProcessKillVerified'] -or $cancelError.Data['NativeProcessId'] -ne $fixturePid -or $cancelError.Data['AutomaticRetrySafe'] -ne $false -or $cancelError.Data['TerminationScope'] -cne 'OwnedProcessOnly' -or $cancelError.Data['ChildProcessTerminationVerified'] -ne $false -or $cancelDetails.ExitCode -ne 3 -or $cancelDetails.Boundary -cne 'NativeProcessWait' -or -not $cancelDetails.Hint -or $cancelDetails.RawOutputIncluded -ne $false){throw 'Native cancellation lost its outcome, exit-3 mapping, or bounded owned-process termination proof.'}
        Assert-NativePidExited $fixturePid;if($cancelError.Message -match 'SECRET-' -or $cancelError.Data['StdOutSha256'] -notmatch '^[a-f0-9]{64}$'){throw 'Native cancellation leaked raw output or omitted its bounded digest.'}

        # Timeout applies the same bounded kill-and-exit proof.
        $script:nativeMode='Timeout';Remove-Item -LiteralPath $script:nativeReady -Force -ErrorAction SilentlyContinue;$timeoutError=$null;try{Invoke-WsmNativeTool 'sc.exe' @('fixture') -TimeoutSeconds 1|Out-Null}catch{$timeoutError=$_.Exception};$fixturePid=[int]$timeoutError.Data['NativeProcessId']
        if($timeoutError -isnot [TimeoutException] -or $timeoutError.Data['NativeResult'] -cne 'Timeout' -or -not $timeoutError.Data['ProcessKillVerified'] -or -not $timeoutError.Data['ProcessExitObserved'] -or $timeoutError.Data['AutomaticRetrySafe'] -ne $false -or $timeoutError.Data['TerminationScope'] -cne 'OwnedProcessOnly' -or $timeoutError.Data['ChildProcessTerminationVerified'] -ne $false -or -not $fixturePid){throw 'Native timeout was not bounded or lost the actual process outcome.'};if([IO.File]::Exists($script:nativeReady) -and [int]([IO.File]::ReadAllText($script:nativeReady).Split('|')[0]) -ne $fixturePid){throw 'Native timeout kill proof names a different fixture process.'};Assert-NativePidExited $fixturePid

        # A silent child reports elapsed wait time and its last observed output time; it does not claim activity.
        $script:nativeMode='Silent';Remove-Item -LiteralPath $script:nativeReady -Force -ErrorAction SilentlyContinue;$silentToken=New-WsmCancellationToken $pair $plan $manifest ([Guid]::NewGuid().ToString()) $stateRoot;Write-WsmJson $script:nativeTokenPath $silentToken;$silentProgressPath=Get-WsmOperationProgressPath $silentToken
        $observer=Start-Job -ArgumentList $silentProgressPath -ScriptBlock {param($Path)$rows=New-Object 'System.Collections.Generic.List[string]';$watch=[Diagnostics.Stopwatch]::StartNew();$last='';while($watch.Elapsed.TotalSeconds -lt 8){if([IO.File]::Exists($Path)){try{$text=[IO.File]::ReadAllText($Path);$row=ConvertFrom-Json $text;if($row.UpdatedUtc -cne $last){$rows.Add($text);$last=$row.UpdatedUtc}}catch{}}elseif($rows.Count){break};Start-Sleep -Milliseconds 25};$rows.ToArray()}
        try{$silentTimeout=$null;$silentResults=@();try{$silentResults=@(Invoke-WsmNativeTool 'sc.exe' @('fixture') -TimeoutSeconds 3 -CancellationToken $silentToken)}catch{$silentTimeout=$_.Exception};$ready=Wait-NativeReady $script:nativeReady;$fixturePid=$ready.ProcessId;Wait-Job $observer -Timeout 8|Out-Null;$silentSamples=@(Receive-Job $observer);if($silentTimeout -isnot [TimeoutException] -or $silentTimeout.Data['LastObservedActivityUtc'] -notmatch 'Z$' -or $silentTimeout.Data['ElapsedSeconds'] -lt 2 -or $silentTimeout.Data['StdOutCharacters'] -ne 0 -or $silentTimeout.Data['StdErrCharacters'] -ne 0 -or $silentResults.Count -ne 0 -or [IO.File]::Exists($silentProgressPath) -or $silentSamples.Count -lt 1){throw 'Silent native child did not expose bounded live status, timeout diagnostics, or cleanup without pipeline JSON.'};$silentRows=@($silentSamples | ForEach-Object {ConvertFrom-WsmJson $_} | Group-Object UpdatedUtc | ForEach-Object {$_.Group[0]});$startedUtc=[DateTime]::new([long]$ready.StartedUtc.Ticks,[DateTimeKind]::Utc);$activity=[DateTimeOffset]::Parse($silentTimeout.Data['LastObservedActivityUtc']);if([Math]::Abs(($activity.UtcDateTime-$startedUtc).TotalSeconds) -gt 2 -or $activity.UtcDateTime -gt [DateTime]::UtcNow.AddSeconds(-1)){throw 'Silent child progress invented output activity instead of retaining its last observed timestamp.'};foreach($row in $silentRows){if($row.Phase -cne 'NativeProcessWait' -or $row.ElapsedSeconds -lt 1 -or $row.LastActivityUtc -notmatch 'Z$' -or ($row|ConvertTo-Json -Compress) -match [regex]::Escape($Root)){throw 'Native progress marker leaked a path or omitted safe wait/activity fields.'}};for($i=1;$i -lt $silentRows.Count;$i++){if(([DateTimeOffset]::Parse($silentRows[$i].UpdatedUtc)-[DateTimeOffset]::Parse($silentRows[$i-1].UpdatedUtc)).TotalMilliseconds -lt 900){throw 'Native progress updates were not throttled to approximately one per second.'}};Assert-NativePidExited $fixturePid}finally{if($observer){if($observer.State -eq 'Running'){Stop-Job $observer|Out-Null};Remove-Job $observer -Force -ErrorAction SilentlyContinue}}

        # A surviving child that inherits redirected output must not block the parent drain indefinitely.
        $script:nativeMode='HungPipe';Remove-Item -LiteralPath $script:nativeReady -Force -ErrorAction SilentlyContinue;$watch=[Diagnostics.Stopwatch]::StartNew();$hung=Invoke-WsmNativeTool 'sc.exe' @('fixture') -TimeoutSeconds 8;$elapsed=$watch.Elapsed.TotalSeconds;$ready=Wait-NativeReady $script:nativeReady;$fixturePid=$ready.ProcessId;$elapsedFromProcessStart=([DateTime]::UtcNow-$ready.StartedUtc).TotalSeconds
        if(-not $hung.Succeeded -or $elapsedFromProcessStart -gt 14 -or -not $hung.OutputTruncated -or $hung.StdOutCaptureComplete -or $hung.StdErrCaptureComplete -or $hung.StdOutDigestKind -notmatch 'Partial' -or $hung.StdErrDigestKind -notmatch 'Partial'){throw ('Fixture did not prove that inherited-pipe capture returned within the process timeout plus bounded drain allowance: elapsedFromStart='+$elapsedFromProcessStart+' elapsedCall='+$elapsed+' succeeded='+$hung.Succeeded+' truncated='+$hung.OutputTruncated+' stdoutComplete='+$hung.StdOutCaptureComplete+' stderrComplete='+$hung.StdErrCaptureComplete+' stdoutDigest='+$hung.StdOutDigestKind+' stderrDigest='+$hung.StdErrDigestKind+'.')}
        if([IO.File]::Exists($script:nativeGrandchild)){$grandchildPid=[int][IO.File]::ReadAllText($script:nativeGrandchild);$child=[Diagnostics.Process]::GetProcessById($grandchildPid);if($child.HasExited){$child.Dispose();throw 'Inherited-pipe fixture child exited before the native capture returned; it did not prove independent bounded return.'};$child.Kill();[void]$child.WaitForExit(2000);$child.Dispose()}
        Write-Host 'PASS: hidden native helper; metadata-only bounded output; mid-process cancellation/timeout kill and exit proof; throttled silent-child progress preserves last observed activity and clears without JSON pipeline output; inherited output handle drain has a finite deadline. The whitelisted host tool was injected and never launched.'
    } $root $repo
} finally {
    if($grandchildPid){try{$p=[Diagnostics.Process]::GetProcessById($grandchildPid);if(-not $p.HasExited){$p.Kill();[void]$p.WaitForExit(2000)};$p.Dispose()}catch{}}
    if($fixturePid){try{$p=[Diagnostics.Process]::GetProcessById($fixturePid);if(-not $p.HasExited){$p.Kill();[void]$p.WaitForExit(2000)};$p.Dispose()}catch{}}
    $resolved=[IO.Path]::GetFullPath($root).TrimEnd('\');$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\')
    if($resolved -notmatch '\\wsm-native-[0-9a-f]{32}$' -or -not $resolved.StartsWith(($temp+'\'),[StringComparison]::OrdinalIgnoreCase)){throw ('Refusing native fixture cleanup outside its validated test root: '+$resolved)}
    if([IO.Directory]::Exists($resolved)){Remove-Item -LiteralPath $resolved -Recurse -Force}
}
