#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$reviewPath=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\src\WindowsSettingsReview.ps1'))
& $module {
    param($reviewPath)
    . $reviewPath
    function Assert-WindowsReview([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
    function New-WindowsReviewItem([string]$HostId,[string]$Kind,[string]$Name,[string]$NaturalKey,$Settings,[object[]]$Dependencies=@(),[string]$Category='System',[string]$Status='Success'){
        [pscustomobject][ordered]@{ItemId=(Get-WsmHashText ($HostId+'|'+$Category+'|'+$Kind+'|'+$NaturalKey));Category=$Category;Kind=$Kind;Name=$Name;NaturalKey=$NaturalKey;Settings=$Settings;SettingsHash=(Get-WsmHashText (ConvertTo-Json -InputObject $Settings -Depth 30 -Compress));Dependencies=$Dependencies;Status=$Status;Adapter='Manual'}
    }
    $sourceHost='11111111-1111-4111-8111-111111111111';$targetHost='22222222-2222-4222-8222-222222222222';$pair='33333333-3333-4333-8333-333333333333'
    $sourceFingerprint='a'*64;$targetFingerprint='b'*64
    $sourceSettings=[pscustomobject][ordered]@{TimeZone='Eastern Standard Time';Culture='en-US';UICulture='日本語<review>';Environment=[ordered]@{PATH='C:\source-private\bin;C:\Windows\System32';APP_HOME='C:\source-private\app';NLS_LANG='日本語<AL32UTF8>';LOCAL='Password=fixture-private';TNS_ADMIN='C:\oracle\network\admin'};ControlSource='GPO'}
    $targetSettings=[pscustomobject][ordered]@{TimeZone='Pacific Standard Time';Culture='fr-FR';UICulture='fr-FR';Environment=[ordered]@{PATH='C:\target-private\bin;C:\Windows\System32';APP_HOME='C:\target-private\app';NLS_LANG='AMERICAN_AMERICA.AL32UTF8';LOCAL='Password=target-private';TNS_ADMIN='C:\target-oracle\network\admin'};ControlSource='Local'}
    $sourceSystem=New-WindowsReviewItem $sourceHost SystemConfiguration 'System settings' 'system-configuration' $sourceSettings
    $targetSystem=New-WindowsReviewItem $targetHost SystemConfiguration 'System settings' 'system-configuration' $targetSettings
    $consumer=New-WindowsReviewItem $sourceHost Service 'Sample service' 'svc:sample' ([pscustomobject]@{Name='Sample'}) @([pscustomobject]@{ItemId=$sourceSystem.ItemId;Type='Mandatory';Evidence='declared required system setting';Confidence='Declared'}) 'Services'
    $sourceHosts=New-WindowsReviewItem $sourceHost HostsFile 'hosts file' 'hosts' ([pscustomobject]@{Content="127.0.0.1 localhost`r`n10.1.2.3 private.internal`r`n"}) @() 'Network'
    $targetHosts=New-WindowsReviewItem $targetHost HostsFile 'hosts file' 'hosts' ([pscustomobject]@{Content="127.0.0.1 localhost`r`n10.9.8.7 target.internal`r`n"}) @() 'Network'
    $gap=New-WindowsReviewItem $sourceHost DiscoveryRequirement 'HTTP.sys and GPO effective policy' 'http-sys-and-external-review' ([pscustomobject]@{Checks=@('GPO effective state');OwnerConfirmationRequired=$true}) @() 'Network' 'Unsupported'
    $source=[pscustomobject]@{Kind='Inventory';Revision=7;Source=[pscustomobject]@{Fingerprint=$sourceFingerprint};Items=@($sourceSystem,$consumer,$sourceHosts,$gap)}
    $target=[pscustomobject]@{Kind='Inventory';Revision=2;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($targetSystem,$targetHosts)}
    $catalog=[pscustomobject]@{PairId=$pair;GeneralHost=[pscustomobject]@{Requirements=@([pscustomobject]@{ProviderItemId=$sourceSystem.ItemId;Certainty='Required';ConsumerItemIds=@($consumer.ItemId)})}}
    $sourceHash='c'*64;$targetHash='d'*64

    $optOut=Get-WsmWindowsSettingsReviewPreview -SourceInventory $source -TargetInventory $target -ReviewWindowsSettings:$false -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $catalog
    Assert-WindowsReview ($optOut.Rows.Count -ge 6) 'System configuration values were not flattened into individual decisions.'
    Assert-WindowsReview (@($optOut.Rows | Where-Object {$_.DefaultAction -ne 'KeepTarget'}).Count -eq 0) 'Declining review did not default all rows to KeepTarget.'
    Assert-WindowsReview (@($optOut.Rows | Where-Object {$_.ControlSource -eq 'GPO'}).Count -gt 0) 'Explicit GPO control source was not preserved.'
    Assert-WindowsReview (@($optOut.Rows | Where-Object {$_.ControlSource -eq 'Unknown'}).Count -gt 0) 'Unknown control source was not surfaced.'
    Assert-WindowsReview ($optOut.RequiredConsumerBlockers.Count -gt 0 -and @($optOut.Rows | Where-Object {$_.RequiredConsumerGateUnchanged -ne $true}).Count -eq 0) 'KeepTarget preference removed a required-consumer impact.'
    Assert-WindowsReview (@($optOut.Coverage | Where-Object {$_.Status -eq 'Unsupported'}).Count -eq 1) 'Unsupported source coverage gap was not retained.'
    $pathRow=@($optOut.Rows | Where-Object {$_.SettingName -eq 'Environment.PATH'})[0]
    Assert-WindowsReview ($pathRow.ManualMergeRequired -and $pathRow.ManualMergeRows.Count -eq 3) 'PATH manual merge component hashes are missing.'
    $hostsRow=@($optOut.Rows | Where-Object {$_.Kind -eq 'HostsFile'})[0]
    Assert-WindowsReview ($hostsRow.ManualMergeRequired -and $hostsRow.ManualMergeRows.Count -eq 3) 'hosts manual merge line hashes are missing.'
    Assert-WindowsReview (@($optOut.Rows | Where-Object {$_.TargetDiff -eq 'Different' -and $_.SourceValueHash -ne $_.TargetValueHash}).Count -gt 0) 'Source and target differences are not bound by exact value hashes.'
    $previewText=ConvertTo-Json -InputObject $optOut -Depth 60 -Compress
    Assert-WindowsReview (@($pathRow.SourceSummary.Components | Where-Object {$_ -ceq 'C:\source-private\bin'}).Count -eq 1 -and @($hostsRow.SourceSummary.Hosts | Where-Object {$_.Address -ceq '10.1.2.3' -and $_.Names -contains 'private.internal'}).Count -eq 1) 'Controlled PATH and hosts allowlist summaries are not readable for owner review.'
    foreach($secret in @('Password=fixture-private','Password=target-private')){Assert-WindowsReview (-not $previewText.Contains($secret)) 'Credential-bearing setting value leaked into the preview.'}
    $nlsRow=@($optOut.Rows | Where-Object {$_.SettingName -eq 'Environment.NLS_LANG'})[0];$uiRow=@($optOut.Rows | Where-Object {$_.SettingName -eq 'UICulture'})[0]
    Assert-WindowsReview ($nlsRow.SourceSummary.Display -ceq '日本語&lt;AL32UTF8&gt;' -and $uiRow.SourceSummary.Display -ceq '日本語&lt;review&gt;') 'Unicode value labels were not decoded and safely escaped in the preview.'
    Assert-WindowsReview ((Get-WsmWindowsSettingsPreviewHash $optOut) -ceq $optOut.PreviewHash) 'Preview hash does not bind the complete safe projection.'

    $optIn=Get-WsmWindowsSettingsReviewPreview -SourceInventory $source -TargetInventory $target -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $catalog
    Assert-WindowsReview (@($optIn.Rows | Where-Object {$_.SettingName -eq 'TimeZone' -and $_.SupportedActions -contains 'UpdateReviewed'}).Count -eq 0) 'The review helper invented an unqualified UpdateReviewed adapter for a system-configuration summary.'

    function New-ReviewSettingSpec([string]$Adapter,$Desired,$Transition){$spec=[pscustomobject][ordered]@{Adapter=$Adapter;Owner='settings-owner';Evidence='change-record:settings-review';Desired=$Desired};if($Transition){$spec | Add-Member NoteProperty SettingTransition $Transition};$spec}
    $firewallSettings=[pscustomobject][ordered]@{Rule=[pscustomobject][ordered]@{Name='fixture-local-firewall';Enabled='False';Direction='Inbound';Action='Allow';Profile=@('Domain');PolicyStoreSourceType='Local'};Ports=@([pscustomobject]@{Protocol='TCP';LocalPort='443';RemotePort='*'});Addresses=@([pscustomobject]@{LocalAddress='Any';RemoteAddress='Any'});Applications=@([pscustomobject]@{Program='C:\Windows\System32\svchost.exe'})}
    $sourceFirewall=New-WindowsReviewItem $sourceHost FirewallRule 'Local firewall rule' 'fixture-local-firewall' $firewallSettings @() 'Network'
    $targetFirewall=New-WindowsReviewItem $targetHost FirewallRule 'Local firewall rule' 'fixture-local-firewall' $firewallSettings @() 'Network'
    $firewallDesired=[pscustomobject][ordered]@{Name='fixture-local-firewall';DisplayName='Local firewall rule';Direction='Inbound';Action='Allow';Profile=@('Domain');Protocol='TCP';LocalPort=@('443');RemotePort=@('*');LocalAddress=@('Any');RemoteAddress=@('Any');Program='C:\Windows\System32\svchost.exe'}
    $firewallSpec=New-ReviewSettingSpec FirewallRule $firewallDesired $null
    $localFirewallCatalog=[pscustomobject]@{PairId=$pair;Items=@([pscustomobject]@{ItemId=$sourceFirewall.ItemId;Kind='FirewallRule';SettingsHash=$sourceFirewall.SettingsHash;MigrationSpec=$firewallSpec})}
    $firewallSource=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$sourceFingerprint};Items=@($sourceFirewall)}
    $firewallTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($targetFirewall)}
    $firewallReview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $firewallSource -TargetInventory $firewallTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $localFirewallCatalog
    Assert-WindowsReview (@($firewallReview.Rows[0].SupportedActions -contains 'ReviewedMigration') -and $firewallReview.Rows[0].ControlSource -ceq 'Local') 'Collector-shaped local firewall provenance did not expose its reviewed adapter.'
    foreach($targetPolicySource in @('GroupPolicy','Unknown')){$managedTargetSettings=$firewallSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$managedTargetSettings.Rule.PolicyStoreSourceType=$targetPolicySource;$managedTargetItem=New-WindowsReviewItem $targetHost FirewallRule 'Managed firewall rule' 'fixture-local-firewall' $managedTargetSettings @() 'Network';$managedTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($managedTargetItem)};$managedTargetPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $firewallSource -TargetInventory $managedTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $localFirewallCatalog;Assert-WindowsReview ($managedTargetPreview.Rows[0].SupportedActions -notcontains 'ReviewedMigration') ('A present target firewall rule with '+$targetPolicySource+' provenance incorrectly enabled an update.')}
    $otherFirewallSettings=$firewallSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$otherFirewallSettings.Rule.Name='other-target-rule';$otherFirewall=New-WindowsReviewItem $targetHost FirewallRule 'Other target rule' 'other-target-rule' $otherFirewallSettings @() 'Network'
    $targetNetworkCapture=[pscustomobject]@{ItemId='network-capture';Category='Network';Kind='IPConfiguration';Name='Interfaces';NaturalKey='interfaces';Settings=[pscustomobject]@{FirewallRuleEnumeration=[pscustomobject]@{PolicyStore='ActiveStore';TracePolicyStore=$true;EnumerationComplete=$true;RuleCount=[long]1}};SettingsHash=('1'*64);Status='Success'}
    $targetNetworkGap=[pscustomobject]@{ItemId='network-scope-gap';Category='Network';Kind='DiscoveryGap';Name='Network discovery scope';NaturalKey='scope:Network';Settings=[pscustomobject]@{};SettingsHash=('3'*64);Status='Unsupported'}
    $absentFirewallTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($otherFirewall,$targetNetworkCapture,$targetNetworkGap)}
    $absentFirewallPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $firewallSource -TargetInventory $absentFirewallTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $localFirewallCatalog
    Assert-WindowsReview ($absentFirewallPreview.Rows[0].SupportedActions -contains 'ReviewedMigration') 'A matching native ActiveStore/TracePolicyStore enumeration marker did not permit the reviewed firewall create path alongside the generic Network DiscoveryGap.'
    $badNetworkCases=@(
        @{Name='missing marker';Kind='IPConfiguration';Status='Success';Settings=[pscustomobject]@{};IncludeFirewall=$true;IncludeGap=$true},
        @{Name='missing marker without generic gap';Kind='IPConfiguration';Status='Success';Settings=[pscustomobject]@{};IncludeFirewall=$true;IncludeGap=$false},
        @{Name='wrong rule count';Kind='IPConfiguration';Status='Success';Settings=[pscustomobject]@{FirewallRuleEnumeration=[pscustomobject]@{PolicyStore='ActiveStore';TracePolicyStore=$true;EnumerationComplete=$true;RuleCount=[long]0}};IncludeFirewall=$true;IncludeGap=$true},
        @{Name='partial capture';Kind='IPConfiguration';Status='Partial';Settings=$targetNetworkCapture.Settings;IncludeFirewall=$true;IncludeGap=$true},
        @{Name='failed capture';Kind='IPConfiguration';Status='Failed';Settings=$targetNetworkCapture.Settings;IncludeFirewall=$true;IncludeGap=$true}
    )
    foreach($badNetworkCapture in $badNetworkCases){$badNetworkItems=@([pscustomobject]@{ItemId='network-capture';Category='Network';Kind=$badNetworkCapture.Kind;Name='Network capture';NaturalKey='interfaces';Settings=$badNetworkCapture.Settings;SettingsHash=('1'*64);Status=$badNetworkCapture.Status});if($badNetworkCapture.IncludeFirewall){$badNetworkItems+=@($otherFirewall)};if($badNetworkCapture.IncludeGap){$badNetworkItems+=@($targetNetworkGap)};$incompleteFirewallTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=$badNetworkItems};$incompleteFirewallPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $firewallSource -TargetInventory $incompleteFirewallTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $localFirewallCatalog;Assert-WindowsReview ($incompleteFirewallPreview.Rows[0].SupportedActions -notcontains 'ReviewedMigration') ('Firewall create ignored '+$badNetworkCapture.Name+' enumeration evidence.')}
    foreach($policyStoreCase in @(@{Value='GroupPolicy';Expected='GPO';Top='Local'},@{Value='None';Expected='Unknown';Top='Local'},@{Value='123';Expected='Unknown';Top='Local'},@{Value='Dynamic';Expected='Unknown';Top='Local'})){$badSettings=$firewallSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$badSettings.Rule.PolicyStoreSourceType=[string]$policyStoreCase.Value;$badSettings | Add-Member NoteProperty ControlSource $policyStoreCase.Top -Force;$badFirewall=New-WindowsReviewItem $sourceHost FirewallRule 'Controlled firewall rule' 'fixture-local-firewall' $badSettings @() 'Network';$badCatalog=[pscustomobject]@{PairId=$pair;Items=@([pscustomobject]@{ItemId=$badFirewall.ItemId;Kind='FirewallRule';SettingsHash=$badFirewall.SettingsHash;MigrationSpec=$firewallSpec})};$badInventory=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$sourceFingerprint};Items=@($badFirewall)};$badPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $badInventory -TargetInventory $firewallTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $badCatalog;Assert-WindowsReview ($badPreview.Rows[0].ControlSource -ceq $policyStoreCase.Expected -and $badPreview.Rows[0].SupportedActions -notcontains 'ReviewedMigration') ('Nested firewall policy source '+$policyStoreCase.Value+' was overridden or treated as Local.')}

    $sourceEnvState=[pscustomobject][ordered]@{Exists=$true;Value='C:\source\oracle\admin';ValueKind='String'};$targetEnvState=[pscustomobject][ordered]@{Exists=$true;Value='C:\target\oracle\admin';ValueKind='ExpandString'}
    $envSourceSettings=[pscustomobject][ordered]@{Environment=[ordered]@{TNS_ADMIN=$sourceEnvState.Value};WindowsSettingMetadata=[pscustomobject][ordered]@{ControlSource='Local';EnvironmentStates=[ordered]@{TNS_ADMIN=$sourceEnvState};EnvironmentStatesComplete=$true}}
    $envTargetSettings=[pscustomobject][ordered]@{Environment=[ordered]@{TNS_ADMIN=$targetEnvState.Value};WindowsSettingMetadata=[pscustomobject][ordered]@{ControlSource='Local';EnvironmentStates=[ordered]@{TNS_ADMIN=$targetEnvState};EnvironmentStatesComplete=$true}}
    $sourceEnvItem=New-WindowsReviewItem $sourceHost SystemConfiguration 'System settings' 'system-configuration' $envSourceSettings
    $targetEnvItem=New-WindowsReviewItem $targetHost SystemConfiguration 'System settings' 'system-configuration' $envTargetSettings
    $envTransition=New-WsmSettingTransition -Adapter MachineEnvironment -Action UpdateReviewed -Name TNS_ADMIN -Before $targetEnvState -After $sourceEnvState -Owner settings-owner -Evidence reviewed-source-target -OwnerReviewHash ('6'*64) -RequiredPhase CutoverReady
    $envSpec=New-ReviewSettingSpec MachineEnvironment ([pscustomobject]@{Name='TNS_ADMIN';Value=$sourceEnvState.Value}) $envTransition
    $envCatalog=[pscustomobject]@{PairId=$pair;Items=@([pscustomobject]@{ItemId=$sourceEnvItem.ItemId;Kind='SystemConfiguration';SettingsHash=$sourceEnvItem.SettingsHash;MigrationSpec=$envSpec})}
    $envSource=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$sourceFingerprint};Items=@($sourceEnvItem)}
    $envTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($targetEnvItem)}
    $envPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $envSource -TargetInventory $envTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $envCatalog
    $envRow=@($envPreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0]
    Assert-WindowsReview ($envRow.SupportedActions -contains 'ReviewedMigration' -and $envRow.SourceValueHash -ceq (Get-WsmWindowsSettingValueHash $sourceEnvState) -and $envRow.TargetValueHash -ceq (Get-WsmWindowsSettingValueHash $targetEnvState)) 'A trusted Local setting transition did not bind target-before and source-after states with exact value hashes.'
    foreach($targetControl in @('GroupPolicy','Unknown')){$blockedTargetSettings=$envTargetSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$blockedTargetSettings.WindowsSettingMetadata.ControlSource=$targetControl;$blockedTargetItem=New-WindowsReviewItem $targetHost SystemConfiguration 'System settings' 'system-configuration' $blockedTargetSettings;$blockedTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($blockedTargetItem)};$blockedTargetPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $envSource -TargetInventory $blockedTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $envCatalog;Assert-WindowsReview (@($blockedTargetPreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0].SupportedActions -notcontains 'ReviewedMigration') ('Target control source '+$targetControl+' incorrectly authorized a tool-owned update.')}
    $wrongBefore=New-WsmSettingTransition -Adapter MachineEnvironment -Action UpdateReviewed -Name TNS_ADMIN -Before $sourceEnvState -After $targetEnvState -Owner settings-owner -Evidence reversed-source-target -OwnerReviewHash ('7'*64) -RequiredPhase CutoverReady
    $wrongSpec=New-ReviewSettingSpec MachineEnvironment ([pscustomobject]@{Name='TNS_ADMIN';Value=$targetEnvState.Value}) $wrongBefore
    $envCatalog.Items[0].MigrationSpec=$wrongSpec
    $wrongPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $envSource -TargetInventory $envTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $envCatalog
    Assert-WindowsReview (@($wrongPreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0].SupportedActions -notcontains 'ReviewedMigration') 'Source-as-before reversed transition was accepted.'
    $unknownEnvSettings=$envSourceSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$unknownEnvSettings.WindowsSettingMetadata.ControlSource='Unknown';$unknownEnvItem=New-WindowsReviewItem $sourceHost SystemConfiguration 'System settings' 'system-configuration' $unknownEnvSettings;$unknownEnvCatalog=[pscustomobject]@{PairId=$pair;Items=@([pscustomobject]@{ItemId=$unknownEnvItem.ItemId;Kind='SystemConfiguration';SettingsHash=$unknownEnvItem.SettingsHash;MigrationSpec=$envSpec})};$unknownEnv=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$sourceFingerprint};Items=@($unknownEnvItem)};$unknownEnvPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $unknownEnv -TargetInventory $envTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $unknownEnvCatalog
    Assert-WindowsReview (@($unknownEnvPreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0].ControlSource -ceq 'Unknown' -and @($unknownEnvPreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0].SupportedActions -notcontains 'ReviewedMigration') 'Unknown environment control source was inferred Local.'
    foreach($controlConflict in @(@{Metadata='Local';Top='GPO';Expected='GPO'},@{Metadata='Unknown';Top='GroupPolicy';Expected='GPO'},@{Metadata='Unknown';Top='Local';Expected='Unknown'})){$conflictSettings=$envSourceSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$conflictSettings.WindowsSettingMetadata.ControlSource=[string]$controlConflict.Metadata;$conflictSettings | Add-Member NoteProperty ControlSource ([string]$controlConflict.Top) -Force;$conflictItem=New-WindowsReviewItem $sourceHost SystemConfiguration 'System settings' 'system-configuration' $conflictSettings;$conflictCatalog=[pscustomobject]@{PairId=$pair;Items=@([pscustomobject]@{ItemId=$conflictItem.ItemId;Kind='SystemConfiguration';SettingsHash=$conflictItem.SettingsHash;MigrationSpec=$envSpec})};$conflictInventory=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$sourceFingerprint};Items=@($conflictItem)};$conflictPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $conflictInventory -TargetInventory $envTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $conflictCatalog;$conflictRow=@($conflictPreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0];Assert-WindowsReview ($conflictRow.ControlSource -ceq $controlConflict.Expected -and $conflictRow.SupportedActions -notcontains 'ReviewedMigration') 'Explicit GPO or Unknown provenance conflict was overridden by Local.'}
    $disagreeSourceSettings=$envSourceSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$disagreeSourceSettings.Environment.TNS_ADMIN='C:\different\unbound-value';$disagreeSourceItem=New-WindowsReviewItem $sourceHost SystemConfiguration 'System settings' 'system-configuration' $disagreeSourceSettings;$disagreeSourceCatalog=[pscustomobject]@{PairId=$pair;Items=@([pscustomobject]@{ItemId=$disagreeSourceItem.ItemId;Kind='SystemConfiguration';SettingsHash=$disagreeSourceItem.SettingsHash;MigrationSpec=$envSpec})};$disagreeSource=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$sourceFingerprint};Items=@($disagreeSourceItem)};$disagreePreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $disagreeSource -TargetInventory $envTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $disagreeSourceCatalog
    Assert-WindowsReview (@($disagreePreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0].SupportedActions -notcontains 'ReviewedMigration') 'A metadata state inconsistent with the captured Environment value was trusted.'
    $absentTargetSettings=[pscustomobject][ordered]@{Environment=[ordered]@{};WindowsSettingMetadata=[pscustomobject][ordered]@{ControlSource='Local';EnvironmentStates=[ordered]@{TNS_ADMIN=[pscustomobject][ordered]@{Exists=$false;Value=$null;ValueKind='None'}};EnvironmentStatesComplete=$true}}
    $absentTargetItem=New-WindowsReviewItem $targetHost SystemConfiguration 'System settings' 'system-configuration' $absentTargetSettings;$absentTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($absentTargetItem)}
    $stringCompleteTargetSettings=$absentTargetSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$stringCompleteTargetSettings.WindowsSettingMetadata.EnvironmentStatesComplete='True';$stringCompleteTargetItem=New-WindowsReviewItem $targetHost SystemConfiguration 'System settings' 'system-configuration' $stringCompleteTargetSettings;$stringCompleteTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($stringCompleteTargetItem)};$stringCompletePreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $envSource -TargetInventory $stringCompleteTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $envCatalog
    Assert-WindowsReview (@($stringCompletePreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0].SupportedActions -notcontains 'ReviewedMigration') 'A string-valued EnvironmentStatesComplete flag was trusted as a Boolean.'
    $createTransition=New-WsmSettingTransition -Adapter MachineEnvironment -Action CreateNew -Name TNS_ADMIN -Before ([pscustomobject][ordered]@{Exists=$false;Value=$null;ValueKind='None'}) -After $sourceEnvState -Owner settings-owner -Evidence reviewed-create -OwnerReviewHash ('8'*64) -RequiredPhase CutoverReady
    $createSpec=New-ReviewSettingSpec MachineEnvironment ([pscustomobject]@{Name='TNS_ADMIN';Value=$sourceEnvState.Value}) $createTransition;$createCatalog=[pscustomobject]@{PairId=$pair;Items=@([pscustomobject]@{ItemId=$sourceEnvItem.ItemId;Kind='SystemConfiguration';SettingsHash=$sourceEnvItem.SettingsHash;MigrationSpec=$createSpec})}
    $createPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $envSource -TargetInventory $absentTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $createCatalog
    Assert-WindowsReview (@($createPreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0].SupportedActions -contains 'ReviewedMigration') 'CreateNew was not enabled when a complete trusted target inventory proved the setting absent.'
    foreach($targetControl in @('GroupPolicy','Unknown')){$blockedAbsentSettings=$absentTargetSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$blockedAbsentSettings.WindowsSettingMetadata.ControlSource=$targetControl;$blockedAbsentItem=New-WindowsReviewItem $targetHost SystemConfiguration 'System settings' 'system-configuration' $blockedAbsentSettings;$blockedAbsent=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($blockedAbsentItem)};$blockedAbsentPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $envSource -TargetInventory $blockedAbsent -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $createCatalog;Assert-WindowsReview (@($blockedAbsentPreview.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0].SupportedActions -notcontains 'ReviewedMigration') ('CreateNew ignored target '+$targetControl+' control source.')}
    $absentTargetSettings.WindowsSettingMetadata.EnvironmentStatesComplete=$false;$incompleteTargetItem=New-WindowsReviewItem $targetHost SystemConfiguration 'System settings' 'system-configuration' $absentTargetSettings;$incompleteTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($incompleteTargetItem)};$incompleteCreate=Get-WsmWindowsSettingsReviewPreview -SourceInventory $envSource -TargetInventory $incompleteTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $createCatalog
    Assert-WindowsReview (@($incompleteCreate.Rows | Where-Object SettingName -CEQ 'Environment.TNS_ADMIN')[0].SupportedActions -notcontains 'ReviewedMigration') 'CreateNew was enabled without complete target environment-state coverage.'

    $sourceTzState=[pscustomobject][ordered]@{Exists=$true;Value='Pacific Standard Time';ValueKind='TimeZoneId';DaylightSaving=[pscustomobject][ordered]@{Exists=$true;Value=$false;ValueKind='DWord'}}
    $targetTzState=[pscustomobject][ordered]@{Exists=$true;Value='Eastern Standard Time';ValueKind='TimeZoneId';DaylightSaving=[pscustomobject][ordered]@{Exists=$true;Value=$true;ValueKind='DWord'}}
    $tzSourceSettings=[pscustomobject][ordered]@{TimeZone=$sourceTzState.Value;WindowsSettingMetadata=[pscustomobject][ordered]@{ControlSource='Local';TimeZoneState=$sourceTzState;TimeZoneStateComplete=$true}}
    $tzTargetSettings=[pscustomobject][ordered]@{TimeZone=$targetTzState.Value;WindowsSettingMetadata=[pscustomobject][ordered]@{ControlSource='Local';TimeZoneState=$targetTzState;TimeZoneStateComplete=$true}}
    $tzSourceItem=New-WindowsReviewItem $sourceHost SystemConfiguration 'System settings' 'system-configuration' $tzSourceSettings;$tzTargetItem=New-WindowsReviewItem $targetHost SystemConfiguration 'System settings' 'system-configuration' $tzTargetSettings
    $tzTransition=New-WsmSettingTransition -Adapter TimeZone -Action UpdateReviewed -Name TimeZone -Before $targetTzState -After $sourceTzState -Owner settings-owner -Evidence reviewed-timezone -OwnerReviewHash ('9'*64) -RequiredPhase CutoverReady;$tzSpec=New-ReviewSettingSpec TimeZone ([pscustomobject]@{Name='TimeZone';Value=$sourceTzState.Value}) $tzTransition
    $tzSource=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$sourceFingerprint};Items=@($tzSourceItem)};$tzTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($tzTargetItem)};$tzCatalog=[pscustomobject]@{PairId=$pair;Items=@([pscustomobject]@{ItemId=$tzSourceItem.ItemId;Kind='SystemConfiguration';SettingsHash=$tzSourceItem.SettingsHash;MigrationSpec=$tzSpec})}
    $tzPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $tzSource -TargetInventory $tzTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $tzCatalog
    Assert-WindowsReview (@($tzPreview.Rows | Where-Object SettingName -CEQ 'TimeZone')[0].SupportedActions -contains 'ReviewedMigration') 'A complete Local time-zone transition did not compare exact target-before/source-after including DST.'
    $tzBadTargetSettings=$tzTargetSettings | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$tzBadTargetSettings.WindowsSettingMetadata.ControlSource='GroupPolicy';$tzBadTargetItem=New-WindowsReviewItem $targetHost SystemConfiguration 'System settings' 'system-configuration' $tzBadTargetSettings;$tzBadTarget=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$targetFingerprint};Items=@($tzBadTargetItem)};$tzBadPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $tzSource -TargetInventory $tzBadTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $tzCatalog
    Assert-WindowsReview (@($tzBadPreview.Rows | Where-Object SettingName -CEQ 'TimeZone')[0].SupportedActions -notcontains 'ReviewedMigration') 'A local source time-zone transition authorized changing a target GPO value.'
    $tzSourceSettings.WindowsSettingMetadata.ControlSource='Unknown';$tzUnknownItem=New-WindowsReviewItem $sourceHost SystemConfiguration 'System settings' 'system-configuration' $tzSourceSettings;$tzUnknownInventory=[pscustomobject]@{Kind='Inventory';Revision=1;Source=[pscustomobject]@{Fingerprint=$sourceFingerprint};Items=@($tzUnknownItem)};$tzUnknownCatalog=[pscustomobject]@{PairId=$pair;Items=@([pscustomobject]@{ItemId=$tzUnknownItem.ItemId;Kind='SystemConfiguration';SettingsHash=$tzUnknownItem.SettingsHash;MigrationSpec=$tzSpec})};$tzUnknownPreview=Get-WsmWindowsSettingsReviewPreview -SourceInventory $tzUnknownInventory -TargetInventory $tzTarget -ReviewWindowsSettings:$true -PairId $pair -SourceInventoryHash $sourceHash -TargetInventoryHash $targetHash -GeneralHostCatalog $tzUnknownCatalog
    Assert-WindowsReview (@($tzUnknownPreview.Rows | Where-Object SettingName -CEQ 'TimeZone')[0].SupportedActions -notcontains 'ReviewedMigration') 'Unknown time-zone control source was inferred Local.'
    # Exercise the catalog-backed consumer: trusted inputs are re-read, GeneralHost receives
    # real External dispositions, and consumer requirements remain blocked for receipt evidence.
    $tempRoot=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());$caseRoot=Join-Path $tempRoot ('wsm-winsettings-'+[Guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($caseRoot);$workspace=Join-Path $caseRoot 'manager';$sourcePath=Join-Path $caseRoot 'source.json';$targetPath=Join-Path $caseRoot 'target.json';$previewPath=Join-Path $caseRoot 'preview.json';$decisionsPath=Join-Path $caseRoot 'decisions.json'
    try{
        [void](Initialize-WsmWorkspace $workspace);$hostId=[Guid]::NewGuid().ToString();$depItem=New-WsmItem $hostId Services Service 'Review consumer' 'review-consumer' ([pscustomobject]@{PathName='C:\fixture\consumer.exe'}) @() Success; $configItem=New-WsmItem $hostId System SystemConfiguration 'System settings' 'system-configuration' ([pscustomobject][ordered]@{TimeZone='Eastern Standard Time';UICulture='zh-TW';Environment=[ordered]@{PATH='C:\source\bin;C:\Windows\System32';NLS_LANG='AMERICAN_AMERICA.AL32UTF8'};ControlSource='Local'}) @() Success
        $depItem.Dependencies=@([pscustomobject]@{ItemId=$configItem.ItemId;Type='Mandatory';Evidence='declared consumer dependency';Confidence='Declared'})
        $sourceDoc=New-WsmInventory ([pscustomobject]@{HostId=$hostId;Fingerprint=('e'*64);Name='fixture-source';OS='Windows Server';Version='2025'}) 3 @($configItem,$depItem);Write-WsmJson $sourcePath $sourceDoc;$sourceHash=(Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash.ToLowerInvariant();$catalog=Import-WsmInventory $workspace $sourcePath $sourceHash 'fixture-target';$catalog=Set-WsmGeneralHostMode $workspace $catalog.PairId $catalog.DecisionRevision
        $targetHost=[Guid]::NewGuid().ToString();$targetConfig=New-WsmItem $targetHost System SystemConfiguration 'System settings' 'system-configuration' ([pscustomobject][ordered]@{TimeZone='Pacific Standard Time';UICulture='en-US';Environment=[ordered]@{PATH='C:\target\bin;C:\Windows\System32';NLS_LANG='AMERICAN_AMERICA.AL32UTF8'};ControlSource='Local'}) @() Success;$targetDoc=New-WsmInventory ([pscustomobject]@{HostId=$targetHost;Fingerprint=('f'*64);Name='fixture-target';OS='Windows Server';Version='2025'}) 1 @($targetConfig);Write-WsmJson $targetPath $targetDoc;$targetHash=(Get-FileHash -LiteralPath $targetPath -Algorithm SHA256).Hash.ToLowerInvariant()
        $preview=Get-WsmWindowsSettingsReviewWorkspacePreview -Workspace $workspace -PairId $catalog.PairId -SourceInventoryPath $sourcePath -SourceInventoryHash $sourceHash -TargetInventoryPath $targetPath -TargetInventoryHash $targetHash -ReviewWindowsSettings:$false;Write-WsmJson $previewPath $preview;$previewHash=(Get-FileHash -LiteralPath $previewPath -Algorithm SHA256).Hash.ToLowerInvariant();$decisions=Get-WsmWindowsSettingsDecisionTemplate $preview;Write-WsmJson $decisionsPath $decisions;$decisionsHash=(Get-FileHash -LiteralPath $decisionsPath -Algorithm SHA256).Hash.ToLowerInvariant();$catalogPath=Get-WsmCatalogPath $workspace $catalog.PairId;$beforeApplyHash=(Get-FileHash -LiteralPath $catalogPath -Algorithm SHA256).Hash.ToLowerInvariant()
        $invalid=$decisions | ConvertTo-Json -Depth 30 | ConvertFrom-Json;$invalid.Decisions[0].Action='ReviewedMigration';$invalidPath=Join-Path $caseRoot 'invalid-decisions.json';Write-WsmJson $invalidPath $invalid;$invalidHash=(Get-FileHash -LiteralPath $invalidPath -Algorithm SHA256).Hash.ToLowerInvariant();$validationRejected=$false;try{Apply-WsmWindowsSettingsReview -Workspace $workspace -PairId $catalog.PairId -SourceInventoryPath $sourcePath -SourceInventoryHash $sourceHash -TargetInventoryPath $targetPath -TargetInventoryHash $targetHash -PreviewPath $previewPath -PreviewHash $previewHash -DecisionsPath $invalidPath -DecisionsHash $invalidHash -ExpectedRevision $catalog.DecisionRevision -Ack | Out-Null}catch{$validationRejected=$true};Assert-WindowsReview ($validationRejected -and (Get-FileHash -LiteralPath $catalogPath -Algorithm SHA256).Hash.ToLowerInvariant() -ceq $beforeApplyHash) 'Invalid typed action partially updated the authoritative catalog.'
        $script:windowsReviewFaultOriginal=(Get-Command Write-WsmJson).ScriptBlock;$script:windowsReviewFaultPath=$catalogPath;$writeFaultBlock={param([string]$Path,$Data)if($Path -ceq $script:windowsReviewFaultPath){throw 'Injected final catalog write failure before replacement.'};& $script:windowsReviewFaultOriginal $Path $Data};Set-Item -Path Function:Write-WsmJson -Value $writeFaultBlock;$writeRejected=$false;try{Apply-WsmWindowsSettingsReview -Workspace $workspace -PairId $catalog.PairId -SourceInventoryPath $sourcePath -SourceInventoryHash $sourceHash -TargetInventoryPath $targetPath -TargetInventoryHash $targetHash -PreviewPath $previewPath -PreviewHash $previewHash -DecisionsPath $decisionsPath -DecisionsHash $decisionsHash -ExpectedRevision $catalog.DecisionRevision -Ack | Out-Null}catch{$writeRejected=$_.Exception.Message -match 'Injected final catalog write failure'}finally{Set-Item -Path Function:Write-WsmJson -Value $script:windowsReviewFaultOriginal;Remove-Variable windowsReviewFaultOriginal,windowsReviewFaultPath -Scope Script -ErrorAction SilentlyContinue};Assert-WindowsReview ($writeRejected -and (Get-FileHash -LiteralPath $catalogPath -Algorithm SHA256).Hash.ToLowerInvariant() -ceq $beforeApplyHash) 'Injected final Write-WsmJson failure changed the real catalog.'
        $applied=Apply-WsmWindowsSettingsReview -Workspace $workspace -PairId $catalog.PairId -SourceInventoryPath $sourcePath -SourceInventoryHash $sourceHash -TargetInventoryPath $targetPath -TargetInventoryHash $targetHash -PreviewPath $previewPath -PreviewHash $previewHash -DecisionsPath $decisionsPath -DecisionsHash $decisionsHash -ExpectedRevision $catalog.DecisionRevision -Ack
        Assert-WindowsReview ($applied.Applied -and -not $applied.ReadinessProof -and $applied.DecisionRevision -gt $catalog.DecisionRevision) 'Windows settings selections were not applied to the authoritative catalog.'
        $appliedCatalog=Get-WsmCatalog $workspace $catalog.PairId
        Assert-WindowsReview (@($appliedCatalog.Items | Where-Object {$_.ItemId -ceq $configItem.ItemId -and $_.Decision -eq 'Exclude' -and $_.GeneralHostOverride.Disposition -eq 'External'}).Count -eq 1) 'KeepTarget was saved only as a detached report instead of a GeneralHost disposition.'
        $settingRequirements=@($appliedCatalog.GeneralHost.Requirements | Where-Object {$_.ExternalId -like 'windows-setting:*' -and $_.Certainty -eq 'Required' -and $_.Decision -eq 'Pending' -and $_.ConsumerItemIds -contains $depItem.ItemId})
        Assert-WindowsReview ($settingRequirements.Count -gt 0) 'Required consumer impact was not preserved as a typed unresolved requirement.'
        Assert-WindowsReview ($settingRequirements.Count -gt 1 -and @($settingRequirements | Select-Object -ExpandProperty ExternalId -Unique).Count -eq $settingRequirements.Count -and @($settingRequirements | Select-Object -ExpandProperty Context | Select-Object -ExpandProperty SettingId -Unique).Count -eq $settingRequirements.Count) 'Settings with the same consumer were merged and lost their individual exact value binding.'
        $gate=@(Get-WsmGeneralHostIssues $appliedCatalog CutoverReady $targetDoc.Source.Fingerprint)
        Assert-WindowsReview ($settingRequirements[0].Decision -eq 'Pending' -and $gate.Count -gt 0) 'KeepTarget preference incorrectly released the required consumer gate.'
    }finally{$resolvedTemp=[IO.Path]::GetFullPath($tempRoot).TrimEnd('\')+'\';$resolvedCase=[IO.Path]::GetFullPath($caseRoot);if(-not $resolvedCase.StartsWith($resolvedTemp,[StringComparison]::OrdinalIgnoreCase) -or $resolvedCase -eq $resolvedTemp.TrimEnd('\')){throw 'Refusing to remove a Windows settings fixture outside the temp root.'};if([IO.Directory]::Exists($resolvedCase)){Remove-Item -LiteralPath $resolvedCase -Recurse -Force}}
    'Windows settings review contract fixtures passed.'
} $reviewPath
