#requires -Version 5.1
$ErrorActionPreference='Stop'
$repo=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$module=Import-Module (Join-Path $repo 'src\WindowsServerMigration.psd1') -Force -PassThru
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-cancel-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
try {
    & $module {
        param($Root,$Repo)
        . (Join-Path $PSScriptRoot '..\src\Cancellation.ps1')
        # This fixture validates marker semantics, not ACL installation. The
        # host lacks SeSecurityPrivilege, so constrain the fixture ACL seam to
        # its short-lived temp tree while retaining all path/reparse checks.
        $script:cancellationFixtureRoot=$Root
        function Protect-WsmDirectory([string]$Path) { $full=[IO.Path]::GetFullPath($Path);if(-not $full.StartsWith(([IO.Path]::GetFullPath($script:cancellationFixtureRoot).TrimEnd('\')+'\'),[StringComparison]::OrdinalIgnoreCase)){throw 'Fixture ACL seam rejected a path outside its temp root.'} }
        function Assert-WsmCancellationDirectoryProtection([string]$Path) { $full=[IO.Path]::GetFullPath($Path);if(-not $full.StartsWith(([IO.Path]::GetFullPath($script:cancellationFixtureRoot).TrimEnd('\')+'\'),[StringComparison]::OrdinalIgnoreCase)){throw 'Fixture ACL verification seam rejected a path outside its temp root.'} }
        $pair=[Guid]::NewGuid().ToString();$otherPair=[Guid]::NewGuid().ToString();$plan='a'*64;$manifest='b'*64;$operation=[Guid]::NewGuid().ToString();$nextOperation=[Guid]::NewGuid().ToString()
        $token=New-WsmCancellationToken $pair $plan $manifest $operation $Root
        if([IO.Directory]::Exists((Join-Path $Root $pair))){throw 'Creating a cancellation descriptor unexpectedly created operation state.'}
        if($token.OperationId -eq 'fixture-state-run-id'){throw 'Cancellation descriptor reused an operation-state run id.'}
        $bound=Assert-WsmCancellationTokenBinding $token $pair $plan $manifest $Root;if($bound.OperationId -cne $operation){throw 'Exact cancellation token binding rejected.'}
        foreach($case in @(@($otherPair,$plan,$manifest,$Root),@($pair,('c'*64),$manifest,$Root),@($pair,$plan,('d'*64),$Root),@($pair,$plan,$manifest,(Join-Path $Root 'other')))){$blocked=$false;try{Assert-WsmCancellationTokenBinding $token $case[0] $case[1] $case[2] $case[3]|Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Cancellation token crossed a pair/plan/manifest/state boundary.'}}
        $manifestless=New-WsmCancellationToken $pair $plan '' $nextOperation $Root;$bound=Assert-WsmCancellationTokenBinding $manifestless $pair $plan '' $Root;if($bound.ManifestHash){throw 'Source-stage manifestless token did not preserve the explicit empty scope.'}
        if(Test-WsmCancellationRequested $token){throw 'Fresh cancellation descriptor appeared requested.'}
        $request=Invoke-WsmLocked $Root {Request-WsmCancellation $token 'Fixture owner' 'reviewed operator stop after durable phase'}
        if(-not $request.Requested -or $request.AlreadyRequested -or -not (Test-WsmCancellationRequested $token)){throw 'Owner cancellation marker was not durably created without the operation lock.'}
        $before=$request.RequestedUtc;$same=Request-WsmCancellation $token 'Fixture owner' 'reviewed operator stop after durable phase';if(-not $same.AlreadyRequested -or $same.RequestedUtc -cne $before){throw 'Idempotent cancellation changed original request evidence/time.'}
        $blocked=$false;try{Request-WsmCancellation $token 'Different owner' 'conflicting request'|Out-Null}catch{$blocked=$_.Exception.Message -match 'Conflicting cancellation request'};if(-not $blocked){throw 'Conflicting cancellation request overwrote its original evidence.'}
        $otherToken=New-WsmCancellationToken $pair $plan $manifest $nextOperation $Root;if(Test-WsmCancellationRequested $otherToken){throw 'Cancellation request escaped its operation ID scope.'}
        $crossToken=New-WsmCancellationToken $otherPair $plan $manifest $operation $Root;if(Test-WsmCancellationRequested $crossToken){throw 'Cancellation request escaped its pair scope.'}
        $blocked=$false;try{Assert-WsmCancellationBoundary $otherToken 'AfterChunk'}catch{$blocked=$true};if($blocked){throw 'Unrequested operation was cancelled.'}
        $caught=$null;try{Assert-WsmCancellationBoundary $token 'AfterChunk'}catch{$caught=$_.Exception}
        if($caught -isnot [OperationCanceledException] -or $caught.Data['CancellationBoundary'] -cne 'AfterChunk' -or $caught.Data['OperationId'] -cne $operation -or $caught.Data['AutomaticRetrySafe'] -ne $false){throw 'Typed cancellation boundary lost scoped review/reconciliation metadata.'}
        # Two concurrent owners serialize on the marker-specific lock; the first durable decision/time wins.
        $raceOperation=[Guid]::NewGuid().ToString();$raceToken=New-WsmCancellationToken $pair $plan $manifest $raceOperation $Root;[void](Get-WsmOperationPaths $Root $pair);$raceTokenPath=Join-Path $Root 'race-token.json';Write-WsmJson $raceTokenPath $raceToken
        $requesterPath=Join-Path $Root 'cancel-requester.ps1';$requesterLines=@('param([string]$Repo,[string]$TokenPath,[string]$GatePath,[string]$ResultPath,[string]$Owner,[string]$Evidence)','. (Join-Path $Repo ''src\Core.ps1'')','. (Join-Path $Repo ''src\MigrationContracts.ps1'')','. (Join-Path $Repo ''src\Cancellation.ps1'')','function Protect-WsmDirectory([string]$Path){$t=Read-WsmJson $TokenPath;$expected=Join-Path $t.StateDirectory $t.PairId;if([IO.Path]::GetFullPath($Path) -ine [IO.Path]::GetFullPath($expected)){throw ''Fixture ACL seam rejected a path outside its operation temp root.''}}','function Assert-WsmCancellationDirectoryProtection([string]$Path){$t=Read-WsmJson $TokenPath;$expected=Join-Path $t.StateDirectory $t.PairId;if([IO.Path]::GetFullPath($Path) -ine [IO.Path]::GetFullPath($expected)){throw ''Fixture ACL verifier rejected a path outside its operation temp root.''}}','$w=[Diagnostics.Stopwatch]::StartNew();while(-not [IO.File]::Exists($GatePath) -and $w.Elapsed.TotalSeconds -lt 5){Start-Sleep -Milliseconds 10};try{$t=Read-WsmJson $TokenPath;$r=Request-WsmCancellation $t $Owner $Evidence;$o=[pscustomobject]@{Outcome=''Won'';Owner=$r.Owner;Evidence=$r.Evidence;RequestedUtc=$r.RequestedUtc}}catch{$o=[pscustomobject]@{Outcome=''Rejected'';Message=$_.Exception.Message}};[IO.File]::WriteAllText($ResultPath,($o|ConvertTo-Json -Compress),(New-Object Text.UTF8Encoding($true)))');[IO.File]::WriteAllLines($requesterPath,$requesterLines,(New-Object Text.UTF8Encoding($true)))
        $gate=Join-Path $Root 'request-race.start';$workers=New-Object 'System.Collections.Generic.List[Diagnostics.Process]'
        foreach($index in 1,2){$resultPath=Join-Path $Root ('request-race-'+$index+'.json');$owner='Race owner '+$index;$evidence='Race evidence '+$index;$exe=Join-Path $env:windir 'System32\WindowsPowerShell\v1.0\powershell.exe';$info=New-Object Diagnostics.ProcessStartInfo;$info.FileName=$exe;$args=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$requesterPath,$Repo,$raceTokenPath,$gate,$resultPath,$owner,$evidence);$info.Arguments=(@($args|ForEach-Object {ConvertTo-WsmWindowsArgument ([string]$_)}) -join ' ');$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$process=New-Object Diagnostics.Process;$process.StartInfo=$info;if(-not $process.Start()){throw 'Could not start concurrent cancellation requester.'};$workers.Add($process)}
        [IO.File]::WriteAllText($gate,'go');foreach($process in $workers){if(-not $process.WaitForExit(10000)){try{$process.Kill()}catch{};[void]$process.WaitForExit(2000);throw 'Concurrent cancellation writer exceeded its bounded deadline.'}}
        $raceResults=@(1,2|ForEach-Object {Read-WsmJson (Join-Path $Root ('request-race-'+$_+'.json'))});if(@($raceResults|Where-Object Outcome -EQ Won).Count -ne 1 -or @($raceResults|Where-Object Outcome -EQ Rejected).Count -ne 1){throw 'Concurrent cancellation writers did not produce exactly one retained request and one conflict.'};$raceMarker=Read-WsmJson $raceToken.RequestPath;$winner=@($raceResults|Where-Object Outcome -EQ Won)[0];if($raceMarker.Owner -cne $winner.Owner -or $raceMarker.Evidence -cne $winner.Evidence -or $raceMarker.RequestedUtc -cne $winner.RequestedUtc){throw 'Concurrent conflicting writer replaced the first durable cancellation owner/evidence/time.'};foreach($process in $workers){$process.Dispose()}
        $badToken=$token.PSObject.Copy();$badToken.RequestPath=Join-Path $Root 'arbitrary.json';$blocked=$false;try{Test-WsmCancellationRequested $badToken|Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Cancellation token accepted an arbitrary marker path.'}
        $badToken=ConvertFrom-WsmJson ($token|ConvertTo-Json -Depth 10);$badToken|Add-Member NoteProperty UnreviewedCallback 'Invoke arbitrary code' -Force;$blocked=$false;try{Test-WsmCancellationRequested $badToken|Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Cancellation token accepted an unknown callback field.'}
        $badToken=ConvertFrom-WsmJson ($token|ConvertTo-Json -Depth 10);$badToken.PSObject.Properties.Remove('CreatedUtc');$blocked=$false;try{Test-WsmCancellationRequested $badToken|Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Cancellation token accepted a missing creation timestamp.'}
        $badToken=ConvertFrom-WsmJson ($token|ConvertTo-Json -Depth 10);$badToken.CreatedUtc=123;$blocked=$false;try{Test-WsmCancellationRequested $badToken|Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Cancellation token accepted a wrong-type creation timestamp.'}
        $requestPath=$token.RequestPath;$marker=Read-WsmJson $requestPath;$marker.PlanHash='c'*64;Write-WsmJson $requestPath $marker;$blocked=$false;try{Test-WsmCancellationRequested $token|Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Mismatched/tampered marker scope was accepted.'}
        if(-not ('WsmProgressFixtureStream' -as [type])){Add-Type -TypeDefinition @"
using System;using System.IO;using System.Threading;
public sealed class WsmProgressFixtureStream : Stream {
 public static string ProgressPath; public static long ObservedCount; public static string[] ObservedJson; private long length,position;
 public WsmProgressFixtureStream(long size,string path){length=size;position=0;ProgressPath=path;ObservedCount=0;ObservedJson=new string[32];}
 public override bool CanRead{get{return true;}} public override bool CanSeek{get{return true;}} public override bool CanWrite{get{return false;}} public override long Length{get{return length;}} public override long Position{get{return position;}set{position=value;}}
 public override int Read(byte[] buffer,int offset,int count){Thread.Sleep(40);int n=(int)Math.Min(count,length-position);if(n<=0)return 0;Array.Clear(buffer,offset,n);position+=n;if(File.Exists(ProgressPath)){string json=File.ReadAllText(ProgressPath);if(ObservedCount<ObservedJson.Length)ObservedJson[ObservedCount]=json;ObservedCount++;}return n;}
 public override long Seek(long offset,SeekOrigin origin){throw new NotSupportedException();} public override void SetLength(long value){throw new NotSupportedException();} public override void Write(byte[] buffer,int offset,int count){throw new NotSupportedException();} public override void Flush(){}
}
"@}
        $progressToken=New-WsmCancellationToken $pair $plan $manifest ([Guid]::NewGuid().ToString()) $Root;[void](Get-WsmOperationPaths $Root $pair);$progressPath=Get-WsmOperationProgressPath $progressToken;$slowStream=[WsmProgressFixtureStream]::new(2097152,$progressPath);$hashOutput=@(Get-WsmCancellableStreamHash $slowStream $progressToken 'FixtureHashBuffer');$sha=[Security.Cryptography.SHA256]::Create();try{$expectedHash=[BitConverter]::ToString($sha.ComputeHash((New-Object byte[] 2097152))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()};$observed=[WsmProgressFixtureStream]::ObservedJson | Where-Object {$_};if($hashOutput.Count -ne 1 -or $hashOutput[0] -cne $expectedHash -or $observed.Count -lt 1){throw 'Real cancellable-stream hashing did not preserve its hash result while exposing throttled progress.'};$progressRows=@($observed | ForEach-Object {ConvertFrom-WsmJson $_} | Group-Object UpdatedUtc | ForEach-Object {$_.Group[0]});foreach($row in $progressRows){if($row.Kind -cne 'OperationProgress' -or $row.Phase -cne 'FixtureHashBuffer' -or $row.CompletedBytes -le 0 -or $row.TotalBytes -ne 2097152 -or $row.LastActivityUtc -notmatch 'Z$' -or ($row | ConvertTo-Json -Compress) -match [regex]::Escape($Root)){throw 'Stream progress leaked a path or lost its bounded phase/byte/time fields.'}};for($i=1;$i -lt $progressRows.Count;$i++){if(([DateTimeOffset]::Parse($progressRows[$i].UpdatedUtc)-[DateTimeOffset]::Parse($progressRows[$i-1].UpdatedUtc)).TotalMilliseconds -lt 900){throw 'Progress sidecar updates were not throttled to approximately one per second.'}};if([IO.File]::Exists($progressPath)){throw 'Completed cancellable-stream hashing left a stale progress marker.'}
        Write-Host 'PASS: exact pair/plan/manifest/operation/state token binding; no creation on token issue; lock-independent atomic marker; idempotent original owner/evidence/time; conflicts and cross-scope markers rejected; typed boundary cancellation disables automatic retry.'
    } $root $repo
} finally {
    $resolved=[IO.Path]::GetFullPath($root).TrimEnd('\');$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\')
    if($resolved -notmatch '\\wsm-cancel-[0-9a-f]{32}$' -or -not $resolved.StartsWith(($temp+'\'),[StringComparison]::OrdinalIgnoreCase)){throw ('Refusing cancellation fixture cleanup outside its validated test root: '+$resolved)}
    if([IO.Directory]::Exists($resolved)){Remove-Item -LiteralPath $resolved -Recurse -Force}
}
