#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
& $module {
    . (Join-Path $PSScriptRoot '..\src\ServiceSupplement.ps1')
    $script:applied=$null;$script:environment=@();$script:actual=$null;$script:nativeFailure=$false
    function Invoke-WsmServiceSupplementNative {param($Name,$NativeConfig)if($script:nativeFailure){throw (New-Object ComponentModel.Win32Exception(5,'fixture SCM access denied'))};$script:applied=$NativeConfig}
    function Set-WsmServiceEnvironment {param($Name,[string[]]$Values)$script:environment=@($Values)}
    function Get-WsmServiceSupplementState {param($Name)$script:actual}
    function New-NativeServiceFixture {
        $actionOne=New-Object 'System.Object[]' 2;$actionOne[0]=1;$actionOne[1]=[uint32]2500000000
        $actionTwo=New-Object 'System.Object[]' 2;$actionTwo[0]=3;$actionTwo[1]=[uint32]10000
        $nativeActions=New-Object 'System.Object[][]' 2;$nativeActions[0]=$actionOne;$nativeActions[1]=$actionTwo
        $failure=New-Object 'System.Object[]' 4;$failure[0]=[uint32]86400;$failure[1]='';$failure[2]='C:\Example\failure.cmd';$failure[3]=$nativeActions
        $triggerDataItem=New-Object 'System.Object[]' 2;$triggerDataItem[0]=[uint32]2;$triggerDataItem[1]=$triggerData
        $triggerDataItems=New-Object 'System.Object[][]' 1;$triggerDataItems[0]=$triggerDataItem
        $trigger=New-Object 'System.Object[]' 4;$trigger[0]=[uint32]4;$trigger[1]=[uint32]1;$trigger[2]='b7569e07-8421-4ee0-ad10-86915afdad09';$trigger[3]=$triggerDataItems
        $triggers=New-Object 'System.Object[][]' 1;$triggers[0]=$trigger
        $native=New-Object 'System.Object[]' 9;$native[0]=[uint32]16;$native[1]=[uint32]1;$native[2]='';$native[3]=$true;$native[4]=$failure;$native[5]=$true;$native[6]=[uint32]3;$native[7]=[string[]]@('SeChangeNotifyPrivilege','SeImpersonatePrivilege');$native[8]=$triggers
        return ,$native
    }
    $triggerData=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes("443`0TCP`0`0"))
    $supplement=[pscustomobject][ordered]@{ServiceType='Win32OwnProcess';ErrorControl='Normal';LoadOrderGroup='';DelayedAutoStart=$true;FailureActions=[pscustomobject][ordered]@{ResetPeriodSeconds=86400;RebootMessage='';Command='C:\Example\failure.cmd';Actions=@([pscustomobject]@{Type='Restart';DelayMilliseconds=[long]2500000000},[pscustomobject]@{Type='RunCommand';DelayMilliseconds=[long]10000})};FailureActionsOnNonCrashFailures=$true;ServiceSidType='Restricted';RequiredPrivileges=@('SeChangeNotifyPrivilege','SeImpersonatePrivilege');Environment=@('APP_HOME=C:\Example','FEATURE=enabled');Triggers=@([pscustomobject][ordered]@{Type=4;Action='Start';Subtype='b7569e07-8421-4ee0-ad10-86915afdad09';DataItems=@([pscustomobject][ordered]@{Type=2;DataBase64=$triggerData})})}
    $null=Assert-WsmServiceSupplement $supplement;$native=ConvertTo-WsmServiceSupplementNativeInput $supplement
    if($native.ErrorControl -ne 1 -or $native.ServiceSidType -ne 3 -or $native.ActionTypes.Count -ne 2 -or $native.ActionTypes[0] -ne 1 -or $native.ActionTypes[1] -ne 3 -or [long]$native.ActionDelays[0] -ne 2500000000){throw 'Native failure-action mapping lost an enum or full-width delay.'}
    if($native.Triggers.Count -ne 1 -or $native.Triggers[0][0] -ne 4 -or $native.Triggers[0][1] -ne 1 -or $native.Triggers[0][2] -cne $supplement.Triggers[0].Subtype -or $native.Triggers[0][3][0][1] -cne $triggerData){throw 'Native service-trigger mapping is not exact.'}
    $script:actual=ConvertFrom-WsmServiceSupplementState (New-NativeServiceFixture) $supplement.Environment
    $exactCheck=Test-WsmServiceSupplement $supplement $script:actual -Phase Final;if(-not $exactCheck.Passed){throw ('Exact supplementary service configuration did not verify: '+($exactCheck.Problems -join '; ')+'; actual='+($script:actual | ConvertTo-Json -Depth 12 -Compress))}
    $script:actual.Triggers[0].Subtype=$script:actual.Triggers[0].Subtype.ToUpperInvariant();if(-not (Test-WsmServiceSupplement $supplement $script:actual -Phase Final).Passed){throw 'Equivalent uppercase trigger GUID was treated as configuration drift.'};$script:actual.Triggers[0].Subtype=$supplement.Triggers[0].Subtype
    $script:actual.ErrorControl='Critical';if((Test-WsmServiceSupplement $supplement $script:actual -Phase Final).Passed){throw 'ErrorControl drift was missed'};$script:actual.ErrorControl='Normal'
    $script:actual.FailureActions.Actions[0].DelayMilliseconds=1;if((Test-WsmServiceSupplement $supplement $script:actual -Phase Final).Passed){throw 'Full-width failure-action delay drift was missed'};$script:actual.FailureActions.Actions[0].DelayMilliseconds=[long]2500000000
    $script:actual.Environment=@('APP_HOME=C:\Changed');if((Test-WsmServiceSupplement $supplement $script:actual -Phase Final).Passed){throw 'Service environment drift was missed'};$script:actual.Environment=@('FEATURE=enabled','APP_HOME=C:\Example')
    $script:actual.Triggers=@();if((Test-WsmServiceSupplement $supplement $script:actual -Phase Final).Passed){throw 'Missing configured service triggers were accepted'};$script:actual=ConvertFrom-WsmServiceSupplementState (New-NativeServiceFixture) $supplement.Environment
    $staged=Get-WsmServiceSupplementForPhase $supplement Staged;if($staged.Triggers.Count -ne 0 -or $staged.FailureActionsOnNonCrashFailures -or @($staged.FailureActions.Actions | Where-Object {$_.Type -ne 'None' -or $_.DelayMilliseconds -ne 0}).Count){throw 'Staged service recovery configuration was not made inert.'}
    $script:actual=$staged; if(-not (Test-WsmServiceSupplement $supplement $script:actual -Phase Staged).Passed){throw 'Exact safe staged supplement did not verify.'}
    Set-WsmServiceSupplement 'FixtureService' $supplement -Phase Staged | Out-Null;if(-not $script:applied -or $script:applied.Triggers.Count -ne 0 -or @($script:environment).Count -ne 2){throw 'Staged native/environment seam was not applied and read back.'}
    $script:actual=ConvertFrom-WsmServiceSupplementState (New-NativeServiceFixture) $supplement.Environment;Set-WsmServiceSupplement 'FixtureService' $supplement -Phase Final | Out-Null;if($script:applied.Triggers.Count -ne 1 -or [long]$script:applied.ActionDelays[0] -ne 2500000000){throw 'Final native supplement did not restore original trigger and recovery values.'}
    $script:nativeFailure=$true;$nativeError=$false;try{Set-WsmServiceSupplement 'FixtureService' $supplement -Phase Final | Out-Null}catch{$nativeError=$_.Exception.Message -like '*fixture SCM access denied*'};$script:nativeFailure=$false;if(-not $nativeError){throw 'Native SCM error was hidden or converted to success.'}
    foreach($unsupported in @('Win32ShareProcess','KernelDriver','FileSystemDriver','UnsupportedServiceType:32')){$copy=$supplement | ConvertTo-Json -Depth 12 | ConvertFrom-Json;$copy.ServiceType=$unsupported;$blocked=$false;try{Assert-WsmServiceSupplement $copy | Out-Null}catch{$blocked=$true};if(-not $blocked){throw ('Unsupported service type accepted: '+$unsupported)}}
    $copy=$supplement | ConvertTo-Json -Depth 12 | ConvertFrom-Json;$copy.Triggers[0].Type=99;$blocked=$false;try{Assert-WsmServiceSupplement $copy | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Unknown service trigger type accepted.'}
    $copy=$supplement | ConvertTo-Json -Depth 12 | ConvertFrom-Json;$copy.Triggers[0].DataItems[0].DataBase64=[Convert]::ToBase64String((New-Object byte[] 1025));$blocked=$false;try{Assert-WsmServiceSupplement $copy | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Oversized service trigger data accepted.'}
    $copy=$supplement | ConvertTo-Json -Depth 12 | ConvertFrom-Json;$copy.DelayedAutoStart=$true;$copy.LoadOrderGroup='LegacyGroup';$blocked=$false;try{Assert-WsmServiceSupplement $copy | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Incompatible delayed start/load-order group combination accepted.'}
    $copy=$supplement | ConvertTo-Json -Depth 12 | ConvertFrom-Json;$copy.FailureActions.Actions=@();$blocked=$false;try{Assert-WsmServiceSupplement $copy | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Unrepresentable empty failure-action reset period accepted.'}
    $blocked=$false;try{Assert-WsmServiceSupplementName '..\Other'}catch{$blocked=$true};if(-not $blocked){throw 'Service name path traversal accepted.'}
    Initialize-WsmServiceSupplementNative
    $multi=[Text.Encoding]::Unicode.GetBytes("first`0second`0`0");$parsed=[WsmServiceSupplementNative]::ParseMultiSzFixture($multi);if($parsed.Count -ne 2 -or $parsed[0] -cne 'first' -or $parsed[1] -cne 'second'){throw 'Bounded MULTI_SZ parser failed an exact-sized unmanaged fixture.'}
    $empty=[WsmServiceSupplementNative]::ParseMultiSzFixture([byte[]](0,0,0,0));if($empty.Count -ne 0){throw 'Empty MULTI_SZ did not parse as an empty list.'}
    $truncated=$false;try{[void][WsmServiceSupplementNative]::ParseMultiSzFixture([byte[]](65,0,0,0))}catch{$truncated=$_.Exception.Message -like '*unterminated MULTI_SZ*'};if(-not $truncated){throw 'Unterminated bounded MULTI_SZ was not rejected.'}
    $triggerFixture=[WsmServiceSupplementNative]::ParseTriggerFixture([Text.Encoding]::Unicode.GetBytes("443`0TCP`0`0"),$false);if($triggerFixture.Length -ne 1 -or [uint32]$triggerFixture[0][0] -ne 4 -or [uint32]$triggerFixture[0][1] -ne 1 -or $triggerFixture[0][2] -cne 'b7569e07-8421-4ee0-ad10-86915afdad09' -or $triggerFixture[0][3][0][1] -cne $triggerData){throw 'Bounded nested trigger-buffer parser lost a trigger field.'}
    $emptyTriggerData=[WsmServiceSupplementNative]::ParseEmptyTriggerDataFixture();if($emptyTriggerData.Length -ne 1 -or $emptyTriggerData[0][3].Length -ne 0){throw 'Empty bounded trigger data array did not parse.'}
    $triggerTruncated=$false;try{[void][WsmServiceSupplementNative]::ParseTriggerFixture([Text.Encoding]::Unicode.GetBytes("443`0TCP`0`0"),$true)}catch{$triggerTruncated=$_.Exception.Message -like '*out-of-buffer*' -or $_.Exception.Message -like '*exceed their query buffer*'};if(-not $triggerTruncated){throw 'Nested trigger data extending past its buffer was not rejected.'}
    $guidTruncated=$false;try{[WsmServiceSupplementNative]::ParseTruncatedTriggerGuidFixture()}catch{$guidTruncated=$_.Exception.Message -like '*subtype GUID exceeds its query buffer*'};if(-not $guidTruncated){throw 'A truncated trigger GUID was not rejected before unmarshalling.'}
    $rootTruncated=$false;try{[WsmServiceSupplementNative]::ParseTruncatedTriggerRootFixture()}catch{$rootTruncated=$_.Exception.Message -like '*trigger-info root exceeds its query buffer*'};if(-not $rootTruncated){throw 'A truncated trigger root struct was not rejected before unmarshalling.'}
    $queryRootTruncated=$false;try{[WsmServiceSupplementNative]::ParseTruncatedFailureActionsRootFixture()}catch{$queryRootTruncated=$_.Exception.Message -like '*failure-actions root exceeds its query buffer*'};if(-not $queryRootTruncated){throw 'A truncated QueryServiceConfig2 root struct was not rejected before unmarshalling.'}
    $noStartMask=[WsmServiceSupplementNative]::RequiredServiceAccessFixture([int[]]@(0,2));if(($noStartMask -band 0x10) -ne 0){throw 'SERVICE_START was requested without an SC_ACTION_RESTART.'}
    $restartMask=[WsmServiceSupplementNative]::RequiredServiceAccessFixture([int[]]@(0,1));if(($restartMask -band 0x10) -eq 0){throw 'SERVICE_START was omitted for an SC_ACTION_RESTART.'}
    $rebootOnlyMask=[WsmServiceSupplementNative]::RequiredServiceAccessFixture([int[]]@(2));if(($rebootOnlyMask -band 0x10) -ne 0){throw 'SC_ACTION_REBOOT unnecessarily requested SERVICE_START.'}
    $privilegeEvents=New-Object 'System.Collections.Generic.List[string]';$acquire=[Func[Action]]{[void]$privilegeEvents.Add('enabled');return [Action]{[void]$privilegeEvents.Add('restored')}};$work=[Action]{[void]$privilegeEvents.Add('applied')};[WsmServiceSupplementNative]::ExecuteWithShutdownPrivilege($work,$acquire);if(($privilegeEvents -join ',') -cne 'enabled,applied,restored'){throw 'Shutdown privilege scope did not restore the original token state after a successful native action.'}
    $privilegeEvents.Clear();$failingWork=[Action]{[void]$privilegeEvents.Add('applied');throw (New-Object InvalidOperationException 'fixture native failure')};$workError=$false;try{[WsmServiceSupplementNative]::ExecuteWithShutdownPrivilege($failingWork,$acquire)}catch{$workError=$_.Exception.Message -like '*fixture native failure*'};if(-not $workError -or ($privilegeEvents -join ',') -cne 'enabled,applied,restored'){throw 'Shutdown privilege scope failed to restore the original token state after a native exception.'}
    $failedEnable=[Func[Action]]{throw (New-Object ComponentModel.Win32Exception(1300,'fixture ERROR_NOT_ALL_ASSIGNED'))};$script:workStarted=$false;$neverWork=[Action]{$script:workStarted=$true};$privilegeError=$false;try{[WsmServiceSupplementNative]::ExecuteWithShutdownPrivilege($neverWork,$failedEnable)}catch{$privilegeError=$_.Exception.GetBaseException().NativeErrorCode -eq 1300};if(-not $privilegeError -or $script:workStarted){throw 'Ineligible shutdown token was not rejected before the operation.'}
    Write-Host 'PASS: typed Win32 own-process supplement conversion; exact uint failure delays and trigger fields; scoped SERVICE_START and shutdown privilege; previous token state restored on success/failure; read-back drift rejection; unsupported-value rejection; bounded empty/truncated trigger and MULTI_SZ fixtures. No SCM service, registry, real token privilege, or reboot operation performed.'
}
