# End-to-end local fixture for the isolated delta transport/apply path. It creates
# temporary package roots and a temporary target tree; it never changes host settings.
#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$contractsPath=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\src\DeltaContracts.ps1'))
$workflowPath=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\src\DeltaWorkflow.ps1'))
& $module {
    param($ContractsPath,$WorkflowPath)
    . $ContractsPath
    . $WorkflowPath
    function Assert-DeltaWorkflow([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
    # The cancellation fixture writes only a typed request under its temporary
    # state root; no host settings or security privileges are changed.
    if(-not (Get-Command Assert-WsmCancellationBoundary -ErrorAction SilentlyContinue)){function Assert-WsmCancellationBoundary($Token,[string]$Phase){if($Token){throw 'Fixture does not authorize cancellation-token execution.'}}}
    function Get-DeltaWorkflowHash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
    function Write-DeltaWorkflowPackage([string]$Root,$Plan,[string]$PlanHash,[long]$Generation,[string]$BaseHash,[bool]$Final,[string]$FreezeHash,$Item){
        [void][IO.Directory]::CreateDirectory($Root);$payload=Join-Path $Root 'payload';[void][IO.Directory]::CreateDirectory($payload)
        $index=Join-Path $Root 'artifacts.jsonl';$writer=New-Object IO.StreamWriter($index,$false,(New-Object Text.UTF8Encoding($false)));$files=[long]0;$bytes=[long]0;$records=[long]0
        try{
            foreach($entry in (Get-WsmScopeEntries $Item.MigrationSpec $Root)){
                $metadata=Get-WsmFileMetadata $entry.SourcePath $Item.MigrationSpec.Metadata;$data=$null
                if(-not $entry.Directory){$data=Write-WsmPayloadFile $entry.SourcePath $payload 65536;$files++;$bytes+=$data.Bytes}
                $row=[pscustomobject]@{ItemId=$Item.ItemId;RelativePath=$entry.RelativePath;Directory=[bool]$entry.Directory;Metadata=$metadata;Data=$data};$writer.WriteLine(($row | ConvertTo-Json -Compress -Depth 20));$records++
            }
        }finally{$writer.Dispose()}
        $manifest=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='MigrationPackage';PackageId=[Guid]::NewGuid().ToString();BatchId=$Plan.BatchId;PairId=$Plan.PairId;ApprovalId=$Plan.ApprovalId;PlanHash=$PlanHash;Source=$Plan.Source;Target=$Plan.Target;InventoryRevision=1;DecisionRevision=1;Generation=$Generation;BaseManifestHash=$BaseHash;Final=$Final;FreezeHash=$FreezeHash;ArtifactsHash=(Get-DeltaWorkflowHash $index);Files=$files;Bytes=$bytes;Records=$records;ChunkBytes=65536;Mode='IsolatedPilot'}
        $manifestPath=Join-Path $Root 'manifest.json';Write-WsmJson $manifestPath $manifest
        [pscustomobject]@{Root=$Root;ManifestPath=$manifestPath;Manifest=$manifest;ManifestHash=(Get-DeltaWorkflowHash $manifestPath);IndexPath=$index;Plan=$Plan}
    }
    function New-DeltaWorkflowState($Paths,$Package,$Item,[string]$ActualHash){
        $rows=@([pscustomobject]@{ItemId=$Item.ItemId;Status='Succeeded';CreatedByTool=$true;ActualHash=$ActualHash;Backup='';Target=$Item.MigrationSpec.TargetPath;Error='';NativeCode=0})
        foreach($other in $Package.Plan.Items){if($other.ItemId -cne $Item.ItemId -and $other.Decision -eq 'Include' -and $other.MigrationSpec.Adapter -ne 'FileScope'){$rows+=@([pscustomobject]@{ItemId=$other.ItemId;Status='Succeeded';CreatedByTool=$true;ActualHash='fixture-adapter-hash';Backup='';Target='';Error='';NativeCode=0})}}
        $manualItems=@($Package.Plan.Items | Where-Object {$_.Decision -eq 'Include' -and $_.MigrationSpec.Adapter -eq 'ManualWorkflow'});$evidence=@();foreach($manual in $manualItems){$rows=@($rows | Where-Object ItemId -CNE $manual.ItemId)+@([pscustomobject]@{ItemId=$manual.ItemId;Status='ManualEvidenceRequired';CreatedByTool=$false;ActualHash='';Backup='';Target='';Error='Dedicated product procedure and business evidence required';NativeCode=$null});$evidence+=@([pscustomobject]@{ItemId=$manual.ItemId;Check='ManualRestore';Passed=$true;ManifestHash=$Package.ManifestHash;Generation=1;Owner='fixture manual operator';Evidence='temporary local manual procedure assertion';Utc=[DateTime]::UtcNow.ToString('o');ExpiresUtc=[DateTime]::UtcNow.AddHours(2).ToString('o');ManualEvidence=$true})}
        $stage='Succeeded';if($manualItems.Count){$stage='ManualEvidenceRequired'};$state=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='OperationState';BatchId=$Package.Manifest.BatchId;PairId=$Package.Manifest.PairId;TargetFingerprint=$Package.Manifest.Target.Fingerprint;PlanHash=$Package.Manifest.PlanHash;RunId=[Guid]::NewGuid().ToString();ManifestHash=$Package.ManifestHash;Generation=1;Stage=$stage;Sequence=0;ResultSequence=0;JournalHash=('0'*64);JournalSegment=0;Items=$rows;Evidence=$evidence;Cutover=$null;PendingOperations=@()}
        Write-WsmJson $Paths.State $state
    }
    function Reset-DeltaWorkflowTarget([string]$TargetRoot,$Rows,$BasePackage,$Item){
        $full=[IO.Path]::GetFullPath($TargetRoot);$temp=[IO.Path]::GetFullPath($root);if(-not $full.StartsWith($temp.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Fixture reset target escaped its owned temporary root.'}
        if([IO.Directory]::Exists($full)){Remove-Item -LiteralPath $full -Recurse -Force};[void][IO.Directory]::CreateDirectory($full)
        foreach($row in $Rows){$path=$full;if($row.RelativePath){$path=Join-Path $full $row.RelativePath};if($row.Directory){if(-not [IO.Directory]::Exists($path)){[void][IO.Directory]::CreateDirectory($path)}}else{Restore-WsmPayloadBytes $row $BasePackage.Root $path}}
        foreach($row in @($Rows | Where-Object {-not $_.Directory})){if($row.ItemId -ceq $Item.ItemId){$path=$full;if($row.RelativePath){$path=Join-Path $full $row.RelativePath};Set-WsmFileMetadata $path $row.Metadata @{}}}
        foreach($row in @($Rows | Where-Object Directory | Sort-Object {if($_.RelativePath){$_.RelativePath.Split([char]92).Count}else{0}} -Descending)){if($row.ItemId -ceq $Item.ItemId){$path=$full;if($row.RelativePath){$path=Join-Path $full $row.RelativePath};Set-WsmFileMetadata $path $row.Metadata @{}}}
    }
    function Invoke-FixtureDeltaExport($Base,$Current,[string]$PlanPath,[string]$PlanHash,[string]$ChangesPath,[string]$SummaryPath,[string]$SummaryHash,[string]$OutputPath,$CancellationToken){
        Export-WsmArtifactDeltaZip -BaseManifestPath $Base.ManifestPath -BaseManifestHash $Base.ManifestHash -BasePlanPath $PlanPath -BasePlanHash $PlanHash -CurrentManifestPath $Current.ManifestPath -CurrentManifestHash $Current.ManifestHash -CurrentPlanPath $PlanPath -CurrentPlanHash $PlanHash -SummaryPath $SummaryPath -SummaryHash $SummaryHash -ChangesPath $ChangesPath -OutputPath $OutputPath -CancellationToken $CancellationToken
    }
    $root=Join-Path ([IO.Path]::GetTempPath()) ('dwt-'+[Guid]::NewGuid().ToString('N').Substring(0,12));[void][IO.Directory]::CreateDirectory($root)
    try{
        $source=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=('a'*64);Name='fixture-source'};$targetHost=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=('b'*64);Name='fixture-target'}
        function Get-WsmMachineIdentity { [pscustomobject]@{Fingerprint=('b'*64);Name='fixture-target';OS='Windows Server fixture';Version='10.0';IsServer=$true;Administrator=$true;Is64Bit=$true} }
        $script:DeltaFixtureServiceState='Exact'
        function Get-WsmAdapterState($Spec){[pscustomobject]@{Exists=($script:DeltaFixtureServiceState -ne 'Absent');FixtureState=$script:DeltaFixtureServiceState}}
        function Test-WsmAdapterConfiguration($Spec,[string]$Phase='Staged',[object[]]$OwnedReceipts=@()){if($script:DeltaFixtureServiceState -ceq 'AccessDenied'){throw (New-Object UnauthorizedAccessException('Fixture service readback access denied.'))};[pscustomobject]@{Passed=($script:DeltaFixtureServiceState -ceq 'Exact');Problems=@(if($script:DeltaFixtureServiceState -cne 'Exact'){'Fixture service configuration drift'});Actual=[pscustomobject]@{State=$script:DeltaFixtureServiceState};Phase=$Phase}}
        $sourceRoot=Join-Path $root 'source';$targetRoot=Join-Path $root 'target';$stateRoot=Join-Path $root 'target-state';[void][IO.Directory]::CreateDirectory($sourceRoot);[void][IO.Directory]::CreateDirectory($targetRoot)
        [IO.File]::WriteAllText((Join-Path $sourceRoot 'keep.txt'),'stable content')
        [IO.File]::WriteAllText((Join-Path $sourceRoot 'change.txt'),'old content')
        [IO.File]::WriteAllText((Join-Path $sourceRoot 'remove.txt'),'owned deletion')
        $itemId='1'*64;$spec=[pscustomobject][ordered]@{Adapter='FileScope';Owner='temporary test fixture';Evidence='temporary test fixture';SourcePath=$sourceRoot;TargetPath=$targetRoot;ExcludedRelativePaths=@();Consistency='Immutable';Metadata='DaclOwner';ConflictPolicy='ReplaceOwned'}
        $serviceId='2'*64;$manualId='3'*64;$serviceSupplement=[pscustomobject]@{ServiceType='Win32OwnProcess';ErrorControl='Normal';LoadOrderGroup='';DelayedAutoStart=$false;FailureActions=[pscustomobject]@{ResetPeriodSeconds=0;RebootMessage='';Command='';Actions=@()};FailureActionsOnNonCrashFailures=$false;ServiceSidType='None';RequiredPrivileges=@();Environment=@();Triggers=@()};$serviceSpec=[pscustomobject]@{Adapter='Service';Owner='temporary test fixture';Evidence='temporary test fixture';Desired=[pscustomobject]@{Name='FixtureDeltaSvc';DisplayName='Fixture delta service';BinaryPathName='C:\Fixture\service.exe';Account='LocalSystem';Dependencies=@();Description='fixture';Supplement=$serviceSupplement}};$manualSpec=[pscustomobject]@{Adapter='ManualWorkflow';Owner='temporary test fixture';Evidence='temporary test fixture';Product='Fixture product';Procedure='Fixture staged restore and readback';Artifacts=@();BusinessChecks=@('Fixture business acceptance')}
        $plan=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='MigrationPlan';BatchId=[Guid]::NewGuid().ToString();PairId=[Guid]::NewGuid().ToString();ApprovalId=[Guid]::NewGuid().ToString();Source=$source;Target=$targetHost;Mode='IsolatedPilot';ToolFingerprint=(Get-WsmToolFingerprint);InventoryRevision=1;DecisionRevision=1;Items=@([pscustomobject]@{ItemId=$itemId;Name='Fixture files';Decision='Include';MigrationSpec=$spec},[pscustomobject]@{ItemId=$serviceId;Name='Fixture service';Decision='Include';MigrationSpec=$serviceSpec},[pscustomobject]@{ItemId=$manualId;Name='Fixture manual workflow';Decision='Include';MigrationSpec=$manualSpec})}
        $planPath=Join-Path $root 'plan.json';Write-WsmJson $planPath $plan;$planHash=Get-DeltaWorkflowHash $planPath
        $base=Write-DeltaWorkflowPackage (Join-Path $root 'base') $plan $planHash 1 '' $false '' ([pscustomobject]@{ItemId=$itemId;MigrationSpec=$spec})
        # Construct the target exactly from the trusted base index, then seed the
        # durable ownership checkpoint expected from an already verified generation 1.
        $baseItem=$plan.Items[0];$baseRows=@(Read-WsmDeltaStreamRecords (Join-Path $base.Root 'artifacts.jsonl') {param($r) $r})
        [void][IO.Directory]::CreateDirectory($targetRoot)
        foreach($row in $baseRows){$path=$targetRoot;if($row.RelativePath){$path=Join-Path $targetRoot $row.RelativePath};if($row.Directory){if(-not [IO.Directory]::Exists($path)){[void][IO.Directory]::CreateDirectory($path)}}else{Restore-WsmPayloadBytes $row $base.Root $path}}
        foreach($row in $baseRows){if(-not $row.Directory){$path=$targetRoot;if($row.RelativePath){$path=Join-Path $targetRoot $row.RelativePath};Set-WsmFileMetadata $path $row.Metadata @{}}}
        foreach($row in @($baseRows | Where-Object Directory | Sort-Object {if($_.RelativePath){$_.RelativePath.Split([char]92).Count}else{0}} -Descending)){$path=$targetRoot;if($row.RelativePath){$path=Join-Path $targetRoot $row.RelativePath};Set-WsmFileMetadata $path $row.Metadata @{}}
        $baseDigest=Get-WsmFileScopeDigest $targetRoot $spec.Metadata;$paths=Get-WsmOperationPaths $stateRoot $plan.PairId
        New-DeltaWorkflowState $paths $base $baseItem $baseDigest
        [IO.File]::WriteAllText((Join-Path $sourceRoot 'change.txt'),'new content with a new chunk')
        [IO.File]::Delete((Join-Path $sourceRoot 'remove.txt'))
        [IO.File]::WriteAllText((Join-Path $sourceRoot 'added.txt'),'new owned file')
        $freeze=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='SourceFreeze';FreezeId=[Guid]::NewGuid().ToString();BatchId=$plan.BatchId;PairId=$plan.PairId;ApprovalId=$plan.ApprovalId;PlanHash=$planHash;SourceHostId=$source.HostId;SourceFingerprint=$source.Fingerprint;Owner='fixture owner';Evidence='temporary fixture only';Acknowledgement='OWNER-CONFIRMED-QUIESCENCE';SourceIdentityReleased=$true;ReleaseEvidence='fixture only';Activities=@();QuiescedSettingsHashes=@();ProducedUtc=[DateTime]::UtcNow.ToString('o');ExpiresUtc=[DateTime]::UtcNow.AddHours(2).ToString('o');Scope='temporary local fixture'}
        $currentRoot=Join-Path $root 'current';[void][IO.Directory]::CreateDirectory($currentRoot);$freezePath=Join-Path $currentRoot 'freeze.json';Write-WsmJson $freezePath $freeze;$freezeHash=Get-DeltaWorkflowHash $freezePath
        $current=Write-DeltaWorkflowPackage $currentRoot $plan $planHash 2 $base.ManifestHash $true $freezeHash ([pscustomobject]@{ItemId=$itemId;MigrationSpec=$spec})
        $changes=Join-Path $root 'changes.jsonl';$summary=Join-Path $root 'summary.json'
        $delta=New-WsmArtifactDeltaManifest -BaseManifestPath $base.ManifestPath -BaseManifestHash $base.ManifestHash -BasePlanPath $planPath -BasePlanHash $planHash -CurrentManifestPath $current.ManifestPath -CurrentManifestHash $current.ManifestHash -CurrentPlanPath $planPath -CurrentPlanHash $planHash -OutputPath $changes -SummaryPath $summary -OwnedItemIds @($itemId)
        foreach($kind in @('Pair','Plan','Manifest','State')){$badDir=Join-Path $root ('bad-export-'+$kind.ToLowerInvariant());$badOutput=Join-Path $badDir 'delta.zip';$tokenPair=$plan.PairId;$tokenPlan=$planHash;$tokenManifest=$current.ManifestHash;$tokenState=$badDir;if($kind -eq 'Pair'){$tokenPair=[Guid]::NewGuid().ToString()};if($kind -eq 'Plan'){$tokenPlan='c'*64};if($kind -eq 'Manifest'){$tokenManifest='d'*64};if($kind -eq 'State'){$tokenState=Join-Path $badDir 'wrong-state'};$badToken=New-WsmCancellationToken $tokenPair $tokenPlan $tokenManifest ([Guid]::NewGuid().ToString()) $tokenState;$rejected=$false;$cancelError=''
            try{Invoke-FixtureDeltaExport $base $current $planPath $planHash $changes $summary $delta.SummaryHash $badOutput $badToken|Out-Null}catch{$cancelError=$_.Exception.Message;$rejected=$cancelError -match 'Cancellation token is not bound'}
            Assert-DeltaWorkflow ($rejected -and -not [IO.Directory]::Exists($badDir) -and -not [IO.File]::Exists($badOutput)) ('Export rejected for the wrong reason or mutated output for '+$kind+': '+$cancelError)
        }
        $zip=Join-Path $root 'incremental.zip';$export=Export-WsmArtifactDeltaZip -BaseManifestPath $base.ManifestPath -BaseManifestHash $base.ManifestHash -BasePlanPath $planPath -BasePlanHash $planHash -CurrentManifestPath $current.ManifestPath -CurrentManifestHash $current.ManifestHash -CurrentPlanPath $planPath -CurrentPlanHash $planHash -SummaryPath $summary -SummaryHash $delta.SummaryHash -ChangesPath $changes -OutputPath $zip
        foreach($kind in @('Pair','Plan','Manifest','State')){$badDir=Join-Path $root ('bad-import-'+$kind.ToLowerInvariant());$tokenPair=$plan.PairId;$tokenPlan=$planHash;$tokenManifest=$current.ManifestHash;$tokenState=$badDir;if($kind -eq 'Pair'){$tokenPair=[Guid]::NewGuid().ToString()};if($kind -eq 'Plan'){$tokenPlan='c'*64};if($kind -eq 'Manifest'){$tokenManifest='d'*64};if($kind -eq 'State'){$tokenState=Join-Path $badDir 'wrong-state'};$badToken=New-WsmCancellationToken $tokenPair $tokenPlan $tokenManifest ([Guid]::NewGuid().ToString()) $tokenState;$rejected=$false
            try{Import-WsmArtifactDeltaZip -TransportPath $zip -ExpectedHash $export.SHA256 -OutputDirectory $badDir -CancellationToken $badToken|Out-Null}catch{$rejected=$_.Exception.Message -match 'Cancellation token is not bound'}
            Assert-DeltaWorkflow ($rejected -and -not [IO.Directory]::Exists($badDir)) ('Import accepted a mismatched cancellation binding or created its output directory for '+$kind+'.')
        }
        $import=Import-WsmArtifactDeltaZip -TransportPath $zip -ExpectedHash $export.SHA256 -OutputDirectory (Join-Path $root 'in')
        Assert-DeltaWorkflow ($import.Valid -and $import.Generation -eq 2 -and $import.ChangedRecords -eq 3) 'ZIP import did not validate the complete incremental transport.'
        $stateHashBeforeWrongToken=Get-DeltaWorkflowHash $paths.State
        foreach($kind in @('Pair','Plan','Manifest','State')){$tokenPair=$plan.PairId;$tokenPlan=$planHash;$tokenManifest=$current.ManifestHash;$tokenState=$stateRoot;if($kind -eq 'Pair'){$tokenPair=[Guid]::NewGuid().ToString()};if($kind -eq 'Plan'){$tokenPlan='c'*64};if($kind -eq 'Manifest'){$tokenManifest='d'*64};if($kind -eq 'State'){$tokenState=Join-Path $stateRoot 'wrong-state'};$badToken=New-WsmCancellationToken $tokenPair $tokenPlan $tokenManifest ([Guid]::NewGuid().ToString()) $tokenState;$rejected=$false
            try{Invoke-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $stateRoot -CancellationToken $badToken -Confirm:$false|Out-Null}catch{$rejected=$_.Exception.Message -match 'Cancellation token is not bound'}
            Assert-DeltaWorkflow ($rejected -and (Get-DeltaWorkflowHash $paths.State) -ceq $stateHashBeforeWrongToken -and (Get-WsmFileScopeDigest $targetRoot $spec.Metadata) -ceq $baseDigest -and -not [IO.File]::Exists((Join-Path $paths.Root 'delta-transaction-g2.json'))) ('Restore accepted a mismatched cancellation binding or changed target/state for '+$kind+'.')
        }
        $keepRow=@($baseRows | Where-Object {$_.ItemId -ceq $itemId -and $_.RelativePath -ceq 'keep.txt'})[0];$keepPath=Join-Path $targetRoot 'keep.txt';[IO.File]::WriteAllText($keepPath,'target drift in unchanged member');$baselineDriftRejected=$false
        try{Invoke-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $stateRoot -Confirm:$false|Out-Null}catch{$baselineDriftRejected=$_.Exception.Message -match 'base drifted before delta package reconstruction'}
        Assert-DeltaWorkflow $baselineDriftRejected 'Delta package reconstruction trusted source membership without verifying an unchanged target member against the durable base.'
        Reset-DeltaWorkflowTarget $targetRoot $baseRows $base $baseItem
        Assert-DeltaWorkflow ((Get-WsmFileScopeDigest $targetRoot $spec.Metadata) -ceq $baseDigest) 'Fixture could not restore the exact trusted base after the drift rejection.'
        $cancelToken=New-WsmCancellationToken $plan.PairId $planHash $current.ManifestHash ([Guid]::NewGuid().ToString()) $stateRoot;$cancelRoot=Join-Path $stateRoot $plan.PairId;if(-not [IO.Directory]::Exists($cancelRoot)){[void][IO.Directory]::CreateDirectory($cancelRoot)};Write-WsmJson $cancelToken.RequestPath ([pscustomobject][ordered]@{SchemaVersion=1;Kind='CancellationRequest';PairId=$cancelToken.PairId;PlanHash=$cancelToken.PlanHash;ManifestHash=$cancelToken.ManifestHash;OperationId=$cancelToken.OperationId;StateDirectory=$cancelToken.StateDirectory;Owner='fixture owner';Evidence='isolated cancellation boundary test';RequestedUtc=(Get-WsmUtc)});$cancelObserved=$false
        try{Invoke-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $stateRoot -CancellationToken $cancelToken -Confirm:$false|Out-Null}catch{$cancelObserved=($_.Exception.Data['CancellationRequested'] -eq $true)}
        Assert-DeltaWorkflow ($cancelObserved -and (Get-WsmFileScopeDigest $targetRoot $spec.Metadata) -ceq $baseDigest) 'Bound cancellation request was not observed safely before target staging.'
        $script:DeltaInterruptAfterDelete=$true
        $script:DeltaFaultPointAction={param($Name,$Context) if($Name -eq 'AfterStagedDeletes' -and $script:DeltaInterruptAfterDelete){$script:DeltaInterruptAfterDelete=$false;throw 'Injected interruption after staging owned delete.'}}
        $interrupted=$false;$restoreError='';try{Invoke-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $stateRoot -Confirm:$false|Out-Null}catch{$restoreError=$_.Exception.ToString();$interrupted=$_.Exception.Message -match 'Injected interruption'}
        Assert-DeltaWorkflow $interrupted ('The interrupted-delete recovery fixture did not reach its injected staging fault. '+$restoreError)
        Assert-DeltaWorkflow ([IO.File]::Exists((Join-Path $targetRoot 'remove.txt'))) 'Interrupted staging changed the live target before verified switch.'
        $repaired=Repair-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $stateRoot
        Assert-DeltaWorkflow ($repaired.Generation -eq 2 -and $repaired.ManifestHash -ceq $current.ManifestHash) 'Delta repair did not adopt generation 2.'
        Assert-DeltaWorkflow ($repaired.DeltaPackageManifestHash -ceq $current.ManifestHash -and [IO.File]::Exists($repaired.DeltaPackageManifestPath)) 'Delta consumer package path/hash was not returned.'
        $localPackage=Test-WsmMigrationPackage $repaired.DeltaPackageManifestPath $repaired.DeltaPackageManifestHash
        Assert-DeltaWorkflow $localPackage.Valid 'Reconstructed current package did not pass the existing full package validator.'
        $final=Test-WsmFileScope $plan.Items[0] $localPackage $targetRoot @{}
        Assert-DeltaWorkflow $final.Passed ('Final target readback failed: '+($final.Problems -join '; '))
        Assert-DeltaWorkflow (-not [IO.File]::Exists((Join-Path $targetRoot 'remove.txt'))) 'Reviewed owned deletion remains after repair.'
        Assert-DeltaWorkflow (([IO.File]::ReadAllText((Join-Path $targetRoot 'change.txt'))) -ceq 'new content with a new chunk' -and ([IO.File]::ReadAllText((Join-Path $targetRoot 'added.txt'))) -ceq 'new owned file') 'Changed/add file content does not match the current package.'
        $finalState=Read-WsmJson $paths.State;$finalOwner=@($finalState.Items | Where-Object ItemId -CEQ $itemId)[0];$manualOwner=@($finalState.Items | Where-Object ItemId -CEQ $manualId)[0];Assert-DeltaWorkflow ($finalState.Generation -eq 2 -and $finalState.ManifestHash -ceq $current.ManifestHash -and $finalOwner.ActualHash -ceq $final.ActualHash -and $finalState.Stage -eq 'ManualEvidenceRequired' -and $manualOwner.Status -eq 'ManualEvidenceRequired' -and $manualOwner.CreatedByTool -eq $false -and -not (Test-WsmEvidence $finalState $manualId ManualRestore $current.ManifestHash)) 'Delta promotion claimed manual work or treated base-generation evidence as current proof.'
        $manualReplay=Invoke-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $stateRoot -Confirm:$false;Assert-DeltaWorkflow ($manualReplay.Generation -eq 2 -and $manualReplay.Stage -eq 'ManualEvidenceRequired') 'Current-generation replay incorrectly required new ManualWorkflow proof or changed its manual stage.'
        $preview=Get-WsmRestorePreview -ManifestPath $repaired.DeltaPackageManifestPath -ExpectedHash $repaired.DeltaPackageManifestHash -StateDirectory $stateRoot
        Assert-DeltaWorkflow (-not $preview.Blocked -and @($preview.Rows | Where-Object {$_.ItemId -ceq $itemId -and $_.Action -eq 'VerifyAndSkip'}).Count -eq 1) 'Existing restore preview did not consume the completed local current package.'
        [void](Set-WsmValidationEvidence -ManifestPath $repaired.DeltaPackageManifestPath -ExpectedHash $repaired.DeltaPackageManifestHash -StateDirectory $stateRoot -ItemId $itemId -Check BusinessStaged -Owner 'fixture business owner' -Evidence 'temporary local fixture assertion' -Passed $true)
        [void](Set-WsmValidationEvidence -ManifestPath $repaired.DeltaPackageManifestPath -ExpectedHash $repaired.DeltaPackageManifestHash -StateDirectory $stateRoot -ItemId $serviceId -Check BusinessStaged -Owner 'fixture business owner' -Evidence 'temporary local service fixture assertion' -Passed $true)
        [void](Set-WsmValidationEvidence -ManifestPath $repaired.DeltaPackageManifestPath -ExpectedHash $repaired.DeltaPackageManifestHash -StateDirectory $stateRoot -ItemId $manualId -Check ManualRestore -Owner 'fixture manual operator' -Evidence 'temporary local current-generation procedure assertion' -Passed $true)
        [void](Set-WsmValidationEvidence -ManifestPath $repaired.DeltaPackageManifestPath -ExpectedHash $repaired.DeltaPackageManifestHash -StateDirectory $stateRoot -ItemId $manualId -Check BusinessStaged -Owner 'fixture business owner' -Evidence 'temporary local manual business assertion' -Passed $true)
        $validation=Invoke-WsmValidation -ManifestPath $repaired.DeltaPackageManifestPath -ExpectedHash $repaired.DeltaPackageManifestHash -StateDirectory $stateRoot -Phase Staged
        Assert-DeltaWorkflow $validation.Passed 'Existing staged validation did not consume the reconstructed package and BusinessStaged evidence.'
        $network=[pscustomobject][ordered]@{FinalName='fixture-target';InterfaceAlias='fixture';FinalIP='192.0.2.20';PrefixLength=24;DefaultGateway='';DnsServers=@('192.0.2.53');TemporaryIP='192.0.2.21';DomainProcedureEvidence='fixture only';RollbackProcedure='fixture only';Owner='fixture owner';MaintenanceWindowUtc=[DateTime]::UtcNow.AddHours(-1).ToString('o');ValidUntilUtc=[DateTime]::UtcNow.AddDays(1).ToString('o');ObservationHours=24}
        $networkPath=Join-Path $root 'network.json';Write-WsmJson $networkPath $network;$cutoverPath=Join-Path $root 'cutover.json';$cutover=New-WsmCutoverPlan -ManifestPath $repaired.DeltaPackageManifestPath -ExpectedHash $repaired.DeltaPackageManifestHash -StateDirectory $stateRoot -NetworkPath $networkPath -NetworkHash (Get-DeltaWorkflowHash $networkPath) -Path $cutoverPath
        Assert-DeltaWorkflow ($cutover.Plan.ManifestHash -ceq $current.ManifestHash -and [IO.File]::Exists($cutoverPath)) 'Existing cutover planning did not consume the reconstructed current package.'
        foreach($faultPhase in @('AfterOldRootMoved','AfterNewRootMovedBeforeJournal')){
            Reset-DeltaWorkflowTarget $targetRoot $baseRows $base $baseItem
            $faultStateRoot=Join-Path $root ('state-'+$faultPhase);[void][IO.Directory]::CreateDirectory($faultStateRoot);$faultPaths=Get-WsmOperationPaths $faultStateRoot $plan.PairId;New-DeltaWorkflowState $faultPaths $base $baseItem $baseDigest
            $script:DeltaFaultPointAction={param($Name,$Context) if($Name -eq $script:DeltaWantedFaultPhase){throw ('Injected atomic rename interruption at '+$Name)}};$script:DeltaWantedFaultPhase=$faultPhase;$faulted=$false;$faultError=''
            try{Invoke-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $faultStateRoot -Confirm:$false|Out-Null}catch{$faultError=$_.Exception.Message;$faulted=$faultError -match ('Injected atomic rename interruption at '+[regex]::Escape($faultPhase))}
            Assert-DeltaWorkflow $faulted ('Atomic exchange interruption was not observed at '+$faultPhase+': '+$faultError)
            $transactionPath=Join-Path $faultPaths.Root ('delta-transaction-g2.json');$pending=Read-WsmJson $transactionPath
            if($faultPhase -eq 'AfterOldRootMoved'){Assert-DeltaWorkflow (-not [IO.Directory]::Exists($targetRoot) -and [IO.Directory]::Exists($pending.Operations[0].Backup)) 'First-rename interruption did not preserve exact old backup and absent live root.'}
            else{Assert-DeltaWorkflow ([IO.Directory]::Exists($targetRoot) -and (Get-WsmFileScopeDigest $targetRoot $spec.Metadata) -ceq $pending.Operations[0].ExpectedCurrentHash -and [IO.Directory]::Exists($pending.Operations[0].Backup)) 'Second-rename interruption did not preserve both exact roots.'}
            $script:DeltaFaultPointAction=$null;$script:DeltaWantedFaultPhase=''
            $atomicRepair=Repair-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $faultStateRoot
            $atomicState=Read-WsmJson $faultPaths.State;$atomicOwner=@($atomicState.Items | Where-Object ItemId -CEQ $itemId)[0];Assert-DeltaWorkflow ($atomicRepair.Generation -eq 2 -and $atomicRepair.ManifestHash -ceq $current.ManifestHash -and (Get-WsmFileScopeDigest $targetRoot $spec.Metadata) -ceq $atomicOwner.ActualHash) ('Atomic interruption repair failed to adopt the trusted current root after '+$faultPhase+'.')
        }
        $mixedStateRoot=Join-Path $root 'mixed-state';[void][IO.Directory]::CreateDirectory($mixedStateRoot);Reset-DeltaWorkflowTarget $targetRoot $baseRows $base $baseItem;$mixedPaths=Get-WsmOperationPaths $mixedStateRoot $plan.PairId;New-DeltaWorkflowState $mixedPaths $base $baseItem $baseDigest
        $mixedStateHash=Get-DeltaWorkflowHash $mixedPaths.State;$script:DeltaFixtureServiceState='Drifted';$genericDriftRejected=$false
        try{Invoke-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $mixedStateRoot -Confirm:$false|Out-Null}catch{$genericDriftRejected=$_.Exception.Message -match 'Delta staged adapter readback failed'}
        Assert-DeltaWorkflow ($genericDriftRejected -and (Get-DeltaWorkflowHash $mixedPaths.State) -ceq $mixedStateHash -and (Get-WsmFileScopeDigest $targetRoot $spec.Metadata) -ceq $baseDigest -and -not [IO.File]::Exists((Join-Path $mixedPaths.Root 'delta-transaction-g2.json'))) 'Unchanged generic service drift was not rejected before any FileScope or state mutation.'
        $script:DeltaFixtureServiceState='AccessDenied';$accessDeniedRejected=$false;try{Invoke-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $mixedStateRoot -Confirm:$false|Out-Null}catch{$accessDeniedRejected=$_.Exception -is [UnauthorizedAccessException]}
        Assert-DeltaWorkflow ($accessDeniedRejected -and (Get-DeltaWorkflowHash $mixedPaths.State) -ceq $mixedStateHash -and (Get-WsmFileScopeDigest $targetRoot $spec.Metadata) -ceq $baseDigest -and -not [IO.File]::Exists((Join-Path $mixedPaths.Root 'delta-transaction-g2.json'))) 'Generic adapter access denial was not a no-mutation preflight failure.'
        $script:DeltaFixtureServiceState='Exact';$script:DeltaInjectGenericDriftAfterSwap=$true;$script:DeltaFaultPointAction={param($Name,$Context) if($Name -eq 'AfterNewRootMovedBeforeJournal' -and $script:DeltaInjectGenericDriftAfterSwap){$script:DeltaInjectGenericDriftAfterSwap=$false;$script:DeltaFixtureServiceState='Drifted'}};$postSwapRejected=$false
        $postSwapError='';try{Invoke-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $mixedStateRoot -Confirm:$false|Out-Null}catch{$postSwapError=$_.Exception.Message;$postSwapRejected=$postSwapError -match 'Delta staged adapter readback failed'}
        $script:DeltaFaultPointAction=$null;Assert-DeltaWorkflow $postSwapRejected ('Expected generic adapter rejection after target swap: '+$postSwapError);$pendingMixed=Read-WsmJson (Join-Path $mixedPaths.Root 'delta-transaction-g2.json');$preservedState=Read-WsmJson $mixedPaths.State
        Assert-DeltaWorkflow ($pendingMixed.Phase -eq 'Switched' -and $preservedState.Generation -eq 1 -and $preservedState.ManifestHash -ceq $base.ManifestHash -and (Get-WsmFileScopeDigest $targetRoot $spec.Metadata) -ceq $pendingMixed.Operations[0].ExpectedCurrentHash) 'Post-swap generic drift promoted generation or lost the exact repair transaction.'
        $script:DeltaFixtureServiceState='Exact';$mixedRepair=Repair-WsmArtifactDeltaRestore -TransportPath $zip -ExpectedTransportHash $export.SHA256 -ImportedDirectory $import.Directory -TargetStateDirectory $mixedStateRoot;$mixedFinal=Read-WsmJson $mixedPaths.State;$mixedOwner=@($mixedFinal.Items | Where-Object ItemId -CEQ $itemId)[0]
        Assert-DeltaWorkflow ($mixedRepair.Generation -eq 2 -and $mixedFinal.Generation -eq 2 -and $mixedFinal.ManifestHash -ceq $current.ManifestHash -and (Get-WsmFileScopeDigest $targetRoot $spec.Metadata) -ceq $mixedOwner.ActualHash) 'Explicit repair did not promote the exact staged generation after generic adapter readback was restored.'
        Write-Host 'PASS: delta ZIP export/import, full current package reconstruction, unchanged-target baseline drift rejection, cancellation boundary, interrupted staging and both atomic rename recovery points, target readback, restore preview, staged validation, and cutover planning.'
    }finally{if([IO.Directory]::Exists($root)){Remove-Item -LiteralPath $root -Recurse -Force}}
} $contractsPath $workflowPath
