#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$root=Join-Path 'C:\' ('wsm-activation-cutover-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
& $module {
    param($Root)
    . (Join-Path $PSScriptRoot '..\tests\Helper-Fixtures.ps1')
    $script:fixtureHost='source';$script:sourceFingerprint=('a'*64);$script:targetFingerprint=('b'*64);$script:sourceHostId=[Guid]::NewGuid().ToString();$script:inventoryRevision=0
    $script:sourceServices=@{};$script:targetServices=@{};$script:activationCalls=@{};$script:failAfterStartName='';$script:fixtureAddresses=@();$script:fixtureDns=@();$script:fixtureRoutes=@()
    function script:Get-WsmMachineIdentity {if($script:fixtureHost -eq 'source'){$fingerprint=$script:sourceFingerprint;$name='fixture-source'}else{$fingerprint=$script:targetFingerprint;$name=$env:COMPUTERNAME};[pscustomobject]@{Fingerprint=$fingerprint;Name=$name;OS='Fixture Windows Server';Version='10.fixture';IsServer=$true;Administrator=$true;Is64Bit=$true}}
    function script:Get-WsmToolFingerprint {('d'*64)}
    function script:Export-WsmInventory {param([Parameter(Mandatory)][string]$OutputDirectory,[switch]$DeepDiscovery)$script:inventoryRevision++;$items=@(foreach($service in $script:sourceServices.Values){$settings=[ordered]@{Name=$service.Name;DisplayName=$service.DisplayName;Description=$service.Description;PathName=$service.PathName;StartMode=$service.StartMode;StartName=$service.StartName;ServiceType=$service.ServiceType;Supplement=$service.Supplement};New-WsmItem $script:sourceHostId Services Service $service.DisplayName $service.Name $settings @() Success Service});$source=[pscustomobject]@{HostId=$script:sourceHostId;Fingerprint=$script:sourceFingerprint;Name='fixture-source';OS='Fixture Windows Server';Version='10.fixture';DiscoveryDepth='Metadata'};$inventory=New-WsmInventory $source $script:inventoryRevision $items;$path=Join-Path $OutputDirectory ('fixture-inventory-'+$script:inventoryRevision+'.json');Write-WsmJson $path $inventory;[pscustomobject]@{Path=$path;SHA256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash}}
    function script:Get-CimInstance {param($ClassName,$ErrorAction)if($ClassName -ceq 'Win32_Service'){if($script:fixtureHost -eq 'source'){$script:sourceServices.Values}else{$script:targetServices.Values}}elseif($ClassName -ceq 'Win32_OperatingSystem'){[pscustomobject]@{LastBootUpTime=[DateTime]::UtcNow.AddDays(-2)}}else{throw ('Unexpected CIM query: '+$ClassName)}}
    function script:Get-WsmServiceDependencies {param([string]$Name)if($script:fixtureHost -eq 'source'){@($script:sourceServices[$Name].Dependencies)}else{@($script:targetServices[$Name].Dependencies)}}
    function script:Get-WsmServiceSupplementState {param([string]$Name)if($script:fixtureHost -eq 'source'){$script:sourceServices[$Name].Supplement}else{$script:targetServices[$Name].Supplement}}
    function script:Set-WsmServiceSupplement {param([string]$Name,$Supplement,[string]$Phase)$object=$script:targetServices[$Name];if(-not $object){$object=$script:sourceServices[$Name]};$object.Supplement=Get-WsmServiceSupplementForPhase $Supplement $Phase}
    function script:New-Service {
        [CmdletBinding(SupportsShouldProcess=$true)]
        param([Parameter(Mandatory)][string]$Name,[Parameter(Mandatory)][string]$BinaryPathName,[ValidateSet('Automatic','Manual','Disabled')][string]$StartupType,[string]$DisplayName,[string]$Description,[string[]]$DependsOn,[PSCredential]$Credential)
        if($script:fixtureHost -ne 'target' -or $StartupType -cne 'Disabled'){throw 'Fixture service must be created disabled on the target.'}
        if(@($DependsOn).Count -ne 1 -or $DependsOn[0] -cne 'FixtureDependency'){throw ('New-Service did not bind the exact service dependencies through -DependsOn: '+(@($DependsOn)-join ','))}
        if($script:targetServices.ContainsKey($Name)){throw 'Duplicate fixture service creation.'}
        if(-not $PSCmdlet.ShouldProcess($Name,'Create disabled fixture service')){return}
        $script:targetServices[$Name]=[pscustomobject]@{Name=$Name;DisplayName=$DisplayName;Description=$Description;PathName=$BinaryPathName;StartMode='Disabled';StartName='LocalSystem';ServiceType='Own Process';State='Stopped';Dependencies=@($DependsOn);Supplement=$null};$script:activationCalls[$Name]=0
    }
    function script:Set-Service {param($Name,$StartupType,$ErrorAction)$object=$null;if($script:fixtureHost -eq 'source'){$object=$script:sourceServices[$Name]}else{$object=$script:targetServices[$Name]};if(-not $object){throw ('Unknown fixture service '+$Name)};$mode=$StartupType;if($mode -ceq 'Automatic'){$mode='Auto'};$object.StartMode=$mode}
    function script:Start-Service {param($Name,$ErrorAction)$object=$null;if($script:fixtureHost -eq 'source'){$object=$script:sourceServices[$Name]}else{$object=$script:targetServices[$Name]};if(-not $object){throw ('Unknown fixture service '+$Name)};$object.State='Running';if($script:fixtureHost -eq 'target'){$script:activationCalls[$Name]++;if($Name -ceq $script:failAfterStartName){$script:failAfterStartName='';throw 'Injected termination after Start-Service took effect'}}}
    function script:Stop-Service {param($Name,$ErrorAction)$object=$null;if($script:fixtureHost -eq 'source'){$object=$script:sourceServices[$Name]}else{$object=$script:targetServices[$Name]};if(-not $object){throw ('Unknown fixture service '+$Name)};$object.State='Stopped'}
    function script:Get-NetAdapter {param($Name,$ErrorAction)[pscustomobject]@{Name=$Name}}
    function script:Get-NetIPAddress {param($InterfaceAlias,$IPAddress,$ErrorAction)$script:fixtureAddresses|Where-Object {($_.InterfaceAlias -ceq $InterfaceAlias) -and (-not $IPAddress -or $_.IPAddress -ceq $IPAddress)}}
    function script:New-NetIPAddress {param($InterfaceAlias,$IPAddress,$PrefixLength,$DefaultGateway,$ErrorAction)$script:fixtureAddresses+=@([pscustomobject]@{InterfaceAlias=$InterfaceAlias;IPAddress=$IPAddress;PrefixLength=$PrefixLength;AddressState='Preferred'})}
    function script:Remove-NetIPAddress {param([Parameter(ValueFromPipeline)]$InputObject,[switch]$Confirm)process{$script:fixtureAddresses=@($script:fixtureAddresses|Where-Object IPAddress -NE $InputObject.IPAddress)}}
    function script:Set-DnsClientServerAddress {param($InterfaceAlias,$ServerAddresses)$script:fixtureDns=@($ServerAddresses)}
    function script:Get-DnsClientServerAddress {param($InterfaceAlias,$AddressFamily,$ErrorAction)[pscustomobject]@{ServerAddresses=$script:fixtureDns}}
    function script:Get-NetRoute {param($InterfaceAlias,$DestinationPrefix,$ErrorAction)$script:fixtureRoutes|Where-Object {($_.InterfaceAlias -ceq $InterfaceAlias) -and (-not $DestinationPrefix -or $_.DestinationPrefix -ceq $DestinationPrefix)}}
    function script:Rename-Computer {throw 'Unexpected computer rename in workflow fixture.'}

    # Source fixture inventory, full review, and approved service plan.
    $supplement=New-WsmFixtureServiceSupplement
    foreach($name in @('FixtureAlpha','FixtureBeta')){$script:sourceServices[$name]=[pscustomobject]@{Name=$name;DisplayName=$name;Description=('Fixture '+$name);PathName=('C:\Fixture\'+$name+'.exe');StartMode='Auto';StartName='LocalSystem';ServiceType='Own Process';State='Running';Dependencies=@('FixtureDependency');Supplement=$supplement};$script:activationCalls[$name]=0}
    $sourceState=Join-Path $Root 'source';$workspace=Join-Path $Root 'manager';$targetState=Join-Path $Root 'target';$packages=Join-Path $Root 'packages';Initialize-WsmWorkspace $workspace | Out-Null;$sourceExport=Export-WsmInventory $sourceState;$catalog=Import-WsmInventory $workspace $sourceExport.Path $sourceExport.SHA256 'fixture-target';$pairId=$catalog.PairId
    $revision=$catalog.DecisionRevision;foreach($item in $catalog.Items){$name=$item.NaturalKey;$spec=[pscustomobject]@{Adapter='Service';Owner='Fixture service owner';Evidence='fixture service review';DesiredFinalState='Automatic';Desired=[pscustomobject]@{Name=$name;DisplayName=$name;BinaryPathName=('C:\Fixture\'+$name+'.exe');Account='LocalSystem';Dependencies=@('FixtureDependency');Description=('Fixture '+$name);Supplement=$supplement}};$specPath=Join-Path $Root ($name+'.spec.json');Write-WsmJson $specPath $spec;Set-WsmMigrationSpec $workspace $pairId $item.ItemId $specPath (Get-FileHash -LiteralPath $specPath -Algorithm SHA256).Hash $revision | Out-Null;$revision++}
    $catalog=Get-WsmCatalog $workspace $pairId;Set-WsmDecision $workspace $pairId @($catalog.Items|ForEach-Object ItemId) Include 'reviewed fixture services' $catalog.DecisionRevision | Out-Null
    $targetIdentityPath=Join-Path $Root 'target-identity.json';$script:fixtureHost='target';$targetIdentity=Register-WsmTarget $targetState $targetIdentityPath;$planPath=Join-Path $Root 'approved-plan.json';$catalog=Get-WsmCatalog $workspace $pairId;$approval=Approve-WsmMigrationPlan $workspace $pairId $targetIdentity.Path $targetIdentity.SHA256 $planPath $catalog.DecisionRevision ISOLATED-PILOT

    # Freeze the source, package the final generation, and stage exact disabled services on the target.
    $script:fixtureHost='source';$freezePath=Join-Path $Root 'freeze.json';$freeze=Export-WsmFreezeRecord $planPath $approval.SHA256 $freezePath 'Fixture source owner' 'fixture service writers stopped' OWNER-CONFIRMED-QUIESCENCE -SourceIdentityReleased -ReleaseEvidence 'fixture source identity withdrawn' -SourceStateDirectory $sourceState
    $packageExport=Export-WsmMigrationPackage $planPath $approval.SHA256 $sourceState $packages -FreezePath $freeze.Path -FreezeHash $freeze.SHA256;$manifestPath=$packageExport.ManifestPath;$manifestHash=$packageExport.SHA256;$package=Test-WsmMigrationPackage $manifestPath $manifestHash
    $script:fixtureHost='target';$restored=Invoke-WsmRestore $manifestPath $manifestHash $targetState;if($restored.Stage -ne 'Succeeded'){throw 'Service fixture did not restore into staged state.'};foreach($service in $script:targetServices.Values){if(@($service.Dependencies).Count -ne 1 -or $service.Dependencies[0] -cne 'FixtureDependency'){throw 'Restore did not preserve the reviewed non-empty service dependency.'}}
    foreach($item in $package.Plan.Items){Set-WsmValidationEvidence $manifestPath $manifestHash $targetState $item.ItemId BusinessStaged 'Fixture business owner' 'fixture staged service check passed' $true | Out-Null}
    if(-not (Invoke-WsmValidation $manifestPath $manifestHash $targetState Staged).Passed){throw 'Reviewed staged service configuration/evidence did not pass.'}

    # The cutover plan binds the reviewed network and frozen final manifest.
    $script:fixtureAddresses=@([pscustomobject]@{InterfaceAlias='FixtureNIC';IPAddress='192.0.2.10';PrefixLength=24;AddressState='Preferred'});$script:fixtureDns=@('192.0.2.53');$script:fixtureRoutes=@([pscustomobject]@{InterfaceAlias='FixtureNIC';DestinationPrefix='0.0.0.0/0';NextHop='192.0.2.1'})
    $network=[pscustomobject]@{FinalName=$env:COMPUTERNAME;InterfaceAlias='FixtureNIC';FinalIP='192.0.2.20';PrefixLength=24;DefaultGateway='192.0.2.1';DnsServers=@('192.0.2.53');TemporaryIP=@('192.0.2.10');DomainProcedureEvidence='fixture domain identity prechecked';RollbackProcedure='fixture stop/reconcile then identity rollback';Owner='Fixture network owner';MaintenanceWindowUtc=[DateTime]::UtcNow.AddMinutes(-1).ToString('o');ValidUntilUtc=[DateTime]::UtcNow.AddHours(1).ToString('o')}
    $networkPath=Join-Path $Root 'network.json';Write-WsmJson $networkPath $network;$cutoverPath=Join-Path $Root 'cutover.json';$cutover=New-WsmCutoverPlan $manifestPath $manifestHash $targetState $networkPath (Get-FileHash -LiteralPath $networkPath -Algorithm SHA256).Hash $cutoverPath;$ack='CUTOVER '+$pairId

    # Fail after the first native start side effect but before its ActivationCompleted journal record.
    $plan=Read-WsmTrustedJson $planPath $approval.SHA256;$firstItem=$plan.Items|Where-Object Decision -EQ Include|Sort-Object ItemId|Select-Object -First 1;$secondItem=$plan.Items|Where-Object { $_.ItemId -cne $firstItem.ItemId -and $_.Decision -eq 'Include' }|Select-Object -First 1;$firstName=$firstItem.NaturalKey;$secondName=$secondItem.NaturalKey;$script:failAfterStartName=$firstName
    $cutoverFailed=$false;try{Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack | Out-Null}catch{$cutoverFailed=$true;$cutoverFailure=$_.Exception.Message}
    if(-not $cutoverFailed -or $script:targetServices[$firstName].State -ne 'Running' -or $script:activationCalls[$firstName] -ne 1){throw 'Cutover did not exercise a post-effect/pre-completion activation interruption.'}
    $statePath=Join-Path (Join-Path $targetState $pairId) 'state.json';$interrupted=Read-WsmJson $statePath;if(-not $interrupted.Cutover.NewTransactionsPossible -or @($interrupted.Cutover.Activations|Where-Object {$_.ItemId -ceq $firstItem.ItemId -and $_.Status -eq 'Intent'}).Count -ne 1){throw 'Cutover did not retain transaction boundary and durable first-service intent.'}

    # An interrupted activation cannot be resumed without explicit owner reconciliation evidence.
    $blocked=$false;try{Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack | Out-Null}catch{$blocked=$_.Exception.Message -match 'explicit ResumeActivation'};if(-not $blocked){throw 'Cutover allowed an implicit activation resume.'}

    # Reject final-IP drift and DNS drift before replaying any service activation.
    $script:fixtureAddresses=@([pscustomobject]@{InterfaceAlias='FixtureNIC';IPAddress='192.0.2.99';PrefixLength=24;AddressState='Preferred'});$blocked=$false;try{Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack -ResumeActivation -ResumeOwner 'Fixture cutover owner' -ResumeEvidence 'fixture network reconciliation reviewed' | Out-Null}catch{$blocked=$_.Exception.Message -match 'Final IP/prefix'};if(-not $blocked -or $script:activationCalls[$firstName] -ne 1){throw 'Activation resume accepted final network drift or replayed a service.'}
    $script:fixtureAddresses=@([pscustomobject]@{InterfaceAlias='FixtureNIC';IPAddress='192.0.2.20';PrefixLength=24;AddressState='Preferred'});$script:fixtureDns=@('192.0.2.99');$blocked=$false;try{Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack -ResumeActivation -ResumeOwner 'Fixture cutover owner' -ResumeEvidence 'fixture DNS reconciliation reviewed' | Out-Null}catch{$blocked=$_.Exception.Message -match 'DNS server order'};if(-not $blocked -or $script:activationCalls[$firstName] -ne 1){throw 'Activation resume accepted DNS drift or replayed a service.'}
    $script:fixtureDns=@('192.0.2.53')

    # Alter the sealed manifest bytes temporarily; package validation must reject the same trusted hash.
    $manifestText=[IO.File]::ReadAllText($manifestPath);$manifestTampered=[regex]::Replace($manifestText,'"Final"\s*:\s*true','"Final": false');if($manifestTampered -ceq $manifestText){$manifestTampered=[regex]::Replace($manifestText,'"Files"\s*:\s*0','"Files": 1')};if($manifestTampered -ceq $manifestText){throw 'Could not construct manifest drift fixture.'};[IO.File]::WriteAllText($manifestPath,$manifestTampered,(New-Object Text.UTF8Encoding($false)));$blocked=$false;try{Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack -ResumeActivation -ResumeOwner 'Fixture cutover owner' -ResumeEvidence 'fixture package review' | Out-Null}catch{$blocked=$_.Exception.Message -match 'Trusted SHA256 mismatch'};[IO.File]::WriteAllText($manifestPath,$manifestText,(New-Object Text.UTF8Encoding($false)));if(-not $blocked -or $script:activationCalls[$firstName] -ne 1){throw 'Activation resume accepted a changed final manifest or replayed a service.'}

    # Resume adopts the already-final first service without calling Start-Service again, then activates the second once.
    $resumed=Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack -ResumeActivation -ResumeOwner 'Fixture cutover owner' -ResumeEvidence 'fixture target state reconciled after injected crash'
    if($resumed.Cutover.Stage -ne 'Activated' -or $script:activationCalls[$firstName] -ne 1 -or $script:activationCalls[$secondName] -ne 1 -or $script:targetServices[$secondName].State -ne 'Running'){throw 'Resume did not adopt first activation and activate the next service exactly once.'}
    $activationRows=@($resumed.Cutover.Activations);if($activationRows.Count -ne 2 -or @($activationRows|Where-Object Status -NE Completed).Count){throw 'Completed cutover did not retain exact activation checkpoints.'}
    $again=Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack;if($script:activationCalls[$firstName] -ne 1 -or $script:activationCalls[$secondName] -ne 1){throw 'Completed Cutover replayed a service activation.'}
    Write-Host ('PASS: real approved-plan/freeze/final-package/staged-restore/New-WsmCutoverPlan/Invoke-WsmCutover workflow; first service effect interrupted before completion journal; explicit resume adopts exact final state and starts next once; implicit resume, final IP drift, DNS drift and manifest hash drift rejected. OS and service/network APIs are fixtures. Root: '+$Root)
} $root
$resolvedRoot=[IO.Path]::GetFullPath($root).TrimEnd('\');if($resolvedRoot -notmatch '^C:\\wsm-activation-cutover-[0-9a-f]{32}$' -or $resolvedRoot -eq 'C:\'){throw ('Refusing fixture cleanup outside the test-owned root: '+$resolvedRoot)};Remove-Item -LiteralPath $resolvedRoot -Recurse -Force
