#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$externalReadinessFixturesPath=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot 'ExternalReadinessEvidenceFixtures.ps1'))
$root=Join-Path 'C:\' ('wsm-observation-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
& $module {
    param($Root,$ExternalReadinessFixturesPath)
    . (Join-Path $PSScriptRoot '..\tests\Helper-Fixtures.ps1')
    . $ExternalReadinessFixturesPath
    $script:fixtureHost='source';$script:sourceFingerprint=('a'*64);$script:targetFingerprint=('b'*64);$script:sourceHostId=[Guid]::NewGuid().ToString();$script:inventoryRevision=0
    $script:sourceServices=@{};$script:targetServices=@{};$script:activationCalls=@{};$script:failAfterStartName='';$script:fixtureAddresses=@();$script:fixtureDns=@();$script:fixtureRoutes=@();$script:observationClock=$null
    function script:Get-WsmObservationClock {if($script:observationClock){[DateTimeOffset]$script:observationClock}else{[DateTimeOffset]::UtcNow}}
    function script:Save-ObservationMutation($Paths,$State){$marker=[pscustomobject]@{ItemId='';Check='ObservationFixtureMutation';Owner='Fixture test';Evidence='test-only journaled mutation';Passed=$false;ManifestHash=$State.ManifestHash;Generation=$State.Generation;Phase=$State.Stage;Utc=(Get-WsmUtc);ExpiresUtc=[DateTime]::UtcNow.AddHours(1).ToString('o');ManualEvidence=$true};$State.Evidence=@($State.Evidence)+@($marker);Add-WsmJournal $Paths $State 'ValidationEvidence' '' $marker}
    function script:Get-WsmMachineIdentity {if($script:fixtureHost -eq 'source'){$fingerprint=$script:sourceFingerprint;$name='fixture-source'}else{$fingerprint=$script:targetFingerprint;$name=$env:COMPUTERNAME};[pscustomobject]@{Fingerprint=$fingerprint;Name=$name;OS='Fixture Windows Server';Version='10.fixture';IsServer=$true;Administrator=$true;Is64Bit=$true}}
    function script:Get-WsmToolFingerprint {('d'*64)}
    function script:Export-WsmInventory {param([Parameter(Mandatory)][string]$OutputDirectory,[switch]$DeepDiscovery)$script:inventoryRevision++;$items=@(foreach($service in $script:sourceServices.Values){$settings=[ordered]@{Name=$service.Name;DisplayName=$service.DisplayName;Description=$service.Description;PathName=$service.PathName;StartMode=$service.StartMode;StartName=$service.StartName;ServiceType=$service.ServiceType;Supplement=$service.Supplement};New-WsmItem $script:sourceHostId Services Service $service.DisplayName $service.Name $settings @() Success Service});$source=[pscustomobject]@{HostId=$script:sourceHostId;Fingerprint=$script:sourceFingerprint;Name='fixture-source';OS='Fixture Windows Server';Version='10.fixture';DiscoveryDepth='Metadata'};$inventory=New-WsmInventory $source $script:inventoryRevision $items;$path=Join-Path $OutputDirectory ('fixture-inventory-'+$script:inventoryRevision+'.json');Write-WsmJson $path $inventory;[pscustomobject]@{Path=$path;SHA256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash}}
    function script:Get-CimInstance {param($ClassName,$ErrorAction)if($ClassName -ceq 'Win32_Service'){if($script:fixtureHost -eq 'source'){$script:sourceServices.Values}else{$script:targetServices.Values}}elseif($ClassName -ceq 'Win32_OperatingSystem'){[pscustomobject]@{LastBootUpTime=[DateTime]::UtcNow.AddDays(-2)}}else{throw ('Unexpected CIM query: '+$ClassName)}}
    function script:Get-WsmServiceDependencies {param([string]$Name)if($script:fixtureHost -eq 'source'){@($script:sourceServices[$Name].Dependencies)}else{@($script:targetServices[$Name].Dependencies)}}
    function script:Get-WsmServiceSupplementState {param([string]$Name)if($script:fixtureHost -eq 'source'){$script:sourceServices[$Name].Supplement}else{$script:targetServices[$Name].Supplement}}
    function script:Set-WsmServiceSupplement {param([string]$Name,$Supplement,[string]$Phase)$object=$script:targetServices[$Name];if(-not $object){$object=$script:sourceServices[$Name]};$object.Supplement=Get-WsmServiceSupplementForPhase $Supplement $Phase}
    function script:New-Service {
        [CmdletBinding(SupportsShouldProcess=$true)]
        param([Parameter(Mandatory)][string]$Name,[Parameter(Mandatory)][string]$BinaryPathName,[ValidateSet('Automatic','Manual','Disabled')][string]$StartupType,[string]$DisplayName,[string]$Description,[string[]]$DependsOn,[PSCredential]$Credential)
        if($script:fixtureHost -ne 'target' -or $StartupType -cne 'Disabled'){throw 'Fixture service must be created disabled on the target.'}
        if(@($DependsOn).Count -ne 1 -or $DependsOn[0] -cne 'FixtureDependency'){throw ('New-Service did not bind the exact service dependencies through -DependsOn: '+(@($DependsOn)-join ','))}
        if($script:targetServices.ContainsKey($Name)){throw 'Duplicate fixture service creation.'}
        if(-not $PSCmdlet.ShouldProcess($Name,'Create disabled fixture service')){return}
        $script:targetServices[$Name]=[pscustomobject]@{Name=$Name;DisplayName=$DisplayName;Description=$Description;PathName=$BinaryPathName;StartMode='Disabled';StartName='LocalSystem';ServiceType='Own Process';State='Stopped';Dependencies=@($DependsOn);Supplement=$null};$script:activationCalls[$Name]=0
    }
    function script:Set-Service {param($Name,$StartupType,$ErrorAction)$object=$null;if($script:fixtureHost -eq 'source'){$object=$script:sourceServices[$Name]}else{$object=$script:targetServices[$Name]};if(-not $object){throw ('Unknown fixture service '+$Name)};$mode=$StartupType;if($mode -ceq 'Automatic'){$mode='Auto'};$object.StartMode=$mode}
    function script:Start-Service {param($Name,$ErrorAction)$object=$null;if($script:fixtureHost -eq 'source'){$object=$script:sourceServices[$Name]}else{$object=$script:targetServices[$Name]};if(-not $object){throw ('Unknown fixture service '+$Name)};$object.State='Running';if($script:fixtureHost -eq 'target'){$script:activationCalls[$Name]++;if($Name -ceq $script:failAfterStartName){$script:failAfterStartName='';throw 'Injected termination after Start-Service took effect'}}}
    function script:Stop-Service {param($Name,$ErrorAction)$object=$null;if($script:fixtureHost -eq 'source'){$object=$script:sourceServices[$Name]}else{$object=$script:targetServices[$Name]};if(-not $object){throw ('Unknown fixture service '+$Name)};$object.State='Stopped'}
    function script:Get-NetAdapter {param($Name,$ErrorAction)[pscustomobject]@{Name=$Name}}
    function script:Get-NetIPAddress {param($InterfaceAlias,$IPAddress,$ErrorAction)$script:fixtureAddresses|Where-Object {($_.InterfaceAlias -ceq $InterfaceAlias) -and (-not $IPAddress -or $_.IPAddress -ceq $IPAddress)}}
    function script:New-NetIPAddress {param($InterfaceAlias,$IPAddress,$PrefixLength,$DefaultGateway,$ErrorAction)$script:fixtureAddresses+=@([pscustomobject]@{InterfaceAlias=$InterfaceAlias;IPAddress=$IPAddress;PrefixLength=$PrefixLength;AddressState='Preferred'})}
    function script:Remove-NetIPAddress {param([Parameter(ValueFromPipeline)]$InputObject,[switch]$Confirm)process{$script:fixtureAddresses=@($script:fixtureAddresses|Where-Object IPAddress -NE $InputObject.IPAddress)}}
    function script:Set-DnsClientServerAddress {param($InterfaceAlias,$ServerAddresses)$script:fixtureDns=@($ServerAddresses)}
    function script:Get-DnsClientServerAddress {param($InterfaceAlias,$AddressFamily,$ErrorAction)[pscustomobject]@{ServerAddresses=$script:fixtureDns}}
    function script:Get-NetRoute {param($InterfaceAlias,$DestinationPrefix,$ErrorAction)$script:fixtureRoutes|Where-Object {($_.InterfaceAlias -ceq $InterfaceAlias) -and (-not $DestinationPrefix -or $_.DestinationPrefix -ceq $DestinationPrefix)}}
    function script:Rename-Computer {throw 'Unexpected computer rename in workflow fixture.'}

    # Source fixture inventory, full review, and approved service plan.
    $supplement=New-WsmFixtureServiceSupplement
    foreach($name in @('FixtureAlpha','FixtureBeta')){$script:sourceServices[$name]=[pscustomobject]@{Name=$name;DisplayName=$name;Description=('Fixture '+$name);PathName=('C:\Fixture\'+$name+'.exe');StartMode='Auto';StartName='LocalSystem';ServiceType='Own Process';State='Running';Dependencies=@('FixtureDependency');Supplement=$supplement};$script:activationCalls[$name]=0}
    $sourceState=Join-Path $Root 'source';$workspace=Join-Path $Root 'manager';$targetState=Join-Path $Root 'target';$packages=Join-Path $Root 'packages';Initialize-WsmWorkspace $workspace | Out-Null;$sourceExport=Export-WsmInventory $sourceState;$catalog=Import-WsmInventory $workspace $sourceExport.Path $sourceExport.SHA256 'fixture-target';$pairId=$catalog.PairId
    $revision=$catalog.DecisionRevision;foreach($item in $catalog.Items){$name=$item.NaturalKey;$spec=[pscustomobject]@{Adapter='Service';Owner='Fixture service owner';Evidence='fixture service review';DesiredFinalState='Automatic';Desired=[pscustomobject]@{Name=$name;DisplayName=$name;BinaryPathName=('C:\Fixture\'+$name+'.exe');Account='LocalSystem';Dependencies=@('FixtureDependency');Description=('Fixture '+$name);Supplement=$supplement}};$specPath=Join-Path $Root ($name+'.spec.json');Write-WsmJson $specPath $spec;Set-WsmMigrationSpec $workspace $pairId $item.ItemId $specPath (Get-FileHash -LiteralPath $specPath -Algorithm SHA256).Hash $revision | Out-Null;$revision++}
    $catalog=Get-WsmCatalog $workspace $pairId;Set-WsmDecision $workspace $pairId @($catalog.Items|ForEach-Object ItemId) Include 'reviewed fixture services' $catalog.DecisionRevision | Out-Null
    $targetIdentityPath=Join-Path $Root 'target-identity.json';$script:fixtureHost='target';$targetIdentity=Register-WsmTarget $targetState $targetIdentityPath;$planPath=Join-Path $Root 'approved-plan.json';$catalog=Get-WsmCatalog $workspace $pairId;$approval=Approve-WsmMigrationPlan $workspace $pairId $targetIdentity.Path $targetIdentity.SHA256 $planPath $catalog.DecisionRevision ISOLATED-PILOT

    # Freeze the source, package the final generation, and stage exact disabled services on the target.
    $script:fixtureHost='source';$approvedPlan=Read-WsmMigrationPlan $planPath $approval.SHA256;$freezeProof=New-WsmSourceFreezeEvidenceFixture -Plan $approvedPlan -PlanHash $approval.SHA256 -Root $Root -Owner 'Fixture source owner';$freezePath=Join-Path $Root 'freeze.json';$freeze=Export-WsmFreezeRecord $planPath $approval.SHA256 $freezePath 'Fixture source owner' 'fixture service writers stopped' OWNER-CONFIRMED-QUIESCENCE -SourceIdentityReleased -ReleaseEvidence 'fixture source identity withdrawn' -SourceStateDirectory $sourceState -FreezeExternalEvidencePath $freezeProof.Path -FreezeExternalEvidenceHash $freezeProof.SHA256 -FreezeEpoch $freezeProof.FreezeEpoch
    $packageExport=Export-WsmMigrationPackage $planPath $approval.SHA256 $sourceState $packages -FreezePath $freeze.Path -FreezeHash $freeze.SHA256 -FreezeExternalEvidencePath $freezeProof.Path -FreezeExternalEvidenceHash $freezeProof.SHA256;$manifestPath=$packageExport.ManifestPath;$manifestHash=$packageExport.SHA256;$package=Test-WsmMigrationPackage $manifestPath $manifestHash
    $script:fixtureHost='target';$restored=Invoke-WsmRestore $manifestPath $manifestHash $targetState;if($restored.Stage -ne 'Succeeded'){throw 'Service fixture did not restore into staged state.'};foreach($service in $script:targetServices.Values){if(@($service.Dependencies).Count -ne 1 -or $service.Dependencies[0] -cne 'FixtureDependency'){throw 'Restore did not preserve the reviewed non-empty service dependency.'}}
    foreach($item in $package.Plan.Items){Set-WsmExternalFixtureValidationEvidence $manifestPath $manifestHash $targetState $item.ItemId BusinessStaged 'Fixture business owner' 'fixture staged service check passed' $true | Out-Null}
    if(-not (Invoke-WsmValidation $manifestPath $manifestHash $targetState Staged).Passed){throw 'Reviewed staged service configuration/evidence did not pass.'}

    # The cutover plan binds the reviewed network and frozen final manifest.
    $script:fixtureAddresses=@([pscustomobject]@{InterfaceAlias='FixtureNIC';IPAddress='192.0.2.10';PrefixLength=24;AddressState='Preferred'});$script:fixtureDns=@('192.0.2.53');$script:fixtureRoutes=@([pscustomobject]@{InterfaceAlias='FixtureNIC';DestinationPrefix='0.0.0.0/0';NextHop='192.0.2.1'})
    $network=[pscustomobject]@{FinalName=$env:COMPUTERNAME;InterfaceAlias='FixtureNIC';FinalIP='192.0.2.20';PrefixLength=24;DefaultGateway='192.0.2.1';DnsServers=@('192.0.2.53');TemporaryIP=@('192.0.2.10');DomainProcedureEvidence='fixture domain identity prechecked';RollbackProcedure='fixture stop/reconcile then identity rollback';Owner='Fixture network owner';MaintenanceWindowUtc=[DateTime]::UtcNow.AddMinutes(-1).ToString('o');ValidUntilUtc=[DateTime]::UtcNow.AddHours(1).ToString('o');ObservationHours=2}
    $networkPath=Join-Path $Root 'network.json';Write-WsmJson $networkPath $network;$cutoverPath=Join-Path $Root 'cutover.json';$cutover=New-WsmCutoverPlan $manifestPath $manifestHash $targetState $networkPath (Get-FileHash -LiteralPath $networkPath -Algorithm SHA256).Hash $cutoverPath -ExternalEvidenceReferences (New-WsmCutoverEvidenceFixtureReferences -Package $package -Root $Root);$ack='CUTOVER '+$pairId
    $defaultNetwork=ConvertFrom-WsmJson ($network|ConvertTo-Json -Depth 20);$defaultNetwork.PSObject.Properties.Remove('ObservationHours');$defaultPath=Join-Path $Root 'network-default.json';Write-WsmJson $defaultPath $defaultNetwork;$defaultPlan=New-WsmCutoverPlan $manifestPath $manifestHash $targetState $defaultPath (Get-FileHash -LiteralPath $defaultPath -Algorithm SHA256).Hash (Join-Path $Root 'cutover-default.json') -ExternalEvidenceReferences (New-WsmCutoverEvidenceFixtureReferences -Package $package -Root $Root);if([int]$defaultPlan.Plan.Network.ObservationHours -ne 24){throw 'Unspecified reviewed observation duration did not default to 24 hours.'}
    Assert-WsmObservationHours 8760;foreach($invalidHours in @(0,8761,1.5,'2')){$invalid=$false;try{Assert-WsmObservationHours $invalidHours}catch{$invalid=$true};if(-not $invalid){throw ('Invalid observation duration passed range/integer validation: '+$invalidHours)}}

    # Fail after the first native start side effect but before its ActivationCompleted journal record.
    $plan=Read-WsmTrustedJson $planPath $approval.SHA256;$firstItem=$plan.Items|Where-Object Decision -EQ Include|Sort-Object ItemId|Select-Object -First 1;$secondItem=$plan.Items|Where-Object { $_.ItemId -cne $firstItem.ItemId -and $_.Decision -eq 'Include' }|Select-Object -First 1;$firstName=$firstItem.NaturalKey;$secondName=$secondItem.NaturalKey;$script:failAfterStartName=$firstName
    $cutoverFailed=$false;try{Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack | Out-Null}catch{$cutoverFailed=$true;$cutoverFailure=$_.Exception.Message}
    if(-not $cutoverFailed -or $script:targetServices[$firstName].State -ne 'Running' -or $script:activationCalls[$firstName] -ne 1){throw 'Cutover did not exercise a post-effect/pre-completion activation interruption.'}
    $statePath=Join-Path (Join-Path $targetState $pairId) 'state.json';$interrupted=Read-WsmJson $statePath;if(-not $interrupted.Cutover.NewTransactionsPossible -or @($interrupted.Cutover.Activations|Where-Object {$_.ItemId -ceq $firstItem.ItemId -and $_.Status -eq 'Intent'}).Count -ne 1){throw 'Cutover did not retain transaction boundary and durable first-service intent.'}

    # An interrupted activation cannot be resumed without explicit owner reconciliation evidence.
    $blocked=$false;try{Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack | Out-Null}catch{$blocked=$_.Exception.Message -match 'explicit ResumeActivation'};if(-not $blocked){throw 'Cutover allowed an implicit activation resume.'}

    # Reject final-IP drift and DNS drift before replaying any service activation.
    $script:fixtureAddresses=@([pscustomobject]@{InterfaceAlias='FixtureNIC';IPAddress='192.0.2.99';PrefixLength=24;AddressState='Preferred'});$blocked=$false;try{Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack -ResumeActivation -ResumeOwner 'Fixture cutover owner' -ResumeEvidence 'fixture network reconciliation reviewed' | Out-Null}catch{$blocked=$_.Exception.Message -match 'Final IP/prefix'};if(-not $blocked -or $script:activationCalls[$firstName] -ne 1){throw 'Activation resume accepted final network drift or replayed a service.'}
    $script:fixtureAddresses=@([pscustomobject]@{InterfaceAlias='FixtureNIC';IPAddress='192.0.2.20';PrefixLength=24;AddressState='Preferred'});$script:fixtureDns=@('192.0.2.99');$blocked=$false;try{Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack -ResumeActivation -ResumeOwner 'Fixture cutover owner' -ResumeEvidence 'fixture DNS reconciliation reviewed' | Out-Null}catch{$blocked=$_.Exception.Message -match 'DNS server order'};if(-not $blocked -or $script:activationCalls[$firstName] -ne 1){throw 'Activation resume accepted DNS drift or replayed a service.'}
    $script:fixtureDns=@('192.0.2.53')


    # Resume adopts the already-final first service without calling Start-Service again, then activates the second once.
    $resumed=Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack -ResumeActivation -ResumeOwner 'Fixture cutover owner' -ResumeEvidence 'fixture target state reconciled after injected crash'
    if($resumed.Cutover.Stage -ne 'Activated' -or $script:activationCalls[$firstName] -ne 1 -or $script:activationCalls[$secondName] -ne 1 -or $script:targetServices[$secondName].State -ne 'Running'){throw 'Resume did not adopt first activation and activate the next service exactly once.'}
    $activationRows=@($resumed.Cutover.Activations);if($activationRows.Count -ne 2 -or @($activationRows|Where-Object Status -NE Completed).Count){throw 'Completed cutover did not retain exact activation checkpoints.'}
    $again=Invoke-WsmCutover $manifestPath $manifestHash $targetState $cutover.Path $cutover.SHA256 $ack;if($script:activationCalls[$firstName] -ne 1 -or $script:activationCalls[$secondName] -ne 1){throw 'Completed Cutover replayed a service activation.'}
    # Journal replay must reconstruct the exact duration and activation timestamp from CutoverCompleted.
    $paths=Get-WsmOperationPaths $targetState $pairId;$liveState=Read-WsmJson $paths.State;$events=@(Read-WsmJournalEvents $paths);$completedEvent=@($events|Where-Object {$_.Row.Action -ceq 'CutoverCompleted'});if($completedEvent.Count -ne 1){throw 'Fixture lacks one durable CutoverCompleted event.'}
    $activationUtc=[string]$liveState.Cutover.ActivatedUtc;$reviewedHours=[int]$liveState.Cutover.ObservationHours;if($reviewedHours -ne 2 -or -not $activationUtc){throw 'Cutover did not persist reviewed observation policy and activation time.'}
    $stale=ConvertFrom-WsmJson ($liveState|ConvertTo-Json -Depth 40);$stale.Sequence=$completedEvent[0].Row.Sequence-1;$stale.JournalHash=$completedEvent[0].Row.PreviousHash;$stale.Cutover.PSObject.Properties.Remove('ActivatedUtc');$stale.Cutover.PSObject.Properties.Remove('ObservationHours');Write-WsmJson $paths.State $stale;$checkpoint=Read-WsmJson $paths.State;Restore-WsmJournalCheckpoint $paths $checkpoint
    $replayed=Read-WsmJson $paths.State;if($replayed.Cutover.Stage -cne 'Activated' -or $replayed.Cutover.ActivatedUtc -cne $activationUtc -or [int]$replayed.Cutover.ObservationHours -ne $reviewedHours){throw 'JournalRecovery did not restore the exact CutoverCompleted timestamp and reviewed observation duration.'}
    # Missing or future activation policy cannot record observation evidence, even a failed observation.
    $windowState=Get-WsmOperationState $paths $package;$windowState.Cutover.PSObject.Properties.Remove('ObservationHours');Save-ObservationMutation $paths $windowState
    $blocked=$false;try{Set-WsmExternalFixtureValidationEvidence $manifestPath $manifestHash $targetState '' Observation 'Fixture observer' 'fixture observation failed' $false|Out-Null}catch{$blocked=$_.Exception.Message -match 'reviewed duration'};if(-not $blocked){throw 'Observation evidence accepted a missing reviewed duration.'}
    $windowState=Get-WsmOperationState $paths $package;$windowState.Cutover|Add-Member NoteProperty ObservationHours $reviewedHours -Force;$windowState.Cutover.ActivatedUtc=[DateTimeOffset]::UtcNow.AddMinutes(5).ToString('o');Save-ObservationMutation $paths $windowState
    $blocked=$false;try{Set-WsmExternalFixtureValidationEvidence $manifestPath $manifestHash $targetState '' Observation 'Fixture observer' 'fixture observation failed' $false|Out-Null}catch{$blocked=$_.Exception.Message -match 'Clock precedes'};if(-not $blocked){throw 'Observation evidence accepted a future activation timestamp.'}
    $windowState=Get-WsmOperationState $paths $package;$windowState.Cutover.ActivatedUtc=$activationUtc;Save-ObservationMutation $paths $windowState
    # The public evidence API rejects early success, allows a failed check, and keeps retirement closed.
    $script:observationClock=[DateTimeOffset]::Parse($activationUtc).AddHours(1)
    $blocked=$false;try{Set-WsmExternalFixtureValidationEvidence $manifestPath $manifestHash $targetState '' Observation 'Fixture observer' 'early observation period' $true|Out-Null}catch{$blocked=$_.Exception.Message -match 'has not elapsed'};if(-not $blocked){throw 'Early positive observation evidence was accepted.'}
    $failedObservation=Set-WsmExternalFixtureValidationEvidence $manifestPath $manifestHash $targetState '' Observation 'Fixture observer' 'observed failures remain open' $false
    if($failedObservation.Passed){throw 'Passed=false observation evidence was rewritten as success.'}
    foreach($item in $package.Plan.Items|Where-Object Decision -EQ Include){Set-WsmExternalFixtureValidationEvidence $manifestPath $manifestHash $targetState $item.ItemId BusinessFinal 'Fixture business owner' 'fixture final service acceptance' $true|Out-Null}
    foreach($check in @('DNS','Kerberos','ExternalConnectivity','Monitoring','SecurityAgent','License','UserAcceptance','BackupRestore','LongCycleJobs','RetirementRetention','ExternalConsumerOldPathDrained','SpecialProductDisposition','DataRetentionHandoff','CredentialHandoff','CertificateHandoff','CMDBHandoff','DNSHandoff','LicenseHandoff','MonitoringHandoff','RollbackCutoffAndDeletionOwner')){Set-WsmExternalFixtureValidationEvidence $manifestPath $manifestHash $targetState '' $check 'Fixture acceptance owner' ('fixture '+$check+' evidence') $true|Out-Null}
    if(-not (Invoke-WsmValidation $manifestPath $manifestHash $targetState Final).Passed){throw 'Fixture final per-item validation failed before observation.'}
    $earlyGates=Get-WsmAcceptanceGates $manifestPath $manifestHash $targetState;if($earlyGates.MissingRetirement -notcontains 'Observation' -or $earlyGates.RetirementReady){throw 'A failed early observation opened the retirement gate.'}
    # An accelerated fixture clock proves elapsed duration without sleeping or changing the host clock.
    $script:observationClock=[DateTimeOffset]::Parse($activationUtc).AddHours($reviewedHours).AddMinutes(1)
    Set-WsmExternalFixtureValidationEvidence $manifestPath $manifestHash $targetState '' Observation 'Fixture observer' 'reviewed observation interval elapsed' $true|Out-Null
    $passedGates=Get-WsmAcceptanceGates $manifestPath $manifestHash $targetState;if($passedGates.MissingRetirement -contains 'Observation' -or -not $passedGates.RetirementReady){throw 'Elapsed positive observation did not open the otherwise-complete retirement gate.'}
    # Bind the evidence to both reviewed duration and the completed-activation timestamp.
    $windowState=Get-WsmOperationState $paths $package;$windowState.Cutover.ObservationHours=$reviewedHours+1;Save-ObservationMutation $paths $windowState;$changedPolicy=Get-WsmAcceptanceGates $manifestPath $manifestHash $targetState;if($changedPolicy.MissingRetirement -notcontains 'Observation'){throw 'Old observation evidence survived a changed reviewed duration.'}
    $windowState=Get-WsmOperationState $paths $package;$windowState.Cutover.ObservationHours=$reviewedHours;$windowState.Cutover.ActivatedUtc=[DateTimeOffset]::Parse($activationUtc).AddSeconds(1).ToString('o');Save-ObservationMutation $paths $windowState;$changedActivation=Get-WsmAcceptanceGates $manifestPath $manifestHash $targetState;if($changedActivation.MissingRetirement -notcontains 'Observation'){throw 'Old observation evidence survived a changed activation timestamp.'}
    Write-Host ('PASS: real approved-plan/freeze/staged-restore/cutover/acceptance workflow; durable activation+duration replay; missing/future policy and early positive evidence rejected; failed observation keeps retirement closed; elapsed reviewed duration opens the gate; changed duration/timestamp invalidates prior evidence. OS APIs are fixtures; clock acceleration is confined to test module scope. Root: '+$Root)
} $root $externalReadinessFixturesPath
$resolvedRoot=[IO.Path]::GetFullPath($root).TrimEnd('\');if($resolvedRoot -notmatch '^C:\\wsm-observation-[0-9a-f]{32}$' -or $resolvedRoot -eq 'C:\'){throw ('Refusing fixture cleanup outside the test-owned root: '+$resolvedRoot)};Remove-Item -LiteralPath $resolvedRoot -Recurse -Force
