#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$helper=Join-Path $PSScriptRoot '..\src\AssistiveRestore.ps1'
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-assistive-restore-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
try {
    & $module {
        param($root,$helper)
        . $helper
        $script:nativeAssistiveFileTopology=(Get-Command Assert-WsmAssistiveFileTopology -CommandType Function).ScriptBlock;$script:rejectAssistiveTopologyPath=''
        Set-Item Function:\script:Assert-WsmAssistiveFileTopology -Value {param([string]$Path)if($script:rejectAssistiveTopologyPath -and [IO.Path]::GetFullPath($Path).Equals([IO.Path]::GetFullPath($script:rejectAssistiveTopologyPath),[StringComparison]::OrdinalIgnoreCase)){throw 'Fixture topology boundary rejection.'};& $script:nativeAssistiveFileTopology $Path}
        $script:nativeAssistiveRestoreDecision=(Get-Command Get-WsmAssistiveRestoreDecision -CommandType Function).ScriptBlock
        function Check($condition,[string]$message){if(-not $condition){throw $message};$script:checks++}
        $script:checks=0
        $nativeOwnerProbe=Join-Path $root 'native-acl-owner-probe';[void][IO.Directory]::CreateDirectory($nativeOwnerProbe);$nativeOwnerFile=Join-Path $nativeOwnerProbe 'probe.txt';[IO.File]::WriteAllText($nativeOwnerFile,'owner getter probe')
        foreach($nativeAclPath in @($nativeOwnerProbe,$nativeOwnerFile)){$nativeAcl=Get-Acl -LiteralPath $nativeAclPath -ErrorAction Stop;Check ($nativeAcl.Owner -is [string]) 'Native Windows Get-Acl Owner is expected to be a string.';$nativeOwnerSid=$nativeAcl.GetOwner([Security.Principal.SecurityIdentifier]).Value;Check ($nativeOwnerSid -match '^S-1-\d+(?:-\d+)+$') 'Native Get-Acl.GetOwner(SecurityIdentifier) did not return a SID.'}
        $script:fixtureMetadata=@{};$script:fixtureMetadataDrift=@{};$script:fixtureUtc='2026-10-10T00:00:00.0000000Z'
        function NewEntry([string]$relative,[string]$content){$bytes=[Text.Encoding]::UTF8.GetBytes($content);[pscustomobject]@{ItemId=$script:testItemId;RelativePath=$relative;Directory=$false;Data=[pscustomobject]@{Hash=(Get-WsmHashText $content);Bytes=$bytes.Length;Content=$content};Metadata=[pscustomobject]@{MetadataMode='DaclOwner';Sddl='';Attributes=0;CreationUtc=$script:fixtureUtc;LastWriteUtc=$script:fixtureUtc}}}
        function NewDirectoryEntry([string]$relative){[pscustomobject]@{ItemId=$script:testItemId;RelativePath=$relative;Directory=$true;Data=$null;Metadata=[pscustomobject]@{MetadataMode='DaclOwner';Sddl='';Attributes=[int][IO.FileAttributes]::Directory;CreationUtc=$script:fixtureUtc;LastWriteUtc=$script:fixtureUtc}}}
        function Read-WsmArtifactLines($Path,$Hash,$CancellationToken){$script:testEntries}
        function Restore-WsmPayloadBytes($Entry,$PackageRoot,$Destination,$CancellationToken){[IO.File]::WriteAllText($Destination,[string]$Entry.Data.Content)}
        function Set-WsmFileMetadata($Path,$Metadata,$SidMap){$key=[IO.Path]::GetFullPath($Path);$script:fixtureMetadata[$key]=$Metadata;if($key -match '\.wsm-[a-f0-9]{32}\.tmp$'){$script:fixtureMetadata[[regex]::Replace($key,'\.wsm-[a-f0-9]{32}\.tmp$','')]=$Metadata}}
        function Get-WsmFileMetadata([string]$Path,[string]$Mode){$key=[IO.Path]::GetFullPath($Path);$metadata=$script:fixtureMetadata[$key];if(-not $metadata){$metadata=[pscustomobject]@{MetadataMode=$Mode;Sddl='';Attributes=0;CreationUtc=$script:fixtureUtc;LastWriteUtc=$script:fixtureUtc}};$actual=$metadata.PSObject.Copy();if($script:fixtureMetadataDrift.ContainsKey($key)){$actual.Sddl='DRIFT'};$actual}
        function Add-WsmJournal($Paths,$State,[string]$Action,[string]$ItemId,$Detail){ }
        function Assert-WsmCancellationBoundary($Token,[string]$Name){ }
        function Assert-WsmSoftwareCatalog($SoftwareCatalog,$SourceInventory){ }
        function Get-WsmAssistiveCurrentSoftwareCatalog($Snapshot){$script:currentSoftwareFixture}
        function Assert-WsmAssistiveContract($Data,[string]$Type){ }
        function Assert-WsmTrustedFile([string]$Path,[string]$ExpectedHash){if((Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash -ine $ExpectedHash){throw 'Fixture trusted-file hash mismatch.'}}
        function Read-WsmTrustedJson([string]$Path,[string]$ExpectedHash){Assert-WsmTrustedFile $Path $ExpectedHash;Read-WsmJson $Path}

        function Get-WsmGeneralHostSoftwareFactsHash($Entry){Get-WsmHashText ($Entry | ConvertTo-Json -Depth 20 -Compress)}
        $script:testItemId='0123456789abcdef0123456789abcdef'
        $target=Join-Path $root 'existing';[void][IO.Directory]::CreateDirectory($target)
        $external=Join-Path $target 'external.txt';[IO.File]::WriteAllText($external,'operator data')
        $newEntry=NewEntry 'new.txt' 'new payload';$externalEntry=NewEntry 'external.txt' 'package must not replace this'
        $script:testEntries=@($newEntry,$externalEntry)
        $item=[pscustomobject]@{ItemId=$script:testItemId;MigrationSpec=[pscustomobject]@{Adapter='FileScope';TargetPath=$target}}
        $package=[pscustomobject]@{Root=$root;SHA256=('a'*64);Manifest=[pscustomobject]@{Generation=1;ArtifactsHash=('b'*64)}}
        $paths=[pscustomobject]@{Root=$root;State=$null;Journal=$null};$state=[pscustomobject]@{Items=@();PendingOperations=@()}
        $result=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check ($result.Status -eq 'BlockedConflict') 'External-file collision did not retain a per-file conflict result.'
        Check ([IO.File]::ReadAllText($external) -ceq 'operator data') 'Existing external file was overwritten.'
        Check ([IO.File]::ReadAllText((Join-Path $target 'new.txt')) -ceq 'new payload') 'Independent new file was not placed into the existing directory.'
        Check (@($result.FileResults|Where-Object Status -eq Applied).Count -eq 1) 'Successful child file was lost because a sibling conflicted.'
        $appliedResult=@($result.FileResults|Where-Object Status -eq Applied)[0];Check ($appliedResult.MetadataStatus -ceq 'Verified' -and $result.OwnedFiles[0].MetadataHash -match '^[a-f0-9]{64}$') 'Successful file placement did not persist verified ACL/owner/attribute/timestamp readback evidence.'

        $ownedTarget=Join-Path $root 'owned';[void][IO.Directory]::CreateDirectory($ownedTarget);$ownedPath=Join-Path $ownedTarget 'app.config';[IO.File]::WriteAllText($ownedPath,'old owned bytes')
        $oldHash=(Get-FileHash -LiteralPath $ownedPath -Algorithm SHA256).Hash.ToLowerInvariant();$script:testEntries=@((NewEntry 'app.config' 'new owned bytes'));$priorMetadataHash=Get-WsmAssistiveMetadataHash $script:testEntries[0].Metadata
        $item.MigrationSpec.TargetPath=$ownedTarget;$state.Items=@([pscustomobject]@{ItemId=$script:testItemId;Status='Succeeded';CreatedByTool=$true;AppliedManifestHash=('c'*64);AppliedGeneration=1;OwnedFiles=@([pscustomobject]@{RelativePath='app.config';TargetPath=$ownedPath;SHA256=$oldHash;MetadataHash=$priorMetadataHash;Generation=1});OwnedDirectories=@()});$package.Manifest.Generation=2
        $result=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check ($result.Status -eq 'Succeeded') 'Verified owned file was not replaced by the next approved generation.'
        Check ([IO.File]::ReadAllText($ownedPath) -ceq 'new owned bytes') 'Approved owned-file update did not read back.'
        Check ($result.OwnedFiles[0].Backup -and [IO.File]::ReadAllText($result.OwnedFiles[0].Backup) -ceq 'old owned bytes') 'Prior owned bytes were not retained for rollback.'
        Check ($result.OwnedFiles[0].MetadataHash -match '^[a-f0-9]{64}$' -and @($result.FileResults|Where-Object {$_.Status -eq 'Applied' -and $_.MetadataStatus -eq 'Verified'}).Count -eq 1) 'Updated owned file did not retain verified native metadata evidence.'

        $directoryTarget=Join-Path $root 'directory-metadata';$script:testEntries=@((NewDirectoryEntry ''),(NewDirectoryEntry 'nested'),(NewEntry 'nested\settings.ini' 'directory payload'));$item.MigrationSpec.TargetPath=$directoryTarget;$state.Items=@();$package.Manifest.Generation=3
        $directoryResult=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check ($directoryResult.Status -eq 'Succeeded' -and (Test-Path -LiteralPath (Join-Path $directoryTarget 'nested\settings.ini'))) 'New native directory tree was not completely restored.'
        Check (@($directoryResult.OwnedDirectories|Where-Object {$_.RelativePath -ceq '' -and $_.TargetPath -ceq $directoryTarget -and $_.MetadataHash -match '^[a-f0-9]{64}$'}).Count -eq 1 -and @($directoryResult.OwnedDirectories|Where-Object {$_.RelativePath -ceq 'nested' -and $_.MetadataHash -match '^[a-f0-9]{64}$'}).Count -eq 1) 'New root/nested directories lack verified metadata ownership evidence.'
        Check (@($directoryResult.FileResults|Where-Object {$_.Status -eq 'DirectoryVerified' -and $_.MetadataStatus -eq 'Verified'}).Count -eq 2) 'Directory ACL/owner/attribute/timestamp metadata was not applied and read back.'
        $script:rejectAssistiveTopologyPath=$directoryTarget;$directoryTopologyRejected=$false;try{Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null|Out-Null}catch{$directoryTopologyRejected=$true};$script:rejectAssistiveTopologyPath=''
        Check ($directoryTopologyRejected -and (Test-Path -LiteralPath (Join-Path $directoryTarget 'nested\settings.ini'))) 'Existing directory target topology failure did not fail closed before G writes.'

        $singleParent=Join-Path $root 'single-file-parent';$singleTarget=Join-Path $singleParent 'settings.ini';$script:testEntries=@((NewEntry '' 'single-file payload'));$item.MigrationSpec.TargetPath=$singleTarget;$state.Items=@();$package.Manifest.Generation=4
        $singleResult=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check ([IO.File]::Exists($singleTarget) -and -not [IO.Directory]::Exists($singleTarget) -and [IO.File]::ReadAllText($singleTarget) -ceq 'single-file payload') 'Single-file source scope was not restored to its exact TargetPath file.'
        Check (@($singleResult.OwnedFiles|Where-Object {$_.RelativePath -ceq '' -and $_.TargetPath -ceq $singleTarget -and $_.MetadataHash -match '^[a-f0-9]{64}$'}).Count -eq 1 -and @($singleResult.OwnedDirectories).Count -eq 0) 'Single-file ownership was not recorded against the exact file target.'
        $state.Items=@($singleResult);$package.Manifest.Generation=5;$singleVerify=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check (@($singleVerify.FileResults|Where-Object Status -eq VerifiedOwned).Count -eq 1 -and -not $singleVerify.OwnedFiles[0].Backup) 'Owned single-file rerun was not verified without a needless replacement.'
        $script:fixtureMetadataDrift[[IO.Path]::GetFullPath($singleTarget)]=$true;$state.Items=@($singleResult);$singleDrift=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check ($singleDrift.Status -eq 'BlockedConflict' -and [IO.File]::ReadAllText($singleTarget) -ceq 'single-file payload' -and $singleDrift.OwnedFiles[0].Generation -eq 5) 'VerifiedOwned accepted metadata drift or advanced its ownership generation.'
        $script:fixtureMetadataDrift.Remove([IO.Path]::GetFullPath($singleTarget))
        $singleExternal=Join-Path $root 'single-file-external.ini';[IO.File]::WriteAllText($singleExternal,'operator-owned');$item.MigrationSpec.TargetPath=$singleExternal;$state.Items=@();$singleCollision=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check ($singleCollision.Status -eq 'BlockedConflict' -and [IO.File]::ReadAllText($singleExternal) -ceq 'operator-owned') 'External file at an exact single-file destination was overwritten.'
        $singleReplacement='replacement payload';$script:testEntries=@((NewEntry '' $singleReplacement));$item.MigrationSpec.TargetPath=$singleTarget;$state.Items=@($singleVerify);$package.Manifest.Generation=6;$script:rejectAssistiveTopologyPath=$singleTarget;$singleTopologyRejected=$false;try{Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null|Out-Null}catch{$singleTopologyRejected=$true};$script:rejectAssistiveTopologyPath=''
        Check ($singleTopologyRejected -and [IO.File]::ReadAllText($singleTarget) -ceq 'single-file payload' -and @($state.PendingOperations).Count -eq 0) 'Existing owned single-file topology failure did not block replacement before intent or preserve prior bytes.'
        $state.Items=@($singleResult);$singleUpdate=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check ([IO.File]::ReadAllText($singleTarget) -ceq $singleReplacement -and $singleUpdate.OwnedFiles[0].Backup -and [IO.File]::ReadAllText($singleUpdate.OwnedFiles[0].Backup) -ceq 'single-file payload') 'Owned single-file generation update did not retain exact prior bytes for rollback.'

        $driftTarget=Join-Path $root 'metadata-drift';[void][IO.Directory]::CreateDirectory($driftTarget);$driftFile=Join-Path $driftTarget 'drift.txt';$script:testEntries=@((NewEntry 'drift.txt' 'drift payload'));$script:fixtureMetadataDrift[[IO.Path]::GetFullPath($driftFile)]=$true;$item.MigrationSpec.TargetPath=$driftTarget;$state.Items=@();$package.Manifest.Generation=4
        $driftResult=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check ($driftResult.Status -eq 'Failed' -and @($driftResult.FileResults|Where-Object {$_.Status -eq 'Failed' -and $_.MetadataStatus -ne 'Verified'}).Count -eq 1 -and @($state.PendingOperations|Where-Object RelativePath -eq 'drift.txt').Count -eq 1) 'Metadata drift after file replacement was adopted without repair intent.'

        [IO.File]::WriteAllText($ownedPath,'operator drift')
        $result=Invoke-WsmAssistiveFileScopeRestore $item $package $paths $state @{} $null
        Check ($result.Status -eq 'BlockedConflict') 'Drifted owned file was silently replaced.'
        Check ([IO.File]::ReadAllText($ownedPath) -ceq 'operator drift') 'Drifted owned file was overwritten.'

        $doc=Read-WsmXml '<rules><rule name="legacy" enabled="true" /></rules>'
        $changes=@([pscustomobject]@{Operation='SetAttribute';FieldPointer="/rules/rule[@name='legacy']/@enabled";ElementName='rule';AttributeName='enabled';BeforeValue='true';AfterValue='false';KeyAttributes=@()})
        $mapped=Set-WsmIisConfigChanges $doc $changes
        Check ($mapped.SelectSingleNode('/rules/rule').GetAttribute('enabled') -ceq 'false') 'Typed IIS pointer did not apply the selected attribute change.'
        $opaque=[pscustomobject]@{MigrationSpec=[pscustomobject]@{Adapter='IISLocation';SourceXml='<rules />';SourceAutoStart='Unknown';StagedDisabled=$true;DesiredFinalState='Disabled';WorkloadMappingReview=@([pscustomobject]@{FieldPointer='/rules/rule/@command';OldRawValue='tool --password SuperSecretValue';TargetValue='';Applied=$false;Status='Opaque';ReviewRequired=$true;Reason='Command contains opaque arguments.'})}}
        $readiness=Get-WsmAssistiveWorkloadReadiness $opaque
        Check ($readiness.Status -eq 'ManualEvidenceRequired') 'Opaque command argument did not require manual owner review.'
        Check ($readiness.Reason -notmatch 'SuperSecretValue|password') 'Safe readiness projection leaked opaque command-line material.'

        $taskSource='<Task xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"><Settings><Enabled>false</Enabled></Settings><Actions><Exec><Command>C:\Fixture\worker.exe</Command></Exec></Actions></Task>'
        $taskTarget=$taskSource.Replace('<Enabled>false</Enabled>','<Enabled>false</Enabled>')
        $taskSpec=[pscustomobject]@{Adapter='ScheduledTask';SourceXml=$taskSource;SourceAutoStart='false';StagedDisabled=$true;DesiredFinalState='Disabled';ActivationPolicyFieldPointer='Task/Settings/Enabled';ReviewedActivation=[pscustomobject]@{FinalState='Disabled';Owner='Fixture owner';Reason='Keep task stopped pending acceptance.';SourceAutoStart='false';FieldPointer='Task/Settings/Enabled'};Desired=[pscustomobject]@{Xml=$taskTarget}}
        Assert-WsmAssistiveReviewedActivation $taskSpec
        Check $true 'Explicit disabled activation intent was rejected.'
        $taskSpec.ReviewedActivation.FinalState='Enabled';$taskSpec.DesiredFinalState='Enabled';$taskSpec.ReviewedActivation.Reason='Enable after business acceptance.'
        $rejected=$false;try{Assert-WsmAssistiveReviewedActivation $taskSpec|Out-Null}catch{$rejected=$true}
        Check $rejected 'Source-disabled task was enabled without an owner reason acknowledging the changed source policy.'
        $taskSpec.ReviewedActivation.Reason='Owner approves enabling despite source task being disabled.'
        Assert-WsmAssistiveReviewedActivation $taskSpec
        Check $true 'Explicit owner-approved activation from source-disabled policy was rejected.'
        $sourceDisabledReason=([string][char]0x8CA0)+[char]0x8CAC+[char]0x4EBA+[char]0x6838+[char]0x51C6+[char]0xFF0C+[char]0x5373+[char]0x4F7F+[char]0x4F86+[char]0x6E90+[char]0x5DE5+[char]0x4F5C+[char]0x5DF2+[char]0x505C+[char]0x7528+[char]0xFF0C+[char]0x9A57+[char]0x6536+[char]0x5F8C+[char]0x4ECD+[char]0x555F+[char]0x7528+[char]0x3002
        $taskSpec.ReviewedActivation.Reason=$sourceDisabledReason
        Assert-WsmAssistiveReviewedActivation $taskSpec
        Check $true 'Unicode owner reason acknowledging the source-disabled policy was rejected.'
        $taskSpec.SourceXml=$taskSource.Replace('<Enabled>false</Enabled>','<Enabled>true</Enabled>');$taskSpec.SourceAutoStart='true';$taskSpec.ReviewedActivation.SourceAutoStart='true';$taskSpec.ReviewedActivation.Reason='Preserve approved source startup policy.'
        Assert-WsmAssistiveReviewedActivation $taskSpec
        Check $true 'Enabled activation matching the protected source startup policy was rejected.'

        $iisSource='<rules><rule name="legacy" enabled="true" path="C:\\source" /></rules>';$iisStaged='<rules><rule name="legacy" enabled="false" path="C:\\target" /></rules>'
        $iisSpec=[pscustomobject]@{Adapter='IISSection';SourceXml=$iisSource;SourceAutoStart='true';StagedDisabled=$true;DesiredFinalState='Enabled';ActivationPolicyFieldPointer="/rules/rule[@name='legacy']/@enabled";ReviewedActivation=[pscustomobject]@{FinalState='Enabled';Owner='Fixture owner';Reason='Preserve the explicitly approved source startup behavior.';SourceAutoStart='true';FieldPointer="/rules/rule[@name='legacy']/@enabled";StagedValue='false';FinalValue='true'};Desired=[pscustomobject]@{SectionPath='system.webServer/rewrite/rules';LocationPath='';Xml=$iisStaged;Changes=@()}}
        Assert-WsmAssistiveReviewedActivation $iisSpec
        $iisFinalXml=Get-WsmIisReviewedActivationXml $iisSpec;$iisFinalDoc=Read-WsmXml $iisFinalXml
        Check ($iisFinalDoc.DocumentElement.FirstChild.GetAttribute('enabled') -ceq 'true' -and $iisFinalDoc.DocumentElement.FirstChild.GetAttribute('path') -ceq 'C:\\target') 'IIS config final intent changed an unreviewed sibling attribute or failed to apply its one approved field.'
        $iisSpec.ReviewedActivation.FinalValue='AlwaysRunning';$iisSpec.DesiredFinalState='Enabled';$iisSpec.ReviewedActivation.FieldPointer="/rules/rule[@name='legacy']/@enabled"
        $iisInvalidValue=$false;try{Assert-WsmAssistiveReviewedActivation $iisSpec|Out-Null}catch{$iisInvalidValue=$true}
        Check $iisInvalidValue 'IIS config activation accepted a final value outside the typed activation field domain.'

        $softwareEntry=[pscustomobject]@{SoftwareId='sw-fixture';Name='Fixture Runtime';Version='1.2.3';Publisher='Fixture';Architecture='x64';Scope='Machine';SID='';RegistryView='Registry64';Location='C:\Fixture\runtime';SourceKind='Registry';Evidence=[pscustomobject]@{RegistryPath='fixture';NaturalKey='fixture'};CaptureStatus='Success';ItemIds=@();AccountContext='Unknown'}
        $softwareCatalog=[pscustomobject]@{Entries=@($softwareEntry);Coverage=@([pscustomobject]@{Probe='ProfileList';Scope='User';SID='S-1-5-21-fixture';View='Registry64';Status='PermissionDenied';EvidenceKind='Registry';Count=0;ErrorKind='AccessDenied';ItemId=''})};$softwareSnapshot=[pscustomobject]@{SoftwareCatalog=$softwareCatalog};$script:currentSoftwareFixture=$softwareCatalog
        $softwareCheck=Assert-WsmAssistiveCurrentSoftware $softwareSnapshot
        Check ($softwareCheck.Status -eq 'Match' -and $softwareCheck.Coverage -eq 'Incomplete' -and $softwareCheck.CoverageGapCount -eq 1 -and $softwareCheck.ProductionVerified -eq $false) 'Stable incomplete profile coverage globally blocked an unrelated restore or was reported complete.'
        $profileGap=[pscustomobject]@{ConsumerItemId='runtime-item';Issue='Required runtime was not observed because profile coverage is incomplete.'};$fileDependencyIssues=Get-WsmAssistiveItemDependencyIssues @($profileGap) $script:testItemId;$runtimeDependencyIssues=Get-WsmAssistiveItemDependencyIssues @($profileGap) 'runtime-item'
        Check (@($fileDependencyIssues).Count -eq 0 -and @($runtimeDependencyIssues).Count -eq 1) 'An incomplete profile/portable probe did not stay scoped to its affected runtime consumer.'
        $dependencyPackage=[pscustomobject]@{Plan=[pscustomobject]@{Items=@([pscustomobject]@{ItemId='runtime-item'},[pscustomobject]@{ItemId=$script:testItemId});GeneralHost=[pscustomobject]@{Requirements=@([pscustomobject]@{RequirementId='req-fixture';ProviderSoftwareId='sw-fixture';ConsumerItemIds=@('runtime-item');Certainty='Required';Decision='Required'})}}}
        $dependencyDecision=[pscustomobject]@{SelectedItemIds=@('runtime-item');Receipt=[pscustomobject]@{Comparison=[pscustomobject]@{Rows=@([pscustomobject]@{SoftwareId='sw-fixture';SourceVersion='1.2.3';ChosenVersion='2.0.0';ObservedTargetVersion='2.0.0';Status='ChosenVersionObserved'})}}}
        $chosenIssues=Get-WsmAssistiveComparisonDependencyIssues $dependencyPackage $dependencyDecision
        Check (@($chosenIssues).Count -eq 0) 'A newer chosen version observed on the target was not accepted as the current dependency expectation.'
        $dependencyDecision.Receipt.Comparison.Rows[0].ObservedTargetVersion='1.2.3';$dependencyDecision.Receipt.Comparison.Rows[0].Status='DifferentFromChosenVersion';$differentIssues=Get-WsmAssistiveComparisonDependencyIssues $dependencyPackage $dependencyDecision
        Check (@($differentIssues | Where-Object ConsumerItemId -CEQ 'runtime-item').Count -eq 1 -and @($differentIssues | Where-Object ConsumerItemId -CEQ $script:testItemId).Count -eq 0) 'An outdated chosen dependency blocked an independent FileScope item or failed to defer its own consumer.'
        $dependencyDecision.Receipt.Comparison.Rows=@();$missingIssues=Get-WsmAssistiveComparisonDependencyIssues $dependencyPackage $dependencyDecision
        Check (@($missingIssues | Where-Object ConsumerItemId -CEQ 'runtime-item').Count -eq 1) 'Missing chosen-version evidence did not remain scoped to the dependent item.'
        $targetPeer=[pscustomobject]@{PeerName='fixture-target';ShareName='data';LocalPhysicalRoot='D:\approved';PeerFingerprint=('b'*64)};$targetPhysicalProof=[pscustomobject]@{PeerShareProofs=@($targetPeer)}
        $nativePackage=[pscustomobject]@{Plan=[pscustomobject]@{Items=@([pscustomobject]@{ItemId=$script:testItemId;MigrationSpec=[pscustomobject]@{Adapter='FileScope';TransferChannel='NonC';TargetPath='D:\approved';ContentSelection='ExactFiles'}})}}
        $nativeEntry=[pscustomobject]@{ItemId=$script:testItemId;EntryType='File';RelativePath='app\worker.dll';TargetPath='\\fixture-target\data\app\worker.dll';TargetPhysicalIdentity=(Get-WsmAssistiveEndpointIdentity '\\fixture-target\data\app\worker.dll' @($targetPeer))};$nativePath=Get-WsmAssistiveNonCTargetNativePath $nativePackage $nativeEntry @($nativeEntry) $targetPhysicalProof
        Check ($nativePath -ceq 'D:\approved\app\worker.dll') 'Exact-file NonC destination did not resolve from the sealed native target and relative path.'
        $nativeProjection=ConvertTo-WsmAssistiveNonCFileResultRows $script:testItemId @([pscustomobject]@{EntryId=('a'*64);RelativePath='app\worker.dll';EntryType='File';Status='Applied';TargetPath=$nativePath;OriginalSourcePath='\\source\share\worker.dll';SHA256=('a'*64);SourceSHA256=('a'*64);Reason='';Generation=2})
        Check ($nativeProjection[0].PreservedPath -ceq $nativePath -and $nativeProjection[0].OriginalPath -ceq '\\source\share\worker.dll' -and $nativeProjection[0].EffectivePath -ceq $nativePath) 'NonC file projection confused the UNC source path with the native target preservation/effective path.'
        $deferredProjection=ConvertTo-WsmAssistiveNonCFileResultRows $script:testItemId @([pscustomobject]@{EntryId=('b'*64);RelativePath='app\worker.dll';EntryType='File';Status='Deferred';TargetPath=$nativePath;OriginalSourcePath='\\source\share\worker.dll';SHA256='';SourceSHA256=('a'*64);Reason='No readback';Generation=2})
        Check (-not $deferredProjection[0].EffectivePath) 'A NonC row without native target readback exposed an EffectivePath.'
        $nativeEntry.TargetPath='\\source\share\worker.dll';$sourcePathRejected=$false;try{Get-WsmAssistiveNonCTargetNativePath $nativePackage $nativeEntry @($nativeEntry) $targetPhysicalProof|Out-Null}catch{$sourcePathRejected=$true}
        Check $sourcePathRejected 'A source UNC path was accepted as the sealed target native destination.'
        $script:currentSoftwareFixture=[pscustomobject]@{Entries=@($softwareEntry);Coverage=@([pscustomobject]@{Probe='ProfileList';Scope='User';SID='S-1-5-21-fixture';View='Registry64';Status='Success';EvidenceKind='Registry';Count=0;ErrorKind='';ItemId=''})};$coverageDriftRejected=$false;try{Assert-WsmAssistiveCurrentSoftware $softwareSnapshot|Out-Null}catch{$coverageDriftRejected=$true}
        Check $coverageDriftRejected 'A changed target software coverage vector reused the prior decision receipt.'
        $script:currentSoftwareFixture=[pscustomobject]@{Entries=@([pscustomobject]@{SoftwareId='sw-fixture';Name='Fixture Runtime';Version='9.9.9';Publisher='Fixture';Architecture='x64';Scope='Machine';SID='';RegistryView='Registry64';Location='C:\Fixture\runtime';SourceKind='Registry';Evidence=[pscustomobject]@{RegistryPath='fixture';NaturalKey='fixture'};CaptureStatus='Success';ItemIds=@();AccountContext='Unknown'});Coverage=@([pscustomobject]@{Status='Success'})}
        $driftRejected=$false;try{Assert-WsmAssistiveCurrentSoftware $softwareSnapshot|Out-Null}catch{$driftRejected=$true}
        Check $driftRejected 'Changed target software version passed the decision freshness gate.'

        # Schema 3 decision evidence must carry the exact comparison and prove
        # that each observed version came from the fingerprinted target snapshot.
        $identity=('9'*64);$targetSnapshot=[pscustomobject]@{CreatedUtc=[DateTime]::UtcNow.ToString('o');Source=[pscustomobject]@{Fingerprint=$identity};SoftwareCatalog=$softwareCatalog}
        $snapshotPath=Join-Path $root 'decision-snapshot.json';Write-WsmJson $snapshotPath $targetSnapshot;$snapshotHash=(Get-FileHash -LiteralPath $snapshotPath -Algorithm SHA256).Hash.ToLowerInvariant()
        $comparison=[pscustomobject][ordered]@{Revision=7;SourceSnapshotHash=('1'*64);TargetSnapshotHash=$snapshotHash;SelectionRevision=3;Rows=@([pscustomobject][ordered]@{SoftwareId='sw-fixture';SourceVersion='1.2.3';ChosenVersion='2.0.0';ObservedTargetVersion='1.2.3';TargetSoftwareId='sw-fixture';Status='DifferentFromChosenVersion'})}
        $plan=[pscustomobject]@{SchemaVersion=3;Kind='MigrationPlan';PairId='pair-fixture';Assistive=[pscustomobject]@{SourceSnapshotHash=('1'*64);ApprovedItemIds=@($script:testItemId)};Items=@([pscustomobject]@{ItemId=$script:testItemId})}
        $decisionPackage=[pscustomobject]@{SHA256=('2'*64);PlanHash=('3'*64);Plan=$plan;Manifest=[pscustomobject]@{PairId='pair-fixture';PlanHash=('3'*64);Generation=5;Target=[pscustomobject]@{Fingerprint=$identity}}}
        $receipt=[pscustomobject][ordered]@{SchemaVersion=1;Kind='AssistiveTargetDecisionReceipt';ReceiptId='fixture';PairId='pair-fixture';PlanHash=('3'*64);ManifestHash=('2'*64);Generation=5;TargetSnapshotHash=$snapshotHash;ComparisonRevision=7;SelectionRevision=3;Decision='RestoreNow';Owner='Fixture owner';Reason='Exercise exact restore evidence';SelectedItemIds=@($script:testItemId);AcceptedUnpreparedItemIds=@();CreatedUtc=[DateTime]::UtcNow.ToString('o');Comparison=$comparison;ComparisonHash=(Get-WsmHashText ($comparison | ConvertTo-Json -Depth 100 -Compress));SHA256=('4'*64)}
        $receiptPath=Join-Path $root 'decision-receipt.json';Write-WsmJson $receiptPath $receipt;$receiptHash=(Get-FileHash -LiteralPath $receiptPath -Algorithm SHA256).Hash.ToLowerInvariant()
        $script:currentSoftwareFixture=$softwareCatalog
        $accepted=Get-WsmAssistiveRestoreDecision $decisionPackage $decisionPackage.SHA256 $receiptPath $receiptHash $snapshotPath
        Check (@($accepted.SelectedItemIds).Count -eq 1 -and $accepted.Receipt.Comparison.Rows[0].ChosenVersion -ceq '2.0.0') 'A newer explicitly chosen version with exact observed snapshot evidence was not preserved through restore decision validation.'
        $bindingPackage=$decisionPackage.PSObject.Copy();$bindingPackage.Plan=$plan.PSObject.Copy();$bindingPackage.Plan | Add-Member NoteProperty GeneralHost ([pscustomobject]@{SoftwareCatalog=[pscustomobject]@{Entries=@([pscustomobject]@{SoftwareId='sw-fixture';Version='1.2.3'})}}) -Force
        $goodObservedComparison=$comparison.PSObject.Copy();$goodObservedComparison.Rows=@($comparison.Rows[0].PSObject.Copy());$goodObservedComparison.Rows[0].Status='ChosenVersionObserved';$goodObservedComparison.Rows[0].ObservedTargetVersion='2.0.0';$receipt.Comparison=$goodObservedComparison;$receipt.ComparisonHash=Get-WsmHashText ($goodObservedComparison|ConvertTo-Json -Depth 100 -Compress)
        $bindingResult=& $module {param($package,$decisionReceipt) Assert-WsmAssistiveReceiptComparisonBinding $package $decisionReceipt} $bindingPackage $receipt
        Check $bindingResult 'A comparison with exact chosen/observed equality and sealed source version was rejected.'
        $badDifferentComparison=$goodObservedComparison.PSObject.Copy();$badDifferentComparison.Rows=@($goodObservedComparison.Rows[0].PSObject.Copy());$badDifferentComparison.Rows[0].Status='DifferentFromChosenVersion';$receipt.Comparison=$badDifferentComparison;$receipt.ComparisonHash=Get-WsmHashText ($badDifferentComparison|ConvertTo-Json -Depth 100 -Compress)
        $statusMismatchRejected=$false;try{& $module {param($package,$decisionReceipt) Assert-WsmAssistiveReceiptComparisonBinding $package $decisionReceipt} $bindingPackage $receipt|Out-Null}catch{$statusMismatchRejected=$true}
        Check $statusMismatchRejected 'DifferentFromChosenVersion accepted equal chosen and observed versions.'
        $badChosenComparison=$goodObservedComparison.PSObject.Copy();$badChosenComparison.Rows=@($goodObservedComparison.Rows[0].PSObject.Copy());$badChosenComparison.Rows[0].ChosenVersion='3.0.0';$receipt.Comparison=$badChosenComparison;$receipt.ComparisonHash=Get-WsmHashText ($badChosenComparison|ConvertTo-Json -Depth 100 -Compress)
        $chosenMismatchRejected=$false;try{& $module {param($package,$decisionReceipt) Assert-WsmAssistiveReceiptComparisonBinding $package $decisionReceipt} $bindingPackage $receipt|Out-Null}catch{$chosenMismatchRejected=$true}
        Check $chosenMismatchRejected 'ChosenVersionObserved accepted unequal chosen and observed versions.'
        $badSourceComparison=$goodObservedComparison.PSObject.Copy();$badSourceComparison.Rows=@($goodObservedComparison.Rows[0].PSObject.Copy());$badSourceComparison.Rows[0].SourceVersion='8.8.8';$receipt.Comparison=$badSourceComparison;$receipt.ComparisonHash=Get-WsmHashText ($badSourceComparison|ConvertTo-Json -Depth 100 -Compress)
        $sourceVersionMismatchRejected=$false;try{& $module {param($package,$decisionReceipt) Assert-WsmAssistiveReceiptComparisonBinding $package $decisionReceipt} $bindingPackage $receipt|Out-Null}catch{$sourceVersionMismatchRejected=$true}
        Check $sourceVersionMismatchRejected 'Comparison SourceVersion differing from the sealed GeneralHost catalog was accepted.'
        $receipt.Comparison=$comparison;$receipt.ComparisonHash=Get-WsmHashText ($comparison|ConvertTo-Json -Depth 100 -Compress)
        $missingComparison=$receipt.PSObject.Copy();$missingComparison.PSObject.Properties.Remove('Comparison');Write-WsmJson $receiptPath $missingComparison;$receiptHash=(Get-FileHash -LiteralPath $receiptPath -Algorithm SHA256).Hash.ToLowerInvariant();$missingRejected=$false;try{Get-WsmAssistiveRestoreDecision $decisionPackage $decisionPackage.SHA256 $receiptPath $receiptHash $snapshotPath|Out-Null}catch{$missingRejected=$true}
        Check $missingRejected 'Schema 3 restore accepted a decision receipt without embedded comparison evidence.'
        $tampered=$receipt.PSObject.Copy();$tampered.Owner='Changed after approval';Write-WsmJson $receiptPath $tampered;$tamperRejected=$false;try{Get-WsmAssistiveRestoreDecision $decisionPackage $decisionPackage.SHA256 $receiptPath $receiptHash $snapshotPath|Out-Null}catch{$tamperRejected=$true}
        Check $tamperRejected 'Receipt content changed after approval but the prior trusted hash still passed.'
        $badComparison=$comparison.PSObject.Copy();$badComparison.SourceSnapshotHash=('5'*64);$receipt.Comparison=$badComparison;$receipt.ComparisonHash=(Get-WsmHashText ($badComparison|ConvertTo-Json -Depth 100 -Compress));Write-WsmJson $receiptPath $receipt;$receiptHash=(Get-FileHash -LiteralPath $receiptPath -Algorithm SHA256).Hash.ToLowerInvariant();$sourceBindingRejected=$false;try{Get-WsmAssistiveRestoreDecision $decisionPackage $decisionPackage.SHA256 $receiptPath $receiptHash $snapshotPath|Out-Null}catch{$sourceBindingRejected=$true}
        Check $sourceBindingRejected 'Restore accepted comparison evidence from a different sealed source snapshot.'
        $wrongObserved=$comparison.PSObject.Copy();$wrongObserved.TargetSnapshotHash=$snapshotHash;$wrongObserved.Rows=@($comparison.Rows[0].PSObject.Copy());$wrongObserved.Rows[0].ObservedTargetVersion='9.9.9';$receipt.Comparison=$wrongObserved;$receipt.TargetSnapshotHash=$snapshotHash;$receipt.ComparisonHash=(Get-WsmHashText ($wrongObserved|ConvertTo-Json -Depth 100 -Compress));Write-WsmJson $receiptPath $receipt;$receiptHash=(Get-FileHash -LiteralPath $receiptPath -Algorithm SHA256).Hash.ToLowerInvariant();$observedBindingRejected=$false;try{Get-WsmAssistiveRestoreDecision $decisionPackage $decisionPackage.SHA256 $receiptPath $receiptHash $snapshotPath|Out-Null}catch{$observedBindingRejected=$true}
        Check $observedBindingRejected 'Comparison observed target version was not checked against the exact snapshot catalog.'
        $receipt.Comparison=$comparison;$receipt.ComparisonHash=(Get-WsmHashText ($comparison|ConvertTo-Json -Depth 100 -Compress));$targetSnapshot.Source.PSObject.Properties.Remove('Fingerprint');Write-WsmJson $snapshotPath $targetSnapshot;$snapshotHash=(Get-FileHash -LiteralPath $snapshotPath -Algorithm SHA256).Hash.ToLowerInvariant();$receipt.TargetSnapshotHash=$snapshotHash;$receipt.Comparison.TargetSnapshotHash=$snapshotHash;$receipt.ComparisonHash=(Get-WsmHashText ($receipt.Comparison|ConvertTo-Json -Depth 100 -Compress));Write-WsmJson $receiptPath $receipt;$receiptHash=(Get-FileHash -LiteralPath $receiptPath -Algorithm SHA256).Hash.ToLowerInvariant();$fingerprintRejected=$false;try{Get-WsmAssistiveRestoreDecision $decisionPackage $decisionPackage.SHA256 $receiptPath $receiptHash $snapshotPath|Out-Null}catch{$fingerprintRejected=$true}
        Check $fingerprintRejected 'Restore accepted a target snapshot with no native target fingerprint.'
        $targetSnapshot.Source | Add-Member NoteProperty Fingerprint ('8'*64) -Force;Write-WsmJson $snapshotPath $targetSnapshot;$snapshotHash=(Get-FileHash -LiteralPath $snapshotPath -Algorithm SHA256).Hash.ToLowerInvariant();$receipt.TargetSnapshotHash=$snapshotHash;$receipt.Comparison.TargetSnapshotHash=$snapshotHash;$receipt.ComparisonHash=(Get-WsmHashText ($receipt.Comparison|ConvertTo-Json -Depth 100 -Compress));Write-WsmJson $receiptPath $receipt;$receiptHash=(Get-FileHash -LiteralPath $receiptPath -Algorithm SHA256).Hash.ToLowerInvariant();$wrongFingerprintRejected=$false;try{Get-WsmAssistiveRestoreDecision $decisionPackage $decisionPackage.SHA256 $receiptPath $receiptHash $snapshotPath|Out-Null}catch{$wrongFingerprintRejected=$true}
        Check $wrongFingerprintRejected 'Restore accepted a native fingerprint that differs from the sealed package target.'

        function Test-WsmMigrationPackage($ManifestPath,$ExpectedHash,$CancellationToken){$script:previewPackage}
        function Assert-WsmMigrationHost($Identity,$Fingerprint){ }
        function Get-WsmAssistiveRestoreDecision($Package,$ExpectedHash,$ReceiptPath,$ReceiptHash,$SnapshotPath){$script:previewDecision}
        function Get-WsmOperationPaths($StateDirectory,$PairId){[pscustomobject]@{Root=$StateDirectory;State=$null;Journal=$null}}
        function Get-WsmOperationState($Paths,$Package){$script:previewState}
        function Get-WsmAssistiveNonCResultRows($Package,$TransferPlanPath,$TransferPlanHash,$ResultPath,$ResultHash,$StateDirectory){@{}}        $previewTarget=Join-Path $root 'preview-single\exact.ini';$previewMetadata=NewEntry '' 'preview single payload';$script:testEntries=@($previewMetadata);$previewItem=[pscustomobject]@{ItemId=$script:testItemId;Name='preview single';Decision='Include';Dependencies=@();MigrationSpec=[pscustomobject]@{Adapter='FileScope';TransferChannel='C';TargetPath=$previewTarget;Metadata='DaclOwner'}};$script:previewPackage=[pscustomobject]@{Root=$root;Plan=[pscustomobject]@{Items=@($previewItem)};Manifest=[pscustomobject]@{PairId='pair-fixture';PlanHash=('3'*64);Generation=9;Target=[pscustomobject]@{Fingerprint=$identity};ArtifactsHash=('b'*64)}};$script:previewDecision=[pscustomobject]@{SelectedItemIds=@($script:testItemId);Receipt=[pscustomobject]@{Decision='RestoreNow';AcceptedUnpreparedItemIds=@()};ReceiptHash=('4'*64);Snapshot=[pscustomobject]@{}};$script:previewState=[pscustomobject]@{Items=@()}
        $preview=Get-WsmAssistiveRestorePreview -ManifestPath 'fixture' -ExpectedHash ('2'*64) -StateDirectory $root -AssistiveDecisionReceiptPath 'fixture' -AssistiveDecisionReceiptHash ('4'*64) -AssistiveTargetSnapshotPath 'fixture'
        Check (($preview.Rows|Where-Object ItemId -EQ $script:testItemId).Action -ceq 'CreateSingleFile' -and ($preview.Rows|Where-Object ItemId -EQ $script:testItemId).Status -ceq 'Ready') 'Single-file preview did not classify the exact absent target path as ready.'
        [void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($previewTarget));[IO.File]::WriteAllText($previewTarget,'operator-owned');$script:previewState.Items=@();$script:rejectAssistiveTopologyPath=$previewTarget;$topologyPreview=Get-WsmAssistiveRestorePreview -ManifestPath 'fixture' -ExpectedHash ('2'*64) -StateDirectory $root -AssistiveDecisionReceiptPath 'fixture' -AssistiveDecisionReceiptHash ('4'*64) -AssistiveTargetSnapshotPath 'fixture';$script:rejectAssistiveTopologyPath=''
        Check (($topologyPreview.Rows|Where-Object ItemId -EQ $script:testItemId).Status -eq 'Blocked' -and [IO.File]::ReadAllText($previewTarget) -ceq 'operator-owned') 'Restore preview did not reject unsupported existing target topology without changing its bytes.'
        $preview=Get-WsmAssistiveRestorePreview -ManifestPath 'fixture' -ExpectedHash ('2'*64) -StateDirectory $root -AssistiveDecisionReceiptPath 'fixture' -AssistiveDecisionReceiptHash ('4'*64) -AssistiveTargetSnapshotPath 'fixture'
        Check (($preview.Rows|Where-Object ItemId -EQ $script:testItemId).Status -ceq 'BlockedConflict' -and [IO.File]::ReadAllText($previewTarget) -ceq 'operator-owned') 'Single-file preview did not block an external file at the exact target.'
        [IO.File]::Delete($previewTarget);$script:testEntries=@((NewEntry '' 'single-file payload'));$item.MigrationSpec.TargetPath=$singleTarget;$item.MigrationSpec | Add-Member NoteProperty TransferChannel C -Force;[IO.File]::WriteAllText($singleTarget,'single-file payload');$item | Add-Member NoteProperty Name 'single file' -Force;$state.Items=@($singleResult);$script:previewPackage.Plan.Items=@($item);$script:previewState=$state
        $preview=Get-WsmAssistiveRestorePreview -ManifestPath 'fixture' -ExpectedHash ('2'*64) -StateDirectory $root -AssistiveDecisionReceiptPath 'fixture' -AssistiveDecisionReceiptHash ('4'*64) -AssistiveTargetSnapshotPath 'fixture'
        Check (($preview.Rows|Where-Object ItemId -EQ $script:testItemId).Action -ceq 'VerifyOwnedSingleFile' -and ($preview.Rows|Where-Object ItemId -EQ $script:testItemId).Status -ceq 'Ready') 'Single-file preview did not accept only the exact owned file with matching bytes and metadata.'

        # Final Assistive activation re-reads the exact durable receipt/snapshot
        # through the native decision seam and requires the whole sealed subset.
        $guardIdA=('a'*64);$guardIdB=('b'*64);$guardSourceId='sw-fixture';$guardIdentity=('9'*64);$guardManifestHash=('2'*64);$guardPlanHash=('3'*64)
        $guardSnapshot=[pscustomobject]@{CreatedUtc=[DateTime]::UtcNow.ToString('o');Source=[pscustomobject]@{Fingerprint=$guardIdentity};SoftwareCatalog=$softwareCatalog}
        $guardSnapshotPath=Join-Path $root 'cutover-target-snapshot.json';Write-WsmJson $guardSnapshotPath $guardSnapshot;$guardSnapshotHash=(Get-FileHash -LiteralPath $guardSnapshotPath -Algorithm SHA256).Hash.ToLowerInvariant()
        $guardComparison=[pscustomobject][ordered]@{Revision=7;SourceSnapshotHash=('1'*64);TargetSnapshotHash=$guardSnapshotHash;SelectionRevision=3;Rows=@([pscustomobject][ordered]@{SoftwareId=$guardSourceId;SourceVersion='1.2.3';ChosenVersion='1.2.3';ObservedTargetVersion='1.2.3';TargetSoftwareId=$guardSourceId;Status='ChosenVersionObserved'})}
        $guardPlan=[pscustomobject]@{Kind='MigrationPlan';SchemaVersion=3;PairId='pair-fixture';Assistive=[pscustomobject]@{SourceSnapshotHash=('1'*64);ApprovedItemIds=@($guardIdA,$guardIdB)};Items=@([pscustomobject]@{ItemId=$guardIdA;Decision='Include';MigrationSpec=[pscustomobject]@{Adapter='ManualWorkflow'}},[pscustomobject]@{ItemId=$guardIdB;Decision='Include';MigrationSpec=[pscustomobject]@{Adapter='ManualWorkflow'}})}
        $guardPackage=[pscustomobject]@{SHA256=$guardManifestHash;PlanHash=$guardPlanHash;Plan=$guardPlan;Manifest=[pscustomobject]@{PairId='pair-fixture';PlanHash=$guardPlanHash;Generation=9;Final=$true;Target=[pscustomobject]@{Fingerprint=$guardIdentity}}}
        $guardReceipt=[pscustomobject][ordered]@{SchemaVersion=1;Kind='AssistiveTargetDecisionReceipt';ReceiptId='fixture';PairId='pair-fixture';PlanHash=$guardPlanHash;ManifestHash=$guardManifestHash;Generation=9;TargetSnapshotHash=$guardSnapshotHash;ComparisonRevision=7;SelectionRevision=3;Decision='RestoreNow';Owner='Fixture owner';Reason='Exercise full approved set cutover guard';SelectedItemIds=@($guardIdA,$guardIdB);AcceptedUnpreparedItemIds=@();CreatedUtc=[DateTime]::UtcNow.ToString('o');Comparison=$guardComparison;ComparisonHash=(Get-WsmHashText ($guardComparison|ConvertTo-Json -Depth 100 -Compress));SHA256=('4'*64)}
        $guardBody=[ordered]@{};foreach($property in $guardReceipt.PSObject.Properties){if($property.Name -cne 'SHA256'){$guardBody[$property.Name]=$property.Value}};$guardReceipt.SHA256=Get-WsmHashText ($guardBody|ConvertTo-Json -Depth 20 -Compress)
        $guardReceiptPath=Join-Path $root 'cutover-decision-receipt.json';Write-WsmJson $guardReceiptPath $guardReceipt;$guardReceiptHash=(Get-FileHash -LiteralPath $guardReceiptPath -Algorithm SHA256).Hash.ToLowerInvariant()
        $script:currentSoftwareFixture=$softwareCatalog
        function Get-WsmAssistiveRestoreDecision($Package,[string]$ManifestHash,[string]$ReceiptPath,[string]$ReceiptHash,[string]$SnapshotPath){& $script:nativeAssistiveRestoreDecision $Package $ManifestHash $ReceiptPath $ReceiptHash $SnapshotPath}
        $guardAttempt=[pscustomobject]@{ManifestHash=$guardManifestHash;Generation=9;DecisionReceiptPath=$guardReceiptPath;DecisionReceiptHash=$guardReceiptHash;TargetSnapshotPath=$guardSnapshotPath;TargetSnapshotHash=$guardSnapshotHash;SelectedItemIds=@($guardIdA,$guardIdB)}
        $script:previewState=[pscustomobject]@{ManifestHash=$guardManifestHash;Generation=9;PendingOperations=@();Items=@();RestoreAttempt=$guardAttempt}
        Assert-WsmAssistiveCutoverActivationIntent $guardPackage $root
        Check $true 'A fresh receipt selecting the complete sealed approved set did not pass cutover intent validation.'
        $guardReceipt.SelectedItemIds=@($guardIdA);$guardBody=[ordered]@{};foreach($property in $guardReceipt.PSObject.Properties){if($property.Name -cne 'SHA256'){$guardBody[$property.Name]=$property.Value}};$guardReceipt.SHA256=Get-WsmHashText ($guardBody|ConvertTo-Json -Depth 20 -Compress);Write-WsmJson $guardReceiptPath $guardReceipt;$guardReceiptHash=(Get-FileHash -LiteralPath $guardReceiptPath -Algorithm SHA256).Hash.ToLowerInvariant();$guardAttempt.DecisionReceiptHash=$guardReceiptHash;$guardAttempt.SelectedItemIds=@($guardIdA)
        $subsetRejected=$false;try{Assert-WsmAssistiveCutoverActivationIntent $guardPackage $root|Out-Null}catch{$subsetRejected=$true}
        Check $subsetRejected 'Cutover activation accepted an updated receipt that deselected a previously staged sealed item.'
        $guardAttempt.DecisionReceiptPath='';$missingReceiptPathRejected=$false;try{Assert-WsmAssistiveCutoverActivationIntent $guardPackage $root|Out-Null}catch{$missingReceiptPathRejected=$true}
        Check $missingReceiptPathRejected 'Schema 3 cutover bypassed current receipt/snapshot validation when durable receipt references were missing.'
        $guardAttempt.DecisionReceiptPath=$guardReceiptPath;$guardAttempt.DecisionReceiptHash=('f'*64);$staleReceiptRejected=$false;try{Assert-WsmAssistiveCutoverActivationIntent $guardPackage $root|Out-Null}catch{$staleReceiptRejected=$true}
        Check $staleReceiptRejected 'Schema 3 cutover accepted a stale durable decision receipt hash.'
        $script:previewState=[pscustomobject]@{Items=@()}

        $repairRoot=Join-Path $root 'repair';[void][IO.Directory]::CreateDirectory($repairRoot);$repairTarget=Join-Path $repairRoot 'worker.bin';$repairStaging=$repairTarget+'.wsm-'+[Guid]::NewGuid().ToString('N')+'.tmp';$repairBackup=$repairTarget+'.wsm-assistive-backup-'+$script:testItemId.Substring(0,12)+'-'+[Guid]::NewGuid().ToString('N')
        [IO.File]::WriteAllText($repairBackup,'prior bytes');[IO.File]::WriteAllText($repairStaging,'approved bytes');$newHash=(Get-FileHash -LiteralPath $repairStaging -Algorithm SHA256).Hash.ToLowerInvariant();$oldHash=(Get-FileHash -LiteralPath $repairBackup -Algorithm SHA256).Hash.ToLowerInvariant()
        $repairItem=[pscustomobject]@{ItemId=$script:testItemId;Name='preview single';Decision='Include';MigrationSpec=[pscustomobject]@{Adapter='FileScope';TargetPath=$repairRoot}}
        $repairMetadata=[pscustomobject]@{MetadataMode='DaclOwner';Sddl='';Attributes=0;CreationUtc=$script:fixtureUtc;LastWriteUtc=$script:fixtureUtc};$repairOp=[pscustomobject]@{ItemId=$script:testItemId;Phase='AssistiveFileReplace';ManifestHash=('d'*64);Generation=2;RelativePath='worker.bin';Target=$repairTarget;Staging=$repairStaging;Backup=$repairBackup;PreviousHash=$oldHash;ExpectedHash=$newHash;ExpectedMetadata=$repairMetadata;WasOwned=$true;PriorOwner=[pscustomobject]@{MetadataHash=(Get-WsmAssistiveMetadataHash $repairMetadata)}}
        $repairPackage=[pscustomobject]@{SHA256=('d'*64);Manifest=[pscustomobject]@{Generation=2}}
        $repairPaths=[pscustomobject]@{Root=$root;State=$null;Journal=$null};$repairState=[pscustomobject]@{Items=@();PendingOperations=@($repairOp)}
        Complete-WsmAssistiveOperationRepair $repairItem $repairOp $repairPackage $repairPaths $repairState | Out-Null
        Check ([IO.File]::ReadAllText($repairTarget) -ceq 'approved bytes' -and [IO.File]::ReadAllText($repairBackup) -ceq 'prior bytes') 'Assistive journal repair did not finish an exact interrupted prior-file replacement.'
        Check (@($repairState.PendingOperations).Count -eq 0 -and $repairState.Items[0].Status -eq 'Partial' -and $repairState.Items[0].AppliedManifestHash -eq '') 'Per-file repair incorrectly marked a partial scope fully applied or left intent ambiguous.'
        $singleRepairRoot=Join-Path $root 'single-repair';[void][IO.Directory]::CreateDirectory($singleRepairRoot);$singleRepairTarget=Join-Path $singleRepairRoot 'exact.ini';$singleRepairStaging=$singleRepairTarget+'.wsm-'+[Guid]::NewGuid().ToString('N')+'.tmp';$singleRepairBackup=$singleRepairTarget+'.wsm-assistive-backup-'+$script:testItemId.Substring(0,12)+'-'+[Guid]::NewGuid().ToString('N');[IO.File]::WriteAllText($singleRepairBackup,'prior single bytes');[IO.File]::WriteAllText($singleRepairStaging,'approved single bytes');$singleRepairHash=(Get-FileHash -LiteralPath $singleRepairStaging -Algorithm SHA256).Hash.ToLowerInvariant();$singleOldHash=(Get-FileHash -LiteralPath $singleRepairBackup -Algorithm SHA256).Hash.ToLowerInvariant();$singleMetadata=[pscustomobject]@{MetadataMode='DaclOwner';Sddl='';Attributes=0;CreationUtc=$script:fixtureUtc;LastWriteUtc=$script:fixtureUtc};$singleRepairOp=[pscustomobject]@{ItemId=$script:testItemId;Phase='AssistiveFileReplace';ManifestHash=('d'*64);Generation=3;RelativePath='';Target=$singleRepairTarget;Staging=$singleRepairStaging;Backup=$singleRepairBackup;PreviousHash=$singleOldHash;ExpectedHash=$singleRepairHash;ExpectedMetadata=$singleMetadata;WasOwned=$true;PriorOwner=[pscustomobject]@{MetadataHash=(Get-WsmAssistiveMetadataHash $singleMetadata)}};$singleRepairItem=[pscustomobject]@{ItemId=$script:testItemId;Name='preview single';Decision='Include';MigrationSpec=[pscustomobject]@{Adapter='FileScope';TargetPath=$singleRepairTarget}};$singleRepairState=[pscustomobject]@{Items=@();PendingOperations=@($singleRepairOp)};Complete-WsmAssistiveOperationRepair $singleRepairItem $singleRepairOp $repairPackage $repairPaths $singleRepairState | Out-Null
        Check ([IO.File]::ReadAllText($singleRepairTarget) -ceq 'approved single bytes' -and [IO.File]::ReadAllText($singleRepairBackup) -ceq 'prior single bytes' -and $singleRepairState.Items[0].OwnedFiles[0].RelativePath -ceq '' -and $singleRepairState.Items[0].OwnedFiles[0].TargetPath -ceq $singleRepairTarget) 'Single-file recovery did not reconcile the exact empty-relative file target and rollback copy.'
        $deltaItem=[pscustomobject]@{ItemId=$script:testItemId;Name='preview single';Decision='Include';MigrationSpec=[pscustomobject]@{Adapter='FileScope';TargetPath=(Join-Path $root 'delta-target')}}
        $deltaBase=[pscustomobject]@{SHA256=('e'*64);Manifest=[pscustomobject]@{PairId='0123456789abcdef0123456789abcdef';Generation=4};Plan=[pscustomobject]@{SchemaVersion=3;Items=@($deltaItem)}}
        $deltaCurrent=[pscustomobject]@{SHA256=('f'*64);Manifest=[pscustomobject]@{PairId=$deltaBase.Manifest.PairId;Generation=5};Plan=[pscustomobject]@{SchemaVersion=3;Assistive=[pscustomobject]@{ApprovedItemIds=@($script:testItemId)};Items=@($deltaItem)}}
        $deltaBaseState=[pscustomobject]@{PairId=$deltaBase.Manifest.PairId;ManifestHash=$deltaBase.SHA256;Generation=4;Cutover=$null;PendingOperations=@();Items=@()}
        $deltaGate=Assert-WsmAssistiveDeltaBaseOwnership $deltaCurrent $deltaBase $deltaBaseState
        Check (-not $deltaGate.Ready -and @($deltaGate.MissingOwnedItemIds) -contains $script:testItemId) 'Delta fallback allowed reconstruction without exact durable FileScope ownership.'
        $deltaCommand=Get-Command Invoke-WsmArtifactDeltaRestore
        Check ($deltaCommand.Parameters.ContainsKey('AssistiveDecisionReceiptPath') -and $deltaCommand.Parameters.ContainsKey('FullPackageManifestPath') -and $deltaCommand.Parameters.ContainsKey('NonCResultPath')) 'Public delta restore does not expose the Assistive full-package fallback receipt/result seam.'
        Write-Host ('PASS: '+$script:checks+' Assistive file ownership, per-file conflict, typed IIS mapping and safe manual-gap checks.')
    } $root $helper
} finally {if([IO.Directory]::Exists($root)){Remove-Item -LiteralPath $root -Recurse -Force}}
