#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$contractPath=Join-Path $PSScriptRoot '..\src\GeneralHostContracts.ps1'
$transitionPath=Join-Path $PSScriptRoot '..\src\SettingTransitions.ps1'
$checks=0
& $module {
    param($path,$transitionSource)
    . $path
    . $transitionSource
    $fixtureReadOptions=@{};if((Get-Command ConvertFrom-Json).Parameters.ContainsKey('DateKind')){$fixtureReadOptions.DateKind='String'}
    function Assert-Check([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
    function Assert-Rejected([scriptblock]$Action,[string]$Message){$rejected=$false;try{& $Action | Out-Null}catch{$rejected=$true};Assert-Check $rejected $Message}

    # Legacy schema 1 remains readable; a new schema cannot omit its contract.
    Assert-WsmEnvelope ([pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='Catalog'}) Catalog
    Assert-Rejected {Assert-WsmEnvelope ([pscustomobject]@{SchemaVersion=2;ToolVersion='0.3.0';Kind='Catalog'}) Catalog} 'Schema 2 catalog without GeneralHost contract was accepted.'

    $hostId=[Guid]::NewGuid().ToString();$pairId=[Guid]::NewGuid().ToString();$source=[pscustomobject]@{HostId=$hostId;Fingerprint=('a'*64);Name='fixture-source';OS='Windows Server';Version='2025'}
    $item=New-WsmItem $hostId Services Service 'Fixture consumer' 'fixture-consumer' @{PathName='C:\fixture\consumer.exe'}
    $item | Add-Member NoteProperty Present $true;$item | Add-Member NoteProperty Decision Include;$item | Add-Member NoteProperty Owner 'service-owner';$item | Add-Member NoteProperty Reason 'Reviewed service';$item | Add-Member NoteProperty Evidence 'change-record:svc-1';$item | Add-Member NoteProperty GeneralHostOverride ([pscustomobject]@{Disposition='Migrate';Owner='service-owner';Reason='Reviewed service';Evidence='change-record:svc-1';SourceHash=('b'*64);Utc=(Get-WsmUtc)})
    $other=New-WsmItem $hostId Services Service 'Unrelated service' 'fixture-other' @{PathName='C:\fixture\other.exe'}
    $other | Add-Member NoteProperty Present $true;$other | Add-Member NoteProperty Decision Exclude;$other | Add-Member NoteProperty Owner 'other-owner';$other | Add-Member NoteProperty Reason 'Unrelated';$other | Add-Member NoteProperty Evidence 'change-record:other';$other | Add-Member NoteProperty GeneralHostOverride ([pscustomobject]@{Disposition='NotNeeded';Owner='other-owner';Reason='Unrelated';Evidence='change-record:other';SourceHash=('4'*64);Utc=(Get-WsmUtc)})
    $catalog=[pscustomobject][ordered]@{SchemaVersion=2;ToolVersion='0.3.0';Kind='Catalog';BatchId=[Guid]::NewGuid().ToString();PairId=$pairId;Source=$source;TargetName='fixture-target';InventoryRevision=7;DecisionRevision=4;InventoryHash=('c'*64);ImportedUtc=(Get-WsmUtc);Approval=$null;Items=@($item,$other);History=@();GeneralHost=$null}
    $sourceInventory=Get-WsmCatalogInventoryProjection $catalog
    $softwareEntry=[pscustomobject][ordered]@{SoftwareId=('sw-'+('d'*32));Name='Ordinary third-party application';Version='4.2';Publisher='Fixture Vendor';Architecture='x64';Scope='Machine';SID='';RegistryView='Registry64';Location='C:\Fixture\app';SourceKind='Registry';Evidence=[pscustomobject]@{RegistryPath='HKLM64\Uninstall\fixture';NaturalKey='fixture'};ObservedUtc=(Get-WsmUtc);CaptureStatus='Success';ItemIds=@();AccountContext='System'}
    $software=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='SoftwareCatalog';Source=[pscustomobject][ordered]@{HostId=$hostId;Fingerprint=$source.Fingerprint;Name=$source.Name;InventoryRevision=7;InventoryProjectionHash=(Get-WsmSoftwareInventoryProjectionHash $sourceInventory)};CaptureContext=[pscustomobject]@{CapturedUtc=(Get-WsmUtc);CaptureIdentity='fixture';AccountContext='System';CaptureHost='fixture';PowerShellVersion='5.1';RequestedPortableRoots=@()};Entries=@($softwareEntry);Coverage=@([pscustomobject]@{Probe='Fixture';Scope='Machine';SID='';View='Fixture';Status='Success';EvidenceKind='Fixture';Count=0;Budget=[pscustomobject]@{MaxEntries=10000};ErrorKind=$null;ObservedUtc=(Get-WsmUtc)});PreparationRequirements=@([pscustomobject]@{PreparationId=('prep-'+('d'*32));SoftwareId=$softwareEntry.SoftwareId;Status='NeedsOwnerReview';RequiredPhase='PreparationReady';EvidenceStatus='Success';ConsumerItemIds=@();Owner='';Reason='Fixture evidence only'});CatalogProjectionHash=('0'*64)}
    $software.CatalogProjectionHash=Get-WsmSoftwareCatalogProjectionHash $software
    $softwareId=$softwareEntry.SoftwareId
    $importInventory=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='Inventory';Source=$source;Revision=7;CreatedUtc=(Get-WsmUtc);Items=@($item,$other)};$software.Source.InventoryProjectionHash=Get-WsmSoftwareInventoryProjectionHash $importInventory;$software.CatalogProjectionHash=Get-WsmSoftwareCatalogProjectionHash $software;$importInventory | Add-Member NoteProperty SoftwareCatalog $software
    $tempBase=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());$importWorkspace=[IO.Path]::GetFullPath((Join-Path $tempBase ('wsm-gh-import-'+[Guid]::NewGuid().ToString('N'))))
    $inventoryPath='';$refreshPath='';try{[void](Initialize-WsmWorkspace $importWorkspace);$inventoryPath=Join-Path $tempBase ([Guid]::NewGuid().ToString('N')+'.inventory.json');Write-WsmJson $inventoryPath $importInventory | Out-Null;$inventoryHash=(Get-FileHash -LiteralPath $inventoryPath -Algorithm SHA256).Hash.ToLowerInvariant();$imported=Import-WsmInventory -Workspace $importWorkspace -Path $inventoryPath -ExpectedHash $inventoryHash -TargetName 'fixture-target';Assert-Check ($imported.PSObject.Properties['SoftwareCatalog'] -and $imported.SoftwareCatalog.CatalogProjectionHash -ceq $software.CatalogProjectionHash) 'Incoming SoftwareCatalog was not preserved on the imported catalog.';$refresh=$importInventory | ConvertTo-Json -Depth 40 | ConvertFrom-Json @fixtureReadOptions;$refresh.Revision=8;$refresh.PSObject.Properties.Remove('SoftwareCatalog');$refreshPath=Join-Path $tempBase ([Guid]::NewGuid().ToString('N')+'.inventory.json');Write-WsmJson $refreshPath $refresh | Out-Null;$refreshHash=(Get-FileHash -LiteralPath $refreshPath -Algorithm SHA256).Hash.ToLowerInvariant();$refreshed=Import-WsmInventory -Workspace $importWorkspace -Path $refreshPath -ExpectedHash $refreshHash;Assert-Check (-not $refreshed.PSObject.Properties['SoftwareCatalog']) 'Inventory refresh without a capture retained stale SoftwareCatalog data.'}finally{foreach($tempFile in @($inventoryPath,$refreshPath)){if($tempFile -and [IO.File]::Exists($tempFile)){Remove-Item -LiteralPath $tempFile -Force}};$resolvedTemp=[IO.Path]::GetFullPath($tempBase).TrimEnd('\')+'\';$resolvedWorkspace=[IO.Path]::GetFullPath($importWorkspace);if(-not $resolvedWorkspace.StartsWith($resolvedTemp,[StringComparison]::OrdinalIgnoreCase) -or $resolvedWorkspace -eq $resolvedTemp.TrimEnd('\')){throw 'Refusing to clean an import test directory outside the system temp root.'};if([IO.Directory]::Exists($resolvedWorkspace)){Remove-Item -LiteralPath $resolvedWorkspace -Recurse -Force}}
    $context=[pscustomobject][ordered]@{Provider='FixtureRuntime';Version='4.2';Architecture='x64';ConsumerItemIds=@($item.ItemId)}
    $requirement=[pscustomobject][ordered]@{RequirementId=('0'*64);Type='Preparation';ProviderSoftwareId=$softwareId;ProviderItemId='';ExternalId='';ConsumerItemIds=@($item.ItemId);Certainty='Required';RequiredPhase='StagedDependencyVerified';ExpectedVersion='4.2';Architecture='x64';Context=$context;Owner='runtime-owner';SourceProof=[pscustomobject]@{InventoryHash=$catalog.InventoryHash;RegistryPathHash=('e'*64);Status='NativeObserved'};Decision='Required';DecisionReason='Provider is needed by the service';DecisionEvidence='change-record:runtime-1'}
    $requirement.RequirementId=Get-WsmGeneralHostRequirementId $requirement
    $catalog.GeneralHost=[pscustomobject][ordered]@{SchemaVersion=1;ScopeMode='GeneralHost';SoftwareCatalog=$software;SoftwareCatalogHash=(Get-WsmHashText ($software | ConvertTo-Json -Depth 30 -Compress));SoftwareDecisions=@([pscustomobject]@{SoftwareId=$softwareId;SoftwareHash=(Get-WsmGeneralHostSoftwareFactsHash $softwareEntry);Disposition='Reinstall';Owner='app-owner';Reason='Prepare offline media';Evidence='media-record:app-1';SourceHash=('f'*64)});Requirements=@($requirement);OrphanedRequirements=@();EvidenceReceipts=@();UpdatedUtc=(Get-WsmUtc)}
    Assert-WsmGeneralHostContract $catalog | Out-Null
    $prepContext=[pscustomobject]@{Provider='FixtureRuntime';Version='4.2';Architecture='x64';ConsumerItemIds=@($item.ItemId);PreparationEvidence=[pscustomobject]@{MediaReference='media-record:app';MediaSHA256=('6'*64);VerificationMethod='OwnerVerified';SignatureEvidence='media-review:app';VendorOSSupportReference='vendor-support:2025';VendorSupportCheckedUtc=[DateTimeOffset]::UtcNow.AddMinutes(-1).ToString('o');LicenseReference='license:app';InstallOrder=1;IsolationEvidenceSHA256=('7'*64);RestartStatus='CompletedAndVerified';SideEffectsReference='isolation:app'}}
    $prepRequirement=$requirement | ConvertTo-Json -Depth 30 | ConvertFrom-Json @fixtureReadOptions;$prepRequirement.RequiredPhase='PreparationReady';$prepRequirement.Context=$prepContext;$prepRequirement.RequirementId=Get-WsmGeneralHostRequirementId $prepRequirement
    Assert-Check (@(Get-WsmGeneralHostIssues $catalog PreparationReady ('9'*64) | Where-Object Issue -Like '*separate PreparationReady*').Count -eq 1) 'Staged configuration proof substituted for software preparation.'
    $catalog.GeneralHost.Requirements=@($prepRequirement,$requirement)
    $prepReceipt=[pscustomobject]@{SchemaVersion=1;ReceiptId=('8'*64);PairId=$pairId;SourceFingerprint=$source.Fingerprint;TargetFingerprint=('9'*64);InventoryHash=$catalog.InventoryHash;ToolFingerprint=(Get-WsmToolFingerprint);Context=$prepContext;RequirementIds=@($prepRequirement.RequirementId);RequirementProjectionHash=(Get-WsmGeneralHostProjectionHash $catalog @($item.ItemId) @($prepRequirement.RequirementId) PreparationReady);Phase='PreparationReady';EvidenceKind='OwnerReadback';EvidencePathHash=('6'*64);Owner='runtime-owner';ObservedUtc=[DateTime]::UtcNow.AddMinutes(-1).ToString('o');ExpiresUtc=[DateTime]::UtcNow.AddHours(2).ToString('o')}
    $catalog.GeneralHost.EvidenceReceipts=@($prepReceipt)
    Assert-Rejected {Assert-WsmPreparationEvidence ([pscustomobject]@{RestartStatus='NotTested'})} 'Unverified preparation checklist was accepted.'
    $missingSoftware=$catalog | ConvertTo-Json -Depth 40 | ConvertFrom-Json @fixtureReadOptions;$missingSoftware.GeneralHost.SoftwareCatalog=$null;$missingSoftware.GeneralHost.SoftwareCatalogHash='';$missingIssues=@(Get-WsmGeneralHostIssues $missingSoftware ReviewComplete);Assert-Check (@($missingIssues | Where-Object Issue -Like '*SoftwareCatalog*').Count -eq 1) 'GeneralHost review without a source SoftwareCatalog was not blocked.'
    $contextOrder=[pscustomobject][ordered]@{ConsumerItemIds=@($item.ItemId);Architecture='x64';Version='4.2';Provider='FixtureRuntime'};$sameIdentity=$requirement | ConvertTo-Json -Depth 20 | ConvertFrom-Json @fixtureReadOptions;$sameIdentity.Context=$contextOrder;Assert-Check ((Get-WsmGeneralHostRequirementId $sameIdentity) -ceq $requirement.RequirementId) 'Requirement identity changed with equivalent Context property ordering.'
    $item | Add-Member NoteProperty Classification ([pscustomobject]@{Disposition='SpecialProduct'}) -Force;$specialIssues=@(Get-WsmGeneralHostIssues $catalog ReviewComplete);Assert-Check (@($specialIssues | Where-Object Issue -Like '*Special server products*').Count -eq 1) 'Special product automatic Include was not blocked by GeneralHost review.'
    $item.Classification.Disposition='Preparation';$preparationIssues=@(Get-WsmGeneralHostIssues $catalog ReviewComplete);Assert-Check (@($preparationIssues | Where-Object Issue -Like '*preparation cannot be installed*').Count -eq 1) 'Runtime or preparation automatic Include was not blocked by GeneralHost review.'
    $item.PSObject.Properties.Remove('Classification')
    $preRestoreIssues=@(Get-WsmGeneralHostIssues $catalog PreparationReady ('9'*64));if($preRestoreIssues.Count){Write-Output ($preRestoreIssues | ForEach-Object {$_ | ConvertTo-Json -Depth 10 -Compress})};Assert-Check ($preRestoreIssues.Count -eq 0) 'Staged TNS/runtime dependency was demanded before restore.'
    $missing=@(Get-WsmGeneralHostIssues $catalog StagedDependencyVerified ('9'*64))
    Assert-Check (@($missing | Where-Object RequirementId -EQ $requirement.RequirementId).Count -eq 1) 'Required staged dependency without proof was accepted.'

    $receipt=[pscustomobject][ordered]@{SchemaVersion=1;ReceiptId=('1'*64);PairId=$pairId;SourceFingerprint=$source.Fingerprint;TargetFingerprint=('9'*64);InventoryHash=$catalog.InventoryHash;ToolFingerprint=(Get-WsmToolFingerprint);Context=$context;RequirementIds=@($requirement.RequirementId);RequirementProjectionHash=(Get-WsmGeneralHostProjectionHash $catalog @($item.ItemId) @($requirement.RequirementId) StagedDependencyVerified);Phase='StagedDependencyVerified';EvidenceKind='NativeReadback';EvidencePathHash=('2'*64);Owner='runtime-owner';ObservedUtc=[DateTime]::UtcNow.ToString('o');ExpiresUtc=[DateTime]::UtcNow.AddHours(2).ToString('o')}
    $catalog.GeneralHost.EvidenceReceipts=@($prepReceipt,$receipt)
    $acceptedIssues=@(Get-WsmGeneralHostIssues $catalog StagedDependencyVerified ('9'*64) '' '' @());if($acceptedIssues.Count){Write-Output ($acceptedIssues | ForEach-Object {$_ | ConvertTo-Json -Depth 10 -Compress})};Assert-Check ($acceptedIssues.Count -eq 0) 'Correct staged target evidence was not accepted.'
    $cutoverCatalog=$catalog | ConvertTo-Json -Depth 40 | ConvertFrom-Json @fixtureReadOptions;$external=[pscustomobject][ordered]@{RequirementId=('0'*64);Type='ExternalDependency';ProviderSoftwareId='';ProviderItemId='';ExternalId='enterprise-db-fixture';ConsumerItemIds=@($item.ItemId);Certainty='Required';RequiredPhase='CutoverReady';ExpectedVersion='19c';Architecture='x64';Context=[pscustomobject][ordered]@{ServiceAccount='DOMAIN\fixture-svc'};Owner='database-owner';SourceProof=[pscustomobject]@{InventoryHash=$catalog.InventoryHash;EvidenceHash=('5'*64);Status='OwnerObserved'};Decision='Required';DecisionReason='Service requires the database';DecisionEvidence='dependency-register:db-1'};$external.RequirementId=Get-WsmGeneralHostRequirementId $external;$cutoverCatalog.GeneralHost.Requirements=@($prepRequirement,$requirement,$external);$cutoverCatalog.GeneralHost.EvidenceReceipts=@($prepReceipt,$receipt);$cutoverSoftwareProjection=Get-WsmSoftwareCatalogProjectionHash $cutoverCatalog.GeneralHost.SoftwareCatalog;Assert-Check (@(Get-WsmGeneralHostIssues $cutoverCatalog CutoverReady ('9'*64)).Count -eq 1) 'CutoverReady proof was not required after the staged dependency receipt.'
    # Reviewed settings whose dependency deadline is CutoverReady are still applied and journaled in isolated staging.
    $beforeSetting=[pscustomobject][ordered]@{Exists=$true;Value='C:\Oracle\source-tns';ValueKind='String'};$afterSetting=[pscustomobject][ordered]@{Exists=$true;Value='C:\Oracle\isolated-tns';ValueKind='String'};$transition=New-WsmSettingTransition -Adapter MachineEnvironment -Action UpdateReviewed -Name TNS_ADMIN -Before $beforeSetting -After $afterSetting -Owner 'database-owner' -Evidence 'change-record:tns-2' -OwnerReviewHash ('8'*64) -RequiredPhase CutoverReady;$fakeTarget=('9'*64);$script:fakeGeneralHostSetting=$beforeSetting;$script:fakeGeneralHostWrites=0
    function Get-WsmSettingNativeSnapshot($Transition){$script:fakeGeneralHostSetting}
    function Set-WsmSettingNativeState($Transition,$State){$script:fakeGeneralHostSetting=$State;$script:fakeGeneralHostWrites++}
    function Add-WsmJournal($Paths,$State,[string]$Action,[string]$ItemId,$Detail){$State.JournalHash=Get-WsmHashText ($State.JournalHash+$Action+$ItemId);$script:settingJournalEvents+=@($Action)}
    $script:settingJournalEvents=@();$settingItem=[pscustomobject]@{ItemId='transition-item';MigrationSpec=[pscustomobject]@{SettingTransition=$transition}};$settingPackage=[pscustomobject]@{SHA256=('a'*64);Manifest=[pscustomobject]@{Target=[pscustomobject]@{Fingerprint=$fakeTarget}}};$settingState=[pscustomobject]@{Items=@();PendingOperations=@();JournalHash=('b'*64)};$settingPaths=[pscustomobject]@{Root='mock-root'}
    $stagedReceipt=Invoke-WsmSettingTransitionForPhase $settingItem $settingPackage $settingPaths $settingState StagedDependencyVerified;Assert-Check ($stagedReceipt.UpdatedByTool -and -not $stagedReceipt.CreatedByTool -and $script:fakeGeneralHostWrites -eq 1) 'CutoverReady transition did not apply with correct existing-setting ownership during isolated staging.'
    $settingRecord=[pscustomobject]@{ItemId=$settingItem.ItemId;Status='Succeeded';CreatedByTool=$false;UpdatedByTool=$true;SettingTransitionIntent=$stagedReceipt.Intent;SettingTransitionReceipt=$stagedReceipt};$settingState.Items=@($settingRecord);$null=Invoke-WsmSettingTransitionForPhase $settingItem $settingPackage $settingPaths $settingState CutoverReady;Assert-Check ($script:fakeGeneralHostWrites -eq 1 -and (Test-WsmSettingTransitionRecordOwnership $settingRecord $settingItem.MigrationSpec $fakeTarget)) 'CutoverReady did not reuse the exact staged receipt without a second write or changed ownership.';Assert-Check ((Get-WsmSoftwareCatalogProjectionHash $cutoverCatalog.GeneralHost.SoftwareCatalog) -ceq $cutoverSoftwareProjection) 'Setting transition fixture altered software projection.'
    $externalReceipt=[pscustomobject][ordered]@{SchemaVersion=1;ReceiptId=('6'*64);PairId=$pairId;SourceFingerprint=$source.Fingerprint;TargetFingerprint=('9'*64);InventoryHash=$cutoverCatalog.InventoryHash;ToolFingerprint=(Get-WsmToolFingerprint);Context=$external.Context;RequirementIds=@($external.RequirementId);RequirementProjectionHash=(Get-WsmGeneralHostProjectionHash $cutoverCatalog @($item.ItemId) @($external.RequirementId) CutoverReady);Phase='CutoverReady';EvidenceKind='ExternalOwner';EvidencePathHash=('7'*64);Owner='database-owner';ObservedUtc=[DateTime]::UtcNow.ToString('o');ExpiresUtc=[DateTime]::UtcNow.AddHours(2).ToString('o')};$cutoverCatalog.GeneralHost.EvidenceReceipts=@($cutoverCatalog.GeneralHost.EvidenceReceipts)+@($externalReceipt);try{Assert-WsmGeneralHostSoftwareCatalog $cutoverCatalog.GeneralHost.SoftwareCatalog $cutoverCatalog | Out-Null}catch{Write-Output ('Software validation detail: '+$_.Exception.Message)};$afterProofIssues=@(Get-WsmGeneralHostIssues $cutoverCatalog CutoverReady ('9'*64));if($afterProofIssues.Count){Write-Output ($afterProofIssues | ForEach-Object {$_ | ConvertTo-Json -Depth 10 -Compress})};Assert-Check ($afterProofIssues.Count -eq 0) 'Valid staged setting and business proof did not close the CutoverReady gate.'
    Assert-Check (@(Get-WsmGeneralHostIssues $catalog StagedDependencyVerified ('8'*64)).Count -gt 0) 'Evidence for another target was accepted.'
    $expired=$receipt | ConvertTo-Json -Depth 20 | ConvertFrom-Json @fixtureReadOptions;$expired.ExpiresUtc=[DateTime]::UtcNow.AddMinutes(-1).ToString('o');Assert-Rejected {Assert-WsmGeneralHostReceipt $expired $catalog -TargetFingerprint ('9'*64)} 'Expired evidence was accepted.'
    $wrongTool=$receipt | ConvertTo-Json -Depth 20 | ConvertFrom-Json @fixtureReadOptions;$wrongTool.ToolFingerprint='3'*64;Assert-Rejected {Assert-WsmGeneralHostReceipt $wrongTool $catalog -TargetFingerprint ('9'*64)} 'Evidence from another tool build was accepted.'
    $wrongSource=$receipt | ConvertTo-Json -Depth 20 | ConvertFrom-Json @fixtureReadOptions;$wrongSource.InventoryHash='4'*64;Assert-Rejected {Assert-WsmGeneralHostReceipt $wrongSource $catalog -TargetFingerprint ('9'*64)} 'Evidence from another source inventory was accepted.'
    $wrongRequirement=$receipt | ConvertTo-Json -Depth 20 | ConvertFrom-Json @fixtureReadOptions;$wrongRequirement.RequirementIds=@(('5'*64));Assert-Rejected {Assert-WsmGeneralHostReceipt $wrongRequirement $catalog -TargetFingerprint ('9'*64)} 'Evidence for an unknown requirement was accepted.'
    $wrongContext=$receipt | ConvertTo-Json -Depth 20 | ConvertFrom-Json @fixtureReadOptions;$wrongContext.Context.Version='wrong';$catalog.GeneralHost.EvidenceReceipts=@($wrongContext);Assert-Check (@(Get-WsmGeneralHostIssues $catalog StagedDependencyVerified ('9'*64) '' '' @()).Count -gt 0) 'Fixture context mutation did not stale its proof.';$catalog.GeneralHost.EvidenceReceipts=@($prepReceipt,$receipt)

    # A different consumer or software row must not invalidate this consumer's evidence.
    $before=Get-WsmGeneralHostProjectionHash $catalog @($item.ItemId) @($requirement.RequirementId) StagedDependencyVerified
    $other.Decision='Pending';$other.Reason='Updated unrelated review';$after=Get-WsmGeneralHostProjectionHash $catalog @($item.ItemId) @($requirement.RequirementId) StagedDependencyVerified
    Assert-Check ($before -ceq $after) 'Unrelated consumer decision changed the scoped requirement projection.'
    Assert-Check (@(Get-WsmGeneralHostIssues $catalog StagedDependencyVerified ('9'*64)).Count -eq 0) 'Unrelated consumer decision invalidated evidence for another consumer.'
    $second=[pscustomobject]@{};foreach($p in $softwareEntry.PSObject.Properties){$second | Add-Member NoteProperty $p.Name $p.Value};$second.SoftwareId='sw-'+('7'*32);$second.Name='Unrelated app';$second.Location='C:\Fixture\other-app';$second.ObservedUtc=(Get-WsmUtc)
    $software.Entries=@($softwareEntry,$second);$software.PreparationRequirements+=@([pscustomobject]@{PreparationId=('prep-'+('7'*32));SoftwareId=$second.SoftwareId;Status='NeedsOwnerReview';RequiredPhase='PreparationReady';EvidenceStatus='Success';ConsumerItemIds=@();Owner='';Reason='Fixture evidence only'});$software.CatalogProjectionHash=Get-WsmSoftwareCatalogProjectionHash $software;$catalog.GeneralHost.SoftwareCatalogHash=Get-WsmHashText ($software | ConvertTo-Json -Depth 30 -Compress)
    $afterSoftware=Get-WsmGeneralHostProjectionHash $catalog @($item.ItemId) @($requirement.RequirementId) StagedDependencyVerified
    Assert-Check ($before -ceq $afterSoftware) 'Unrelated software row changed the scoped requirement projection.'
    Assert-Check (@(Get-WsmGeneralHostIssues $catalog StagedDependencyVerified ('9'*64)).Count -eq 0) 'Unrelated software row invalidated provider evidence.'
    $softwareEntry.Version='4.3';$software.CatalogProjectionHash=Get-WsmSoftwareCatalogProjectionHash $software;$catalog.GeneralHost.SoftwareCatalogHash=Get-WsmHashText ($software | ConvertTo-Json -Depth 30 -Compress);$providerChanged=Get-WsmGeneralHostProjectionHash $catalog @($item.ItemId) @($requirement.RequirementId) StagedDependencyVerified
    Assert-Check ($before -cne $providerChanged) 'Changed required provider facts did not stale its requirement projection.'
    Assert-Check (@(Get-WsmGeneralHostIssues $catalog StagedDependencyVerified ('9'*64) | Where-Object Issue -Like '*stale*').Count -eq 2) 'Changed required provider facts did not invalidate its receipt.'

    # Required NotNeeded is still a gate; CutoverReady dependencies are not demanded at staging.
    $requirement.Decision='NotNeeded';$requirement.DecisionReason='Owner says no';$requirement.DecisionEvidence='review:required-not-needed';$issues=@(Get-WsmGeneralHostIssues $catalog StagedDependencyVerified ('9'*64));Assert-Check (@($issues | Where-Object Issue -Like '*NotNeeded*').Count -eq 1) 'Required dependency marked NotNeeded satisfied a consumer.'
    $external=[pscustomobject][ordered]@{RequirementId=('0'*64);Type='ExternalDependency';ProviderSoftwareId='';ProviderItemId='';ExternalId='enterprise-db-fixture';ConsumerItemIds=@($item.ItemId);Certainty='Required';RequiredPhase='CutoverReady';ExpectedVersion='19c';Architecture='x64';Context=[pscustomobject]@{ServiceAccount='DOMAIN\fixture-svc'};Owner='database-owner';SourceProof=[pscustomobject]@{InventoryHash=$catalog.InventoryHash;EvidenceHash=('5'*64);Status='OwnerObserved'};Decision='Required';DecisionReason='Service requires the database';DecisionEvidence='dependency-register:db-1'};$external.RequirementId=Get-WsmGeneralHostRequirementId $external;$catalog.GeneralHost.Requirements=@($prepRequirement,$requirement,$external)
    Assert-Check (@(Get-WsmGeneralHostIssues $catalog StagedDependencyVerified ('9'*64) '' '' @() | Where-Object RequirementId -EQ $external.RequirementId).Count -eq 0) 'CutoverReady business proof was demanded before staging completion.'
    Assert-Check (@(Get-WsmGeneralHostIssues $catalog CutoverReady ('9'*64) '' '' @() | Where-Object RequirementId -EQ $external.RequirementId).Count -eq 1) 'External business proof was not required before cutover.'
    # A fresh capture invalidates source proof, while unchanged software review is retained.
    $refreshRoot=Join-Path $tempBase ('wsm-gh-refresh-'+[Guid]::NewGuid().ToString('N'))
    try {
        [void](Initialize-WsmWorkspace $refreshRoot)
        $incoming=Get-WsmCatalogInventoryProjection $catalog
        $capture=$software | ConvertTo-Json -Depth 40 | ConvertFrom-Json @fixtureReadOptions
        $capture.Source.InventoryProjectionHash=Get-WsmSoftwareInventoryProjectionHash $incoming
        $capture.CatalogProjectionHash=Get-WsmSoftwareCatalogProjectionHash $capture
        $incoming | Add-Member NoteProperty SoftwareCatalog $capture
        $firstPath=Join-Path $refreshRoot 'initial.json';Write-WsmJson $firstPath $incoming
        $initial=Import-WsmInventory $refreshRoot $firstPath (Get-FileHash $firstPath).Hash 'fixture-target'
        $initial.SchemaVersion=2
        $general=$catalog.GeneralHost | ConvertTo-Json -Depth 40 | ConvertFrom-Json @fixtureReadOptions
        foreach($dependency in $general.Requirements){$dependency.SourceProof.InventoryHash=$initial.InventoryHash}
        foreach($priorReceipt in $general.EvidenceReceipts){$priorReceipt.PairId=$initial.PairId;$priorReceipt.InventoryHash=$initial.InventoryHash}
        $general.SoftwareCatalog=$capture;$general.SoftwareCatalogHash=Get-WsmHashText ($capture | ConvertTo-Json -Depth 30 -Compress)
        $general.SoftwareDecisions[0].SoftwareHash=Get-WsmGeneralHostSoftwareFactsHash $capture.Entries[0]
        $initial | Add-Member NoteProperty GeneralHost $general
        Write-WsmWorkspaceTransaction $refreshRoot $initial (Get-WsmFleet $refreshRoot)
        $reviewPath=Join-Path $refreshRoot 'requirements-review.json';Write-WsmJson $reviewPath ([pscustomobject]@{Requirements=@($general.Requirements)})
        $reviewHash=(Get-FileHash $reviewPath).Hash
        $review=Get-WsmGeneralHostRequirementPreview $refreshRoot $initial.PairId $reviewPath $reviewHash $initial.DecisionRevision
        Assert-Check ((Get-WsmGeneralHostPreviewHash $review Requirement) -ceq (Get-WsmHashText ($review | ConvertTo-Json -Depth 25 -Compress))) 'Public review hash differs from the apply contract.'
        $invalidReview=ConvertFrom-WsmJson ([IO.File]::ReadAllText($reviewPath));$invalidReview.Requirements[0].Context.PreparationEvidence.RestartStatus='NotTested';$invalidReview.Requirements[0].RequirementId=Get-WsmGeneralHostRequirementId $invalidReview.Requirements[0]
        $invalidPath=Join-Path $refreshRoot 'invalid-requirements.json';Write-WsmJson $invalidPath $invalidReview
        Assert-Rejected {Get-WsmGeneralHostRequirementPreview $refreshRoot $initial.PairId $invalidPath (Get-FileHash $invalidPath).Hash $initial.DecisionRevision} 'Preview accepted unverified restart evidence.'
        $incoming.Revision++
        $capture.Source.InventoryRevision=$incoming.Revision
        $capture.Source.InventoryProjectionHash=Get-WsmSoftwareInventoryProjectionHash $incoming
        $capture.CatalogProjectionHash=Get-WsmSoftwareCatalogProjectionHash $capture
        $nextPath=Join-Path $refreshRoot 'refresh.json';Write-WsmJson $nextPath $incoming
        $next=Import-WsmInventory $refreshRoot $nextPath (Get-FileHash $nextPath).Hash
        Assert-Check (@($next.GeneralHost.SoftwareDecisions).Count -eq 1) 'Unchanged software review was erased by source refresh.'
        Assert-Check (@($next.GeneralHost.Requirements).Count -eq 0 -and @($next.GeneralHost.OrphanedRequirements).Count -eq 3) 'Source refresh reused dependency proof for the prior inventory.'
        Assert-Check (@($next.GeneralHost.EvidenceReceipts).Count -eq 0) 'Source refresh reused prior target receipts.'
    } finally {
        $resolvedRefresh=[IO.Path]::GetFullPath($refreshRoot)
        if(-not $resolvedRefresh.StartsWith($tempBase.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Unsafe refresh fixture cleanup.'}
        if([IO.Directory]::Exists($resolvedRefresh)){Remove-Item -LiteralPath $resolvedRefresh -Recurse -Force}
    }
    Write-Output 'PASS: GeneralHost schema, phase gates, receipt bindings, scoped invalidation, source refresh, required NotNeeded, and staged transition before cutover proof.'
} $contractPath $transitionPath
