#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$formsPath=Join-Path $PSScriptRoot '..\src\AssistiveSettingsForms.ps1'
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-assistive-settings-forms-'+[Guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($root)
function Invoke-Form([string]$Name,$Arguments){& $module {param($Path,$Name,$Arguments) . $Path; & $Name @Arguments} $formsPath $Name $Arguments}
function Check([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message};$script:passed++}
function Reject([scriptblock]$Action,[string]$Message){$rejected=$false;try{& $Action | Out-Null}catch{$rejected=$true};Check $rejected $Message}
function SaveJson($Data,[string]$Path){[IO.File]::WriteAllText($Path,($Data|ConvertTo-Json -Depth 40),(New-Object Text.UTF8Encoding($false)));$Path}
$passed=0
try {
    $workspace=Join-Path $root 'manager';Initialize-WsmWorkspace $workspace | Out-Null
    $sourceHost=[Guid]::NewGuid().ToString();$consumer=New-WsmItem $sourceHost Services Service 'Form consumer' 'form-consumer' ([pscustomobject]@{PathName='C:\fixture\consumer.exe'}) @() Success
    $config=New-WsmItem $sourceHost System SystemConfiguration 'System settings' 'system-configuration' ([pscustomobject][ordered]@{TimeZone='Eastern Standard Time';UICulture='zh-TW';Environment=[ordered]@{PATH='C:\source-private\bin;C:\Windows\System32';NLS_LANG='AMERICAN_AMERICA.AL32UTF8'};ControlSource='Local'}) @() Success
    $consumer.Dependencies=@([pscustomobject]@{ItemId=$config.ItemId;Type='Mandatory';Evidence='fixture dependency';Confidence='Declared'})
    $sourcePath=Join-Path $root 'source.json';$sourceDoc=New-WsmInventory ([pscustomobject]@{HostId=$sourceHost;Fingerprint=('a'*64);Name='form-source';OS='Windows Server';Version='2025'}) 3 @($config,$consumer);SaveJson $sourceDoc $sourcePath | Out-Null;$sourceHash=(Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash.ToLowerInvariant()
    $catalog=Import-WsmInventory $workspace $sourcePath $sourceHash 'form-target';$catalog=Set-WsmGeneralHostMode $workspace $catalog.PairId $catalog.DecisionRevision
    $targetHost=[Guid]::NewGuid().ToString();$targetConfig=New-WsmItem $targetHost System SystemConfiguration 'System settings' 'system-configuration' ([pscustomobject][ordered]@{TimeZone='Pacific Standard Time';UICulture='en-US';Environment=[ordered]@{PATH='C:\target-private\bin;C:\Windows\System32';NLS_LANG='AMERICAN_AMERICA.AL32UTF8'};ControlSource='Local'}) @() Success
    $targetPath=Join-Path $root 'target.json';$targetDoc=New-WsmInventory ([pscustomobject]@{HostId=$targetHost;Fingerprint=('b'*64);Name='form-target';OS='Windows Server';Version='2025'}) 1 @($targetConfig);SaveJson $targetDoc $targetPath | Out-Null;$targetHash=(Get-FileHash -LiteralPath $targetPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $catalog=Get-WsmCatalog $workspace $catalog.PairId;$revision=[int]$catalog.DecisionRevision
    $previewPath=Join-Path (Join-Path (Join-Path $workspace 'assistive') 'forms') 'windows-preview.json';$previewResult=Invoke-Form Export-WsmAssistiveWindowsSettingsPreview @{Workspace=$workspace;PairId=$catalog.PairId;SourceInventoryPath=$sourcePath;SourceInventoryHash=$sourceHash;TargetInventoryPath=$targetPath;TargetInventoryHash=$targetHash;ReviewWindowsSettings=$false;OutputPath=$previewPath}
    $previewFile=Get-Content -LiteralPath $previewPath -Raw | ConvertFrom-Json;$previewHash=$previewResult.PreviewFileHash
    Check ($previewResult.Status -ceq 'Previewed' -and $previewResult.PreviewHash -ceq $previewFile.PreviewHash -and $previewResult.RowCount -eq @($previewResult.Rows).Count) 'Preview producer did not persist a full trusted preview and return semantic/file hashes separately.'
    Check (-not ((ConvertTo-Json -InputObject $previewResult.Rows -Depth 20 -Compress).Contains('C:\source-private\bin') -or (ConvertTo-Json -InputObject $previewResult.Rows -Depth 20 -Compress).Contains('C:\target-private\bin'))) 'Safe HTML preview rows leaked raw source or target values.'
    $preview=& $module {param($Path) Read-WsmTrustedJson $Path (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash} $previewPath
    $native=& $module {param($Preview) Get-WsmWindowsSettingsDecisionTemplate $Preview} $preview
    $decisions=@(foreach($row in $native.Decisions){[pscustomobject][ordered]@{SettingId=$row.SettingId;Action='KeepTarget';Owner='fixture owner';Reason='Preserve reviewed target';Evidence='change:form-fixture'}})
    $formArgs=@{Workspace=$workspace;PairId=$catalog.PairId;SourceInventoryPath=$sourcePath;SourceInventoryHash=$sourceHash;TargetInventoryPath=$targetPath;TargetInventoryHash=$targetHash;PreviewPath=$previewPath;PreviewHash=$previewHash;ExpectedRevision=$revision;Ack=$true;Decisions=$decisions}
    $result=Invoke-Form Submit-WsmAssistiveWindowsSettingsReview $formArgs
    Check ($result.Status -ceq 'Applied' -and $result.Applied -and $result.DecisionRevision -gt $revision -and $result.DecisionCount -eq $preview.Rows.Count) 'Typed Windows settings form did not commit through the core apply consumer.'
    Check ((Test-Path -LiteralPath $result.GeneratedDecisionsPath -PathType Leaf) -and $result.GeneratedDecisionsHash -ceq (Get-FileHash -LiteralPath $result.GeneratedDecisionsPath -Algorithm SHA256).Hash.ToLowerInvariant()) 'Form did not persist its generated, protected decision artifact with its actual hash.'
    $generated=Get-Content -LiteralPath $result.GeneratedDecisionsPath -Raw | ConvertFrom-Json
    Check (@($generated.Decisions | Where-Object {$_.PSObject.Properties['SourceValueHash'] -and $_.PSObject.Properties['TargetValueHash']}).Count -eq $preview.Rows.Count) 'Generated decisions did not receive server-derived source and target value hashes.'
    Check (-not (([IO.File]::ReadAllText($result.GeneratedDecisionsPath)).Contains('C:\source-private\bin') -or ([IO.File]::ReadAllText($result.GeneratedDecisionsPath)).Contains('C:\target-private\bin'))) 'Generated form artifact leaked raw source or target settings.'
    Check ($result.ReadinessProof -eq $false -and $result.AuthoritativeApproval -eq $false) 'Form result claimed readiness or approval authority.'

    $current=Get-WsmCatalog $workspace $catalog.PairId;$currentRevision=[int]$current.DecisionRevision;$catalogPath=& $module {param($Workspace,$PairId) Get-WsmCatalogPath $Workspace $PairId} $workspace $catalog.PairId;$beforeHash=(Get-FileHash -LiteralPath $catalogPath -Algorithm SHA256).Hash.ToLowerInvariant()
    Reject { Invoke-Form Submit-WsmAssistiveWindowsSettingsReview $formArgs } 'Stale revision or stale preview was accepted.'
    Check ((Get-FileHash -LiteralPath $catalogPath -Algorithm SHA256).Hash.ToLowerInvariant() -ceq $beforeHash) 'Rejected stale decision changed the catalog.'
    $freshPreviewPath=Join-Path (Join-Path (Join-Path $workspace 'assistive') 'forms') 'fresh-preview.json';$freshPreviewResult=Invoke-Form Export-WsmAssistiveWindowsSettingsPreview @{Workspace=$workspace;PairId=$catalog.PairId;SourceInventoryPath=$sourcePath;SourceInventoryHash=$sourceHash;TargetInventoryPath=$targetPath;TargetInventoryHash=$targetHash;ReviewWindowsSettings=$false;OutputPath=$freshPreviewPath};$freshPreviewHash=$freshPreviewResult.PreviewFileHash;$freshPreview=& $module {param($Path) Read-WsmTrustedJson $Path (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash} $freshPreviewPath;$freshArgs=$formArgs.Clone();$freshArgs.PreviewPath=$freshPreviewPath;$freshArgs.PreviewHash=$freshPreviewHash;$freshArgs.ExpectedRevision=$currentRevision
    $unknown=@($decisions);$unknown[0]=[pscustomobject][ordered]@{SettingId=('0'*64);Action='KeepTarget'};$badArgs=$freshArgs.Clone();$badArgs.Decisions=$unknown;Reject { Invoke-Form Submit-WsmAssistiveWindowsSettingsReview $badArgs } 'Unknown SettingId was accepted.'
    $unsupported=@($decisions);$unsupported[0]=[pscustomobject][ordered]@{SettingId=$decisions[0].SettingId;Action='ReviewedMigration'};$badArgs=$freshArgs.Clone();$badArgs.Decisions=$unsupported;Reject { Invoke-Form Submit-WsmAssistiveWindowsSettingsReview $badArgs } 'Unsupported setting action was accepted.'
    $extra=@($decisions);$extra[0]=[pscustomobject][ordered]@{SettingId=$decisions[0].SettingId;Action='KeepTarget';SourceValueHash=('c'*64)};$badArgs=$freshArgs.Clone();$badArgs.Decisions=$extra;Reject { Invoke-Form Submit-WsmAssistiveWindowsSettingsReview $badArgs } 'Caller-supplied value hashes or extra fields were accepted.'
    $missing=@($decisions | Select-Object -Skip 1);$badArgs=$freshArgs.Clone();$badArgs.Decisions=$missing;Reject { Invoke-Form Submit-WsmAssistiveWindowsSettingsReview $badArgs } 'Incomplete decision row set was accepted.'
    $dispositionCatalog=Get-WsmCatalog $workspace $catalog.PairId;$dispositionRevision=[int]$dispositionCatalog.DecisionRevision;$disposition=@([pscustomobject][ordered]@{ItemId=$consumer.ItemId;ScopeDisposition='External';Owner='fixture owner';Reason='Owner-reviewed external handling';Evidence='change:disposition-fixture'})
    $dispositionResult=Invoke-Form Submit-WsmAssistiveGeneralHostDispositions @{Workspace=$workspace;PairId=$catalog.PairId;ExpectedRevision=$dispositionRevision;Ack=$true;Decisions=$disposition}
    Check ($dispositionResult.Status -ceq 'Applied' -and $dispositionResult.DecisionRevision -gt $dispositionRevision -and (Test-Path -LiteralPath $dispositionResult.GeneratedDecisionsPath -PathType Leaf)) 'Typed GeneralHost disposition was not applied through its native preview/set consumer.'
    $afterDisposition=Get-WsmCatalog $workspace $catalog.PairId;$requirementRevision=[int]$afterDisposition.DecisionRevision;$requirements=@($afterDisposition.GeneralHost.Requirements)
    $requirementResult=Invoke-Form Submit-WsmAssistiveGeneralHostRequirements @{Workspace=$workspace;PairId=$catalog.PairId;ExpectedRevision=$requirementRevision;Ack=$true;Requirements=$requirements}
    Check ($requirementResult.Status -ceq 'Applied' -and $requirementResult.DecisionRevision -gt $requirementRevision -and $requirementResult.RequirementCount -eq $requirements.Count) 'Typed GeneralHost requirements were not applied through the native preview/set consumer.'
    if($requirements.Count -gt 0){$omitted=@($requirements | Select-Object -Skip 1);Reject { Invoke-Form Submit-WsmAssistiveGeneralHostRequirements @{Workspace=$workspace;PairId=$catalog.PairId;ExpectedRevision=$requirementResult.DecisionRevision;Ack=$true;Requirements=$omitted} } 'GeneralHost requirement form allowed removal of an existing obligation.'}
    $requirementReview=Get-WsmAssistiveGeneralHostRequirementReview $workspace $catalog.PairId
    $current=Get-WsmCatalog $workspace $catalog.PairId;$beforeRequirements=$current.GeneralHost.Requirements|ConvertTo-Json -Depth 100 -Compress
    Check ($requirementReview.Kind -ceq 'AssistiveRequirementReview' -and $requirementReview.Rows.Count -eq $current.GeneralHost.Requirements.Count -and -not ($requirementReview|ConvertTo-Json -Depth 100).Contains('SourceProof')) 'Requirement preview omitted current rows or exposed raw source proof.'
    $minimal=@(foreach($r in $requirementReview.Rows){[pscustomobject]@{RequirementId=$r.RequirementId;Decision=$r.Decision;Owner='fixture owner';DecisionReason='Explicit current review';DecisionEvidence='change:requirement-minimal'}})
    $minimalArgs=@{Workspace=$workspace;PairId=$catalog.PairId;ExpectedRevision=$requirementReview.ExpectedRevision;ReviewHash=$requirementReview.ReviewHash;Ack=$true;Decisions=$minimal}
    $bad=$minimalArgs.Clone();$bad.ReviewHash='0'*64;Reject {Submit-WsmAssistiveGeneralHostRequirementDecisions @bad} 'Stale requirement projection accepted.'
    $bad=$minimalArgs.Clone();$bad.Ack=$false;Reject {Submit-WsmAssistiveGeneralHostRequirementDecisions @bad} 'Missing explicit requirement confirmation accepted.'
    if($minimal.Count){$bad=$minimalArgs.Clone();$bad.Decisions=@();Reject {Submit-WsmAssistiveGeneralHostRequirementDecisions @bad} 'Minimal form removed an existing requirement.'; $bad=$minimalArgs.Clone();$bad.Decisions=@($minimal[0],$minimal[0]);Reject {Submit-WsmAssistiveGeneralHostRequirementDecisions @bad} 'Duplicate requirement decisions accepted.'}
    $applied=Submit-WsmAssistiveGeneralHostRequirementDecisions @minimalArgs
    Check ($applied.Status -ceq 'Applied') 'Minimal native requirement form did not reach the existing full requirement consumer.'
    $current=Get-WsmCatalog $workspace $catalog.PairId
    foreach($r in $current.GeneralHost.Requirements){$original=@($requirements|Where-Object RequirementId -CEQ $r.RequirementId)[0];Check (($r.Context|ConvertTo-Json -Depth 100 -Compress) -ceq ($original.Context|ConvertTo-Json -Depth 100 -Compress) -and ($r.SourceProof|ConvertTo-Json -Depth 100 -Compress) -ceq ($original.SourceProof|ConvertTo-Json -Depth 100 -Compress)) 'Minimal decision form changed nested source facts.'}
    Reject {Submit-WsmAssistiveGeneralHostRequirementDecisions @minimalArgs} 'Old minimal review was reused after native apply.'
    Write-Host ('PASS: '+$passed+' Assistive settings form checks; actual core consumer applied server-bound documents, with stale, unknown, unsupported and extra-field inputs rejected.')
} finally {if([IO.Directory]::Exists($root)){Remove-Item -LiteralPath $root -Recurse -Force}}
