#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-target-preparation-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
$passed=0
function Check([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message};$script:passed++}
function Reject([scriptblock]$Action,[string]$Message){$rejected=$false;try{& $Action | Out-Null}catch{$rejected=$true};Check $rejected $Message}
function SaveJson($Data,[string]$Path){[IO.File]::WriteAllText($Path,($Data|ConvertTo-Json -Depth 100 -Compress),(New-Object Text.UTF8Encoding($false)));$Path}
function CallModule([scriptblock]$Block,[object[]]$Arguments=@()){& $script:module $Block @Arguments}
function Get-HashTextModule($Value){CallModule {param($v) Get-WsmHashText ($v|ConvertTo-Json -Depth 100 -Compress)} @($Value)}
try {
    $source=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=('a'*64);Name='preparation-source';OS='Windows Server';Version='2025'}
    $target=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=('b'*64);Name='preparation-target';OS='Windows Server';Version='2025'}
    $selectedItem=CallModule {param($host) New-WsmItem $host Services Service 'Selected consumer' 'selected-consumer' @{PathName='C:\fixture\consumer.exe'}} @($source.HostId)
    $otherItem=CallModule {param($host) New-WsmItem $host Services Service 'Other approved consumer' 'other-consumer' @{PathName='C:\fixture\other.exe'}} @($source.HostId)
    $sourceInventory=CallModule {param($src,$items) New-WsmInventory $src 1 $items} @($source,@($selectedItem,$otherItem))
    $sourceEntry1=[pscustomobject][ordered]@{SoftwareId=('sw-'+('c'*32));Name='Fixture Runtime';Version='4.2';Publisher='Fixture Vendor';Architecture='x64';Scope='Machine';SID='';RegistryView='Registry64';Location='C:\Fixture\runtime';SourceKind='Registry';Evidence=[pscustomobject]@{RegistryPath='HKLM64\Uninstall\runtime';NaturalKey='fixture-runtime'};ObservedUtc=(Get-Date).ToUniversalTime().ToString('o');CaptureStatus='Success';ItemIds=@($selectedItem.ItemId,$otherItem.ItemId);AccountContext='System'}
    $sourceEntry2=[pscustomobject][ordered]@{SoftwareId=('sw-'+('d'*32));Name='Unselected Provider';Version='3.0';Publisher='Fixture Vendor';Architecture='x64';Scope='Machine';SID='';RegistryView='Registry64';Location='C:\Fixture\unselected';SourceKind='Registry';Evidence=[pscustomobject]@{RegistryPath='HKLM64\Uninstall\unselected';NaturalKey='fixture-unselected'};ObservedUtc=(Get-Date).ToUniversalTime().ToString('o');CaptureStatus='Success';ItemIds=@($otherItem.ItemId);AccountContext='System'}
    function New-SoftwareFixture($Inventory,[object[]]$Entries){$software=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion='0.4.0';Kind='SoftwareCatalog';Source=[pscustomobject][ordered]@{HostId=$Inventory.Source.HostId;Fingerprint=$Inventory.Source.Fingerprint;Name=$Inventory.Source.Name;InventoryRevision=[int]$Inventory.Revision;InventoryProjectionHash=(CallModule {param($i) Get-WsmSoftwareInventoryProjectionHash $i} @($Inventory))};CaptureContext=[pscustomobject][ordered]@{CapturedUtc=(Get-Date).ToUniversalTime().ToString('o');CaptureIdentity='fixture';AccountContext='System';CaptureHost='fixture';PowerShellVersion='5.1';RequestedPortableRoots=@()};Entries=$Entries;Coverage=@([pscustomobject][ordered]@{Probe='Uninstall';Scope='Machine';SID='';View='Registry64';Status='Success';EvidenceKind='Registry';Count=$Entries.Count;Budget=[pscustomobject]@{MaxEntries=100};ErrorKind=$null;ItemId='';ObservedUtc=(Get-Date).ToUniversalTime().ToString('o')});PreparationRequirements=@(foreach($entry in $Entries){[pscustomobject]@{PreparationId=('prep-'+([string]$entry.SoftwareId).Substring(3));SoftwareId=$entry.SoftwareId;Status='NeedsOwnerReview';RequiredPhase='PreparationReady';EvidenceStatus=$entry.CaptureStatus;ConsumerItemIds=@($entry.ItemIds);Owner='';Reason='Fixture evidence only'}});CatalogProjectionHash=('0'*64)};$software.CatalogProjectionHash=CallModule {param($s) Get-WsmSoftwareCatalogProjectionHash $s} @($software);CallModule {param($s,$i) Assert-WsmSoftwareCatalog $s -SourceInventory $i | Out-Null} @($software,$Inventory);$software}
    $sourceInventory | Add-Member NoteProperty SoftwareCatalog (New-SoftwareFixture $sourceInventory @($sourceEntry1,$sourceEntry2)) -Force
    $sourceInventoryPath=Join-Path $root 'source-inventory.json';SaveJson $sourceInventory $sourceInventoryPath | Out-Null;$sourceHash=(Get-FileHash -LiteralPath $sourceInventoryPath -Algorithm SHA256).Hash.ToLowerInvariant()

    $targetInventory=CallModule {param($src) New-WsmInventory $src 1 @()} @($target)
    $targetEntry=[pscustomobject][ordered]@{};foreach($property in $sourceEntry1.PSObject.Properties){$targetEntry | Add-Member NoteProperty $property.Name $property.Value};$targetEntry.Version='5.0';$targetEntry.ItemIds=@();$targetEntry.ObservedUtc=(Get-Date).ToUniversalTime().ToString('o')
    $targetInventory | Add-Member NoteProperty SoftwareCatalog (New-SoftwareFixture $targetInventory @($targetEntry)) -Force
    $targetSnapshotPath=Join-Path $root 'target-snapshot.json';SaveJson $targetInventory $targetSnapshotPath | Out-Null;$targetSnapshotHash=(Get-FileHash -LiteralPath $targetSnapshotPath -Algorithm SHA256).Hash.ToLowerInvariant()

    $pairId=[Guid]::NewGuid().ToString();$batchId=[Guid]::NewGuid().ToString();$approvalId=[Guid]::NewGuid().ToString();$sourceSelectionVersion=1
    $selectedPlanItem=$selectedItem | ConvertTo-Json -Depth 30 | ConvertFrom-Json
    $otherPlanItem=$otherItem | ConvertTo-Json -Depth 30 | ConvertFrom-Json
    foreach($entry in @($selectedPlanItem,$otherPlanItem)){$entry | Add-Member NoteProperty Decision Include -Force;$entry | Add-Member NoteProperty Reason 'Reviewed source workload' -Force;$entry | Add-Member NoteProperty Owner 'source owner' -Force;$entry | Add-Member NoteProperty Evidence 'fixture review record' -Force;$entry | Add-Member NoteProperty MigrationSpec ([pscustomobject][ordered]@{Adapter='ManualWorkflow';Product='Fixture workload';Procedure='Owner installs and verifies the workload';Artifacts=@();BusinessChecks=@('Owner confirms application readiness');Owner='source owner';Evidence='fixture review record'}) -Force}
    $prepEvidence=[pscustomobject][ordered]@{MediaReference='fixture-media';MediaSHA256=('e'*64);VerificationMethod='OwnerVerified';SignatureEvidence='signature-review';VendorOSSupportReference='vendor-support';VendorSupportCheckedUtc=(Get-Date).ToUniversalTime().AddMinutes(-1).ToString('o');LicenseReference='license-review';InstallOrder=1;IsolationEvidenceSHA256=('f'*64);RestartStatus='CompletedAndVerified';SideEffectsReference='isolation-review'}
    $requirement1=[pscustomobject][ordered]@{RequirementId='';Type='Preparation';ProviderSoftwareId=$sourceEntry1.SoftwareId;ProviderItemId='';ExternalId='';ConsumerItemIds=@($selectedItem.ItemId,$otherItem.ItemId);Certainty='Required';RequiredPhase='PreparationReady';ExpectedVersion='4.2';Architecture='x64';Context=[pscustomobject][ordered]@{Provider='Fixture Runtime';Version='4.2';Architecture='x64';ConsumerItemIds=@($selectedItem.ItemId,$otherItem.ItemId);PreparationEvidence=$prepEvidence};Owner='runtime owner';SourceProof=[pscustomobject]@{InventoryHash=$sourceHash;RegistryPathHash=('1'*64);Status='NativeObserved'};Decision='Required';DecisionReason='Required by the selected consumer';DecisionEvidence='dependency review'}
    $requirement2=[pscustomobject][ordered]@{RequirementId='';Type='Preparation';ProviderSoftwareId=$sourceEntry2.SoftwareId;ProviderItemId='';ExternalId='';ConsumerItemIds=@($otherItem.ItemId);Certainty='Required';RequiredPhase='PreparationReady';ExpectedVersion='3.0';Architecture='x64';Context=[pscustomobject][ordered]@{Provider='Unselected Provider';Version='3.0';Architecture='x64';ConsumerItemIds=@($otherItem.ItemId);PreparationEvidence=$prepEvidence};Owner='other owner';SourceProof=[pscustomobject]@{InventoryHash=$sourceHash;RegistryPathHash=('2'*64);Status='NativeObserved'};Decision='Required';DecisionReason='Only needed by the unselected consumer';DecisionEvidence='other dependency review'}
    foreach($requirement in @($requirement1,$requirement2)){$requirement.RequirementId=CallModule {param($r) Get-WsmGeneralHostRequirementId $r} @($requirement)}
    $sourceSoftware=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion='0.4.0';Kind='SoftwareCatalog';Source=[pscustomobject][ordered]@{HostId=$source.HostId;Fingerprint=$source.Fingerprint;Name=$source.Name;InventoryRevision=1;InventoryProjectionHash=(CallModule {param($i) Get-WsmSoftwareInventoryProjectionHash $i} @($sourceInventory))};CaptureContext=$sourceInventory.SoftwareCatalog.CaptureContext;Entries=@($sourceEntry1,$sourceEntry2);Coverage=$sourceInventory.SoftwareCatalog.Coverage;PreparationRequirements=$sourceInventory.SoftwareCatalog.PreparationRequirements;CatalogProjectionHash=('0'*64)};$sourceSoftware.CatalogProjectionHash=CallModule {param($s) Get-WsmSoftwareCatalogProjectionHash $s} @($sourceSoftware)
    $plan=[pscustomobject][ordered]@{SchemaVersion=3;ToolVersion='0.4.0';Kind='MigrationPlan';BatchId=$batchId;PairId=$pairId;ApprovalId=$approvalId;Source=$source;Target=$target;InventoryRevision=1;DecisionRevision=1;InventoryHash=$sourceHash;ImportedUtc=(Get-Date).ToUniversalTime().ToString('o');Mode='IsolatedPilot';ToolFingerprint=(CallModule {Get-WsmToolFingerprint});ApprovedUtc=(Get-Date).ToUniversalTime().ToString('o');Items=@($selectedPlanItem,$otherPlanItem);ScopeMode='GeneralHost';GeneralHost=[pscustomobject][ordered]@{SchemaVersion=1;ScopeMode='GeneralHost';SoftwareCatalog=$sourceSoftware;SoftwareCatalogHash=(Get-HashTextModule $sourceSoftware);SoftwareDecisions=@();Requirements=@($requirement1,$requirement2);OrphanedRequirements=@();EvidenceReceipts=@();UpdatedUtc=(Get-Date).ToUniversalTime().ToString('o')}}
    $sourceReference=[pscustomobject][ordered]@{Reference='source-inventory.json';SHA256=$sourceHash;CreatedUtc=(Get-Date).ToUniversalTime().ToString('o');InventoryRevision=1}
    $plan | Add-Member NoteProperty Assistive ([pscustomobject][ordered]@{ContractVersion=1;PairId=$pairId;SourceSnapshotHash=$sourceHash;SourcePolicy='SourceCOnly';SourceSelectionsVersion=$sourceSelectionVersion;ApprovedItemIds=@($selectedItem.ItemId,$otherItem.ItemId);MaterialReferences=@();DiscoveryAuthority=[pscustomobject][ordered]@{SourceSnapshotReference=$sourceReference;InventoryRevision=1;SelectionRevision=$sourceSelectionVersion;Dispositions=@([pscustomobject]@{ItemId=$selectedItem.ItemId;Selected=$true;Decision='Include';Reason='reviewed'},[pscustomobject]@{ItemId=$otherItem.ItemId;Selected=$true;Decision='Include';Reason='reviewed'})}}) -Force
    CallModule {param($p) Assert-WsmAssistiveContract $p MigrationPlan | Out-Null;Assert-WsmGeneralHostSoftwareCatalog $p.GeneralHost.SoftwareCatalog | Out-Null} @($plan)
    $planPath=Join-Path $root 'typed-plan.json';SaveJson $plan $planPath | Out-Null;$planHash=(Get-FileHash -LiteralPath $planPath -Algorithm SHA256).Hash.ToLowerInvariant();$plan=CallModule {param($path,$hash) Read-WsmJson $path $hash} @($planPath,$planHash)
    $manifestPath=Join-Path $root 'fixture-manifest.json';$manifest=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion='0.4.0';Kind='MigrationManifest';PairId=$pairId;PlanHash=$planHash;Generation=1;Final=$true;Target=$target};SaveJson $manifest $manifestPath | Out-Null;$manifestHash=(Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $package=[pscustomobject][ordered]@{Plan=$plan;Manifest=$manifest;ManifestPath=$manifestPath;ManifestHash=$manifestHash;PlanHash=$planHash;SHA256=$manifestHash}
    $comparison=[pscustomobject][ordered]@{Revision=1;SelectionRevision=$sourceSelectionVersion;SourceSnapshotHash=$sourceHash;TargetSnapshotHash=$targetSnapshotHash;Rows=@(
        [pscustomobject][ordered]@{SoftwareId=$sourceEntry1.SoftwareId;SourceVersion='4.2';ChosenVersion='5.0';ObservedTargetVersion='5.0';TargetSoftwareId=$targetEntry.SoftwareId;Status='ChosenVersionObserved'},
        [pscustomobject][ordered]@{SoftwareId=$sourceEntry2.SoftwareId;SourceVersion='3.0';ChosenVersion='3.0';ObservedTargetVersion='';TargetSoftwareId='';Status='TargetMissing'}
    )}
    $receipt=CallModule {param($path,$planHash,$manifestHash,$generation,$targetHash,$selectionVersion,$selectedId,$comparison) New-WsmAssistiveTargetDecisionReceipt -PlanPath $path -PlanHash $planHash -ManifestHash $manifestHash -Generation $generation -TargetSnapshotHash $targetHash -ComparisonRevision $comparison.Revision -SelectionRevision $selectionVersion -Decision RestoreNow -Owner 'target owner' -Reason 'Reviewed target runtime preparation' -SelectedItemIds @($selectedId) -Comparison $comparison} @($planPath,$planHash,$manifestHash,1,$targetSnapshotHash,$sourceSelectionVersion,$selectedItem.ItemId,$comparison)
    $receiptPath=Join-Path $root 'target-decision.json';SaveJson $receipt $receiptPath | Out-Null;$receiptHash=(Get-FileHash -LiteralPath $receiptPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $evidencePath=Join-Path $root 'owner-evidence.bin';$secretSentinel='raw-evidence-secret-sentinel';[IO.File]::WriteAllText($evidencePath,$secretSentinel,(New-Object Text.UTF8Encoding($false)));$evidenceHash=(Get-FileHash -LiteralPath $evidencePath -Algorithm SHA256).Hash.ToLowerInvariant()
    $workspace=Join-Path $root 'target-workspace';[void][IO.Directory]::CreateDirectory($workspace)
    $fixtureIdentity=[pscustomobject]@{HostId=$target.HostId;Fingerprint=$target.Fingerprint;Name=$target.Name;OS=$target.OS;Version=$target.Version;IsServer=$true;Administrator=$true;Is64Bit=$true}
    CallModule {param($pkg,$packagePath,$packageHash,$identity) $script:targetPreparationPackage=$pkg;$script:targetPreparationManifestPath=$packagePath;$script:targetPreparationManifestHash=$packageHash;$script:targetPreparationIdentity=$identity;function script:Test-WsmMigrationPackage {param([string]$ManifestPath,[string]$ExpectedHash) if([IO.Path]::GetFullPath($ManifestPath) -ine [IO.Path]::GetFullPath($script:targetPreparationManifestPath) -or $ExpectedHash -ine $script:targetPreparationManifestHash){throw 'Isolated fixture package validator received an unexpected manifest binding.'};$script:targetPreparationPackage};function script:Get-WsmMachineIdentity {$script:targetPreparationIdentity};function script:Get-WsmAssistiveCurrentSoftwareCatalog($Snapshot){$Snapshot.SoftwareCatalog}} @($package,$manifestPath,$manifestHash,$fixtureIdentity)
    $previewArgs=@{ManifestPath=$manifestPath;ExpectedHash=$manifestHash;AssistiveDecisionReceiptPath=$receiptPath;AssistiveDecisionReceiptHash=$receiptHash;AssistiveTargetSnapshotPath=$targetSnapshotPath}
    $preview=Get-WsmAssistivePreparationPreview @previewArgs
    Check ($preview.Kind -ceq 'AssistivePreparationPreview' -and $preview.Status -ceq 'Previewed' -and $preview.ReadinessProof -eq $false -and $preview.Rows.Count -eq 1) 'Public preparation preview did not project only requirements with a selected consumer.'
    Check ($preview.Rows[0].ExpectedVersion -ceq '5.0' -and $preview.Rows[0].ConsumerItemIds -contains $otherItem.ItemId -and $preview.Rows[0].ContextHash -match '^[a-f0-9]{64}$') 'Preview lost chosen target version, shared source consumer obligations, or safe context hash.'
    Check (-not ($preview | ConvertTo-Json -Depth 20 -Compress).Contains($secretSentinel) -and -not $preview.Rows[0].PSObject.Properties['Context']) 'Public preview exposed raw context or evidence content.'
    $freshArgs=@{ManifestPath=$manifestPath;ExpectedHash=$manifestHash;AssistiveDecisionReceiptPath=$receiptPath;AssistiveDecisionReceiptHash=$receiptHash;AssistiveTargetSnapshotPath=$targetSnapshotPath;RequirementIds=@($preview.Rows[0].RequirementId);Owner='target runtime owner';EvidencePath=$evidencePath;EvidenceHash=$evidenceHash;ObservedUtc=(Get-Date).ToUniversalTime().ToString('o');ExpiresUtc=(Get-Date).ToUniversalTime().AddHours(2).ToString('o');Workspace=$workspace;AckContextReadback=$true}
    $noAck=$freshArgs.Clone();$noAck.AckContextReadback=$false;Reject {Export-WsmAssistivePreparationEvidence @noAck} 'Preparation evidence was written without context-readback acknowledgment.'
    $unknown=$freshArgs.Clone();$unknown.RequirementIds=@(('9'*64));Reject {Export-WsmAssistivePreparationEvidence @unknown} 'Out-of-scope requirement identity was accepted.'
    $duplicate=$freshArgs.Clone();$duplicate.RequirementIds=@($preview.Rows[0].RequirementId,$preview.Rows[0].RequirementId);Reject {Export-WsmAssistivePreparationEvidence @duplicate} 'Duplicate requirement identities were accepted.'
    $unselected=$freshArgs.Clone();$unselected.RequirementIds=@($requirement2.RequirementId);Reject {Export-WsmAssistivePreparationEvidence @unselected} 'A requirement belonging only to an unselected consumer was accepted.'
    $badEvidence=$freshArgs.Clone();$badEvidence.EvidenceHash=('0'*64);Reject {Export-WsmAssistivePreparationEvidence @badEvidence} 'Evidence bytes with a mismatched physical SHA256 were accepted.'
    $badReceipt=$freshArgs.Clone();$badReceipt.AssistiveDecisionReceiptHash=('0'*64);Reject {Export-WsmAssistivePreparationEvidence @badReceipt} 'A stale or corrupted target decision receipt was accepted.'
    $missingAck=$freshArgs.Clone();$missingAck.Remove('AckContextReadback');Reject {Export-WsmAssistivePreparationEvidence @missingAck} 'Evidence factory accepted a missing owner acknowledgment switch.'
    $outputOutside=$freshArgs.Clone();$outputOutside.OutputPath=Join-Path $root 'outside-evidence.json';Reject {Export-WsmAssistivePreparationEvidence @outputOutside} 'Evidence factory wrote outside the protected workspace forms directory.'
    $forms=Join-Path (Join-Path $workspace 'assistive') 'forms';[void][IO.Directory]::CreateDirectory($forms);$collisionPath=Join-Path $forms 'already-exists.json';[IO.File]::WriteAllText($collisionPath,'existing');$collision=$freshArgs.Clone();$collision.OutputPath=$collisionPath;Reject {Export-WsmAssistivePreparationEvidence @collision} 'Evidence factory overwrote an existing output file.'
    $written=Export-WsmAssistivePreparationEvidence @freshArgs
    Check ($written.Status -ceq 'EvidenceRecorded' -and $written.ReadinessProof -eq $false -and $written.ProductionVerified -eq $false -and $written.ReceiptCount -eq 1) 'Public evidence factory returned an overstated gate result or wrong receipt count.'
    Check ((Get-FileHash -LiteralPath $written.Path -Algorithm SHA256).Hash.ToLowerInvariant() -ceq $written.SHA256 -and $written.SHA256 -cne $evidenceHash) 'Generated file hash was not the exact physical bytes hash or was confused with evidence hash.'
    $evidenceSet=CallModule {param($path,$hash) Read-WsmTrustedJson $path $hash} @($written.Path,$written.SHA256)
    Check ($evidenceSet.Kind -ceq 'GeneralHostEvidenceSet' -and $evidenceSet.PairId -ceq $pairId -and $evidenceSet.Receipts.Count -eq 1 -and $evidenceSet.Receipts[0].EvidencePathHash -ceq $evidenceHash -and $evidenceSet.Receipts[0].RequirementProjectionHash -match '^[a-f0-9]{64}$' -and $evidenceSet.Receipts[0].RequirementProjectionHash -cne $evidenceHash) 'Generated receipt confused source evidence bytes with its semantic requirement projection.'
    Check (-not [IO.File]::ReadAllText($written.Path).Contains($secretSentinel)) 'Generated evidence set copied raw physical evidence content.'
    $decision=CallModule {param($pkg,$hash,$receiptPath,$receiptHash,$snapshotPath) Get-WsmAssistiveRestoreDecision $pkg $hash $receiptPath $receiptHash $snapshotPath} @($package,$manifestHash,$receiptPath,$receiptHash,$targetSnapshotPath)
    $targetPlan=CallModule {param($pkg,$d) Get-WsmAssistiveTargetPlan $pkg $d} @($package,$decision)
    $nativeReceipt=$evidenceSet.Receipts[0]
    CallModule {param($r,$p,$targetFingerprint,$planHash) Assert-WsmGeneralHostReceipt $r $p -TargetFingerprint $targetFingerprint -PlanHash $planHash | Out-Null} @($nativeReceipt,$targetPlan,$target.Fingerprint,$planHash)
    Check ($nativeReceipt.Context.AssistiveTargetBinding.DecisionReceiptHash -ceq $receiptHash -and $nativeReceipt.Context.AssistiveTargetBinding.TargetSnapshotHash -ceq $targetSnapshotHash -and $nativeReceipt.Context.AssistiveTargetBinding.ComparisonHash -ceq $receipt.ComparisonHash) 'Generated phase receipt did not preserve all fresh target decision bindings.'

    $registry=CallModule {param($path) Get-WsmAssistiveResourceRegistry $path} @($workspace)
    $registeredEvidence=@($registry.Materials | Where-Object {$_.Kind -ceq 'TargetPreparationOwnerEvidence' -and $_.Path -ieq [IO.Path]::GetFullPath($evidencePath)})
    $registeredReceipt=@($registry.Materials | Where-Object {$_.Kind -ceq 'TargetPreparationReceipt' -and $_.Path -ieq [IO.Path]::GetFullPath($written.Path)})
    Check ($registeredEvidence.Count -eq 1 -and $registeredReceipt.Count -eq 1 -and $registry.Materials.Count -eq 2) 'Material registry did not retain exactly the original evidence and generated receipt.'
    foreach($material in @($registeredEvidence)+@($registeredReceipt)){Check ($material.PairId -ceq $pairId -and $material.Generation -eq 1 -and @($material.ConsumerRefs).Count -eq 1 -and $material.ConsumerRefs[0] -ceq $selectedItem.ItemId -and -not $material.Closed -and -not $material.RetentionUntilUtc) ('Material registry lost selected consumer scope or prematurely closed material: '+$material.Kind)}
    Check ($registeredEvidence[0].SHA256 -ceq $evidenceHash -and $registeredReceipt[0].SHA256 -ceq $written.SHA256) 'Material registry stored hashes other than the validated physical evidence and receipt byte hashes.'
    $cleanupPreview=Get-WsmAssistiveCleanupPreview -Workspace $workspace -RetentionBeforeUtc (Get-Date).ToUniversalTime().AddDays(1).ToString('o')
    Check (@($cleanupPreview.Rows | Where-Object {$_.MaterialId -in @($registeredEvidence[0].MaterialId,$registeredReceipt[0].MaterialId) -and -not $_.Eligible}).Count -eq 2) 'Unclosed preparation evidence or receipt appeared eligible for cleanup.'
    $forcedCleanupPreview=CallModule {param($p) $copy=ConvertFrom-WsmJson ($p|ConvertTo-Json -Depth 40 -Compress);foreach($row in $copy.Rows){$row.Eligible=$true};$copy.PSObject.Properties.Remove('SHA256');$copy|Add-Member NoteProperty SHA256 (Get-WsmHashText ($copy|ConvertTo-Json -Depth 30 -Compress));$copy} @($cleanupPreview)
    Reject {CallModule {param($ws,$p,$hash,$revision) Invoke-WsmAssistiveCleanup -Workspace $ws -Preview $p -ExpectedPreviewHash $hash -ExpectedRevision $revision -Reason 'Test cleanup must refuse live preparation materials' -Confirmed $true -Confirm:$false} @($workspace,$forcedCleanupPreview,$forcedCleanupPreview.SHA256,$forcedCleanupPreview.RegistryRevision)} 'Cleanup accepted a forged eligible preview for still-referenced preparation materials.'
    Check ([IO.File]::Exists($evidencePath) -and [IO.File]::Exists($written.Path)) 'Cleanup refusal deleted original evidence or generated receipt bytes.'
    $afterCleanupRegistry=CallModule {param($path) Get-WsmAssistiveResourceRegistry $path} @($workspace)
    Check ($afterCleanupRegistry.Materials.Count -eq 2 -and @($afterCleanupRegistry.Materials | Where-Object {$_.MaterialId -in @($registeredEvidence[0].MaterialId,$registeredReceipt[0].MaterialId) -and @($_.ConsumerRefs).Count -eq 1 -and -not $_.Closed}).Count -eq 2) 'Cleanup refusal removed or closed registered preparation material references.'

    function New-TamperedReceiptFile($Original,[string]$Field,[string]$Value,[string]$Name){$copy=CallModule {param($r) ConvertFrom-WsmJson ($r|ConvertTo-Json -Depth 100 -Compress)} @($Original);$copy.Comparison.Rows[0].$Field=$Value;$copy.ComparisonHash=Get-HashTextModule $copy.Comparison;$body=[ordered]@{};foreach($property in $copy.PSObject.Properties){if($property.Name -cne 'SHA256'){$body[$property.Name]=$property.Value}};$copy.SHA256=CallModule {param($v) Get-WsmHashText ($v|ConvertTo-Json -Depth 20 -Compress)} @($body);$path=Join-Path $root $Name;SaveJson $copy $path | Out-Null;[pscustomobject]@{Path=$path;Hash=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}}
    $tamperedSource=New-TamperedReceiptFile $receipt SourceVersion '99.0' 'tampered-source-version.json'
    Reject {CallModule {param($pkg,$hash,$path,$receiptHash,$snapshotPath) Get-WsmAssistiveRestoreDecision $pkg $hash $path $receiptHash $snapshotPath} @($package,$manifestHash,$tamperedSource.Path,$tamperedSource.Hash,$targetSnapshotPath)} 'Native restore-decision validation accepted a hash-consistent comparison with a tampered source version.'
    $contradictoryStatus=New-TamperedReceiptFile $receipt Status 'DifferentFromChosenVersion' 'tampered-contradictory-status.json'
    Reject {CallModule {param($pkg,$hash,$path,$receiptHash,$snapshotPath) Get-WsmAssistiveRestoreDecision $pkg $hash $path $receiptHash $snapshotPath} @($package,$manifestHash,$contradictoryStatus.Path,$contradictoryStatus.Hash,$targetSnapshotPath)} 'Native restore-decision validation accepted DifferentFromChosenVersion when the exact chosen and observed versions matched.'
    $tamperedStatus=New-TamperedReceiptFile $receipt ChosenVersion '6.0' 'tampered-chosen-status.json'
    Reject {CallModule {param($pkg,$hash,$path,$receiptHash,$snapshotPath) Get-WsmAssistiveRestoreDecision $pkg $hash $path $receiptHash $snapshotPath} @($package,$manifestHash,$tamperedStatus.Path,$tamperedStatus.Hash,$targetSnapshotPath)} 'Native restore-decision validation accepted ChosenVersionObserved when the selected version differed from the exact target evidence.'
    $staleSnapshot=CallModule {param($snapshot) $copy=ConvertFrom-WsmJson ($snapshot|ConvertTo-Json -Depth 100 -Compress);$copy.CreatedUtc='2020-01-01T00:00:00Z';$copy} @($targetInventory);$staleSnapshotPath=Join-Path $root 'stale-target-snapshot.json';SaveJson $staleSnapshot $staleSnapshotPath | Out-Null;$staleSnapshotHash=(Get-FileHash -LiteralPath $staleSnapshotPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $staleComparison=CallModule {param($c,$hash) $copy=ConvertFrom-WsmJson ($c|ConvertTo-Json -Depth 100 -Compress);$copy.TargetSnapshotHash=$hash;$copy} @($comparison,$staleSnapshotHash)
    $staleReceipt=CallModule {param($path,$planHash,$manifestHash,$snapshotHash,$selection,$selectedId,$comparison) New-WsmAssistiveTargetDecisionReceipt -PlanPath $path -PlanHash $planHash -ManifestHash $manifestHash -Generation 1 -TargetSnapshotHash $snapshotHash -ComparisonRevision $comparison.Revision -SelectionRevision $selection -Decision RestoreNow -Owner 'target owner' -Reason 'stale snapshot negative' -SelectedItemIds @($selectedId) -Comparison $comparison} @($planPath,$planHash,$manifestHash,$staleSnapshotHash,$sourceSelectionVersion,$selectedItem.ItemId,$staleComparison)
    $staleReceiptPath=Join-Path $root 'stale-snapshot-receipt.json';SaveJson $staleReceipt $staleReceiptPath | Out-Null;$staleReceiptHash=(Get-FileHash -LiteralPath $staleReceiptPath -Algorithm SHA256).Hash.ToLowerInvariant()
    Reject {CallModule {param($pkg,$hash,$path,$receiptHash,$snapshotPath) Get-WsmAssistiveRestoreDecision $pkg $hash $path $receiptHash $snapshotPath} @($package,$manifestHash,$staleReceiptPath,$staleReceiptHash,$staleSnapshotPath)} 'Native restore-decision validation accepted a stale target snapshot.'
    $wrongIdentity=[pscustomobject]@{HostId=$target.HostId;Fingerprint=('7'*64);Name='wrong target';OS='Windows Server';Version='2025';IsServer=$true;Administrator=$true;Is64Bit=$true};CallModule {param($identity) $script:targetPreparationIdentity=$identity} @($wrongIdentity)
    Reject {Get-WsmAssistivePreparationPreview @previewArgs} 'Public preparation preview accepted an execution host other than the sealed target.'
    CallModule {param($identity) $script:targetPreparationIdentity=$identity} @($fixtureIdentity)
    $tamperedSnapshot=[IO.File]::ReadAllBytes($targetSnapshotPath);[IO.File]::AppendAllText($targetSnapshotPath,' ');Reject {Get-WsmAssistivePreparationPreview @previewArgs} 'Public preparation preview accepted changed target snapshot bytes.';[IO.File]::WriteAllBytes($targetSnapshotPath,$tamperedSnapshot)
    Write-Host ('PASS: '+$passed+' Assistive target-preparation public-seam checks (package-validator isolation explicitly mocked).')
} finally {Remove-Item -LiteralPath $root -Recurse -Force}
