#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-cross-host-coordination-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
& $module {
    param($Root)
    . (Join-Path $PSScriptRoot '..\src\CrossHostCoordination.ps1')
    $script:coordinationFingerprint=''
    $script:coordinationPackages=@{};$script:rollbackFixtureState=$null;$script:rollbackReadbacks=@{}
    function script:Get-WsmMachineIdentity {[pscustomobject]@{Fingerprint=$script:coordinationFingerprint}}
    function script:Assert-WsmMigrationHost($Identity,[string]$Fingerprint){if($Identity.Fingerprint -cne $Fingerprint){throw 'Fixture target identity mismatch.'}}
    function script:Test-WsmMigrationPackage([string]$ManifestPath,[string]$ExpectedHash){if((Get-FileHash $ManifestPath).Hash -ine $ExpectedHash -or -not $script:coordinationPackages.ContainsKey($ManifestPath)){throw 'Fixture package trust check failed.'};$script:coordinationPackages[$ManifestPath]}
    function script:Get-WsmOperationPaths([string]$StateDirectory,[string]$PairId){[pscustomobject]@{Root=$StateDirectory}}
    function script:Get-WsmOperationState($Paths,$Package){$script:rollbackFixtureState}
    function script:Invoke-WsmLocked([string]$Workspace,[scriptblock]$Action){& $Action}
    function script:Test-WsmAdapterConfiguration($Spec,[string]$Phase='Staged'){$script:rollbackReadbacks[[string]$Spec.Desired.Name]}
    function Assert-Throws([scriptblock]$Action,[string]$Name){$thrown=$false;try{& $Action}catch{$thrown=$true};if(-not $thrown){throw ('Expected rejection: '+$Name)}}
    $batch=[Guid]::NewGuid().ToString();$groupId=[Guid]::NewGuid().ToString();$members=@();$plans=@()
    for($n=1;$n -le 2;$n++){
        $pair=[Guid]::NewGuid().ToString();$sourceId=[Guid]::NewGuid().ToString();$targetId=[Guid]::NewGuid().ToString();$approval=[Guid]::NewGuid().ToString();$prefix=(''+$n)
        $planPath=Join-Path $Root ('plan-'+$n+'.json');$plan=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='MigrationPlan';BatchId=$batch;PairId=$pair;ApprovalId=$approval;Source=[pscustomobject]@{HostId=$sourceId;Fingerprint=(('a' * 63)+$prefix)};Target=[pscustomobject]@{HostId=$targetId;Fingerprint=(('b' * 63)+$prefix)};Mode='IsolatedPilot';InventoryRevision=1;DecisionRevision=2;Items=@([pscustomobject]@{ItemId=($prefix*64);Decision='Include';ConsistencyGroup=$groupId;ConsistencyOwner='change owner';ConsistencyEvidence='approved consistency review';MigrationSpec=[pscustomobject]@{Adapter='Service'}});CrossHostDependencies=@()}
        if($n -eq 1){$plan.CrossHostDependencies=@([pscustomobject]@{PairId='00000000-0000-0000-0000-000000000002';Type='Mandatory';Evidence='cycle member'})}
        Write-WsmJson $planPath $plan;$planHash=(Get-FileHash $planPath).Hash;$plans+=@([pscustomobject]@{Path=$planPath;Hash=$planHash;Plan=$plan})
        $freezePath=Join-Path $Root ('freeze-'+$n+'.json');$freeze=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='SourceFreeze';FreezeId=[Guid]::NewGuid().ToString();BatchId=$batch;PairId=$pair;ApprovalId=$approval;PlanHash=$planHash;SourceHostId=$sourceId;SourceFingerprint=$plan.Source.Fingerprint;Owner='source owner';Evidence='fixture freeze';Acknowledgement='OWNER-CONFIRMED-QUIESCENCE';ProducedUtc=[DateTime]::UtcNow.ToString('o');ExpiresUtc=[DateTime]::UtcNow.AddHours(2).ToString('o')};Write-WsmJson $freezePath $freeze;$freezeHash=(Get-FileHash $freezePath).Hash
        $manifestPath=Join-Path $Root ('manifest-'+$n+'.json');$generation=3;$manifest=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='MigrationPackage';BatchId=$batch;PairId=$pair;ApprovalId=$approval;PlanHash=$planHash;Source=$plan.Source;Target=$plan.Target;Generation=$generation;Final=$true;FreezeHash=$freezeHash};Write-WsmJson $manifestPath $manifest;$manifestHash=(Get-FileHash $manifestPath).Hash
        $resultPath=Join-Path $Root ('staged-'+$n+'.json');$result=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='StageResult';BatchId=$batch;PairId=$pair;SourceHostId=$sourceId;TargetHostId=$targetId;TargetFingerprint=$plan.Target.Fingerprint;ApprovalId=$approval;PlanHash=$planHash;ManifestHash=$manifestHash;PayloadGeneration=$generation;Stage='PreCutoverValidation';Status='Succeeded';ProducedUtc=[DateTime]::UtcNow.ToString('o');Mode='IsolatedPilot';ProductionVerified=$false};Write-WsmJson $resultPath $result
        $members+=@([pscustomobject]@{PlanPath=$planPath;PlanHash=$planHash})
        $plans[-1] | Add-Member NoteProperty FreezePath $freezePath;$plans[-1] | Add-Member NoteProperty FreezeHash $freezeHash;$plans[-1] | Add-Member NoteProperty ManifestPath $manifestPath;$plans[-1] | Add-Member NoteProperty ManifestHash $manifestHash;$plans[-1] | Add-Member NoteProperty ResultPath $resultPath;$plans[-1] | Add-Member NoteProperty ResultHash (Get-FileHash $resultPath).Hash
    }
    # Set an actual reciprocal mandatory cycle using each member's stable pair identity.
    $plans[0].Plan.CrossHostDependencies=@([pscustomobject]@{PairId=$plans[1].Plan.PairId;Type='Mandatory';Evidence='cycle A to B'})
    $plans[1].Plan.CrossHostDependencies=@([pscustomobject]@{PairId=$plans[0].Plan.PairId;Type='Mandatory';Evidence='cycle B to A'})
    foreach($p in $plans){Write-WsmJson $p.Path $p.Plan;$p.Hash=(Get-FileHash $p.Path).Hash;$p.FreezePath=(Join-Path $Root ('freeze-'+([array]::IndexOf($plans,$p)+1)+'.json'))
        $freeze=Read-WsmJson $p.FreezePath;$freeze.PlanHash=$p.Hash;Write-WsmJson $p.FreezePath $freeze;$p.FreezeHash=(Get-FileHash $p.FreezePath).Hash
        $manifestPath=$p.ManifestPath;$manifest=Read-WsmJson $manifestPath;$manifest.PlanHash=$p.Hash;$manifest.FreezeHash=$p.FreezeHash;Write-WsmJson $manifestPath $manifest;$p.ManifestHash=(Get-FileHash $manifestPath).Hash
        $result=Read-WsmJson $p.ResultPath;$result.PlanHash=$p.Hash;$result.ManifestHash=$p.ManifestHash;Write-WsmJson $p.ResultPath $result;$p.ResultHash=(Get-FileHash $p.ResultPath).Hash;$script:coordinationPackages[$p.ManifestPath]=[pscustomobject]@{Valid=$true;Manifest=$manifest;Plan=$p.Plan;PlanHash=$p.Hash}
    }
    $members=@(foreach($p in $plans){[pscustomobject]@{PlanPath=$p.Path;PlanHash=$p.Hash}})
    $groupPath=Join-Path $Root 'group.json';$created=New-WsmConsistencyGroupPlan -GroupId $groupId -Members $members -Owner 'change owner' -Evidence 'approved consistency review' -Path $groupPath
    $receipts=@()
    for($i=0;$i -lt 2;$i++){$p=$plans[$i];$script:coordinationFingerprint=$p.Plan.Target.Fingerprint;$path=Join-Path $Root ('receipt-'+($i+1)+'.json');$receipt=New-WsmConsistencyGroupReceipt -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -PairId $p.Plan.PairId -Stage FinalStaged -PlanPath $p.Path -PlanHash $p.Hash -ManifestPath $p.ManifestPath -ManifestHash $p.ManifestHash -FreezePath $p.FreezePath -FreezeHash $p.FreezeHash -StageResultPath $p.ResultPath -StageResultHash $p.ResultHash -Path $path;$receipts+=@([pscustomobject]@{Path=$path;SHA256=$receipt.SHA256})}
    $barrier=Assert-WsmConsistencyGroupBarrier -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -Stage FinalStaged -Receipts $receipts
    if(-not $barrier.Passed -or $barrier.MemberCount -ne 2){throw 'Complete reciprocal cycle did not clear the reviewed all-member final-staged barrier.'}
    # Exercise the actual cutover consumer: it must bind the local applied package to a complete final-staged group round.
    $groupIndexPath=Join-Path $Root 'group-index.json';$groupIndex=[pscustomobject][ordered]@{GroupPlanPath=[IO.Path]::GetFullPath($groupPath);GroupPlanHash=$created.SHA256;Receipts=$receipts};Write-WsmJson $groupIndexPath $groupIndex;$groupIndexHash=(Get-FileHash -LiteralPath $groupIndexPath).Hash
    $localPackage=$script:coordinationPackages[$plans[0].ManifestPath];$cutoverDependencies=Read-WsmCutoverDependencies $localPackage $plans[0].ManifestHash '' '' $groupIndexPath $groupIndexHash
    if(-not $cutoverDependencies.GroupCoordination.Barrier.Passed -or $cutoverDependencies.GroupCoordination.Barrier.MemberCount -ne 2 -or $cutoverDependencies.GroupCoordination.GroupId -cne $groupId){throw 'Cutover dependency consumer did not return the complete local final-staged group barrier.'}
    Assert-Throws {Read-WsmCutoverDependencies $localPackage ('0'*64) '' '' $groupIndexPath $groupIndexHash} 'local manifest hash differs from current final-staged group receipt'
    $wrongGenerationPackage=[pscustomobject]@{Valid=$true;Manifest=($localPackage.Manifest | ConvertTo-Json -Depth 20 | ConvertFrom-Json);Plan=$localPackage.Plan;PlanHash=$localPackage.PlanHash};$wrongGenerationPackage.Manifest.Generation++
    Assert-Throws {Read-WsmCutoverDependencies $wrongGenerationPackage $plans[0].ManifestHash '' '' $groupIndexPath $groupIndexHash} 'local package generation differs from final-staged group receipt'
    $badHashIndex=[pscustomobject]@{GroupPlanPath=$groupIndex.GroupPlanPath;GroupPlanHash=$groupIndex.GroupPlanHash;Receipts=@($groupIndex.Receipts)};$badHashIndex.Receipts[0]=[pscustomobject]@{Path=$groupIndex.Receipts[0].Path;SHA256=('0'*64)};$badHashIndexPath=Join-Path $Root 'group-index-bad-receipt-hash.json';Write-WsmJson $badHashIndexPath $badHashIndex
    Assert-Throws {Read-WsmCutoverDependencies $localPackage $plans[0].ManifestHash '' '' $badHashIndexPath (Get-FileHash $badHashIndexPath).Hash} 'group receipt hash differs from indexed independently supplied hash'
    $expiredReceipt=Read-WsmJson $receipts[0].Path;$expiredReceipt.FreezeExpiresUtc=[DateTime]::UtcNow.AddMinutes(-1).ToString('o');$expiredReceiptPath=Join-Path $Root 'expired-freeze-receipt.json';Write-WsmJson $expiredReceiptPath $expiredReceipt
    $expiredIndex=[pscustomobject]@{GroupPlanPath=$groupIndex.GroupPlanPath;GroupPlanHash=$groupIndex.GroupPlanHash;Receipts=@($groupIndex.Receipts)};$expiredIndex.Receipts[0]=[pscustomobject]@{Path=$expiredReceiptPath;SHA256=(Get-FileHash $expiredReceiptPath).Hash};$expiredIndexPath=Join-Path $Root 'group-index-expired-freeze.json';Write-WsmJson $expiredIndexPath $expiredIndex
    Assert-Throws {Read-WsmCutoverDependencies $localPackage $plans[0].ManifestHash '' '' $expiredIndexPath (Get-FileHash $expiredIndexPath).Hash} 'source freeze expired at local group cutover barrier'
    $activated=@();$rolledBack=@()
    foreach($p in $plans){$script:coordinationFingerprint=$p.Plan.Target.Fingerprint;$cutoverPath=Join-Path $Root ('cutover-'+$p.Plan.PairId+'.json');$cutover=Read-WsmJson $p.ResultPath;$cutover.Stage='Cutover';Write-WsmJson $cutoverPath $cutover;$cutoverHash=(Get-FileHash $cutoverPath).Hash;$activationPath=Join-Path $Root ('activation-'+$p.Plan.PairId+'.json');$activation=New-WsmConsistencyGroupReceipt -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -PairId $p.Plan.PairId -Stage Activated -PlanPath $p.Path -PlanHash $p.Hash -ManifestPath $p.ManifestPath -ManifestHash $p.ManifestHash -FreezePath $p.FreezePath -FreezeHash $p.FreezeHash -StageResultPath $cutoverPath -StageResultHash $cutoverHash -Path $activationPath;$activated+=@([pscustomobject]@{Path=$activationPath;SHA256=$activation.SHA256})
        $rollbackPath=Join-Path $Root ('rollback-'+$p.Plan.PairId+'.json');$rollbackRow=[pscustomobject][ordered]@{ItemId=$p.Plan.Items[0].ItemId;Adapter='Service';Outcome='RolledBack';Verification='LocalRollbackState';StateStatus='RolledBack';NativeReadbackVerified=$false;JournalHash=('c'*64)};$rollback=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='RollbackResult';BatchId=$batch;PairId=$p.Plan.PairId;SourceHostId=$p.Plan.Source.HostId;SourceFingerprint=$p.Plan.Source.Fingerprint;TargetHostId=$p.Plan.Target.HostId;TargetFingerprint=$p.Plan.Target.Fingerprint;ApprovalId=$p.Plan.ApprovalId;PlanHash=$p.Hash;ManifestHash=$p.ManifestHash;Generation=3;Status='RollbackEvidenceComplete';CompletionScope='AutoRollbackAndExplicitReadbackOrExternalAttestation';ItemResults=@($rollbackRow);DedicatedEvidencePath='';DedicatedEvidenceHash='';Owner='rollback owner';Evidence='fixture rollback';JournalHash=('c'*64);ProducedUtc=[DateTime]::UtcNow.ToString('o');Mode='IsolatedPilot';ProductionVerified=$false};Write-WsmJson $rollbackPath $rollback;$rollbackHash=(Get-FileHash $rollbackPath).Hash;$rollbackReceiptPath=Join-Path $Root ('rollback-receipt-'+$p.Plan.PairId+'.json');$rollbackReceipt=New-WsmConsistencyGroupReceipt -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -PairId $p.Plan.PairId -Stage RolledBack -PlanPath $p.Path -PlanHash $p.Hash -ManifestPath $p.ManifestPath -ManifestHash $p.ManifestHash -FreezePath $p.FreezePath -FreezeHash $p.FreezeHash -RollbackEvidencePath $rollbackPath -RollbackEvidenceHash $rollbackHash -Path $rollbackReceiptPath;$rolledBack+=@([pscustomobject]@{Path=$rollbackReceiptPath;SHA256=$rollbackReceipt.SHA256})
    }
    if(-not (Assert-WsmConsistencyGroupBarrier -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -Stage Activated -Receipts $activated -AnchorReceipts $receipts).Passed){throw 'All-member activation barrier failed.'}
    if(-not (Assert-WsmConsistencyGroupBarrier -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -Stage RolledBack -Receipts $rolledBack -AnchorReceipts $receipts).Passed){throw 'All-member rollback barrier failed.'}
    $alteredActivation=Read-WsmJson $activated[0].Path;$alteredActivation.Generation++;$alteredActivationPath=Join-Path $Root 'altered-activation.json';Write-WsmJson $alteredActivationPath $alteredActivation;$badActivation=@($activated);$badActivation[0]=[pscustomobject]@{Path=$alteredActivationPath;SHA256=(Get-FileHash $alteredActivationPath).Hash}
    Assert-Throws {Assert-WsmConsistencyGroupBarrier -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -Stage Activated -Receipts $badActivation -AnchorReceipts $receipts} 'activation generation differs from final-staged anchor'
    Assert-Throws {Assert-WsmConsistencyGroupBarrier -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -Stage FinalStaged -Receipts @($receipts[0])} 'missing member'
    $badHash=@($receipts);$badHash[1]=[pscustomobject]@{Path=$receipts[1].Path;SHA256=('0'*64)}
    Assert-Throws {Assert-WsmConsistencyGroupBarrier -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -Stage FinalStaged -Receipts $badHash} 'receipt hash mismatch'
    $stale=Read-WsmJson $receipts[0].Path;$stale.ProducedUtc=[DateTime]::UtcNow.AddHours(-30).ToString('o');Write-WsmJson $receipts[0].Path $stale;$receipts[0].SHA256=(Get-FileHash $receipts[0].Path).Hash
    Assert-Throws {Assert-WsmConsistencyGroupBarrier -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -Stage FinalStaged -Receipts $receipts} 'stale group receipt'
    # Recreate the first valid receipt, then supply a stage result with the wrong payload generation.
    $p=$plans[0];$script:coordinationFingerprint=$p.Plan.Target.Fingerprint;$good=New-WsmConsistencyGroupReceipt -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -PairId $p.Plan.PairId -Stage FinalStaged -PlanPath $p.Path -PlanHash $p.Hash -ManifestPath $p.ManifestPath -ManifestHash $p.ManifestHash -FreezePath $p.FreezePath -FreezeHash $p.FreezeHash -StageResultPath $p.ResultPath -StageResultHash $p.ResultHash -Path $receipts[0].Path;$receipts[0].SHA256=$good.SHA256
    $expired=Read-WsmJson $receipts[0].Path;$expired.FreezeExpiresUtc=[DateTime]::UtcNow.AddMinutes(-1).ToString('o');Write-WsmJson $receipts[0].Path $expired;$receipts[0].SHA256=(Get-FileHash $receipts[0].Path).Hash
    Assert-Throws {Assert-WsmConsistencyGroupBarrier -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -Stage FinalStaged -Receipts $receipts} 'source freeze expired before barrier'
    $good=New-WsmConsistencyGroupReceipt -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -PairId $p.Plan.PairId -Stage FinalStaged -PlanPath $p.Path -PlanHash $p.Hash -ManifestPath $p.ManifestPath -ManifestHash $p.ManifestHash -FreezePath $p.FreezePath -FreezeHash $p.FreezeHash -StageResultPath $p.ResultPath -StageResultHash $p.ResultHash -Path $receipts[0].Path;$receipts[0].SHA256=$good.SHA256
    $staleEvidence=Read-WsmJson $receipts[0].Path;$staleEvidence.StageResultProducedUtc=[DateTime]::UtcNow.AddHours(-30).ToString('o');Write-WsmJson $receipts[0].Path $staleEvidence;$receipts[0].SHA256=(Get-FileHash $receipts[0].Path).Hash
    Assert-Throws {Assert-WsmConsistencyGroupBarrier -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -Stage FinalStaged -Receipts $receipts} 'underlying staged validation stale'
    $good=New-WsmConsistencyGroupReceipt -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -PairId $p.Plan.PairId -Stage FinalStaged -PlanPath $p.Path -PlanHash $p.Hash -ManifestPath $p.ManifestPath -ManifestHash $p.ManifestHash -FreezePath $p.FreezePath -FreezeHash $p.FreezeHash -StageResultPath $p.ResultPath -StageResultHash $p.ResultHash -Path $receipts[0].Path;$receipts[0].SHA256=$good.SHA256
    $wrong=Read-WsmJson $p.ResultPath;$wrong.PayloadGeneration=99;$wrongPath=Join-Path $Root 'wrong-generation.json';Write-WsmJson $wrongPath $wrong
    Assert-Throws {$script:coordinationFingerprint=$p.Plan.Target.Fingerprint;New-WsmConsistencyGroupReceipt -GroupPlanPath $groupPath -GroupPlanHash $created.SHA256 -PairId $p.Plan.PairId -Stage FinalStaged -PlanPath $p.Path -PlanHash $p.Hash -ManifestPath $p.ManifestPath -ManifestHash $p.ManifestHash -FreezePath $p.FreezePath -FreezeHash $p.FreezeHash -StageResultPath $wrongPath -StageResultHash (Get-FileHash $wrongPath).Hash -Path (Join-Path $Root 'rejected.json')} 'wrong generation result'
    # The rollback producer accounts honestly for mixed automatic, pre-existing, and dedicated-procedure items.
    $rollbackPair=[Guid]::NewGuid().ToString();$rollbackSource=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=('d'*64)};$rollbackTarget=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=('e'*64)};$rollbackApproval=[Guid]::NewGuid().ToString();$rollbackItems=@(
        [pscustomobject]@{ItemId=('a'*64);Decision='Include';MigrationSpec=[pscustomobject]@{Adapter='Service';Desired=[pscustomobject]@{Name='CreatedService'}}},
        [pscustomobject]@{ItemId=('b'*64);Decision='Include';MigrationSpec=[pscustomobject]@{Adapter='Service';Desired=[pscustomobject]@{Name='ExistingService'}}},
        [pscustomobject]@{ItemId=('c'*64);Decision='Include';MigrationSpec=[pscustomobject]@{Adapter='ManualWorkflow';Desired=[pscustomobject]@{Name='ManualProduct'}}},
        [pscustomobject]@{ItemId=('d'*64);Decision='Include';MigrationSpec=[pscustomobject]@{Adapter='WindowsFeature';Desired=[pscustomobject]@{Name='OptionalFeature'}}})
    $rollbackPlan=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='MigrationPlan';BatchId=$batch;PairId=$rollbackPair;ApprovalId=$rollbackApproval;Source=$rollbackSource;Target=$rollbackTarget;Mode='IsolatedPilot';Items=$rollbackItems}
    $rollbackManifestPath=Join-Path $Root 'rollback-mixed-manifest.json';$rollbackManifest=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='MigrationPackage';BatchId=$batch;PairId=$rollbackPair;ApprovalId=$rollbackApproval;PlanHash=('a'*64);Source=$rollbackSource;Target=$rollbackTarget;Generation=7;Final=$true;FreezeHash=('b'*64)};Write-WsmJson $rollbackManifestPath $rollbackManifest;$rollbackManifestHash=(Get-FileHash $rollbackManifestPath).Hash
    $existingActual=[pscustomobject]@{Exists=$true;Name='ExistingService';ConfigHash=('f'*64)};$existingHash=Get-WsmHashText ($existingActual | ConvertTo-Json -Depth 15 -Compress);$script:rollbackReadbacks['ExistingService']=[pscustomobject]@{Passed=$true;Actual=$existingActual}
    $script:rollbackFixtureState=[pscustomobject]@{ManifestHash=$rollbackManifestHash;Generation=7;Stage='ManualEvidenceRequired';PendingOperations=@();JournalHash=('c'*64);Items=@(
        [pscustomobject]@{ItemId=('a'*64);Status='RolledBack';CreatedByTool=$true;ActualHash=('1'*64)},
        [pscustomobject]@{ItemId=('b'*64);Status='Succeeded';CreatedByTool=$false;ActualHash=$existingHash},
        [pscustomobject]@{ItemId=('c'*64);Status='ManualEvidenceRequired';CreatedByTool=$false;ActualHash=''},
        [pscustomobject]@{ItemId=('d'*64);Status='Succeeded';CreatedByTool=$true;ActualHash=('2'*64)})}
    $script:coordinationPackages[$rollbackManifestPath]=[pscustomobject]@{Valid=$true;Manifest=$rollbackManifest;Plan=$rollbackPlan;PlanHash=$rollbackManifest.PlanHash};$script:coordinationFingerprint=$rollbackTarget.Fingerprint
    $exportPath=Join-Path $Root 'rollback-mixed-result.json';Assert-Throws {Export-WsmRollbackResult -ManifestPath $rollbackManifestPath -ExpectedHash $rollbackManifestHash -StateDirectory $Root -Owner 'review owner' -Evidence 'review ticket' -Path $exportPath} 'owner text cannot substitute for ManualWorkflow/WindowsFeature typed rollback evidence';if(Test-Path $exportPath){throw 'Rejected rollback evidence wrote a result file.'}
    $dedicatedPath=Join-Path $Root 'dedicated-rollback-evidence.json';$dedicated=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='DedicatedRollbackEvidence';BatchId=$batch;PairId=$rollbackPair;ApprovalId=$rollbackApproval;PlanHash=$rollbackManifest.PlanHash;ManifestHash=$rollbackManifestHash;Generation=7;TargetHostId=$rollbackTarget.HostId;TargetFingerprint=$rollbackTarget.Fingerprint;Owner='product rollback operator';Evidence='approved product rollback report';ProducedUtc=[DateTime]::UtcNow.ToString('o');Mode='IsolatedPilot';ProductionVerified=$false;Items=@(
        [pscustomobject]@{ItemId=('c'*64);Adapter='ManualWorkflow';Status='ProcedureReportedComplete';Procedure='Vendor restore playbook';Evidence='ticket MANUAL-21';Owner='product rollback operator';CompletedUtc=[DateTime]::UtcNow.ToString('o')},
        [pscustomobject]@{ItemId=('d'*64);Adapter='WindowsFeature';Status='ProcedureReportedComplete';Procedure='Dedicated feature removal and dependent-role review';Evidence='ticket FEATURE-22';Owner='server operator';CompletedUtc=[DateTime]::UtcNow.ToString('o')})};Write-WsmJson $dedicatedPath $dedicated;$dedicatedHash=(Get-FileHash $dedicatedPath).Hash
    $rollbackExport=Export-WsmRollbackResult -ManifestPath $rollbackManifestPath -ExpectedHash $rollbackManifestHash -StateDirectory $Root -Owner 'review owner' -Evidence 'rollback review' -Path $exportPath -DedicatedEvidencePath $dedicatedPath -DedicatedEvidenceHash $dedicatedHash
    $exported=$rollbackExport.Result;$manualOutcome=@($exported.ItemResults | Where-Object ItemId -EQ ('c'*64))[0];$featureOutcome=@($exported.ItemResults | Where-Object ItemId -EQ ('d'*64))[0];$existingOutcome=@($exported.ItemResults | Where-Object ItemId -EQ ('b'*64))[0]
    if($exported.Status -ne 'RollbackEvidenceComplete' -or $manualOutcome.Outcome -ne 'ExternalProcedureReportedComplete' -or $manualOutcome.NativeReadbackVerified -ne $false -or $manualOutcome.Limitation -notmatch 'did not execute or verify' -or $featureOutcome.Outcome -ne 'ExternalProcedureReportedComplete' -or $existingOutcome.Outcome -ne 'PreExistingUnchanged' -or $existingOutcome.Verification -ne 'LocalReadback'){throw 'Mixed rollback result misrepresented a manual/feature attestation or pre-existing readback.'}
    $dishonest=$exported.PSObject.Copy();$dishonestRows=@($exported.ItemResults);$manual=@($dishonestRows | Where-Object ItemId -EQ ('c'*64))[0];$manual.Outcome='PreExistingUnchanged';$manual.Verification='LocalReadback';$manual | Add-Member NoteProperty BeforeHash ('e'*64) -Force;$manual | Add-Member NoteProperty ActualHash ('e'*64) -Force;$manual | Add-Member NoteProperty ReadBackUtc (Get-WsmUtc) -Force;$dishonest.ItemResults=$dishonestRows
    Assert-Throws {Assert-WsmRollbackResultItemOutcomes $rollbackPlan $dishonest} 'ManualWorkflow cannot be presented as local native readback'
    $wrongExternal=$dedicated.PSObject.Copy();$wrongExternal.PairId=[Guid]::NewGuid().ToString();$wrongExternalPath=Join-Path $Root 'dedicated-rollback-wrong-pair.json';Write-WsmJson $wrongExternalPath $wrongExternal
    Assert-Throws {Export-WsmRollbackResult -ManifestPath $rollbackManifestPath -ExpectedHash $rollbackManifestHash -StateDirectory $Root -Owner 'review owner' -Evidence 'rollback review' -Path (Join-Path $Root 'wrong-external-output.json') -DedicatedEvidencePath $wrongExternalPath -DedicatedEvidenceHash (Get-FileHash $wrongExternalPath).Hash} 'dedicated evidence bound to another pair'
    $script:rollbackReadbacks['ExistingService']=[pscustomobject]@{Passed=$true;Actual=[pscustomobject]@{Exists=$true;Name='ExistingService';ConfigHash=('9'*64)}}
    Assert-Throws {Export-WsmRollbackResult -ManifestPath $rollbackManifestPath -ExpectedHash $rollbackManifestHash -StateDirectory $Root -Owner 'review owner' -Evidence 'rollback review' -Path (Join-Path $Root 'drift-output.json') -DedicatedEvidencePath $dedicatedPath -DedicatedEvidenceHash $dedicatedHash} 'pre-existing configuration changed since the original readback'
    Write-Host 'PASS: group cutover consumer accepts complete all-member final-staged evidence and rejects local manifest/generation/hash/expiry drift; mixed rollback output distinguishes native rollback, unchanged local readback, and bounded typed external attestations.'
} $root
