# Contract-level tests for externally performed readiness proof. These fixtures do not claim server or business qualification.
#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
. (Join-Path $PSScriptRoot 'ExternalReadinessEvidenceFixtures.ps1')
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-external-gates-'+[Guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($root)
try {
    $pair=[Guid]::NewGuid().ToString('D');$source='a'*64;$target='b'*64;$planHash='c'*64;$manifestHash='d'*64;$tool='e'*64
    $package=[pscustomobject]@{Manifest=[pscustomobject]@{ToolVersion='0.4.0';PairId=$pair;Source=[pscustomobject]@{Fingerprint=$source};Target=[pscustomobject]@{Fingerprint=$target};PlanHash=$planHash};Plan=[pscustomobject]@{ToolVersion='0.4.0';ToolFingerprint=$tool};SHA256=$manifestHash}
    $cutoverRefs=@(New-WsmCutoverEvidenceFixtureReferences -Package $package -Root $root)
    if($cutoverRefs.Count -ne 5){throw 'Cutover fixture did not create every separate source/fencing/isolation/network-owner proof.'}
    $missingBlocked=$false;$missingError='';$incompleteRefs=@($cutoverRefs | Select-Object -First 4);try{& $module {param($Refs,$Pkg) Assert-WsmExternalReadinessReferences -References $Refs -Package $Pkg -RequiredChecks @('SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval')|Out-Null} $incompleteRefs $package}catch{$missingError=$_.Exception.Message;$missingBlocked=$true};if(-not $missingBlocked){throw ('Missing cutover external proof was accepted. Refs='+$incompleteRefs.Count+' Error='+$missingError)}
    $validated=& $module {param($Refs,$Pkg) Assert-WsmExternalReadinessReferences -References $Refs -Package $Pkg -RequiredChecks @('SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval')} $cutoverRefs $package
    if(@($validated | Where-Object {$_.Passed -ne $true}).Count){throw 'Typed mocked cutover external facts did not validate.'}
    $freezePlan=[pscustomobject]@{ToolVersion=$package.Manifest.ToolVersion;PairId=$pair;ApprovalId=[Guid]::NewGuid().ToString();Source=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=$source};Target=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=$target};ToolFingerprint=$tool};$freezeProof=New-WsmSourceFreezeEvidenceFixture -Plan $freezePlan -PlanHash $planHash -Root $root -Owner 'Fixture independent owner';$freezeAttestation=& $module {param($Ref,$Plan,$PlanHash,$Epoch)Assert-WsmSourceFreezeEvidence $Ref.Path $Ref.SHA256 $Plan $PlanHash $Epoch} $freezeProof $freezePlan $planHash $freezeProof.FreezeEpoch;if($freezeAttestation.WriterSetHash -ne $freezeProof.Evidence.WriterSetHash){throw 'Source freeze writer inventory attestation did not validate.'};$epochBlocked=$false;try{& $module {param($Ref,$Plan,$PlanHash,$Epoch)Assert-WsmSourceFreezeEvidence $Ref.Path $Ref.SHA256 $Plan $PlanHash $Epoch|Out-Null} $freezeProof $freezePlan $planHash ([Guid]::NewGuid().ToString())}catch{$epochBlocked=$true};if(-not $epochBlocked){throw 'SourceFreezeReady evidence accepted a different freeze epoch.'}
    $freezeEnvelope=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='SourceFreeze';FreezeId=[Guid]::NewGuid().ToString();PairId=$pair;ApprovalId=$freezePlan.ApprovalId;PlanHash=$planHash;SourceHostId=$freezePlan.Source.HostId;SourceFingerprint=$source;TargetFingerprint=$target;FreezeEpoch=$freezeProof.FreezeEpoch;SourceFreezeEvidence=$freezeAttestation;Owner='Fixture independent owner';Evidence='fixture only';Acknowledgement='OWNER-CONFIRMED-QUIESCENCE';ProducedUtc=[DateTime]::UtcNow.ToString('o');ExpiresUtc=[DateTime]::UtcNow.AddHours(1).ToString('o');QuiescedSettingsHashes=@()};$freezeEnvelopePath=Join-Path $root 'freeze.json';[IO.File]::WriteAllText($freezeEnvelopePath,($freezeEnvelope|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)));$freezeEnvelopeHash=(Get-FileHash -LiteralPath $freezeEnvelopePath).Hash;& $module {param($Path,$Hash,$Plan,$PlanHash)Read-WsmFreezeRecord $Path $Hash $Plan $PlanHash|Out-Null} $freezeEnvelopePath $freezeEnvelopeHash $freezePlan $planHash;if($freezeEnvelope.SourceFreezeEvidence.PSObject.Properties['Path']){throw 'Transferred freeze attestation leaked a source evidence path.'};$badFreeze=$freezeEnvelope|ConvertTo-Json -Depth 20|ConvertFrom-Json;$badFreeze.SourceFreezeEvidence.FreezeEpoch=[Guid]::NewGuid().ToString();$badFreezePath=Join-Path $root 'bad-freeze.json';[IO.File]::WriteAllText($badFreezePath,($badFreeze|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)));$badFreezeHash=(Get-FileHash $badFreezePath).Hash;$badAttestationBlocked=$false;try{& $module {param($Path,$Hash,$Plan,$PlanHash)Read-WsmFreezeRecord $Path $Hash $Plan $PlanHash|Out-Null} $badFreezePath $badFreezeHash $freezePlan $planHash}catch{$badAttestationBlocked=$true};if(-not $badAttestationBlocked){throw 'Transferred freeze did not bind its evidence epoch.'}
    $attemptId=[Guid]::NewGuid().ToString('D');$attemptHash='f'*64;$resumeAttempt=[pscustomobject]@{State=[pscustomobject]@{AttemptId=$attemptId}};$resumeProof=New-WsmSourceResumeEvidenceFixture -Plan $freezePlan -PlanHash $planHash -AttemptId $attemptId -AttemptHash $attemptHash -Root $root -Owner 'Fixture independent owner';$resumeAttestation=& $module {param($Ref,$Plan,$PlanHash,$Attempt,$AttemptHash,$Owner)Assert-WsmSourceResumeEvidence $Ref.Path $Ref.SHA256 $Plan $PlanHash $Attempt $AttemptHash $Owner} $resumeProof $freezePlan $planHash $resumeAttempt $attemptHash 'Fixture independent owner';if(-not $resumeAttestation.Passed){throw 'Source resume fixture external proof did not validate.'};$attemptBlocked=$false;try{& $module {param($Ref,$Plan,$PlanHash,$Attempt,$AttemptHash,$Owner)Assert-WsmSourceResumeEvidence $Ref.Path $Ref.SHA256 $Plan $PlanHash $Attempt $AttemptHash $Owner|Out-Null} $resumeProof $freezePlan $planHash $resumeAttempt ('a'*64) 'Fixture independent owner'}catch{$attemptBlocked=$true};if(-not $attemptBlocked){throw 'SourceResumeReady proof accepted a different attempt hash.'}
    $wrong=New-WsmExternalReadinessEvidenceFixture -Package $package -Root $root -Check SourceIdentityReleased -BindingOverride ([Guid]::NewGuid().ToString('D'));$wrongBlocked=$false;try{& $module {param($Ref,$Pkg) Assert-WsmExternalReadinessEvidence -Path $Ref.Path -SHA256 $Ref.SHA256 -Package $Pkg -Check SourceIdentityReleased|Out-Null} $wrong $package}catch{$wrongBlocked=$_.Exception.Message -match 'different pair'};if(-not $wrongBlocked){throw 'Wrong-pair evidence was accepted.'}
    $phase=New-WsmExternalReadinessEvidenceFixture -Package $package -Root $root -Check RollbackReconcile;$phase.Evidence.Phase='CutoverReady';$phaseText=$phase.Evidence|ConvertTo-Json -Depth 20;$phaseBytes=(New-Object Text.UTF8Encoding($false)).GetBytes($phaseText+[Environment]::NewLine);[IO.File]::WriteAllBytes($phase.Path,$phaseBytes);$phase.SHA256=(Get-FileHash -LiteralPath $phase.Path -Algorithm SHA256).Hash.ToLowerInvariant();$phaseBlocked=$false;try{& $module {param($Ref,$Pkg) Assert-WsmExternalReadinessEvidence -Path $Ref.Path -SHA256 $Ref.SHA256 -Package $Pkg -Check RollbackReconcile|Out-Null} $phase $package}catch{$phaseBlocked=$_.Exception.Message -match 'phase'};if(-not $phaseBlocked){throw 'Wrong-phase rollback evidence was accepted.'}
    $expired=New-WsmExternalReadinessEvidenceFixture -Package $package -Root $root -Check NetworkOwnerApproval -ExpiryOverride ([DateTime]::UtcNow.AddMinutes(-1).ToString('o'));$expiredBlocked=$false;try{& $module {param($Ref,$Pkg) Assert-WsmExternalReadinessEvidence -Path $Ref.Path -SHA256 $Ref.SHA256 -Package $Pkg -Check NetworkOwnerApproval|Out-Null} $expired $package}catch{$expiredBlocked=$_.Exception.Message -match 'expired'};if(-not $expiredBlocked){throw 'Expired external evidence was accepted.'}
    $wrongTool=New-WsmExternalReadinessEvidenceFixture -Package $package -Root $root -Check DNS;$wrongTool.Evidence.ToolFingerprint='f'*64;$wrongToolBytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($wrongTool.Evidence|ConvertTo-Json -Depth 20)+[Environment]::NewLine);[IO.File]::WriteAllBytes($wrongTool.Path,$wrongToolBytes);$wrongTool.SHA256=(Get-FileHash -LiteralPath $wrongTool.Path -Algorithm SHA256).Hash.ToLowerInvariant();$toolBlocked=$false;try{& $module {param($Ref,$Pkg) Assert-WsmExternalReadinessEvidence -Path $Ref.Path -SHA256 $Ref.SHA256 -Package $Pkg -Check DNS|Out-Null} $wrongTool $package}catch{$toolBlocked=$_.Exception.Message -match 'different pair'};if(-not $toolBlocked){throw 'Wrong-tool evidence was accepted.'}
    $payload=New-WsmExternalReadinessEvidenceFixture -Package $package -Root $root -Check BusinessStaged -ItemId ([Guid]::NewGuid().ToString('D'));[IO.File]::AppendAllText($payload.Evidence.PayloadArtifact.Path,'tampered');$payloadBlocked=$false;try{& $module {param($Ref,$Pkg) Assert-WsmExternalReadinessEvidence -Path $Ref.Path -SHA256 $Ref.SHA256 -Package $Pkg -Check BusinessStaged -ItemId $Ref.ItemId|Out-Null} $payload $package}catch{$payloadBlocked=$_.Exception.Message -match 'payload artifact'};if(-not $payloadBlocked){throw 'Changed payload artifact was accepted.'}
    $legacyState=[pscustomobject]@{PairId=$pair;TargetFingerprint=$target;PlanHash=$planHash;ManifestHash=$manifestHash;Evidence=@([pscustomobject]@{ItemId='';Check='RollbackReconcile';Passed=$true;ManifestHash=$manifestHash;ExpiresUtc=[DateTime]::UtcNow.AddHours(1).ToString('o');Evidence='legacy text claim'})};$legacyPassed=& $module {param($State) Test-WsmEvidence $State '' RollbackReconcile $State.ManifestHash} $legacyState;if($legacyPassed){throw 'Legacy text-only rollback claim satisfied the reconciliation gate.'}
    $notApplicable=New-WsmExternalReadinessEvidenceFixture -Package $package -Root $root -Check ExternalNetworkFencing;$notApplicable.Evidence.TypedResults.Facts.DhcpFenced='NotApplicable';$notApplicableBytes=(New-Object Text.UTF8Encoding($false)).GetBytes(($notApplicable.Evidence|ConvertTo-Json -Depth 20)+[Environment]::NewLine);[IO.File]::WriteAllBytes($notApplicable.Path,$notApplicableBytes);$notApplicable.SHA256=(Get-FileHash -LiteralPath $notApplicable.Path -Algorithm SHA256).Hash.ToLowerInvariant();$naBlocked=$false;try{& $module {param($Ref,$Pkg) Assert-WsmExternalReadinessEvidence -Path $Ref.Path -SHA256 $Ref.SHA256 -Package $Pkg -Check ExternalNetworkFencing|Out-Null} $notApplicable $package}catch{$naBlocked=$_.Exception.Message -match 'specific owner reason'};if(-not $naBlocked){throw 'NotApplicable without an owner reason was accepted.'}
    Write-Host 'PASS: typed external evidence requires exact pair/target/tool/plan/manifest/phase/check bindings, live artifact hashes, current expiry and nonempty scoped results; missing, tampered, wrong-phase, wrong-tool and text-only rollback evidence block. No real server or enterprise proof was exercised.'
} finally {if([IO.Directory]::Exists($root)){Remove-Item -LiteralPath $root -Recurse -Force}}
