#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
& $module {
    . (Join-Path $PSScriptRoot '..\src\Qualification.ps1')
    function New-FixtureEvidence([string]$Type,[DateTime]$Expires) { $observed=[DateTime]::UtcNow.AddMinutes(-1);if($Expires -le $observed){$observed=$Expires.AddDays(-2)};[pscustomobject]@{EvidenceId=[Guid]::NewGuid().ToString();Type=$Type;Owner='fixture reviewer';Reference=('fixture://evidence/'+$Type);ObservedUtc=$observed.ToString('o');ExpiresUtc=$Expires.ToString('o');SHA256=('a'*64)} }
    function New-FixtureTuple { [pscustomobject][ordered]@{ToolFingerprint=(Get-WsmToolFingerprint);Adapter='Service';AdapterFingerprint=('2'*64);Source=[pscustomobject][ordered]@{Family='WindowsServer';Version='2016';Build='14393';Edition='Standard';Architecture='x64';InstallationType='ServerWithDesktopExperience'};Target=[pscustomobject][ordered]@{Family='WindowsServer';Version='2025';Build='26100';Edition='Standard';Architecture='x64';InstallationType='ServerCore'};Product='ExampleService';ProductVersion='4.2.1'} }
    function New-FixtureRequirements { [pscustomobject]@{Permissions='Local administrator and module access';ConsistencyMethod='Owner-approved product consistency';RebootBehavior='Post-reboot verification';SideEffects='Consumers remain disabled until activation';RollbackLevel='Owned configuration restored; data reconciliation remains manual'} }
    $root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-qualification-'+[Guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($root);$path=Join-Path $root 'qualification.json'
    try {
        $tuple=New-FixtureTuple;$legacyTuple=New-FixtureTuple;$key=Get-WsmQualificationRecordKey -Tuple $tuple
        $oldTuple=New-FixtureTuple;$oldTuple.Source.PSObject.Properties.Remove('InstallationType');$oldTuple.Target.PSObject.Properties.Remove('InstallationType');$oldCanonical=[ordered]@{ToolFingerprint=$oldTuple.ToolFingerprint.ToLowerInvariant();Adapter=[string]$oldTuple.Adapter;AdapterFingerprint=$oldTuple.AdapterFingerprint.ToLowerInvariant();Source=[ordered]@{Family=$oldTuple.Source.Family;Version=$oldTuple.Source.Version;Build=$oldTuple.Source.Build;Edition=$oldTuple.Source.Edition;Architecture=$oldTuple.Source.Architecture};Target=[ordered]@{Family=$oldTuple.Target.Family;Version=$oldTuple.Target.Version;Build=$oldTuple.Target.Build;Edition=$oldTuple.Target.Edition;Architecture=$oldTuple.Target.Architecture};Product=[string]$oldTuple.Product;ProductVersion=[string]$oldTuple.ProductVersion};if((Get-WsmQualificationKey $oldTuple) -cne (Get-WsmHashText ($oldCanonical | ConvertTo-Json -Depth 8 -Compress))){throw 'Legacy qualification tuple key changed.'}
        $reordered=[pscustomobject]@{ProductVersion=$tuple.ProductVersion;Product=$tuple.Product;Target=$tuple.Target;Source=$tuple.Source;AdapterFingerprint=$tuple.AdapterFingerprint;Adapter=$tuple.Adapter;ToolFingerprint=$tuple.ToolFingerprint};if((Get-WsmQualificationRecordKey -Tuple $reordered) -cne $key){throw 'Tuple property ordering changed its qualification key.'}
        $changed=New-FixtureTuple;$changed.Target.InstallationType='ServerWithDesktopExperience';if((Get-WsmQualificationRecordKey -Tuple $changed) -ceq $key){throw 'InstallationType was omitted from qualification scope.'}
        $changedBuild=New-FixtureTuple;$changedBuild.Source.Build='99999';if((Get-WsmQualificationRecordKey -Tuple $changedBuild) -ceq $key){throw 'Source build was omitted from exact qualification scope.'}
        $oracle=New-FixtureTuple;$oracle | Add-Member NoteProperty OracleProvider ([pscustomobject]@{Product='Oracle Client';Version='19.24';Architecture='x64';Context='OracleHome=C:\Oracle\19'}) -Force;$oracle | Add-Member NoteProperty OracleConsumer ([pscustomobject]@{Product='IIS App';Version='4.2.1';Architecture='x64';Context='AppPool=orders'}) -Force;$oracleKey=Get-WsmQualificationRecordKey $oracle;$oracle2=$oracle | ConvertTo-Json -Depth 10 | ConvertFrom-Json;$oracle2.OracleConsumer.Context='AppPool=billing';if((Get-WsmQualificationRecordKey $oracle2) -ceq $oracleKey){throw 'Oracle provider/consumer context was omitted from exact qualification scope.'}
        $future=[DateTime]::UtcNow.AddDays(30);$pilot=New-WsmQualificationRecord -Tuple $legacyTuple -ReleaseDecision PilotOnly -Requirements (New-FixtureRequirements) -Evidence @((New-FixtureEvidence Fixture $future)) -CreatedBy 'fixture reviewer';$added=Add-WsmQualification -Path $path -Record $pilot;if($added.QualificationId -cne $pilot.QualificationId){throw 'Pilot record was not added.'}
        $resolved=Resolve-WsmProductionQualification -Path $path -Tuple $legacyTuple;if($resolved.Qualified -or -not ($resolved.Problems -contains 'Release decision is not ProductionAccepted.')){throw 'Pilot-only qualification unexpectedly qualified production.'}
        $blocked=$false;try{New-WsmQualificationRecord -Tuple $tuple -ReleaseDecision ProductionAccepted -Requirements (New-FixtureRequirements) -Evidence @((New-FixtureEvidence ServerLab $future),(New-FixtureEvidence IsolatedPilot $future),(New-FixtureEvidence ProductionAcceptance $future)) -CreatedBy 'self-declared owner' | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Self-declared production record bypassed independent signature workflow.'}
        $policyPath=Join-Path $root 'trust-policy.json';$policy=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='EnterpriseTrustPolicy';ExpiresUtc=[DateTime]::UtcNow.AddDays(10).ToString('o');RevocationEvidenceUpdatedUtc=[DateTime]::UtcNow.AddMinutes(-10).ToString('o');RevocationMaxAgeHours=24;Roles=@([pscustomobject]@{Name='QualificationApprover';SignerThumbprints=@(('1'*40));RootThumbprints=@(('2'*40))},[pscustomobject]@{Name='ReleaseSigner';SignerThumbprints=@(('3'*40));RootThumbprints=@(('2'*40))});RevokedThumbprints=@();QualificationRevocations=@()};Write-WsmJson $policyPath $policy;$policyHash=(Get-FileHash $policyPath).Hash
        Assert-WsmQualificationRevocationPolicy $policyPath $policyHash $pilot.QualificationId
        $policy.QualificationRevocations=@([pscustomobject]@{QualificationId=$pilot.QualificationId;Owner='enterprise revocation owner';Reference='change:qualification-revoked';RevokedUtc=[DateTime]::UtcNow.AddMinutes(-1).ToString('o')});Write-WsmJson $policyPath $policy;$revokedPolicyHash=(Get-FileHash -LiteralPath $policyPath).Hash
        $policyRevoked=$false;try{Assert-WsmQualificationRevocationPolicy $policyPath $revokedPolicyHash $pilot.QualificationId}catch{$policyRevoked=$_.Exception.Message -match 'independently pinned enterprise policy'};if(-not $policyRevoked){throw 'Enterprise revocation ledger failed to deny a qualification independently of the local registry.'}
        $policy.QualificationRevocations=@();Write-WsmJson $policyPath $policy;$removalBlocked=$false;try{Assert-WsmQualificationRevocationPolicy $policyPath $revokedPolicyHash $pilot.QualificationId}catch{$removalBlocked=$_.Exception.Message -match 'Trusted SHA256 mismatch'};if(-not $removalBlocked){throw 'Removing enterprise revocation row bypassed the pinned policy hash.'};$policyHash=(Get-FileHash -LiteralPath $policyPath).Hash
        Assert-WsmCmsAlgorithmPolicy -DigestOid '2.16.840.1.101.3.4.2.1' -SignatureOid '1.2.840.113549.1.1.11' -KeyAlgorithm RSA -KeySize 2048
        Assert-WsmCmsAlgorithmPolicy -DigestOid '2.16.840.1.101.3.4.2.3' -SignatureOid '1.2.840.10045.4.3.4' -KeyAlgorithm ECDSA -KeySize 256
        foreach($weak in @(@{Digest='1.3.14.3.2.26';Signature='1.2.840.113549.1.1.5';Key='RSA';Size=2048},@{Digest='2.16.840.1.101.3.4.2.1';Signature='1.2.840.113549.1.1.11';Key='RSA';Size=1024},@{Digest='2.16.840.1.101.3.4.2.1';Signature='1.2.840.10045.4.3.2';Key='ECDSA';Size=224},@{Digest='2.16.840.1.101.3.4.2.3';Signature='1.2.840.10045.4.3.2';Key='ECDSA';Size=256})){$algorithmBlocked=$false;try{Assert-WsmCmsAlgorithmPolicy -DigestOid $weak.Digest -SignatureOid $weak.Signature -KeyAlgorithm $weak.Key -KeySize $weak.Size}catch{$algorithmBlocked=$true};if(-not $algorithmBlocked){throw 'Weak or mismatched CMS algorithm policy input was accepted.'}}
        if($env:OS -eq 'Windows_NT'){
            Initialize-WsmCrypt32OfflineChainVerifier
            $rsa=[Security.Cryptography.RSA]::Create(2048)
            $leafRequest=[Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=WSM Offline Chain Negative Fixture',$rsa,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)
            $leafRequest.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509KeyUsageExtension]::new([Security.Cryptography.X509Certificates.X509KeyUsageFlags]::DigitalSignature,$true))
            $leaf=$leafRequest.CreateSelfSigned([DateTimeOffset]::UtcNow.AddDays(-1),[DateTimeOffset]::UtcNow.AddDays(1))
            try {
                if([long][WsmCrypt32OfflineChainVerifier]::RequiredFlags -ne 3221233924L){throw 'Crypt32 chain helper omitted a required cache-only/AIA/auth-root/revocation flag.'}
                [WsmCrypt32OfflineChainVerifier]::ValidateCertificatePolicy($leaf.RawData)
                $weakRsa=[Security.Cryptography.RSA]::Create(1024)
                try {$weakRequest=[Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=WSM Weak Chain Fixture',$weakRsa,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1);$weakLeaf=$weakRequest.CreateSelfSigned([DateTimeOffset]::UtcNow.AddDays(-1),[DateTimeOffset]::UtcNow.AddDays(1));try{$weakFailure='';try{[WsmCrypt32OfflineChainVerifier]::ValidateCertificatePolicy($weakLeaf.RawData)}catch{$weakFailure=$_.Exception.Message};if($weakFailure -notmatch 'below 2048 bits'){throw ('Weak actual chain certificate was not rejected by key policy: '+$weakFailure)}}finally{$weakLeaf.Dispose()}}finally{$weakRsa.Dispose()}
                $nativeBlocked=$false;try{Get-WsmCrypt32OfflineChainRoot -Certificate $leaf | Out-Null}catch{$nativeBlocked=$true};if(-not $nativeBlocked){throw 'Untrusted native test leaf passed cache-only chain verification.'}
                Add-Type -AssemblyName System.Security -ErrorAction Stop;$payload=[Text.Encoding]::UTF8.GetBytes('detached CMS signer fixture payload');$contentInfo=[Security.Cryptography.Pkcs.ContentInfo]::new($payload);$cms=[Security.Cryptography.Pkcs.SignedCms]::new($contentInfo,$true);$cmsSigner=[Security.Cryptography.Pkcs.CmsSigner]::new($leaf);$cmsSigner.DigestAlgorithm=[Security.Cryptography.Oid]::new('2.16.840.1.101.3.4.2.1');$cms.ComputeSignature($cmsSigner);$cmsBytes=$cms.Encode()
                $decoded=[Security.Cryptography.Pkcs.SignedCms]::new($contentInfo,$true);$decoded.Decode($cmsBytes);if($decoded.SignerInfos.Count -ne 1 -or $decoded.SignerInfos[0].DigestAlgorithm.Value -cne '2.16.840.1.101.3.4.2.1'){throw 'Generated detached CMS fixture did not carry the intended SHA-256 signer.'}
                $policy.Roles | Where-Object Name -CEQ 'ReleaseSigner' | ForEach-Object {$_.SignerThumbprints=@($leaf.Thumbprint);$_.RootThumbprints=@($leaf.Thumbprint)};Write-WsmJson $policyPath $policy;$policyHash=(Get-FileHash -LiteralPath $policyPath).Hash
                $cmsFailure='';try{Assert-WsmDetachedCmsSignature -ContentBytes $payload -SignatureBytes $cmsBytes -TrustPolicyPath $policyPath -TrustPolicyHash $policyHash -Role ReleaseSigner | Out-Null}catch{$cmsFailure=$_.Exception.Message}
                if($cmsFailure -notmatch 'Offline signer chain/revocation check failed|trust error flags|Crypt32 could not build a cache-only certificate chain'){throw ('Generated detached CMS fixture did not reach the offline chain gate: '+$cmsFailure)}
                $originalRevocation=$policy.RevocationEvidenceUpdatedUtc;$policy.RevocationEvidenceUpdatedUtc=[DateTime]::UtcNow.AddDays(5).ToString('o');Write-WsmJson $policyPath $policy
                $futureFailure='';try{Assert-WsmDetachedCmsSignature -ContentBytes $payload -SignatureBytes $cmsBytes -TrustPolicyPath $policyPath -TrustPolicyHash (Get-FileHash $policyPath).Hash -Role ReleaseSigner | Out-Null}catch{$futureFailure=$_.Exception.Message}
                if($futureFailure -notmatch 'revocation evidence is missing, invalid, or stale'){throw ('Future revocation evidence bypassed the freshness gate: '+$futureFailure)}
                $policy.RevocationEvidenceUpdatedUtc=$originalRevocation;Write-WsmJson $policyPath $policy;$policyHash=(Get-FileHash $policyPath).Hash
            } finally {$leaf.Dispose();$rsa.Dispose()}
        }
        $signaturePath=Join-Path $root 'invalid.p7s';[IO.File]::WriteAllBytes($signaturePath,[Text.Encoding]::UTF8.GetBytes('not a CMS signature'));$sigHash=(Get-FileHash $signaturePath).Hash
        $releasePath=Join-Path $root 'tool-release.zip';$release=Export-WsmToolRelease -Path $releasePath;$releaseProjection=Get-WsmReleaseArchiveProjection $releasePath;if($releaseProjection.ToolFingerprint -cne $release.ToolFingerprint -or $releaseProjection.FileCount -lt 1){throw 'Exported release did not pass exact manifest/payload readback.'};$releaseHash=(Get-FileHash $releasePath).Hash
        foreach($docPath in @('docs/MIGRATION-3-PLAN.md','docs/archive/README.md','docs/archive/MIGRATION-1-PLAN.md','docs/archive/MIGRATION-2-PLAN.md','docs/archive/MIGRATION-2-REVIEW.md','docs/archive/MIGRATION-2-VERIFICATION.md')){if($docPath -cnotin @($releaseProjection.Index.Files.Path)){throw ('Offline release is missing current or archived migration documentation: '+$docPath)}}
        $tuple | Add-Member NoteProperty ReleaseArtifact ([pscustomobject]@{ArchiveSHA256=$releaseHash.ToLowerInvariant();SignatureSHA256=$sigHash.ToLowerInvariant();ToolFingerprint=$release.ToolFingerprint;SignerThumbprint=('3'*40);TrustPolicyHash=$policyHash.ToLowerInvariant()}) -Force
        $fixtureRuntime=[pscustomobject]@{PowerShellVersion='5.1.14393.1000';Edition='Desktop';ProcessArchitecture='x64';LanguageMode='FullLanguage';CLRVersion='4.0.30319.42000';DotNetFrameworkRelease='528040'}
        $tuple | Add-Member NoteProperty Runtime ([pscustomobject]@{Source=$fixtureRuntime;Target=$fixtureRuntime})
        $runtimeKey=Get-WsmQualificationRecordKey $tuple
        $changedRuntime=ConvertFrom-WsmJson ($tuple | ConvertTo-Json -Depth 20 -Compress);$changedRuntime.Runtime.Target.DotNetFrameworkRelease='528049'
        if((Get-WsmQualificationRecordKey $changedRuntime) -ceq $runtimeKey){throw 'Runtime servicing drift did not change exact qualification scope.'}
        $changedRuntime.Runtime.Target.PowerShellVersion='7.5.0.0';$runtimeRejected=$false;try{Assert-WsmProductionRuntime $changedRuntime.Runtime}catch{$runtimeRejected=$true};if(-not $runtimeRejected){throw 'Unsupported production runtime was accepted.'}
        $requestPath=Join-Path $root 'signing-request.json';$request=New-WsmQualificationSigningRequest -Tuple $tuple -Requirements (New-FixtureRequirements) -Evidence @((New-FixtureEvidence ServerLab $future),(New-FixtureEvidence IsolatedPilot $future),(New-FixtureEvidence ProductionAcceptance $future)) -CreatedBy 'fixture reviewer' -Path $requestPath
        if($request.SigningContentSHA256 -cne $request.SHA256){throw 'Signing request did not bind the exact externally signed bytes.'}
        $blocked=$false;try{Complete-WsmQualificationSigningRequest -RequestPath $requestPath -RequestHash $request.SHA256 -SignaturePath $signaturePath -SignatureHash $sigHash -ReleasePath $releasePath -ReleaseHash $releaseHash -ReleaseSignaturePath $signaturePath -ReleaseSignatureHash $sigHash -TrustPolicyPath $policyPath -TrustPolicyHash $policyHash | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Invalid detached CMS release/qualification signatures passed signing.'}
        $blocked=$false;try{Test-WsmToolRelease -Path $requestPath -ExpectedHash $request.SHA256 -SignaturePath $signaturePath -ExpectedSignatureHash $sigHash -TrustPolicyPath $policyPath -TrustPolicyHash $policyHash | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Non-ZIP release artifact passed release verification.'}
        $blocked=$false;try{Test-WsmToolRelease -Path $releasePath -ExpectedHash $releaseHash -SignaturePath $signaturePath -ExpectedSignatureHash $sigHash -TrustPolicyPath $policyPath -TrustPolicyHash $policyHash | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Unsigned/invalidly signed exact release archive was accepted.'};$blocked=$false;try{Test-WsmToolRelease -Path $releasePath -ExpectedHash ('0'*64) -SignaturePath $signaturePath -ExpectedSignatureHash $sigHash -TrustPolicyPath $policyPath -TrustPolicyHash $policyHash | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Release archive accepted a mismatched independent byte hash.'};Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::Open($releasePath,[IO.Compression.ZipArchiveMode]::Update);try{[void]$zip.CreateEntry('unmanifested.txt')}finally{$zip.Dispose()};$blocked=$false;try{Get-WsmReleaseArchiveProjection $releasePath | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Unmanifested release bytes passed archive validation.'}
        $legacy=$pilot | ConvertTo-Json -Depth 20 | ConvertFrom-Json;$legacy.ReleaseDecision='ProductionAccepted';$legacy.Evidence=@((New-FixtureEvidence ServerLab $future),(New-FixtureEvidence IsolatedPilot $future),(New-FixtureEvidence ProductionAcceptance $future));$legacy.PSObject.Properties.Remove('Trust');$untrustedPath=Join-Path $root 'legacy-unsigned.json';Write-WsmJson $untrustedPath ([pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='QualificationRegistry';Records=@($legacy);Revocations=@()});$untrusted=Resolve-WsmProductionQualification -Path $untrustedPath -Tuple $legacyTuple;if($untrusted.Qualified -or -not ($untrusted.Problems -contains 'Independent enterprise trust policy was not supplied.')){throw 'Legacy unsigned qualification passed without an independent trust policy.'}
        $revoke=Revoke-WsmQualification -Path $path -QualificationId $pilot.QualificationId -Owner 'fixture revoker' -Reference 'fixture revocation';$revoked=Resolve-WsmProductionQualification -Path $path -Tuple $legacyTuple;if(-not $revoke.Revoked -or $revoked.Qualified -or -not ($revoked.Problems -contains 'Qualification was revoked.')){throw 'Revoked qualification remained eligible.'}
        $tupleFile=Join-Path $root 'tuples.json';Write-WsmJson $tupleFile ([pscustomobject]@{Tuples=@($legacyTuple)});$tupleHash=(Get-FileHash -LiteralPath $tupleFile).Hash;$matrix=Get-WsmQualificationMatrix -RegistryPath $path -TuplesPath $tupleFile -TuplesHash $tupleHash;if($matrix.Rows[0].QualificationRecorded -or $matrix.ProductionExecutionEnabled -or $matrix.Rows[0].ProductionExecutionEnabled){throw 'Pilot tuple was reported as qualified or execution was enabled.'}
        $expiredPath=Join-Path $root 'expired.json';$expired=New-WsmQualificationRecord -Tuple $tuple -ReleaseDecision PilotOnly -Requirements (New-FixtureRequirements) -Evidence @((New-FixtureEvidence Fixture ([DateTime]::UtcNow.AddSeconds(3)))) -CreatedBy 'fixture reviewer';Add-WsmQualification -Path $expiredPath -Record $expired | Out-Null;Start-Sleep -Seconds 4;$expiredResult=Resolve-WsmProductionQualification -Path $expiredPath -Tuple $tuple;if($expiredResult.Qualified -or -not @($expiredResult.Problems | Where-Object {$_ -like 'Evidence expired:*'}).Count){throw 'Expired evidence remained current.'}
        $badTuple=$tuple | ConvertTo-Json -Depth 12 | ConvertFrom-Json;$badTuple.Source.PSObject.Properties.Remove('InstallationType');$blocked=$false;try{New-WsmQualificationSigningRequest -Tuple $badTuple -Requirements (New-FixtureRequirements) -Evidence @((New-FixtureEvidence ServerLab $future),(New-FixtureEvidence IsolatedPilot $future),(New-FixtureEvidence ProductionAcceptance $future)) -CreatedBy 'fixture reviewer' -Path (Join-Path $root 'missing-install-type.json') | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Production signing request accepted missing InstallationType.'}
        Write-Host 'PASS: exact InstallationType and Oracle provider/consumer qualification scope, legacy lookup compatibility, unsigned/self-asserted evidence denial, signing-request byte binding, invalid signature/release rejection, expiry/revocation and execution lockout. No real enterprise trust material was available; production remains Blocked.'
    } finally {
        $resolvedRoot=[IO.Path]::GetFullPath($root);$tempRoot=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\')+'\';if(-not $resolvedRoot.StartsWith($tempRoot,[StringComparison]::OrdinalIgnoreCase) -or [IO.Path]::GetFileName($resolvedRoot) -notlike 'wsm-qualification-*'){throw 'Refusing cleanup outside the test-owned temporary directory.'};if([IO.Directory]::Exists($resolvedRoot)){[IO.Directory]::Delete($resolvedRoot,$true)}
    }
}
