#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-lab-validation-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
try {
    & $module {
        param($TestsPath,$Root)
        . (Join-Path $TestsPath '..\src\LabValidation.ps1')
        $script:labFingerprint=('a'*64);$script:labRole='Source';$script:labSecret='fixture-secret-must-not-appear';$script:labPackage=$null
        function script:Get-WsmMachineIdentity {[pscustomobject]@{Fingerprint=$script:labFingerprint;Name='fixture-host';OS='Windows Server Fixture';Version='10.0.fixture';IsServer=$true;Administrator=$true;Is64Bit=$true}}
        function script:Get-WsmToolFingerprint {'b'*64}
        function script:Get-WsmAdapterRequiredCommands {param([string]$Adapter) @()}
        function script:Get-WsmMigrationPackageFixture {
            $id='c'*64;$manual=[pscustomobject]@{Adapter='ManualWorkflow';BusinessChecks=@('do not serialize business text '+$script:labSecret)}
            $item=[pscustomobject]@{ItemId=$id;SettingsHash=('d'*64);Decision='Include';MigrationSpec=$manual}
            $plan=[pscustomobject]@{SchemaVersion=1;Items=@($item);ToolFingerprint=('b'*64);Source=[pscustomobject]@{Fingerprint=('a'*64)}}
            $manifest=[pscustomobject]@{PairId='11111111-1111-4111-8111-111111111111';Generation=1;PlanHash=('e'*64);Source=[pscustomobject]@{Fingerprint=('a'*64)};Target=[pscustomobject]@{Fingerprint=('f'*64)};InventoryRevision=2;DecisionRevision=3}
            [pscustomobject]@{Manifest=$manifest;Plan=$plan;SHA256=('9'*64);Root=$root}
        }
        function script:New-WsmLabEnvironmentConfirmationFixture($Manifest,[string]$Path,[string]$PairIdOverride='') {
            $pairId=$Manifest.PairId;if($PairIdOverride){$pairId=$PairIdOverride};$sourceHash=('5'*64)
            $projection=[pscustomobject][ordered]@{SchemaVersion=1;Kind='EnvironmentConfirmationProjection';PairId=$pairId;Source=[pscustomobject][ordered]@{HostId='33333333-3333-4333-8333-333333333333';Fingerprint=$Manifest.Source.Fingerprint;Name='fixture-source'};CaptureContext=[pscustomobject]@{};SourceInventoryProjectionHash=$sourceHash;InventoryRevision=$Manifest.InventoryRevision;InventoryHash=('6'*64);DecisionRevision=$Manifest.DecisionRevision;ToolVersion=$script:ToolVersion;Phase='Staged';PlanHash=$Manifest.PlanHash;GeneratedUtc=[DateTime]::UtcNow.ToString('o');TargetObservation=$null;TargetDiff=@();Coverage=@();Software=@();PreparationRequirements=@();RuntimeEvidence=@();OracleConfiguration=@();WindowsDecisions=@();Items=@();SpecialProducts=@();Unknowns=@();Requirements=@();ReadinessProjection=@();EvidenceReceipts=@();Blockers=@();OwnerHandoff=@();Counts=[pscustomobject]@{Items=0};ProductionQualified=$false;TrustStatement='Report only.'}
            $projectionHash=Get-WsmHashText (ConvertTo-Json -InputObject $projection -Depth 45 -Compress);$document=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='EnvironmentConfirmation';DocumentId=[Guid]::NewGuid().ToString('D');PairId=$pairId;InventoryRevision=$Manifest.InventoryRevision;DecisionRevision=$Manifest.DecisionRevision;TargetObservationRevision=0;SourceInventoryProjectionHash=$sourceHash;ReportProjectionHash=$projectionHash;GeneratedUtc=$projection.GeneratedUtc;Projection=$projection;Counts=$projection.Counts;Status='Generated';AuthoritativeDecisionInput=$false;ProductionQualified=$false}
            Write-WsmJson $Path $document;[pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant();DocumentId=$document.DocumentId}
        }
        function script:Test-WsmMigrationPackage {param([string]$ManifestPath,[string]$ExpectedHash)$script:labPackage}
        function script:Export-WsmInventory {
            param([string]$OutputDirectory,[switch]$DeepDiscovery)
            $inventory=[pscustomobject]@{Source=[pscustomobject]@{Fingerprint='a'*64};Items=@([pscustomobject]@{ItemId='c'*64;SettingsHash='d'*64;Status='Success';Settings=[pscustomobject]@{PrivateValue=$script:labSecret}})}
            $path=Join-Path $OutputDirectory 'fixture-inventory.json';$inventory | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $path -Encoding UTF8
            [pscustomobject]@{Path=$path;SHA256=(Get-FileHash -LiteralPath $path).Hash}
        }
        function script:Get-WsmBootStamp {'2026-10-08T00:00:00.0000000Z'}
        $safe=Join-Path $Root 'safe';$result=Export-WsmLabValidationReport -OutputDirectory $safe -Role Source -TextCheckLimit 2
        if($result.Readiness -ne 'NotTested' -or $result.ProductionVerified -ne $false -or $result.Counts.NotTested -lt 1){throw 'Environment-only report must remain explicitly NotTested and non-production.'}
        if($result.Report.TextChecksShown -ne 2 -or $result.Report.TextChecksOmitted -le 0 -or $result.Report.Checks.Count -le $result.Report.TextChecksShown){throw 'Text check cap silently discarded or failed to count complete JSON checks.'}
        $textBytes=[IO.File]::ReadAllBytes($result.TextPath);if($textBytes.Length -lt 3 -or $textBytes[0] -ne 0xEF -or $textBytes[1] -ne 0xBB -or $textBytes[2] -ne 0xBF){throw 'Copy/paste report lacks a UTF-8 BOM.'}
        $reportText=[IO.File]::ReadAllText($result.TextPath);if($reportText -notmatch [regex]::Escape($result.JSONSHA256) -or $reportText -notmatch 'Business validation: required'){throw 'Text handback omits report digest or unsatisfied business-validation statement.'}
        $targetEnvironment=Export-WsmLabValidationReport -OutputDirectory (Join-Path $Root 'target-environment') -Role Target;if($targetEnvironment.Readiness -ne 'NotTested'){throw 'Target environment-only report unexpectedly claimed package validation.'}
        $jsonText=[IO.File]::ReadAllText($result.JSONPath);if($jsonText.Contains($script:labSecret) -or $reportText.Contains($script:labSecret)){throw 'Fixture secret leaked into handback report.'}
        $sourceOut=Join-Path $Root 'source-pkg';$script:labPackage=Get-WsmMigrationPackageFixture;$trusted=Export-WsmLabValidationReport -OutputDirectory $sourceOut -Role Source -ManifestPath 'fixture-manifest.json' -ExpectedHash ('9'*64)
        $detail=$trusted.Report.Checks | Where-Object Code -CEQ SourceInventoryBinding;if(-not $detail -or $detail.Status -ne 'PASS' -or $detail.ExpectedSHA256 -cne $detail.ObservedSHA256){throw 'Source collector settings hash was not bound exactly to the approved item.'}
        $confirmationPath=Join-Path $Root 'environment-confirmation.json';$confirmation=New-WsmLabEnvironmentConfirmationFixture $script:labPackage.Manifest $confirmationPath
        $baselineReport=Export-WsmLabValidationReport -OutputDirectory (Join-Path $Root 'confirmation-baseline') -Role Source -ManifestPath 'fixture-manifest.json' -ExpectedHash ('9'*64)
        $withConfirmation=Export-WsmLabValidationReport -OutputDirectory (Join-Path $Root 'confirmation-attached') -Role Source -ManifestPath 'fixture-manifest.json' -ExpectedHash ('9'*64) -EnvironmentConfirmationReferences @([pscustomobject]@{Path=$confirmation.Path;SHA256=$confirmation.SHA256})
        if($withConfirmation.Readiness -cne $baselineReport.Readiness -or $withConfirmation.Blocked -ne $baselineReport.Blocked -or (ConvertTo-Json $withConfirmation.Counts -Compress) -cne (ConvertTo-Json $baselineReport.Counts -Compress) -or $withConfirmation.Report.Checks.Count -ne $baselineReport.Report.Checks.Count){throw 'Attaching a valid environment confirmation changed lab gates.'}
        $reference=$withConfirmation.Report.EnvironmentConfirmationReferences[0];if($reference.DocumentId -cne $confirmation.DocumentId -or $reference.Path -cne [IO.Path]::GetFullPath($confirmation.Path) -or $reference.SHA256 -cne $confirmation.SHA256 -or $reference.Status -cne 'ReportOnly' -or $reference.AuthoritativeDecisionInput -or $reference.ReadinessProof -or $withConfirmation.Report.EnvironmentConfirmationReferencesAuthoritativeDecisionInput -or $withConfirmation.Report.EnvironmentConfirmationReferencesReadinessProof -or @($withConfirmation.Report.Checks | Where-Object Code -Like '*EnvironmentConfirmation*').Count){throw 'Environment confirmation reference was not preserved as a report-only locator.'}
        $missingOutput=Join-Path $Root 'missing-confirmation';$missingBlocked=$false;try{Export-WsmLabValidationReport -OutputDirectory $missingOutput -Role Source -ManifestPath 'fixture-manifest.json' -ExpectedHash ('9'*64) -EnvironmentConfirmationReferences @([pscustomobject]@{Path=(Join-Path $Root 'absent-confirmation.json');SHA256=('7'*64)}) | Out-Null}catch{$missingBlocked=$true};if(-not $missingBlocked -or [IO.Directory]::Exists($missingOutput)){throw 'Missing environment confirmation reference was accepted or wrote output.'}
        $tamperedConfirmation=New-WsmLabEnvironmentConfirmationFixture $script:labPackage.Manifest (Join-Path $Root 'tampered-confirmation.json');[IO.File]::AppendAllText($tamperedConfirmation.Path,' ');$tamperOutput=Join-Path $Root 'tampered-confirmation-output';$tamperBlocked=$false;try{Export-WsmLabValidationReport -OutputDirectory $tamperOutput -Role Source -ManifestPath 'fixture-manifest.json' -ExpectedHash ('9'*64) -EnvironmentConfirmationReferences @([pscustomobject]@{Path=$tamperedConfirmation.Path;SHA256=$tamperedConfirmation.SHA256}) | Out-Null}catch{$tamperBlocked=$true};if(-not $tamperBlocked -or [IO.Directory]::Exists($tamperOutput)){throw 'Tampered environment confirmation reference was accepted or wrote output.'}
        $wrongPairConfirmation=New-WsmLabEnvironmentConfirmationFixture $script:labPackage.Manifest (Join-Path $Root 'wrong-pair-confirmation.json') '44444444-4444-4444-8444-444444444444';$wrongPairOutput=Join-Path $Root 'wrong-pair-confirmation-output';$wrongPairBlocked=$false;try{Export-WsmLabValidationReport -OutputDirectory $wrongPairOutput -Role Source -ManifestPath 'fixture-manifest.json' -ExpectedHash ('9'*64) -EnvironmentConfirmationReferences @([pscustomobject]@{Path=$wrongPairConfirmation.Path;SHA256=$wrongPairConfirmation.SHA256}) | Out-Null}catch{$wrongPairBlocked=$true};if(-not $wrongPairBlocked -or [IO.Directory]::Exists($wrongPairOutput)){throw 'Wrong-pair environment confirmation reference was accepted or wrote output.'}
        if($trusted.Report.Checks.Where({$_.Code -eq 'ManualWorkflow'}).Count -ne 1 -or $trusted.Report.Checks.Where({$_.Code -eq 'ManualWorkflow'})[0].Status -ne 'NotTested'){throw 'Manual workflow was reported as tested.'}
        $trustedText=[IO.File]::ReadAllText($trusted.TextPath);$trustedJson=[IO.File]::ReadAllText($trusted.JSONPath);if($trustedText.Contains($script:labSecret) -or $trustedJson.Contains($script:labSecret)){throw 'Package/manual business fixture secret leaked into handback report.'}
        function script:Export-WsmInventory {param([string]$OutputDirectory,[switch]$DeepDiscovery)$failure=New-Object UnauthorizedAccessException(('fixture failure contains '+$script:labSecret));$failure.Data['NativeCode']=5;throw $failure};$failureOut=Join-Path $Root 'safe-failure';$failureResult=Export-WsmLabValidationReport -OutputDirectory $failureOut -Role Source -ManifestPath 'fixture-manifest.json' -ExpectedHash ('9'*64);$collectorFailure=@($failureResult.Report.Checks | Where-Object Code -CEQ NativeInventoryCollected)[0];if($collectorFailure.FailureCategory -ne 'Permission' -or $collectorFailure.NativeCode -ne 5 -or -not $collectorFailure.HResult -or ([IO.File]::ReadAllText($failureResult.TextPath).Contains($script:labSecret))){throw 'Safe native failure classification leaked fixture error text or omitted numeric diagnostics.'};function script:Export-WsmInventory {param([string]$OutputDirectory,[switch]$DeepDiscovery)$inventory=[pscustomobject]@{Source=[pscustomobject]@{Fingerprint='a'*64};Items=@([pscustomobject]@{ItemId='c'*64;SettingsHash='d'*64;Status='Success';Settings=[pscustomobject]@{PrivateValue=$script:labSecret}})};$path=Join-Path $OutputDirectory 'fixture-inventory.json';$inventory | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $path -Encoding UTF8;[pscustomobject]@{Path=$path;SHA256=(Get-FileHash -LiteralPath $path).Hash}}
        $scopeRoot=Join-Path $Root 'real-scope';[void][IO.Directory]::CreateDirectory($scopeRoot);$scopeFile=Join-Path $scopeRoot 'sample.txt';$fixtureContent='actual file-scope fixture';[IO.File]::WriteAllText($scopeFile,$fixtureContent);$scopePackageRoot=Join-Path $Root 'scope-package';$blobRoot=Join-Path $scopePackageRoot 'payload';[void][IO.Directory]::CreateDirectory($blobRoot)
        $scopeBytes=[Text.Encoding]::UTF8.GetBytes($fixtureContent);$scopeSha=[Security.Cryptography.SHA256]::Create();try{$scopeHash=[BitConverter]::ToString($scopeSha.ComputeHash($scopeBytes)).Replace('-','').ToLowerInvariant()}finally{$scopeSha.Dispose()};[IO.File]::WriteAllBytes((Join-Path $blobRoot ($scopeHash+'.blob')),$scopeBytes);$metadata=Get-WsmFileMetadata $scopeFile 'DaclOwner';$rootMetadata=Get-WsmFileMetadata $scopeRoot 'DaclOwner';$scopeItem=[pscustomobject]@{ItemId='c'*64;SettingsHash='d'*64;MigrationSpec=[pscustomobject]@{Adapter='FileScope';Metadata='DaclOwner';AclControlPolicy='Exact';ExcludedRelativePaths=@()}};$rootRow=[pscustomobject]@{ItemId=$scopeItem.ItemId;RelativePath='';Directory=$true;Metadata=$rootMetadata;Data=$null};$fileRow=[pscustomobject]@{ItemId=$scopeItem.ItemId;RelativePath='sample.txt';Directory=$false;Metadata=$metadata;Data=[pscustomobject]@{Bytes=$scopeBytes.Length;Hash=$scopeHash;Chunks=@([pscustomobject]@{Hash=$scopeHash;Bytes=$scopeBytes.Length})}};$indexPath=Join-Path $scopePackageRoot 'artifacts.jsonl';$indexText=(@($rootRow,$fileRow) | ForEach-Object {ConvertTo-Json -InputObject $_ -Compress -Depth 10}) -join [Environment]::NewLine;[IO.File]::WriteAllText($indexPath,$indexText+[Environment]::NewLine,(New-Object Text.UTF8Encoding($false)));$artifactsHash=(Get-FileHash -LiteralPath $indexPath).Hash;$scopePackage=[pscustomobject]@{Root=$scopePackageRoot;Manifest=[pscustomobject]@{ArtifactsHash=$artifactsHash};Plan=[pscustomobject]@{}};$rawScope=Test-WsmFileScope $scopeItem $scopePackage $scopeRoot;$scopeCheck=Test-WsmLabFileScopeCheck $scopeItem $scopePackage $scopeRoot;if($scopeCheck.Status -ne 'PASS' -or -not $scopeCheck.ObservedSHA256){throw ('Real file-scope content/metadata verification did not pass: '+($rawScope | ConvertTo-Json -Compress))}
        $tampered=Join-Path $Root 'tampered.json';[IO.File]::WriteAllText($tampered,'{"Kind":"MigrationPackage"}');$blocked=$false;try{Read-WsmTrustedJson $tampered ('0'*64) | Out-Null}catch{$blocked=$true};if(-not $blocked){throw 'Tampered package hash was accepted.'}
        $wrongRoot=Join-Path $Root 'wrong-role';$script:labFingerprint='0'*64;$blocked=$false;try{Export-WsmLabValidationReport -OutputDirectory $wrongRoot -Role Source -ManifestPath 'fixture-manifest.json' -ExpectedHash ('9'*64) | Out-Null}catch{$blocked=$true};if(-not $blocked -or [IO.Directory]::Exists($wrongRoot)){throw 'Wrong role fingerprint did not reject before writing reports.'};$script:labFingerprint='a'*64
        $foreignOut=Join-Path $Root 'foreign-state';$stateDir=Join-Path $Root 'state';$pair='11111111-1111-4111-8111-111111111111';$pairRoot=Join-Path $stateDir $pair;[void][IO.Directory]::CreateDirectory($pairRoot);$script:labFingerprint='f'*64
        $foreignState=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='OperationState';PairId=$pair;TargetFingerprint='0'*64;PlanHash='e'*64;ManifestHash='9'*64;Generation=1;PendingOperations=@();Sequence=0;JournalHash='0'*64;RunId='22222222-2222-4222-8222-222222222222'};Write-WsmJson (Join-Path $pairRoot 'state.json') $foreignState;[IO.File]::WriteAllText((Join-Path $pairRoot 'journal.jsonl'),'')
        $blocked=$false;try{Export-WsmLabValidationReport -OutputDirectory $foreignOut -Role Target -ManifestPath 'fixture-manifest.json' -ExpectedHash ('9'*64) -StateDirectory $stateDir | Out-Null}catch{$blocked=$true};if(-not $blocked -or [IO.Directory]::Exists($foreignOut)){throw 'Foreign target state did not reject before writing reports.'}
        $boundState=$foreignState | ConvertTo-Json -Depth 8 | ConvertFrom-Json;$boundState.TargetFingerprint='f'*64;Write-WsmJson (Join-Path $pairRoot 'state.json') $boundState;$binding=Assert-WsmLabStateBinding $script:labPackage.Manifest ('9'*64) $stateDir;if(-not $binding.Journal.Consistent -or $binding.Journal.StateSequence -ne 0){throw 'Read-only target journal binding failed against a real empty journal and checkpoint.'}
        $badHash=$false;try{Export-WsmLabValidationReport -OutputDirectory (Join-Path $Root 'missing-hash') -Role Source -ManifestPath 'fixture-manifest.json' | Out-Null}catch{$badHash=$true};if(-not $badHash){throw 'Manifest without expected hash was accepted.'}
        $identityBad=$false;function script:Get-WsmMachineIdentity {[pscustomobject]@{Fingerprint=$script:labFingerprint;Name='fixture-host';OS='Windows Server Fixture';Version='10.0.fixture';IsServer='yes';Administrator=$true;Is64Bit=$true}};try{Export-WsmLabValidationReport -OutputDirectory (Join-Path $Root 'bad-environment') -Role Source | Out-Null}catch{$identityBad=$true};if(-not $identityBad){throw 'Malformed environment boolean type was accepted.'}
        Write-Host 'PASS: offline lab report binds source settings and host identity, verifies a real file scope and operation journal, keeps manual/business evidence NotTested, attaches trusted environment confirmation JSON as report-only metadata without changing gates, rejects missing/tampered/wrong-pair refs before output, caps text with complete JSON counts, emits BOM copy/paste text with JSON hash, reports safe native failure codes, and sanitizes fixture secrets.'
    } $PSScriptRoot $root
} finally {
    $resolved=[IO.Path]::GetFullPath($root);$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath())
    if(-not $resolved.StartsWith($temp,[StringComparison]::OrdinalIgnoreCase) -or [IO.Path]::GetFileName($resolved) -notlike 'wsm-lab-validation-*'){throw 'Lab validation fixture cleanup guard failed.'}
    if([IO.Directory]::Exists($resolved)){[IO.Directory]::Delete($resolved,$true)}
}
