#requires -Version 5.1
$ErrorActionPreference='Stop'
$module=Import-Module (Join-Path $PSScriptRoot '..\src\WindowsServerMigration.psd1') -Force -PassThru
$root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-share-quiescence-'+[Guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($root)
& $module {
    param($Root)
    . (Join-Path $PSScriptRoot '..\src\ShareQuiescence.ps1')
    $script:shareTestRoot=$Root
    $script:share=$null;$script:shares=@();$script:acl=@();$script:openFiles=@();$script:sessions=@();$script:world='Fixture Local Everyone';$script:closed=@();$script:closeScopes=@();$script:expectedHandleScope='*';$script:unblockCount=0;$script:blockedCount=0;$script:failCloseAfterEffect=$false;$script:failCloseBeforeEffect=$false
    function script:Get-WsmMachineIdentity {[pscustomobject]@{Fingerprint=$script:fixtureSourceFingerprint}}
    function script:Assert-WsmMigrationHost($Identity,[string]$Fingerprint){if($Identity.Fingerprint -cne $Fingerprint){throw 'Fixture host identity mismatch.'}}
    function script:Get-WsmEveryoneName {$script:world}
    function script:Resolve-WsmAccountSid([string]$Account){switch -CaseSensitive ($Account){'Fixture Local Everyone'{'S-1-1-0'};'S-1-1-0'{'S-1-1-0'};'Fixture Readers'{'S-1-5-21-1-2-3-1001'};'Fixture Writers'{'S-1-5-21-1-2-3-1002'};'Unowned User'{'S-1-5-21-1-2-3-1003'};default{throw ('Unknown fixture account: '+$Account)}}}
    function script:Get-SmbShare {param($Name,$ScopeName,$ErrorAction)if($PSBoundParameters.ContainsKey('Name')){if($Name -cne $script:share.Name){return @()};return $script:share};@($script:shares)}
    function script:Get-SmbShareAccess {param($Name,$ScopeName,$ErrorAction)if($Name -cne $script:share.Name){throw 'Unexpected share ACL query'};@($script:acl)}
    function script:Block-SmbShareAccess {param($Name,$ScopeName,$AccountName,[switch]$Force,$ErrorAction)$script:blockedCount++;if(-not @($script:acl | Where-Object {$_.AccountName -eq $AccountName -and $_.AccessControlType -eq 'Deny'}).Count){$script:acl+=@([pscustomobject]@{AccountName=$AccountName;AccessControlType='Deny';AccessRight='Full'})}}
    function script:Unblock-SmbShareAccess {param($Name,$ScopeName,$AccountName,[switch]$Force,$ErrorAction)$script:unblockCount++;$script:acl=@($script:acl | Where-Object {-not ($_.AccountName -eq $AccountName -and $_.AccessControlType -eq 'Deny')})}
    function script:Grant-SmbShareAccess {param($Name,$ScopeName,$AccountName,$AccessRight,[switch]$Force,$ErrorAction)$script:acl+=@([pscustomobject]@{AccountName=$AccountName;AccessControlType='Allow';AccessRight=$AccessRight})}
    function script:Revoke-SmbShareAccess {param($Name,$ScopeName,$AccountName,[switch]$Force,$ErrorAction)$script:acl=@($script:acl | Where-Object {-not ($_.AccountName -eq $AccountName -and $_.AccessControlType -eq 'Allow')})}
    function script:Get-SmbOpenFile {param([string[]]$ScopeName,$ErrorAction)if($ScopeName -cne $script:expectedHandleScope){throw 'Open-file query omitted or widened the exact SMB scope'};@($script:openFiles)}
    function script:Get-SmbSession {param([string[]]$ScopeName,$ErrorAction)if($ScopeName -cne $script:expectedHandleScope){throw 'Session query omitted or widened the exact SMB scope'};@($script:sessions)}
    function script:Close-SmbOpenFile {param([UInt64]$FileId,[string[]]$ScopeName,[switch]$Force,[bool]$Confirm,$ErrorAction)if($ScopeName -cne $script:expectedHandleScope){throw 'Close omitted or widened the exact SMB scope'};$script:closed+=@($FileId);$script:closeScopes+=@($ScopeName);if($script:failCloseBeforeEffect){$script:failCloseBeforeEffect=$false;throw 'fixture close transport failed before effect'};$script:openFiles=@($script:openFiles | Where-Object {[UInt64]$_.FileId -ne $FileId});if($script:failCloseAfterEffect){$script:failCloseAfterEffect=$false;throw 'fixture close transport failed after effect'}}
    function Assert-Throws([scriptblock]$Action,[string]$Name){$thrown=$false;try{& $Action}catch{$thrown=$true};if(-not $thrown){throw ('Expected rejection: '+$Name)}}
    function New-FixtureShareCase([string]$Policy='BlockNewOpens',[bool]$OriginalWorldDeny=$false,[string]$CaseName='case'){
        $script:fixtureSourceFingerprint=('a'*64);$script:closed=@();$script:closeScopes=@();$script:unblockCount=0;$script:blockedCount=0;$script:openFiles=@();$script:sessions=@();$script:expectedHandleScope='*';$script:failCloseBeforeEffect=$false;$script:failCloseAfterEffect=$false
        $script:share=[pscustomobject]@{Name='Data';Path='C:\Fixture\data';ScopeName=''};$script:shares=@($script:share,[pscustomobject]@{Name='C$';Path='C:\';ScopeName=''},[pscustomobject]@{Name='IPC$';Path='';ScopeName=''})
        $script:acl=@([pscustomobject]@{AccountName='Fixture Readers';AccessControlType='Allow';AccessRight='Read'},[pscustomobject]@{AccountName='Fixture Writers';AccessControlType='Allow';AccessRight='Change'})
        if($OriginalWorldDeny){$script:acl+=@([pscustomobject]@{AccountName=$script:world;AccessControlType='Deny';AccessRight='Full'})}
        $pair=[Guid]::NewGuid().ToString();$sourceId=[Guid]::NewGuid().ToString();$approval=[Guid]::NewGuid().ToString();$itemId=('1'*64);$settingsHash=('e'*64);$plan=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='MigrationPlan';BatchId=[Guid]::NewGuid().ToString();PairId=$pair;ApprovalId=$approval;Source=[pscustomobject]@{HostId=$sourceId;Fingerprint=$script:fixtureSourceFingerprint;Name='source'};Target=[pscustomobject]@{HostId=[Guid]::NewGuid().ToString();Fingerprint=('b'*64)};Mode='IsolatedPilot'}
        $desired=[pscustomobject]@{Name='Data';Path='D:\Target\Data';DrainPolicy=$Policy;DrainEvidence='Reviewed drain ticket '+$CaseName;Access=@()};$spec=[pscustomobject]@{Adapter='SmbShare';Owner='storage-owner';Evidence='approved migration plan';Desired=$desired}
        $item=[pscustomobject]@{Decision='Include';ItemId=$itemId;Kind='Share';NaturalKey='Data';SettingsHash=$settingsHash;MigrationSpec=$spec}
        $sourceAccess=@(foreach($ace in $script:acl){[pscustomobject]@{AccountName=$ace.AccountName;AccessControlType=$ace.AccessControlType;AccessRight=$ace.AccessRight}})
        $sourceItem=[pscustomobject]@{ItemId=$itemId;NaturalKey='Data';SettingsHash=$settingsHash;Status='Success';Settings=[pscustomobject]@{Definition=[pscustomobject]@{Name='Data';Path='C:\Fixture\data';ScopeName=''};Access=$sourceAccess}}
        $baselinePath=Join-Path $script:shareTestRoot ($CaseName+'-baseline.json');$planHash=('f'*64);$baseline=Export-WsmShareQuiescenceBaseline -Plan $plan -Item $item -SourceItem $sourceItem -PlanHash $planHash -Path $baselinePath -Owner 'storage-owner' -Evidence 'approved migration plan'
        $attemptPath=Join-Path $script:shareTestRoot ($CaseName+'-attempt.json');$attempt=[pscustomobject]@{SchemaVersion=1;ToolVersion='0.3.0';Kind='SourceFreezeAttempt';PairId=$pair;ApprovalId=$approval;PlanHash=$planHash;SourceFingerprint=$script:fixtureSourceFingerprint;BaselinePath=(Join-Path $script:shareTestRoot ($CaseName+'-inventory.json'));BaselineHash=('0'*64);ShareBaselines=@([pscustomobject]@{ItemId=$itemId;Path=$baselinePath;SHA256=$baseline.SHA256});ShareQuiescence=@();Status='Prepared'};Write-WsmJson $attemptPath $attempt
        [pscustomobject]@{Plan=$plan;Item=$item;SourceItem=$sourceItem;PlanHash=$planHash;BaselinePath=$baselinePath;BaselineHash=$baseline.SHA256;AttemptPath=$attemptPath;AttemptHash=(Get-FileHash $attemptPath).Hash}
    }
    function Invoke-FixtureDrain($Case){Invoke-WsmShareQuiescence -Plan $Case.Plan -Item $Case.Item -BaselinePath $Case.BaselinePath -BaselineHash $Case.BaselineHash -AttemptPath $Case.AttemptPath -AttemptHash $Case.AttemptHash}
    function Assert-FixtureAclKeys([string[]]$Expected){$actual=@(Get-WsmShareQuiescenceAceKeys (Get-WsmShareQuiescenceAces 'Data'));if((($actual|Sort-Object)-join ';') -cne (($Expected|Sort-Object)-join ';')){throw ('Unexpected fixture share ACL: '+($actual -join ';'))}}

    # A clean share is denied for new opens, drained, retried from its original durable ACL baseline, then restored exactly.
    $case=New-FixtureShareCase BlockNewOpens $false 'positive';$drained=Invoke-FixtureDrain $case
    if($drained.Status -ne 'Quiesced' -or -not $drained.NewOpensBlocked -or $script:blockedCount -ne 1){throw 'Clean share did not reach blocked-new-opens and drained state.'}
    $withDeny=@((Get-WsmShareQuiescenceAceKeys (Get-WsmShareQuiescenceAces 'Data')));if($withDeny -notcontains 'S-1-1-0|Deny|Full'){throw 'Localized Everyone deny was not applied.'}
    $retry=Invoke-WsmShareQuiescence -Plan $case.Plan -Item $case.Item -BaselinePath $case.BaselinePath -BaselineHash $case.BaselineHash -AttemptPath $case.AttemptPath -AttemptHash $drained.AttemptHash
    if($script:blockedCount -ne 1 -or $retry.Status -ne 'Quiesced'){throw 'Idempotent retry changed the ACL or lost the completed state.'}
    $resumed=Restore-WsmShareQuiescence -Plan $case.Plan -Item $case.Item -BaselinePath $case.BaselinePath -BaselineHash $case.BaselineHash -AttemptPath $case.AttemptPath -AttemptHash $retry.AttemptHash -Owner 'storage-owner' -OwnershipEvidence 'target stopped and writes reconciled' -Acknowledgement ('SOURCE-OWNERSHIP-RESTORED '+$case.Plan.PairId)
    if(-not $resumed.ExactBaselineRestored -or $script:unblockCount -ne 1){throw 'Source resume did not remove only the temporary deny.'}
    $resumedAgain=Restore-WsmShareQuiescence -Plan $case.Plan -Item $case.Item -BaselinePath $case.BaselinePath -BaselineHash $case.BaselineHash -AttemptPath $case.AttemptPath -AttemptHash $resumed.AttemptHash -Owner 'storage-owner' -OwnershipEvidence 'target stopped and writes reconciled' -Acknowledgement ('SOURCE-OWNERSHIP-RESTORED '+$case.Plan.PairId)
    if(-not $resumedAgain.ExactBaselineRestored -or $script:unblockCount -ne 1){throw 'Idempotent source resume changed the already restored ACL.'}
    Assert-FixtureAclKeys @('S-1-5-21-1-2-3-1001|Allow|Read','S-1-5-21-1-2-3-1002|Allow|Change')

    # A crash after the native deny but before the attempt status update leaves Prepared intent; exact ACL evidence still permits safe ownership-proven restoration.
    $case=New-FixtureShareCase BlockNewOpens $false 'restore-native-crash';$drained=Invoke-FixtureDrain $case;$staleAttempt=Read-WsmTrustedJson $case.AttemptPath $drained.AttemptHash;$staleAttempt.ShareQuiescence[0].Status='Prepared';Write-WsmJson $case.AttemptPath $staleAttempt;$staleHash=(Get-FileHash -LiteralPath $case.AttemptPath -Algorithm SHA256).Hash
    $resumed=Restore-WsmShareQuiescence -Plan $case.Plan -Item $case.Item -BaselinePath $case.BaselinePath -BaselineHash $case.BaselineHash -AttemptPath $case.AttemptPath -AttemptHash $staleHash -Owner 'storage-owner' -OwnershipEvidence 'target stopped and writes reconciled' -Acknowledgement ('SOURCE-OWNERSHIP-RESTORED '+$case.Plan.PairId)
    if(-not $resumed.ExactBaselineRestored -or $script:unblockCount -ne 1){throw 'Source resume did not reconcile exact temporary deny from a durable pre-mutation intent.'}

    # Active handles block the default policy; a similarly named sibling path is outside the selected share and is never closed.
    $case=New-FixtureShareCase BlockNewOpens $false 'active';$script:openFiles=@([pscustomobject]@{FileId=[UInt64]101;ScopeName='*';SessionId=[UInt64]501;Path='C:\Fixture\data\active.db';ShareRelativePath='active.db';ClientComputerName='client-a';ClientUserName='Fixture Writers'},[pscustomobject]@{FileId=[UInt64]102;ScopeName='*';SessionId=[UInt64]502;Path='C:\Fixture\data-archive\other.db';ShareRelativePath='other.db';ClientComputerName='client-b';ClientUserName='Fixture Writers'});$script:sessions=@([pscustomobject]@{SessionId=[UInt64]501;ClientComputerName='client-a';ClientUserName='Fixture Writers';NumOpens=1;ScopeName='*'},[pscustomobject]@{SessionId=[UInt64]502;ClientComputerName='client-b';ClientUserName='Fixture Writers';NumOpens=1;ScopeName='*'})
    Assert-Throws {Invoke-FixtureDrain $case} 'existing in-scope handle under BlockNewOpens'
    $savedAttempt=Read-WsmJson $case.AttemptPath;$currentHash=(Get-FileHash $case.AttemptPath).Hash;if(@($savedAttempt.ShareQuiescence | Where-Object Status -EQ BlockedByOpenHandles).Count -ne 1 -or $script:closed.Count -ne 0 -or $script:openFiles.Count -ne 2){throw 'Open handle failure lost retry state or touched an unowned client.'}
    $script:openFiles=@($script:openFiles | Where-Object FileId -ne 101);$case.AttemptHash=$currentHash;$drained=Invoke-FixtureDrain $case
    if($drained.Status -ne 'Quiesced' -or $script:closed.Count -ne 0 -or $script:openFiles.Count -ne 1){throw 'Retry did not wait for natural handle closure and leave the sibling handle alone.'}

    # CloseReviewedHandles closes only individual files proven to be within this share and records matching sessions.
    $case=New-FixtureShareCase CloseReviewedHandles $false 'reviewed-close';$script:openFiles=@([pscustomobject]@{FileId=[UInt64]201;ScopeName='*';SessionId=[UInt64]601;Path='C:\Fixture\data\one.dat';ShareRelativePath='one.dat';ClientComputerName='client-one';ClientUserName='Fixture Writers'},[pscustomobject]@{FileId=[UInt64]202;ScopeName='*';SessionId=[UInt64]602;Path='C:\Fixture\data\nested\two.dat';ShareRelativePath='nested\two.dat';ClientComputerName='client-two';ClientUserName='Fixture Writers'},[pscustomobject]@{FileId=[UInt64]203;ScopeName='*';SessionId=[UInt64]603;Path='C:\Fixture\data-old\outside.dat';ShareRelativePath='outside.dat';ClientComputerName='client-three';ClientUserName='Unowned User'});$script:sessions=@(foreach($id in @(601,602,603)){[pscustomobject]@{SessionId=[UInt64]$id;ClientComputerName=('client-'+$id);ClientUserName='Fixture Writers';NumOpens=1;ScopeName='*'}})
    $drained=Invoke-FixtureDrain $case
    if($drained.Status -ne 'Quiesced' -or (($script:closed|Sort-Object)-join ',') -ne '201,202' -or @($script:openFiles | Where-Object FileId -EQ 203).Count -ne 1){throw 'Reviewed close policy closed a file outside the exact share or missed an in-scope file.'}
    if($script:closeScopes.Count -ne 2 -or @($script:closeScopes | Where-Object {$_ -cne '*'}).Count){throw 'A reviewed close did not carry the exact unscoped-handle identity.'}
    $savedAttempt=Read-WsmJson $case.AttemptPath;$closeRecord=@($savedAttempt.ShareQuiescence | Where-Object ItemId -EQ $case.Item.ItemId)[0];if(@($closeRecord.Sessions).Count -ne 2){throw 'Drain report did not retain the sessions correlated to in-scope open files.'}

    # A close API error after the server has closed the file preserves durable intent without falsely claiming a confirmed successful close.
    $case=New-FixtureShareCase CloseReviewedHandles $false 'close-error-after-effect';$script:openFiles=@([pscustomobject]@{FileId=[UInt64]401;ScopeName='*';SessionId=[UInt64]801;Path='C:\Fixture\data\one.dat';ShareRelativePath='one.dat';ClientComputerName='client';ClientUserName='Fixture Writers'});$script:sessions=@([pscustomobject]@{SessionId=[UInt64]801;ClientComputerName='client';ClientUserName='Fixture Writers';NumOpens=1;ScopeName='*'});$script:failCloseAfterEffect=$true;$errorText='';try{Invoke-FixtureDrain $case|Out-Null}catch{$errorText=$_.Exception.Message}
    if($errorText -notmatch 'attempt hash ([a-fA-F0-9]{64})'){throw 'A native close failure did not expose its durable retry hash.'};$retryHash=$Matches[1];$savedAttempt=Read-WsmTrustedJson $case.AttemptPath $retryHash;$closeRecord=@($savedAttempt.ShareQuiescence | Where-Object ItemId -EQ $case.Item.ItemId)[0]
    if($closeRecord.Status -ne 'Quiesced' -and $closeRecord.Status -ne 'ClosingReviewedHandles'){throw 'Failed close attempt state was not retained for retry.'}
    if(@($closeRecord.ClosedFileIds).Count -ne 0 -or @($closeRecord.ObservedGoneFileIds | Where-Object {$_ -eq 401}).Count -ne 1 -or $closeRecord.CloseIntents[0].Status -ne 'CloseFailedObservedGone'){throw ('A close that errored after effect was falsely counted as confirmed closed or lost its intent. closed='+(@($closeRecord.ClosedFileIds)-join ',')+' gone='+(@($closeRecord.ObservedGoneFileIds)-join ',')+' state='+$closeRecord.CloseIntents[0].Status)}
    $retried=Invoke-WsmShareQuiescence -Plan $case.Plan -Item $case.Item -BaselinePath $case.BaselinePath -BaselineHash $case.BaselineHash -AttemptPath $case.AttemptPath -AttemptHash $retryHash;if($retried.Status -ne 'Quiesced'){throw 'Retry did not converge after observing the open file gone.'};$savedAttempt=Read-WsmTrustedJson $case.AttemptPath $retried.AttemptHash;$closeRecord=@($savedAttempt.ShareQuiescence | Where-Object ItemId -EQ $case.Item.ItemId)[0];if(@($closeRecord.ClosedFileIds).Count -ne 0){throw 'Retry changed an observed-gone file into a confirmed close.'}

    # A close fault before effect keeps the scoped handle open and retry can close it once.
    $case=New-FixtureShareCase CloseReviewedHandles $false 'close-error-before-effect';$script:openFiles=@([pscustomobject]@{FileId=[UInt64]402;ScopeName='*';SessionId=[UInt64]802;Path='C:\Fixture\data\before.bin';ShareRelativePath='before.bin';ClientComputerName='client';ClientUserName='Fixture Writers'});$script:sessions=@([pscustomobject]@{SessionId=[UInt64]802;ClientComputerName='client';ClientUserName='Fixture Writers';NumOpens=1;ScopeName='*'});$script:failCloseBeforeEffect=$true;$errorText='';try{Invoke-FixtureDrain $case|Out-Null}catch{$errorText=$_.Exception.Message};if($errorText -notmatch 'attempt hash ([a-fA-F0-9]{64})' -or @($script:openFiles | Where-Object FileId -EQ 402).Count -ne 1){throw 'Before-effect close failure did not preserve an open handle and durable retry hash.'};$retryHash=$Matches[1];$savedAttempt=Read-WsmTrustedJson $case.AttemptPath $retryHash;$closeRecord=@($savedAttempt.ShareQuiescence | Where-Object ItemId -EQ $case.Item.ItemId)[0];if($closeRecord.CloseIntents[0].Status -ne 'CloseFailedStillOpen' -or @($closeRecord.ClosedFileIds).Count -ne 0){throw 'Before-effect close failure was incorrectly recorded as closed.'};$retried=Invoke-WsmShareQuiescence -Plan $case.Plan -Item $case.Item -BaselinePath $case.BaselinePath -BaselineHash $case.BaselineHash -AttemptPath $case.AttemptPath -AttemptHash $retryHash;if($retried.Status -ne 'Quiesced' -or @($script:openFiles | Where-Object FileId -EQ 402).Count){throw 'Before-effect close retry did not close the exact surviving handle.'}

    # Original Everyone deny is retained on resume and is never mistaken for the temporary deny.
    $case=New-FixtureShareCase BlockNewOpens $true 'original-deny';$drained=Invoke-FixtureDrain $case
    if($drained.TemporaryDenyAdded -or $script:blockedCount -ne 0){throw 'Existing reviewed Everyone deny was duplicated as a temporary rule.'}
    $resumed=Restore-WsmShareQuiescence -Plan $case.Plan -Item $case.Item -BaselinePath $case.BaselinePath -BaselineHash $case.BaselineHash -AttemptPath $case.AttemptPath -AttemptHash $drained.AttemptHash -Owner 'storage-owner' -OwnershipEvidence 'target stopped and writes reconciled' -Acknowledgement ('SOURCE-OWNERSHIP-RESTORED '+$case.Plan.PairId)
    if($script:unblockCount -ne 0 -or @($script:acl | Where-Object {$_.AccountName -eq $script:world -and $_.AccessControlType -eq 'Deny'}).Count -ne 1){throw 'Original Everyone deny was removed during source resume.'}

    # Changed ACL, missing close policy evidence, alternate baseline, and overlapping-share scope ambiguity all fail closed.
    $case=New-FixtureShareCase BlockNewOpens $false 'acl-drift';$script:acl+=@([pscustomobject]@{AccountName='Unowned User';AccessControlType='Allow';AccessRight='Full'});Assert-Throws {Invoke-FixtureDrain $case} 'share ACL drift';if($script:blockedCount -ne 0){throw 'Share ACL drift was followed by a temporary deny mutation.'}
    $case=New-FixtureShareCase CloseReviewedHandles $false 'missing-evidence';$case.Item.MigrationSpec.Desired.DrainEvidence='';Assert-Throws {Invoke-FixtureDrain $case} 'missing reviewed close evidence';if($script:blockedCount -ne 0){throw 'Missing evidence was followed by an SMB mutation.'}
    $case=New-FixtureShareCase BlockNewOpens $false 'wrong-baseline';$other=Export-WsmShareQuiescenceBaseline -Plan $case.Plan -Item $case.Item -SourceItem $case.SourceItem -PlanHash $case.PlanHash -Path (Join-Path $Root 'alternate-baseline.json') -Owner 'storage-owner' -Evidence 'reviewed alternate';Assert-Throws {Invoke-WsmShareQuiescence -Plan $case.Plan -Item $case.Item -BaselinePath $other.Path -BaselineHash $other.SHA256 -AttemptPath $case.AttemptPath -AttemptHash $case.AttemptHash} 'retry with another baseline';if($script:blockedCount -ne 0){throw 'Alternate baseline changed the source share.'}
    $case=New-FixtureShareCase CloseReviewedHandles $false 'alias-scope';$script:shares+=@([pscustomobject]@{Name='DataAlias';Path='C:\Fixture\data';ScopeName=''});$script:openFiles=@([pscustomobject]@{FileId=[UInt64]301;ScopeName='*';SessionId=[UInt64]701;Path='C:\Fixture\data\nested\file.bin';ShareRelativePath='nested\file.bin';ClientComputerName='client';ClientUserName='Fixture Writers'});$script:sessions=@([pscustomobject]@{SessionId=[UInt64]701;ClientComputerName='client';ClientUserName='Fixture Writers';NumOpens=1;ScopeName='*'});Assert-Throws {Invoke-FixtureDrain $case} 'same-root share alias handle must drain naturally';if($script:closed.Count -ne 0){throw 'Same-root aliased handle was closed automatically.'};$saved=Read-WsmJson $case.AttemptPath;if(@($saved.ShareQuiescence[0].OpenFiles | Where-Object {$_.OwnershipAmbiguous -and $_.ShareAliases -contains 'DataAlias'}).Count -ne 1){throw 'Same-root alias ambiguity was not retained in drain evidence.'}

    # File/session identifiers alone never bind a handle across scopes; the mismatched-scope row is ignored.
    $case=New-FixtureShareCase CloseReviewedHandles $false 'same-id-other-scope';$script:openFiles=@([pscustomobject]@{FileId=[UInt64]311;ScopeName='OTHER-SCOPE';SessionId=[UInt64]711;Path='C:\Fixture\data\foreign.bin';ShareRelativePath='foreign.bin';ClientComputerName='other';ClientUserName='Fixture Writers'});$script:sessions=@([pscustomobject]@{SessionId=[UInt64]711;ClientComputerName='other';ClientUserName='Fixture Writers';NumOpens=1;ScopeName='OTHER-SCOPE'});$drained=Invoke-FixtureDrain $case;if($drained.Status -ne 'Quiesced' -or $script:closed.Count){throw 'Same file ID in another scope was closed or blocked the selected unscoped share.'}
    $script:share.ScopeName='CLUSTER-A';$script:expectedHandleScope='CLUSTER-A';$script:openFiles=@([pscustomobject]@{FileId=[UInt64]312;ScopeName='CLUSTER-A';SessionId=[UInt64]712;Path='C:\Fixture\data\owned.bin';ShareRelativePath='owned.bin';ClientComputerName='cluster-client';ClientUserName='Fixture Writers'},[pscustomobject]@{FileId=[UInt64]312;ScopeName='CLUSTER-B';SessionId=[UInt64]712;Path='C:\Fixture\data\other.bin';ShareRelativePath='other.bin';ClientComputerName='foreign-client';ClientUserName='Fixture Writers'});$script:sessions=@([pscustomobject]@{SessionId=[UInt64]712;ClientComputerName='cluster-client';ClientUserName='Fixture Writers';NumOpens=1;ScopeName='CLUSTER-A'},[pscustomobject]@{SessionId=[UInt64]712;ClientComputerName='foreign-client';ClientUserName='Fixture Writers';NumOpens=1;ScopeName='CLUSTER-B'});$scoped=Get-WsmShareQuiescenceOpenFiles 'C:\Fixture\data' 'Data' 'CLUSTER-A';if($scoped.Files.Count -ne 1 -or $scoped.Files[0].FileId -ne 312 -or $scoped.Files[0].ScopeName -cne 'CLUSTER-A' -or $scoped.Sessions.Count -ne 1 -or $scoped.Sessions[0].ScopeName -cne 'CLUSTER-A'){throw 'Identical file/session IDs in another cluster scope contaminated the exact-scope open-file result.'}

    # The post-freeze inventory delta accepts only the recorded temporary deny and rejects any other source share drift.
    $case=New-FixtureShareCase BlockNewOpens $false 'inventory-proof';$drained=Invoke-FixtureDrain $case;$baseline=Read-WsmTrustedJson $case.BaselinePath $case.BaselineHash;$savedAttempt=Read-WsmTrustedJson $case.AttemptPath $drained.AttemptHash;$record=@($savedAttempt.ShareQuiescence | Where-Object ItemId -EQ $case.Item.ItemId)[0]
    $afterAccess=@($case.SourceItem.Settings.Access)+@([pscustomobject]@{AccountName=$script:world;AccessControlType='Deny';AccessRight='Full'})
    $afterItem=[pscustomobject]@{ItemId=$case.Item.ItemId;SettingsHash=('c'*64);Status='Success';Settings=[pscustomobject]@{Definition=$case.SourceItem.Settings.Definition;Access=$afterAccess}}
    $proof=Assert-WsmShareQuiescenceInventoryDelta $baseline $case.SourceItem $afterItem $record $case.BaselineHash;if(-not $proof.OnlyApprovedShareDenyChanged -or -not $proof.ExistingHandlesDrained){throw 'Exact approved source share delta was not proven.'}
    $driftedAccess=$afterAccess+@([pscustomobject]@{AccountName='Unowned User';AccessControlType='Allow';AccessRight='Full'});$driftedItem=[pscustomobject]@{ItemId=$case.Item.ItemId;SettingsHash=('d'*64);Status='Success';Settings=[pscustomobject]@{Definition=$case.SourceItem.Settings.Definition;Access=$driftedAccess}};Assert-Throws {Assert-WsmShareQuiescenceInventoryDelta $baseline $case.SourceItem $driftedItem $record $case.BaselineHash} 'additional access change in frozen inventory'
    $changedDefinition=[pscustomobject]@{Name='Data';Path='C:\Fixture\other';ScopeName=''};$driftedItem.Settings.Definition=$changedDefinition;$driftedItem.Settings.Access=$afterAccess;Assert-Throws {Assert-WsmShareQuiescenceInventoryDelta $baseline $case.SourceItem $driftedItem $record $case.BaselineHash} 'share definition change in frozen inventory'
    $tampered=$baseline.PSObject.Copy();$tampered.BatchId=[Guid]::NewGuid().ToString();Assert-Throws {Assert-WsmShareQuiescenceBaseline $tampered $case.Plan $case.Item $case.PlanHash} 'baseline from another batch'
    Write-Host 'PASS: SMB source share deny/drain/resume preserves exact ACLs, handles only exact-scope files, and rejects drift, unsafe handles, and unreviewed retries.'
} $root
