/* Offline, dependency-free console. All user and server values enter the DOM as text. */
(function () {
  'use strict';
  const state = { token: null, session: null, context: null, views: {}, actions: [], inventory: [], selected: new Set(), selectionReasons: new Map(), selectionDirty: false, inventoryPage: 0, inventoryPageSize: 50, inventoryTotal: 0, softwareChoices: new Map(), jobs: new Map(), activeAction: null, preview: null, drafts: new Map(), busy: false, jobPoll: null };
  const $ = id => document.getElementById(id);
  const el = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text !== undefined) n.textContent = String(text); return n; };
  const safeText = value => value == null || value === '' ? '—' : String(value);
  const isSensitive = p => p.sensitive === true || /password|secret|credential|token/i.test(p.name || '');
  function announce(message) { const box = $('notice'); box.textContent = message; box.hidden = false; $('error-summary').hidden = true; }
  function fail(message, errors) { const box = $('error-summary'); box.replaceChildren(); box.appendChild(el('strong', '', message)); if (errors && errors.length) { const ul = el('ul'); errors.forEach(item => ul.appendChild(el('li', '', item))); box.appendChild(ul); } box.hidden = false; $('notice').hidden = true; box.focus(); }
  function clearFailure() { $('error-summary').hidden = true; $('field-errors').hidden = true; }
  function endpoint(path, options) {
    const headers = Object.assign({ 'Accept': 'application/json' }, options && options.headers || {});
    if (state.token) headers['X-Wsm-Token'] = state.token;
    return fetch(path, Object.assign({}, options || {}, { headers, credentials: 'same-origin', cache: 'no-store' })).then(async response => {
      const body = response.status === 204 ? null : await response.json().catch(() => ({}));
      if (response.status === 401 || response.status === 403) { state.token = null; fail('本機工作階段已失效，請重新啟動工具並開啟新的操作頁面。'); throw new Error('session expired'); }
      if (!response.ok) { const error = new Error(body && body.message || `要求失敗（${response.status}）`); error.status = response.status; error.body = body; throw error; }
      return body;
    });
  }
  function rowsOf(data) { return Array.isArray(data) ? data : data && (data.items || data.rows || data.entries) || []; }
  function getView(name, refresh) {
    if (!refresh && state.views[name]) return Promise.resolve(state.views[name]);
    return endpoint(`/api/view?action=${encodeURIComponent(name)}`).then(data => { state.views[name] = data || {}; return data || {}; });
  }
  function pill(text, status) { const n = el('span', `tag ${statusClass(status)}`, text || status || '未知'); return n; }
  function statusClass(s) { const v = String(s || '').toLowerCase(); return /fail|block|conflict|error|denied/.test(v) ? 'danger' : /pending|defer|wait|unknown|external|review/.test(v) ? 'warn' : /ready|success|complete|approved|passed|verified/.test(v) ? 'success' : ''; }
  function statusName(value) { const names = { Selected: '已選取', NotSelected: '未選取', Approved: '已核准', Pending: '待核准', Ready: '可執行', DeferredSoftware: '等待軟體', BlockedConflict: '目的衝突', External: '外部處理', Failed: '失敗', Unknown: '未知', Running: '執行中', CancelRequested: '已要求取消', Cancelled: '已停止', Succeeded: '已完成', RestoreNow: '直接還原', WaitForInstall: '等待補裝' }; return names[value] || value || '未知'; }
  function renderSession(s) {
    $('session-label').textContent = `本機 session ${safeText(s.sessionId || s.id)}`; $('host-label').textContent = safeText(s.hostName || s.host); $('role-label').textContent = safeText(s.role); $('workspace-label').textContent = safeText(s.workspace || s.workRoot); $('pair-label').textContent = safeText(s.pairId || s.waveId); $('revision-label').textContent = `revision ${safeText(s.revision)}`; $('footer-session').textContent = `工作階段 ${safeText(s.sessionId || s.id)} · token 僅存於記憶體`;
    const details = $('context-details'); details.replaceChildren(); [['目前主機', s.hostName || s.host], ['執行角色', s.role], ['工作區', s.workspace || s.workRoot], ['配對／波次', s.pairId || s.waveId], ['本機執行身分', s.principal]].forEach(([label, value]) => { details.append(el('dt', '', label), el('dd', '', safeText(value))); });
  }
  function renderContext(c) { state.context = c; const roles = $('context-role'), pairs = $('context-pair'); roles.replaceChildren(); (c.roles || ['Source', 'Target', 'Manager']).forEach(role => { const value = typeof role === 'string' ? role : role.value || role.id; roles.appendChild(new Option(typeof role === 'string' ? role : role.label || value, value)); }); roles.value = c.role || state.session.role; pairs.replaceChildren(); (c.pairs || []).forEach(pair => pairs.appendChild(new Option(pair.label || pair.pairId, pair.pairId))); if (c.pairId && ![...pairs.options].some(option => option.value === c.pairId)) pairs.appendChild(new Option(c.pairId, c.pairId)); pairs.value = c.pairId || ''; }
  function clearActiveActionView() { state.activeAction = null; state.preview = null; $('action-picker').value = ''; $('parameter-fields').replaceChildren(el('p', 'empty-state', '角色或配對已變更；請重新選擇操作。草稿仍保留在目前頁面記憶體中。')); $('preview-panel').hidden = true; $('confirm-line').hidden = true; $('operation-confirm').checked = false; $('submit-operation').disabled = true; $('preview-operation').disabled = true; renderActionMetadata(null); }
  async function refreshContext() { try { const context = await endpoint('/api/context'); renderContext(context); return context; } catch (e) { if (e.message !== 'session expired') fail(`無法載入角色與配對選項：${e.message}`); return null; } }
  async function refreshSession(refreshView) { captureDraft(); invalidatePreview(); const oldContext = state.session && state.session.contextId, oldPair = state.session && state.session.pairId; try { const response = await fetch('/api/session', { headers: { Accept: 'application/json' }, credentials: 'same-origin', cache: 'no-store' }); if (!response.ok) throw new Error(`工作階段重新整理失敗（${response.status}）`); const session = await response.json(); const changed = oldContext !== session.contextId; state.session = session; state.token = session.token; state.views = {}; if (changed) { clearActiveActionView(); if (oldPair !== session.pairId) { state.drafts.clear(); state.selected.clear(); state.selectionReasons.clear(); state.selectionDirty = false; state.softwareChoices.clear(); } } renderSession(session); await refreshContext(); if (refreshView) { const active = location.hash.slice(1) || 'overview'; if (active === 'operations') await loadView('actions', true); else if (active === 'jobs') await refreshJobs(); else await loadView(active, true); } return !changed; } catch (e) { fail(`${e.message}。請重新啟動本機工具並確認主機及配對。`); return false; } }
  async function applyContext() { captureDraft(); const previous = state.session.pairId; const body = { pairId: $('context-pair').value, role: $('context-role').value, expectedRevision: state.context && state.context.revision != null ? state.context.revision : state.session.revision, contextId: state.session.contextId }; try { const next = await endpoint('/api/context', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); state.session.contextId = next.contextId; state.session.pairId = next.pairId; state.session.role = next.role; state.session.revision = next.revision; if (previous !== next.pairId) { state.drafts.clear(); state.selected.clear(); state.selectionReasons.clear(); state.selectionDirty = false; state.softwareChoices.clear(); } clearActiveActionView(); state.views = {}; renderSession(state.session); renderContext(next); await loadView(location.hash.slice(1) || 'overview', true); announce(`已切換到 ${next.role} 角色與配對 ${next.pairId || '未選擇'}。舊預覽已失效。`); } catch (e) { if (e.status === 409) { await refreshSession(true); fail('角色或配對已由其他視窗變更，請檢查目前上下文後再切換。'); } else if (e.message !== 'session expired') fail(`無法切換上下文：${e.message}`); } }
  function renderOverview(data) {
    const m = data.metrics || data.summary || {}; const entries = [['已發現', m.discovered], ['目前選取', m.selected], ['已核准', m.approved], ['本次可執行', m.executable], ['待處理／失敗', m.pendingOrFailed]];
    const metrics = $('metrics'); metrics.replaceChildren(); entries.forEach(([label, value]) => { const card = el('article', 'metric-card'); card.append(el('div', 'metric-label', label), el('div', 'metric-value', value == null ? '—' : value), el('div', 'metric-note', label === '本次可執行' ? '依目前有效核准範圍' : '本次工作負載')); metrics.appendChild(card); });
    const p = data.progress || {}; $('progress-value').textContent = p.percent == null ? '—' : `${p.percent}%`; $('workload-state').textContent = statusName(data.workloadStatus || 'ReviewRequired'); $('workload-state').className = `state-pill state-${statusClass(data.workloadStatus) || 'neutral'}`;
    $('next-step-title').textContent = safeText(data.nextStep && data.nextStep.title || '查看盤點與待處理項目'); $('next-step-copy').textContent = safeText(data.nextStep && data.nextStep.description || '選取狀態、核准狀態與本次可執行項目會分開列出。');
    const steps = $('workflow-steps'); steps.replaceChildren(); (data.steps || []).forEach((s, i) => { const li = el('li'); li.append(el('span', 'step-index', i + 1), el('div')); li.children[1].append(el('div', 'step-title', s.title), el('div', 'step-note', s.note)); li.appendChild(pill(statusName(s.status), s.status)); steps.appendChild(li); });
  }
  function inventoryItem(row) { return String(row.itemId || row.id || row.scopeId); }
  function renderInventory(data) {
    state.inventory = rowsOf(data); state.inventoryTotal = Number(data.totalCount == null ? state.inventory.length : data.totalCount); if (!state.selectionDirty) { state.selected.clear(); state.selectionReasons.clear(); state.inventory.forEach(row => { const id = inventoryItem(row); if (row.selectable !== false && row.selected === true) state.selected.add(id); else if (row.selected === false) state.selectionReasons.set(id, row.reason || ''); }); (data.selectedItemIds || []).forEach(id => { const row = state.inventory.find(item => inventoryItem(item) === String(id)); if (row && row.selectable !== false) state.selected.add(String(id)); }); }
    if (data.pageSize) state.inventoryPageSize = Number(data.pageSize); state.inventoryPage = Math.max(0, Math.min(state.inventoryPage, Math.ceil(Math.max(state.inventoryTotal, 1) / state.inventoryPageSize) - 1));
    const filter = $('category-filter'), old = filter.value, cats = [...new Set(state.inventory.map(r => r.category).filter(Boolean))]; filter.replaceChildren(el('option', '', '所有類別')); filter.options[0].value = ''; cats.forEach(c => { const o = el('option', '', c); o.value = c; filter.appendChild(o); }); filter.value = cats.includes(old) ? old : '';
    paintInventory();
  }
  function paintInventory() {
    const query = $('inventory-search').value.trim().toLocaleLowerCase(), category = $('category-filter').value, body = $('inventory-rows'); body.replaceChildren(); const filtered = state.inventory.filter(r => (!category || r.category === category) && (!query || [r.name, r.path, r.itemId, r.source, r.category].some(v => String(v || '').toLocaleLowerCase().includes(query)))); const pages = Math.max(1, Math.ceil(filtered.length / state.inventoryPageSize)); state.inventoryPage = Math.min(state.inventoryPage, pages - 1); const start = state.inventoryPage * state.inventoryPageSize; const shown = filtered.slice(start, start + state.inventoryPageSize);
    shown.forEach(r => { const id = inventoryItem(r), tr = el('tr'), selectable = r.selectable !== false; const checkTd = el('td'), check = el('input'); check.type = 'checkbox'; check.checked = selectable && state.selected.has(id); check.disabled = !selectable; check.setAttribute('aria-label', `選取 ${safeText(r.name || r.path || id)}`); check.addEventListener('change', () => { if (!selectable) return; if (check.checked) { state.selected.add(id); state.selectionReasons.delete(id); } else state.selected.delete(id); state.selectionDirty = true; paintInventory(); if (!check.checked) { const reason = [...$('inventory-rows').querySelectorAll('.selection-reason')].find(n => n.getAttribute('aria-label') === `未選取原因：${safeText(r.name || id)}`); if (reason) reason.focus(); } }); checkTd.appendChild(check); if (!selectable) { checkTd.appendChild(el('div', 'item-sub', r.reason || '此項目目前不可選取。')); } else if (!check.checked) { const reason = el('input'); reason.type = 'text'; reason.className = 'selection-reason'; reason.placeholder = '未選原因'; reason.setAttribute('aria-label', `未選取原因：${safeText(r.name || id)}`); reason.value = state.selectionReasons.get(id) || r.reason || ''; reason.addEventListener('input', () => { state.selectionReasons.set(id, reason.value); state.selectionDirty = true; }); checkTd.appendChild(reason); } tr.appendChild(checkTd);
      const item = el('td'); item.append(el('div', 'item-title', r.name || r.path || id), el('div', 'item-sub', r.path || r.source || id)); const review = el('button', 'quiet-button', '審閱規格'); review.type = 'button'; review.classList.add('spec-review-button'); review.addEventListener('click', () => openSpecReview(id)); item.appendChild(review); tr.appendChild(item); tr.appendChild(el('td', '', r.category || '未分類')); const approval = el('td'); approval.appendChild(pill(statusName(r.approvalStatus || (r.approved ? 'Approved' : 'Pending')), r.approvalStatus || (r.approved ? 'Approved' : 'Pending'))); tr.appendChild(approval); const readiness = el('td'); readiness.appendChild(pill(statusName(r.executionStatus || r.status), r.executionStatus || r.status)); tr.appendChild(readiness); tr.appendChild(el('td', '', r.impact || r.dependenciesSummary || '無已知相依')); body.appendChild(tr); });
    $('inventory-count').textContent = `${filtered.length} 筆符合篩選 · 顯示 ${filtered.length ? start + 1 : 0}–${Math.min(start + state.inventoryPageSize, filtered.length)}`; $('inventory-page-label').textContent = `第 ${state.inventoryPage + 1} / ${pages} 頁`; $('inventory-previous').disabled = state.inventoryPage === 0; $('inventory-next').disabled = state.inventoryPage >= pages - 1; $('inventory-page-size').value = String(state.inventoryPageSize); updateSelectionCount();
  }
  function updateSelectionCount() { const rows = state.inventory.filter(row => row.selectable !== false), ids = rows.map(inventoryItem); $('selection-summary').textContent = `目前選取 ${ids.filter(id => state.selected.has(id)).length} / ${ids.length} 筆可選項目（另有 ${state.inventory.length - rows.length} 筆暫不可選）`; }
  function renderSoftware(data) { const body = $('software-rows'); body.replaceChildren(); rowsOf(data).forEach((r, index) => { const id = String(r.softwareId || r.id || r.name || index), tr = el('tr'); tr.appendChild(el('td', '', r.name || r.displayName)); tr.appendChild(el('td', '', safeText(r.sourceVersion))); const choiceTd = el('td'), select = document.createElement('select'), custom = el('input'); select.setAttribute('aria-label', `選擇 ${safeText(r.name || id)} 的軟體版本`); select.appendChild(new Option('輸入其他版本…', '__custom__')); (r.versionChoices || []).forEach(opt => select.appendChild(new Option(opt.label || opt.value || opt, opt.value == null ? opt : opt.value))); custom.type = 'text'; custom.autocomplete = 'off'; custom.placeholder = '輸入欲安裝版本'; custom.setAttribute('aria-label', `${safeText(r.name || id)} 的其他版本`); const saved = state.softwareChoices.get(id), initial = saved == null ? String(r.chosenVersion || r.selectedVersion || '') : saved; if ((r.versionChoices || []).some(opt => String(opt.value == null ? opt : opt.value) === initial)) { select.value = initial; custom.hidden = true; } else { select.value = '__custom__'; custom.value = initial; } select.addEventListener('change', () => { const value = select.value === '__custom__' ? custom.value : select.value; custom.hidden = select.value !== '__custom__'; state.softwareChoices.set(id, value); }); custom.addEventListener('input', () => state.softwareChoices.set(id, custom.value)); choiceTd.append(select, custom); tr.appendChild(choiceTd); tr.appendChild(el('td', '', safeText(r.observedVersion || r.targetVersion))); tr.appendChild(el('td', '', safeText(r.actionOwner || r.manualAction || r.owner))); const status = el('td'); status.appendChild(pill(statusName(r.status || r.readiness), r.status || r.readiness)); const save = el('button', 'quiet-button', '保存版本選擇'); save.type = 'button'; save.addEventListener('click', () => saveSoftwareChoice(id, select.value === '__custom__' ? custom.value.trim() : select.value)); status.appendChild(save); tr.appendChild(status); body.appendChild(tr); }); if (!body.children.length) body.appendChild(emptyRow(6, '尚無軟體差異資料。')); }
  async function saveSoftwareChoice(softwareId, chosenVersion) { if (!chosenVersion) { fail('請選擇或輸入明確的軟體版本。'); return; } try { const data = await endpoint('/api/operations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(buildOperationRequest('SetSoftwareVersion', { softwareId, chosenVersion }, state.session.revision)) }); if (data.revision != null) { state.session.revision = data.revision; $('revision-label').textContent = `revision ${data.revision}`; } state.softwareChoices.set(softwareId, chosenVersion); announce(`已保存選用版本 ${chosenVersion}。目標觀測版本仍以重新檢查結果為準。`); } catch (e) { if (e.status === 409) { fail('工作資料已更新。選用版本草稿已保留；請重新載入比較資料並再次保存。'); } else if (e.message !== 'session expired') fail(e.message); } }
  function observed(value) { return value == null || value === '' || /^(unknown|notobserved|notmeasured|unobserved)$/i.test(String(value)) ? '未知（未觀測）' : String(value); }
  function renderFiles(data) { const body = $('file-rows'); body.replaceChildren(); rowsOf(data).forEach(r => { const tr = el('tr'); const original = r.originalPath ?? r.sourcePath ?? r.OriginalPath ?? r.SourcePath, preserved = r.preservedPath ?? r.archivePath ?? r.PreservedPath ?? r.ArchivePath, effective = r.effectivePath ?? r.EffectivePath; [observed(original), observed(preserved), observed(effective), '', safeText(r.scopeImpact ?? r.impact)].forEach(v => tr.appendChild(el('td', '', v))); const statusCell = tr.children[3]; statusCell.appendChild(pill(statusName(r.placementStatus || r.status), r.placementStatus || r.status)); statusCell.appendChild(el('div', 'item-sub', `來源 SHA-256：${observed(r.sourceHash ?? r.SourceHash)}`)); statusCell.appendChild(el('div', 'item-sub', `讀回 SHA-256：${observed(r.readbackHash ?? r.ReadbackHash)}`)); statusCell.appendChild(el('div', 'item-sub', `衝突 SHA-256：${observed(r.conflictHash ?? r.ConflictHash)}`)); statusCell.appendChild(el('div', 'item-sub', `原因：${safeText(r.reason ?? r.Reason)}`)); body.appendChild(tr); }); if (!body.children.length) body.appendChild(emptyRow(5, '尚無檔案路徑資料。')); }
  const reviewFieldNames = new Set(['TargetPath', 'TransferChannel', 'ContentSelection', 'ExcludedRelativePaths', 'Consistency', 'Metadata', 'ConflictPolicy', 'ConfigFiles', 'ConfigOverrides', 'DesiredFinalState', 'BusinessChecks', 'Product', 'Procedure', 'Artifacts', 'CatchUpPolicy', 'WorkloadFieldReviews', 'IisBindings', 'IisApplicationPools', 'IisPoolSettings', 'IisConfigChanges', 'DesiredChanges', 'ActivationPolicyFieldPointer', 'SharedResourceReviewReasons', 'ActivationOwner', 'ActivationReason', 'PrincipalUser']);
  function safeReviewValue(value, key) { if (/(secret|password|credential|token|privatekey|sddl|xml|arguments|script|command)/i.test(String(key || ''))) return undefined; if (typeof value === 'string' && /(password|passwd|secret|token|credential|api[_-]?key)\s*[:=]\s*[^\s;]+/i.test(value)) return '[敏感內容已隱去]'; if (value == null || ['string', 'number', 'boolean'].includes(typeof value)) return value; if (Array.isArray(value)) return value.map(item => safeReviewValue(item, key)).filter(item => item !== undefined); if (typeof value === 'object') { const safe = {}; Object.entries(value).forEach(([name, item]) => { const child = safeReviewValue(item, name); if (child !== undefined) safe[name] = child; }); return safe; } return undefined; }
  function safeTypedFields(review) { const typed = review && (review.TypedFields || review.typedFields) || {}; const safe = {}; Object.entries(typed).forEach(([name, value]) => { if (!reviewFieldNames.has(name)) return; const clean = safeReviewValue(value, name); if (clean !== undefined) safe[name] = clean; }); return safe; }
  function specReviewDialog() { const panel = $('spec-review-panel'); if (!panel) return null; const button = $('spec-review-prefill'); if (!button.dataset.bound) { button.dataset.bound = 'true'; button.addEventListener('click', () => { if (state.lastSpecReview) prefillSpecReview(state.lastSpecReview); }); $('spec-review-close').addEventListener('click', () => { panel.hidden = true; }); } return panel; }
  function appendReviewList(list, values) { list.replaceChildren(); (values || []).forEach(item => { const text = typeof item === 'string' ? item : [item.FieldPointer || item.fieldPointer, item.ReferenceKind || item.referenceKind, item.Status || item.status, item.Reason || item.reason].filter(Boolean).join(' · '); list.appendChild(el('li', '', text || JSON.stringify(item))); }); if (!list.children.length) list.appendChild(el('li', '', '無')); }
  const iisReviewLabels = { Index:'來源列', Protocol:'通訊協定', BindingInformation:'繫結位址', CertificateHash:'憑證指紋', CertificateStoreName:'憑證存放區', SslFlags:'SSL 旗標', ApplicationPath:'應用程式路徑', PoolName:'應用程式集區', managedRuntimeVersion:'Managed Runtime', managedPipelineMode:'Pipeline 模式', enable32BitAppOnWin64:'32 位元應用程式', startMode:'啟動模式', queueLength:'佇列上限', autoStart:'自動啟動' };
  function appendSafeReviewTable(host, title, rows, fields, labels) { if (!Array.isArray(rows) || !rows.length) return; const section = el('section', 'spec-review-section'); section.appendChild(el('h3', '', title)); const region = el('div', 'table-wrap'); region.setAttribute('role', 'region'); region.setAttribute('tabindex', '0'); region.setAttribute('aria-label', `${title}，可水平捲動`); const table = document.createElement('table'), head = document.createElement('thead'), header = document.createElement('tr'), body = document.createElement('tbody'); fields.forEach(field => header.appendChild(el('th', '', labels[field] || field))); head.appendChild(header); table.append(head, body); rows.forEach(row => { const tr = document.createElement('tr'); fields.forEach(field => tr.appendChild(el('td', '', row && row[field] != null && row[field] !== '' ? row[field] : '（未設定）'))); body.appendChild(tr); }); region.appendChild(table); section.appendChild(region); host.appendChild(section); }
  function appendIisReview(host, typed) { appendSafeReviewTable(host, 'IIS 網站繫結（來源安全欄位）', typed.IisBindings, ['Index','Protocol','BindingInformation','CertificateHash','CertificateStoreName','SslFlags'], iisReviewLabels); appendSafeReviewTable(host, 'IIS 應用程式集區對應（來源安全欄位）', typed.IisApplicationPools, ['Index','ApplicationPath','PoolName'], iisReviewLabels); if (typed.IisPoolSettings && typeof typed.IisPoolSettings === 'object') { const rows = Object.entries(typed.IisPoolSettings).filter(([key, value]) => Object.prototype.hasOwnProperty.call(iisReviewLabels, key) && ['string','number','boolean'].includes(typeof value)).map(([Key, Value]) => ({ Key, Value })); appendSafeReviewTable(host, 'IIS 集區設定（來源安全欄位）', rows, ['Key','Value'], { Key:'設定', Value:'目前值' }); } }
  function renderSpecReview(review) { state.lastSpecReview = review; const panel = specReviewDialog(); if (!panel) { fail('頁面缺少規格審閱區塊。'); return; } const fieldsList = $('spec-review-fields'); fieldsList.replaceChildren(); const summary = el('dd', 'item-sub', `項目 ${safeText(review.ItemId || review.itemId)} · ${safeText(review.Adapter || review.adapter)} · 決策 revision ${safeText(review.DecisionRevision)}、Assistive revision ${safeText(review.AssistiveRevision)}、選取 revision ${safeText(review.SelectionRevision)}。未包含原始 XML 或 secrets。`); fieldsList.append(el('dt', '', '審閱範圍'), summary); [['負責人', review.Owner], ['佐證', review.Evidence], ['最終狀態', review.DesiredFinalState], ['來源 XML SHA-256', review.SourceXmlSHA256], ['目標 XML SHA-256', review.TargetXmlSHA256]].forEach(([label, value]) => fieldsList.append(el('dt', '', label), el('dd', '', safeText(value)))); const typed = safeTypedFields(review); Object.entries(typed).filter(([name]) => !['IisBindings','IisApplicationPools','IisPoolSettings'].includes(name)).forEach(([name, value]) => fieldsList.append(el('dt', '', name), el('dd', '', JSON.stringify(value)))); appendIisReview(panel, typed); $('spec-review-counts').textContent = [['排程動作', review.WorkloadActions], ['IIS bindings', review.IisBindings], ['IIS applications', review.IisApplications]].map(([label, rows]) => `${label}：${Array.isArray(rows) ? rows.length : 0}`).join(' · '); appendReviewList($('spec-review-missing'), review.MissingTypedFields || []); const opaque = [...(review.OpaqueReviewRequired || []), ...(review.WorkloadPathReferences || []).filter(item => item.Opaque || item.ReviewRequired)]; appendReviewList($('spec-review-pointers'), opaque); let shared = $('spec-review-shared'); if (!shared) { shared = el('section', 'spec-review-section'); shared.id = 'spec-review-shared'; shared.appendChild(el('h3', '', '共享資源審閱理由')); const list = el('ul'); list.id = 'spec-review-shared-list'; shared.appendChild(list); panel.appendChild(shared); } appendReviewList($('spec-review-shared-list'), review.SharedResourceReviewReasons || []); $('spec-review-prefill').disabled = !metadataFor('SaveSpecReview'); panel.hidden = false; panel.scrollIntoView({ block: 'nearest' }); }
  async function openSpecReview(itemId) { try { const review = await endpoint(`/api/spec-review?itemId=${encodeURIComponent(itemId)}`); if (!metadataFor('SaveSpecReview')) renderActions(await getView('actions')); renderSpecReview(review); } catch (e) { if (e.message !== 'session expired') fail(`無法載入項目 ${itemId} 的規格審閱：${e.message}`); } }
  function prefillSpecReview(review) { const action = 'SaveSpecReview', metadata = metadataFor(action); if (!metadata) { fail('目前操作清單未提供「保存規格審閱」欄位；請檢查操作上下文。是否可執行仍由 Windows 權限與核心審核條件決定。'); return false; } navigate('operations'); $('spec-review-panel').hidden = true; $('action-picker').value = action; setAction(action); const typed = safeTypedFields(review), values = { ItemId: review.ItemId || review.itemId, ExpectedDecisionRevision: review.DecisionRevision, ExpectedAssistiveRevision: review.AssistiveRevision, ExpectedSelectionRevision: review.SelectionRevision, Owner: review.Owner || '', Evidence: review.Evidence || '', Fields: typed }; metadata.parameters.forEach((parameter, index) => { const value = values[parameter.name]; if (value === undefined) return; if (parameter.name === 'Fields' && parameter.type === 'object') { const allowed = new Set(Object.keys(parameter.schema && parameter.schema.properties || {})); const flattened = {}; Object.entries(typed).forEach(([name, fieldValue]) => { if (allowed.has(name)) flattened[name] = fieldValue; }); restoreDraftValue(parameter, $(`param-${index}`), flattened); } else restoreDraftValue(parameter, $(`param-${index}`), value); }); captureDraft(); $('parameter-fields').focus?.(); announce('已把規格審閱摘要帶入保存表單；請確認負責人、佐證與型別欄位，再預覽並提交。'); return true; }
  function createWindowsSettingsReviewDraft(output) {
    if (!output || output.Kind !== 'AssistiveWindowsSettingsPreviewOutput' || !Array.isArray(output.Rows)) return null;
    const hash = value => typeof value === 'string' && /^[a-f0-9]{64}$/i.test(value);
    const revisionText = typeof output.ExpectedRevision === 'string' ? output.ExpectedRevision : '';
    const validRevision = Number.isSafeInteger(output.ExpectedRevision) && output.ExpectedRevision >= 0 || /^\d+$/.test(revisionText) && Number.isSafeInteger(Number(revisionText));
    if (!state.session || !output.PairId || output.PairId !== state.session.pairId || typeof output.ReviewWindowsSettings !== 'boolean' || typeof output.SourceInventoryPath !== 'string' || !output.SourceInventoryPath || !hash(output.SourceInventoryHash) || typeof output.TargetInventoryPath !== 'string' || !output.TargetInventoryPath || !hash(output.TargetInventoryHash) || typeof output.PreviewPath !== 'string' || !output.PreviewPath || !hash(output.PreviewFileHash) || !validRevision) return null;
    const allowedActions = new Set(['KeepTarget', 'External', 'ReviewedMigration']), ids = new Set(), decisions = [];
    for (const row of output.Rows) {
      if (!row || typeof row.SettingId !== 'string' || !row.SettingId.trim() || ids.has(row.SettingId)) return null;
      ids.add(row.SettingId);
      const supported = Array.isArray(row.SupportedActions) ? row.SupportedActions : [];
      const action = allowedActions.has(row.DefaultAction) && (!supported.length || supported.includes(row.DefaultAction)) ? row.DefaultAction : '';
      decisions.push({ SettingId: row.SettingId, Action: action, Owner: '', Reason: '', Evidence: '' });
    }
    return { Workspace: state.session.workspace || state.session.workRoot || '', PairId: output.PairId, SourceInventoryPath: output.SourceInventoryPath, SourceInventoryHash: output.SourceInventoryHash, TargetInventoryPath: output.TargetInventoryPath, TargetInventoryHash: output.TargetInventoryHash, PreviewPath: output.PreviewPath, PreviewHash: output.PreviewFileHash, ExpectedRevision: Number(output.ExpectedRevision), ReviewWindowsSettings: output.ReviewWindowsSettings, Decisions: decisions };
  }
  async function prefillWindowsSettingsReview(output) {
    const values = createWindowsSettingsReviewDraft(output);
    if (!values) { fail('此工作沒有完整且有效的 Windows 設定預覽投影，無法帶入審閱草稿。'); return false; }
    if (!metadataFor('WindowsSettingsSubmit')) {
      try { renderActions(await getView('actions')); } catch (error) { if (error.message !== 'session expired') fail(`無法載入 Windows 設定審閱操作：${error.message}`); return false; }
    }
    const action = 'WindowsSettingsSubmit', metadata = metadataFor(action);
    if (!metadata) { fail('目前操作清單未提供「提交 Windows 設定審閱」欄位；請檢查操作上下文。實際執行仍須通過 Windows 權限與核心審核條件。'); return false; }
    if (!metadata.parameters.some(parameter => parameter.name === 'Decisions' && parameter.type === 'objectArray')) { fail('伺服端尚未提供逐項 Windows 設定決策欄位。'); return false; }
    navigate('operations'); $('action-picker').value = action; setAction(action);
    metadata.parameters.forEach((parameter, index) => { if (Object.prototype.hasOwnProperty.call(values, parameter.name)) restoreDraftValue(parameter, $(`param-${index}`), values[parameter.name]); });
    captureDraft(); $('operation-confirm').checked = false; $('submit-operation').disabled = true; $('preview-panel').hidden = true; $('confirm-line').hidden = true;
    announce(`已從預覽帶入 ${values.Decisions.length} 筆設定審閱草稿。請確認每筆操作、填寫負責人與佐證，再預覽及明確提交；目前尚未提交。`); return true;
  }
  function createRequirementDecisionDraft(output) {
    if (!output || output.Kind !== 'AssistiveRequirementReview' || !Array.isArray(output.Rows)) return null;
    const hash = value => typeof value === 'string' && /^[a-f0-9]{64}$/i.test(value), revisionText = typeof output.ExpectedRevision === 'string' ? output.ExpectedRevision : '';
    const validRevision = Number.isSafeInteger(output.ExpectedRevision) && output.ExpectedRevision >= 0 || /^\d+$/.test(revisionText) && Number.isSafeInteger(Number(revisionText));
    if (!state.session || !output.PairId || output.PairId !== state.session.pairId || !hash(output.ReviewHash) || !validRevision) return null;
    const ids = new Set(), decisions = [], allowed = new Set(['Pending','Required','NotNeeded']);
    for (const row of output.Rows) { if (!row || typeof row.RequirementId !== 'string' || !row.RequirementId.trim() || ids.has(row.RequirementId)) return null; ids.add(row.RequirementId); decisions.push({ RequirementId: row.RequirementId, Decision: allowed.has(row.Decision) ? row.Decision : 'Pending', Owner: '', DecisionReason: '', DecisionEvidence: '' }); }
    return { Workspace: state.session.workspace || state.session.workRoot || '', PairId: output.PairId, ExpectedRevision: Number(output.ExpectedRevision), ReviewHash: output.ReviewHash, Decisions: decisions };
  }
  async function prefillRequirementDecisionReview(output) {
    const values = createRequirementDecisionDraft(output);
    if (!values) { fail('此工作沒有完整且有效的需求審閱投影，無法帶入草稿。'); return false; }
    if (!metadataFor('RequirementDecisionSubmit')) { try { renderActions(await getView('actions')); } catch (error) { if (error.message !== 'session expired') fail(`無法載入需求審閱操作：${error.message}`); return false; } }
    const metadata = metadataFor('RequirementDecisionSubmit');
    if (!metadata) { fail('目前操作清單未提供「提交需求決策」欄位；請檢查操作上下文。實際執行仍須通過 Windows 權限與核心審核條件。'); return false; }
    if (!metadata.parameters.some(parameter => parameter.name === 'Decisions' && parameter.type === 'objectArray')) { fail('伺服端尚未提供逐項需求決策欄位。'); return false; }
    navigate('operations'); $('action-picker').value = 'RequirementDecisionSubmit'; setAction('RequirementDecisionSubmit');
    metadata.parameters.forEach((parameter, index) => { if (Object.prototype.hasOwnProperty.call(values, parameter.name)) restoreDraftValue(parameter, $(`param-${index}`), values[parameter.name]); });
    captureDraft(); $('operation-confirm').checked = false; $('submit-operation').disabled = true; $('preview-panel').hidden = true; $('confirm-line').hidden = true;
    announce(`已從完整預覽帶入 ${values.Decisions.length} 筆需求決策草稿。請逐項確認決策、填寫負責人與理由／佐證，然後預覽並明確確認；尚未送出確認或提交。`); return true;
  }
  const projectedRowLabels = { SettingId:'設定識別碼', SourceItemId:'來源項目', Category:'類別', Kind:'類型', SettingName:'設定名稱', SourceValueHash:'來源值 SHA-256', TargetValueHash:'目標值 SHA-256', TargetDiff:'目標差異', ControlSource:'控制來源', SupportedActions:'可選處置', DefaultAction:'建議處置', RequiredConsumerItemIds:'相依消費者', RequirementId:'需求識別碼', ProviderSoftwareId:'提供者軟體', ExpectedVersion:'預期版本', Architecture:'架構', RequiredPhase:'需求階段', Decision:'目前決策', Certainty:'確定度', ConsumerItemIds:'相依消費者', ContextHash:'上下文 SHA-256' };
  function appendProjectedRows(host, output) {
    const settings = output && output.Kind === 'AssistiveWindowsSettingsPreviewOutput', preparation = output && output.Kind === 'AssistivePreparationPreview', requirementReview = output && output.Kind === 'AssistiveRequirementReview';
    if (!settings && !preparation && !requirementReview) return;
    const fields = settings ? ['SettingId','SettingName','Category','Kind','SourceItemId','SourceValueHash','TargetValueHash','TargetDiff','ControlSource','SupportedActions','DefaultAction','RequiredConsumerItemIds'] : preparation ? ['RequirementId','ProviderSoftwareId','ExpectedVersion','Architecture','RequiredPhase','Decision','Certainty','ConsumerItemIds','ContextHash'] : ['RequirementId','Type','ProviderSoftwareId','ProviderItemId','ExternalId','ExpectedVersion','Architecture','RequiredPhase','Decision','Certainty','ConsumerItemIds','ContextHash'];
    const rows = Array.isArray(output.Rows) ? output.Rows : [], region = el('div', 'table-wrap'); region.setAttribute('role', 'region'); region.setAttribute('tabindex', '0'); region.setAttribute('aria-label', settings ? 'Windows 設定預覽安全欄位，可水平捲動' : '目標準備需求預覽安全欄位，可水平捲動');
    const table = document.createElement('table'), head = document.createElement('thead'), header = document.createElement('tr'), body = document.createElement('tbody'); fields.forEach(field => header.appendChild(el('th', '', projectedRowLabels[field]))); head.appendChild(header); table.append(head, body);
    rows.forEach(row => { const tr = document.createElement('tr'); fields.forEach(field => { const value = row && row[field], cell = el('td'); if (Array.isArray(value) && value.every(item => ['string','number','boolean'].includes(typeof item))) cell.textContent = value.length ? value.join('、') : '—'; else if (['string','number','boolean'].includes(typeof value)) cell.textContent = String(value); else cell.textContent = '—'; tr.appendChild(cell); }); body.appendChild(tr); });
    if (!rows.length) body.appendChild(emptyRow(fields.length, '此安全投影沒有列出需求列。'));
    region.appendChild(table); host.appendChild(region);
  }
  function emptyRow(cols, message) { const tr = el('tr'), td = el('td', 'empty-state', message); td.colSpan = cols; tr.appendChild(td); return tr; }
  const actionTerms = { Source:'來源', Snapshot:'快照', Inventory:'盤點', Target:'目標', Preparation:'準備', Restore:'還原', Preview:'預覽', Rollback:'回復', Save:'保存', Spec:'規格', Review:'審閱', Assistive:'輔助流程', Report:'報告', Check:'檢查', Comparison:'比較', Publish:'發布', Software:'軟體', Version:'版本', File:'檔案', Placement:'放置', Non:'非', C:'C 檔案', Peer:'同端', Share:'共享', Proof:'證明', Physical:'實體', Plan:'計畫', Transfer:'傳輸', Import:'匯入', Export:'匯出', Reserve:'保留', Reservation:'保留', Resource:'資源', Evidence:'佐證', Release:'釋放', Register:'登錄', Material:'材料', Close:'結案', Job:'工作', Lock:'鎖定', Cleanup:'清理', Environment:'環境', Probe:'檢查', Enable:'啟用', Selections:'選取', Selection:'選取', Decision:'決策', Receipt:'收據', Workspace:'工作區', Delivery:'交付', Document:'文件', Windows:'Windows', Settings:'設定', Apply:'套用', Qualification:'資格', Signing:'簽署', Request:'申請', Complete:'完成', Tool:'工具', Delta:'差異', Directory:'目錄', General:'一般', Host:'主機', Disposition:'處置', Requirement:'需求', SoftwareCatalog:'軟體目錄', Output:'輸出', Initialize:'初始化', Resolve:'解析', Pair:'配對', Confirm:'確認', State:'狀態', Preferences:'偏好設定', Enrolled:'已納管', Package:'套件', Oracle:'Oracle', Binding:'繫結', Config:'設定', Draft:'草稿', Confirmation:'確認', Volumes:'磁碟區', Lab:'實驗室', Validation:'驗證', Raw:'原始', Artifact:'產物', Manifest:'清單', Zip:'ZIP', Repair:'修復', Cancellation:'取消', Token:'代碼', Group:'群組', Barrier:'屏障', Record:'記錄', Add:'新增', Revoke:'撤銷', Lookup:'查詢', Matrix:'矩陣', Task:'工作排程', Resume:'續跑', Bundle:'套件', RegisterTarget:'登錄目標', Identity:'身分', Map:'對應', Configure:'設定', Approve:'核准', Estimate:'估算', Freeze:'凍結', Acceptance:'驗收', Stage:'階段', Cutover:'切換', Journal:'日誌', Fleet:'主機群', Dependencies:'相依項目', Mapping:'映射', Manual:'人工', Item:'項目', Metadata:'中繼資料', Template:'範本', SaveSelection:'保存選取', SelectionReason:'未選原因', DirectoryDelivery:'目錄交付', Migration:'搬移', Operation:'操作', Result:'結果', Imported:'匯入', WindowsSettings:'Windows 設定', TargetReceipt:'目標收據', SourceResult:'來源結果', IdentityMap:'身分對應', SoftwareVersion:'軟體版本', PackageEstimate:'套件估算', TargetSnapshot:'目標快照', SpecBundle:'規格套件', WorkspaceTransfer:'工作區傳輸', NonCPlan:'非 C 檔案計畫', FilePlacement:'檔案放置', CancellationToken:'取消權杖', RequestCancellation:'要求取消', AssistiveReportCheck:'輔助流程報告檢查' };
  const actionOverrides = { SourceSnapshot:'來源主機快照', SourceInventory:'來源主機盤點', TargetSnapshot:'目標現況快照', TargetPreparation:'目標環境準備', Restore:'執行還原', RestorePreview:'還原範圍預覽', Rollback:'執行回復', RollbackPreview:'回復範圍預覽', SaveSpecReview:'保存規格審閱', SpecReview:'查看規格審閱', AssistiveReport:'匯出管理報告', AssistiveReportCheck:'檢查管理報告', HttpIntegrityProbe:'檢查本機頁面傳輸完整性', WindowsSettingsPreviewExport:'匯出 Windows 設定審閱預覽', WindowsSettingsSubmit:'提交 Windows 設定審閱', DispositionSubmit:'提交一般主機處置審閱', RequirementReview:'預覽一般主機需求審閱', RequirementDecisionSubmit:'提交一般主機需求決策', RequirementSubmit:'提交一般主機需求審閱（進階）', PreparationPreview:'預覽目標準備需求', PreparationEvidence:'匯出準備佐證', Report:'匯出審核報告', FleetReport:'匯出主機群報告', Inventory:'匯出來源盤點', SaveSelection:'保存項目選取' };
  const safeJobOutputFields = new Set(['Status','Stage','Path','SHA256','Hash','ReportPath','HtmlPath','ManifestPath','ManifestHash','Archive','ArchiveSHA256','RunId','PairId','Generation','Revision','ObservedChecks','PendingChecks','SpecPath','SpecHash','ReceiptPath','ReceiptHash','DecisionRevision','AssistiveRevision','SelectionRevision','TargetPhysicalId','RegistryRevision','ResourceKey','DocumentManifestPath','DocumentManifestHash','DocumentId','BundlePath','MemberCount','Valid','ProbeStatus','IndexPath','Kind','ExpectedRevision','PreviewPath','PreviewFileHash','PreviewHash','ReviewHash','ReviewWindowsSettings','RowCount','SourceInventoryPath','SourceInventoryHash','TargetInventoryPath','TargetInventoryHash','GeneratedDecisionsPath','GeneratedDecisionsHash','GeneratedRequirementsPath','GeneratedRequirementsHash','FailureCode']);
  function translatedWords(value) { return String(value || '').replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/([A-Z])([A-Z][a-z])/g, '$1 $2').split(/[^A-Za-z0-9]+/).filter(Boolean).map(word => actionTerms[word] || '').filter(Boolean).join(''); }
  function actionLabel(action, fallbackOrOrdinal) { if (actionOverrides[action]) return actionOverrides[action]; const tokens = String(action || '').replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/([A-Z])([A-Z][a-z])/g, '$1 $2').split(/[^A-Za-z0-9]+/).filter(Boolean), words = translatedWords(action); if (tokens.length && tokens.every(word => actionTerms[word])) return words; if (typeof fallbackOrOrdinal === 'string' && /[\u3400-\u9fff]/.test(fallbackOrOrdinal)) return fallbackOrOrdinal; return `其他進階操作（第 ${typeof fallbackOrOrdinal === 'number' ? fallbackOrOrdinal : 1} 項）`; }
  function actionGroup(action) { if (/(Source|Inventory|FreezeSource|SourceResult|PeerShareProof|NonCPlan|SourceTask|SourceResume)/.test(action)) return 'Source'; if (/(Target|Preparation|Restore|Rollback|Cutover|Validation|Resource|Reservation|Reserve|Release|Cleanup|NonCPhysical|NonCTransfer|TargetSnapshot|TargetReceipt|WorkspaceTransferRestore)/.test(action)) return 'Target'; return 'Manager'; }
  const actionGroupLabels = { Source:'來源端｜盤點與來源材料', Manager:'管理端｜審閱、交付與協調', Target:'目標端｜準備、套用與驗證' };
  function renderActions(data) { state.actions = Array.isArray(data) ? data : data.actions || []; const select = $('action-picker'); select.replaceChildren(new Option('請選擇操作', '')); const groups = new Map(); ['Source','Manager','Target'].forEach(key => { const group = document.createElement('optgroup'); group.label = actionGroupLabels[key]; groups.set(key, group); select.appendChild(group); }); state.actions.forEach((a, index) => { const action = a.action || a.id, o = new Option(actionLabel(action, index + 1), action); o.dataset.action = action; groups.get(actionGroup(action)).appendChild(o); }); }
  function metadataFor(action) { return state.actions.find(a => (a.action || a.id) === action); }
  function actionGuidance(action, a) { const group = actionGroup(action), groupLabel = group === 'Source' ? '來源端' : group === 'Target' ? '目標端' : '管理端', index = state.actions.findIndex(entry => (entry.action || entry.id) === action); const intent = /^(Get|Test|Assert|Read|SpecReview|Fleet|Acceptance|Check|.*Preview)/.test(action) ? '建議步驟：先查看結果及範圍，再決定是否進入下一步；預覽不會取得核准。' : '建議步驟：確認必要欄位與配對，產生伺服端預覽，核對影響後再明確提交。'; const precondition = group === 'Source' ? '前提：在核准的來源主機執行，確認主機身分、WorkRoot 與來源範圍。' : group === 'Target' ? '前提：在核准的目標主機執行，確認配對、目標現況與相關材料有效。' : '前提：在管理主機確認正確配對、revision、責任人及可信證據。'; const output = /^(Get|Test|Assert|Read|.*Preview)/.test(action) ? '輸出與下步：查看結果、阻擋原因及待補資料，再選擇對應操作。' : '輸出與下步：取得工作識別碼及安全投影，到「作業與交接」查看進度、報告或後續修復。'; return { group:groupLabel, purpose:`目的：${actionLabel(action, index + 1)}。${a && a.readOnly ? '此操作只讀取資料。' : intent}`, precondition, output }; }
  function renderActionMetadata(a) { const box = $('action-metadata'); box.replaceChildren(); $('action-description').textContent = a ? '具名操作會以目前本機 Windows 身分執行；是否允許仍由本機角色、參數與伺服端檢查決定。' : '操作說明與角色需求會在選取後顯示。'; if (!a) return; const action = a.action || a.id, guide = actionGuidance(action, a), section = el('section', 'action-guidance'); section.append(el('h3', '', `${guide.group}操作步驟`), el('p', '', guide.purpose), el('p', '', guide.precondition), el('p', '', guide.output)); if (a.readOnly) section.appendChild(el('p', 'inline-note', '此操作為唯讀；結果不代表資源已就緒。')); if (action === 'HttpIntegrityProbe') section.appendChild(el('p', 'inline-note', '只會 GET 工作階段中繼資料與四個靜態資源。請自行指定報告輸出路徑；結果僅描述本機目前觀察，不代表其他瀏覽器／環境已驗證。')); box.appendChild(section); }
  const fieldLabels = { ItemId:'項目識別碼', ExpectedDecisionRevision:'預期決策 revision', ExpectedAssistiveRevision:'預期輔助流程 revision', ExpectedSelectionRevision:'預期選取 revision', Owner:'負責人', Evidence:'佐證與觀察', Fields:'型別化設定欄位', Origin:'本機頁面來源網址', OutputPath:'報告輸出檔案路徑', DocumentManifestPath:'文件清單路徑', CommandManifestPath:'命令清單路徑', SHA256:'SHA-256（進階核對值）', ExpectedHash:'預期 SHA-256（進階核對值）', TrustedSHA256:'可信材料 SHA-256（進階核對值）', Path:'檔案路徑', Workspace:'受控工作區', PairId:'主機配對識別碼', ExpectedRevision:'預期 revision', ContextId:'工作階段上下文識別碼', SourcePath:'來源路徑', TargetPath:'目標路徑', Reason:'原因', Description:'說明', Name:'名稱', Status:'狀態', Action:'操作類型', Arguments:'具名參數', ReportReferences:'報告引用', ReportArtifacts:'報告產物', DocumentId:'文件識別碼', ManifestPath:'文件清單路徑', OutputDirectory:'輸出目錄', WorkRoot:'受控工作根目錄', ItemIds:'項目識別碼清單', SelectedItemIds:'已選項目', UnselectedItems:'未選項目與原因', SoftwareId:'軟體識別碼', ChosenVersion:'選用版本', ResultPath:'結果檔案路徑', ImportedDirectory:'匯入目錄', TransferPlanPath:'傳輸計畫路徑', TransportPath:'傳輸檔案路徑', ExpectedTransportHash:'傳輸檔案 SHA-256（進階核對值）', ExpectedPlanHash:'計畫 SHA-256（進階核對值）', Secrets:'本次工作秘密資料', Credential:'本次工作認證資料', Decisions:'逐項設定決策', SourceInventoryPath:'來源盤點檔案路徑', SourceInventoryHash:'來源盤點 SHA-256（進階核對值）', TargetInventoryPath:'目標盤點檔案路徑', TargetInventoryHash:'目標盤點 SHA-256（進階核對值）', PreviewPath:'審閱預覽檔案路徑', PreviewHash:'預覽檔案 SHA-256（進階核對值）', PreviewFileHash:'預覽檔案 SHA-256（進階核對值）', ReviewWindowsSettings:'是否納入 Windows 設定審閱' };
  function parameterLabel(name, provided) { if (fieldLabels[name]) return fieldLabels[name]; const translated = translatedWords(name); return translated || `進階欄位（${provided || name}）`; }
  function addFormField(container, p, index) {
    const wrap = el('div', `form-field${p.wide ? ' wide' : ''}`), id = `param-${index}`, label = el('label', '', parameterLabel(p.name, p.label)); label.htmlFor = id; if (p.required) label.appendChild(el('span', 'required', ' *')); wrap.appendChild(label);
    let input; const type = p.type || 'string';
    if (type === 'object') { input = buildObjectEditor(p.schema || {}, id); }
    else if (type === 'objectArray') { input = buildObjectArrayEditor(p.schema || {}, id, p); }
    else if (type === 'enum' || type === 'boolean') { input = document.createElement('select'); input.appendChild(new Option(p.required ? '請選擇…' : '未指定', '')); if (type === 'boolean') { input.appendChild(new Option('是', 'true')); input.appendChild(new Option('否', 'false')); } else (p.options || []).forEach(opt => input.appendChild(new Option(opt.label || opt, opt.value == null ? opt : opt.value))); }
    else if (type === 'stringArray' || type === 'array') { input = el('div', 'array-editor'); input.dataset.kind = 'array'; const add = el('button', 'secondary-button', '新增一列'); add.type = 'button'; add.addEventListener('click', () => addArrayRow(input, '', p)); input.appendChild(add); addArrayRow(input, '', p); }
    else if (type === 'map' || type === 'stringMap') { input = el('div', 'map-editor'); input.dataset.kind = 'map'; const add = el('button', 'secondary-button', '新增鍵值'); add.type = 'button'; add.addEventListener('click', () => addMapRow(input, '', '', p)); input.appendChild(add); addMapRow(input, '', '', p); }
    else { input = document.createElement('input'); input.type = isSensitive(p) && type === 'string' ? 'password' : type === 'integer' || type === 'number' ? 'number' : type === 'path' || type === 'directory' || type === 'file' ? 'text' : 'text'; if (input.type === 'number') { input.step = type === 'integer' ? '1' : 'any'; } input.autocomplete = isSensitive(p) ? 'new-password' : 'off'; if (isSensitive(p)) input.autocomplete = 'off'; if (p.placeholder) input.placeholder = p.placeholder; }
    input.id = id; input.dataset.parameter = p.name; input.dataset.type = type; input.dataset.required = p.required ? 'true' : 'false'; input.dataset.allowEmpty = p.allowEmpty ? 'true' : 'false'; if (p.description) input.setAttribute('aria-describedby', `${id}-hint`); wrap.appendChild(input); if (p.description) wrap.appendChild(el('span', 'hint', p.description)).id = `${id}-hint`; container.appendChild(wrap);
  }
  function buildObjectEditor(schema, id) { const box = el('fieldset', 'object-editor'); box.dataset.complexType = 'object'; const legend = el('legend', '', parameterLabel(schema.title || 'Fields')); box.appendChild(legend); Object.entries(schema.properties || {}).forEach(([name, property], index) => { addFormField(box, Object.assign({ name }, property), `${id}-${index}`); const field = box.lastElementChild; field.dataset.objectKey = name; }); return box; }
  function buildObjectArrayEditor(schema, id, p) { const box = el('div', 'object-array-editor'); box.dataset.complexType = 'objectArray'; const rows = el('div', 'object-array-rows'); rows.dataset.rows = 'true'; const add = el('button', 'secondary-button', `新增${parameterLabel(schema.title || p.name)}`); add.type = 'button'; add.addEventListener('click', () => addObjectArrayRow(rows, schema, id)); box.append(rows, add); return box; }
  function addObjectArrayRow(rows, schema, id) { const row = el('fieldset', 'object-array-row'); row.appendChild(el('legend', '', schema.title || '一筆資料')); Object.entries(schema.properties || {}).forEach(([name, property], index) => { addFormField(row, Object.assign({ name, label: name }, property), `${id}-${rows.children.length}-${index}`); row.lastElementChild.dataset.objectKey = name; }); const remove = el('button', 'icon-remove', '移除此列'); remove.type = 'button'; remove.addEventListener('click', () => row.remove()); row.appendChild(remove); rows.appendChild(row); }
  function collectObjectValues(node) { const out = {}; [...node.children].filter(child => child.dataset && child.dataset.objectKey).forEach(child => { const key = child.dataset.objectKey, control = child.querySelector('[data-type]'); if (!control) return; const value = collectControl(control); if (value !== undefined && (control.dataset.required === 'true' || !(Array.isArray(value) && value.length === 0) && !(value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === 0))) out[key] = value; }); return out; }
  function collectComplex(node) { const kind = node.dataset.complexType; if (kind === 'object') return collectObjectValues(node); if (kind === 'objectArray') return [...node.querySelector('[data-rows]').children].map(collectObjectValues); return undefined; }
  function collectControl(control) { const type = control.dataset.type; if (type === 'object' || type === 'objectArray') return collectComplex(control); if (type === 'array' || type === 'stringArray') return [...control.querySelectorAll('.collection-row input')].map(n => n.value).filter(v => v !== ''); if (type === 'map' || type === 'stringMap') { const value = {}; [...control.querySelectorAll('.collection-row')].forEach(row => { const [k, v] = row.querySelectorAll('input'); if (k.value && !Object.prototype.hasOwnProperty.call(value, k.value)) value[k.value] = v.value; }); return value; } if (type === 'boolean') return control.value === '' ? undefined : control.value === 'true'; if ((type === 'integer' || type === 'number') && control.value !== '') return Number(control.value); return control.value === '' && control.dataset.allowEmpty !== 'true' ? undefined : control.value; }
  function addArrayRow(editor, value, p) { const row = el('div', 'collection-row'); const input = el('input'); input.type = 'text'; input.autocomplete = 'off'; input.value = value; input.setAttribute('aria-label', `${p.label || p.name}項目`); const remove = el('button', 'icon-remove', '移除'); remove.type = 'button'; remove.addEventListener('click', () => { row.remove(); captureDraft(); }); row.append(input, remove); editor.insertBefore(row, editor.lastChild); }
  function addMapRow(editor, key, value, p) { const row = el('div', 'collection-row map-row'); const k = el('input'), v = el('input'); k.type = v.type = 'text'; k.autocomplete = v.autocomplete = 'off'; k.value = key; v.value = value; k.setAttribute('aria-label', `${p.label || p.name}鍵`); v.setAttribute('aria-label', `${p.label || p.name}值`); const remove = el('button', 'icon-remove', '移除'); remove.type = 'button'; remove.addEventListener('click', () => { row.remove(); captureDraft(); }); row.append(k, v, remove); editor.insertBefore(row, editor.lastChild); }
  function safeDraftValue(param, control) {
    if (!control || isSensitive(param)) return undefined;
    const type = param.type || 'string';
    if (type === 'object') { const result = {}; Object.entries(param.schema && param.schema.properties || {}).forEach(([key, property]) => { const wrap = [...control.children].find(child => child.dataset && child.dataset.objectKey === key), nested = wrap && wrap.querySelector('[data-type]'); const value = safeDraftValue(property, nested); if (value !== undefined) result[key] = value; }); return result; }
    if (type === 'objectArray') { const rows = control.querySelector('[data-rows]'); return [...(rows ? rows.children : [])].map(row => { const result = {}; Object.entries(param.schema && param.schema.properties || {}).forEach(([key, property]) => { const wrap = [...row.children].find(child => child.dataset && child.dataset.objectKey === key), nested = wrap && wrap.querySelector('[data-type]'); const value = safeDraftValue(property, nested); if (value !== undefined) result[key] = value; }); return result; }); }
    if ((type === 'array' || type === 'stringArray') && param.items && isSensitive(param.items)) return undefined;
    return collectControl(control);
  }
  function invalidatePreview() { if (!state.preview) return; state.preview = null; $('confirm-line').hidden = true; $('operation-confirm').checked = false; $('submit-operation').disabled = true; $('preview-summary').textContent = '輸入已變更，請重新預覽。'; }
  function captureDraft() { const action = state.activeAction, metadata = metadataFor(action); if (!action || !metadata) return; const draft = {}; (metadata.parameters || []).forEach((param, index) => { const value = safeDraftValue(param, $(`param-${index}`)); if (value !== undefined) draft[param.name] = value; }); state.drafts.set(action, draft); invalidatePreview(); }
  function restoreDraftValue(param, control, value) { if (!control || isSensitive(param) || value === undefined) return; const type = param.type || 'string'; if (type === 'object') { Object.entries(param.schema && param.schema.properties || {}).forEach(([key, property]) => { const wrap = [...control.children].find(child => child.dataset && child.dataset.objectKey === key); restoreDraftValue(property, wrap && wrap.querySelector('[data-type]'), value[key]); }); return; } if (type === 'objectArray') { const rows = control.querySelector('[data-rows]'); if (!rows || !Array.isArray(value)) return; [...rows.children].forEach(row => row.remove()); value.forEach(item => { addObjectArrayRow(rows, param.schema || {}, control.id); const row = rows.lastElementChild; Object.entries(param.schema && param.schema.properties || {}).forEach(([key, property]) => { const wrap = [...row.children].find(child => child.dataset && child.dataset.objectKey === key); restoreDraftValue(property, wrap && wrap.querySelector('[data-type]'), item[key]); }); }); return; } if (type === 'stringArray' || type === 'array') { [...control.querySelectorAll('.collection-row')].forEach(row => row.remove()); value.forEach(item => addArrayRow(control, item, param)); return; } if (type === 'map' || type === 'stringMap') { [...control.querySelectorAll('.collection-row')].forEach(row => row.remove()); Object.entries(value).forEach(([key, item]) => addMapRow(control, key, item, param)); return; } control.value = type === 'boolean' ? (value ? 'true' : 'false') : String(value); }
  function restoreDraft(action) { const data = state.drafts.get(action); const metadata = metadataFor(action); if (!data || !metadata) return; (metadata.parameters || []).forEach((param, index) => restoreDraftValue(param, $(`param-${index}`), data[param.name])); }
  function setAction(action) { captureDraft(); state.activeAction = action; state.preview = null; $('preview-panel').hidden = true; clearFailure(); const a = metadataFor(action), container = $('parameter-fields'); container.replaceChildren(); $('confirm-line').hidden = true; $('operation-confirm').checked = false; $('preview-operation').disabled = !a; $('submit-operation').disabled = true; renderActionMetadata(a); if (!a) { container.appendChild(el('p', 'empty-state', '請先選擇一項操作。')); return; } const allowed = new Set(['string', 'path', 'directory', 'file', 'integer', 'number', 'boolean', 'enum', 'stringArray', 'array', 'map', 'stringMap', 'object', 'objectArray']); const unsupported = (a.parameters || []).filter(p => !allowed.has(p.type || 'string') || (['object', 'objectArray'].includes(p.type) && !p.schema)); if (a.unsupportedReason || unsupported.length) { container.appendChild(el('p', 'error-summary', a.unsupportedReason || `此操作的型別化欄位尚未定義：${unsupported.map(p => parameterLabel(p.name, p.label)).join('、')}。`)); $('preview-operation').disabled = true; return; } (a.parameters || []).forEach((p, i) => addFormField(container, p, i)); restoreDraft(action); if (action === 'HttpIntegrityProbe') { const origin = (a.parameters || []).findIndex(p => p.name === 'Origin'), draft = state.drafts.get(action) || {}; if (origin >= 0 && !Object.prototype.hasOwnProperty.call(draft, 'Origin')) { const input = $(`param-${origin}`); if (input && !input.value) input.value = location.origin; } } const manifest = (a.parameters || []).findIndex(p => ['DocumentManifestPath','CommandManifestPath','ManifestPath'].includes(p.name)); if (manifest >= 0) { const input = $(`param-${manifest}`), isReportCheck = action === 'AssistiveReportCheck', text = isReportCheck ? '先前匯出結果的 DocumentManifestPath 對應本次檢查的文件清單路徑；SHA-256 請使用同一輸出中的 DocumentManifestHash。' : '請從先前工作輸出中的 commandManifestPath 複製完整路徑。'; if (input) { const hint = $(`param-${manifest}-hint`); if (hint) hint.textContent = text; else { const note = el('span','hint',text); note.id = `param-${manifest}-hint`; input.setAttribute('aria-describedby', note.id); input.parentNode.appendChild(note); } } } }
  function validateSchema(schema, value, label, errors) { if (Array.isArray(value)) { value.forEach((item, index) => validateSchema(schema, item, `${label}第${index + 1}列`, errors)); return; } Object.entries(schema.properties || {}).forEach(([key, property]) => { const v = value && value[key]; if (property.required && (v == null || (v === '' && !property.allowEmpty))) errors.push(`${label}：${property.label || key}為必填。`); if (property.type === 'object' && v) validateSchema(property.schema || property, v, `${label}／${property.label || key}`, errors); if (property.type === 'objectArray' && Array.isArray(v)) v.forEach((item, index) => validateSchema(property.schema || property, item, `${label}第${index + 1}列`, errors)); }); }
  function collectArgs(validate) { const a = metadataFor(state.activeAction); if (!a) return null; const args = {}, errors = []; (a.parameters || []).forEach((p, i) => { const input = $(`param-${i}`), type = p.type || 'string'; let value = collectControl(input);
          if (p.required && (value === undefined || value === null || value === '' || (Array.isArray(value) && !value.length && !p.allowEmpty))) errors.push(`${p.label || p.name}為必填。`);
      if (type === 'map' || type === 'stringMap') [...input.querySelectorAll('.collection-row')].forEach(row => { const [k, v] = row.querySelectorAll('input'); if (k.value || v.value) { const rows = [...input.querySelectorAll('.collection-row')]; if (!k.value || rows.filter(other => other.querySelectorAll('input')[0].value === k.value).length > 1) errors.push(`${p.label || p.name} 的鍵不可空白或重複。`); } });
      if (type === 'integer' || type === 'number') { const raw = input.value; if (raw !== '' && (!Number.isFinite(Number(raw)) || (type === 'integer' && !Number.isInteger(Number(raw))))) errors.push(`${p.label || p.name}請輸入有效${type === 'integer' ? '整數' : '數字'}。`); }
      if ((type === 'object' || type === 'objectArray') && value !== undefined) validateSchema(p.schema || {}, value, p.label || p.name, errors);
      if (value !== undefined || p.required) args[p.name] = value === undefined ? null : value;
    });
    if (validate && errors.length) { $('field-errors').textContent = errors.join(' '); $('field-errors').hidden = false; return null; } $('field-errors').hidden = true; return args;
  }
  function parseResponse(response) { return response && (response.operation || response.preview || response.result || response); }
  function requestId() { return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; }
  function buildOperationRequest(action, args, expectedRevision) { return { action, args, operationId: requestId(), idempotencyKey: requestId(), expectedRevision, contextId: state.session && state.session.contextId }; }
  function buildSelectionArgs(inventory, selected, reasons) { return { selectedItemIds: inventory.filter(r => r.selectable !== false && selected.has(inventoryItem(r))).map(inventoryItem), unselectedItems: inventory.filter(r => r.selectable === false || !selected.has(inventoryItem(r))).map(r => ({ itemId: inventoryItem(r), reason: reasons.get(inventoryItem(r)) || r.reason || '' })) }; }
  function invalidateForConflict() { state.preview = null; return { preserveDraft: true, requireFreshPreview: true }; }
  function renderPreview(data) { const d = parseResponse(data); state.preview = d; $('preview-panel').hidden = false; const summaryText = typeof d.summary === 'string' ? d.summary : d.summary && typeof d.summary === 'object' ? Object.entries(d.summary).filter(([key, value]) => ['discovered', 'selected', 'approved', 'executable', 'deferred', 'blocked', 'conflicts', 'files', 'bytes'].includes(key.toLowerCase()) && ['string', 'number'].includes(typeof value)).map(([key, value]) => `${key} ${value}`).join(' · ') : ''; $('preview-summary').textContent = `${d.previewKind === 'ParametersOnly' ? '參數已檢查；此結果未檢查資源就緒狀態。' : d.canExecute === true ? '伺服端預覽未列出阻擋條件；執行時仍會重新檢查。' : d.canExecute === false ? '目前有阻擋或待處理條件。' : '請審閱伺服端回傳的影響與待處理項目。'} ${summaryText}${d.revision == null ? '' : ` · revision ${d.revision}`}`; const issues = $('preview-issues'); issues.replaceChildren(); (d.issues || []).forEach(issue => issues.appendChild(el('li', '', typeof issue === 'string' ? issue : issue.message || issue.title || issue.reason || issue.Issue || issue.Reason || '有待處理項目'))); const body = $('preview-items'); body.replaceChildren(); const items = rowsOf(d.items); items.forEach(item => { const tr = el('tr'); const source = item.originalPath ?? item.OriginalPath ?? item.sourcePath ?? item.SourcePath ?? item.sourceVersion ?? item.SourceVersion ?? item.RelativePath, effective = item.effectivePath ?? item.EffectivePath, note = [item.reason || item.Reason || item.message || item.Issue || item.Gate, item.sourceHash || item.SourceHash ? `來源 SHA-256：${item.sourceHash || item.SourceHash}` : '', item.readbackHash || item.ReadbackHash ? `讀回 SHA-256：${item.readbackHash || item.ReadbackHash}` : '', item.conflictHash || item.ConflictHash ? `衝突 SHA-256：${item.conflictHash || item.ConflictHash}` : ''].filter(Boolean).join(' · '); tr.append(el('td', '', item.name || item.Name || item.title || item.Title || item.itemId || item.ItemId || item.resourceId || item.ResourceId || '項目'), el('td', '', statusName(item.status || item.Status || item.state || item.State)), el('td', '', safeText(source)), el('td', '', safeText(effective)), el('td', '', safeText(note))); body.appendChild(tr); }); if (!items.length) body.appendChild(emptyRow(5, d.previewKind === 'ParametersOnly' ? '此操作僅檢查輸入欄位；不含資源或就緒狀態結果。' : '預覽沒有列出個別影響項目。')); $('confirm-line').hidden = false; $('operation-confirm').checked = false; $('operation-confirm').disabled = d.canExecute === false; $('submit-operation').disabled = true; const notes = (d.issues || []).map(x => typeof x === 'string' ? x : x.message || x.title || x.Issue || x.Reason).filter(Boolean); announce(`預覽已更新${d.revision == null ? '' : `（revision ${d.revision}）`}。${d.previewKind === 'ParametersOnly' ? '這不是資源就緒結論。' : '請確認受影響範圍及待處理項目。'}${notes.length ? ` ${notes.slice(0, 3).join('；')}` : ''}`); }
  function resetDraft() { const form = $('operation-form'); if (state.activeAction) state.drafts.delete(state.activeAction); form.reset(); state.activeAction = null; state.preview = null; $('preview-panel').hidden = true; $('parameter-fields').replaceChildren(el('p', 'empty-state', '請先選擇一項操作。')); $('action-picker').value = ''; $('preview-operation').disabled = true; $('submit-operation').disabled = true; $('confirm-line').hidden = true; renderActionMetadata(null); }
  async function submitOperation(event) { event.preventDefault(); if (state.busy || !state.preview || !$('operation-confirm').checked) return; const args = collectArgs(true); if (!args) return; const a = metadataFor(state.activeAction); const request = buildOperationRequest(state.activeAction, args, state.preview.revision == null ? state.session.revision : state.preview.revision);
    state.busy = true; $('submit-operation').disabled = true; try { const data = await endpoint('/api/operations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(request) }); const job = data.job || data; if (job.jobId || job.id || job.operationId) state.jobs.set(job.jobId || job.id || job.operationId, job); announce(`已提交「${a.label || a.action}」。工作識別碼 ${safeText(job.jobId || job.id || job.operationId)}；頁面關閉不會取消作業。`); await refreshJobs(); resetDraft(); } catch (error) { if (error.status === 409) { // CAS conflict: retain typed form values and ask for a fresh preview.
        invalidateForConflict(); $('confirm-line').hidden = true; $('submit-operation').disabled = true; $('preview-operation').disabled = false; fail(`工作資料已由其他視窗更新${error.body && error.body.revision != null ? `至 revision ${error.body.revision}` : ''}。草稿仍保留；請重新預覽後再確認。`); if (error.body && error.body.currentRevision != null) $('revision-label').textContent = `revision ${error.body.currentRevision}`;
      } else if (error.message !== 'session expired') fail(error.message); } finally { state.busy = false; }
  }
  function stripSensitiveValue(param, value) { if (isSensitive(param) || value === undefined) return undefined; const properties = param.schema && param.schema.properties || {}; if (param.type === 'object' && value && typeof value === 'object') return stripSensitiveArguments(Object.entries(properties).map(([name, p]) => Object.assign({ name }, p)), value); if (param.type === 'objectArray' && Array.isArray(value)) return value.map(row => stripSensitiveArguments(Object.entries(properties).map(([name, p]) => Object.assign({ name }, p)), row)); if ((param.type === 'array' || param.type === 'stringArray') && Array.isArray(value) && param.schema && param.schema.item) return value.map(item => stripSensitiveValue(param.schema.item, item)); return value; }
  function stripSensitiveArguments(parameters, args) { const safe = {}; (parameters || []).forEach(param => { if (!Object.prototype.hasOwnProperty.call(args, param.name)) return; const value = stripSensitiveValue(param, args[param.name]); if (value !== undefined) safe[param.name] = value; }); return safe; }
  async function previewOperation() { if (state.busy) return; clearFailure(); const args = collectArgs(true); if (!args) return; const a = metadataFor(state.activeAction); const previewArgs = args; state.busy = true; $('preview-operation').disabled = true; try { const data = await endpoint('/api/view', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: state.activeAction, args: previewArgs, expectedRevision: state.session.revision, contextId: state.session.contextId }) }); renderPreview(data); } catch (error) { if (error.status === 409) { invalidateForConflict(); $('preview-operation').disabled = false; fail('工作資料或上下文已更新。欄位草稿已保留，請重新整理資料後再次預覽。'); } else if (error.message !== 'session expired') fail(error.message); } finally { state.busy = false; $('preview-operation').disabled = false; } }
  function renderJobs() {
    const box = $('job-list'); box.replaceChildren(); const jobs = [...state.jobs.values()];
    if (!jobs.length) { box.appendChild(el('div', 'empty-card', '目前沒有進行中的工作。')); return; }
    jobs.forEach(job => {
      const card = el('article', 'job-card'), main = el('div'), acts = el('div', 'job-actions'), id = job.jobId || job.id || job.operationId, title = actionLabel(job.action, job.label || '本機作業'), status = statusName(job.status);
      main.append(el('h2', '', title), el('div', 'job-meta', `工作識別碼：${id} · ${status}`), el('div', 'job-meta', job.message || job.nextStep || '狀態會在安全檢查點更新。'));
      if (job.progress && job.progress.percent != null) { const bar = el('div', 'job-progress'), fill = document.createElement('progress'); fill.max = 100; fill.value = Math.max(0, Math.min(100, Number(job.progress.percent))); fill.textContent = `進度 ${job.progress.percent}%`; bar.appendChild(fill); bar.setAttribute('aria-label', `進度 ${job.progress.percent}%`); main.appendChild(bar); }
      (job.outputs || []).forEach(output => {
        const list = el('dl', 'job-output');
        Object.entries(output).forEach(([key, value]) => {
          if (!safeJobOutputFields.has(key)) return;
        if (key === 'Rows' && ['AssistiveWindowsSettingsPreviewOutput','AssistivePreparationPreview','AssistiveRequirementReview'].includes(output.Kind)) return;
          list.append(el('dt', '', key), el('dd', '', typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' ? String(value) : '未知'));
        });
        main.appendChild(list); appendProjectedRows(main, output);
        if (output.Kind === 'AssistiveWindowsSettingsPreviewOutput' && Array.isArray(output.Rows)) {
          const usePreview = el('button', 'secondary-button', '使用此預覽準備設定審閱'); usePreview.type = 'button'; usePreview.addEventListener('click', () => prefillWindowsSettingsReview(output)); acts.appendChild(usePreview);
        }
        if (output.Kind === 'AssistiveRequirementReview' && Array.isArray(output.Rows)) { const useReview = el('button', 'secondary-button', '使用此預覽準備需求審閱'); useReview.type = 'button'; useReview.addEventListener('click', () => prefillRequirementDecisionReview(output)); acts.appendChild(useReview); }
      });
      (job.reportArtifacts || []).forEach((artifact, index) => { const label = artifact.Label || artifact.label || '驗證過的報告'; const open = el('button', 'secondary-button', `開啟報告：${label}`); open.type = 'button'; open.disabled = !id || !artifact.SHA256; open.addEventListener('click', () => openJobReport(id, index, artifact.SHA256)); acts.appendChild(open); });
      const reconnect = el('button', 'secondary-button', '重新連線'); reconnect.type = 'button'; reconnect.addEventListener('click', () => reconnectJob(id)); acts.appendChild(reconnect);
      if (job.canCancel === true && ['Queued', 'Running', 'CancelRequested'].includes(job.status)) { const cancel = el('button', 'secondary-button', job.status === 'CancelRequested' ? '取消已送出' : '要求取消'); cancel.type = 'button'; cancel.disabled = job.status === 'CancelRequested'; cancel.addEventListener('click', () => cancelJob(id)); acts.appendChild(cancel); }
      card.append(main, acts); box.appendChild(card);
    });
  }
  async function openJobReport(id, index, SHA256) { try { await endpoint(`/api/jobs/${encodeURIComponent(id)}/reports/${index}/open`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ SHA256 }) }); announce('已要求本機開啟驗證過的 HTML 報告。'); } catch (e) { if (e.message !== 'session expired') fail(`無法開啟報告：${e.message}`); } }
  async function refreshJobs() { try { const data = await endpoint('/api/jobs'); rowsOf(data).forEach(j => state.jobs.set(j.jobId || j.id || j.operationId, j)); renderJobs(); } catch (e) { if (e.message !== 'session expired') fail(`無法讀取作業狀態：${e.message}。可稍後重新連線。`); } }
  async function reconnectJob(id) { try { const job = await endpoint(`/api/jobs/${encodeURIComponent(id)}`); state.jobs.set(id, job); renderJobs(); announce(`已重新連線工作 ${id}。`); } catch (e) { if (e.message !== 'session expired') fail(`無法重新連線工作 ${id}：${e.message}`); } }
  async function cancelJob(id) { try { const job = await endpoint(`/api/jobs/${encodeURIComponent(id)}/cancel`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); state.jobs.set(id, job.job || job); renderJobs(); announce(`已送出工作 ${id} 的取消要求。實際停止狀態會在安全邊界更新。`); } catch (e) { if (e.message !== 'session expired') fail(`取消要求未完成：${e.message}`); } }
  async function loadView(view, refresh) { const targets = { overview: 'overview', inventory: 'inventory', software: 'software', files: 'files', actions: 'actions' }; if (!targets[view]) return; try { const data = await getView(targets[view], refresh); if (view === 'overview') renderOverview(data); else if (view === 'inventory') renderInventory(data); else if (view === 'software') renderSoftware(data); else if (view === 'files') renderFiles(data); else renderActions(data); } catch (e) { if (e.message !== 'session expired') fail(`無法載入資料：${e.message}。請重新整理或重新啟動本機工具。`); } }
  function navigate(view) { if (!view) return; document.querySelectorAll('.view').forEach(node => { node.hidden = node.id !== `view-${view}`; }); document.querySelectorAll('.nav-link').forEach(node => { const active = node.dataset.view === view; node.classList.toggle('active', active); if (active) node.setAttribute('aria-current', 'page'); else node.removeAttribute('aria-current'); }); history.replaceState(null, '', `#${view}`); const h = document.querySelector(`#view-${view} h1`); if (h) { h.setAttribute('tabindex', '-1'); h.focus({ preventScroll: true }); } if (state.jobPoll) { clearInterval(state.jobPoll); state.jobPoll = null; } if (['overview', 'inventory', 'software', 'files'].includes(view)) loadView(view); if (view === 'operations') loadView('actions'); if (view === 'jobs') { refreshJobs(); state.jobPoll = setInterval(() => { if (!document.hidden && location.hash === '#jobs') refreshJobs(); }, 2500); } }
  function currentVisibleIds() { const query = $('inventory-search').value.trim().toLocaleLowerCase(), category = $('category-filter').value; return state.inventory.filter(r => r.selectable !== false && (!category || r.category === category) && (!query || [r.name, r.path, r.itemId, r.source, r.category].some(v => String(v || '').toLocaleLowerCase().includes(query)))).map(inventoryItem); }
  async function saveSelection() { const args = buildSelectionArgs(state.inventory, state.selected, state.selectionReasons), missing = args.unselectedItems.filter(item => !item.reason.trim()); if (missing.length) { fail('請為每個未選取項目填寫原因。', missing.map(item => item.itemId)); return; } try { const response = await endpoint('/api/operations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(buildOperationRequest('SaveSelection', args, state.session.revision)) }); if (response.revision != null) { state.session.revision = response.revision; $('revision-label').textContent = `revision ${response.revision}`; } state.selectionDirty = false; announce('已保存目前選取與未選原因。此操作沒有授予核准或執行權限。'); } catch (e) { if (e.status === 409) fail('其他視窗已修改選取資料，草稿已保留；請重新載入後再次保存。'); else if (e.message !== 'session expired') fail(e.message); } }
  async function setRestoreChoice(choice) { try { const data = await endpoint('/api/operations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(buildOperationRequest('SetRestoreChoice', { choice }, state.session.revision)) }); state.session.revision = data.revision || state.session.revision; announce(choice === 'RestoreNow' ? '已記錄直接還原選擇；仍須預覽與一般核准。' : '已記錄等待補裝選擇；不會自動安裝或開始還原。'); return true; } catch (e) { if (e.status === 409) { await refreshSession(true); fail('工作資料或上下文已更新；請重新載入比較結果後再選擇。'); } else if (e.message !== 'session expired') fail(e.message); return false; } }
  async function openRestorePreview() { if (!(await setRestoreChoice('RestoreNow'))) return; navigate('operations'); await loadView('actions', true); if (!metadataFor('RestorePreview')) { fail('目前操作清單未提供還原預覽欄位；請檢查操作上下文。實際執行仍須通過 Windows 權限與核心審核條件。選擇已記錄。'); return; } $('action-picker').value = 'RestorePreview'; setAction('RestorePreview'); }
  async function init() { try { const s = await fetch('/api/session', { headers: { Accept: 'application/json' }, credentials: 'same-origin', cache: 'no-store' }); if (!s.ok) throw new Error(`無法連線本機工作階段（${s.status}）`); state.session = await s.json(); state.token = state.session.token; if (!state.token) throw new Error('工作階段未提供寫入 token，請重新啟動本機工具。'); renderSession(state.session); await refreshContext(); await loadView('overview'); const hash = location.hash.slice(1); if (hash && document.querySelector(`#view-${hash}`)) navigate(hash); } catch (error) { fail(`${error.message}。請依離線操作指引重新啟動本機工具。`); $('session-label').textContent = '無法連線本機工作階段'; } }
  document.addEventListener('DOMContentLoaded', () => {
    document.querySelectorAll('[data-view]').forEach(link => link.addEventListener('click', event => { event.preventDefault(); navigate(link.dataset.view); })); document.querySelectorAll('[data-go]').forEach(button => button.addEventListener('click', () => navigate(button.dataset.go)));
    $('refresh-button').addEventListener('click', () => { refreshSession(true); }); $('inventory-search').addEventListener('input', () => { state.inventoryPage = 0; paintInventory(); }); $('category-filter').addEventListener('change', () => { state.inventoryPage = 0; paintInventory(); }); $('inventory-page-size').addEventListener('change', event => { state.inventoryPageSize = Number(event.target.value); state.inventoryPage = 0; paintInventory(); }); $('inventory-previous').addEventListener('click', () => { state.inventoryPage = Math.max(0, state.inventoryPage - 1); paintInventory(); }); $('inventory-next').addEventListener('click', () => { state.inventoryPage++; paintInventory(); });
    $('select-all').addEventListener('click', () => { currentVisibleIds().forEach(id => { state.selected.add(id); state.selectionReasons.delete(id); }); state.selectionDirty = true; paintInventory(); }); $('clear-selection').addEventListener('click', () => { currentVisibleIds().forEach(id => state.selected.delete(id)); state.selectionDirty = true; paintInventory(); }); $('save-selection').addEventListener('click', saveSelection); $('refresh-software').addEventListener('click', () => loadView('software', true)); $('refresh-files').addEventListener('click', () => loadView('files', true)); $('wait-install').addEventListener('click', () => setRestoreChoice('WaitForInstall')); $('restore-now').addEventListener('click', openRestorePreview); $('apply-context').addEventListener('click', applyContext);
    $('operation-form').addEventListener('input', event => { if (event.target.id !== 'operation-confirm') captureDraft(); }); $('operation-form').addEventListener('change', event => { if (event.target.id !== 'operation-confirm') captureDraft(); }); $('action-picker').addEventListener('change', event => setAction(event.target.value)); $('operation-form').addEventListener('submit', submitOperation); $('preview-operation').addEventListener('click', previewOperation); $('operation-confirm').addEventListener('change', event => { $('submit-operation').disabled = !event.target.checked || !state.preview; }); $('reconnect-jobs').addEventListener('click', refreshJobs); window.addEventListener('hashchange', () => { const view = location.hash.slice(1); if (document.querySelector(`#view-${view}`)) navigate(view); }); init();
  });
  // Exposed only for the repository's dependency-free mocked DOM contract test.
  window.WsmConsole = { statusName, statusClass, isSensitive, collectArgs, collectControl, state, navigate, renderInventory, renderFiles, renderJobs, renderActions, setAction, parseResponse, endpoint, openJobReport, openSpecReview, prefillSpecReview, prefillWindowsSettingsReview, createWindowsSettingsReviewDraft, createRequirementDecisionDraft, prefillRequirementDecisionReview, safeTypedFields, actionLabel, actionGroup, actionGuidance, parameterLabel, buildOperationRequest, buildSelectionArgs, stripSensitiveArguments, invalidateForConflict };
}());
