function Assert-WsmAdapterDesired($Spec) {
    if($Spec.Adapter -eq 'ScheduledTask' -and (-not $Spec.PSObject.Properties['CatchUpPolicy'] -or $Spec.CatchUpPolicy -cnotin @('PreserveSourceSettings','SkipMissedRuns','DedicatedManualCatchUp'))){throw 'Task requires an explicit reviewed CatchUpPolicy: PreserveSourceSettings, SkipMissedRuns or DedicatedManualCatchUp.'}
    $contracts=@{
        ScheduledTask=@('TaskName','TaskPath','Xml','User','SecuritySddl','FolderSecurity'); Service=@('Name','DisplayName','BinaryPathName','Account','Dependencies','Description','Supplement'); SmbShare=@('Name','Path','Description','EncryptData','Access','DrainPolicy','DrainEvidence'); MachineEnvironment=@('Name','Value'); TimeZone=@('Name','Value'); WindowsFeature=@('Name','Source','IsolationEvidence','SideEffects'); IISPool=@('Name','Xml'); IISSite=@('Name','Xml','Bindings'); Certificate=@('Thumbprint','Store','ArtifactPath','ArtifactHash','HasPrivateKey'); LocalUser=@('Name','FullName','Description'); LocalGroup=@('Name','Description','Members'); FirewallRule=@('Name','DisplayName','Direction','Action','Profile','Protocol','LocalPort','RemotePort','LocalAddress','RemoteAddress','Program')
    }
    if (-not $contracts.ContainsKey($Spec.Adapter)) { throw 'Unsupported adapter desired contract.' }
    $optional=@();if($Spec.Adapter -eq 'Service'){$optional=@('SecuritySddl')}
    if($Spec.Adapter -ceq 'SmbShare'){$optional+=@('ScopeName');if($Spec.Desired.PSObject.Properties['ScopeName'] -and [string]$Spec.Desired.ScopeName -cnotin @('','*')){throw 'Clustered or named-scope SMB targets require a dedicated role workflow.'}}
    Assert-WsmFields $Spec.Desired ($contracts[$Spec.Adapter]+$optional)
    $required=$contracts[$Spec.Adapter]; if ($Spec.Adapter -eq 'WindowsFeature') { $required=@('Name') }
    foreach ($f in $required) { if (-not $Spec.Desired.PSObject.Properties[$f]) { throw ('Desired requires '+$f) }; if($f -in @('Name','TaskName','TaskPath','Xml','Path','BinaryPathName','Thumbprint','Store','ArtifactPath','ArtifactHash') -and [string]::IsNullOrWhiteSpace([string]$Spec.Desired.$f)){throw ('Desired requires a nonempty '+$f)} }
    foreach ($f in @('Name','TaskName')) { if ($Spec.Desired.PSObject.Properties[$f] -and [string]$Spec.Desired.$f -match '[\x00-\x1f/\\*?\[\]]') { throw 'Invalid adapter object name.' } }
    if ($Spec.Adapter -eq 'ScheduledTask') { if ($Spec.Desired.TaskPath -notmatch '^\\(?:[^<>:"|?*\x00-\x1f]+\\)*$' -or $Spec.Desired.TaskPath -match '(?:^|\\)\.\.(?:\\|$)') { throw 'Invalid task folder.' }; $xml=Read-WsmXml $Spec.Desired.Xml; if ($xml.DocumentElement.LocalName -ne 'Task') { throw 'Expected task XML.' };[void](ConvertTo-WsmTaskSecuritySddl ([string]$Spec.Desired.SecuritySddl));$folderSpecs=ConvertTo-WsmTaskSecurityFolderSpecs @($Spec.Desired.FolderSecurity);$expected=@(Get-WsmTaskSecurityFolderAncestors $Spec.Desired.TaskPath | ForEach-Object {$_.ToUpperInvariant()} | Sort-Object);$actual=@($folderSpecs | ForEach-Object {$_.Path.ToUpperInvariant()} | Sort-Object);if(($expected -join '|') -cne ($actual -join '|')){throw 'Task FolderSecurity must define exactly the task folder and every ancestor.'} }
    if($Spec.Desired.PSObject.Properties['SecuritySddl']){[void](New-Object Security.AccessControl.RawSecurityDescriptor($Spec.Desired.SecuritySddl))}
    if ($Spec.Adapter -in @('IISPool','IISSite')) { $xml=Read-WsmXml $Spec.Desired.Xml; $elementName='add'; if($Spec.Adapter -eq 'IISSite'){$elementName='site'}; if ($xml.DocumentElement.LocalName -ne $elementName -or $xml.DocumentElement.GetAttribute('name') -cne $Spec.Desired.Name) { throw 'IIS XML/name mismatch.' }; if ($xml.SelectNodes('//*[@password]').Count) { throw 'IIS passwords must be supplied as a SecretRef, not embedded in desired XML.' } }
    if ($Spec.Adapter -eq 'SmbShare') { [void](ConvertTo-WsmCanonicalPath $Spec.Desired.Path); if ($Spec.Desired.Name.EndsWith('$') -and $Spec.Desired.Name -match '^(?:ADMIN|IPC|[A-Z])\$$') { throw 'System administrative shares require dedicated workflow.' } }
    if($Spec.Adapter -eq 'SmbShare'){$seen=@{};foreach($ace in $Spec.Desired.Access){Assert-WsmFields $ace @('AccountName','AccessControlType','AccessRight') @('AccountName','AccessControlType','AccessRight');if([string]::IsNullOrWhiteSpace($ace.AccountName) -or $ace.AccessControlType -cnotin @('Allow','Deny') -or $ace.AccessRight -cnotin @('Read','Change','Full') -or ($ace.AccessControlType -eq 'Deny' -and $ace.AccessRight -ne 'Full')){throw 'Unsupported share ACE; Block-SmbShareAccess only creates Full deny.'};$key=$ace.AccountName.ToUpperInvariant()+'|'+$ace.AccessControlType;if($seen.ContainsKey($key)){throw 'Duplicate share principal/type ACE.'};$seen[$key]=$true}}
    if ($Spec.Adapter -eq 'Certificate') { if ($Spec.Desired.Thumbprint -notmatch '^[A-Fa-f0-9]{40,64}$' -or $Spec.Desired.Store -notmatch '^Cert:\\LocalMachine\\[A-Za-z0-9_-]+$' -or $Spec.Desired.ArtifactHash -notmatch '^[a-fA-F0-9]{64}$') { throw 'Invalid certificate artifact/store.' } }
    if($Spec.Adapter -eq 'IISSite'){$bindings=@((Read-WsmXml $Spec.Desired.Xml).SelectNodes('/site/bindings/binding'));if($bindings.Count -ne @($Spec.Desired.Bindings).Count){throw 'Reviewed IIS binding list differs from site XML.'};foreach($b in $Spec.Desired.Bindings){Assert-WsmFields $b @('Protocol','BindingInformation','CertificateHash','CertificateStoreName','SslFlags') @('Protocol','BindingInformation','CertificateHash','CertificateStoreName','SslFlags');if(@($bindings | Where-Object {$_.GetAttribute('protocol') -ieq $b.Protocol -and $_.GetAttribute('bindingInformation') -ceq $b.BindingInformation}).Count -ne 1){throw 'IIS binding identity differs from XML.'};if($b.Protocol -ieq 'https' -and ($b.CertificateHash -notmatch '^[a-fA-F0-9]{40,64}$' -or -not $b.CertificateStoreName)){throw 'HTTPS requires a reviewed certificate/store; cannot infer a private key.'}}}
    if ($Spec.Adapter -eq 'Service' -and ([string]::IsNullOrWhiteSpace($Spec.Desired.BinaryPathName) -or $Spec.Desired.Name -match '^(?i)(?:WinDefend|NTDS|DNS|DHCPServer|W32Time|LanmanServer|RpcSs)$')) { throw 'Service requires explicit binary and must not replace protected OS services.' }
    if ($Spec.Adapter -eq 'WindowsFeature' -and $Spec.Desired.Name -match '^(?i)(?:AD-Domain-Services|AD-Certificate|ADCS-|Failover-Clustering|DNS|DHCP|Hyper-V)') { throw 'Identity/cluster roles require dedicated product workflow.' }
    if ($Spec.Adapter -eq 'MachineEnvironment' -and $Spec.Desired.Name -match '^(?i)(?:PATH|SystemRoot|windir|COMSPEC|TEMP|TMP|PROCESSOR.*|NUMBER_OF_PROCESSORS)$') { throw 'Shared OS environment variables require dedicated reviewed procedure.' }
    if($Spec.Adapter -eq 'MachineEnvironment' -and $Spec.Desired.Name -ieq 'LOCAL' -and ([string]$Spec.Desired.Value).Length -gt 0){throw 'Nonempty Oracle LOCAL requires external credential-safe handling.'}
    if($Spec.PSObject.Properties['SettingTransition']) {
        Assert-WsmSettingTransition $Spec.SettingTransition | Out-Null
        if($Spec.SettingTransition.Adapter -cne $Spec.Adapter){throw 'SettingTransition adapter must match MigrationSpec.Adapter.'}
        if($Spec.Adapter -in @('MachineEnvironment','TimeZone') -and ($Spec.SettingTransition.Name -cne $Spec.Desired.Name -or [string]$Spec.SettingTransition.After.Value -cne [string]$Spec.Desired.Value)){throw 'Desired state must match the reviewed SettingTransition after value.'}
    }
    if($Spec.Adapter -eq 'TimeZone') { if(-not $Spec.PSObject.Properties['SettingTransition'] -or $Spec.Desired.Name -cne 'TimeZone' -or $Spec.SettingTransition.Adapter -cne 'TimeZone'){throw 'TimeZone requires a typed SettingTransition and the finite TimeZone identity.'} }
    if($Spec.Adapter -eq 'Service'){[void](Assert-WsmServiceSupplement $Spec.Desired.Supplement);$policy=Get-WsmServiceAccountPolicy $Spec.Desired $Spec;if($policy.Mode -ceq 'ReviewRequired'){throw 'Service account mode must be reviewed before migration approval.'};[void](ConvertTo-WsmServiceDependencyMultiSz @($Spec.Desired.Dependencies))};if($Spec.Adapter -eq 'SmbShare' -and ($Spec.Desired.DrainPolicy -cnotin @('BlockNewOpens','CloseReviewedHandles') -or [string]::IsNullOrWhiteSpace($Spec.Desired.DrainEvidence))){throw 'SMB share requires reviewed drain policy and evidence.'};if($Spec.Adapter -eq 'WindowsFeature'){Assert-WsmInstallerPolicy $Spec.Desired}
    $needsSecret=$Spec.Adapter -eq 'LocalUser' -or ($Spec.Adapter -eq 'Certificate' -and $Spec.Desired.HasPrivateKey) -or ($Spec.Adapter -eq 'Service' -and (Get-WsmServiceAccountPolicy $Spec.Desired $Spec).NeededSecret)
    if($Spec.Adapter -eq 'ScheduledTask'){$principal=(Read-WsmXml $Spec.Desired.Xml).SelectSingleNode("//*[local-name()='Principal']/*[local-name()='LogonType']");if($principal -and $principal.InnerText -eq 'Password'){$needsSecret=$true}}
    if($needsSecret -and (-not $Spec.PSObject.Properties['SecretRef'] -or -not $Spec.SecretRef)){throw 'Adapter requires a reviewed SecretRef; no passwords may be stored in desired configuration.'}
}
function Get-WsmAdapterRequiredCommands([string]$Adapter) {
    switch ($Adapter) {
        ScheduledTask { @('Get-ScheduledTask','Register-ScheduledTask','Export-ScheduledTask','Unregister-ScheduledTask') }
        Service { @('Get-Service','New-Service','Set-Service') }
        SmbShare { @('Get-SmbShare','New-SmbShare','Get-SmbShareAccess','Grant-SmbShareAccess','Block-SmbShareAccess') }
        TimeZone { @('Get-TimeZone','Set-TimeZone') }
        WindowsFeature { @('Get-WindowsFeature','Install-WindowsFeature') }
        LocalUser { @('Get-LocalUser','New-LocalUser','Disable-LocalUser') }
        LocalGroup { @('Get-LocalGroup','New-LocalGroup','Add-LocalGroupMember') }
        FirewallRule { @('Get-NetFirewallRule','New-NetFirewallRule') }
        Certificate { @('Get-PfxData','Import-PfxCertificate','Import-Certificate') }
        { $_ -in @('IISPool','IISSite') } { @('Get-WebConfiguration') }
        default { @() }
    }
}
function Get-WsmEveryoneName {(New-Object Security.Principal.SecurityIdentifier('S-1-1-0')).Translate([Security.Principal.NTAccount]).Value}
function ConvertTo-WsmShareAclKeys([object[]]$Access) {
    foreach($ace in $Access){(Resolve-WsmAccountSid ([string]$ace.AccountName))+'|'+[string]$ace.AccessControlType+'|'+[string]$ace.AccessRight}
}
function Test-WsmDesiredWorldDeny($Desired) {
    foreach($ace in $Desired.Access){if($ace.AccessControlType -eq 'Deny' -and (Resolve-WsmAccountSid ([string]$ace.AccountName)) -eq 'S-1-1-0'){return $true}};$false
}
function Get-WsmSecret($Spec,[hashtable]$Secrets) {
    if (-not $Spec.PSObject.Properties['SecretRef'] -or -not $Spec.SecretRef) { return $null }
    if (-not $Secrets -or -not $Secrets.ContainsKey($Spec.SecretRef) -or $Secrets[$Spec.SecretRef] -isnot [Management.Automation.PSCredential]) { throw ('Required in-memory credential unavailable: '+$Spec.SecretRef) }
    $Secrets[$Spec.SecretRef]
}
function New-WsmTaskScheduler {$scheduler=New-Object -ComObject 'Schedule.Service';$scheduler.Connect();$scheduler}
function Test-WsmKnownAdapterAbsentError($ErrorRecord,[string[]]$AllowedIds) { $id=[string]$ErrorRecord.FullyQualifiedErrorId;foreach($allowed in $AllowedIds){if($id.StartsWith($allowed+',',[StringComparison]::OrdinalIgnoreCase) -or $id -ceq $allowed){return $true}};$false }
function Get-WsmAdapterState($Spec) {
    $d=$Spec.Desired
    switch ($Spec.Adapter) {
        ScheduledTask { $t=$null;try{$t=Get-ScheduledTask -TaskName $d.TaskName -TaskPath $d.TaskPath -ErrorAction Stop}catch{if($_.FullyQualifiedErrorId -notmatch 'NoMatchingTasksFound'){throw}};if ($t) { [pscustomobject]@{ Exists=$true; Xml=(Export-ScheduledTask -TaskName $d.TaskName -TaskPath $d.TaskPath -ErrorAction Stop); Enabled=[bool]$t.Settings.Enabled } } else { [pscustomobject]@{Exists=$false} } }
        Service { $s=@(Get-CimInstance Win32_Service | Where-Object Name -CEQ $d.Name); if ($s.Count) { [pscustomobject]@{Exists=$true; Configuration=($s[0] | Select-Object Name,DisplayName,Description,PathName,StartMode,StartName); Supplement=(Get-WsmServiceSupplementState $d.Name);State=[string]$s[0].State;Dependencies=@(Get-WsmServiceDependencies $d.Name)} } else { [pscustomobject]@{Exists=$false} } }
        SmbShare { $shares=@(Get-SmbShare -ErrorAction Stop | Where-Object {$_.Name -ceq $d.Name});if($shares.Count -gt 1){throw 'Target share name is ambiguous across SMB scopes.'};$s=$null;if($shares.Count){$s=$shares[0];if(-not $s.PSObject.Properties['ScopeName'] -or [string]$s.ScopeName -cnotin @('','*')){throw 'Target clustered share scope requires a dedicated role workflow.'}}; if ($s) { [pscustomobject]@{Exists=$true; Configuration=($s | Select-Object Name,Path,Description,EncryptData); Access=@(Get-SmbShareAccess -Name $d.Name -ScopeName '*')} } else { [pscustomobject]@{Exists=$false} } }
        MachineEnvironment { $v=[Environment]::GetEnvironmentVariable($d.Name,'Machine'); [pscustomobject]@{Exists=($null -ne $v); Value=$v} }
        TimeZone { Get-WsmSettingTimeZoneSnapshot }
        WindowsFeature { $f=Get-WindowsFeature -Name $d.Name; if (-not $f) { throw 'Unknown target Windows feature.' }; [pscustomobject]@{Exists=[bool]$f.Installed; Name=$f.Name} }
        LocalUser { $u=$null;try{$u=Get-LocalUser -Name $d.Name -ErrorAction Stop}catch{if(-not (Test-WsmKnownAdapterAbsentError $_ @('UserNotFound'))){throw}};if ($u) { [pscustomobject]@{Exists=$true; Enabled=[bool]$u.Enabled; SID=[string]$u.SID; FullName=$u.FullName; Description=$u.Description} } else { [pscustomobject]@{Exists=$false} } }
        LocalGroup { $g=$null;try{$g=Get-LocalGroup -Name $d.Name -ErrorAction Stop}catch{if(-not (Test-WsmKnownAdapterAbsentError $_ @('GroupNotFound'))){throw}};if ($g) { [pscustomobject]@{Exists=$true; SID=[string]$g.SID; Members=@(Get-LocalGroupMember -Group $d.Name -ErrorAction Stop | ForEach-Object Name)} } else { [pscustomobject]@{Exists=$false} } }
        FirewallRule { $r=$null;try{$r=Get-NetFirewallRule -Name $d.Name -ErrorAction Stop}catch{if(-not (Test-WsmKnownAdapterAbsentError $_ @('CmdletizationQuery_NotFound_Name','CmdletizationQuery_NotFound_Path'))){throw}};if ($r) { [pscustomobject]@{Exists=$true; Enabled=[string]$r.Enabled; Rule=($r | Select-Object Name,Direction,Action,Profile); Ports=@($r | Get-NetFirewallPortFilter -ErrorAction Stop); Addresses=@($r | Get-NetFirewallAddressFilter -ErrorAction Stop); Applications=@($r | Get-NetFirewallApplicationFilter -ErrorAction Stop)} } else { [pscustomobject]@{Exists=$false} } }
        Certificate { $cert=$null;try{$cert=Get-Item -LiteralPath ($d.Store+'\'+$d.Thumbprint) -ErrorAction Stop}catch{if(-not (Test-WsmKnownAdapterAbsentError $_ @('PathNotFound','ItemNotFound'))){throw}};[pscustomobject]@{Exists=($null -ne $cert); HasPrivateKey=($cert -and $cert.HasPrivateKey)} }
        { $_ -in @('IISPool','IISSite') } { Get-WsmIisState $Spec }
        default { throw 'No automatic adapter state for this workflow.' }
    }
}
function ConvertTo-WsmDisabledTaskXml($Spec) {
    $doc=Read-WsmXml $Spec.Desired.Xml; $root=$doc.DocumentElement; $ns=$root.NamespaceURI
    $settings=$root.SelectSingleNode("*[local-name()='Settings']"); if (-not $settings) { $settings=$doc.CreateElement('Settings',$ns); [void]$root.AppendChild($settings) }
    $enabled=$settings.SelectSingleNode("*[local-name()='Enabled']"); if (-not $enabled) { $enabled=$doc.CreateElement('Enabled',$ns); [void]$settings.AppendChild($enabled) }; $enabled.InnerText='false'
    if($Spec.PSObject.Properties['CatchUpPolicy'] -and $Spec.CatchUpPolicy -in @('SkipMissedRuns','DedicatedManualCatchUp')){$catchUp=$settings.SelectSingleNode("*[local-name()='StartWhenAvailable']");if(-not $catchUp){$catchUp=$doc.CreateElement('StartWhenAvailable',$ns);[void]$settings.AppendChild($catchUp)};$catchUp.InnerText='false'}
    if ($Spec.Desired.PSObject.Properties['User'] -and $Spec.Desired.User) { $user=$root.SelectSingleNode("*[local-name()='Principals']/*[local-name()='Principal']/*[local-name()='UserId']"); if ($user) { $user.InnerText=$Spec.Desired.User } else { throw 'Task account mapping requires an existing UserId principal.' } }
    $doc.OuterXml
}
function Invoke-WsmAdapterRestore($Spec,[hashtable]$Secrets,$Package,$InstallerBaseline=$null,[scriptblock]$BeforeFolderCreate,[scriptblock]$AfterFolderCreate,[object[]]$OwnedReceipts=@(),[object[]]$SharedReceipts=@()) {
    Assert-WsmAdapterDesired $Spec; $d=$Spec.Desired; $secret=Get-WsmSecret $Spec $Secrets
    if($Spec.Adapter -eq 'TimeZone'){throw 'TimeZone changes require the durable SettingTransition coordinator.'}
    if($Spec.Adapter -in @('MachineEnvironment','TimeZone') -and $Spec.PSObject.Properties['SettingTransition']){throw 'Reviewed setting changes require the durable SettingTransition coordinator.'}
    if($secret -and $Spec.Adapter -eq 'ScheduledTask'){$principal=(Read-WsmXml (ConvertTo-WsmDisabledTaskXml $Spec)).SelectSingleNode("//*[local-name()='Principal']/*[local-name()='UserId']");if(-not $principal -or $principal.InnerText -ine $secret.UserName){throw 'Credential username must match the reviewed target task principal.'}}
    switch ($Spec.Adapter) {
        ScheduledTask { $scheduler=New-WsmTaskScheduler;if(-not $BeforeFolderCreate){throw 'Durable folder-create intent callback is required for scheduled task restore.'};$folderResult=Prepare-WsmTaskSecurityFolders -Folders @($d.FolderSecurity) -BeforeCreate $BeforeFolderCreate -AfterCreate $AfterFolderCreate -OwnedReceipts $OwnedReceipts -SharedReceipts $SharedReceipts -Scheduler $scheduler;$folder=Get-WsmTaskSecurityFolderObject $scheduler $d.TaskPath;$args=@{ TaskName=$d.TaskName; TaskPath=$d.TaskPath; Xml=(ConvertTo-WsmDisabledTaskXml $Spec); ErrorAction='Stop' }; if ($d.PSObject.Properties['User'] -and $d.User) { $args.User=$d.User }; if ($secret) { $args.User=$secret.UserName; $args.Password=$secret.GetNetworkCredential().Password };try{Register-ScheduledTask @args | Out-Null}finally{[void]$args.Remove('Password')};$task=$folder.GetTask($d.TaskName);$task.SetSecurityDescriptor((ConvertTo-WsmTaskSecuritySddl ([string]$d.SecuritySddl)),0);$taskActual=ConvertTo-WsmTaskSecuritySddl ([string]$task.GetSecurityDescriptor(7));if($taskActual -cne (ConvertTo-WsmTaskSecuritySddl ([string]$d.SecuritySddl))){throw 'Registered task security descriptor readback differs from reviewed descriptor.'};return [pscustomobject]@{RebootRequired=$false;AuxiliaryOwnership=$folderResult.OwnedReceipts} }
        Service { $policy=Get-WsmServiceAccountPolicy $d $Spec;if($policy.Mode -ceq 'ManagedServiceAccount'){New-WsmManagedService $d $Spec | Out-Null}else{$credentialPlan=Get-WsmServiceAccountCredential $d $Spec $Secrets;$args=@{Name=$d.Name;BinaryPathName=$d.BinaryPathName;StartupType='Disabled';ErrorAction='Stop';DependsOn=@($d.Dependencies)};foreach($f in @('DisplayName','Description')){if($d.PSObject.Properties[$f] -and -not [string]::IsNullOrEmpty([string]$d.$f)){$args[$f]=$d.$f}};if($policy.Mode -cne 'KnownLocalSystem'){$args.Credential=$credentialPlan.Credential};New-Service @args | Out-Null};Set-WsmServiceSupplement $d.Name $d.Supplement -Phase Staged | Out-Null;if($d.PSObject.Properties['SecuritySddl']){Invoke-WsmServiceSecurity $d.Name $d.SecuritySddl | Out-Null} }
        SmbShare { $args=@{ Name=$d.Name; Path=$d.Path; ErrorAction='Stop' }; foreach($f in @('Description','EncryptData')) { if ($d.PSObject.Properties[$f] -and -not [string]::IsNullOrEmpty([string]$d.$f)) { $args[$f]=$d.$f } }; $args.NoAccess=@((Get-WsmEveryoneName)); New-SmbShare @args | Out-Null; foreach($a in $d.Access) { if ($a.AccessControlType -eq 'Deny') { Block-SmbShareAccess -Name $d.Name -ScopeName '*' -AccountName $a.AccountName -Force | Out-Null } elseif ($a.AccessControlType -eq 'Allow' -and $a.AccessRight -in @('Read','Change','Full')) { Grant-SmbShareAccess -Name $d.Name -ScopeName '*' -AccountName $a.AccountName -AccessRight $a.AccessRight -Force | Out-Null } else { throw 'Unsupported share ACE.' } }; # Everyone remains denied until explicit activation.
        }
        MachineEnvironment { [Environment]::SetEnvironmentVariable($d.Name,[string]$d.Value,'Machine') }
        WindowsFeature { if(-not $InstallerBaseline){$InstallerBaseline=Get-WsmInstallerSnapshot};$args=@{Name=$d.Name;ErrorAction='Stop'}; if ($d.PSObject.Properties['Source'] -and $d.Source) { $args.Source=$d.Source }; $installError=$null;try{$r=Install-WindowsFeature @args}catch{$installError=$_.Exception};$safety=Protect-WsmInstallerSideEffects $d $InstallerBaseline;if($installError){throw $installError}; $nativeResult='NotReported';if($r.PSObject.Properties['ExitCode']){$nativeResult=[string]$r.ExitCode};if ($r.Success -ne $true -or ($nativeResult -cnotin @('Success','SuccessRestart','NoChangeNeeded'))) { $failure=New-Object InvalidOperationException('Windows feature installation did not succeed; review native result and durable installer baseline.');$failure.Data['NativeTool']='Install-WindowsFeature';$failure.Data['NativeResult']=$nativeResult;throw $failure };return [pscustomobject]@{RebootRequired=([string]$r.RestartNeeded -cne 'No' -or $nativeResult -ceq 'SuccessRestart');InstallerSafety=$safety;NativeResult=$nativeResult;RestartNeeded=[string]$r.RestartNeeded} }
        LocalUser { if (-not $secret) { throw 'New local account requires SecretRef credential.' }; $args=@{Name=$d.Name;Password=$secret.Password;Disabled=$true;ErrorAction='Stop'}; foreach($f in @('FullName','Description')){if($d.PSObject.Properties[$f]){$args[$f]=$d.$f}}; New-LocalUser @args | Out-Null }
        LocalGroup { New-LocalGroup -Name $d.Name -Description $d.Description | Out-Null; foreach($member in $d.Members){Add-LocalGroupMember -Group $d.Name -Member $member} }
        FirewallRule { $args=@{Enabled='False';ErrorAction='Stop'}; foreach($f in $d.PSObject.Properties){$args[$f.Name]=$f.Value}; New-NetFirewallRule @args | Out-Null }
        Certificate { $artifact=Get-WsmCertificateArtifact $Package $d;try{if ($d.HasPrivateKey) { if (-not $secret) { throw 'PFX requires in-memory password credential.' };$data=Get-PfxData -FilePath $artifact -Password $secret.Password;if(@($data.EndEntityCertificates).Count -ne 1 -or @($data.OtherCertificates).Count -gt 0 -or $data.EndEntityCertificates[0].Thumbprint -ine $d.Thumbprint){throw 'PFX must contain the exact reviewed leaf only; chain certificates require separately reviewed items.'}; Import-PfxCertificate -FilePath $artifact -CertStoreLocation $d.Store -Password $secret.Password | Out-Null } else {$cert=New-Object Security.Cryptography.X509Certificates.X509Certificate2($artifact);try{if($cert.Thumbprint -ine $d.Thumbprint -or $cert.HasPrivateKey){throw 'Public certificate artifact differs from reviewed thumbprint/type.'}}finally{$cert.Dispose()}; Import-Certificate -FilePath $artifact -CertStoreLocation $d.Store | Out-Null }}finally{if([IO.File]::Exists($artifact)){[IO.File]::Delete($artifact)}} }
        { $_ -in @('IISPool','IISSite') } { Invoke-WsmIisRestore $Spec $secret }
        default { throw 'Unsupported adapter.' }
    }
    [pscustomobject]@{RebootRequired=$false}
}
function Test-WsmAdapterConfiguration($Spec,[ValidateSet('Staged','Final')][string]$Phase='Staged',[object[]]$OwnedReceipts=@()) {
    $s=Get-WsmAdapterState $Spec; $d=$Spec.Desired; $errors=New-Object 'System.Collections.Generic.List[string]'
    if (-not $s.Exists) { $errors.Add('Object absent') }
    elseif ($Spec.Adapter -eq 'ScheduledTask') {
        $expected=Read-WsmXml (ConvertTo-WsmDisabledTaskXml $Spec); $actual=Read-WsmXml $s.Xml
        # Date/URI registration metadata may be assigned by the scheduler; compare execution-sensitive sections.
        if($Phase -eq 'Final'){$enabled=$expected.SelectSingleNode("//*[local-name()='Settings']/*[local-name()='Enabled']");$enabled.InnerText=([string](Get-WsmDesiredActivation $Spec)).ToLowerInvariant()}
        foreach($name in @('Actions','Triggers','Principals','Settings')) { $a=$actual.DocumentElement.SelectSingleNode("*[local-name()='$name']"); $e=$expected.DocumentElement.SelectSingleNode("*[local-name()='$name']"); if (($null -eq $a) -ne ($null -eq $e) -or ($a -and (ConvertTo-WsmXmlComparable $a) -cne (ConvertTo-WsmXmlComparable $e))) { $errors.Add('Task '+$name+' mismatch') } }
        if ($Phase -eq 'Staged' -and $s.Enabled) { $errors.Add('Task must remain disabled') }
        if($Phase -eq 'Final' -and $s.Enabled -ne (Get-WsmDesiredActivation $Spec)){$errors.Add('Task final enabled state mismatch')}
    }
    elseif ($Spec.Adapter -eq 'Service') { $supplementCheck=Test-WsmServiceSupplement $d.Supplement $s.Supplement -Phase $Phase;foreach($problem in $supplementCheck.Problems){$errors.Add($problem)};if ($s.Configuration.PathName -cne $d.BinaryPathName -or $s.Configuration.DisplayName -cne $d.DisplayName) { $errors.Add('Service binary/display mismatch') };if((ConvertTo-WsmServiceAccount $s.Configuration.StartName) -ine (ConvertTo-WsmServiceAccount $d.Account) -or [string]$s.Configuration.Description -cne [string]$d.Description -or (@($s.Dependencies | Sort-Object) -join ',') -ine (@($d.Dependencies | Sort-Object) -join ',')){$errors.Add('Service account/description/dependencies mismatch')}; if ($Phase -eq 'Staged' -and ($s.Configuration.StartMode -ne 'Disabled' -or $s.State -ne 'Stopped')) { $errors.Add('Service staging invariant violated') } }
    elseif ($Spec.Adapter -eq 'MachineEnvironment') { if ($s.Value -cne [string]$d.Value) { $errors.Add('Environment value mismatch') } }
    elseif ($Spec.Adapter -eq 'TimeZone') {if($Spec.PSObject.Properties['SettingTransition']){if(-not (Test-WsmSettingStateEqual $s $Spec.SettingTransition.After 'TimeZone')){$errors.Add('Time zone or daylight-saving setting mismatch')}}else{$errors.Add('TimeZone requires a reviewed SettingTransition for verification')}}
    elseif ($Spec.Adapter -eq 'SmbShare') {
        if($s.Configuration.Path -ine $d.Path -or $s.Configuration.EncryptData -ne $d.EncryptData -or [string]$s.Configuration.Description -cne [string]$d.Description){$errors.Add('Share configuration mismatch')}
        $expected=@(ConvertTo-WsmShareAclKeys $d.Access);if(($Phase -eq 'Staged' -or -not (Get-WsmDesiredActivation $Spec)) -and -not (Test-WsmDesiredWorldDeny $d)){$expected+=@('S-1-1-0|Deny|Full')};$actual=@(ConvertTo-WsmShareAclKeys $s.Access)
        if((($expected | Sort-Object) -join ';') -cne (($actual | Sort-Object) -join ';')){$errors.Add('Share ACL differs (missing/extra/right/type/principal)')}
    }
    elseif ($Spec.Adapter -eq 'LocalUser') { if ($Phase -eq 'Staged' -and $s.Enabled) { $errors.Add('Local account must remain disabled') }; if ($s.FullName -cne $d.FullName -or $s.Description -cne $d.Description) { $errors.Add('Local user metadata mismatch') } }
    elseif ($Spec.Adapter -eq 'LocalGroup') { if (@(Compare-Object @($d.Members | Sort-Object) @($s.Members | Sort-Object)).Count) { $errors.Add('Group membership mismatch') } }
    elseif ($Spec.Adapter -eq 'Certificate') { if ($s.HasPrivateKey -ne [bool]$d.HasPrivateKey) { $errors.Add('Certificate private key mismatch') } }
    elseif ($Spec.Adapter -eq 'FirewallRule') { if ($Phase -eq 'Staged' -and $s.Enabled -ne 'False') { $errors.Add('Firewall rule must remain disabled') }; if ($s.Rule.Direction -ne $d.Direction -or $s.Rule.Action -ne $d.Action) { $errors.Add('Firewall rule mismatch') };foreach($field in @('LocalPort','RemotePort')){if(@($s.Ports).Count -ne 1 -or (@($s.Ports[0].$field) -join ',') -ine (@($d.$field) -join ',')){$errors.Add('Firewall port/protocol mismatch: '+$field)}};if(@($s.Ports).Count -ne 1 -or (ConvertTo-WsmFirewallProtocol $s.Ports[0].Protocol) -cne (ConvertTo-WsmFirewallProtocol $d.Protocol)){$errors.Add('Firewall protocol mismatch')};foreach($field in @('LocalAddress','RemoteAddress')){if(@($s.Addresses).Count -ne 1 -or (@($s.Addresses[0].$field | Sort-Object) -join ',') -ine (@($d.$field | Sort-Object) -join ',')){$errors.Add('Firewall address mismatch: '+$field)}};if(@($s.Applications).Count -ne 1 -or $s.Applications[0].Program -ine $d.Program){$errors.Add('Firewall program mismatch')};if((@(([string]$s.Rule.Profile).Split(',') | ForEach-Object {$_.Trim()} | Sort-Object) -join ',') -ine (@($d.Profile | ForEach-Object {$_.ToString().Split(',')} | ForEach-Object {$_.Trim()} | Sort-Object) -join ',')){$errors.Add('Firewall profile mismatch')} }
    elseif ($Spec.Adapter -in @('IISPool','IISSite')) { foreach($e in (Test-WsmIisConfiguration $Spec $Phase)){$errors.Add($e)} }
    if($s.Exists -and $d.PSObject.Properties['SecuritySddl']){$actualSddl='';if($Spec.Adapter -eq 'Service'){$actualSddl=Get-WsmServiceSecurity $d.Name}elseif($Spec.Adapter -eq 'ScheduledTask'){$scheduler=New-WsmTaskScheduler;$actualSddl=(Get-WsmTaskSecurityFolderObject $scheduler $d.TaskPath).GetTask($d.TaskName).GetSecurityDescriptor(7)};if((ConvertTo-WsmTaskSecuritySddl $actualSddl) -cne (ConvertTo-WsmTaskSecuritySddl ([string]$d.SecuritySddl))){$errors.Add('Object security descriptor mismatch')}}
    if($s.Exists -and $Spec.Adapter -eq 'ScheduledTask'){try{[void](Assert-WsmTaskSecurityFolders -Folders @($d.FolderSecurity) -OwnedReceipts $OwnedReceipts)}catch{$errors.Add('Task folder security verification failed: '+$_.Exception.GetType().FullName)}}
    if($s.Exists -and $Phase -eq 'Final'){$active=Get-WsmDesiredActivation $Spec;switch($Spec.Adapter){Service{$mode='Disabled';$state='Stopped';if($active){$mode='Manual';if($Spec.DesiredFinalState -eq 'Automatic'){$mode='Auto'};if($Spec.DesiredFinalState -in @('Automatic','Running')){$state='Running'}};if($s.Configuration.StartMode -ne $mode -or $s.State -ne $state){$errors.Add('Service final mode/running state mismatch')}};LocalUser{if($s.Enabled -ne $active){$errors.Add('User final enabled state mismatch')}};FirewallRule{if(($s.Enabled -eq 'True') -ne $active){$errors.Add('Firewall final enabled state mismatch')}};}}
    [pscustomobject]@{Passed=($errors.Count -eq 0); Problems=$errors.ToArray(); Actual=$s; Phase=$Phase}
}
function Get-WsmDesiredActivation($Spec) { $Spec.PSObject.Properties['DesiredFinalState'] -and $Spec.DesiredFinalState -in @('Enabled','Automatic','Manual','Running') }
function ConvertTo-WsmXmlComparable($Node) {
    $attributes=[ordered]@{};foreach($a in @($Node.Attributes | Where-Object {$_.Name -ne 'xmlns' -and $_.Prefix -ne 'xmlns'} | Sort-Object LocalName)){$attributes[$a.LocalName]=$a.Value};$elements=@($Node.ChildNodes | Where-Object NodeType -EQ ([Xml.XmlNodeType]::Element));if($Node.LocalName -notin @('Actions','Triggers')){$elements=@($elements | Sort-Object LocalName)};$children=@(foreach($child in $elements){ConvertTo-WsmXmlComparable $child});$text='';if(-not $elements.Count){$text=$Node.InnerText};([pscustomobject][ordered]@{Name=$Node.LocalName;Attributes=$attributes;Text=$text;Children=$children} | ConvertTo-Json -Compress -Depth 30)
}
function Remove-WsmCreatedAdapter($Spec) {
    $d=$Spec.Desired
    switch($Spec.Adapter){
        ScheduledTask { Unregister-ScheduledTask -TaskName $d.TaskName -TaskPath $d.TaskPath -Confirm:$false }
        Service { $s=Get-CimInstance Win32_Service | Where-Object Name -CEQ $d.Name; if($s.State -ne 'Stopped'){throw 'Stop created service before rollback.'}; $r=Invoke-CimMethod -InputObject $s -MethodName Delete; if($r.ReturnValue -ne 0){throw ('Service delete native code '+$r.ReturnValue)} }
        SmbShare { Remove-SmbShare -Name $d.Name -ScopeName '*' -Force }
        MachineEnvironment { [Environment]::SetEnvironmentVariable($d.Name,$null,'Machine') }
        TimeZone { throw 'TimeZone cannot be removed; restore a reviewed prior state through SettingTransition rollback.' }
        WindowsFeature { throw 'Feature removal requires explicit dedicated rollback; dependency/reboot effects must be reviewed.' }
        LocalUser { Remove-LocalUser -Name $d.Name }
        LocalGroup { Remove-LocalGroup -Name $d.Name }
        FirewallRule { Remove-NetFirewallRule -Name $d.Name }
        Certificate { Remove-Item -LiteralPath ($d.Store+'\'+$d.Thumbprint) }
        { $_ -in @('IISPool','IISSite') } { Remove-WsmIisObject $Spec }
    }
}

function ConvertTo-WsmFirewallProtocol([string]$Value){switch($Value.ToUpperInvariant()){TCP{'6'};UDP{'17'};ICMPV4{'1'};ICMPV6{'58'};ANY{'256'};default{$Value}}}

function Get-WsmServiceDependencies([string]$Name){$p=Get-ItemProperty -LiteralPath ('HKLM:\SYSTEM\CurrentControlSet\Services\'+$Name);if($p.PSObject.Properties['DependOnService']){@($p.DependOnService)};if($p.PSObject.Properties['DependOnGroup']){foreach($group in @($p.DependOnGroup)){if([string]::IsNullOrWhiteSpace($group)){throw 'Empty source service dependency group.'};'+'+[string]$group}}}
function ConvertTo-WsmServiceAccount([string]$Name){switch -Regex ($Name){'^(?i:LocalSystem|NT AUTHORITY\\SYSTEM|SYSTEM|S-1-5-18)$'{'LocalSystem';break};'^(?i:LocalService|NT AUTHORITY\\LocalService|S-1-5-19)$'{'NT AUTHORITY\LocalService';break};'^(?i:NetworkService|NT AUTHORITY\\NetworkService|S-1-5-20)$'{'NT AUTHORITY\NetworkService';break};default{$Name}}}
