function Get-WsmCoordinationUtc([string]$Value, [string]$Label, [int]$FreshHours=24) {
    $parsed=[DateTimeOffset]::MinValue
    if(-not [DateTimeOffset]::TryParse($Value,[ref]$parsed) -or $parsed.Offset -ne [TimeSpan]::Zero -or $parsed -gt [DateTimeOffset]::UtcNow.AddMinutes(5) -or $parsed -lt [DateTimeOffset]::UtcNow.AddHours(-$FreshHours)){throw ($Label+' is stale or has an invalid UTC clock.')}
    $parsed
}
function Assert-WsmCoordinationPlan($Plan,[string]$PlanHash) {
    Assert-WsmEnvelope $Plan 'MigrationPlan'
    foreach($id in @($Plan.BatchId,$Plan.PairId,$Plan.ApprovalId,$Plan.Source.HostId,$Plan.Target.HostId)){Assert-WsmId $id}
    if($PlanHash -notmatch '^[a-fA-F0-9]{64}$' -or $Plan.Mode -cne 'IsolatedPilot' -or $Plan.Source.Fingerprint -notmatch '^[a-f0-9]{64}$' -or $Plan.Target.Fingerprint -notmatch '^[a-f0-9]{64}$' -or -not $Plan.Items){throw 'Invalid or incomplete approved plan for coordination.'}
    $Plan
}
function Read-WsmCoordinationGroup([string]$Path,[string]$ExpectedHash) {
    $group=Read-WsmTrustedJson $Path $ExpectedHash;Assert-WsmEnvelope $group 'ConsistencyGroupPlan'
    Assert-WsmId $group.BatchId
    if($group.GroupId -notmatch '^[A-Za-z0-9_. -]{1,128}$'){throw 'Invalid consistency group name.'}
    if(-not $group.Owner -or -not $group.Evidence -or $group.Members.Count -lt 2){throw 'Consistency group requires reviewed owner/evidence and at least two members.'}
    $seen=@{}
    foreach($m in $group.Members){Assert-WsmId $m.PairId;Assert-WsmId $m.SourceHostId;Assert-WsmId $m.TargetHostId;Assert-WsmId $m.ApprovalId
        if($seen.ContainsKey($m.PairId) -or $m.PlanHash -notmatch '^[a-fA-F0-9]{64}$' -or $m.SourceFingerprint -notmatch '^[a-f0-9]{64}$' -or $m.TargetFingerprint -notmatch '^[a-f0-9]{64}$'){throw 'Duplicate or invalid consistency group member.'};$seen[$m.PairId]=$m
    }
    $group
}
function New-WsmConsistencyGroupPlan {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$GroupId,[Parameter(Mandatory)][object[]]$Members,[Parameter(Mandatory)][string]$Owner,[Parameter(Mandatory)][string]$Evidence,[Parameter(Mandatory)][string]$Path)
    if($GroupId -notmatch '^[A-Za-z0-9_. -]{1,128}$'){throw 'Consistency group name must use 1 to 128 letters, digits, spaces, dots, underscores or hyphens.'}
    if([string]::IsNullOrWhiteSpace($Owner) -or [string]::IsNullOrWhiteSpace($Evidence) -or $Members.Count -lt 2){throw 'Group owner/evidence and at least two approved member plans are required.'}
    $rows=New-Object 'System.Collections.Generic.List[object]';$seen=@{};$batch=''
    foreach($entry in $Members){if(-not $entry.PlanPath -or $entry.PlanHash -notmatch '^[a-fA-F0-9]{64}$'){throw 'Each member requires PlanPath and independently obtained PlanHash.'}
        $plan=Read-WsmTrustedJson $entry.PlanPath $entry.PlanHash;[void](Assert-WsmCoordinationPlan $plan $entry.PlanHash)
        if($batch -and $batch -cne $plan.BatchId){throw 'Consistency group members must belong to one batch.'};$batch=$plan.BatchId
        if($seen.ContainsKey($plan.PairId)){throw 'Duplicate pair in consistency group.'};$seen[$plan.PairId]=$true
        $tagged=@($plan.Items | Where-Object {$_.Decision -eq 'Include' -and $_.ConsistencyGroup -ceq $GroupId});if(-not $tagged.Count){throw ('Plan has no included item reviewed for consistency group '+$GroupId+': '+$plan.PairId)}
        foreach($item in $tagged){if(-not $item.ConsistencyOwner -or -not $item.ConsistencyEvidence -or $item.ConsistencyOwner -cne $Owner -or $item.ConsistencyEvidence -cne $Evidence){throw ('Group owner/evidence must match the reviewed item metadata for pair '+$plan.PairId)}}
        $dependencies=@();if($plan.PSObject.Properties['CrossHostDependencies']){$dependencies=@($plan.CrossHostDependencies)}
        $rows.Add([pscustomobject][ordered]@{PairId=$plan.PairId;SourceHostId=$plan.Source.HostId;SourceFingerprint=$plan.Source.Fingerprint;TargetHostId=$plan.Target.HostId;TargetFingerprint=$plan.Target.Fingerprint;ApprovalId=$plan.ApprovalId;InventoryRevision=$plan.InventoryRevision;DecisionRevision=$plan.DecisionRevision;Dependencies=$dependencies;PlanPath=[IO.Path]::GetFullPath($entry.PlanPath);PlanHash=$entry.PlanHash.ToLowerInvariant()})
    }
    $group=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='ConsistencyGroupPlan';GroupId=$GroupId;BatchId=$batch;Owner=$Owner;Evidence=$Evidence;CreatedUtc=(Get-WsmUtc);Members=$rows.ToArray();ProductionVerified=$false}
    Write-WsmJson $Path $group
    [pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;Group=$group}
}
function New-WsmConsistencyGroupReceipt {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$GroupPlanPath,[Parameter(Mandatory)][string]$GroupPlanHash,[Parameter(Mandatory)][string]$PairId,[Parameter(Mandatory)][ValidateSet('FinalStaged','Activated','RolledBack')][string]$Stage,[Parameter(Mandatory)][string]$PlanPath,[Parameter(Mandatory)][string]$PlanHash,[Parameter(Mandatory)][string]$ManifestPath,[Parameter(Mandatory)][string]$ManifestHash,[Parameter(Mandatory)][string]$FreezePath,[Parameter(Mandatory)][string]$FreezeHash,[string]$StageResultPath,[string]$StageResultHash,[string]$RollbackEvidencePath,[string]$RollbackEvidenceHash,[Parameter(Mandatory)][string]$Path)
    $group=Read-WsmCoordinationGroup $GroupPlanPath $GroupPlanHash;$member=@($group.Members | Where-Object PairId -CEQ $PairId);if($member.Count -ne 1){throw 'Pair is not an exact member of the reviewed group.'}
    $plan=Read-WsmTrustedJson $PlanPath $PlanHash;[void](Assert-WsmCoordinationPlan $plan $PlanHash);$m=$member[0]
    if($plan.PairId -cne $m.PairId -or $plan.BatchId -cne $group.BatchId -or $plan.Source.HostId -cne $m.SourceHostId -or $plan.Source.Fingerprint -cne $m.SourceFingerprint -or $plan.Target.HostId -cne $m.TargetHostId -or $plan.Target.Fingerprint -cne $m.TargetFingerprint -or $plan.ApprovalId -cne $m.ApprovalId -or $plan.InventoryRevision -ne $m.InventoryRevision -or $plan.DecisionRevision -ne $m.DecisionRevision -or $PlanHash -ine $m.PlanHash){throw 'Plan does not match the exact reviewed group membership/hash.'}
    Assert-WsmMigrationHost (Get-WsmMachineIdentity) $plan.Target.Fingerprint
    $freeze=Read-WsmTrustedJson $FreezePath $FreezeHash;Assert-WsmEnvelope $freeze 'SourceFreeze'
    if($freeze.PairId -cne $PairId -or $freeze.BatchId -cne $group.BatchId -or $freeze.ApprovalId -cne $plan.ApprovalId -or $freeze.PlanHash -ine $PlanHash -or $freeze.SourceHostId -cne $plan.Source.HostId -or $freeze.SourceFingerprint -cne $plan.Source.Fingerprint -or $freeze.Acknowledgement -cne 'OWNER-CONFIRMED-QUIESCENCE' -or -not $freeze.Owner -or -not $freeze.Evidence){throw 'Source freeze is not bound to this approved plan and source.'}
    $freezeProduced=[DateTimeOffset]::MinValue;if(-not [DateTimeOffset]::TryParse($freeze.ProducedUtc,[ref]$freezeProduced) -or $freezeProduced.Offset -ne [TimeSpan]::Zero -or $freezeProduced -gt [DateTimeOffset]::UtcNow.AddMinutes(5)){throw 'Source freeze has an invalid UTC production time.'};if($Stage -in @('FinalStaged','Activated')){[void](Get-WsmCoordinationUtc $freeze.ProducedUtc 'Source freeze' 24)};$expires=[DateTimeOffset]::MinValue;if(-not [DateTimeOffset]::TryParse($freeze.ExpiresUtc,[ref]$expires) -or $expires.Offset -ne [TimeSpan]::Zero -or $expires -le $freezeProduced -or (($Stage -in @('FinalStaged','Activated')) -and $expires -le [DateTimeOffset]::UtcNow)){throw 'Source freeze expired or has invalid expiry for this barrier stage.'}
    $package=Test-WsmMigrationPackage $ManifestPath $ManifestHash;$manifest=$package.Manifest;Assert-WsmEnvelope $manifest 'MigrationPackage'
    if(-not $package.Valid -or $package.Plan.PairId -cne $PairId -or $package.Plan.ApprovalId -cne $plan.ApprovalId -or $package.PlanHash -ine $PlanHash){throw 'Local package failed its full artifact/plan validation.'}
    if($manifest.PairId -cne $PairId -or $manifest.BatchId -cne $group.BatchId -or $manifest.ApprovalId -cne $plan.ApprovalId -or $manifest.PlanHash -ine $PlanHash -or $manifest.Source.HostId -cne $plan.Source.HostId -or $manifest.Source.Fingerprint -cne $plan.Source.Fingerprint -or $manifest.Target.HostId -cne $plan.Target.HostId -or $manifest.Target.Fingerprint -cne $plan.Target.Fingerprint -or -not $manifest.Final -or $manifest.FreezeHash -ine $FreezeHash -or $manifest.Generation -lt 1){throw 'Final package identity, freeze, generation or plan binding mismatch.'}
    $result=$null;$resultHash='';$stageResultProducedUtc='';$rollbackSummary=$null
    if($Stage -eq 'FinalStaged' -or $Stage -eq 'Activated'){
        if(-not $StageResultPath -or $StageResultHash -notmatch '^[a-fA-F0-9]{64}$'){throw 'A trusted local staged validation or activation result is required.'}
        $result=Read-WsmTrustedJson $StageResultPath $StageResultHash;Assert-WsmEnvelope $result 'StageResult';$resultHash=$StageResultHash.ToLowerInvariant()
        $expectedStage='PreCutoverValidation';if($Stage -eq 'Activated'){$expectedStage='Cutover'}
        if($result.BatchId -cne $group.BatchId -or $result.PairId -cne $PairId -or $result.SourceHostId -cne $plan.Source.HostId -or $result.TargetHostId -cne $plan.Target.HostId -or $result.TargetFingerprint -cne $plan.Target.Fingerprint -or $result.ApprovalId -cne $plan.ApprovalId -or $result.PlanHash -ine $PlanHash -or $result.ManifestHash -ine $ManifestHash -or $result.PayloadGeneration -ne $manifest.Generation -or $result.Stage -cne $expectedStage -or $result.Status -cne 'Succeeded' -or $result.Mode -cne 'IsolatedPilot' -or $result.ProductionVerified -ne $false){throw 'Member stage result is incomplete or bound to another plan/package/generation.'}
        [void](Get-WsmCoordinationUtc $result.ProducedUtc 'Member stage result' 24);$stageResultProducedUtc=$result.ProducedUtc
    } else {
        if(-not $RollbackEvidencePath -or $RollbackEvidenceHash -notmatch '^[a-fA-F0-9]{64}$'){throw 'RolledBack requires a trusted local RollbackResult envelope.'}
        $result=Read-WsmTrustedJson $RollbackEvidencePath $RollbackEvidenceHash;Assert-WsmEnvelope $result 'RollbackResult';$resultHash=$RollbackEvidenceHash.ToLowerInvariant()
        if($result.PairId -cne $PairId -or $result.BatchId -cne $group.BatchId -or $result.SourceHostId -cne $plan.Source.HostId -or $result.SourceFingerprint -cne $plan.Source.Fingerprint -or $result.TargetHostId -cne $plan.Target.HostId -or $result.TargetFingerprint -cne $plan.Target.Fingerprint -or $result.ApprovalId -cne $plan.ApprovalId -or $result.PlanHash -ine $PlanHash -or $result.ManifestHash -ine $ManifestHash -or $result.Generation -ne $manifest.Generation -or $result.Status -cne 'RollbackEvidenceComplete' -or $result.Mode -cne 'IsolatedPilot' -or $result.ProductionVerified -ne $false -or $result.JournalHash -notmatch '^[a-f0-9]{64}$' -or -not $result.Owner -or -not $result.Evidence -or $result.CompletionScope -cne 'AutoRollbackAndExplicitReadbackOrExternalAttestation'){throw 'RollbackResult does not prove accountable completion for this exact generation.'};[void](Assert-WsmRollbackResultItemOutcomes $plan $result)
        $externalOutcomes=@($result.ItemResults | Where-Object Outcome -CEQ 'ExternalProcedureReportedComplete')
        if($externalOutcomes.Count){if(-not $result.DedicatedEvidencePath -or $result.DedicatedEvidenceHash -notmatch '^[a-fA-F0-9]{64}$' -or @($externalOutcomes | Where-Object ExternalEvidenceHash -INE $result.DedicatedEvidenceHash).Count){throw 'External rollback outcomes do not share one exact typed evidence artifact.'};$dedicated=Read-WsmTrustedJson $result.DedicatedEvidencePath $result.DedicatedEvidenceHash;Assert-WsmEnvelope $dedicated 'DedicatedRollbackEvidence';if($dedicated.BatchId -cne $group.BatchId -or $dedicated.PairId -cne $PairId -or $dedicated.ApprovalId -cne $plan.ApprovalId -or $dedicated.PlanHash -ine $PlanHash -or $dedicated.ManifestHash -ine $ManifestHash -or $dedicated.Generation -ne $manifest.Generation -or $dedicated.TargetHostId -cne $plan.Target.HostId -or $dedicated.TargetFingerprint -cne $plan.Target.Fingerprint -or $dedicated.Mode -cne 'IsolatedPilot' -or $dedicated.ProductionVerified -ne $false -or [string]::IsNullOrWhiteSpace([string]$dedicated.Owner) -or [string]::IsNullOrWhiteSpace([string]$dedicated.Evidence)){throw 'Dedicated rollback artifact does not bind the exact local plan/package/generation/target.'};[void](Get-WsmCoordinationUtc $dedicated.ProducedUtc 'Dedicated rollback evidence' 24);$dedicatedRows=@{};foreach($row in @($dedicated.Items)){if($dedicatedRows.ContainsKey($row.ItemId)){throw 'Dedicated rollback artifact repeats an item attestation.'};$dedicatedRows[$row.ItemId]=$row};if($dedicatedRows.Count -ne $externalOutcomes.Count){throw 'Dedicated rollback artifact item count differs from typed result outcomes.'};foreach($outcome in $externalOutcomes){if(-not $dedicatedRows.ContainsKey($outcome.ItemId)){throw 'Typed rollback outcome has no dedicated evidence item.'};$row=$dedicatedRows[$outcome.ItemId];if($row.Adapter -cne $outcome.Adapter -or $row.Status -cne 'ProcedureReportedComplete' -or [string]::IsNullOrWhiteSpace([string]$row.Procedure) -or [string]::IsNullOrWhiteSpace([string]$row.Evidence) -or [string]::IsNullOrWhiteSpace([string]$row.Owner) -or $outcome.EvidenceReference -cne $row.Evidence -or $outcome.Owner -cne $row.Owner -or (Get-WsmHashText (ConvertTo-Json -InputObject $row -Depth 20 -Compress)) -ine $outcome.ExternalEvidenceItemHash){throw 'Dedicated rollback item attestation differs from its typed result outcome.'};[void](Get-WsmCoordinationUtc $row.CompletedUtc ('Dedicated rollback item '+$outcome.ItemId) 24)}}elseif($result.DedicatedEvidencePath -or $result.DedicatedEvidenceHash){throw 'Rollback result contains an unused dedicated evidence reference.'}
        $rollbackItems=@($result.ItemResults);$rollbackSummary=[pscustomobject][ordered]@{IncludedItemCount=$rollbackItems.Count;LocallyRolledBackCount=@($rollbackItems | Where-Object Outcome -CEQ 'RolledBack').Count;PreExistingUnchangedCount=@($rollbackItems | Where-Object Outcome -CEQ 'PreExistingUnchanged').Count;ExternalProcedureReportedCompleteCount=$externalOutcomes.Count;ExternalVerificationLimit='External procedure outcomes are operator-reported attestations; the migration tool did not execute or verify native product rollback.'}
        [void](Get-WsmCoordinationUtc $result.ProducedUtc 'Rollback result' 24);$stageResultProducedUtc=$result.ProducedUtc
    }
    $receipt=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='ConsistencyGroupReceipt';GroupId=$group.GroupId;GroupPlanHash=$GroupPlanHash.ToLowerInvariant();BatchId=$group.BatchId;PairId=$PairId;SourceHostId=$plan.Source.HostId;SourceFingerprint=$plan.Source.Fingerprint;TargetHostId=$plan.Target.HostId;TargetFingerprint=$plan.Target.Fingerprint;ApprovalId=$plan.ApprovalId;InventoryRevision=$plan.InventoryRevision;DecisionRevision=$plan.DecisionRevision;PlanHash=$PlanHash.ToLowerInvariant();ManifestHash=$ManifestHash.ToLowerInvariant();Generation=[int]$manifest.Generation;Stage=$Stage;FreezeHash=$FreezeHash.ToLowerInvariant();FreezeExpiresUtc=$freeze.ExpiresUtc;StageResultHash=$resultHash;StageResultProducedUtc=$stageResultProducedUtc;RollbackOutcomeSummary=$rollbackSummary;ProducedUtc=(Get-WsmUtc);Mode='IsolatedPilot';ProductionVerified=$false}
    Write-WsmJson $Path $receipt;[pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;Receipt=$receipt}
}
function Assert-WsmConsistencyGroupBarrier {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$GroupPlanPath,[Parameter(Mandatory)][string]$GroupPlanHash,[Parameter(Mandatory)][ValidateSet('FinalStaged','Activated','RolledBack')][string]$Stage,[Parameter(Mandatory)][object[]]$Receipts,[object[]]$AnchorReceipts=@(),[object[]]$ExternalActivatedReceipts=@())
    $group=Read-WsmCoordinationGroup $GroupPlanPath $GroupPlanHash;$wanted=@{};foreach($m in $group.Members){$wanted[$m.PairId]=$m};$seen=@{}
    foreach($inputReceipt in $Receipts){if(-not $inputReceipt.Path -or $inputReceipt.SHA256 -notmatch '^[a-fA-F0-9]{64}$'){throw 'Each barrier receipt requires a path and independent SHA256.'};$r=Read-WsmTrustedJson $inputReceipt.Path $inputReceipt.SHA256;Assert-WsmEnvelope $r 'ConsistencyGroupReceipt'
        if($r.GroupId -cne $group.GroupId -or $r.GroupPlanHash -ine $GroupPlanHash -or $r.BatchId -cne $group.BatchId -or $r.Stage -cne $Stage -or $r.Mode -cne 'IsolatedPilot' -or $r.ProductionVerified -ne $false -or -not $wanted.ContainsKey($r.PairId) -or $seen.ContainsKey($r.PairId)){throw 'Group barrier receipt is duplicate, stale or outside this reviewed stage/membership.'};$m=$wanted[$r.PairId]
        if($r.SourceHostId -cne $m.SourceHostId -or $r.SourceFingerprint -cne $m.SourceFingerprint -or $r.TargetHostId -cne $m.TargetHostId -or $r.TargetFingerprint -cne $m.TargetFingerprint -or $r.ApprovalId -cne $m.ApprovalId -or $r.InventoryRevision -ne $m.InventoryRevision -or $r.DecisionRevision -ne $m.DecisionRevision -or $r.PlanHash -ine $m.PlanHash -or $r.ManifestHash -notmatch '^[a-fA-F0-9]{64}$' -or $r.FreezeHash -notmatch '^[a-fA-F0-9]{64}$' -or $r.Generation -lt 1 -or $r.StageResultHash -notmatch '^[a-fA-F0-9]{64}$'){throw 'Group receipt identity/hash/generation binding mismatch.'}
        if($Stage -eq 'RolledBack'){$summary=$r.RollbackOutcomeSummary;if(-not $summary -or $summary.IncludedItemCount -lt 1 -or $summary.LocallyRolledBackCount -lt 0 -or $summary.PreExistingUnchangedCount -lt 0 -or $summary.ExternalProcedureReportedCompleteCount -lt 0 -or ($summary.LocallyRolledBackCount+$summary.PreExistingUnchangedCount+$summary.ExternalProcedureReportedCompleteCount) -ne $summary.IncludedItemCount -or ($summary.ExternalProcedureReportedCompleteCount -gt 0 -and $summary.ExternalVerificationLimit -notmatch 'operator-reported attestations')){throw 'Rollback group receipt lacks a complete, explicit typed outcome summary.'}}
        [void](Get-WsmCoordinationUtc $r.ProducedUtc 'Group receipt' 24);[void](Get-WsmCoordinationUtc $r.StageResultProducedUtc 'Member evidence' 24);$freezeExpires=[DateTimeOffset]::MinValue;if(-not [DateTimeOffset]::TryParse($r.FreezeExpiresUtc,[ref]$freezeExpires) -or $freezeExpires.Offset -ne [TimeSpan]::Zero -or (($Stage -in @('FinalStaged','Activated')) -and $freezeExpires -le [DateTimeOffset]::UtcNow)){throw 'Source freeze expired before the consistency barrier.'};$seen[$r.PairId]=$r
    }
    foreach($id in $wanted.Keys){if(-not $seen.ContainsKey($id)){throw ('Group barrier incomplete; member receipt missing: '+$id)}}
    if($Stage -ne 'FinalStaged'){
        $anchors=@{};foreach($inputAnchor in $AnchorReceipts){if(-not $inputAnchor.Path -or $inputAnchor.SHA256 -notmatch '^[a-fA-F0-9]{64}$'){throw 'Each final-staged anchor requires a path and independent SHA256.'};$a=Read-WsmTrustedJson $inputAnchor.Path $inputAnchor.SHA256;Assert-WsmEnvelope $a 'ConsistencyGroupReceipt';if($a.GroupId -cne $group.GroupId -or $a.GroupPlanHash -ine $GroupPlanHash -or $a.BatchId -cne $group.BatchId -or $a.Stage -cne 'FinalStaged' -or -not $wanted.ContainsKey($a.PairId) -or $anchors.ContainsKey($a.PairId)){throw 'Final-staged anchor is outside this reviewed group or duplicated.'};$anchors[$a.PairId]=$a}
        foreach($id in $wanted.Keys){if(-not $anchors.ContainsKey($id)){throw ('Final-staged generation anchor missing: '+$id)};$anchor=$anchors[$id];$current=$seen[$id];if($anchor.PlanHash -ine $current.PlanHash -or $anchor.ManifestHash -ine $current.ManifestHash -or $anchor.Generation -ne $current.Generation -or $anchor.FreezeHash -ine $current.FreezeHash -or $anchor.FreezeExpiresUtc -cne $current.FreezeExpiresUtc){throw ('Member receipt drifted from its final-staged generation anchor: '+$id)}}
    }
    if($Stage -eq 'FinalStaged' -or $Stage -eq 'Activated'){
        foreach($m in $group.Members){
            foreach($edge in @($m.Dependencies | Where-Object Type -CEQ 'Mandatory')){if($wanted.ContainsKey($edge.PairId)){continue};$provider=@($ExternalActivatedReceipts | Where-Object {$_.Result.PairId -ceq $edge.PairId -and $_.Result.Stage -ceq 'Cutover' -and $_.Result.Status -ceq 'Succeeded'});if($provider.Count -ne 1 -or $provider[0].IndependentHash -notmatch '^[a-fA-F0-9]{64}$' -or $provider[0].Result.Mode -cne 'IsolatedPilot' -or $provider[0].Result.ProductionVerified -ne $false -or $provider[0].Result.ManifestHash -notmatch '^[a-fA-F0-9]{64}$' -or $provider[0].Result.PayloadGeneration -lt 1){throw ('External mandatory provider must remain activated with a fresh trusted receipt: '+$edge.PairId)};[void](Get-WsmCoordinationUtc $provider[0].Result.ProducedUtc 'External provider activation' 24)}
        }
    }
    [pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='ConsistencyGroupBarrier';GroupId=$group.GroupId;GroupPlanHash=$GroupPlanHash.ToLowerInvariant();BatchId=$group.BatchId;Stage=$Stage;MemberCount=$group.Members.Count;Members=@($seen.Values | Sort-Object PairId);Passed=$true;ProductionVerified=$false;CreatedUtc=(Get-WsmUtc)}
}
function Assert-WsmRollbackResultItemOutcomes($Plan,$Result) {
    if(-not $Result.PSObject.Properties['ItemResults']){throw 'RollbackResult must include a typed outcome for every included item.'}
    $expected=@{};foreach($item in @($Plan.Items | Where-Object Decision -EQ Include)){$expected[$item.ItemId]=$item};$seen=@{}
    foreach($row in @($Result.ItemResults)){
        if(-not $expected.ContainsKey($row.ItemId) -or $seen.ContainsKey($row.ItemId)){throw 'RollbackResult item outcomes are duplicate or outside the approved plan.'};$item=$expected[$row.ItemId];$adapter=[string]$item.MigrationSpec.Adapter
        if($row.Adapter -cne $adapter){throw ('RollbackResult item adapter mismatch: '+$row.ItemId)}
        switch -CaseSensitive ($row.Outcome){
            'RolledBack' {if($row.Verification -cne 'LocalRollbackState' -or $row.StateStatus -cne 'RolledBack' -or $row.JournalHash -ine $Result.JournalHash -or $adapter -in @('ManualWorkflow','WindowsFeature')){throw 'Automatic rollback outcome is not valid for this adapter or local state.'}}
            'PreExistingUnchanged' {if($adapter -eq 'ManualWorkflow' -or $row.Verification -cne 'LocalReadback' -or $row.BeforeHash -notmatch '^[a-fA-F0-9]{64}$' -or $row.ActualHash -ine $row.BeforeHash -or $row.NativeReadbackVerified -ne $true -or -not $row.ReadBackUtc){throw 'Pre-existing unchanged outcome lacks matching local readback hashes.'};[void](Get-WsmCoordinationUtc $row.ReadBackUtc ('Pre-existing item readback '+$row.ItemId) 24)}
            'ExternalProcedureReportedComplete' {if($adapter -notin @('ManualWorkflow','WindowsFeature') -or $row.Verification -cne 'ExternalAttestation' -or $row.ExternalEvidenceHash -notmatch '^[a-fA-F0-9]{64}$' -or $row.ExternalEvidenceItemHash -notmatch '^[a-fA-F0-9]{64}$' -or $row.NativeReadbackVerified -ne $false -or $row.Limitation -notmatch 'did not execute or verify' -or -not $row.EvidenceReference -or -not $row.Owner){throw 'External rollback outcome is not a typed, bounded dedicated-procedure attestation.'}}
            default {throw ('Unknown rollback outcome: '+[string]$row.Outcome)}
        }
        $seen[$row.ItemId]=$true
    }
    if($seen.Count -ne $expected.Count){throw 'RollbackResult lacks a typed outcome for one or more included items.'}
    $true
}
function Export-WsmRollbackResult {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$ManifestPath,[Parameter(Mandatory)][string]$ExpectedHash,[Parameter(Mandatory)][string]$StateDirectory,[Parameter(Mandatory)][string]$Owner,[Parameter(Mandatory)][string]$Evidence,[Parameter(Mandatory)][string]$Path,[string]$DedicatedEvidencePath,[string]$DedicatedEvidenceHash)
    if([string]::IsNullOrWhiteSpace($Owner) -or [string]::IsNullOrWhiteSpace($Evidence)){throw 'Rollback result requires an accountable owner and independent evidence reference.'}
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $package.Manifest.Target.Fingerprint;$operationPaths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId
    Invoke-WsmLocked $operationPaths.Root {
        $state=Get-WsmOperationState $operationPaths $package
        if($state.ManifestHash -ine $ExpectedHash -or $state.Generation -ne $package.Manifest.Generation -or @($state.PendingOperations).Count -or $state.Stage -notin @('RolledBack','Succeeded','ManualEvidenceRequired','RebootRequired','Failed')){throw 'Local operation is not in a completed or explicitly reviewable rollback state for this generation.'}
        $included=@($package.Plan.Items | Where-Object Decision -EQ Include);if(-not $included.Count){throw 'Rollback result cannot be exported for an empty selection.'};$itemsById=@{};foreach($item in $included){if($itemsById.ContainsKey($item.ItemId)){throw 'Approved plan repeats an included item identity.'};$itemsById[$item.ItemId]=$item}
        $recordsById=@{};foreach($record in @($state.Items)){if(-not $itemsById.ContainsKey($record.ItemId) -or $recordsById.ContainsKey($record.ItemId)){throw 'Local rollback state contains an unknown or duplicate item record.'};$recordsById[$record.ItemId]=$record}
        foreach($item in $included){if(-not $recordsById.ContainsKey($item.ItemId)){throw ('Included item has no local state record: '+$item.ItemId)}}
        $externalItems=@($included | Where-Object {$_.MigrationSpec.Adapter -eq 'ManualWorkflow' -or ($_.MigrationSpec.Adapter -eq 'WindowsFeature' -and $recordsById[$_.ItemId].CreatedByTool)})
        $external=$null;$externalRows=@{}
        if($externalItems.Count){if(-not $DedicatedEvidencePath -or $DedicatedEvidenceHash -notmatch '^[a-fA-F0-9]{64}$'){throw 'ManualWorkflow and tool-created WindowsFeature items require typed DedicatedRollbackEvidence; owner text alone is not rollback proof.'};$external=Read-WsmTrustedJson $DedicatedEvidencePath $DedicatedEvidenceHash;Assert-WsmEnvelope $external 'DedicatedRollbackEvidence';if($external.BatchId -cne $package.Manifest.BatchId -or $external.PairId -cne $package.Manifest.PairId -or $external.ApprovalId -cne $package.Manifest.ApprovalId -or $external.PlanHash -ine $package.Manifest.PlanHash -or $external.ManifestHash -ine $ExpectedHash -or $external.Generation -ne $package.Manifest.Generation -or $external.TargetHostId -cne $package.Manifest.Target.HostId -or $external.TargetFingerprint -cne $package.Manifest.Target.Fingerprint -or $external.Mode -cne 'IsolatedPilot' -or $external.ProductionVerified -ne $false -or [string]::IsNullOrWhiteSpace([string]$external.Owner) -or [string]::IsNullOrWhiteSpace([string]$external.Evidence)){throw 'Dedicated rollback evidence is not bound to the exact local plan/package/generation/target.'};[void](Get-WsmCoordinationUtc $external.ProducedUtc 'Dedicated rollback evidence' 24)
            foreach($row in @($external.Items)){if($externalRows.ContainsKey($row.ItemId) -or $row.Adapter -notin @('ManualWorkflow','WindowsFeature') -or $row.Status -cne 'ProcedureReportedComplete' -or [string]::IsNullOrWhiteSpace([string]$row.Procedure) -or [string]::IsNullOrWhiteSpace([string]$row.Evidence) -or [string]::IsNullOrWhiteSpace([string]$row.Owner)){throw 'Dedicated rollback evidence contains an incomplete, duplicate, or unsupported item attestation.'};$externalRows[$row.ItemId]=$row}
            if($externalRows.Count -ne $externalItems.Count){throw 'Dedicated rollback evidence must contain exactly one attestation for each required external procedure.'};foreach($item in $externalItems){$row=$externalRows[$item.ItemId];if($row.Adapter -cne $item.MigrationSpec.Adapter){throw ('Dedicated rollback evidence adapter mismatch: '+$item.ItemId)};[void](Get-WsmCoordinationUtc $row.CompletedUtc ('Dedicated rollback item '+$item.ItemId) 24)}
        }elseif($DedicatedEvidencePath -or $DedicatedEvidenceHash){throw 'Dedicated rollback evidence was supplied when no included item requires an external procedure.'}
        if($state.Stage -ne 'RolledBack' -and -not $externalItems.Count){throw 'Local operation has not reached RolledBack; external evidence is required for every non-automatic outcome.'}
        $outcomes=New-Object 'System.Collections.Generic.List[object]'
        foreach($item in $included){$record=$recordsById[$item.ItemId];$adapter=[string]$item.MigrationSpec.Adapter
            if($adapter -eq 'ManualWorkflow' -or ($adapter -eq 'WindowsFeature' -and $record.CreatedByTool)){$evidenceRow=$externalRows[$item.ItemId];$rowJson=ConvertTo-Json -InputObject $evidenceRow -Depth 20 -Compress;$outcomes.Add([pscustomobject][ordered]@{ItemId=$item.ItemId;Adapter=$adapter;Outcome='ExternalProcedureReportedComplete';Verification='ExternalAttestation';ExternalEvidenceHash=$DedicatedEvidenceHash.ToLowerInvariant();ExternalEvidenceItemHash=(Get-WsmHashText $rowJson);NativeReadbackVerified=$false;Limitation='Operator-supplied dedicated-procedure attestation; migration tool did not execute or verify native product rollback.';EvidenceReference=[string]$evidenceRow.Evidence;Owner=[string]$evidenceRow.Owner}) ;continue}
            if($record.CreatedByTool){if($record.Status -cne 'RolledBack'){throw ('Tool-created item lacks completed automatic rollback: '+$item.ItemId)};$outcomes.Add([pscustomobject][ordered]@{ItemId=$item.ItemId;Adapter=$adapter;Outcome='RolledBack';Verification='LocalRollbackState';StateStatus=[string]$record.Status;NativeReadbackVerified=$false;JournalHash=$state.JournalHash});continue}
            if($record.Status -notin @('Succeeded','RebootRequired')){throw ('Pre-existing item does not have a successful original readback record: '+$item.ItemId)}
            if($adapter -eq 'FileScope'){$actualHash=Get-WsmFileScopeDigest $item.MigrationSpec.TargetPath $item.MigrationSpec.Metadata}else{$check=Test-WsmAdapterConfiguration $item.MigrationSpec;if(-not $check.Passed){throw ('Pre-existing item no longer passes local readback: '+$item.ItemId)};$actualHash=Get-WsmHashText ($check.Actual | ConvertTo-Json -Depth 15 -Compress)}
            if($actualHash -notmatch '^[a-fA-F0-9]{64}$' -or $actualHash -ine $record.ActualHash){throw ('Pre-existing item readback differs from its recorded original configuration: '+$item.ItemId)}
            $outcomes.Add([pscustomobject][ordered]@{ItemId=$item.ItemId;Adapter=$adapter;Outcome='PreExistingUnchanged';Verification='LocalReadback';BeforeHash=$record.ActualHash;ActualHash=$actualHash;ReadBackUtc=(Get-WsmUtc);NativeReadbackVerified=$true})
        }
        if($state.JournalHash -notmatch '^[a-f0-9]{64}$'){throw 'Local operation journal hash is unavailable; rollback result cannot be exported.'}
        $result=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='RollbackResult';BatchId=$package.Manifest.BatchId;PairId=$package.Manifest.PairId;SourceHostId=$package.Manifest.Source.HostId;SourceFingerprint=$package.Manifest.Source.Fingerprint;TargetHostId=$package.Manifest.Target.HostId;TargetFingerprint=$package.Manifest.Target.Fingerprint;ApprovalId=$package.Manifest.ApprovalId;PlanHash=$package.Manifest.PlanHash;ManifestHash=$ExpectedHash.ToLowerInvariant();Generation=$package.Manifest.Generation;Status='RollbackEvidenceComplete';CompletionScope='AutoRollbackAndExplicitReadbackOrExternalAttestation';ItemResults=$outcomes.ToArray();DedicatedEvidencePath=$(if($external){[IO.Path]::GetFullPath($DedicatedEvidencePath)}else{''});DedicatedEvidenceHash=$(if($external){$DedicatedEvidenceHash.ToLowerInvariant()}else{''});Owner=$Owner;Evidence=$Evidence;JournalHash=$state.JournalHash;ProducedUtc=(Get-WsmUtc);Mode='IsolatedPilot';ProductionVerified=$false}
        [void](Assert-WsmRollbackResultItemOutcomes $package.Plan $result);Write-WsmJson $Path $result;[pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;Result=$result}
    }
}
