function Get-WsmObservationClock { [DateTimeOffset]::UtcNow }
function Assert-WsmObservationHours($Value) {
    if($Value -isnot [int] -and $Value -isnot [long]){throw 'ObservationHours must be an integer.'}
    if($Value -lt 1 -or $Value -gt 8760){throw 'ObservationHours must be between 1 and 8760.'}
}
function Get-WsmObservationWindow($State) {
    if(-not $State.Cutover -or $State.Cutover.Stage -cne 'Activated' -or -not $State.Cutover.PSObject.Properties['ActivatedUtc'] -or -not $State.Cutover.PSObject.Properties['ObservationHours']){throw 'Observation requires a durable completed activation and reviewed duration.'}
    Assert-WsmObservationHours $State.Cutover.ObservationHours
    $activation=[DateTimeOffset]::MinValue
    if(-not [DateTimeOffset]::TryParse($State.Cutover.ActivatedUtc,[ref]$activation) -or $activation.Offset -ne [TimeSpan]::Zero){throw 'Invalid activation UTC timestamp.'}
    $now=Get-WsmObservationClock
    if($activation -gt $now){throw 'Clock precedes completed activation; observation is blocked.'}
    $earliest=$activation.AddHours($State.Cutover.ObservationHours)
    [pscustomobject]@{ActivatedUtc=$State.Cutover.ActivatedUtc;RequiredHours=$State.Cutover.ObservationHours;EarliestCompletionUtc=$earliest.ToString('o');ObservedUntilUtc=$now.ToString('o');ElapsedHours=($now-$activation).TotalHours;Ready=($now -ge $earliest);BusinessEvidenceRequired=$true}
}
function Complete-WsmCutoverObservation($Paths,$State) {
    Assert-WsmObservationHours $State.Cutover.ObservationHours
    $activation=Get-WsmUtc
    $State.Cutover | Add-Member NoteProperty ActivatedUtc $activation -Force
    Add-WsmJournal $Paths $State 'CutoverCompleted' '' ([pscustomobject]@{Status=$State.Stage;ActivatedUtc=$activation;ObservationHours=$State.Cutover.ObservationHours})
}
function Invoke-WsmFreezeCore {
    [CmdletBinding(SupportsShouldProcess)]param([string]$PlanPath,[string]$ExpectedHash,[string]$Path,[string]$Owner,[string]$Evidence,[Parameter(Mandatory)][string]$Acknowledgement,[switch]$SourceIdentityReleased,[string]$ReleaseEvidence,[ValidateRange(1,48)][int]$ValidHours=4,[Parameter(Mandatory)][string]$SourceStateDirectory,[string]$PreviousFreezePath,[string]$PreviousFreezeHash,[string]$SourceAttemptPath,[string]$OriginalBaselinePath,[string]$OriginalBaselineHash)
    $p=Read-WsmMigrationPlan $PlanPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $p.Source.Fingerprint
    if($Acknowledgement -cne 'OWNER-CONFIRMED-QUIESCENCE' -or -not $Owner -or -not $Evidence){throw 'Source freeze requires owner-confirmed quiescence and independent evidence.'}
    if($SourceIdentityReleased -and -not $ReleaseEvidence){throw 'Source hostname/IP/domain release requires independent release evidence.'}
    $previousFreeze=$null;if($PreviousFreezePath){$previousFreeze=Read-WsmFreezeRecord $PreviousFreezePath $PreviousFreezeHash $p -AllowExpired}
    $beforeResult=Export-WsmInventory $SourceStateDirectory -DeepDiscovery:($p.Source.PSObject.Properties['DiscoveryDepth'] -and $p.Source.DiscoveryDepth -eq 'Deep');$before=Read-WsmTrustedJson $beforeResult.Path $beforeResult.SHA256;$original=@{};foreach($i in $before.Items){$original[$i.ItemId]=$i};if($before.Source.HostId -cne $p.Source.HostId){throw 'Source inventory identity mismatch.'};foreach($i in $p.Items){if($i.Decision -eq 'Include' -and $i.Kind -ne 'ManualItem'){$baseline=$i.SettingsHash;if($previousFreeze){$old=@($previousFreeze.QuiescedSettingsHashes | Where-Object ItemId -CEQ $i.ItemId);if($old.Count -ne 1 -or $old[0].OriginalHash -cne $i.SettingsHash){throw 'Previous freeze baseline does not match approved item.'};$baseline=$old[0].QuiescedHash};if(-not $original.ContainsKey($i.ItemId) -or $original[$i.ItemId].SettingsHash -cne $baseline){throw 'Source configuration drift before freeze; review required.'}}}
    if(-not $PSCmdlet.ShouldProcess($p.Source.Name,'Disable selected source producers and record owner-confirmed freeze')){return}
    $shareOriginalIndex=@{};if($OriginalBaselinePath){$savedBaseline=Read-WsmTrustedJson $OriginalBaselinePath $OriginalBaselineHash;Assert-WsmInventory $savedBaseline;if($savedBaseline.Source.HostId -cne $p.Source.HostId){throw 'Original share baseline inventory belongs to another source.'};foreach($entry in $savedBaseline.Items){$shareOriginalIndex[$entry.ItemId]=$entry}};$activities=New-Object 'System.Collections.Generic.List[object]'
    $freezeOrder=@(Get-WsmRestoreOrder @($p.Items | Where-Object Decision -EQ Include));[array]::Reverse($freezeOrder)
    foreach($i in $freezeOrder){$allowed=@{ScheduledTask='ScheduledTask';Service='Service';IISPool='IISPool';IISSite='IISSite'};if($allowed.ContainsKey($i.Kind) -and $i.MigrationSpec.Adapter -cne $allowed[$i.Kind]){$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind=$i.Kind;State='OwnerConfirmedDedicatedQuiescence';Name=$i.NaturalKey});continue};switch($i.Kind){
        Share {if($i.MigrationSpec.Adapter -eq 'SmbShare'){if(-not $SourceAttemptPath){throw 'Share drain needs durable source freeze workflow baseline.'};$attempt=Read-WsmJson $SourceAttemptPath;$shareBaseline=@($attempt.ShareBaselines | Where-Object ItemId -CEQ $i.ItemId);if($shareBaseline.Count -ne 1){throw 'Share has no unique saved original ACL baseline.'};$drain=Invoke-WsmShareQuiescence -Plan $p -Item $i -BaselinePath $shareBaseline[0].Path -BaselineHash $shareBaseline[0].SHA256 -AttemptPath $SourceAttemptPath -AttemptHash (Get-FileHash -LiteralPath $SourceAttemptPath).Hash;$activities.Add($drain.Activity)}else{$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind='Share';State='OwnerConfirmedDedicatedQuiescence';Name=$i.NaturalKey})}}
        ScheduledTask {$full=$i.NaturalKey;$last=$full.LastIndexOf('\');$folder=$full.Substring(0,$last+1);$name=$full.Substring($last+1);Disable-ScheduledTask -TaskName $name -TaskPath $folder | Out-Null;$t=Get-ScheduledTask -TaskName $name -TaskPath $folder;if($t.Settings.Enabled -or [string]$t.State -eq 'Running'){throw 'Task is enabled/running; stop/reconcile its in-flight business operation before freezing.'};$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind='ScheduledTask';State='Disabled';Name=$full})}
        Service {$name=$i.NaturalKey;Set-Service -Name $name -StartupType Disabled;Stop-Service -Name $name -ErrorAction Stop;$s=Get-CimInstance Win32_Service | Where-Object Name -CEQ $name;if(-not $s -or $s.StartMode -ne 'Disabled' -or $s.State -ne 'Stopped'){throw 'Source service did not quiesce.'};$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind='Service';State='DisabledStopped';Name=$name})}
        {$_ -in @('IISSite','IISPool')} {$m=New-WsmIisManager;try{$o=$m.Sites[$i.NaturalKey];if($i.Kind -eq 'IISPool'){$o=$m.ApplicationPools[$i.NaturalKey];$o.AutoStart=$false}else{$o.ServerAutoStart=$false};if(-not $o){throw 'Source IIS object absent.'};$m.CommitChanges();if([string]$o.State -ne 'Stopped'){[void]$o.Stop()};if([string]$o.State -ne 'Stopped'){throw 'Source IIS object did not stop.'};$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind=$i.Kind;State='Stopped';Name=$i.NaturalKey})}finally{$m.Dispose()}}
    }}
    $afterResult=Export-WsmInventory $SourceStateDirectory -DeepDiscovery:($p.Source.PSObject.Properties['DiscoveryDepth'] -and $p.Source.DiscoveryDepth -eq 'Deep');$after=Read-WsmTrustedJson $afterResult.Path $afterResult.SHA256;$quiesced=@{};foreach($i in $after.Items){$quiesced[$i.ItemId]=$i};$hashes=@(foreach($i in $p.Items){if($i.Decision -eq 'Include' -and $i.Kind -ne 'ManualItem'){if(-not $quiesced.ContainsKey($i.ItemId)){throw 'Source item disappeared while freezing.'};if($i.Kind -eq 'Share' -and $i.MigrationSpec.Adapter -eq 'SmbShare'){$attempt=Read-WsmJson $SourceAttemptPath;$shareRecord=@($attempt.ShareQuiescence | Where-Object ItemId -CEQ $i.ItemId);$shareBaseline=@($attempt.ShareBaselines | Where-Object ItemId -CEQ $i.ItemId);if($shareRecord.Count -ne 1 -or $shareBaseline.Count -ne 1 -or -not $shareOriginalIndex.ContainsKey($i.ItemId)){throw 'Share drain has no complete original inventory/intent proof.'};$saved=Read-WsmTrustedJson $shareBaseline[0].Path $shareBaseline[0].SHA256;[void](Assert-WsmShareQuiescenceInventoryDelta $saved $shareOriginalIndex[$i.ItemId] $quiesced[$i.ItemId] $shareRecord[0] $shareBaseline[0].SHA256)}else{Assert-WsmQuiescenceChange $original[$i.ItemId] $quiesced[$i.ItemId] $activities.ToArray()};[pscustomobject]@{ItemId=$i.ItemId;OriginalHash=$i.SettingsHash;QuiescedHash=$quiesced[$i.ItemId].SettingsHash}}})
    $r=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='SourceFreeze';FreezeId=[Guid]::NewGuid().ToString();BatchId=$p.BatchId;PairId=$p.PairId;ApprovalId=$p.ApprovalId;PlanHash=$ExpectedHash;SourceHostId=$p.Source.HostId;SourceFingerprint=$p.Source.Fingerprint;Owner=$Owner;Evidence=$Evidence;Acknowledgement=$Acknowledgement;SourceIdentityReleased=[bool]$SourceIdentityReleased;ReleaseEvidence=$ReleaseEvidence;Activities=$activities.ToArray();QuiescedSettingsHashes=$hashes;ProducedUtc=(Get-WsmUtc);ExpiresUtc=[DateTime]::UtcNow.AddHours($ValidHours).ToString('o');Scope='Selected producers plus externally owner-confirmed writers; not a remote interlock'}
    Write-WsmJson $Path $r;[pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path).Hash;FreezeId=$r.FreezeId;ExpiresUtc=$r.ExpiresUtc}
}
function Assert-WsmQuiescenceChange($Before,$After,[object[]]$Activities) {
    if($Before.SettingsHash -ceq $After.SettingsHash){return};$expected=ConvertFrom-WsmJson ($Before.Settings | ConvertTo-Json -Depth 30);$actual=ConvertFrom-WsmJson ($After.Settings | ConvertTo-Json -Depth 30)
    $activity=@($Activities | Where-Object {$_.ItemId -ceq $Before.ItemId -and $_.State -ne 'OwnerConfirmedDedicatedQuiescence'})
    if($Before.Kind -eq 'Share' -and $activity.Count){$oldKeys=@(ConvertTo-WsmShareAclKeys $Before.Settings.Access);$newKeys=@(ConvertTo-WsmShareAclKeys $After.Settings.Access);if($oldKeys -cnotcontains 'S-1-1-0|Deny|Full'){$oldKeys+=@('S-1-1-0|Deny|Full')};if((($oldKeys | Sort-Object) -join ';') -cne (($newKeys | Sort-Object) -join ';')){throw 'Source share drift is not exactly the temporary Everyone deny.'};$expected.Access=$actual.Access}
    if($Before.Kind -eq 'Service' -and $activity.Count){$expected.StartMode='Disabled'}
    elseif($Before.Kind -eq 'ServiceRegistryDetails' -and @($Activities | Where-Object {$_.Kind -eq 'Service' -and $_.Name -ceq $Before.NaturalKey -and $_.State -eq 'DisabledStopped'}).Count){$expected.Start=4}
    elseif($Before.Kind -in @('ScheduledTask','IISPool','IISSite','IISGlobalConfig')){
        $xml=Read-WsmXml $expected.Xml
        if($Before.Kind -eq 'ScheduledTask' -and $activity.Count){$node=$xml.SelectSingleNode("//*[local-name()='Settings']/*[local-name()='Enabled']");if(-not $node){throw 'Task lacked explicit Enabled setting; use dedicated freeze procedure.'};$node.InnerText='false'}
        elseif($Before.Kind -eq 'IISPool' -and $activity.Count){$xml.DocumentElement.SetAttribute('autoStart','false')}
        elseif($Before.Kind -eq 'IISSite' -and $activity.Count){$xml.DocumentElement.SetAttribute('serverAutoStart','false')}
        elseif($Before.Kind -eq 'IISGlobalConfig'){foreach($a in $Activities){if($a.Kind -eq 'IISPool' -and $a.State -eq 'Stopped'){foreach($node in $xml.SelectNodes('/configuration/system.applicationHost/applicationPools/add')){if($node.GetAttribute('name') -ceq $a.Name){$node.SetAttribute('autoStart','false')}}};if($a.Kind -eq 'IISSite' -and $a.State -eq 'Stopped'){foreach($node in $xml.SelectNodes('/configuration/system.applicationHost/sites/site')){if($node.GetAttribute('name') -ceq $a.Name){$node.SetAttribute('serverAutoStart','false')}}}}}
        $expected.Xml=ConvertTo-WsmXmlComparable $xml.DocumentElement;$actual.Xml=ConvertTo-WsmXmlComparable (Read-WsmXml $actual.Xml).DocumentElement
    }
    if(($expected | ConvertTo-Json -Compress -Depth 30) -cne ($actual | ConvertTo-Json -Compress -Depth 30)){throw ('Non-quiescence configuration changed during freeze: '+$Before.ItemId+'; do not bless it as final delta.')}
}
function Read-WsmFreezeRecord([string]$Path,[string]$ExpectedHash,$Plan,[switch]$AllowExpired) {
    $r=Read-WsmTrustedJson $Path $ExpectedHash;Assert-WsmEnvelope $r 'SourceFreeze';Assert-WsmId $r.FreezeId
    if($r.PairId -cne $Plan.PairId -or $r.ApprovalId -cne $Plan.ApprovalId -or $r.SourceHostId -cne $Plan.Source.HostId -or $r.SourceFingerprint -cne $Plan.Source.Fingerprint -or $r.Acknowledgement -cne 'OWNER-CONFIRMED-QUIESCENCE' -or -not $r.Owner -or -not $r.Evidence){throw 'Freeze identity/evidence mismatch.'}
    $now=[DateTimeOffset]::UtcNow;$produced=[DateTimeOffset]::MinValue;$expires=[DateTimeOffset]::MinValue
    if(-not [DateTimeOffset]::TryParse($r.ProducedUtc,[ref]$produced) -or -not [DateTimeOffset]::TryParse($r.ExpiresUtc,[ref]$expires) -or $produced.Offset -ne [TimeSpan]::Zero -or $expires.Offset -ne [TimeSpan]::Zero -or $produced -gt $now.AddMinutes(5) -or (-not $AllowExpired -and $expires -le $now) -or $expires -le $produced){throw 'Freeze expired or source clock invalid; refresh source evidence.'}
    $r
}
function Set-WsmValidationEvidence {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[string]$ItemId,[ValidateSet('ManualRestore','BusinessStaged','BusinessFinal','DNS','Kerberos','ExternalConnectivity','Monitoring','BackupRestore','LongCycleJobs','SecurityAgent','License','UserAcceptance','Observation','RollbackReconcile','RetirementRetention')][string]$Check,[string]$Owner,[string]$Evidence,[bool]$Passed,[ValidateRange(1,720)][int]$ValidHours=24)
    if(-not $Owner -or -not $Evidence){throw 'Validation requires responsible owner and independent evidence reference.'}
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $package.Manifest.Target.Fingerprint;$paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId
    if($ItemId -and -not @($package.Plan.Items | Where-Object {$_.ItemId -ceq $ItemId -and $_.Decision -eq 'Include'}).Count){throw 'Evidence item absent/excluded.'}
    Invoke-WsmLocked $paths.Root {$state=Get-WsmOperationState $paths $package;if($state.ManifestHash -ine $ExpectedHash){throw 'Evidence must bind to applied generation.'};if($Check -eq 'BusinessFinal' -and (-not $state.Cutover -or $state.Cutover.Stage -ne 'Activated')){throw 'Final business evidence can only be recorded after activation.'};$observation=$null;if($Check -ceq 'Observation'){if($ItemId){throw 'Observation is a pair-level check.'};$observation=Get-WsmObservationWindow $state;if($Passed -and -not $observation.Ready){throw 'Reviewed observation period has not elapsed since completed activation.'}};$record=[pscustomobject]@{ItemId=$ItemId;Check=$Check;Owner=$Owner;Evidence=$Evidence;Passed=$Passed;ManifestHash=$ExpectedHash;Generation=$package.Manifest.Generation;Phase=$state.Stage;Utc=(Get-WsmUtc);ExpiresUtc=[DateTime]::UtcNow.AddHours($ValidHours).ToString('o');ManualEvidence=$true};if($observation){$record | Add-Member NoteProperty Observation $observation};$state.Evidence=@($state.Evidence | Where-Object {-not ($_.ItemId -ceq $ItemId -and $_.Check -ceq $Check)})+@($record);Add-WsmJournal $paths $state 'ValidationEvidence' $ItemId $record;$record}
}
function Test-WsmEvidence($State,[string]$ItemId,[string]$Check,[string]$ManifestHash) {
    $matches=@($State.Evidence | Where-Object {$_.ItemId -ceq $ItemId -and $_.Check -ceq $Check -and $_.Passed -and $_.ManifestHash -ieq $ManifestHash -and [DateTime]::Parse($_.ExpiresUtc).ToUniversalTime() -gt [DateTime]::UtcNow})
    if($matches.Count -ne 1){return $false};if($Check -ceq 'Observation'){try{$window=Get-WsmObservationWindow $State;if(-not $window.Ready -or -not $matches[0].PSObject.Properties['Observation']){return $false};$record=$matches[0].Observation;return ($record.Ready -and $record.ActivatedUtc -ceq $window.ActivatedUtc -and $record.RequiredHours -eq $window.RequiredHours -and [DateTimeOffset]::Parse($record.ObservedUntilUtc) -le (Get-WsmObservationClock) -and [DateTimeOffset]::Parse($record.ObservedUntilUtc) -ge [DateTimeOffset]::Parse($window.EarliestCompletionUtc))}catch{return $false}};return $true
}
function Invoke-WsmValidation {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[ValidateSet('Staged','Final')][string]$Phase='Staged',[hashtable]$SidMap=@{})
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $package.Manifest.Target.Fingerprint;$paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId
    $SidMap=Resolve-WsmIdentityMap $package.Plan $SidMap
    Invoke-WsmLocked $paths.Root {$state=Get-WsmOperationState $paths $package;if($state.ManifestHash -ine $ExpectedHash){throw 'Validation requires current applied generation.'};$checks=New-Object 'System.Collections.Generic.List[object]'
        foreach($item in $package.Plan.Items){if($item.Decision -ne 'Include'){continue};$spec=$item.MigrationSpec;$configuration=$false;$problems=@();$automatic=$spec.Adapter -ne 'ManualWorkflow'
            try{$ownership=@($state.Items | Where-Object ItemId -CEQ $item.ItemId);if($ownership.Count -and $ownership[0].Status -eq 'RebootRequired'){Assert-WsmRebootCompleted $ownership[0]};if($spec.Adapter -eq 'FileScope'){$r=Test-WsmFileScope $item $package $spec.TargetPath $SidMap;$configuration=$r.Passed;$problems=$r.Problems}elseif($automatic){$r=Test-WsmAdapterConfiguration $spec $Phase;$configuration=$r.Passed;$problems=$r.Problems;if($spec.Adapter -eq 'WindowsFeature' -and $ownership.Count -and $ownership[0].CreatedByTool){[void](Test-WsmInstallerConsumers $spec.Desired $ownership[0].InstallerSafety $Phase)}}else{$configuration=Test-WsmEvidence $state $item.ItemId ManualRestore $ExpectedHash;if(-not $configuration){$problems=@('Dedicated restore procedure evidence missing')}}}catch{$problems=@($_.Exception.GetType().FullName)}
            $businessCheck='BusinessStaged';if($Phase -eq 'Final'){$businessCheck='BusinessFinal'};$business=Test-WsmEvidence $state $item.ItemId $businessCheck $ExpectedHash
            $checks.Add([pscustomobject]@{ItemId=$item.ItemId;ConfigurationPassed=$configuration;BusinessPassed=$business;Passed=($configuration -and $business);AutomaticConfiguration=$automatic;BusinessEvidence='Owner supplied; no arbitrary package commands run';Problems=$problems;Utc=(Get-WsmUtc);ManifestHash=$ExpectedHash})
        }
        $passed=($checks.Count -gt 0 -and @($checks | Where-Object Passed -EQ $false).Count -eq 0);$result=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='ValidationResult';PairId=$state.PairId;ManifestHash=$ExpectedHash;Generation=$state.Generation;Phase=$Phase;Passed=$passed;Checks=$checks.ToArray();Utc=(Get-WsmUtc);ProductionVerified=$false}
        Write-WsmJson (Join-Path $paths.Root ('validation-'+$Phase+'.json')) $result;Add-WsmJournal $paths $state 'ValidationCompleted' '' ([pscustomobject]@{Phase=$Phase;Passed=$passed;Checks=$checks.Count});$result
    }
}
function New-WsmCutoverPlan {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[string]$NetworkPath,[string]$NetworkHash,[string]$Path,[string]$DependencyEvidencePath,[string]$DependencyEvidenceHash,[string]$GroupEvidenceIndexPath,[string]$GroupEvidenceIndexHash)
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;if(-not $package.Manifest.Final){throw 'Cutover requires final frozen generation.'};$freeze=Read-WsmFreezeRecord (Join-Path $package.Root 'freeze.json') $package.Manifest.FreezeHash $package.Plan;if(-not $freeze.SourceIdentityReleased -or -not $freeze.ReleaseEvidence){throw 'Source identity release evidence missing.'}
    $dependency=Read-WsmCutoverDependencies $package $ExpectedHash $DependencyEvidencePath $DependencyEvidenceHash $GroupEvidenceIndexPath $GroupEvidenceIndexHash;$receipts=$dependency.Receipts
    $network=Read-WsmTrustedJson $NetworkPath $NetworkHash;Assert-WsmFields $network @('FinalName','InterfaceAlias','FinalIP','PrefixLength','DefaultGateway','DnsServers','TemporaryIP','DomainProcedureEvidence','RollbackProcedure','Owner','MaintenanceWindowUtc','ValidUntilUtc','ObservationHours') @('FinalName','InterfaceAlias','FinalIP','PrefixLength','DnsServers','TemporaryIP','DomainProcedureEvidence','RollbackProcedure','Owner','MaintenanceWindowUtc','ValidUntilUtc')
    if(-not $network.PSObject.Properties['ObservationHours']){$network | Add-Member NoteProperty ObservationHours 24};Assert-WsmObservationHours $network.ObservationHours
    if($network.FinalName -notmatch '^[A-Za-z0-9][A-Za-z0-9-]{0,14}$' -or -not $network.Owner -or -not $network.DomainProcedureEvidence -or -not $network.RollbackProcedure){throw 'Invalid final name or missing domain/rollback owner procedure.'};$ip=$null;if(-not [Net.IPAddress]::TryParse($network.FinalIP,[ref]$ip) -or $ip.AddressFamily -ne [Net.Sockets.AddressFamily]::InterNetwork -or $network.PrefixLength -lt 1 -or $network.PrefixLength -gt 32){throw 'Automatic cutover currently requires explicit IPv4 interface/prefix.'};foreach($address in @($network.DnsServers)+@($network.TemporaryIP)+@($network.DefaultGateway)){if($address -and -not [Net.IPAddress]::TryParse($address,[ref]$ip)){throw 'Invalid network address.'}}
    $validation=Invoke-WsmValidation $ManifestPath $ExpectedHash $StateDirectory Staged;if(-not $validation.Passed){throw 'Staged configuration and business validation must pass.'}
    $p=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='CutoverPlan';CutoverId=[Guid]::NewGuid().ToString();PairId=$package.Manifest.PairId;ManifestHash=$ExpectedHash;Generation=$package.Manifest.Generation;TargetFingerprint=$package.Manifest.Target.Fingerprint;FreezeHash=$package.Manifest.FreezeHash;DependencyReceipts=$receipts;DependencyEvidencePath=$DependencyEvidencePath;DependencyEvidenceHash=$DependencyEvidenceHash;GroupCoordination=$dependency.GroupCoordination;Network=$network;ReviewedUtc=(Get-WsmUtc);Actions=@('Verify source release and final-generation validation','Rename target if required; reboot and revalidate staging before activation','Apply reviewed final IP/DNS and remove explicitly listed temporary IP','Activate explicitly reviewed objects','Record post-cutover business/security/backup evidence');ProductionVerified=$false}
    Write-WsmJson $Path $p;[pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path).Hash;Plan=$p}
}
function Invoke-WsmAdapterActivation($Spec,[bool]$Enable,$Ownership=$null) {
    if($Spec.Adapter -in @('FileScope','ManualWorkflow')){return}
    $d=$Spec.Desired;$desired='Disabled';if($Spec.PSObject.Properties['DesiredFinalState']){$desired=$Spec.DesiredFinalState};$active=$Enable -and $desired -in @('Enabled','Automatic','Manual','Running')
    switch($Spec.Adapter){
        WindowsFeature {if($Ownership -and $Ownership.CreatedByTool){Invoke-WsmInstallerConsumerActivation $d $Ownership.InstallerSafety $Enable}}
        ScheduledTask {if($active){Enable-ScheduledTask -TaskName $d.TaskName -TaskPath $d.TaskPath | Out-Null}else{Disable-ScheduledTask -TaskName $d.TaskName -TaskPath $d.TaskPath | Out-Null}}
        Service {if($active){$accountPolicy=Get-WsmServiceAccountPolicy $d $Spec;if($accountPolicy.Mode -ceq 'ManagedServiceAccount'){[void](Test-WsmServiceAccountTargetPreflight $accountPolicy)};Set-WsmServiceSupplement $d.Name $d.Supplement -Phase Final | Out-Null;$mode='Manual';if($desired -eq 'Automatic'){$mode='Automatic'};Set-Service -Name $d.Name -StartupType $mode;if($desired -in @('Automatic','Running')){Start-Service -Name $d.Name}}else{Set-Service -Name $d.Name -StartupType Disabled;Stop-Service -Name $d.Name -ErrorAction Stop;Set-WsmServiceSupplement $d.Name $d.Supplement -Phase Staged | Out-Null}}
        SmbShare {if($active){if(-not (Test-WsmDesiredWorldDeny $d)){Unblock-SmbShareAccess -Name $d.Name -ScopeName '*' -AccountName (Get-WsmEveryoneName) -Force | Out-Null}}else{Block-SmbShareAccess -Name $d.Name -ScopeName '*' -AccountName (Get-WsmEveryoneName) -Force | Out-Null}}
        LocalUser {if($active){Enable-LocalUser -Name $d.Name}else{Disable-LocalUser -Name $d.Name}}
        FirewallRule {if($active){Enable-NetFirewallRule -Name $d.Name}else{Disable-NetFirewallRule -Name $d.Name}}
        {$_ -in @('IISSite','IISPool')} {$m=New-WsmIisManager;try{$o=$m.Sites[$d.Name];if($Spec.Adapter -eq 'IISPool'){$o=$m.ApplicationPools[$d.Name];$o.AutoStart=$active;$xml=Read-WsmXml $d.Xml;$mode='OnDemand';if($active -and $xml.DocumentElement.HasAttribute('startMode')){$mode=$xml.DocumentElement.GetAttribute('startMode')};$o.StartMode=[Enum]::Parse([Microsoft.Web.Administration.StartMode],$mode,$true)}else{$o.ServerAutoStart=$active};$m.CommitChanges();if($active){[void]$o.Start()}elseif([string]$o.State -ne 'Stopped'){[void]$o.Stop()}}finally{$m.Dispose()}}
    }
}
function Invoke-WsmCutover {
    [CmdletBinding(SupportsShouldProcess)]param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[string]$CutoverPlanPath,[string]$CutoverPlanHash,[string]$Acknowledgement,[hashtable]$Secrets=@{},[switch]$ResumeActivation,[string]$ResumeOwner,[string]$ResumeEvidence)
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $package.Manifest.Target.Fingerprint;$plan=Read-WsmTrustedJson $CutoverPlanPath $CutoverPlanHash;Assert-WsmEnvelope $plan 'CutoverPlan';if($plan.PairId -cne $package.Manifest.PairId -or $plan.ManifestHash -ine $ExpectedHash -or $plan.TargetFingerprint -cne $package.Manifest.Target.Fingerprint -or -not $package.Manifest.Final){throw 'Cutover plan binding mismatch.'}
    if($plan.PSObject.Properties['GroupCoordination'] -and $plan.GroupCoordination){$groupDependency=Read-WsmCutoverDependencies $package $ExpectedHash $plan.DependencyEvidencePath $plan.DependencyEvidenceHash $plan.GroupCoordination.IndexPath $plan.GroupCoordination.IndexHash;if($groupDependency.GroupCoordination.GroupPlanHash -ine $plan.GroupCoordination.GroupPlanHash){throw 'Reviewed group changed after cutover preview.'}}else{Assert-WsmDependencyReceipts $package.Plan @($plan.DependencyReceipts)}
    Assert-WsmObservationHours $plan.Network.ObservationHours
    $now=[DateTime]::UtcNow;if($now -lt [DateTime]::Parse($plan.Network.MaintenanceWindowUtc).ToUniversalTime() -or $now -ge [DateTime]::Parse($plan.Network.ValidUntilUtc).ToUniversalTime()){throw 'Outside approved cutover window.'};[void](Read-WsmFreezeRecord (Join-Path $package.Root 'freeze.json') $package.Manifest.FreezeHash $package.Plan)
    if($Acknowledgement -cne ('CUTOVER '+$package.Manifest.PairId)){throw 'Cutover requires the exact pair acknowledgement shown in the reviewed plan.'}
    $paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId;$existing=Get-WsmOperationState $paths $package
    if($existing.Cutover -and $existing.Cutover.PlanHash -ine $CutoverPlanHash){throw 'Cannot replace a running cutover plan.'}
    if($existing.Cutover -and $existing.Cutover.NewTransactionsPossible){if($existing.Cutover.Stage -eq 'Activated'){return $existing};if(-not $ResumeActivation -or [string]::IsNullOrWhiteSpace($ResumeOwner) -or [string]::IsNullOrWhiteSpace($ResumeEvidence)){throw 'Interrupted activation requires explicit ResumeActivation, responsible owner and reconciliation evidence.'}}
    $resuming=($existing.Cutover -and $existing.Cutover.NewTransactionsPossible);if(-not $resuming){$validation=Invoke-WsmValidation $ManifestPath $ExpectedHash $StateDirectory Staged;if(-not $validation.Passed){throw 'Final-generation staging has drifted or business evidence missing.'}}
    $paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId
    Invoke-WsmLocked $paths.Root {$state=Get-WsmOperationState $paths $package;if(-not $PSCmdlet.ShouldProcess($state.PairId,'Apply reviewed isolated pilot identity/network and activation')){return $plan};if($state.ManifestHash -ine $ExpectedHash){throw 'Wrong applied generation.'};if($state.Cutover -and $state.Cutover.Stage -ceq 'Activated'){return $state};if($state.Cutover -and $state.Cutover.NewTransactionsPossible -and -not $resuming){throw 'Activation state changed after preview; re-open the reviewed resume flow.'};$network=$plan.Network;$before=Get-WsmNetworkSnapshot
        if(-not $state.Cutover){$state.Cutover=[pscustomobject]@{CutoverId=$plan.CutoverId;PlanHash=$CutoverPlanHash;Stage='Prepared';Before=$before;NewTransactionsPossible=$false;ObservationHours=$network.ObservationHours};Add-WsmJournal $paths $state 'CutoverPrepared' '' $state.Cutover}elseif($state.Cutover.PlanHash -ine $CutoverPlanHash){throw 'Cannot replace a running cutover plan.'}
        if($resuming){Assert-WsmActivationNetwork $network;$review=[pscustomobject]@{Owner=$ResumeOwner;Evidence=$ResumeEvidence;Utc=(Get-WsmUtc);ManifestHash=$ExpectedHash;CutoverPlanHash=$CutoverPlanHash};$state.Cutover | Add-Member NoteProperty ResumeReview $review -Force;Add-WsmJournal $paths $state 'ActivationResumeReviewed' '' $review;Invoke-WsmActivationSequence $package $paths $state -Resume;$state.Cutover.Stage='Activated';$state.Stage='PostCutoverValidationRequired';Complete-WsmCutoverObservation $paths $state;return $state};if($env:COMPUTERNAME -ine $network.FinalName){$args=@{NewName=$network.FinalName;Force=$true;ErrorAction='Stop'};if($Secrets.ContainsKey('DomainRename')){$args.DomainCredential=$Secrets.DomainRename};Rename-Computer @args | Out-Null;$state.Stage='RebootRequired';$state.Cutover.Stage='RenameRebootRequired';Add-WsmJournal $paths $state 'RenameRequiresReboot' '' ([pscustomobject]@{FinalName=$network.FinalName});return $state}
        $interface=Get-NetAdapter -Name $network.InterfaceAlias -ErrorAction Stop;if(-not $interface){throw 'Reviewed network interface absent.'}
        if(-not @(Get-NetIPAddress -InterfaceAlias $network.InterfaceAlias -IPAddress $network.FinalIP -ErrorAction SilentlyContinue).Count){$args=@{InterfaceAlias=$network.InterfaceAlias;IPAddress=$network.FinalIP;PrefixLength=$network.PrefixLength;ErrorAction='Stop'};if($network.PSObject.Properties['DefaultGateway'] -and $network.DefaultGateway){$args.DefaultGateway=$network.DefaultGateway};New-NetIPAddress @args | Out-Null}
        Set-DnsClientServerAddress -InterfaceAlias $network.InterfaceAlias -ServerAddresses $network.DnsServers
        foreach($temp in $network.TemporaryIP){if($temp -and $temp -ine $network.FinalIP){Get-NetIPAddress -InterfaceAlias $network.InterfaceAlias -IPAddress $temp -ErrorAction SilentlyContinue | Remove-NetIPAddress -Confirm:$false}}
        $final=Get-NetIPAddress -InterfaceAlias $network.InterfaceAlias -IPAddress $network.FinalIP;if([string]$final.AddressState -eq 'Duplicate'){throw 'Duplicate address detected; activation blocked.'}
        Assert-WsmActivationNetwork $network;$state.Cutover.Stage='NetworkApplied';Add-WsmJournal $paths $state 'NetworkApplied' '' ([pscustomobject]@{Interface=$network.InterfaceAlias;IP=$network.FinalIP})
        # Record the point of no automatic source restart before starting any consumer.
        $state.Cutover.NewTransactionsPossible=$true;Add-WsmJournal $paths $state 'ActivationBoundary' '' ([pscustomobject]@{ReconcileRequiredForRollback=$true})
        Invoke-WsmActivationSequence $package $paths $state
        $state.Cutover.Stage='Activated';$state.Stage='PostCutoverValidationRequired';Complete-WsmCutoverObservation $paths $state;$state
    }
}
function Get-WsmNetworkSnapshot {
    [pscustomobject]@{Name=$env:COMPUTERNAME;Addresses=@(Get-NetIPAddress | Select-Object InterfaceAlias,IPAddress,PrefixLength);DNS=@(Get-DnsClientServerAddress | Select-Object InterfaceAlias,ServerAddresses);Routes=@(Get-NetRoute | Select-Object InterfaceAlias,DestinationPrefix,NextHop)}
}
function Get-WsmAcceptanceGates {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory)
    $p=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;$paths=Get-WsmOperationPaths $StateDirectory $p.Manifest.PairId;$s=Get-WsmOperationState $paths $p;$missing=New-Object 'System.Collections.Generic.List[string]'
    if($s.ManifestHash -ine $ExpectedHash -or -not $p.Manifest.Final){$missing.Add('Applied final generation')};if(-not $s.Cutover -or $s.Cutover.Stage -ne 'Activated'){$missing.Add('Reviewed cutover activation')}
    $v=Invoke-WsmValidation $ManifestPath $ExpectedHash $StateDirectory Final;if(-not $v.Passed){$missing.Add('Final per-item configuration and business validation')}
    foreach($check in @('DNS','Kerberos','ExternalConnectivity','Monitoring','SecurityAgent','License','UserAcceptance')){if(-not (Test-WsmEvidence $s '' $check $ExpectedHash)){$missing.Add($check)}};$accepted=$missing.Count -eq 0
    $retirement=New-Object 'System.Collections.Generic.List[string]';foreach($check in @('BackupRestore','LongCycleJobs','Observation','RetirementRetention')){if(-not (Test-WsmEvidence $s '' $check $ExpectedHash)){$retirement.Add($check)}}
    $observation=$null;try{$observation=Get-WsmObservationWindow $s}catch{$observation=[pscustomobject]@{Ready=$false;Reason=$_.Exception.Message}}
    [pscustomobject]@{Observation=$observation;PairId=$s.PairId;FinalAccepted=$accepted;RetirementReady=($accepted -and $retirement.Count -eq 0);MissingFinal=$missing.ToArray();MissingRetirement=$retirement.ToArray();Mode='IsolatedPilot';ProductionVerified=$false;RetirementAction='Report only; never deletes source or secrets'}
}
function Export-WsmStageResult {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[ValidateSet('Restore','PreCutoverValidation','Cutover','PostCutoverValidation','Retirement')][string]$Stage,[string]$Path)
    $p=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $p.Manifest.Target.Fingerprint;$paths=Get-WsmOperationPaths $StateDirectory $p.Manifest.PairId
    $gates=$null;if($Stage -in @('PostCutoverValidation','Retirement')){$gates=Get-WsmAcceptanceGates $ManifestPath $ExpectedHash $StateDirectory}
    Invoke-WsmLocked $paths.Root {$s=Get-WsmOperationState $paths $p;if($s.ManifestHash -ine $ExpectedHash){$attemptMatches=($Stage -ceq 'Restore' -and $s.Stage -cin @('Failed','Cancelled','Running') -and $s.PSObject.Properties['RestoreAttempt'] -and $s.RestoreAttempt.ManifestHash -ieq $ExpectedHash -and $s.RestoreAttempt.Generation -eq $p.Manifest.Generation);if(-not $attemptMatches){throw 'No current applied generation or matching durable restore attempt.'}};$status='Blocked';switch($Stage){Restore{$status=$s.Stage;if($status -notin @('Succeeded','Failed','Cancelled','RebootRequired','ManualEvidenceRequired')){$status='Blocked'}};PreCutoverValidation{$pathV=Join-Path $paths.Root 'validation-Staged.json';if([IO.File]::Exists($pathV)){$v=Read-WsmJson $pathV;if($v.ManifestHash -ieq $ExpectedHash -and $v.Passed){$status='Succeeded'}}};Cutover{if($s.Cutover -and $s.Cutover.Stage -eq 'Activated'){$status='Succeeded'}};PostCutoverValidation{if($gates.FinalAccepted){$status='Succeeded'}else{$status='ManualEvidenceRequired'}};Retirement{if($gates.RetirementReady){$status='Succeeded'}else{$status='ManualEvidenceRequired'}}};$s.ResultSequence++;$r=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='StageResult';BatchId=$p.Manifest.BatchId;PairId=$p.Manifest.PairId;SourceHostId=$p.Plan.Source.HostId;TargetHostId=$p.Plan.Target.HostId;TargetFingerprint=$p.Plan.Target.Fingerprint;InventoryRevision=$p.Manifest.InventoryRevision;DecisionRevision=$p.Manifest.DecisionRevision;ApprovalId=$p.Manifest.ApprovalId;PlanHash=$p.Manifest.PlanHash;ManifestHash=$ExpectedHash;PayloadGeneration=$p.Manifest.Generation;RunId=$s.RunId;Sequence=$s.ResultSequence;Stage=$Stage;Status=$status;ProducedUtc=(Get-WsmUtc);Mode='IsolatedPilot';ProductionVerified=$false;JournalHash=$s.JournalHash};Write-WsmJson $Path $r;Add-WsmJournal $paths $s 'StageResultExported' '' ([pscustomobject]@{Stage=$Stage;Sequence=$r.Sequence;Status=$status});[pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path).Hash;Result=$r}}
}
