function Get-WsmObservationClock { [DateTimeOffset]::UtcNow }
function Assert-WsmObservationHours($Value) {
    if($Value -isnot [int] -and $Value -isnot [long]){throw 'ObservationHours must be an integer.'}
    if($Value -lt 1 -or $Value -gt 8760){throw 'ObservationHours must be between 1 and 8760.'}
}
function Get-WsmObservationWindow($State) {
    if(-not $State.Cutover -or $State.Cutover.Stage -cne 'Activated' -or -not $State.Cutover.PSObject.Properties['ActivatedUtc'] -or -not $State.Cutover.PSObject.Properties['ObservationHours']){throw 'Observation requires a durable completed activation and reviewed duration.'}
    Assert-WsmObservationHours $State.Cutover.ObservationHours
    $activation=[DateTimeOffset]::MinValue
    if(-not [DateTimeOffset]::TryParse($State.Cutover.ActivatedUtc,[ref]$activation) -or $activation.Offset -ne [TimeSpan]::Zero){throw 'Invalid activation UTC timestamp.'}
    $now=Get-WsmObservationClock
    if($activation -gt $now){throw 'Clock precedes completed activation; observation is blocked.'}
    $earliest=$activation.AddHours($State.Cutover.ObservationHours)
    [pscustomobject]@{ActivatedUtc=$State.Cutover.ActivatedUtc;RequiredHours=$State.Cutover.ObservationHours;EarliestCompletionUtc=$earliest.ToString('o');ObservedUntilUtc=$now.ToString('o');ElapsedHours=($now-$activation).TotalHours;Ready=($now -ge $earliest);BusinessEvidenceRequired=$true}
}
function Complete-WsmCutoverObservation($Paths,$State) {
    Assert-WsmObservationHours $State.Cutover.ObservationHours
    $activation=Get-WsmUtc
    $State.Cutover | Add-Member NoteProperty ActivatedUtc $activation -Force
    Add-WsmJournal $Paths $State 'CutoverCompleted' '' ([pscustomobject]@{Status=$State.Stage;ActivatedUtc=$activation;ObservationHours=$State.Cutover.ObservationHours})
}
function Get-WsmExternalReadinessEvidencePhase([string]$Check) {
    switch -CaseSensitive ($Check) {
        SourceOwnershipRestored { return 'SourceResumeReady' }
        {$_ -in @('SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval')} { return 'CutoverReady' }
        ManualRestore { return 'StagedDependencyVerified' }
        BusinessStaged { return 'CutoverReady' }
        RollbackReconcile { return 'RollbackReady' }
        {$_ -in @('BackupRestore','LongCycleJobs','Observation','RetirementRetention','ExternalConsumerOldPathDrained','SpecialProductDisposition','DataRetentionHandoff','CredentialHandoff','CertificateHandoff','CMDBHandoff','DNSHandoff','LicenseHandoff','MonitoringHandoff','RollbackCutoffAndDeletionOwner')} { return 'RetirementReady' }
        default { return 'FinalAccepted' }
    }
}
function Get-WsmExternalReadinessFacts([string]$Check) {
    $map=@{
        ManualRestore=@('NativeReadbackPerformed','ExpectedStateMatched','OwnerAccepted')
        BusinessStaged=@('ConsumerExecuted','ExpectedResultMatched','OwnerAccepted')
        BusinessFinal=@('ConsumerExecuted','ExpectedResultMatched','OwnerAccepted')
        DNS=@('ForwardResolutionMatched','ReverseResolutionMatched','OwnerAccepted')
        Kerberos=@('TicketObtained','ServicePrincipalMatched','OwnerAccepted')
        ExternalConnectivity=@('EndpointReachable','ExpectedIdentityMatched','OwnerAccepted')
        Monitoring=@('SignalObserved','AlertRouteConfirmed','OwnerAccepted')
        BackupRestore=@('BackupRestored','IntegrityVerified','OwnerAccepted')
        LongCycleJobs=@('LongCycleRunCompleted','ResultVerified','OwnerAccepted')
        SecurityAgent=@('AgentHealthy','PolicyConfirmed','OwnerAccepted')
        License=@('EntitlementVerified','UsageWithinTerms','OwnerAccepted')
        UserAcceptance=@('UserWorkflowPassed','OwnerAccepted')
        Observation=@('WindowCompleted','AlertReviewPassed','OwnerAccepted')
        RetirementRetention=@('RetentionTermRecorded','OwnerAccepted')
        RollbackReconcile=@('WritersStopped','LatestTargetPreserved','DataReconciled','ProductSynchronizationComplete','OwnerAccepted')
        SourceIdentityReleased=@('HostnameReleased','IpReleased','DomainIdentityReleased','OwnerAccepted')
        SourceWritersFenced=@('SourceWritersStopped','ExternalWritersFenced','OwnerAccepted')
        TargetIsolationConfirmed=@('TargetIsolated','TemporaryIdentityVerified','OwnerAccepted')
        ExternalNetworkFencing=@('DnsPtrFenced','SpnFenced','DhcpFenced','LoadBalancerFenced','OwnerAccepted')
        NetworkOwnerApproval=@('FinalNameApproved','FinalIpApproved','DnsApproved','RollbackProcedureApproved','OwnerAccepted')
        ExternalConsumerOldPathDrained=@('OldPathTrafficZero','ObservationWindowComplete','OwnerAccepted')
        SpecialProductDisposition=@('ProductOwnerDispositionComplete','VendorProcedureComplete','OwnerAccepted')
        DataRetentionHandoff=@('RetentionTermRecorded','DataOwnerAccepted','OwnerAccepted')
        CredentialHandoff=@('CredentialOwnersUpdated','OldCredentialsRevoked','OwnerAccepted')
        CertificateHandoff=@('CertificateOwnersUpdated','OldCertificatesRevoked','OwnerAccepted')
        CMDBHandoff=@('CIRelationshipsUpdated','OwnerAccepted')
        DNSHandoff=@('OldRecordsRetired','NewRecordsOwned','OwnerAccepted')
        LicenseHandoff=@('LicenseTransferred','OldEntitlementReleased','OwnerAccepted')
        MonitoringHandoff=@('MonitoringOwnerUpdated','AlertRouteTested','OwnerAccepted')
        RollbackCutoffAndDeletionOwner=@('RollbackDeadlineRecorded','IrrevocablePointRecorded','DeletionOwnerAuthorized','OwnerAccepted')
        SourceOwnershipRestored=@('TargetWritersStopped','LatestTargetPreserved','ReconciliationCompleted','SourceExclusiveWriteOwner','OwnerAccepted')
    }
    if(-not $map.ContainsKey($Check)){throw ('Unsupported external readiness check: '+$Check)}
    @($map[$Check])
}
function Assert-WsmLocalExternalEvidenceFile([string]$Path,[long]$MaximumBytes) {
    if([string]::IsNullOrWhiteSpace($Path) -or $Path -notmatch '^[A-Za-z]:\\'){throw 'External evidence files must be local drive paths; UNC and drive-relative paths are rejected.'}
    if($Path.Substring(2).Contains(':')){throw 'External evidence paths cannot address alternate data streams.'};$full=[IO.Path]::GetFullPath($Path);Assert-WsmNoReparse $full
    if(-not [IO.File]::Exists($full)){throw 'External evidence file is absent.'}
    $info=New-Object IO.FileInfo($full);if($info.Length -lt 1 -or $info.Length -gt $MaximumBytes){throw 'External evidence file exceeds its bounded size limit.'}
    $full
}function Assert-WsmExternalReadinessEvidence {
    param([Parameter(Mandatory)][string]$Path,[Parameter(Mandatory)][string]$SHA256,[Parameter(Mandatory)]$Package,[Parameter(Mandatory)][string]$Check,[string]$ItemId='')
    $evidencePath=Assert-WsmLocalExternalEvidenceFile $Path 1MB;$e=Read-WsmTrustedJson $evidencePath $SHA256
    Assert-WsmEnvelope $e 'ExternalReadinessEvidence'
    Assert-WsmFields $e @('SchemaVersion','ToolVersion','Kind','EvidenceId','PairId','SourceFingerprint','TargetFingerprint','ToolFingerprint','PlanHash','ManifestHash','Phase','Check','ItemId','Context','Owner','ObservedUtc','ExpiresUtc','PayloadArtifact','TypedResults','FreezeEpoch','SourceWriterInventory','WriterSetHash','SourceAttemptHash','SourceAttemptId') @('EvidenceId','PairId','SourceFingerprint','TargetFingerprint','ToolFingerprint','PlanHash','ManifestHash','Phase','Check','ItemId','Context','Owner','ObservedUtc','ExpiresUtc','PayloadArtifact','TypedResults')
    $expectedToolVersion='';if($Package.Manifest.PSObject.Properties['ToolVersion']){$expectedToolVersion=[string]$Package.Manifest.ToolVersion}elseif($Package.Plan.PSObject.Properties['ToolVersion']){$expectedToolVersion=[string]$Package.Plan.ToolVersion}
    if($e.SchemaVersion -ne 1 -or -not $expectedToolVersion -or $e.ToolVersion -cne $expectedToolVersion){throw 'External readiness evidence schema/tool version is unsupported or differs from its bound plan/package.'}
    Assert-WsmId $e.EvidenceId
    if($e.PairId -cne $Package.Manifest.PairId -or $e.SourceFingerprint -ine $Package.Manifest.Source.Fingerprint -or $e.TargetFingerprint -ine $Package.Manifest.Target.Fingerprint -or $e.ToolFingerprint -ine $Package.Plan.ToolFingerprint -or $e.PlanHash -ine $Package.Manifest.PlanHash -or $e.ManifestHash -ine $Package.SHA256){throw 'External readiness evidence is bound to a different pair, source, target, tool, plan or manifest.'}
    $phase=Get-WsmExternalReadinessEvidencePhase $Check
    $sourceFreeze=($Check -ceq 'SourceWritersFenced' -and $e.Phase -ceq 'SourceFreezeReady')
    if($sourceFreeze){$phase='SourceFreezeReady'}
    $sourceResume=($Check -ceq 'SourceOwnershipRestored' -and $e.Phase -ceq 'SourceResumeReady');if($sourceResume){$phase='SourceResumeReady'}
    if($e.Check -cne $Check -or $e.Phase -cne $phase -or $e.ItemId -cne $ItemId){throw 'External readiness evidence check, item or phase does not match the requested gate.'}
    if([string]::IsNullOrWhiteSpace([string]$e.Owner) -or $e.Owner.Length -gt 256 -or $e.Owner -match '[\x00-\x1f]|(?i)(password|passwd|secret|token|credential|private[ _-]?key)[\s:=]'){throw 'External evidence requires a bounded non-secret owner identifier.'}
    Assert-WsmFields $e.Context @('Scope','ItemId','ContextType','ConsumerId','Provider','Version','Architecture','RuntimeAccount','AccountType','AccountSid','ServiceName','Endpoint','OracleHome','ObservedEffectivePath','ConsumerItemIds','WindowId','CIRelationshipId','RetentionPolicyId') @('Scope','ItemId','ContextType','ConsumerId')
    if($e.Context.Scope -cnotin @('Item','Pair') -or $e.Context.ContextType -cnotin @('Consumer','Cutover','Rollback','Retirement','Acceptance','Preparation')){throw 'External evidence context scope/type is not supported.'}
    foreach($property in $e.Context.PSObject.Properties){if($property.Name -ceq 'ConsumerItemIds'){if(@($property.Value).Count -gt 100 -or @($property.Value | Where-Object {$_ -isnot [string] -or $_.Length -gt 256 -or $_ -match '(?i)(password|passwd|secret|token|credential|private[ _-]?key)[\s:=]'}).Count){throw 'External evidence consumer list exceeds its bound or includes a secret-like value.'}}else{$contextValue=$property.Value;if($contextValue -isnot [string] -or $contextValue.Length -gt 512 -or $contextValue -match '[\x00-\x1f]|(?i)(password|passwd|secret|token|credential|private[ _-]?key)[\s:=]'){$valueType='null';if($null -ne $contextValue){$valueType=$contextValue.GetType().FullName};throw ('External evidence context field is not a bounded non-secret string: '+$property.Name+' ('+$valueType+')')}}}
    if($ItemId){if($e.Context.Scope -cne 'Item' -or -not $e.Context.PSObject.Properties['ItemId'] -or $e.Context.ItemId -cne $ItemId){throw 'Item-level external evidence context is not bound to the selected consumer.'}}
    elseif($e.Context.Scope -cne 'Pair' -or ($e.Context.PSObject.Properties['ItemId'] -and $e.Context.ItemId)){throw 'Pair-level external evidence must use an exact pair context.'}
    $observed=ConvertTo-WsmQualificationUtc ([string]$e.ObservedUtc) ObservedUtc;$expires=ConvertTo-WsmQualificationUtc ([string]$e.ExpiresUtc) ExpiresUtc;$now=[DateTimeOffset]::UtcNow
    if($observed -gt $now.AddMinutes(5) -or $expires -le $now -or $expires -le $observed -or ($expires-$observed).TotalHours -gt 720){throw 'External readiness evidence is expired or has an invalid time interval.'}
    Assert-WsmFields $e.PayloadArtifact @('Path','SHA256') @('Path','SHA256')
    if([string]$e.PayloadArtifact.SHA256 -notmatch '^[a-fA-F0-9]{64}$'){throw 'External evidence requires an absolute, hash-bound payload artifact.'}
    $artifact=Assert-WsmLocalExternalEvidenceFile ([string]$e.PayloadArtifact.Path) 128MB
    if((Get-FileHash -LiteralPath $artifact -Algorithm SHA256).Hash -ine [string]$e.PayloadArtifact.SHA256){throw 'External evidence payload artifact is absent or changed.'}
    $facts=Get-WsmExternalReadinessFacts $Check;if($sourceFreeze){$facts=@('WriterSetEnumerated','WriterOwnershipReviewed','AllWritersStopped','OwnerAccepted')};$result=$e.TypedResults
    Assert-WsmFields $result @('Outcome','TestId','Method','Expected','Observed','Facts','NotApplicableReasons') @('Outcome','TestId','Method','Expected','Observed','Facts')
    foreach($field in @('TestId','Method','Expected','Observed')){$value=[string]$result.$field;if([string]::IsNullOrWhiteSpace($value) -or $value.Length -gt 1024 -or $value -match '[\x00-\x08\x0b\x0c\x0e-\x1f]|(?i)(password|passwd|secret|token|credential|private[ _-]?key)[\s:=]'){throw ('External typed result is missing or has an invalid/secret-like '+$field+'.')}}
    if([string]$result.TestId -notmatch '^[A-Za-z0-9_.:-]{1,128}$' -or [string]$result.Method -cnotin @('NativeReadback','BusinessTransaction','OwnerObservation','DirectoryReadback','NetworkReadback','BackupRestore','MonitoringReview','RetirementReview','Reconciliation','HumanProcedure','FixtureMock')){throw 'External typed result TestId or Method is not a supported finite value.'}
    if($result.Outcome -cnotin @('Pass','Fail')){throw 'External typed result Outcome must be Pass or Fail.'}
    $factNames=@($result.Facts.PSObject.Properties.Name);if(@($facts | Where-Object {$factNames -cnotcontains $_}).Count -or @($factNames | Where-Object {$facts -cnotcontains $_}).Count){throw 'External typed result facts do not exactly match this check.'}
    $notApplicable=@();$failed=$false
    $notApplicableAllowed=@('DomainIdentityReleased','DhcpFenced','LoadBalancerFenced','SpnFenced','DnsPtrFenced')
    foreach($fact in $facts){$value=$result.Facts.$fact;if($value -is [bool]){if(-not $value){$failed=$true}}elseif($value -ceq 'NotApplicable'){if($notApplicableAllowed -cnotcontains $fact){throw ('NotApplicable is prohibited for safety-critical fact: '+$fact)};$notApplicable+=@($fact)}else{throw ('External typed fact must be Boolean or NotApplicable: '+$fact)}}
    $reasons=@{};if($result.PSObject.Properties['NotApplicableReasons']){foreach($property in $result.NotApplicableReasons.PSObject.Properties){$reasons[$property.Name]=[string]$property.Value}}
    if(@($notApplicable | Where-Object {$reasons[$_] -notmatch '.{10,}' }).Count){throw 'Each NotApplicable fact requires a specific owner reason of at least 10 characters.'}
    if(@($reasons.Keys | Where-Object {$notApplicable -cnotcontains $_}).Count){throw 'NotApplicable reason names a fact that was not marked NotApplicable.'}
    if($result.Facts.OwnerAccepted -isnot [bool] -or -not $result.Facts.OwnerAccepted){throw 'External owner acceptance must be an explicit Boolean true.'}
    if($sourceFreeze){
        if(-not $e.PSObject.Properties['FreezeEpoch'] -or [string]$e.FreezeEpoch -notmatch '^[0-9a-fA-F-]{36}$' -or -not $e.PSObject.Properties['SourceWriterInventory'] -or -not $e.PSObject.Properties['WriterSetHash']){throw 'SourceFreezeReady evidence requires an epoch and a bounded writer inventory.'}
        $writers=@($e.SourceWriterInventory);if($writers.Count -lt 1 -or $writers.Count -gt 256){throw 'Source writer inventory must enumerate between one and 256 writers.'}
        $writerIds=@{};$canonical=New-Object 'System.Collections.Generic.List[object]'
        foreach($writer in $writers){Assert-WsmFields $writer @('WriterId','Owner','Scope','Kind','Stopped','OwnershipReviewed','EvidenceId') @('WriterId','Owner','Scope','Kind','Stopped','OwnershipReviewed','EvidenceId');foreach($field in @('WriterId','Owner','Scope','Kind','EvidenceId')){$value=[string]$writer.$field;if([string]::IsNullOrWhiteSpace($value) -or $value.Length -gt 256 -or $value -match '[\x00-\x1f]'){throw 'Source writer inventory contains an invalid bounded identifier.'}};if($writerIds.ContainsKey([string]$writer.WriterId) -or $writer.Stopped -isnot [bool] -or $writer.OwnershipReviewed -isnot [bool] -or -not $writer.Stopped -or -not $writer.OwnershipReviewed){throw 'Every enumerated source writer must be uniquely identified, stopped, and ownership-reviewed.'};$writerIds[[string]$writer.WriterId]=$true;$canonical.Add([pscustomobject][ordered]@{WriterId=[string]$writer.WriterId;Owner=[string]$writer.Owner;Scope=[string]$writer.Scope;Kind=[string]$writer.Kind;Stopped=[bool]$writer.Stopped;OwnershipReviewed=[bool]$writer.OwnershipReviewed;EvidenceId=[string]$writer.EvidenceId})}
        if([string]$e.WriterSetHash -notmatch '^[a-fA-F0-9]{64}$'){throw 'Source writer inventory requires a SHA256 projection hash.'};$writerJson=ConvertTo-Json -InputObject @($canonical.ToArray()) -Depth 8 -Compress;$actualWriterHash=[Security.Cryptography.SHA256]::Create();try{$writerBytes=[Text.Encoding]::UTF8.GetBytes($writerJson);$computedWriterHash=([BitConverter]::ToString($actualWriterHash.ComputeHash($writerBytes))).Replace('-','')}finally{$actualWriterHash.Dispose()};if($computedWriterHash -ine [string]$e.WriterSetHash){throw 'Source writer inventory projection hash mismatch.'}
        if($result.Facts.WriterSetEnumerated -isnot [bool] -or -not $result.Facts.WriterSetEnumerated -or $result.Facts.WriterOwnershipReviewed -isnot [bool] -or -not $result.Facts.WriterOwnershipReviewed -or $result.Facts.AllWritersStopped -isnot [bool] -or -not $result.Facts.AllWritersStopped){throw 'SourceFreezeReady typed results do not prove complete writer enumeration, ownership review, and stop state.'}
    }
    $computed='Pass';if($failed){$computed='Fail'};if($result.Outcome -cne $computed){throw 'External typed result Outcome is inconsistent with its facts.'}
    [pscustomobject]@{Evidence=$e;Path=[IO.Path]::GetFullPath($Path);SHA256=$SHA256.ToLowerInvariant();Passed=($computed -eq 'Pass');Phase=$phase;Check=$Check;ItemId=$ItemId;Owner=[string]$e.Owner;Context=$e.Context}
}
function Assert-WsmExternalReadinessReferences {
    param([object[]]$References,[Parameter(Mandatory)]$Package,[Parameter(Mandatory)][string[]]$RequiredChecks)
    if(@($References).Count -gt 100){throw 'External readiness reference count exceeds its bound.'}
    $validated=New-Object 'System.Collections.Generic.List[object]';$byCheck=@{}
    foreach($reference in @($References)){
        Assert-WsmFields $reference @('Path','SHA256','Check','ItemId','Phase','EvidenceId','Owner','Passed') @('Path','SHA256','Check')
        $itemId='';if($reference.PSObject.Properties['ItemId']){$itemId=[string]$reference.ItemId}
        $evidence=Assert-WsmExternalReadinessEvidence -Path ([string]$reference.Path) -SHA256 ([string]$reference.SHA256) -Package $Package -Check ([string]$reference.Check) -ItemId $itemId
        foreach($field in @('Phase','EvidenceId','Owner','Passed')){if($reference.PSObject.Properties[$field] -and [string]$reference.$field -cne [string]$(switch($field){Phase{$evidence.Phase};EvidenceId{$evidence.Evidence.EvidenceId};Owner{$evidence.Owner};Passed{$evidence.Passed}})){throw ('External readiness reference '+$field+' projection changed: '+$reference.Check)}}
        if($byCheck.ContainsKey($evidence.Check)){throw ('Duplicate external readiness evidence check: '+$evidence.Check)};$byCheck[$evidence.Check]=$true
        $validated.Add([pscustomobject][ordered]@{Path=$evidence.Path;SHA256=$evidence.SHA256;Check=$evidence.Check;ItemId=$itemId;Phase=$evidence.Phase;EvidenceId=$evidence.Evidence.EvidenceId;Owner=$evidence.Owner;Passed=$evidence.Passed})
    }
    $missing=@($RequiredChecks | Where-Object {-not $byCheck.ContainsKey($_)});if($missing.Count){throw ('Required external readiness evidence is missing: '+($missing -join ', '))}
    foreach($check in $RequiredChecks){$row=@($validated | Where-Object Check -ceq $check)[0];if(-not $row.Passed){throw ('External readiness evidence did not pass: '+$check)}}
    $validated.ToArray()
}
function Assert-WsmSourceFreezeEvidence([string]$Path,[string]$SHA256,$Plan,[string]$PlanHash,[string]$FreezeEpoch) {
    $surrogate=[pscustomobject]@{Manifest=[pscustomobject]@{PairId=$Plan.PairId;ToolVersion=[string]$Plan.ToolVersion;Source=[pscustomobject]@{Fingerprint=$Plan.Source.Fingerprint};Target=[pscustomobject]@{Fingerprint=$Plan.Target.Fingerprint};PlanHash=$PlanHash};Plan=[pscustomobject]@{ToolFingerprint=$Plan.ToolFingerprint;ToolVersion=[string]$Plan.ToolVersion};SHA256=''}
    $proof=Assert-WsmExternalReadinessEvidence -Path $Path -SHA256 $SHA256 -Package $surrogate -Check SourceWritersFenced -ItemId ''
    if($proof.Phase -cne 'SourceFreezeReady' -or $proof.Evidence.ManifestHash -cne '' -or $proof.Evidence.FreezeEpoch -cne $FreezeEpoch){throw 'SourceFreezeReady evidence must bind the exact plan, tool, pair, source, target and freeze epoch with no future manifest hash.'}
    [pscustomobject]@{EvidenceId=$proof.Evidence.EvidenceId;SHA256=$proof.SHA256;Owner=$proof.Owner;WriterSetHash=[string]$proof.Evidence.WriterSetHash;FreezeEpoch=$FreezeEpoch;PairId=$Plan.PairId;SourceFingerprint=$Plan.Source.Fingerprint;TargetFingerprint=$Plan.Target.Fingerprint;ToolFingerprint=$Plan.ToolFingerprint;PlanHash=$PlanHash;Phase='SourceFreezeReady';Check='SourceWritersFenced';ObservedUtc=$proof.Evidence.ObservedUtc;ExpiresUtc=$proof.Evidence.ExpiresUtc;Passed=$proof.Passed}
}
function Assert-WsmSourceFreezeEvidenceMatchesAttestation($Evidence,$Freeze) {
    foreach($field in @('EvidenceId','SHA256','Owner','WriterSetHash','FreezeEpoch','PairId','SourceFingerprint','TargetFingerprint','ToolFingerprint','PlanHash','Phase','Check','ObservedUtc','ExpiresUtc','Passed')){if([string]$Evidence.$field -cne [string]$Freeze.SourceFreezeEvidence.$field){throw ('SourceFreezeReady proof changed from the transferred freeze attestation: '+$field)}}
}
function Assert-WsmSourceResumeEvidence([string]$Path,[string]$SHA256,$Plan,[string]$PlanHash,$Attempt,[string]$AttemptHash,[string]$Owner) {
    $surrogate=[pscustomobject]@{Manifest=[pscustomobject]@{PairId=$Plan.PairId;ToolVersion=[string]$Plan.ToolVersion;Source=[pscustomobject]@{Fingerprint=$Plan.Source.Fingerprint};Target=[pscustomobject]@{Fingerprint=$Plan.Target.Fingerprint};PlanHash=$PlanHash};Plan=[pscustomobject]@{ToolFingerprint=$Plan.ToolFingerprint;ToolVersion=[string]$Plan.ToolVersion};SHA256=''}
    $proof=Assert-WsmExternalReadinessEvidence -Path $Path -SHA256 $SHA256 -Package $surrogate -Check SourceOwnershipRestored -ItemId ''
    if($proof.Phase -cne 'SourceResumeReady' -or $proof.Evidence.ManifestHash -cne '' -or $proof.Evidence.SourceAttemptHash -ine $AttemptHash -or $proof.Evidence.SourceAttemptId -cne $Attempt.State.AttemptId -or $proof.Owner -cne $Owner){throw 'SourceResumeReady evidence is not bound to this exact source attempt and responsible owner.'}
    [pscustomobject]@{EvidenceId=$proof.Evidence.EvidenceId;SHA256=$proof.SHA256;Owner=$proof.Owner;PairId=$Plan.PairId;SourceFingerprint=$Plan.Source.Fingerprint;TargetFingerprint=$Plan.Target.Fingerprint;ToolFingerprint=$Plan.ToolFingerprint;PlanHash=$PlanHash;SourceAttemptHash=$AttemptHash;SourceAttemptId=[string]$Attempt.State.AttemptId;Phase='SourceResumeReady';Check='SourceOwnershipRestored';ObservedUtc=$proof.Evidence.ObservedUtc;ExpiresUtc=$proof.Evidence.ExpiresUtc;Passed=$proof.Passed}
}
function Assert-WsmFreezeAttestation($Freeze,$Plan,[string]$ExpectedPlanHash,[switch]$AllowExpired) {
    if(-not $Freeze.PSObject.Properties['SourceFreezeEvidence']){throw 'Freeze is missing typed SourceFreezeReady fencing evidence.'};$a=$Freeze.SourceFreezeEvidence
    Assert-WsmFields $a @('EvidenceId','SHA256','Owner','WriterSetHash','FreezeEpoch','PairId','SourceFingerprint','TargetFingerprint','ToolFingerprint','PlanHash','Phase','Check','ObservedUtc','ExpiresUtc','Passed') @('EvidenceId','SHA256','Owner','WriterSetHash','FreezeEpoch','PairId','SourceFingerprint','TargetFingerprint','ToolFingerprint','PlanHash','Phase','Check','ObservedUtc','ExpiresUtc','Passed')
    if($a.PairId -cne $Plan.PairId -or $a.SourceFingerprint -ine $Plan.Source.Fingerprint -or $a.TargetFingerprint -ine $Plan.Target.Fingerprint -or $a.ToolFingerprint -ine $Plan.ToolFingerprint -or $a.ToolFingerprint -notmatch '^[a-fA-F0-9]{64}$' -or $a.PlanHash -ine $ExpectedPlanHash -or $Freeze.PlanHash -ine $ExpectedPlanHash -or $a.FreezeEpoch -cne $Freeze.FreezeEpoch -or $a.Owner -cne $Freeze.Owner -or [string]::IsNullOrWhiteSpace([string]$a.Owner) -or $a.Phase -cne 'SourceFreezeReady' -or $a.Check -cne 'SourceWritersFenced' -or $a.Passed -isnot [bool] -or -not $a.Passed -or $a.SHA256 -notmatch '^[a-fA-F0-9]{64}$' -or $a.WriterSetHash -notmatch '^[a-fA-F0-9]{64}$'){throw 'Freeze SourceFreezeReady attestation binding is invalid.'}
    $observed=ConvertTo-WsmQualificationUtc ([string]$a.ObservedUtc) SourceFreezeObservedUtc;$expires=ConvertTo-WsmQualificationUtc ([string]$a.ExpiresUtc) SourceFreezeExpiresUtc;$now=[DateTimeOffset]::UtcNow
    if($observed -gt $now.AddMinutes(5) -or (-not $AllowExpired -and $expires -le $now) -or $expires -le $observed -or ($expires-$observed).TotalHours -gt 720){throw 'SourceFreezeReady attestation expired or has invalid UTC bounds.'}
    $a
}
function Invoke-WsmFreezeCore {
    [CmdletBinding(SupportsShouldProcess)]param([string]$PlanPath,[string]$ExpectedHash,[string]$Path,[string]$Owner,[string]$Evidence,[Parameter(Mandatory)][string]$Acknowledgement,[switch]$SourceIdentityReleased,[string]$ReleaseEvidence,[ValidateRange(1,48)][int]$ValidHours=4,[Parameter(Mandatory)][string]$SourceStateDirectory,[string]$PreviousFreezePath,[string]$PreviousFreezeHash,[string]$SourceAttemptPath,[string]$OriginalBaselinePath,[string]$OriginalBaselineHash,[string]$FreezeExternalEvidencePath,[string]$FreezeExternalEvidenceHash,[string]$FreezeEpoch)
    $p=Read-WsmMigrationPlan $PlanPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $p.Source.Fingerprint
    if($Acknowledgement -cne 'OWNER-CONFIRMED-QUIESCENCE' -or -not $Owner -or -not $Evidence){throw 'Source freeze requires owner-confirmed quiescence and independent evidence.'}
    if(-not $FreezeExternalEvidencePath -or -not $FreezeExternalEvidenceHash){throw 'A SourceFreezeReady typed external writer fence is required before the final package can be frozen.'};if(-not $FreezeEpoch){$FreezeEpoch=[Guid]::NewGuid().ToString()};$sourceFreezeEvidence=Assert-WsmSourceFreezeEvidence $FreezeExternalEvidencePath $FreezeExternalEvidenceHash $p $ExpectedHash $FreezeEpoch;if($sourceFreezeEvidence.Owner -cne $Owner){throw 'SourceFreezeReady owner differs from freeze owner.'}
    if($SourceIdentityReleased -and -not $ReleaseEvidence){throw 'Source hostname/IP/domain release requires independent release evidence.'}
    $previousFreeze=$null;if($PreviousFreezePath){$previousFreeze=Read-WsmFreezeRecord $PreviousFreezePath $PreviousFreezeHash $p $ExpectedHash -AllowExpired}
    $beforeResult=Export-WsmInventory $SourceStateDirectory -DeepDiscovery:($p.Source.PSObject.Properties['DiscoveryDepth'] -and $p.Source.DiscoveryDepth -eq 'Deep');$before=Read-WsmTrustedJson $beforeResult.Path $beforeResult.SHA256;$original=@{};foreach($i in $before.Items){$original[$i.ItemId]=$i};if($before.Source.HostId -cne $p.Source.HostId){throw 'Source inventory identity mismatch.'};foreach($i in $p.Items){if($i.Decision -eq 'Include' -and $i.Kind -ne 'ManualItem'){$baseline=$i.SettingsHash;if($previousFreeze){$old=@($previousFreeze.QuiescedSettingsHashes | Where-Object ItemId -CEQ $i.ItemId);if($old.Count -ne 1 -or $old[0].OriginalHash -cne $i.SettingsHash){throw 'Previous freeze baseline does not match approved item.'};$baseline=$old[0].QuiescedHash};if(-not $original.ContainsKey($i.ItemId) -or $original[$i.ItemId].SettingsHash -cne $baseline){throw 'Source configuration drift before freeze; review required.'}}}
    if(-not $PSCmdlet.ShouldProcess($p.Source.Name,'Disable selected source producers and record owner-confirmed freeze')){return}
    $shareOriginalIndex=@{};if($OriginalBaselinePath){$savedBaseline=Read-WsmTrustedJson $OriginalBaselinePath $OriginalBaselineHash;Assert-WsmInventory $savedBaseline;if($savedBaseline.Source.HostId -cne $p.Source.HostId){throw 'Original share baseline inventory belongs to another source.'};foreach($entry in $savedBaseline.Items){$shareOriginalIndex[$entry.ItemId]=$entry}};$activities=New-Object 'System.Collections.Generic.List[object]'
    $freezeOrder=@(Get-WsmRestoreOrder @($p.Items | Where-Object Decision -EQ Include));[array]::Reverse($freezeOrder)
    foreach($i in $freezeOrder){$allowed=@{ScheduledTask='ScheduledTask';Service='Service';IISPool='IISPool';IISSite='IISSite'};if($allowed.ContainsKey($i.Kind) -and $i.MigrationSpec.Adapter -cne $allowed[$i.Kind]){$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind=$i.Kind;State='OwnerConfirmedDedicatedQuiescence';Name=$i.NaturalKey});continue};switch($i.Kind){
        Share {if($i.MigrationSpec.Adapter -eq 'SmbShare'){if(-not $SourceAttemptPath){throw 'Share drain needs durable source freeze workflow baseline.'};$attempt=Read-WsmJson $SourceAttemptPath;$shareBaseline=@($attempt.ShareBaselines | Where-Object ItemId -CEQ $i.ItemId);if($shareBaseline.Count -ne 1){throw 'Share has no unique saved original ACL baseline.'};$drain=Invoke-WsmShareQuiescence -Plan $p -Item $i -BaselinePath $shareBaseline[0].Path -BaselineHash $shareBaseline[0].SHA256 -AttemptPath $SourceAttemptPath -AttemptHash (Get-FileHash -LiteralPath $SourceAttemptPath).Hash;$activities.Add($drain.Activity)}else{$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind='Share';State='OwnerConfirmedDedicatedQuiescence';Name=$i.NaturalKey})}}
        ScheduledTask {$full=$i.NaturalKey;$last=$full.LastIndexOf('\');$folder=$full.Substring(0,$last+1);$name=$full.Substring($last+1);Disable-ScheduledTask -TaskName $name -TaskPath $folder | Out-Null;$t=Get-ScheduledTask -TaskName $name -TaskPath $folder;if($t.Settings.Enabled -or [string]$t.State -eq 'Running'){throw 'Task is enabled/running; stop/reconcile its in-flight business operation before freezing.'};$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind='ScheduledTask';State='Disabled';Name=$full})}
        Service {$name=$i.NaturalKey;Set-Service -Name $name -StartupType Disabled;Stop-Service -Name $name -ErrorAction Stop;$s=Get-CimInstance Win32_Service | Where-Object Name -CEQ $name;if(-not $s -or $s.StartMode -ne 'Disabled' -or $s.State -ne 'Stopped'){throw 'Source service did not quiesce.'};$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind='Service';State='DisabledStopped';Name=$name})}
        {$_ -in @('IISSite','IISPool')} {$m=New-WsmIisManager;try{$o=$m.Sites[$i.NaturalKey];if($i.Kind -eq 'IISPool'){$o=$m.ApplicationPools[$i.NaturalKey];$o.AutoStart=$false}else{$o.ServerAutoStart=$false};if(-not $o){throw 'Source IIS object absent.'};$m.CommitChanges();if([string]$o.State -ne 'Stopped'){[void]$o.Stop()};if([string]$o.State -ne 'Stopped'){throw 'Source IIS object did not stop.'};$activities.Add([pscustomobject]@{ItemId=$i.ItemId;Kind=$i.Kind;State='Stopped';Name=$i.NaturalKey})}finally{$m.Dispose()}}
    }}
    $afterResult=Export-WsmInventory $SourceStateDirectory -DeepDiscovery:($p.Source.PSObject.Properties['DiscoveryDepth'] -and $p.Source.DiscoveryDepth -eq 'Deep');$after=Read-WsmTrustedJson $afterResult.Path $afterResult.SHA256;$quiesced=@{};foreach($i in $after.Items){$quiesced[$i.ItemId]=$i};$hashes=@(foreach($i in $p.Items){if($i.Decision -eq 'Include' -and $i.Kind -ne 'ManualItem'){if(-not $quiesced.ContainsKey($i.ItemId)){throw 'Source item disappeared while freezing.'};if($i.Kind -eq 'Share' -and $i.MigrationSpec.Adapter -eq 'SmbShare'){$attempt=Read-WsmJson $SourceAttemptPath;$shareRecord=@($attempt.ShareQuiescence | Where-Object ItemId -CEQ $i.ItemId);$shareBaseline=@($attempt.ShareBaselines | Where-Object ItemId -CEQ $i.ItemId);if($shareRecord.Count -ne 1 -or $shareBaseline.Count -ne 1 -or -not $shareOriginalIndex.ContainsKey($i.ItemId)){throw 'Share drain has no complete original inventory/intent proof.'};$saved=Read-WsmTrustedJson $shareBaseline[0].Path $shareBaseline[0].SHA256;[void](Assert-WsmShareQuiescenceInventoryDelta $saved $shareOriginalIndex[$i.ItemId] $quiesced[$i.ItemId] $shareRecord[0] $shareBaseline[0].SHA256)}else{Assert-WsmQuiescenceChange $original[$i.ItemId] $quiesced[$i.ItemId] $activities.ToArray()};[pscustomobject]@{ItemId=$i.ItemId;OriginalHash=$i.SettingsHash;QuiescedHash=$quiesced[$i.ItemId].SettingsHash}}})
    $freezeAttestation=[pscustomobject][ordered]@{EvidenceId=$sourceFreezeEvidence.EvidenceId;SHA256=$sourceFreezeEvidence.SHA256;Owner=$sourceFreezeEvidence.Owner;WriterSetHash=$sourceFreezeEvidence.WriterSetHash;FreezeEpoch=$sourceFreezeEvidence.FreezeEpoch;PairId=$sourceFreezeEvidence.PairId;SourceFingerprint=$sourceFreezeEvidence.SourceFingerprint;TargetFingerprint=$sourceFreezeEvidence.TargetFingerprint;ToolFingerprint=$sourceFreezeEvidence.ToolFingerprint;PlanHash=$sourceFreezeEvidence.PlanHash;Phase=$sourceFreezeEvidence.Phase;Check=$sourceFreezeEvidence.Check;ObservedUtc=$sourceFreezeEvidence.ObservedUtc;ExpiresUtc=$sourceFreezeEvidence.ExpiresUtc;Passed=$sourceFreezeEvidence.Passed}
    $r=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='SourceFreeze';FreezeId=[Guid]::NewGuid().ToString();BatchId=$p.BatchId;PairId=$p.PairId;ApprovalId=$p.ApprovalId;PlanHash=$ExpectedHash;SourceHostId=$p.Source.HostId;SourceFingerprint=$p.Source.Fingerprint;TargetFingerprint=$p.Target.Fingerprint;FreezeEpoch=$FreezeEpoch;SourceFreezeEvidence=$freezeAttestation;Owner=$Owner;Evidence=$Evidence;Acknowledgement=$Acknowledgement;SourceIdentityReleased=[bool]$SourceIdentityReleased;ReleaseEvidence=$ReleaseEvidence;Activities=$activities.ToArray();QuiescedSettingsHashes=$hashes;ProducedUtc=(Get-WsmUtc);ExpiresUtc=[DateTime]::UtcNow.AddHours($ValidHours).ToString('o');Scope='Selected producers plus typed externally owner-confirmed writers; no remote interlock'}
    Write-WsmJson $Path $r;[pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path).Hash;FreezeId=$r.FreezeId;ExpiresUtc=$r.ExpiresUtc}
}
function Assert-WsmQuiescenceChange($Before,$After,[object[]]$Activities) {
    if($Before.SettingsHash -ceq $After.SettingsHash){return};$expected=ConvertFrom-WsmJson ($Before.Settings | ConvertTo-Json -Depth 30);$actual=ConvertFrom-WsmJson ($After.Settings | ConvertTo-Json -Depth 30)
    $activity=@($Activities | Where-Object {$_.ItemId -ceq $Before.ItemId -and $_.State -ne 'OwnerConfirmedDedicatedQuiescence'})
    if($Before.Kind -eq 'Share' -and $activity.Count){$oldKeys=@(ConvertTo-WsmShareAclKeys $Before.Settings.Access);$newKeys=@(ConvertTo-WsmShareAclKeys $After.Settings.Access);if($oldKeys -cnotcontains 'S-1-1-0|Deny|Full'){$oldKeys+=@('S-1-1-0|Deny|Full')};if((($oldKeys | Sort-Object) -join ';') -cne (($newKeys | Sort-Object) -join ';')){throw 'Source share drift is not exactly the temporary Everyone deny.'};$expected.Access=$actual.Access}
    if($Before.Kind -eq 'Service' -and $activity.Count){$expected.StartMode='Disabled'}
    elseif($Before.Kind -eq 'ServiceRegistryDetails' -and @($Activities | Where-Object {$_.Kind -eq 'Service' -and $_.Name -ceq $Before.NaturalKey -and $_.State -eq 'DisabledStopped'}).Count){$expected.Start=4}
    elseif($Before.Kind -in @('ScheduledTask','IISPool','IISSite','IISGlobalConfig')){
        $xml=Read-WsmXml $expected.Xml
        if($Before.Kind -eq 'ScheduledTask' -and $activity.Count){$node=$xml.SelectSingleNode("//*[local-name()='Settings']/*[local-name()='Enabled']");if(-not $node){throw 'Task lacked explicit Enabled setting; use dedicated freeze procedure.'};$node.InnerText='false'}
        elseif($Before.Kind -eq 'IISPool' -and $activity.Count){$xml.DocumentElement.SetAttribute('autoStart','false')}
        elseif($Before.Kind -eq 'IISSite' -and $activity.Count){$xml.DocumentElement.SetAttribute('serverAutoStart','false')}
        elseif($Before.Kind -eq 'IISGlobalConfig'){foreach($a in $Activities){if($a.Kind -eq 'IISPool' -and $a.State -eq 'Stopped'){foreach($node in $xml.SelectNodes('/configuration/system.applicationHost/applicationPools/add')){if($node.GetAttribute('name') -ceq $a.Name){$node.SetAttribute('autoStart','false')}}};if($a.Kind -eq 'IISSite' -and $a.State -eq 'Stopped'){foreach($node in $xml.SelectNodes('/configuration/system.applicationHost/sites/site')){if($node.GetAttribute('name') -ceq $a.Name){$node.SetAttribute('serverAutoStart','false')}}}}}
        $expected.Xml=ConvertTo-WsmXmlComparable $xml.DocumentElement;$actual.Xml=ConvertTo-WsmXmlComparable (Read-WsmXml $actual.Xml).DocumentElement
    }
    if(($expected | ConvertTo-Json -Compress -Depth 30) -cne ($actual | ConvertTo-Json -Compress -Depth 30)){throw ('Non-quiescence configuration changed during freeze: '+$Before.ItemId+'; do not bless it as final delta.')}
}
function Read-WsmFreezeRecord([string]$Path,[string]$ExpectedHash,$Plan,[string]$ExpectedPlanHash,[switch]$AllowExpired) {
    $r=Read-WsmTrustedJson $Path $ExpectedHash;Assert-WsmEnvelope $r 'SourceFreeze';Assert-WsmId $r.FreezeId
    if($r.PairId -cne $Plan.PairId -or $r.ApprovalId -cne $Plan.ApprovalId -or $r.PlanHash -ine $ExpectedPlanHash -or $r.SourceHostId -cne $Plan.Source.HostId -or $r.SourceFingerprint -cne $Plan.Source.Fingerprint -or $r.Acknowledgement -cne 'OWNER-CONFIRMED-QUIESCENCE' -or -not $r.Owner -or -not $r.Evidence){throw 'Freeze identity/evidence mismatch.'}
    $now=[DateTimeOffset]::UtcNow;$produced=[DateTimeOffset]::MinValue;$expires=[DateTimeOffset]::MinValue
    if(-not [DateTimeOffset]::TryParse($r.ProducedUtc,[ref]$produced) -or -not [DateTimeOffset]::TryParse($r.ExpiresUtc,[ref]$expires) -or $produced.Offset -ne [TimeSpan]::Zero -or $expires.Offset -ne [TimeSpan]::Zero -or $produced -gt $now.AddMinutes(5) -or (-not $AllowExpired -and $expires -le $now) -or $expires -le $produced){throw 'Freeze expired or source clock invalid; refresh source evidence.'}
    if(-not $r.PSObject.Properties['TargetFingerprint'] -or $r.TargetFingerprint -ine $Plan.Target.Fingerprint -or -not $r.PSObject.Properties['FreezeEpoch'] -or [string]$r.FreezeEpoch -notmatch '^[0-9a-fA-F-]{36}$'){throw 'Freeze target or epoch binding is missing.'};[void](Assert-WsmFreezeAttestation $r $Plan $ExpectedPlanHash -AllowExpired:$AllowExpired)
    $r
}
function Set-WsmValidationEvidence {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[string]$ItemId,[ValidateSet('ManualRestore','BusinessStaged','BusinessFinal','DNS','Kerberos','ExternalConnectivity','Monitoring','BackupRestore','LongCycleJobs','SecurityAgent','License','UserAcceptance','Observation','RollbackReconcile','RetirementRetention','SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval','ExternalConsumerOldPathDrained','SpecialProductDisposition','DataRetentionHandoff','CredentialHandoff','CertificateHandoff','CMDBHandoff','DNSHandoff','LicenseHandoff','MonitoringHandoff','RollbackCutoffAndDeletionOwner')][string]$Check,[string]$Owner,[string]$Evidence,[bool]$Passed,[ValidateRange(1,720)][int]$ValidHours=24,[string]$ExternalEvidencePath,[string]$ExternalEvidenceHash)
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $package.Manifest.Target.Fingerprint;$paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId
    $itemScoped=@('ManualRestore','BusinessStaged','BusinessFinal');if($Check -in $itemScoped){if(-not $ItemId -or -not @($package.Plan.Items | Where-Object {$_.ItemId -ceq $ItemId -and $_.Decision -eq 'Include'}).Count){throw 'This evidence check requires an included consumer ItemId.'}}elseif($ItemId){throw 'This evidence check is pair-level and cannot name an ItemId.'}
    $externalChecks=@('ManualRestore','BusinessStaged','BusinessFinal','DNS','Kerberos','ExternalConnectivity','Monitoring','BackupRestore','LongCycleJobs','SecurityAgent','License','UserAcceptance','Observation','RollbackReconcile','RetirementRetention','SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval','ExternalConsumerOldPathDrained','SpecialProductDisposition','DataRetentionHandoff','CredentialHandoff','CertificateHandoff','CMDBHandoff','DNSHandoff','LicenseHandoff','MonitoringHandoff','RollbackCutoffAndDeletionOwner')
    $external=$null;$recordPassed=$false;$status='NotTested';$recordOwner=$Owner;$reference=$null
    if($ExternalEvidencePath -or $ExternalEvidenceHash){if(-not $ExternalEvidencePath -or -not $ExternalEvidenceHash){throw 'External evidence path and independently obtained SHA256 must be supplied together.'};$external=Assert-WsmExternalReadinessEvidence -Path $ExternalEvidencePath -SHA256 $ExternalEvidenceHash -Package $package -Check $Check -ItemId $ItemId;if($external.Owner -cne $Owner){throw 'Evidence owner differs from the typed external record.'};if($Passed -ne $external.Passed){throw 'Passed must match the check-specific typed result in the external evidence record.'};$recordPassed=$external.Passed;$status=$(if($recordPassed){'Verified'}else{'Failed'});$recordOwner=$external.Owner;$reference=[pscustomobject][ordered]@{Path=$external.Path;SHA256=$external.SHA256;EvidenceId=$external.Evidence.EvidenceId;Check=$Check;ItemId=$ItemId;Phase=$external.Phase;PairId=$package.Manifest.PairId;SourceFingerprint=$package.Manifest.Source.Fingerprint;TargetFingerprint=$package.Manifest.Target.Fingerprint;ToolFingerprint=$package.Plan.ToolFingerprint;PlanHash=$package.Manifest.PlanHash;ManifestHash=$ExpectedHash.ToLowerInvariant()}}
    elseif($Check -in $externalChecks){$recordPassed=$false;$status='NotTested'}
    else{$recordPassed=$Passed;$status=$(if($Passed){'OwnerRecorded'}else{'Failed'})}
    Invoke-WsmLocked $paths.Root {$state=Get-WsmOperationState $paths $package;if($state.ManifestHash -ine $ExpectedHash){throw 'Evidence must bind to applied generation.'};if($Check -eq 'BusinessFinal' -and (-not $state.Cutover -or $state.Cutover.Stage -ne 'Activated')){throw 'Final business evidence can only be recorded after activation.'};$observation=$null;if($Check -ceq 'Observation'){if($ItemId){throw 'Observation is a pair-level check.'};$observation=Get-WsmObservationWindow $state;if($recordPassed -and -not $observation.Ready){throw 'Reviewed observation period has not elapsed since completed activation.'}};$record=[pscustomobject]@{ItemId=$ItemId;Check=$Check;Owner=$recordOwner;Evidence=$Evidence;Passed=$recordPassed;EvidenceStatus=$status;ExternalEvidence=$reference;ManifestHash=$ExpectedHash;Generation=$package.Manifest.Generation;Phase=$state.Stage;Utc=(Get-WsmUtc);ExpiresUtc=$(if($external){$external.Evidence.ExpiresUtc}else{[DateTime]::UtcNow.AddHours($ValidHours).ToString('o')});ManualEvidence=$true};if($observation){$record | Add-Member NoteProperty Observation $observation};$state.Evidence=@($state.Evidence | Where-Object {-not ($_.ItemId -ceq $ItemId -and $_.Check -ceq $Check)})+@($record);Add-WsmJournal $paths $state 'ValidationEvidence' $ItemId $record;$record}
}
function Test-WsmEvidence($State,[string]$ItemId,[string]$Check,[string]$ManifestHash) {
    $matches=New-Object 'System.Collections.Generic.List[object]';foreach($candidate in @($State.Evidence)){if($candidate.ItemId -cne $ItemId -or $candidate.Check -cne $Check -or -not $candidate.Passed -or $candidate.ManifestHash -ine $ManifestHash){continue};try{$expiry=ConvertTo-WsmQualificationUtc ([string]$candidate.ExpiresUtc) EvidenceExpiresUtc;if($expiry -gt [DateTimeOffset]::UtcNow){$matches.Add($candidate)}}catch{}}
    if($matches.Count -ne 1){return $false};$record=$matches[0]
    if(-not $record.PSObject.Properties['ExternalEvidence'] -or -not $record.ExternalEvidence){return $false}
    try{$ref=$record.ExternalEvidence;if($ref.PairId -cne $State.PairId -or $ref.TargetFingerprint -cne $State.TargetFingerprint -or $ref.PlanHash -ine $State.PlanHash -or $ref.ManifestHash -ine $ManifestHash -or $ref.Check -cne $Check -or $ref.ItemId -cne $ItemId){return $false};$toolVersion='';if($State.PSObject.Properties['ToolVersion']){$toolVersion=[string]$State.ToolVersion};$surrogate=[pscustomobject]@{Manifest=[pscustomobject]@{PairId=$State.PairId;Source=[pscustomobject]@{Fingerprint=$ref.SourceFingerprint};Target=[pscustomobject]@{Fingerprint=$State.TargetFingerprint};PlanHash=$State.PlanHash;ToolVersion=$toolVersion};Plan=[pscustomobject]@{ToolFingerprint=$ref.ToolFingerprint;ToolVersion=$toolVersion};SHA256=$ManifestHash};$verified=Assert-WsmExternalReadinessEvidence -Path $ref.Path -SHA256 $ref.SHA256 -Package $surrogate -Check $Check -ItemId $ItemId;if($verified.Evidence.EvidenceId -cne $ref.EvidenceId -or -not $verified.Passed){return $false}}catch{return $false}
    if($Check -ceq 'Observation'){try{$window=Get-WsmObservationWindow $State;if(-not $window.Ready -or -not $record.PSObject.Properties['Observation']){return $false};$observation=$record.Observation;$observedUntil=ConvertTo-WsmQualificationUtc ([string]$observation.ObservedUntilUtc) ObservationObservedUntilUtc;$earliest=ConvertTo-WsmQualificationUtc ([string]$window.EarliestCompletionUtc) ObservationEarliestCompletionUtc;return ($observation.Ready -and $observation.ActivatedUtc -ceq $window.ActivatedUtc -and $observation.RequiredHours -eq $window.RequiredHours -and $observedUntil -le (Get-WsmObservationClock) -and $observedUntil -ge $earliest)}catch{return $false}};return $true
}function Invoke-WsmValidation {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[ValidateSet('Staged','Final')][string]$Phase='Staged',[hashtable]$SidMap=@{},[object[]]$GeneralHostEvidence=@())
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $package.Manifest.Target.Fingerprint;$paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId
    $SidMap=Resolve-WsmIdentityMap $package.Plan $SidMap
    Invoke-WsmLocked $paths.Root {$state=Get-WsmOperationState $paths $package;if($state.ManifestHash -ine $ExpectedHash){throw 'Validation requires current applied generation.'};$checks=New-Object 'System.Collections.Generic.List[object]';$generalPhase='';if($package.Plan.SchemaVersion -eq 2 -and $package.Plan.ScopeMode -ceq 'GeneralHost'){$generalPhase='StagedDependencyVerified';if($Phase -eq 'Final'){$generalPhase='FinalAccepted'};$gateIssues=@(Get-WsmGeneralHostIssues $package.Plan $generalPhase $package.Manifest.Target.Fingerprint '' $package.Manifest.PlanHash $GeneralHostEvidence);foreach($gateIssue in $gateIssues){$checks.Add([pscustomobject]@{Code='GeneralHostDependency';ItemId=[string]$gateIssue.ConsumerItemId;ConfigurationPassed=$false;BusinessPassed=$false;Passed=$false;AutomaticConfiguration=$false;BusinessEvidence='NotTested';Problems=@([string]$gateIssue.Issue);Utc=(Get-WsmUtc);ManifestHash=$ExpectedHash})}}elseif($package.Plan.SchemaVersion -eq 3 -and $package.Plan.PSObject.Properties['GeneralHost']){if($Phase -cnotin @('Staged','Final')){throw 'Unsupported schema 3 target preparation validation phase.'};$generalPhase='StagedDependencyVerified';if($Phase -ceq 'Final'){$generalPhase='FinalAccepted'};$gateIssues=@(Get-WsmAssistiveStateGeneralHostIssues $package $state $generalPhase $GeneralHostEvidence);foreach($gateIssue in $gateIssues){$checks.Add([pscustomobject]@{Code='GeneralHostDependency';ItemId=[string]$gateIssue.ConsumerItemId;ConfigurationPassed=$false;BusinessPassed=$false;Passed=$false;AutomaticConfiguration=$false;BusinessEvidence='NotTested';Problems=@([string]$gateIssue.Issue);Utc=(Get-WsmUtc);ManifestHash=$ExpectedHash})}}
        foreach($item in $package.Plan.Items){if($item.Decision -ne 'Include'){continue};$spec=$item.MigrationSpec;$configuration=$false;$problems=@();$automatic=$spec.Adapter -ne 'ManualWorkflow'
            try{$ownership=@($state.Items | Where-Object ItemId -CEQ $item.ItemId);if($ownership.Count -and $ownership[0].Status -eq 'RebootRequired'){Assert-WsmRebootCompleted $ownership[0]};if($spec.Adapter -eq 'FileScope'){$r=Test-WsmFileScope $item $package $spec.TargetPath $SidMap;$configuration=$r.Passed;$problems=$r.Problems}elseif($automatic){$r=Test-WsmAdapterConfiguration $spec $Phase;$configuration=$r.Passed;$problems=$r.Problems;if($spec.Adapter -eq 'WindowsFeature' -and $ownership.Count -and $ownership[0].CreatedByTool){[void](Test-WsmInstallerConsumers $spec.Desired $ownership[0].InstallerSafety $Phase)}}else{$configuration=Test-WsmEvidence $state $item.ItemId ManualRestore $ExpectedHash;if(-not $configuration){$problems=@('Dedicated restore procedure evidence missing')}}}catch{$problems=@($_.Exception.GetType().FullName)}
            $businessCheck='BusinessStaged';if($Phase -eq 'Final'){$businessCheck='BusinessFinal'};$business=Test-WsmEvidence $state $item.ItemId $businessCheck $ExpectedHash
            $checks.Add([pscustomobject]@{ItemId=$item.ItemId;ConfigurationPassed=$configuration;BusinessPassed=$business;Passed=($configuration -and $business);AutomaticConfiguration=$automatic;BusinessEvidence='Owner supplied; no arbitrary package commands run';Problems=$problems;Utc=(Get-WsmUtc);ManifestHash=$ExpectedHash})
        }
        $passed=($checks.Count -gt 0 -and @($checks | Where-Object Passed -EQ $false).Count -eq 0 -and -not @($checks | Where-Object { $_.PSObject.Properties['Code'] -and $_.Code -ceq 'GeneralHostDependency' }).Count);$result=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='ValidationResult';PairId=$state.PairId;ManifestHash=$ExpectedHash;Generation=$state.Generation;Phase=$Phase;ScopeMode=$(if($package.Plan.SchemaVersion -eq 2){$package.Plan.ScopeMode}else{'Legacy'});Passed=$passed;Checks=$checks.ToArray();Utc=(Get-WsmUtc);ProductionVerified=$false}
        Write-WsmJson (Join-Path $paths.Root ('validation-'+$Phase+'.json')) $result;Add-WsmJournal $paths $state 'ValidationCompleted' '' ([pscustomobject]@{Phase=$Phase;Passed=$passed;Checks=$checks.Count});$result
    }
}
function Assert-WsmAssistiveCutoverActivationIntent($Package,[string]$StateDirectory,$State=$null) {
    if($Package.Plan.SchemaVersion -ne 3){return}
    $paths=Get-WsmOperationPaths $StateDirectory $Package.Manifest.PairId;$state=$State;if(-not $state){$state=Get-WsmOperationState $paths $Package}
    if($state.ManifestHash -ine $Package.SHA256 -or [long]$state.Generation -ne [long]$Package.Manifest.Generation -or @($state.PendingOperations).Count){throw 'Assistive cutover requires a quiescent exact applied generation with no pending item operation.'}
    if(-not $state.PSObject.Properties['RestoreAttempt'] -or -not $state.RestoreAttempt -or -not $state.RestoreAttempt.PSObject.Properties['ManifestHash'] -or -not $state.RestoreAttempt.PSObject.Properties['Generation'] -or [string]$state.RestoreAttempt.ManifestHash -ine [string]$Package.SHA256 -or [long]$state.RestoreAttempt.Generation -ne [long]$Package.Manifest.Generation){throw 'Assistive cutover requires a current-generation durable restore attempt.'}
    $attempt=$state.RestoreAttempt
    foreach($field in @('DecisionReceiptPath','DecisionReceiptHash','TargetSnapshotPath','TargetSnapshotHash','SelectedItemIds')){if(-not $attempt.PSObject.Properties[$field] -or ($attempt.$field -is [string] -and [string]::IsNullOrWhiteSpace([string]$attempt.$field))){throw ('Assistive cutover requires the durable current decision receipt and target snapshot reference: '+$field)}}
    $decision=Get-WsmAssistiveRestoreDecision $Package $Package.SHA256 ([string]$attempt.DecisionReceiptPath) ([string]$attempt.DecisionReceiptHash) ([string]$attempt.TargetSnapshotPath)
    if(-not $decision){throw 'Assistive cutover decision receipt could not be revalidated.'}
    if($decision.Receipt.Decision -cne 'RestoreNow'){throw 'Assistive cutover decision receipt is deferred and cannot authorize final activation.'}
    if($decision.ReceiptHash -ine [string]$attempt.DecisionReceiptHash){throw 'Assistive cutover receipt file no longer matches its durable hash.'}
    if([string]$decision.Receipt.TargetSnapshotHash -ine [string]$attempt.TargetSnapshotHash){throw 'Assistive cutover target snapshot hash differs from the durable restore attempt.'}
    if(-not ([IO.Path]::GetFullPath([string]$attempt.DecisionReceiptPath)).Equals([string]$decision.ReceiptPath,[StringComparison]::OrdinalIgnoreCase)){throw 'Assistive cutover receipt path differs from the canonical path in the durable restore attempt.'}
    if(-not ([IO.Path]::GetFullPath([string]$attempt.TargetSnapshotPath)).Equals([string]$decision.SnapshotPath,[StringComparison]::OrdinalIgnoreCase)){throw 'Assistive cutover snapshot path differs from the canonical path in the durable restore attempt.'}
    $approved=@($Package.Plan.Assistive.ApprovedItemIds);$selected=@($decision.SelectedItemIds);$attemptSelected=@($attempt.SelectedItemIds)
    if($approved.Count -eq 0 -or $selected.Count -ne $approved.Count -or $attemptSelected.Count -ne $approved.Count -or @($selected | Select-Object -Unique).Count -ne $approved.Count -or @($attemptSelected | Select-Object -Unique).Count -ne $approved.Count){throw 'Assistive final activation requires a current target receipt selecting the entire sealed approved item set.'}
    $approvedSorted=@($approved | Sort-Object -CaseSensitive);$selectedSorted=@($selected | Sort-Object -CaseSensitive);$attemptSorted=@($attemptSelected | Sort-Object -CaseSensitive)
    if((ConvertTo-Json -InputObject $selectedSorted -Compress) -cne (ConvertTo-Json -InputObject $approvedSorted -Compress) -or (ConvertTo-Json -InputObject $attemptSorted -Compress) -cne (ConvertTo-Json -InputObject $approvedSorted -Compress)){throw 'Assistive final activation receipt selection differs from the entire sealed approved item set.'}
    foreach($item in @($Package.Plan.Items | Where-Object Decision -EQ Include)){
        $spec=$item.MigrationSpec
        if($spec.PSObject.Properties['SourceXml']){
            [void](Assert-WsmAssistiveReviewedActivation $spec)
            if(-not $spec.StagedDisabled -or [string]$spec.DesiredFinalState -cne [string]$spec.ReviewedActivation.FinalState){throw ('Assistive activation intent is not explicit and separately staged for item '+$item.ItemId)}
            $record=@($state.Items | Where-Object ItemId -CEQ $item.ItemId)
            if($record.Count -ne 1 -or -not $record[0].CreatedByTool -or $record[0].AppliedManifestHash -ine $Package.SHA256 -or [long]$record[0].AppliedGeneration -ne [long]$Package.Manifest.Generation -or $record[0].Status -notin @('Succeeded','Partial')){throw ('Assistive workload has not been staged and read back in this exact generation: '+$item.ItemId)}
            $staged=Test-WsmAdapterConfiguration $spec Staged
            if(-not $staged.Passed){throw ('Assistive staged-disabled state drifted before cutover: '+$item.ItemId)}
        }
    }
}
function New-WsmCutoverPlan {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[string]$NetworkPath,[string]$NetworkHash,[string]$Path,[string]$DependencyEvidencePath,[string]$DependencyEvidenceHash,[string]$GroupEvidenceIndexPath,[string]$GroupEvidenceIndexHash,[object[]]$GeneralHostEvidence=@(),[object[]]$ExternalEvidenceReferences=@())
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;if(-not $package.Manifest.Final){throw 'Cutover requires final frozen generation.'};Assert-WsmAssistiveCutoverActivationIntent $package $StateDirectory;$freeze=Read-WsmFreezeRecord (Join-Path $package.Root 'freeze.json') $package.Manifest.FreezeHash $package.Plan $package.Manifest.PlanHash;if(-not $freeze.SourceIdentityReleased -or -not $freeze.ReleaseEvidence){throw 'Source identity release evidence missing.'}
    $dependency=Read-WsmCutoverDependencies $package $ExpectedHash $DependencyEvidencePath $DependencyEvidenceHash $GroupEvidenceIndexPath $GroupEvidenceIndexHash;$receipts=$dependency.Receipts
    $externalReadiness=Assert-WsmExternalReadinessReferences -References $ExternalEvidenceReferences -Package $package -RequiredChecks @('SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval');$network=Read-WsmTrustedJson $NetworkPath $NetworkHash;Assert-WsmFields $network @('FinalName','InterfaceAlias','FinalIP','PrefixLength','DefaultGateway','DnsServers','TemporaryIP','DomainProcedureEvidence','RollbackProcedure','Owner','MaintenanceWindowUtc','ValidUntilUtc','ObservationHours') @('FinalName','InterfaceAlias','FinalIP','PrefixLength','DnsServers','TemporaryIP','DomainProcedureEvidence','RollbackProcedure','Owner','MaintenanceWindowUtc','ValidUntilUtc')
    if(-not $network.PSObject.Properties['ObservationHours']){$network | Add-Member NoteProperty ObservationHours 24};Assert-WsmObservationHours $network.ObservationHours
    if($network.FinalName -notmatch '^[A-Za-z0-9][A-Za-z0-9-]{0,14}$' -or -not $network.Owner -or -not $network.DomainProcedureEvidence -or -not $network.RollbackProcedure){throw 'Invalid final name or missing domain/rollback owner procedure.'};$ip=$null;if(-not [Net.IPAddress]::TryParse($network.FinalIP,[ref]$ip) -or $ip.AddressFamily -ne [Net.Sockets.AddressFamily]::InterNetwork -or $network.PrefixLength -lt 1 -or $network.PrefixLength -gt 32){throw 'Automatic cutover currently requires explicit IPv4 interface/prefix.'};foreach($address in @($network.DnsServers)+@($network.TemporaryIP)+@($network.DefaultGateway)){if($address -and -not [Net.IPAddress]::TryParse($address,[ref]$ip)){throw 'Invalid network address.'}}
    $validation=Invoke-WsmValidation $ManifestPath $ExpectedHash $StateDirectory Staged @{} $GeneralHostEvidence;if(-not $validation.Passed){throw 'Staged configuration, dependencies and business validation must pass.'}
    if($package.Plan.SchemaVersion -eq 2 -and $package.Plan.ScopeMode -ceq 'GeneralHost'){$cutoverIssues=@(Get-WsmGeneralHostIssues $package.Plan CutoverReady $package.Manifest.Target.Fingerprint '' $package.Manifest.PlanHash $GeneralHostEvidence);if($cutoverIssues.Count){throw ('CutoverReady dependencies remain open: '+(@($cutoverIssues | ForEach-Object Issue | Select-Object -Unique) -join '; '))}}elseif($package.Plan.SchemaVersion -eq 3 -and $package.Plan.PSObject.Properties['GeneralHost']){$paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId;$state=Get-WsmOperationState $paths $package;foreach($phase in @('FinalAccepted','CutoverReady')){$cutoverIssues=@(Get-WsmAssistiveStateGeneralHostIssues $package $state $phase $GeneralHostEvidence);if($cutoverIssues.Count){throw ($phase+' dependencies remain open: '+(@($cutoverIssues | ForEach-Object Issue | Select-Object -Unique) -join '; '))}}}
    $p=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='CutoverPlan';CutoverId=[Guid]::NewGuid().ToString();PairId=$package.Manifest.PairId;ManifestHash=$ExpectedHash;Generation=$package.Manifest.Generation;TargetFingerprint=$package.Manifest.Target.Fingerprint;FreezeHash=$package.Manifest.FreezeHash;DependencyReceipts=$receipts;DependencyEvidencePath=$DependencyEvidencePath;DependencyEvidenceHash=$DependencyEvidenceHash;GroupCoordination=$dependency.GroupCoordination;Network=$network;ExternalEvidenceReferences=$externalReadiness;ReviewedUtc=(Get-WsmUtc);Actions=@('Verify source release and final-generation validation','Rename target if required; reboot and revalidate staging before activation','Apply reviewed final IP/DNS and remove explicitly listed temporary IP','Activate explicitly reviewed objects','Record post-cutover business/security/backup evidence');ProductionVerified=$false}
    Write-WsmJson $Path $p;[pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path).Hash;Plan=$p}
}
function Invoke-WsmAdapterActivation($Spec,[bool]$Enable,$Ownership=$null) {
    if($Spec.Adapter -in @('FileScope','ManualWorkflow')){return}
    $d=$Spec.Desired;$desired='Disabled';if($Spec.PSObject.Properties['DesiredFinalState']){$desired=$Spec.DesiredFinalState};$active=$Enable -and $desired -in @('Enabled','Automatic','Manual','Running')
    switch($Spec.Adapter){
        WindowsFeature {if($Ownership -and $Ownership.CreatedByTool){Invoke-WsmInstallerConsumerActivation $d $Ownership.InstallerSafety $Enable}}
        ScheduledTask {if($active){Enable-ScheduledTask -TaskName $d.TaskName -TaskPath $d.TaskPath | Out-Null}else{Disable-ScheduledTask -TaskName $d.TaskName -TaskPath $d.TaskPath | Out-Null}}
        Service {if($active){$accountPolicy=Get-WsmServiceAccountPolicy $d $Spec;if($accountPolicy.Mode -ceq 'ManagedServiceAccount'){[void](Test-WsmServiceAccountTargetPreflight $accountPolicy)};Set-WsmServiceSupplement $d.Name $d.Supplement -Phase Final | Out-Null;$mode='Manual';if($desired -eq 'Automatic'){$mode='Automatic'};Set-Service -Name $d.Name -StartupType $mode;if($desired -in @('Automatic','Running')){Start-Service -Name $d.Name}}else{Set-Service -Name $d.Name -StartupType Disabled;Stop-Service -Name $d.Name -ErrorAction Stop;Set-WsmServiceSupplement $d.Name $d.Supplement -Phase Staged | Out-Null}}
        SmbShare {if($active){if(-not (Test-WsmDesiredWorldDeny $d)){Unblock-SmbShareAccess -Name $d.Name -ScopeName '*' -AccountName (Get-WsmEveryoneName) -Force | Out-Null}}else{Block-SmbShareAccess -Name $d.Name -ScopeName '*' -AccountName (Get-WsmEveryoneName) -Force | Out-Null}}
        LocalUser {if($active){Enable-LocalUser -Name $d.Name}else{Disable-LocalUser -Name $d.Name}}
        FirewallRule {if($active){Enable-NetFirewallRule -Name $d.Name}else{Disable-NetFirewallRule -Name $d.Name}}
        {$_ -in @('IISSite','IISPool')} {$m=New-WsmIisManager;try{$o=$m.Sites[$d.Name];if($Spec.Adapter -eq 'IISPool'){$o=$m.ApplicationPools[$d.Name];$o.AutoStart=$active;$xml=Read-WsmXml $d.Xml;$mode='OnDemand';if($active -and $xml.DocumentElement.HasAttribute('startMode')){$mode=$xml.DocumentElement.GetAttribute('startMode')};$o.StartMode=[Enum]::Parse([Microsoft.Web.Administration.StartMode],$mode,$true)}else{$o.ServerAutoStart=$active};$m.CommitChanges();if($active){[void]$o.Start()}elseif([string]$o.State -ne 'Stopped'){[void]$o.Stop()}}finally{$m.Dispose()}}
        {$_ -in @('IISSection','IISLocation')} {[void](Invoke-WsmIisConfigActivation $Spec $active)}
    }
}
function Invoke-WsmCutover {
    [CmdletBinding(SupportsShouldProcess)]param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[string]$CutoverPlanPath,[string]$CutoverPlanHash,[string]$Acknowledgement,[hashtable]$Secrets=@{},[switch]$ResumeActivation,[string]$ResumeOwner,[string]$ResumeEvidence,[object[]]$GeneralHostEvidence=@(),[object[]]$ExternalEvidenceReferences=@())
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $package.Manifest.Target.Fingerprint;Assert-WsmAssistiveCutoverActivationIntent $package $StateDirectory;$plan=Read-WsmTrustedJson $CutoverPlanPath $CutoverPlanHash;Assert-WsmEnvelope $plan 'CutoverPlan';if($plan.PairId -cne $package.Manifest.PairId -or $plan.ManifestHash -ine $ExpectedHash -or $plan.TargetFingerprint -cne $package.Manifest.Target.Fingerprint -or -not $package.Manifest.Final){throw 'Cutover plan binding mismatch.'};$frozenRefs=@($plan.ExternalEvidenceReferences);if(@($ExternalEvidenceReferences).Count){$callerRefs=@(Assert-WsmExternalReadinessReferences -References $ExternalEvidenceReferences -Package $package -RequiredChecks @('SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval'));if((ConvertTo-Json -InputObject $callerRefs -Depth 12 -Compress) -cne (ConvertTo-Json -InputObject $frozenRefs -Depth 12 -Compress)){throw 'Caller external readiness references differ from the reviewed cutover plan.'}};$validatedExternal=Assert-WsmExternalReadinessReferences -References $frozenRefs -Package $package -RequiredChecks @('SourceIdentityReleased','SourceWritersFenced','TargetIsolationConfirmed','ExternalNetworkFencing','NetworkOwnerApproval');if($package.Plan.SchemaVersion -eq 2 -and $package.Plan.ScopeMode -ceq 'GeneralHost'){$cutoverIssues=@(Get-WsmGeneralHostIssues $package.Plan CutoverReady $package.Manifest.Target.Fingerprint '' $package.Manifest.PlanHash $GeneralHostEvidence);if($cutoverIssues.Count){throw ('CutoverReady dependencies remain open: '+(@($cutoverIssues | ForEach-Object Issue | Select-Object -Unique) -join '; '))}}elseif($package.Plan.SchemaVersion -eq 3 -and $package.Plan.PSObject.Properties['GeneralHost']){$paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId;$state=Get-WsmOperationState $paths $package;foreach($phase in @('FinalAccepted','CutoverReady')){$cutoverIssues=@(Get-WsmAssistiveStateGeneralHostIssues $package $state $phase $GeneralHostEvidence);if($cutoverIssues.Count){throw ($phase+' dependencies remain open: '+(@($cutoverIssues | ForEach-Object Issue | Select-Object -Unique) -join '; '))}}}
    if($plan.PSObject.Properties['GroupCoordination'] -and $plan.GroupCoordination){$groupDependency=Read-WsmCutoverDependencies $package $ExpectedHash $plan.DependencyEvidencePath $plan.DependencyEvidenceHash $plan.GroupCoordination.IndexPath $plan.GroupCoordination.IndexHash;if($groupDependency.GroupCoordination.GroupPlanHash -ine $plan.GroupCoordination.GroupPlanHash){throw 'Reviewed group changed after cutover preview.'}}else{Assert-WsmDependencyReceipts $package.Plan @($plan.DependencyReceipts)}
    Assert-WsmObservationHours $plan.Network.ObservationHours
    $now=[DateTime]::UtcNow;if($now -lt [DateTime]::Parse($plan.Network.MaintenanceWindowUtc).ToUniversalTime() -or $now -ge [DateTime]::Parse($plan.Network.ValidUntilUtc).ToUniversalTime()){throw 'Outside approved cutover window.'};[void](Read-WsmFreezeRecord (Join-Path $package.Root 'freeze.json') $package.Manifest.FreezeHash $package.Plan $package.Manifest.PlanHash)
    if($Acknowledgement -cne ('CUTOVER '+$package.Manifest.PairId)){throw 'Cutover requires the exact pair acknowledgement shown in the reviewed plan.'}
    if(-not $PSCmdlet.ShouldProcess($package.Manifest.PairId,'Apply reviewed isolated pilot identity/network and activation')){return [pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='CutoverExecutionPreview';PairId=$package.Manifest.PairId;ManifestHash=$ExpectedHash;CutoverPlanHash=$CutoverPlanHash;Status='NotStarted';Executed=$false;PreflightValidated=$true;TargetStateRead=$false;TargetStateGatesEvaluated=$false;StagedValidationPassed=$null;NextStep='Review current target state and rerun without -WhatIf to evaluate staged gates and activate.';ProductionVerified=$false}}
    $paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId;$existing=Get-WsmOperationState $paths $package
    if($existing.Cutover -and $existing.Cutover.PlanHash -ine $CutoverPlanHash){throw 'Cannot replace a running cutover plan.'}
    if($existing.Cutover -and $existing.Cutover.NewTransactionsPossible){if($existing.Cutover.Stage -eq 'Activated'){return $existing};if(-not $ResumeActivation -or [string]::IsNullOrWhiteSpace($ResumeOwner) -or [string]::IsNullOrWhiteSpace($ResumeEvidence)){throw 'Interrupted activation requires explicit ResumeActivation, responsible owner and reconciliation evidence.'}}
    $resuming=($existing.Cutover -and $existing.Cutover.NewTransactionsPossible);if(-not $resuming){$validation=Invoke-WsmValidation $ManifestPath $ExpectedHash $StateDirectory Staged @{} $GeneralHostEvidence;if(-not $validation.Passed){throw 'Final-generation staging has drifted, dependencies are open, or business evidence is missing.'}}
    $paths=Get-WsmOperationPaths $StateDirectory $package.Manifest.PairId
    Invoke-WsmLocked $paths.Root {$state=Get-WsmOperationState $paths $package;if($state.ManifestHash -ine $ExpectedHash){throw 'Wrong applied generation.'};if($state.Cutover -and $state.Cutover.Stage -ceq 'Activated'){return $state};if($package.Plan.SchemaVersion -eq 3){Assert-WsmAssistiveCutoverActivationIntent $package $StateDirectory $state;if($package.Plan.PSObject.Properties['GeneralHost']){foreach($phase in @('FinalAccepted','CutoverReady')){$freshIssues=@(Get-WsmAssistiveStateGeneralHostIssues $package $state $phase $GeneralHostEvidence);if($freshIssues.Count){throw ($phase+' dependencies changed before activation: '+(@($freshIssues | ForEach-Object Issue | Select-Object -Unique) -join '; '))}}}};if($state.Cutover -and $state.Cutover.NewTransactionsPossible -and -not $resuming){throw 'Activation state changed after preview; re-open the reviewed resume flow.'};$network=$plan.Network;$before=Get-WsmNetworkSnapshot
        if(-not $state.Cutover){$state.Cutover=[pscustomobject]@{CutoverId=$plan.CutoverId;PlanHash=$CutoverPlanHash;Stage='Prepared';Before=$before;NewTransactionsPossible=$false;ObservationHours=$network.ObservationHours};Add-WsmJournal $paths $state 'CutoverPrepared' '' $state.Cutover}elseif($state.Cutover.PlanHash -ine $CutoverPlanHash){throw 'Cannot replace a running cutover plan.'};Confirm-WsmOutputStateCheckpoint -StateDirectory $StateDirectory -PairId $package.Manifest.PairId -PlanHash $package.Manifest.PlanHash
        if($resuming){Assert-WsmActivationNetwork $network;$review=[pscustomobject]@{Owner=$ResumeOwner;Evidence=$ResumeEvidence;Utc=(Get-WsmUtc);ManifestHash=$ExpectedHash;CutoverPlanHash=$CutoverPlanHash};$state.Cutover | Add-Member NoteProperty ResumeReview $review -Force;Add-WsmJournal $paths $state 'ActivationResumeReviewed' '' $review;Invoke-WsmCutoverSettingTransitions $package $paths $state;Invoke-WsmActivationSequence $package $paths $state -Resume;$state.Cutover.Stage='Activated';$state.Stage='PostCutoverValidationRequired';Complete-WsmCutoverObservation $paths $state;return $state};if($env:COMPUTERNAME -ine $network.FinalName){$args=@{NewName=$network.FinalName;Force=$true;ErrorAction='Stop'};if($Secrets.ContainsKey('DomainRename')){$args.DomainCredential=$Secrets.DomainRename};Rename-Computer @args | Out-Null;$state.Stage='RebootRequired';$state.Cutover.Stage='RenameRebootRequired';Add-WsmJournal $paths $state 'RenameRequiresReboot' '' ([pscustomobject]@{FinalName=$network.FinalName});return $state}
        $interface=Get-NetAdapter -Name $network.InterfaceAlias -ErrorAction Stop;if(-not $interface){throw 'Reviewed network interface absent.'}
        if(-not @(Get-NetIPAddress -InterfaceAlias $network.InterfaceAlias -IPAddress $network.FinalIP -ErrorAction SilentlyContinue).Count){$args=@{InterfaceAlias=$network.InterfaceAlias;IPAddress=$network.FinalIP;PrefixLength=$network.PrefixLength;ErrorAction='Stop'};if($network.PSObject.Properties['DefaultGateway'] -and $network.DefaultGateway){$args.DefaultGateway=$network.DefaultGateway};New-NetIPAddress @args | Out-Null}
        Set-DnsClientServerAddress -InterfaceAlias $network.InterfaceAlias -ServerAddresses $network.DnsServers
        foreach($temp in $network.TemporaryIP){if($temp -and $temp -ine $network.FinalIP){Get-NetIPAddress -InterfaceAlias $network.InterfaceAlias -IPAddress $temp -ErrorAction SilentlyContinue | Remove-NetIPAddress -Confirm:$false}}
        $final=Get-NetIPAddress -InterfaceAlias $network.InterfaceAlias -IPAddress $network.FinalIP;if([string]$final.AddressState -eq 'Duplicate'){throw 'Duplicate address detected; activation blocked.'}
        Assert-WsmActivationNetwork $network;Invoke-WsmCutoverSettingTransitions $package $paths $state;$state.Cutover.Stage='NetworkApplied';Add-WsmJournal $paths $state 'NetworkApplied' '' ([pscustomobject]@{Interface=$network.InterfaceAlias;IP=$network.FinalIP})
        # Record the point of no automatic source restart before starting any consumer.
        $state.Cutover.NewTransactionsPossible=$true;Add-WsmJournal $paths $state 'ActivationBoundary' '' ([pscustomobject]@{ReconcileRequiredForRollback=$true})
        Invoke-WsmActivationSequence $package $paths $state
        $state.Cutover.Stage='Activated';$state.Stage='PostCutoverValidationRequired';Complete-WsmCutoverObservation $paths $state;$state
    }
}
function Invoke-WsmCutoverSettingTransitions($Package,$Paths,$State) {
    foreach($item in @($Package.Plan.Items | Where-Object {$_.Decision -eq 'Include' -and $_.MigrationSpec.PSObject.Properties['SettingTransition'] -and $_.MigrationSpec.SettingTransition.RequiredPhase -eq 'CutoverReady'})) {
        [void](Invoke-WsmSettingTransitionForPhase $item $Package $Paths $State CutoverReady)
    }
}
function Get-WsmNetworkSnapshot {
    [pscustomobject]@{Name=$env:COMPUTERNAME;Addresses=@(Get-NetIPAddress | Select-Object InterfaceAlias,IPAddress,PrefixLength);DNS=@(Get-DnsClientServerAddress | Select-Object InterfaceAlias,ServerAddresses);Routes=@(Get-NetRoute | Select-Object InterfaceAlias,DestinationPrefix,NextHop)}
}
function Get-WsmAcceptanceGates {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[object[]]$GeneralHostEvidence=@())
    $p=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;$paths=Get-WsmOperationPaths $StateDirectory $p.Manifest.PairId;$s=Get-WsmOperationState $paths $p;$missing=New-Object 'System.Collections.Generic.List[string]'
    if($s.ManifestHash -ine $ExpectedHash -or -not $p.Manifest.Final){$missing.Add('Applied final generation')};if(-not $s.Cutover -or $s.Cutover.Stage -ne 'Activated'){$missing.Add('Reviewed cutover activation')}
    $v=Invoke-WsmValidation $ManifestPath $ExpectedHash $StateDirectory Final @{} $GeneralHostEvidence;if(-not $v.Passed){$missing.Add('Final per-item configuration, dependency and business validation')}
    foreach($check in @('DNS','Kerberos','ExternalConnectivity','Monitoring','SecurityAgent','License','UserAcceptance')){if(-not (Test-WsmEvidence $s '' $check $ExpectedHash)){$missing.Add($check)}}
    if($p.Plan.SchemaVersion -eq 3){$projection=Get-WsmAssistiveStageResultProjection $p $s;if(@($projection.DeferredItemIds).Count -or @($projection.PendingItemIds).Count){$missing.Add('Every approved Assistive item applied and read back in the current generation')}}
    $accepted=$missing.Count -eq 0
    $retirement=New-Object 'System.Collections.Generic.List[string]';foreach($check in @('BackupRestore','LongCycleJobs','Observation','RetirementRetention','ExternalConsumerOldPathDrained','SpecialProductDisposition','DataRetentionHandoff','CredentialHandoff','CertificateHandoff','CMDBHandoff','DNSHandoff','LicenseHandoff','MonitoringHandoff','RollbackCutoffAndDeletionOwner')){if(-not (Test-WsmEvidence $s '' $check $ExpectedHash)){$retirement.Add($check)}}
    $observation=$null;try{$observation=Get-WsmObservationWindow $s}catch{$observation=[pscustomobject]@{Ready=$false;Reason=$_.Exception.Message}}
    [pscustomobject]@{Observation=$observation;PairId=$s.PairId;FinalAccepted=$accepted;RetirementReady=($accepted -and $retirement.Count -eq 0);MissingFinal=$missing.ToArray();MissingRetirement=$retirement.ToArray();Mode='IsolatedPilot';ProductionVerified=$false;RetirementAction='Report only; never deletes source or secrets'}
}
function Get-WsmAssistiveStageResultProjection($Package,$State) {
    $approved=@($Package.Plan.Assistive.ApprovedItemIds | Sort-Object -Unique);$applied=New-Object 'System.Collections.Generic.List[string]';$pendingIds=New-Object 'System.Collections.Generic.List[string]';$deferred=New-Object 'System.Collections.Generic.List[string]';$rows=New-Object 'System.Collections.Generic.List[object]'
    $items=@{};foreach($item in @($Package.Plan.Items)){$items[[string]$item.ItemId]=$item}
    foreach($id in $approved){$records=@($State.Items | Where-Object ItemId -CEQ $id);$operations=@($State.PendingOperations | Where-Object ItemId -CEQ $id);$record=$null;if($records.Count -eq 1){$record=$records[0]};$decision='Include';if($items.ContainsKey($id)){$decision=[string]$items[$id].Decision};$hash='';$generation=0;$status='Deferred';if($record){$status=[string]$record.Status;if($record.PSObject.Properties['AppliedManifestHash']){$hash=[string]$record.AppliedManifestHash};if($record.PSObject.Properties['AppliedGeneration']){$generation=[long]$record.AppliedGeneration}};$isPending=($operations.Count -gt 0);$isApplied=(-not $isPending -and $record -and $status -eq 'Succeeded' -and $hash -ieq $Package.SHA256 -and $generation -eq [long]$Package.Manifest.Generation -and ($record.CreatedByTool -eq $true -or ($record.PSObject.Properties['ExternalOwnershipVerified'] -and $record.ExternalOwnershipVerified -and $record.OwnershipChannel -ceq 'NonC' -and @($record.FileResults|Where-Object {$_.Status -notin @('Applied','DirectoryReady') -or [long]$_.Generation -ne [long]$Package.Manifest.Generation}).Count -eq 0)))
        if($isApplied){$applied.Add($id)};if($isPending){$pendingIds.Add($id)};if(-not $isApplied){$deferred.Add($id)}
        $rows.Add([pscustomobject][ordered]@{ItemId=$id;Decision=$decision;Status=$status;AppliedManifestHash=$hash;AppliedGeneration=$generation;Pending=$isPending;Deferred=(-not $isApplied)})
    }
    $fileRows=@(Get-WsmAssistiveStageFileResultRows $Package $State $approved $items)
    [pscustomobject][ordered]@{ApprovedItemIds=[string[]]$approved;ItemResults=[object[]]$rows.ToArray();AppliedItemIds=[string[]]@($applied.ToArray()|Sort-Object);PendingItemIds=[string[]]@($pendingIds.ToArray()|Sort-Object);DeferredItemIds=[string[]]@($deferred.ToArray()|Sort-Object);FileResults=[object[]]$fileRows}
}
function Get-WsmAssistiveStageFileResultRows($Package,$State,[string[]]$ApprovedItemIds,[hashtable]$PlanItems) {
    $output=New-Object 'System.Collections.Generic.List[object]';$generation=[long]$Package.Manifest.Generation;$artifactRows=@()
    try{$artifactRows=@(Read-WsmArtifactLines (Join-Path $Package.Root 'artifacts.jsonl') $Package.Manifest.ArtifactsHash)}catch{}
    $persisted=@();if($State.PSObject.Properties['AssistiveFileResults']){$persisted=@($State.AssistiveFileResults)}
    foreach($itemId in $ApprovedItemIds){
        if(-not $PlanItems.ContainsKey([string]$itemId)){continue};$item=$PlanItems[[string]$itemId];$spec=$item.MigrationSpec
        if($spec.Adapter -ne 'FileScope'){continue};$channel=[string]$spec.TransferChannel;if($channel -notin @('C','NonC','External')){$channel='Unknown'}
        if($channel -eq 'NonC'){
            $rows=@($persisted|Where-Object ItemId -CEQ $itemId)
            if($rows.Count){foreach($row in $rows){$effective=[string]$row.EffectivePath;$status=[string]$row.Status;$observed=[string]$row.ObservedHash;$existing=[string]$row.ExistingTargetPath;$reason=[string]$row.Reason;if($row.Generation -ne $generation){$effective='';$status='Deferred';$existing='';$observed='';$reason='NonC evidence belongs to a different package generation.'}elseif($effective -and $status -in @('Applied','DirectoryReady')){try{Assert-WsmNoReparse $effective;Assert-WsmAssistiveFileTopology $effective;if($row.EntryType -eq 'Directory'){if(-not [IO.Directory]::Exists($effective)){throw 'Target directory is absent.'};$observed=''}else{if(-not [IO.File]::Exists($effective)){throw 'Target file is absent.'};$observed=(Get-FileHash -LiteralPath $effective -Algorithm SHA256).Hash.ToLowerInvariant();if($observed -ine [string]$row.SourceHash){throw 'Target file bytes drifted from the approved source hash.'}};$liveMetadata=Get-WsmFileMetadata $effective 'DaclOwner';if(-not $row.PSObject.Properties['MetadataHash'] -or (Get-WsmAssistiveMetadataHash $liveMetadata) -ine [string]$row.MetadataHash){throw 'Target metadata drifted from the accepted D readback.'}}catch{$effective='';$status='Deferred';$reason='Current native NonC target bytes or metadata no longer match the accepted D readback.'}};$output.Add([pscustomobject][ordered]@{ItemId=[string]$itemId;EntryId=[string]$row.EntryId;RelativePath=[string]$row.RelativePath;Channel='NonC';OriginalPath=[string]$row.OriginalPath;PreservedPath=[string]$row.PreservedPath;EffectivePath=$effective;Status=$status;ExistingTargetPath=$existing;ExistingTargetHash=[string]$row.ExistingTargetHash;ObservedHash=$observed;SourceHash=[string]$row.SourceHash;Reason=$reason;Generation=$generation;ProjectedGeneration=$generation})}}
            continue
        }
        if($channel -ne 'C'){continue}
        $record=@($State.Items|Where-Object ItemId -CEQ $itemId);$recordItem=$null;if($record.Count -eq 1){$recordItem=$record[0]}
        $targetRoot=[string]$spec.TargetPath
        foreach($entry in @($artifactRows|Where-Object ItemId -CEQ $itemId)){
            $relative=[string]$entry.RelativePath;$path=$targetRoot;if($relative){$path=Join-Path $targetRoot $relative};$isDirectory=[bool]$entry.Directory;$sourceHash='';if(-not $isDirectory -and $entry.Data){$sourceHash=[string]$entry.Data.Hash}
            $fileResult=@();if($recordItem -and $recordItem.PSObject.Properties['FileResults']){$fileResult=@($recordItem.FileResults|Where-Object RelativePath -CEQ $relative)};$resultStatus='Deferred';$reason='No current per-file restore/readback record exists.';if($fileResult.Count -eq 1){$resultStatus=[string]$fileResult[0].Status;$reason=[string]$fileResult[0].Reason}
            $effective='';$existing='';$existingHash='';$observed='';$status=$resultStatus
            try{
                Assert-WsmNoReparse $path
                if([IO.File]::Exists($path) -or [IO.Directory]::Exists($path)){Assert-WsmAssistiveFileTopology $path}
                if($isDirectory){if([IO.Directory]::Exists($path)){$dirs=@();if($recordItem -and $recordItem.PSObject.Properties['OwnedDirectories']){$dirs=@($recordItem.OwnedDirectories|Where-Object RelativePath -CEQ $relative)};if($dirs.Count -eq 1 -and [long]$dirs[0].Generation -eq $generation -and $dirs[0].MetadataHash -match '^[a-f0-9]{64}$' -and (Get-WsmAssistiveMetadataHash (Get-WsmFileMetadata $path $spec.Metadata)) -ieq [string]$dirs[0].MetadataHash){$effective=$path;$status='DirectoryReady';$reason='Required directory current metadata matches exact-generation ownership readback.'}else{$existing=$path;$status='Deferred';$reason='Directory metadata or current-generation ownership/readback is not verified.'}}}
                elseif([IO.File]::Exists($path)){$observed=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant();$owned=@();if($recordItem -and $recordItem.PSObject.Properties['OwnedFiles']){$owned=@($recordItem.OwnedFiles|Where-Object RelativePath -CEQ $relative)};if($owned.Count -eq 1 -and [long]$owned[0].Generation -eq $generation -and $owned[0].MetadataHash -match '^[a-f0-9]{64}$' -and (Get-WsmAssistiveMetadataHash (Get-WsmFileMetadata $path $spec.Metadata)) -ieq [string]$owned[0].MetadataHash -and $observed -ieq [string]$owned[0].SHA256 -and $observed -ieq $sourceHash){$effective=$path;$status='Applied';$reason='File bytes and metadata match the sealed artifact and current-generation ownership/readback.'}else{$existing=$path;$existingHash=$observed;if($status -eq 'Applied' -or $status -eq 'VerifiedOwned'){$status='Deferred';$reason='Target bytes, metadata or exact current-generation ownership/readback do not match.'}}}
            }catch{$status='Deferred';$reason='Target path/readback could not be verified safely.';$effective='';$existing=$path}
            if($status -eq 'BlockedConflict' -and -not $existing){$existing=$path;if(-not $isDirectory -and [IO.File]::Exists($path)){try{$existingHash=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}catch{}}}
            if($status -notin @('Applied','VerifiedOwned','DirectoryReady','BlockedConflict','DeferredManual','Deferred','Failed')){$status='Deferred'};if($status -in @('Applied','VerifiedOwned','DirectoryReady') -and -not $effective){$status='Deferred';$reason='Target path lacks matching current-generation readback.'}
            $output.Add([pscustomobject][ordered]@{ItemId=[string]$itemId;EntryId='';RelativePath=$relative;Channel='C';OriginalPath=$(if($relative){Join-Path ([string]$spec.SourcePath) $relative}else{[string]$spec.SourcePath});PreservedPath=[string]$path;EffectivePath=$effective;Status=$status;ExistingTargetPath=$existing;ExistingTargetHash=$existingHash;ObservedHash=$observed;SourceHash=$sourceHash;Reason=$reason;Generation=$generation;ProjectedGeneration=$generation})
        }
    }
    $output.ToArray()
}
function Export-WsmStageResult {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[ValidateSet('Restore','PreCutoverValidation','Cutover','PostCutoverValidation','Retirement')][string]$Stage,[string]$Path,[object[]]$GeneralHostEvidence=@())
    $p=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $p.Manifest.Target.Fingerprint;$paths=Get-WsmOperationPaths $StateDirectory $p.Manifest.PairId
    $gates=$null;if($Stage -in @('PostCutoverValidation','Retirement')){$gates=Get-WsmAcceptanceGates $ManifestPath $ExpectedHash $StateDirectory $GeneralHostEvidence}
    Invoke-WsmLocked $paths.Root {$s=Get-WsmOperationState $paths $p;if($s.ManifestHash -ine $ExpectedHash){$attemptMatches=($Stage -ceq 'Restore' -and $s.Stage -cin @('Failed','Cancelled','Running') -and $s.PSObject.Properties['RestoreAttempt'] -and $s.RestoreAttempt.ManifestHash -ieq $ExpectedHash -and $s.RestoreAttempt.Generation -eq $p.Manifest.Generation);if(-not $attemptMatches){throw 'No current applied generation or matching durable restore attempt.'}};$status='Blocked';switch($Stage){Restore{$status=$s.Stage;if($status -notin @('Succeeded','Failed','Cancelled','RebootRequired','ManualEvidenceRequired')){$status='Blocked'}};PreCutoverValidation{$pathV=Join-Path $paths.Root 'validation-Staged.json';if([IO.File]::Exists($pathV)){$v=Read-WsmJson $pathV;if($v.ManifestHash -ieq $ExpectedHash -and $v.Passed){$status='Succeeded'}}};Cutover{if($s.Cutover -and $s.Cutover.Stage -eq 'Activated'){$status='Succeeded'}};PostCutoverValidation{if($gates.FinalAccepted){$status='Succeeded'}else{$status='ManualEvidenceRequired'}};Retirement{if($gates.RetirementReady){$status='Succeeded'}else{$status='ManualEvidenceRequired'}}};$s.ResultSequence++;$r=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='StageResult';BatchId=$p.Manifest.BatchId;PairId=$p.Manifest.PairId;SourceHostId=$p.Plan.Source.HostId;TargetHostId=$p.Plan.Target.HostId;TargetFingerprint=$p.Plan.Target.Fingerprint;InventoryRevision=$p.Manifest.InventoryRevision;DecisionRevision=$p.Manifest.DecisionRevision;ApprovalId=$p.Manifest.ApprovalId;PlanHash=$p.Manifest.PlanHash;ManifestHash=$ExpectedHash;PayloadGeneration=$p.Manifest.Generation;RunId=$s.RunId;Sequence=$s.ResultSequence;Stage=$Stage;Status=$status;ProducedUtc=(Get-WsmUtc);Mode='IsolatedPilot';ProductionVerified=$false;JournalHash=$s.JournalHash};if($p.Plan.SchemaVersion -eq 3){$r | Add-Member NoteProperty Assistive (Get-WsmAssistiveStageResultProjection $p $s) -Force};Write-WsmJson $Path $r;Add-WsmJournal $paths $s 'StageResultExported' '' ([pscustomobject]@{Stage=$Stage;Sequence=$r.Sequence;Status=$status});[pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path).Hash;Result=$r}}
}
