function ConvertTo-WsmDeliveryMarkdownValue($Value) {
    if($null -eq $Value){return '(none)'}
    $text=[string]$Value
    $text=$text.Replace('\','\\').Replace('`','\`').Replace('|','\|').Replace('<','&lt;').Replace('>','&gt;')
    $text=[regex]::Replace($text,"`r`n|`r|`n",'<br>')
    $text
}
function Get-WsmDeliveryBaseManifestBinding($Package,[string]$BaseManifestPath,[string]$BaseManifestHash,[ValidateSet('Full','Delta')][string]$OperationKind='Full') {
    $baseHash='';$status='None'
    if($OperationKind -ceq 'Delta' -and -not $Package.Manifest.BaseManifestHash){throw 'Delta delivery requires a base manifest binding.'}
    if($Package.Manifest.BaseManifestHash){
        if(-not $BaseManifestPath){if($OperationKind -ceq 'Delta'){throw 'Delta delivery requires its trusted base manifest file.'};$baseHash=([string]$Package.Manifest.BaseManifestHash).ToLowerInvariant();$status='ReferenceOnly';return [pscustomobject]@{Hash=$baseHash;Status=$status}}
        if($BaseManifestHash -notmatch '^[a-fA-F0-9]{64}$' -or $Package.Manifest.BaseManifestHash -ine $BaseManifestHash){throw 'Delivery base manifest hash differs from the sealed current manifest.'}
        $base=Test-WsmMigrationPackage $BaseManifestPath $BaseManifestHash
        if($base.Manifest.PairId -cne $Package.Manifest.PairId -or $base.Manifest.PlanHash -ine $Package.Manifest.PlanHash -or $Package.Manifest.Generation -le $base.Manifest.Generation){throw 'Delta base/current pair, plan or generation binding mismatch.'}
        $baseHash=$BaseManifestHash.ToLowerInvariant();$status='VerifiedTrustedBase'
    }elseif($BaseManifestPath -or $BaseManifestHash){throw 'A base manifest was provided for a full package.'}
    [pscustomobject]@{Hash=$baseHash;Status=$status}
}
function Assert-WsmPackageTransportEntries($Package,$Transport) {
    $members=@(Get-WsmPackageMembers $Package);$entries=@($Transport.Entries)
    if($members.Count -ne $entries.Count -or $members.Count -gt 100000){throw 'Transport entry set differs from the validated package whitelist.'}
    $expected=@{};foreach($member in $members){$expected[[string]$member.Name]=$member}
    $seen=@{};$volumeCounts=@{};foreach($entry in $entries){
        Assert-WsmFields $entry @('Name','Bytes','Hash','Volume') @('Name','Bytes','Hash','Volume')
        $name=[string]$entry.Name;if(-not $expected.ContainsKey($name) -or $seen.ContainsKey($name) -or $entry.Hash -notmatch '^[a-fA-F0-9]{64}$' -or $entry.Volume -lt 1 -or $entry.Volume -gt @($Transport.Volumes).Count){throw 'Transport contains an unknown, duplicate or invalid package member.'}
        $member=$expected[$name];if([long]$entry.Bytes -ne [long]$member.Bytes -or [string]$entry.Hash -ine [string]$member.Hash){throw ('Transport member bytes/hash differ from the validated package: '+$name)}
        $seen[$name]=$true;if(-not $volumeCounts.ContainsKey([int]$entry.Volume)){$volumeCounts[[int]$entry.Volume]=0};$volumeCounts[[int]$entry.Volume]++
    }
    for($number=1;$number -le @($Transport.Volumes).Count;$number++){if(-not $volumeCounts.ContainsKey($number) -or $volumeCounts[$number] -lt 1){throw 'Transport has an empty or unreferenced volume.'}}
}
function Get-WsmDirectoryDeliveryReceiptContext([string]$SummaryPath,[string]$ExpectedHash,[string]$ManifestPath,[string]$ExpectedManifestHash,[string]$BaseManifestPath,[string]$BaseManifestHash,[ValidateSet('Full','Delta')][string]$OperationKind='Full') {
    if($OperationKind -ceq 'Delta'){throw 'DirectoryDelivery is a full package transport; delta receipts require the validated ArtifactDeltaVolumeTransport or ArtifactDeltaDirectoryTransport consumer.'}
    $summary=Read-WsmTrustedJson $SummaryPath $ExpectedHash;Assert-WsmEnvelope $summary 'DirectoryDelivery'
    Assert-WsmFields $summary @('SchemaVersion','ToolVersion','Kind','DeliveryId','PackageId','PairId','PlanHash','ManifestHash','PackageDirectory','Members','TotalBytes','ReportReferences','CreatedUtc','Status') @('SchemaVersion','DeliveryId','PackageId','PairId','PlanHash','ManifestHash','PackageDirectory','Members','TotalBytes','ReportReferences','Status')
    if($summary.SchemaVersion -ne 1 -or $summary.Status -cne 'Sealed' -or $summary.DeliveryId -notmatch '^[0-9a-fA-F-]{36}$' -or $summary.ManifestHash -ine $ExpectedManifestHash -or $summary.PlanHash -notmatch '^[a-fA-F0-9]{64}$' -or @($summary.Members).Count -lt 3 -or @($summary.Members).Count -gt 100000){throw 'Directory delivery summary is not a supported sealed package delivery.'}
    foreach($id in @($summary.DeliveryId,$summary.PackageId,$summary.PairId)){Assert-WsmId ([string]$id)}
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedManifestHash
    if($package.Manifest.PackageId -cne $summary.PackageId -or $package.Manifest.PairId -cne $summary.PairId -or $package.Manifest.PlanHash -ine $summary.PlanHash){throw 'Directory delivery/package identity binding mismatch.'}
    $packageRoot=[IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($ManifestPath));Assert-WsmNoReparse $packageRoot
    $wanted=@{};$total=[long]0
    foreach($member in @($summary.Members)){
        Assert-WsmFields $member @('Name','Bytes','SHA256') @('Name','Bytes','SHA256')
        $name=[string]$member.Name;if($name -notmatch '^(?:manifest\.json|plan\.json|artifacts\.jsonl|freeze\.json|payload/[a-f0-9]{64}\.blob)$' -or $wanted.ContainsKey($name) -or $member.SHA256 -notmatch '^[a-fA-F0-9]{64}$' -or [long]$member.Bytes -lt 0){throw 'Directory delivery contains an invalid or duplicate member descriptor.'}
        $wanted[$name]=[pscustomobject]@{Name=$name;Bytes=[long]$member.Bytes;Hash=([string]$member.SHA256).ToLowerInvariant()};$total+=[long]$member.Bytes
    }
    if($total -ne [long]$summary.TotalBytes){throw 'Directory delivery member byte total mismatch.'}
    $actual=@(Get-WsmDirectoryDeliveryFileIndex $packageRoot);if($actual.Count -ne $wanted.Count){throw 'Directory package member set differs from the trusted delivery summary.'}
    $actualMap=@{};foreach($file in $actual){$actualMap[$file.Name]=$file}
    foreach($name in $wanted.Keys){if(-not $actualMap.ContainsKey($name) -or [long]$actualMap[$name].Bytes -ne $wanted[$name].Bytes -or (Get-FileHash -LiteralPath $actualMap[$name].Path -Algorithm SHA256).Hash -ine $wanted[$name].Hash){throw ('Directory package member hash/length mismatch: '+$name)}}
    $packageMembers=@(foreach($member in $wanted.Values){[pscustomobject]@{Name=$member.Name;Bytes=$member.Bytes;Hash=$member.Hash}});Assert-WsmDirectoryDeliveryPackageMembers $package $packageMembers
    $receiptMembers=@(foreach($member in $wanted.Values){[pscustomobject]@{Name=$member.Name;Bytes=$member.Bytes;SHA256=$member.Hash}})
    $base=Get-WsmDeliveryBaseManifestBinding $package $BaseManifestPath $BaseManifestHash $OperationKind
    [pscustomobject]@{Transport=$summary;TransportPath=[IO.Path]::GetFullPath($SummaryPath);TransportHash=([string]$ExpectedHash).ToLowerInvariant();Package=$package;ManifestHash=([string]$ExpectedManifestHash).ToLowerInvariant();BaseManifestHash=$base.Hash;BaseVerificationStatus=$base.Status;Volumes=@();Members=$receiptMembers;TotalVolumeBytes=$total;Mode='Directory';OperationKind=$OperationKind;DeliveryId=[string]$summary.DeliveryId}
}
function Get-WsmArtifactDeltaReceiptContext([string]$TransportPath,[string]$ExpectedHash,[string]$ManifestPath,[string]$ExpectedManifestHash,[string]$BaseManifestPath,[string]$BaseManifestHash,[string]$ImportedDirectory,[string]$SummaryPath,[string]$SummaryHash,[string]$ChangesPath) {
    $transport=Read-WsmJson $TransportPath
    if($transport.Kind -ceq 'ArtifactDeltaVolumeTransport'){$transport=Read-WsmDeltaVolumeTransport $TransportPath $ExpectedHash;$transferMode='Zip'}
    elseif($transport.Kind -ceq 'ArtifactDeltaDirectoryTransport'){$actualTransportHash=Get-WsmDeltaVolumeHash $TransportPath;if($actualTransportHash -ine $ExpectedHash){throw 'Independent delta directory transport SHA256 mismatch.'};Assert-WsmDeltaTransportMetadata $transport;if($transport.FormatVersion -ne 1 -or $transport.Mode -cne 'Directory'){throw 'Unsupported delta directory transport mode/version.'};$transferMode='Directory'}
    else{throw 'Wrong delta transport kind; full PackageTransport cannot serve as a delta.'}
    if([string]::IsNullOrWhiteSpace($BaseManifestPath) -or $BaseManifestHash -notmatch '^[a-fA-F0-9]{64}$' -or $BaseManifestHash -ine $transport.BaseManifestHash){throw 'Delta receipt requires the exact trusted base manifest file and hash.'}
    if($ExpectedManifestHash -ine $transport.CurrentManifestHash){throw 'Delta receipt current manifest hash differs from the sealed transport.'}
    $basePath=[IO.Path]::GetFullPath($BaseManifestPath);$currentPath=[IO.Path]::GetFullPath($ManifestPath)
    if($ImportedDirectory){$importRoot=[IO.Path]::GetFullPath($ImportedDirectory);$candidateBase=Join-Path (Join-Path $importRoot 'base') 'manifest.json';$candidateCurrent=Join-Path (Join-Path $importRoot 'current') 'manifest.json';if([IO.File]::Exists($candidateBase)){$basePath=$candidateBase};if([IO.File]::Exists($candidateCurrent)){$currentPath=$candidateCurrent}}
    # A delta import intentionally contains the exact base/current metadata and changed
    # payload only. Validate those manifests and plans here; the native transport
    # validator below checks the actual delta tree without requiring unchanged payload.
    $baseManifest=Read-WsmTrustedJson $basePath $BaseManifestHash;Assert-WsmPackageHeaderContract $baseManifest
    $currentManifest=Read-WsmTrustedJson $currentPath $ExpectedManifestHash;Assert-WsmPackageHeaderContract $currentManifest
    $basePlanPath=Join-Path ([IO.Path]::GetDirectoryName($basePath)) 'plan.json';$currentPlanPath=Join-Path ([IO.Path]::GetDirectoryName($currentPath)) 'plan.json'
    $basePlan=Read-WsmMigrationPlan $basePlanPath $transport.PlanHash;$currentPlan=Read-WsmMigrationPlan $currentPlanPath $transport.PlanHash
    foreach($pair in @(@($baseManifest,$basePlan),@($currentManifest,$currentPlan))){$m=$pair[0];$p=$pair[1];if($m.PairId -cne $transport.PairId -or $m.PlanHash -ine $transport.PlanHash -or $p.PairId -cne $m.PairId -or $p.BatchId -cne $m.BatchId -or $p.ApprovalId -cne $m.ApprovalId -or $p.Source.HostId -cne $m.Source.HostId -or $p.Target.HostId -cne $m.Target.HostId -or $p.Source.Fingerprint -ine $m.Source.Fingerprint -or $p.Target.Fingerprint -ine $m.Target.Fingerprint -or $p.DecisionRevision -ne $m.DecisionRevision -or $p.InventoryRevision -ne $m.InventoryRevision){throw 'Delta base/current pair, plan or endpoint binding mismatch.'}}
    if($currentManifest.Generation -lt 1 -or $currentManifest.Generation -le $baseManifest.Generation -or $currentManifest.BaseManifestHash -ine $BaseManifestHash){throw 'Delta base/current generation or manifest ancestry binding mismatch.'}
    $base=[pscustomobject]@{Manifest=$baseManifest;Plan=$basePlan;Root=[IO.Path]::GetDirectoryName($basePath);SHA256=$BaseManifestHash;Valid=$true}
    $current=[pscustomobject]@{Manifest=$currentManifest;Plan=$currentPlan;Root=[IO.Path]::GetDirectoryName($currentPath);SHA256=$ExpectedManifestHash;Valid=$true}
    if($transferMode -ceq 'Directory'){$root=[IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($TransportPath));$checked=Test-WsmDeltaVolumeTransportContents $root $transport $ExpectedHash}
    elseif($ImportedDirectory){$root=[IO.Path]::GetFullPath($ImportedDirectory);$checked=Test-WsmDeltaVolumeTransportContents $root $transport $ExpectedHash}
    else{
        if(-not $SummaryPath -or $SummaryHash -notmatch '^[a-fA-F0-9]{64}$' -or -not $ChangesPath){throw 'Delta ZIP export receipt requires the trusted summary and changes inputs, or an independently validated imported directory.'}
        [void](Test-WsmArtifactDeltaManifest -SummaryPath $SummaryPath -SummaryHash $SummaryHash -ChangesPath $ChangesPath -BaseManifestPath $BaseManifestPath -BaseManifestHash $BaseManifestHash -BasePlanPath $basePlanPath -BasePlanHash $transport.PlanHash -CurrentManifestPath $ManifestPath -CurrentManifestHash $ExpectedManifestHash -CurrentPlanPath $currentPlanPath -CurrentPlanHash $transport.PlanHash)
        $sequence=0;$volumeRows=New-Object 'System.Collections.Generic.List[object]';$memberRows=New-Object 'System.Collections.Generic.List[object]';$seenMembers=@{}
        foreach($v in @($transport.Volumes | Sort-Object Sequence)){$sequence++;if($v.Sequence -ne $sequence -or $v.Name -notmatch ('^delta-'+[regex]::Escape([string]$transport.AttemptId)+'-'+$sequence.ToString('0000')+'\.zip$')){throw 'Delta receipt transport has a volume sequence gap or invalid name.'};$path=Join-Path ([IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($TransportPath))) $v.Name;[void](Test-WsmDeltaVolumeArchive $path $v $transport);$volumeRows.Add([pscustomobject]@{Name=[string]$v.Name;Number=$sequence;Bytes=[long]$v.Bytes;SHA256=([string]$v.SHA256).ToLowerInvariant()});foreach($m in @($v.Members)){if($m.Name -ceq 'volume.json'){continue};if($seenMembers.ContainsKey([string]$m.Name)){throw 'Delta transport repeats a member across volumes.'};$seenMembers[[string]$m.Name]=$true;$memberRows.Add([pscustomobject]@{Name=[string]$m.Name;Bytes=[long]$m.Bytes;SHA256=([string]$m.SHA256).ToLowerInvariant()})}}
        if($volumeRows.Count -ne @($transport.Volumes).Count){throw 'Delta transport volume set is incomplete.'}
        foreach($m in @($transport.MetadataMembers)){$matches=@($memberRows | Where-Object Name -CEQ $m.Name);if($matches.Count -ne 1 -or $matches[0].Bytes -ne $m.Bytes -or $matches[0].SHA256 -ine $m.SHA256){throw ('Delta transport metadata differs from its volume entry: '+$m.Name)}}
        $indexEntry=@($memberRows | Where-Object Name -CEQ 'delta-volume-index.json');if($indexEntry.Count -ne 1 -or $indexEntry[0].SHA256 -ine $transport.IndexHash){throw 'Delta volume index hash differs from its transport binding.'}
        $indexVolume=@($transport.Volumes | Where-Object {$_.Members.Name -contains 'delta-volume-index.json'});if($indexVolume.Count -ne 1){throw 'Delta volume index is absent or duplicated across volumes.'}
        $indexStream=[IO.File]::Open((Join-Path ([IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($TransportPath))) $indexVolume[0].Name),'Open','Read','Read');$archive=$null
        try{$archive=New-Object IO.Compression.ZipArchive($indexStream,[IO.Compression.ZipArchiveMode]::Read,$true);$indexEntryZip=@($archive.Entries | Where-Object FullName -CEQ 'delta-volume-index.json');if($indexEntryZip.Count -ne 1 -or $indexEntryZip[0].Length -gt 128MB){throw 'Delta volume index is missing or exceeds its bounded size.'};$indexReader=New-Object IO.StreamReader($indexEntryZip[0].Open(),[Text.Encoding]::UTF8,$true);try{$volumeIndexObject=ConvertFrom-WsmJson $indexReader.ReadToEnd()}finally{$indexReader.Dispose()}}finally{if($archive){$archive.Dispose()};$indexStream.Dispose()}
        if($volumeIndexObject.Kind -cne 'DeltaVolumeIndex' -or $volumeIndexObject.AttemptId -cne $transport.AttemptId -or @($volumeIndexObject.Chunks).Count -ne @($transport.Chunks).Count){throw 'Delta embedded index shape differs from the trusted transport.'}
        for($chunkIndex=0;$chunkIndex -lt @($transport.Chunks).Count;$chunkIndex++){$actualChunk=$volumeIndexObject.Chunks[$chunkIndex];$expectedChunk=$transport.Chunks[$chunkIndex];foreach($field in @('Hash','Bytes','Sequence','Offset','FullChunkHash','FullChunkBytes')){if([string]$actualChunk.$field -cne [string]$expectedChunk.$field){throw 'Delta embedded chunk index differs from the transport.'}};if($actualChunk.SegmentCount -ne 1 -or $expectedChunk.MemberName -notmatch ('^segments/'+$expectedChunk.Sequence.ToString('00000000')+'-'+[regex]::Escape([string]$expectedChunk.Hash)+'\.blob$')){throw 'Delta embedded chunk member mapping is invalid.'}}
        $total=($volumeRows | Measure-Object Bytes -Sum).Sum
        return [pscustomobject]@{Transport=$transport;TransportPath=[IO.Path]::GetFullPath($TransportPath);TransportHash=$ExpectedHash.ToLowerInvariant();Package=$current;ManifestHash=$ExpectedManifestHash.ToLowerInvariant();BaseManifestHash=$BaseManifestHash.ToLowerInvariant();BaseVerificationStatus='VerifiedTrustedBase';Volumes=$volumeRows.ToArray();Members=$memberRows.ToArray();TotalVolumeBytes=[long]$total;Mode='Zip';OperationKind='Delta';DeliveryId=[string]$transport.DeliveryId}
    }
    if(-not $checked.Valid -or $checked.Transport.CurrentManifestHash -ine $ExpectedManifestHash -or $checked.Transport.BaseManifestHash -ine $BaseManifestHash){throw 'Delta imported directory failed independent transport/base/current validation.'}
    if($transferMode -ceq 'Directory'){$members=@(foreach($m in @($transport.Members)){[pscustomobject]@{Name=[string]$m.Name;Bytes=[long]$m.Bytes;SHA256=([string]$m.SHA256).ToLowerInvariant()}});$volumeRows=@();$total=($members | Measure-Object Bytes -Sum).Sum}
    else{$members=@(foreach($v in @($transport.Volumes)){foreach($m in @($v.Members)){if($m.Name -cne 'volume.json'){[pscustomobject]@{Name=[string]$m.Name;Bytes=[long]$m.Bytes;SHA256=([string]$m.SHA256).ToLowerInvariant()}}}});$volumeRows=@(foreach($v in @($transport.Volumes | Sort-Object Sequence)){[pscustomobject]@{Name=[string]$v.Name;Number=[int]$v.Sequence;Bytes=[long]$v.Bytes;SHA256=([string]$v.SHA256).ToLowerInvariant()}});$total=($volumeRows | Measure-Object Bytes -Sum).Sum}
    [pscustomobject]@{Transport=$transport;TransportPath=[IO.Path]::GetFullPath($TransportPath);TransportHash=$ExpectedHash.ToLowerInvariant();Package=$current;ManifestHash=$ExpectedManifestHash.ToLowerInvariant();BaseManifestHash=$BaseManifestHash.ToLowerInvariant();BaseVerificationStatus='VerifiedTrustedBase';Volumes=$volumeRows;Members=$members;TotalVolumeBytes=[long]$total;Mode=$transferMode;OperationKind='Delta';DeliveryId=[string]$transport.DeliveryId}
}
function Get-WsmDeliveryPackageContext([string]$TransportPath,[string]$ExpectedHash,[string]$ManifestPath,[string]$ExpectedManifestHash,[string]$BaseManifestPath='',[string]$BaseManifestHash='',[ValidateSet('Full','Delta')][string]$OperationKind='Full',[string]$ImportedDirectory='',[string]$SummaryPath='',[string]$SummaryHash='',[string]$ChangesPath='') {
    if($ExpectedHash -notmatch '^[a-fA-F0-9]{64}$' -or $ExpectedManifestHash -notmatch '^[a-fA-F0-9]{64}$'){throw 'Delivery requires trusted SHA256 values for the transport and manifest.'}
    Assert-WsmNoReparse $TransportPath;Assert-WsmNoReparse $ManifestPath
    $transport=Read-WsmTrustedJson $TransportPath $ExpectedHash;Assert-WsmEnvelope $transport ([string]$transport.Kind)
    if($transport.Kind -ceq 'DirectoryDelivery'){return Get-WsmDirectoryDeliveryReceiptContext $TransportPath $ExpectedHash $ManifestPath $ExpectedManifestHash $BaseManifestPath $BaseManifestHash $OperationKind}
    if($transport.Kind -cin @('ArtifactDeltaVolumeTransport','ArtifactDeltaDirectoryTransport')){if($OperationKind -cne 'Delta'){throw 'ArtifactDelta transport requires OperationKind=Delta.'};return Get-WsmArtifactDeltaReceiptContext $TransportPath $ExpectedHash $ManifestPath $ExpectedManifestHash $BaseManifestPath $BaseManifestHash $ImportedDirectory $SummaryPath $SummaryHash $ChangesPath}
    if($OperationKind -ceq 'Delta'){throw 'PackageTransport cannot create a delta receipt; a validated ArtifactDelta transport consumer is required.'}
    if($transport.Kind -cne 'PackageTransport'){throw 'Unsupported transport kind for a delivery receipt.'}
    Assert-WsmFields $transport @('SchemaVersion','ToolVersion','Kind','PackageId','PairId','PlanHash','ManifestHash','Volumes','Entries','CreatedUtc','Mode') @('SchemaVersion','Kind','PackageId','PairId','PlanHash','ManifestHash','Volumes','Entries','Mode')
    if($transport.SchemaVersion -ne 1 -or $transport.Mode -cne 'IsolatedPilot' -or $transport.ManifestHash -ine $ExpectedManifestHash -or $transport.PlanHash -notmatch '^[a-fA-F0-9]{64}$' -or @($transport.Volumes).Count -lt 1 -or @($transport.Volumes).Count -gt 9999 -or @($transport.Entries).Count -lt 3 -or @($transport.Entries).Count -gt 100000){throw 'Transport is not a supported sealed full-package delivery.'}
    $package=Test-WsmMigrationPackage $ManifestPath $ExpectedManifestHash
    if($package.Manifest.PackageId -cne $transport.PackageId -or $package.Manifest.PairId -cne $transport.PairId -or $package.Manifest.PlanHash -ine $transport.PlanHash -or $package.Manifest.Generation -lt 1){throw 'Transport/package identity or generation binding mismatch.'}
    Assert-WsmPackageTransportEntries $package $transport
    $transportFile=[IO.Path]::GetFullPath($TransportPath);$transportDir=[IO.Path]::GetDirectoryName($transportFile);$volumes=@();$total=[long]0;$names=@{}
    foreach($volume in @($transport.Volumes)){
        Assert-WsmFields $volume @('Name','Bytes','Hash') @('Name','Bytes','Hash')
        if($volume.Name -notmatch ('^package-'+[regex]::Escape([string]$transport.PackageId)+'-\d{4}\.zip$') -or $volume.Hash -notmatch '^[a-fA-F0-9]{64}$' -or [long]$volume.Bytes -lt 1 -or [long]$volume.Bytes -gt 2GB -or $names.ContainsKey([string]$volume.Name)){throw 'Transport contains an invalid or duplicate volume descriptor.'}
        $names[[string]$volume.Name]=$true;$path=Join-Path $transportDir ([string]$volume.Name);Assert-WsmNoReparse $path
        $expected=@($transport.Entries | Where-Object Volume -EQ (@($volumes).Count+1));$check=Test-WsmZipVolume $path $expected ([string]$volume.Hash)
        if($check.Bytes -ne [long]$volume.Bytes){throw 'Transport volume byte count does not match the sealed descriptor.'}
        $volumes+=,[pscustomobject]@{Name=[string]$volume.Name;Number=(@($volumes).Count+1);Bytes=[long]$volume.Bytes;SHA256=([string]$volume.Hash).ToLowerInvariant()};$total+=[long]$volume.Bytes
    }
    $base=Get-WsmDeliveryBaseManifestBinding $package $BaseManifestPath $BaseManifestHash $OperationKind
    $members=@(foreach($entry in @($transport.Entries)){[pscustomobject]@{Name=[string]$entry.Name;Bytes=[long]$entry.Bytes;SHA256=([string]$entry.Hash).ToLowerInvariant()}})
    [pscustomobject]@{Transport=$transport;TransportPath=$transportFile;TransportHash=([string]$ExpectedHash).ToLowerInvariant();Package=$package;ManifestHash=([string]$ExpectedManifestHash).ToLowerInvariant();BaseManifestHash=$base.Hash;BaseVerificationStatus=$base.Status;Volumes=$volumes;Members=$members;TotalVolumeBytes=$total;Mode='Zip';OperationKind=$OperationKind;DeliveryId=''}
}
function New-WsmDeliveryReceiptRecord($Context,[string]$Status,[string]$DeliveryId) {
    $plan=$Context.Package.Plan;$manifest=$Context.Package.Manifest
    [pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='DeliveryReceipt';ReceiptId=[Guid]::NewGuid().ToString('D');DeliveryId=$DeliveryId;Status=$Status;Mode=$Context.Mode;OperationKind=$Context.OperationKind;MigrationMode=$manifest.Mode;BaseVerificationStatus=$Context.BaseVerificationStatus;PairId=$manifest.PairId;BatchId=$manifest.BatchId;SourceHostId=$manifest.Source.HostId;SourceFingerprint=$manifest.Source.Fingerprint;TargetHostId=$manifest.Target.HostId;TargetFingerprint=$manifest.Target.Fingerprint;ToolFingerprint=[string]$plan.ToolFingerprint;ApprovalId=$manifest.ApprovalId;PlanHash=$manifest.PlanHash.ToLowerInvariant();Generation=[int]$manifest.Generation;PackageId=$manifest.PackageId;ManifestHash=$Context.ManifestHash;BaseManifestHash=$Context.BaseManifestHash;TransportHash=$Context.TransportHash;VolumeBytes=$(if($Context.Transport.PSObject.Properties['VolumeBytes']){[long]$Context.Transport.VolumeBytes}else{[long]0});Volumes=@($Context.Volumes);Members=@($Context.Members);TotalVolumeBytes=[long]$Context.TotalVolumeBytes;CreatedUtc=(Get-WsmUtc);ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}
}
function Write-WsmDeliveryMarkdown([string]$Path,$Receipt,[object[]]$ReportReferences) {
    Assert-WsmNoReparse $Path
    $lines=New-Object 'System.Collections.Generic.List[string]'
    foreach($line in @('# Migration delivery','',('- Status: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.Status)),('- DeliveryId: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.DeliveryId)),('- ReceiptId: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.ReceiptId)),('- Mode: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.Mode)),('- Operation kind: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.OperationKind)),('- Base verification: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.BaseVerificationStatus)),('- PairId: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.PairId)),('- Source host: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.SourceHostId)),('- Target host: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.TargetHostId)),('- ApprovalId: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.ApprovalId)),('- PlanHash: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.PlanHash)),('- Generation: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.Generation)),('- PackageId: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.PackageId)),('- ManifestHash: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.ManifestHash)),('- BaseManifestHash: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.BaseManifestHash)),('- TransportHash: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.TransportHash)),('- Total volume bytes: '+(ConvertTo-WsmDeliveryMarkdownValue $Receipt.TotalVolumeBytes)),'','## Volumes','')){$lines.Add($line)}
    foreach($volume in @($Receipt.Volumes)){$lines.Add(('- '+(ConvertTo-WsmDeliveryMarkdownValue $volume.Number)+' — '+(ConvertTo-WsmDeliveryMarkdownValue $volume.Name)+' — '+(ConvertTo-WsmDeliveryMarkdownValue $volume.Bytes)+' bytes — SHA256 '+(ConvertTo-WsmDeliveryMarkdownValue $volume.SHA256)))}
    $lines.Add('');$lines.Add('## Package members');$lines.Add('')
    foreach($member in @($Receipt.Members)){$lines.Add(('- '+(ConvertTo-WsmDeliveryMarkdownValue $member.Name)+' — '+(ConvertTo-WsmDeliveryMarkdownValue $member.Bytes)+' bytes — SHA256 '+(ConvertTo-WsmDeliveryMarkdownValue $member.SHA256)))}
    $lines.Add('');$lines.Add('## Reports');$lines.Add('')
    if(@($ReportReferences).Count){foreach($report in $ReportReferences){$projectionStatus='ReportLocatorOnly';if($report.ReportProjectionHash){$projectionStatus='ProjectionHashVerified'};$lines.Add(('- DocumentId: '+(ConvertTo-WsmDeliveryMarkdownValue $report.DocumentId)+' — type '+(ConvertTo-WsmDeliveryMarkdownValue $report.DocumentType)+' — '+(ConvertTo-WsmDeliveryMarkdownValue $report.Path)+' — SHA256 '+(ConvertTo-WsmDeliveryMarkdownValue $report.SHA256)+' — projection '+(ConvertTo-WsmDeliveryMarkdownValue $report.ReportProjectionHash)+' ('+(ConvertTo-WsmDeliveryMarkdownValue $projectionStatus)+')'))}}else{$lines.Add('- No report references supplied.')}
    $lines.Add('');$lines.Add('## Scope and next step');$lines.Add('');$lines.Add('- This document describes the verified transport/package binding. It does not approve scope, prove readiness, or authorize restore/activation.');$lines.Add('- Move the complete trusted transport index and every listed volume through the approved trusted channel. The target must independently verify all files before restore.');$lines.Add('- Receipt status is report-only; ProductionVerified and ReadinessProof are false.')
    $directory=[IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($Path));if(-not [IO.Directory]::Exists($directory)){[void][IO.Directory]::CreateDirectory($directory)}
    [IO.File]::WriteAllText([IO.Path]::GetFullPath($Path),($lines -join "`r`n")+"`r`n",(New-Object Text.UTF8Encoding($false)))
}
function Assert-WsmDeliveryReportReferences([object[]]$References) {
    if(@($References).Count -gt 100){throw 'Delivery report-reference budget exceeded.'}
    $ids=@();$safe=@(foreach($reference in $References){
        Assert-WsmFields $reference @('DocumentId','Path','SHA256','DocumentType','ReportProjectionHash','TargetObservationRevision') @('DocumentId','Path','SHA256')
        Assert-WsmId ([string]$reference.DocumentId)
        if([string]$reference.SHA256 -notmatch '^[a-fA-F0-9]{64}$'){throw 'Delivery report reference requires a file SHA256.'}
        if($reference.PSObject.Properties['DocumentType'] -and [string]$reference.DocumentType -notmatch '^[A-Za-z][A-Za-z0-9]{0,63}$'){throw 'Delivery report reference type is invalid.'}
        if($reference.PSObject.Properties['ReportProjectionHash']){if([string]$reference.ReportProjectionHash -notmatch '^[a-fA-F0-9]{64}$'){throw 'Delivery report projection hash is invalid.'};if([IO.Path]::GetExtension([string]$reference.Path) -ine '.json'){throw 'A report projection hash can only be verified from typed JSON.'};$typed=Read-WsmTrustedJson ([string]$reference.Path) ([string]$reference.SHA256);if(-not $typed.PSObject.Properties['ReportProjectionHash'] -or -not $typed.PSObject.Properties['Projection']){throw 'Typed report projection fields are absent; report remains locator-only.'};$computedProjectionHash=Get-WsmHashText (ConvertTo-Json -InputObject $typed.Projection -Depth 45 -Compress);if($computedProjectionHash -ine [string]$typed.ReportProjectionHash -or $computedProjectionHash -ine [string]$reference.ReportProjectionHash){throw 'Typed report projection hash does not match its current projection content.'}}
        if($ids -contains [string]$reference.DocumentId){throw 'Duplicate delivery report DocumentId.'};$ids+=,[string]$reference.DocumentId
        if($reference.PSObject.Properties['TargetObservationRevision'] -and ($reference.TargetObservationRevision -isnot [int] -and $reference.TargetObservationRevision -isnot [long] -or $reference.TargetObservationRevision -lt 0)){throw 'Report target-observation revision must be a non-negative integer.'}
        $path=[IO.Path]::GetFullPath([string]$reference.Path);Assert-WsmNoReparse $path;Assert-WsmTrustedFile $path ([string]$reference.SHA256)
        [pscustomobject][ordered]@{DocumentId=[string]$reference.DocumentId;DocumentType=$(if($reference.PSObject.Properties['DocumentType']){[string]$reference.DocumentType}else{'ReportLocatorOnly'});Path=$path;SHA256=([string]$reference.SHA256).ToLowerInvariant();ReportProjectionHash=$(if($reference.PSObject.Properties['ReportProjectionHash']){([string]$reference.ReportProjectionHash).ToLowerInvariant()}else{''});TargetObservationRevision=$(if($reference.PSObject.Properties['TargetObservationRevision']){[long]$reference.TargetObservationRevision}else{$null})}
    })
    $safe
}
function Assert-WsmDeliveryReceipt {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$Path,[Parameter(Mandatory)][string]$ExpectedHash,[Parameter(Mandatory)][string]$PairId,[Parameter(Mandatory)][string]$PlanHash,[Parameter(Mandatory)][string]$SourceHostId,[Parameter(Mandatory)][string]$SourceFingerprint,[Parameter(Mandatory)][string]$TargetHostId,[Parameter(Mandatory)][string]$TargetFingerprint,[Parameter(Mandatory)][string]$ToolFingerprint,[Parameter(Mandatory)][string]$ApprovalId,[Parameter(Mandatory)][int]$Generation,[Parameter(Mandatory)][string]$ManifestHash,[Parameter(Mandatory)][ValidateSet('Full','Delta')][string]$OperationKind,[Parameter(Mandatory)][ValidateSet('None','ReferenceOnly','VerifiedTrustedBase')][string]$BaseVerificationStatus,[string]$BaseManifestHash='', [ValidateSet('Sealed','ImportedVerified')][string]$ExpectedStatus='ImportedVerified')
    $r=Read-WsmTrustedJson $Path $ExpectedHash;Assert-WsmEnvelope $r 'DeliveryReceipt'
    Assert-WsmFields $r @('SchemaVersion','ToolVersion','Kind','ReceiptId','DeliveryId','Status','Mode','OperationKind','MigrationMode','BaseVerificationStatus','PairId','BatchId','SourceHostId','SourceFingerprint','TargetHostId','TargetFingerprint','ToolFingerprint','ApprovalId','PlanHash','Generation','PackageId','ManifestHash','BaseManifestHash','TransportHash','VolumeBytes','Volumes','Members','TotalVolumeBytes','CreatedUtc','ReportOnly','ReadinessProof','ProductionVerified') @('Status','Mode','OperationKind','MigrationMode','BaseVerificationStatus','PairId','SourceHostId','SourceFingerprint','TargetHostId','TargetFingerprint','ToolFingerprint','ApprovalId','PlanHash','Generation','ManifestHash','BaseManifestHash','ReportOnly','ReadinessProof','ProductionVerified')
    if($r.Status -cne $ExpectedStatus -or $r.OperationKind -cne $OperationKind -or $r.BaseVerificationStatus -cne $BaseVerificationStatus -or $r.MigrationMode -cne 'IsolatedPilot' -or $r.Mode -cnotin @('Zip','Directory') -or $r.PairId -cne $PairId -or $r.PlanHash -ine $PlanHash -or $r.SourceHostId -cne $SourceHostId -or $r.SourceFingerprint -ine $SourceFingerprint -or $r.TargetHostId -cne $TargetHostId -or $r.TargetFingerprint -ine $TargetFingerprint -or $r.ToolFingerprint -ine $ToolFingerprint -or $r.ApprovalId -cne $ApprovalId -or $r.Generation -ne $Generation -or $r.ManifestHash -ine $ManifestHash -or $r.BaseManifestHash -ine $BaseManifestHash -or ($r.OperationKind -ceq 'Delta' -and $r.BaseVerificationStatus -cne 'VerifiedTrustedBase') -or $r.ReportOnly -isnot [bool] -or -not $r.ReportOnly -or $r.ReadinessProof -isnot [bool] -or $r.ReadinessProof -or $r.ProductionVerified -isnot [bool] -or $r.ProductionVerified){throw 'Delivery receipt does not bind the expected current package and pair plan, or is not report-only.'}
    $created=[DateTimeOffset]::MinValue;if(-not [DateTimeOffset]::TryParse([string]$r.CreatedUtc,[ref]$created) -or $created.Offset -ne [TimeSpan]::Zero -or $created -gt [DateTimeOffset]::UtcNow.AddMinutes(5) -or $created -lt [DateTimeOffset]::UtcNow.AddHours(-24)){throw 'Delivery receipt is expired or has an invalid production time.'}
    $r
}
function Export-WsmDeliveryDocument {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$TransportPath,[Parameter(Mandatory)][string]$ExpectedHash,[Parameter(Mandatory)][string]$ManifestPath,[Parameter(Mandatory)][string]$ExpectedManifestHash,[Parameter(Mandatory)][string]$OutputDirectory,[string]$BaseManifestPath='',[string]$BaseManifestHash='',[ValidateSet('Full','Delta')][string]$OperationKind='Full',[string]$ImportedDirectory='',[string]$SummaryPath='',[string]$SummaryHash='',[string]$ChangesPath='',[object[]]$ReportReferences=@())
    $reports=@(Assert-WsmDeliveryReportReferences $ReportReferences)
    $context=Get-WsmDeliveryPackageContext $TransportPath $ExpectedHash $ManifestPath $ExpectedManifestHash $BaseManifestPath $BaseManifestHash $OperationKind $ImportedDirectory $SummaryPath $SummaryHash $ChangesPath
    $output=[IO.Path]::GetFullPath($OutputDirectory);Assert-WsmNoReparse $output
    if([IO.Directory]::Exists($output) -or [IO.File]::Exists($output)){throw 'Delivery output directory already exists; choose a new exclusive directory.'}
    $parent=[IO.Path]::GetDirectoryName($output);if(-not [IO.Directory]::Exists($parent)){[void][IO.Directory]::CreateDirectory($parent)};Assert-WsmNoReparse $parent
    $deliveryId=[string]$context.DeliveryId;if(-not $deliveryId){$deliveryId=Get-WsmHashText ($context.TransportHash+'|'+$context.Package.Manifest.PackageId);$deliveryId=[Guid]::ParseExact($deliveryId.Substring(0,32),'N').ToString('D')}
    [void][IO.Directory]::CreateDirectory($output);Protect-WsmDirectory $output
    $receipt=New-WsmDeliveryReceiptRecord $context Sealed $deliveryId
    $receiptPath=Join-Path $output 'delivery-receipt.json';$markdownPath=Join-Path $output 'delivery.md';$indexPath=Join-Path $output 'delivery-index.json'
    Write-WsmJson $receiptPath $receipt;Write-WsmDeliveryMarkdown $markdownPath $receipt $reports
    $index=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='DeliveryIndex';DeliveryId=$deliveryId;ReceiptId=$receipt.ReceiptId;ReceiptPath='delivery-receipt.json';ReceiptHash=(Get-FileHash -LiteralPath $receiptPath).Hash.ToLowerInvariant();Status='Sealed';Mode=$receipt.Mode;PairId=$receipt.PairId;PlanHash=$receipt.PlanHash;Generation=$receipt.Generation;ManifestHash=$receipt.ManifestHash;BaseManifestHash=$receipt.BaseManifestHash;BaseVerificationStatus=$receipt.BaseVerificationStatus;TransportPath=[IO.Path]::GetFullPath($context.TransportPath);TransportHash=$context.TransportHash;MarkdownPath='delivery.md';MarkdownHash=(Get-FileHash -LiteralPath $markdownPath).Hash.ToLowerInvariant();ReportReferences=$reports;Volumes=@($receipt.Volumes);Members=@($receipt.Members);TotalVolumeBytes=$receipt.TotalVolumeBytes;ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}
    Write-WsmJson $indexPath $index
    [pscustomobject]@{DeliveryId=$deliveryId;ReceiptPath=$receiptPath;ReceiptHash=(Get-FileHash -LiteralPath $receiptPath).Hash.ToLowerInvariant();MarkdownPath=$markdownPath;MarkdownHash=(Get-FileHash -LiteralPath $markdownPath).Hash.ToLowerInvariant();IndexPath=$indexPath;IndexHash=(Get-FileHash -LiteralPath $indexPath).Hash.ToLowerInvariant();Status='Sealed';ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}
}
function Export-WsmImportedDeliveryReceipt {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$TransportPath,[Parameter(Mandatory)][string]$ExpectedHash,[Parameter(Mandatory)][string]$ManifestPath,[Parameter(Mandatory)][string]$ExpectedManifestHash,[Parameter(Mandatory)][string]$OutputDirectory,[string]$BaseManifestPath='',[string]$BaseManifestHash='',[ValidateSet('Full','Delta')][string]$OperationKind='Full',[string]$ImportedDirectory='',[string]$SummaryPath='',[string]$SummaryHash='',[string]$ChangesPath='',[object[]]$ReportReferences=@())
    $context=Get-WsmDeliveryPackageContext $TransportPath $ExpectedHash $ManifestPath $ExpectedManifestHash $BaseManifestPath $BaseManifestHash $OperationKind $ImportedDirectory $SummaryPath $SummaryHash $ChangesPath
    $reports=@(Assert-WsmDeliveryReportReferences $ReportReferences)
    $output=[IO.Path]::GetFullPath($OutputDirectory);Assert-WsmNoReparse $output;if([IO.Directory]::Exists($output) -or [IO.File]::Exists($output)){throw 'Receipt output directory already exists; choose a new exclusive directory.'}
    [void][IO.Directory]::CreateDirectory($output);Protect-WsmDirectory $output
    $deliveryId=[string]$context.DeliveryId;if(-not $deliveryId){$deliveryId=Get-WsmHashText ($context.TransportHash+'|'+$context.Package.Manifest.PackageId);$deliveryId=[Guid]::ParseExact($deliveryId.Substring(0,32),'N').ToString('D')}
    $receipt=New-WsmDeliveryReceiptRecord $context ImportedVerified $deliveryId
    $receiptPath=Join-Path $output 'import-receipt.json';$markdownPath=Join-Path $output 'delivery.md';Write-WsmJson $receiptPath $receipt;Write-WsmDeliveryMarkdown $markdownPath $receipt $reports
    [pscustomobject]@{Path=$receiptPath;SHA256=(Get-FileHash -LiteralPath $receiptPath).Hash.ToLowerInvariant();MarkdownPath=$markdownPath;MarkdownHash=(Get-FileHash -LiteralPath $markdownPath).Hash.ToLowerInvariant();ReceiptId=$receipt.ReceiptId;DeliveryId=$deliveryId;Status='ImportedVerified';ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}
}
function Import-WsmDeliveryReceipt {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$Workspace,[Parameter(Mandatory)][string]$Path,[Parameter(Mandatory)][string]$ExpectedHash)
    $r=Read-WsmTrustedJson $Path $ExpectedHash;Assert-WsmEnvelope $r 'DeliveryReceipt'
    Assert-WsmFields $r @('SchemaVersion','ToolVersion','Kind','ReceiptId','DeliveryId','Status','Mode','OperationKind','MigrationMode','BaseVerificationStatus','PairId','BatchId','SourceHostId','SourceFingerprint','TargetHostId','TargetFingerprint','ToolFingerprint','ApprovalId','PlanHash','Generation','PackageId','ManifestHash','BaseManifestHash','TransportHash','VolumeBytes','Volumes','Members','TotalVolumeBytes','CreatedUtc','ReportOnly','ReadinessProof','ProductionVerified') @('SchemaVersion','ToolVersion','ReceiptId','DeliveryId','Status','Mode','OperationKind','MigrationMode','BaseVerificationStatus','PairId','BatchId','SourceHostId','SourceFingerprint','TargetHostId','TargetFingerprint','ToolFingerprint','ApprovalId','PlanHash','Generation','PackageId','ManifestHash','BaseManifestHash','TransportHash','VolumeBytes','Volumes','Members','TotalVolumeBytes','CreatedUtc','ReportOnly','ReadinessProof','ProductionVerified')
    foreach($id in @($r.ReceiptId,$r.DeliveryId,$r.PairId,$r.SourceHostId,$r.TargetHostId,$r.ApprovalId,$r.PackageId)){Assert-WsmId ([string]$id)}
    foreach($hash in @($r.SourceFingerprint,$r.TargetFingerprint,$r.ToolFingerprint,$r.PlanHash,$r.ManifestHash,$r.TransportHash)){if([string]$hash -notmatch '^[a-fA-F0-9]{64}$'){throw 'Delivery receipt contains an invalid identity hash.'}}
    if($r.Mode -ceq 'Zip' -and $r.OperationKind -ceq 'Full'){$deliveryDigest=Get-WsmHashText ([string]$r.TransportHash+'|'+[string]$r.PackageId);$expectedDeliveryId=[Guid]::ParseExact($deliveryDigest.Substring(0,32),'N').ToString('D');if($r.DeliveryId -cne $expectedDeliveryId){throw 'DeliveryId does not match the sealed transport/package identity.'}}
    if($r.SchemaVersion -ne 1 -or $r.Status -cnotin @('Sealed','ImportedVerified') -or $r.MigrationMode -cne 'IsolatedPilot' -or $r.OperationKind -cnotin @('Full','Delta') -or $r.BaseVerificationStatus -cnotin @('None','ReferenceOnly','VerifiedTrustedBase') -or ($r.OperationKind -ceq 'Delta' -and $r.BaseVerificationStatus -cne 'VerifiedTrustedBase') -or $r.Mode -cnotin @('Zip','Directory') -or $r.Generation -lt 1 -or $r.ReportOnly -isnot [bool] -or -not $r.ReportOnly -or $r.ReadinessProof -isnot [bool] -or $r.ReadinessProof -or $r.ProductionVerified -isnot [bool] -or $r.ProductionVerified -or ($r.Mode -ceq 'Zip' -and (@($r.Volumes).Count -lt 1 -or @($r.Volumes).Count -gt 9999)) -or ($r.Mode -ceq 'Directory' -and @($r.Volumes).Count -ne 0) -or @($r.Members).Count -lt 3 -or @($r.Members).Count -gt 100000){throw 'Receipt is not a bounded report-only Sealed or ImportedVerified receipt.'}
    $total=[long]0;$volumeNames=@{};$volumeIndex=0;foreach($v in @($r.Volumes)){$volumeIndex++;Assert-WsmFields $v @('Name','Number','Bytes','SHA256') @('Name','Number','Bytes','SHA256');$expectedName='package-'+$r.PackageId+'-'+$volumeIndex.ToString('0000')+'.zip';if($r.OperationKind -ceq 'Delta'){$expectedName='delta-'+[regex]::Match([string]$v.Name,'^delta-([0-9a-fA-F-]{36})-').Groups[1].Value+'-'+$volumeIndex.ToString('0000')+'.zip'};if($v.Number -ne $volumeIndex -or $v.Name -cne $expectedName -or $v.SHA256 -notmatch '^[a-fA-F0-9]{64}$' -or $v.Bytes -lt 1 -or $v.Bytes -gt 2GB -or $volumeNames.ContainsKey([string]$v.Name) -or ($r.VolumeBytes -gt 0 -and $v.Bytes -gt $r.VolumeBytes)){throw 'Receipt volume list is invalid or duplicated.'};$volumeNames[[string]$v.Name]=$true;$total+=[long]$v.Bytes};if($r.Mode -ceq 'Zip' -and $total -ne [long]$r.TotalVolumeBytes){throw 'Receipt volume byte summary mismatch.'}
    $memberNames=@{};foreach($member in @($r.Members)){$allowedName=$false;$name=[string]$member.Name;if($r.OperationKind -ceq 'Full'){$allowedName=($name -match '^(?:manifest\.json|plan\.json|artifacts\.jsonl|freeze\.json|payload/[a-f0-9]{64}\.blob)$')}else{$allowedName=($name -match '^(?:delta-volume-index\.json|segments/[0-9]{8}-[a-f0-9]{64}\.blob|base/(?:manifest|plan)\.json|base/artifacts\.jsonl|current/(?:manifest|plan|freeze)\.json|current/artifacts\.jsonl|current/payload/[a-f0-9]{64}\.blob|delta/(?:summary|changes|records|blobs)\.jsonl?)$')};Assert-WsmFields $member @('Name','Bytes','SHA256') @('Name','Bytes','SHA256');if(-not $allowedName -or $memberNames.ContainsKey($name) -or $member.SHA256 -notmatch '^[a-fA-F0-9]{64}$' -or $member.Bytes -lt 0){throw 'Receipt package member list is invalid or duplicated.'};$memberNames[$name]=$true};if($r.OperationKind -ceq 'Full'){foreach($required in @('manifest.json','plan.json','artifacts.jsonl')){if(-not $memberNames.ContainsKey($required)){throw 'Receipt package member list omits required metadata.'}}}else{foreach($required in @('base/manifest.json','base/plan.json','base/artifacts.jsonl','current/manifest.json','current/plan.json','current/artifacts.jsonl','delta/summary.json','delta/changes.jsonl')){if(-not $memberNames.ContainsKey($required)){throw 'Delta receipt member list omits required base/current/delta metadata.'}}}
    $produced=[DateTimeOffset]::MinValue;if(-not [DateTimeOffset]::TryParse([string]$r.CreatedUtc,[ref]$produced) -or $produced.Offset -ne [TimeSpan]::Zero -or $produced -gt [DateTimeOffset]::UtcNow.AddMinutes(5) -or $produced -lt [DateTimeOffset]::UtcNow.AddHours(-24)){throw 'Imported delivery receipt is expired or has an invalid production time.'}
    Invoke-WsmLocked $Workspace {
        $profilePath=Join-Path (Join-Path ([IO.Path]::GetFullPath($Workspace)) 'workspace-control') 'output-profile.json'
        if([IO.File]::Exists($profilePath)){$profile=Read-WsmOutputProfile $Workspace;$managerIdentity=Get-WsmMachineIdentity;if($profile.Role -cne 'Manager' -or $profile.Fingerprint -ine $managerIdentity.Fingerprint){throw 'Delivery receipt import requires a Manager OutputProfile enrolled to this exact manager host.'}}
        $c=Get-WsmCatalog $Workspace ([string]$r.PairId);$a=$c.Approval
        if(-not $a -or -not $a.PSObject.Properties['Kind'] -or $a.Kind -cne 'MigrationPlan' -or $a.Mode -cne 'IsolatedPilot' -or $r.BatchId -cne $c.BatchId -or $r.SourceHostId -cne $c.Source.HostId -or $r.SourceFingerprint -ine $c.Source.Fingerprint -or $r.TargetHostId -cne $a.TargetHostId -or $r.TargetFingerprint -ine $a.TargetFingerprint -or $r.ApprovalId -cne $a.ApprovalId -or $r.PlanHash -ine $a.Hash -or $r.ToolFingerprint -ine (Get-WsmToolFingerprint)){throw 'Receipt does not match the exact current manager approval, tool fingerprint and source/target pair.'}
        if($c.PSObject.Properties['OutputProfile'] -and $c.OutputProfile.PSObject.Properties['PairId'] -and $c.OutputProfile.PairId -cne $r.PairId){throw 'Receipt manager OutputProfile pair binding mismatch.'}
        $receipts=@();if($c.PSObject.Properties['DeliveryReceipts']){$receipts=@($c.DeliveryReceipts)}
        $same=@($receipts | Where-Object DeliveryId -CEQ $r.DeliveryId)
        if($same.Count){if(@($same | Where-Object {($_.TransportHash -ine $r.TransportHash) -or ($_.ManifestHash -ine $r.ManifestHash) -or ($_.BaseManifestHash -ine $r.BaseManifestHash) -or ($_.Generation -ne $r.Generation) -or ($_.OperationKind -cne $r.OperationKind) -or ($_.Mode -cne $r.Mode)}).Count){throw 'Conflicting receipt for this DeliveryId.'}}
        if(@($receipts | Where-Object ReceiptId -CEQ $r.ReceiptId).Count){throw 'Duplicate ReceiptId; the existing receipt remains authoritative.'}
        $stageOrder=@{Sealed=1;ImportedVerified=2};$sameStage=@($same | Where-Object Status -CEQ $r.Status);if($sameStage.Count){throw 'Duplicate delivery receipt stage; the existing receipt remains authoritative.'};if(@($same | Where-Object {$stageOrder[[string]$_.Status] -gt $stageOrder[[string]$r.Status]}).Count){throw 'A receipt stage cannot move backwards from ImportedVerified to Sealed.'}
        $sameGeneration=@($receipts | Where-Object {$_.ApprovalId -ceq $r.ApprovalId -and $_.Generation -eq $r.Generation})
        if(@($sameGeneration | Where-Object {$_.ManifestHash -ine $r.ManifestHash -or $_.BaseManifestHash -ine $r.BaseManifestHash}).Count){throw 'Conflicting manifest/base binding for the same approved generation.'}
        $newer=@($receipts | Where-Object {$_.ApprovalId -ceq $r.ApprovalId -and $_.Generation -gt $r.Generation});if($newer.Count){throw 'Stale delivery generation receipt refused.'}
        Assert-WsmTrustedFile $Path $ExpectedHash;$receiptHash=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant();if($receiptHash -ine $ExpectedHash){throw 'Delivery receipt changed during manager import.'};$summary=[pscustomobject][ordered]@{ReceiptId=$r.ReceiptId;DeliveryId=$r.DeliveryId;Status=[string]$r.Status;OperationKind=$r.OperationKind;BaseVerificationStatus=$r.BaseVerificationStatus;Mode=$r.Mode;PairId=$r.PairId;SourceHostId=$r.SourceHostId;TargetHostId=$r.TargetHostId;ApprovalId=$r.ApprovalId;PlanHash=$r.PlanHash;Generation=[int]$r.Generation;PackageId=$r.PackageId;ManifestHash=$r.ManifestHash;BaseManifestHash=$r.BaseManifestHash;TransportHash=$r.TransportHash;VolumeCount=@($r.Volumes).Count;TotalVolumeBytes=[long]$r.TotalVolumeBytes;ReceiptHash=$receiptHash;ImportedUtc=(Get-WsmUtc);ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}
        $receipts+=,$summary;$c | Add-Member NoteProperty DeliveryReceipts $receipts -Force;Write-WsmJson (Get-WsmCatalogPath $Workspace $r.PairId) $c
        [pscustomobject]@{PairId=$r.PairId;DeliveryId=$r.DeliveryId;Status=[string]$r.Status;Generation=[int]$r.Generation;ReceiptHash=$receiptHash;ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}
    }
}
function Get-WsmDeliveryReceiptSummary($Catalog) {
    $receipts=@();if($Catalog.PSObject.Properties['DeliveryReceipts']){$receipts=@($Catalog.DeliveryReceipts)}
    if(-not $Catalog -or -not $Catalog.PSObject.Properties['Approval'] -or -not $Catalog.Approval){return [pscustomobject]@{Status='NoApproval';Mode='';Generation=0;VolumeCount=0;TotalVolumeBytes=0;TransportHash='';DeliveryId='';ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}}
    $current=@($receipts | Where-Object {$_.ApprovalId -ceq $Catalog.Approval.ApprovalId -and $_.PlanHash -ieq $Catalog.Approval.Hash -and $_.SourceHostId -ceq $Catalog.Source.HostId -and $_.TargetHostId -ceq $Catalog.Approval.TargetHostId})
    if(-not $current.Count){$status=if($receipts.Count){'OldApproval'}else{'NoReceipt'};return [pscustomobject]@{Status=$status;Mode='';Generation=0;VolumeCount=0;TotalVolumeBytes=0;TransportHash='';DeliveryId='';ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}}
    $latestGeneration=($current | Measure-Object Generation -Maximum).Maximum;$r=$null
    $latest=@($current | Where-Object Generation -EQ $latestGeneration)
    if($Catalog.PSObject.Properties['Generation'] -and $Catalog.Generation -gt 0 -and $latestGeneration -lt $Catalog.Generation){$status='Stale'}
    else{$verified=@($latest | Where-Object Status -CEQ 'ImportedVerified' | Sort-Object ImportedUtc -Descending);if($verified.Count){$r=$verified[0];$status='ImportedVerified'}else{$sealed=@($latest | Where-Object Status -CEQ 'Sealed' | Sort-Object ImportedUtc -Descending);if($sealed.Count){$r=$sealed[0];$status='Sealed'}else{$r=$null;$status='Stale'}}}
    if(-not $r){return [pscustomobject]@{Status=$status;Mode='';Generation=[int]$latestGeneration;VolumeCount=0;TotalVolumeBytes=0;TransportHash='';DeliveryId='';ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}}
    [pscustomobject]@{Status=$status;Mode=$r.Mode;Generation=$r.Generation;VolumeCount=$r.VolumeCount;TotalVolumeBytes=$r.TotalVolumeBytes;TransportHash=$r.TransportHash;DeliveryId=$r.DeliveryId;ReportOnly=$true;ReadinessProof=$false;ProductionVerified=$false}
}
