function Initialize-WsmDeltaPlainMerge {
    if('WsmDeltaPlainMerge' -as [type]){return}
    Add-Type -TypeDefinition @'
using System;
using System.IO;
using System.Text;
public static class WsmDeltaPlainMerge {
    public static void Merge(string[] paths,string output){
        if(paths.Length<1 || paths.Length>64)throw new InvalidDataException("Delta hash merge fan-in must be 1..64.");
        var readers=new StreamReader[paths.Length];var heads=new string[paths.Length];
        try{for(int n=0;n<paths.Length;n++){readers[n]=new StreamReader(paths[n],Encoding.ASCII);heads[n]=readers[n].ReadLine();}
            using(var writer=new StreamWriter(output,false,Encoding.ASCII)){while(true){int best=-1;for(int n=0;n<heads.Length;n++){if(heads[n]!=null&&(best<0||StringComparer.Ordinal.Compare(heads[n],heads[best])<0))best=n;}if(best<0)break;writer.WriteLine(heads[best]);heads[best]=readers[best].ReadLine();}}
        }finally{foreach(var reader in readers){if(reader!=null)reader.Dispose();}}
    }
}
'@
}
function Save-WsmDeltaTextRun($State) {
    if(-not $State.Buffer.Count){return};$State.Buffer.Sort([StringComparer]::Ordinal);$path=Join-Path $State.Root ('hashes-'+$State.Serial+'.txt');$State.Serial++
    [IO.File]::WriteAllLines($path,[string[]]$State.Buffer.ToArray(),[Text.Encoding]::ASCII);$State.Runs.Add($path);$State.Known.Add($path);$State.Buffer.Clear()
}
function Add-WsmDeltaTextRun($State,[string]$Line) { $State.Buffer.Add($Line);if($State.Buffer.Count -ge 5000){Save-WsmDeltaTextRun $State} }
function Merge-WsmDeltaTextRuns($State) {
    Save-WsmDeltaTextRun $State
    while($State.Runs.Count -gt 1){$next=New-Object 'System.Collections.Generic.List[string]';for($n=0;$n -lt $State.Runs.Count;$n+=64){$last=[Math]::Min($n+63,$State.Runs.Count-1);$group=@(for($i=$n;$i -le $last;$i++){$State.Runs[$i]});$merged=Join-Path $State.Root ('merged-'+$State.Serial+'.txt');$State.Serial++;Initialize-WsmDeltaPlainMerge;[WsmDeltaPlainMerge]::Merge([string[]]$group,$merged);$State.Known.Add($merged);$next.Add($merged);foreach($part in $group){[IO.File]::Delete($part)}};$State.Runs=$next}
    if($State.Runs.Count){$State.Runs[0]}else{$null}
}
function Add-WsmDeltaZipFile($Archive,[string]$Name,[string]$Path,$CancellationToken=$null) {
    Assert-WsmNoReparse $Path;$entry=$Archive.CreateEntry($Name,[IO.Compression.CompressionLevel]::NoCompression);$input=[IO.File]::Open($Path,'Open','Read','Read');$output=$entry.Open()
    try{$buffer=New-Object byte[] 65536;while(($read=$input.Read($buffer,0,$buffer.Length)) -gt 0){Assert-WsmCancellationBoundary $CancellationToken 'DeltaExportZipMember';$output.Write($buffer,0,$read)}}finally{$output.Dispose();$input.Dispose()}
}
function Copy-WsmDeltaZipEntry($Entry,[string]$Destination,[string]$ExpectedHash,[long]$ExpectedBytes,$CancellationToken=$null) {
    if($Entry.Length -ne $ExpectedBytes -or $ExpectedBytes -gt 128GB){throw 'Delta transport member size mismatch/limit.'}
    Assert-WsmNoReparse $Destination;$parent=[IO.Path]::GetDirectoryName($Destination);if(-not [IO.Directory]::Exists($parent)){[void][IO.Directory]::CreateDirectory($parent)}
    $temp=$Destination+'.'+[Guid]::NewGuid().ToString('N')+'.partial';$source=$Entry.Open();$output=[IO.File]::Open($temp,'CreateNew','Write','None');$sha=[Security.Cryptography.SHA256]::Create();$length=[long]0
    try{$buffer=New-Object byte[] 65536;while(($n=$source.Read($buffer,0,$buffer.Length)) -gt 0){Assert-WsmCancellationBoundary $CancellationToken 'DeltaImportZipMember';$length+=$n;if($length -gt $ExpectedBytes){throw 'Delta ZIP expansion exceeds member size.'};[void]$sha.TransformBlock($buffer,0,$n,$buffer,0);$output.Write($buffer,0,$n)};[void]$sha.TransformFinalBlock((New-Object byte[] 0),0,0);$output.Flush($true);$hash=[BitConverter]::ToString($sha.Hash).Replace('-','').ToLowerInvariant();if($length -ne $ExpectedBytes -or $hash -ine $ExpectedHash){throw 'Delta ZIP member hash/length mismatch.'}}finally{$source.Dispose();$output.Dispose();$sha.Dispose()}
    [IO.File]::Move($temp,$Destination)
}
function Copy-WsmDeltaFileCancellable([string]$Source,[string]$Destination,$CancellationToken=$null,[string]$Phase='DeltaPackageCopy') {
    Assert-WsmNoReparse $Source;Assert-WsmNoReparse $Destination;$parent=[IO.Path]::GetDirectoryName($Destination);if(-not [IO.Directory]::Exists($parent)){[void][IO.Directory]::CreateDirectory($parent)}
    $input=[IO.File]::Open($Source,'Open','Read','Read');$output=[IO.File]::Open($Destination,'CreateNew','Write','None')
    try{$buffer=New-Object byte[] 65536;while(($read=$input.Read($buffer,0,$buffer.Length)) -gt 0){Assert-WsmCancellationBoundary $CancellationToken $Phase;$output.Write($buffer,0,$read)};$output.Flush($true)}finally{$input.Dispose();$output.Dispose()}
}
function Get-WsmDeltaFileHashCancellable([string]$Path,$CancellationToken=$null,[string]$Phase='DeltaHash') {
    $stream=[IO.File]::Open([IO.Path]::GetFullPath($Path),'Open','Read','Read');$sha=[Security.Cryptography.SHA256]::Create()
    try{$buffer=New-Object byte[] 1048576;while(($read=$stream.Read($buffer,0,$buffer.Length)) -gt 0){Assert-WsmCancellationBoundary $CancellationToken $Phase;[void]$sha.TransformBlock($buffer,0,$read,$buffer,0)};[void]$sha.TransformFinalBlock((New-Object byte[] 0),0,0);[BitConverter]::ToString($sha.Hash).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose();$stream.Dispose()}
}
function New-WsmDeltaBoundedRowSpool([string]$Source,[string]$ExpectedHash,[string]$TempRoot,$CancellationToken=$null,[string]$Phase='DeltaBoundedSpool') {
    $reader=New-Object IO.StreamReader([IO.Path]::GetFullPath($Source),[Text.Encoding]::UTF8,$true);$destination=Join-Path $TempRoot ([Guid]::NewGuid().ToString('N')+'.jsonl');$writer=New-Object IO.StreamWriter($destination,$false,(New-Object Text.UTF8Encoding($false)))
    try{Read-WsmBoundedLines $reader 1048576 | ForEach-Object {Assert-WsmCancellationBoundary $CancellationToken $Phase;$writer.WriteLine($_)}}finally{$reader.Dispose();$writer.Dispose()}
    if((Get-WsmDeltaFileHash $Source) -ine $ExpectedHash){[IO.File]::Delete($destination);throw 'Delta row source changed while its bounded spool was being created.'};$destination
}
function Get-WsmDeltaRecordLookup($Package,$ChangesPath,[string]$WorkRoot) {
    $state=[pscustomobject]@{Root=$WorkRoot;Serial=0;Buffer=(New-Object 'System.Collections.Generic.List[string]');Runs=(New-Object 'System.Collections.Generic.List[string]');Known=(New-Object 'System.Collections.Generic.List[string]')}
    $sorted=Read-WsmDeltaSortedIndex (Join-Path $Package.Root 'artifacts.jsonl') $Package.Manifest.ArtifactsHash $Package.Plan $state
    $recordsPath=Join-Path $WorkRoot 'records.jsonl';$recordWriter=New-Object IO.StreamWriter($recordsPath,$false,(New-Object Text.UTF8Encoding($false)))
    $hashRoot=Join-Path $WorkRoot 'hash-runs';[void][IO.Directory]::CreateDirectory($hashRoot);$hashState=[pscustomobject]@{Root=$hashRoot;Serial=0;Buffer=(New-Object 'System.Collections.Generic.List[string]');Runs=(New-Object 'System.Collections.Generic.List[string]');Known=(New-Object 'System.Collections.Generic.List[string]')}
    $changeReader=New-Object IO.StreamReader($ChangesPath,[Text.Encoding]::UTF8,$true);$rowReader=$null;$recordCount=[long]0
    try{
        if($sorted.Path){$rowReader=New-Object IO.StreamReader($sorted.Path,[Text.Encoding]::ASCII)}
        $rowLine=$null;if($rowReader){$rowLine=$rowReader.ReadLine()}
        Read-WsmBoundedLines $changeReader 1048576 | ForEach-Object {
            $change=ConvertFrom-WsmJson $_;$changeKey=ConvertTo-WsmDeltaKeyHex $change.ItemId $change.RelativePath
            if($null -eq $rowLine){if($change.Change -in @('Added','Modified','MetadataOnly')){throw 'Delta references missing current record.'}}
            else{
                $spool=Read-WsmDeltaSpoolRow $rowLine;$compare=[StringComparer]::Ordinal.Compare($changeKey,$spool.Key)
                if($compare -lt 0){if($change.Change -ne 'Deleted'){throw 'Delta changes contain a non-delete without a current record.'}}
                elseif($compare -gt 0){throw 'Current artifact index record is absent from delta changes.'}
                else{
                    $item=@($Package.Plan.Items | Where-Object ItemId -CEQ $spool.Row.ItemId);$sendCertificate=($change.Change -eq 'Unchanged' -and $item.Count -eq 1 -and $item[0].MigrationSpec.Adapter -eq 'Certificate')
                    if($change.Change -in @('Added','Modified','MetadataOnly') -or $sendCertificate){
                        $parts=Get-WsmDeltaRecordParts $spool.Row;if($parts.RecordHash -cne $change.CurrentRecordHash){throw 'Delta current record hash differs from current index.'}
                        $recordWriter.WriteLine((ConvertTo-Json -InputObject ([pscustomobject][ordered]@{Change=$change.Change;Record=$spool.Row}) -Depth 25 -Compress))
                        $recordCount++
                        if(($change.Change -in @('Added','Modified') -or $sendCertificate) -and -not $spool.Row.Directory){foreach($chunk in $spool.Row.Data.Chunks){Add-WsmDeltaTextRun $hashState ([string]$chunk.Hash+'|'+([long]$chunk.Bytes).ToString([Globalization.CultureInfo]::InvariantCulture))}}
                    }
                    $rowLine=$rowReader.ReadLine()
                }
            }
        }
        if($null -ne $rowLine){throw 'Current artifact index record is absent from delta changes.'}
        $recordWriter.Flush()
    }finally{$recordWriter.Dispose();$changeReader.Dispose();if($rowReader){$rowReader.Dispose()}}
    foreach($path in $state.Known){if([IO.File]::Exists($path)){[IO.File]::Delete($path)}}
    [pscustomobject]@{RecordsPath=$recordsPath;RecordCount=$recordCount;HashRuns=$hashState}
}
function Export-WsmArtifactDeltaZip {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$BaseManifestPath,[Parameter(Mandatory)][string]$BaseManifestHash,[Parameter(Mandatory)][string]$BasePlanPath,[Parameter(Mandatory)][string]$BasePlanHash,[Parameter(Mandatory)][string]$CurrentManifestPath,[Parameter(Mandatory)][string]$CurrentManifestHash,[Parameter(Mandatory)][string]$CurrentPlanPath,[Parameter(Mandatory)][string]$CurrentPlanHash,[Parameter(Mandatory)][string]$SummaryPath,[Parameter(Mandatory)][string]$SummaryHash,[Parameter(Mandatory)][string]$ChangesPath,[Parameter(Mandatory)][string]$OutputPath,$CancellationToken=$null)
    $checked=Test-WsmArtifactDeltaManifest -SummaryPath $SummaryPath -SummaryHash $SummaryHash -ChangesPath $ChangesPath -BaseManifestPath $BaseManifestPath -BaseManifestHash $BaseManifestHash -BasePlanPath $BasePlanPath -BasePlanHash $BasePlanHash -CurrentManifestPath $CurrentManifestPath -CurrentManifestHash $CurrentManifestHash -CurrentPlanPath $CurrentPlanPath -CurrentPlanHash $CurrentPlanHash
    if([IO.Path]::GetFileName($ChangesPath) -cne 'changes.jsonl'){throw 'Delta transport requires the fixed changes.jsonl member name.'}
    $base=Read-WsmDeltaInput $BaseManifestPath $BaseManifestHash $BasePlanPath $BasePlanHash;$current=Read-WsmDeltaInput $CurrentManifestPath $CurrentManifestHash $CurrentPlanPath $CurrentPlanHash
    $out=[IO.Path]::GetFullPath($OutputPath);if([IO.File]::Exists($out)){throw 'Delta transport output already exists.'};Assert-WsmNoReparse $out;$outDir=[IO.Path]::GetDirectoryName($out)
    if($CancellationToken){[void](Assert-WsmCancellationTokenBinding $CancellationToken $checked.Summary.PairId $CurrentPlanHash $CurrentManifestHash $outDir)}
    Assert-WsmCancellationBoundary $CancellationToken 'DeltaExportStart'
    $root=Join-Path ([IO.Path]::GetTempPath()) ('wsm-delta-zip-'+[Guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($root);Protect-WsmDirectory $root
    if(-not [IO.Directory]::Exists($outDir)){[void][IO.Directory]::CreateDirectory($outDir)}
    $stage=Get-WsmDeltaRecordLookup ([pscustomobject]@{Root=(Split-Path -Parent $current.IndexPath);Manifest=$current.Manifest;Plan=$current.Plan}) $ChangesPath $root
    $hashFile=Merge-WsmDeltaTextRuns $stage.HashRuns;$blobPath=Join-Path $root 'blobs.bin';$blobIndexPath=Join-Path $root 'blobs.jsonl';$blobWriter=New-Object IO.StreamWriter($blobIndexPath,$false,(New-Object Text.UTF8Encoding($false)));$blobOutput=[IO.File]::Open($blobPath,'CreateNew','Write','None');$offset=[long]0
    try{if($hashFile){$hashReader=New-Object IO.StreamReader($hashFile,[Text.Encoding]::ASCII);try{$previousHash='';while($null -ne ($line=$hashReader.ReadLine())){Assert-WsmCancellationBoundary $CancellationToken 'DeltaExportPayloadChunk';$p=$line.Split('|');if($p.Count -ne 2 -or $p[0] -notmatch '^[a-f0-9]{64}$' -or $p[0] -ceq $previousHash){throw 'Duplicate/malformed chunk hash in delta spool.'};$previousHash=$p[0];$blob=Join-Path (Join-Path ([IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($CurrentManifestPath))) 'payload') ($p[0]+'.blob');Assert-WsmNoReparse $blob;$length=[long]$p[1];if($length -lt 1 -or $length -gt $current.Manifest.ChunkBytes -or (New-Object IO.FileInfo($blob)).Length -ne $length -or (Get-WsmDeltaFileHash $blob) -ine $p[0]){throw 'Changed delta payload chunk is corrupt.'};$blobWriter.WriteLine((ConvertTo-Json -InputObject ([pscustomobject][ordered]@{Hash=$p[0];Bytes=$length;Offset=$offset}) -Compress));$input=[IO.File]::Open($blob,'Open','Read','Read');try{$buffer=New-Object byte[] 65536;while(($read=$input.Read($buffer,0,$buffer.Length)) -gt 0){Assert-WsmCancellationBoundary $CancellationToken 'DeltaExportPayloadBytes';$blobOutput.Write($buffer,0,$read)}}finally{$input.Dispose()};$offset+=$length}}finally{$hashReader.Dispose()}};$blobOutput.Flush($true)}finally{$blobWriter.Dispose();$blobOutput.Dispose()}
    $baseRoot=[IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($BaseManifestPath));$currentRoot=[IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($CurrentManifestPath));$members=@(
        [pscustomobject]@{Name='base/manifest.json';Path=$BaseManifestPath},[pscustomobject]@{Name='base/plan.json';Path=$BasePlanPath},[pscustomobject]@{Name='base/artifacts.jsonl';Path=(Join-Path $baseRoot 'artifacts.jsonl')},
        [pscustomobject]@{Name='current/manifest.json';Path=$CurrentManifestPath},[pscustomobject]@{Name='current/plan.json';Path=$CurrentPlanPath},[pscustomobject]@{Name='current/artifacts.jsonl';Path=(Join-Path $currentRoot 'artifacts.jsonl')},[pscustomobject]@{Name='current/freeze.json';Path=(Join-Path $currentRoot 'freeze.json')},
        [pscustomobject]@{Name='delta/summary.json';Path=$SummaryPath},[pscustomobject]@{Name='delta/changes.jsonl';Path=$ChangesPath},[pscustomobject]@{Name='delta/records.jsonl';Path=$stage.RecordsPath},[pscustomobject]@{Name='delta/blobs.jsonl';Path=$blobIndexPath},[pscustomobject]@{Name='delta/blobs.bin';Path=$blobPath})
    $transport=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='ArtifactDeltaTransport';PairId=$checked.Summary.PairId;PlanHash=$checked.Summary.PlanHash;BaseManifestHash=$BaseManifestHash.ToLowerInvariant();CurrentManifestHash=$CurrentManifestHash.ToLowerInvariant();SummaryHash=$SummaryHash.ToLowerInvariant();ChangesHash=(Get-WsmDeltaFileHash $ChangesPath);Members=@(foreach($member in $members){if(-not [IO.File]::Exists($member.Path)){throw ('Required delta member missing: '+$member.Path)};[pscustomobject]@{Name=$member.Name;Bytes=(New-Object IO.FileInfo($member.Path)).Length;SHA256=(Get-WsmDeltaFileHash $member.Path)}});BlobBytes=$offset;CreatedUtc=(Get-WsmUtc);Mode='IsolatedPilot'}
    $transportPath=Join-Path $root 'transport.json';Write-WsmJson $transportPath $transport
    $temp=$out+'.'+[Guid]::NewGuid().ToString('N')+'.partial';$file=[IO.File]::Open($temp,'CreateNew','ReadWrite','None');$archive=$null
    try{Add-Type -AssemblyName System.IO.Compression;$archive=New-Object IO.Compression.ZipArchive($file,[IO.Compression.ZipArchiveMode]::Create,$true);Add-WsmDeltaZipFile $archive 'transport.json' $transportPath $CancellationToken;foreach($member in $members){Assert-WsmCancellationBoundary $CancellationToken 'DeltaExportMember';Add-WsmDeltaZipFile $archive $member.Name $member.Path $CancellationToken};$archive.Dispose();$archive=$null;$file.Flush($true)}finally{if($archive){$archive.Dispose()};$file.Dispose()}
    try{[IO.File]::Move($temp,$out)}finally{if([IO.File]::Exists($temp)){[IO.File]::Delete($temp)}}
    foreach($path in @($stage.RecordsPath,$blobPath,$blobIndexPath,$transportPath)+@($stage.HashRuns.Known)){if($path -and [IO.File]::Exists($path)){[IO.File]::Delete($path)}}
    foreach($path in @($hashFile)){if($path -and [IO.File]::Exists($path)){[IO.File]::Delete($path)}}
    foreach($path in $stage.HashRuns.Known){if([IO.File]::Exists($path)){[IO.File]::Delete($path)}}
    [IO.Directory]::Delete((Join-Path $root 'hash-runs'),$true);[IO.Directory]::Delete($root,$false)
    [pscustomobject]@{Path=$out;SHA256=(Get-WsmDeltaFileHash $out);Bytes=(New-Object IO.FileInfo($out)).Length;PairId=$transport.PairId;BaseManifestHash=$transport.BaseManifestHash;CurrentManifestHash=$transport.CurrentManifestHash;ChangedRecords=$stage.RecordCount;Mode='IsolatedPilot'}
}
function Test-WsmDeltaTransportContents([string]$Root,$Transport,$CancellationToken=$null) {
    Assert-WsmEnvelope $Transport 'ArtifactDeltaTransport';Assert-WsmId $Transport.PairId
    if($Transport.PlanHash -notmatch '^[a-f0-9]{64}$' -or $Transport.BaseManifestHash -notmatch '^[a-f0-9]{64}$' -or $Transport.CurrentManifestHash -notmatch '^[a-f0-9]{64}$' -or $Transport.SummaryHash -notmatch '^[a-f0-9]{64}$' -or $Transport.ChangesHash -notmatch '^[a-f0-9]{64}$'){throw 'Invalid delta transport binding hashes.'}
    $expectedNames=@('base/manifest.json','base/plan.json','base/artifacts.jsonl','current/manifest.json','current/plan.json','current/artifacts.jsonl','current/freeze.json','delta/summary.json','delta/changes.jsonl','delta/records.jsonl','delta/blobs.jsonl','delta/blobs.bin')
    if($Transport.Members.Count -ne $expectedNames.Count){throw 'Delta transport member list is incomplete.'};$memberMap=@{}
    foreach($member in $Transport.Members){Assert-WsmCancellationBoundary $CancellationToken 'DeltaTransportMember';Assert-WsmFields $member @('Name','Bytes','SHA256') @('Name','Bytes','SHA256');if($expectedNames -cnotcontains $member.Name -or $memberMap.ContainsKey([string]$member.Name) -or $member.SHA256 -notmatch '^[a-f0-9]{64}$' -or $member.Bytes -lt 0){throw 'Delta transport contains an unsafe/duplicate member descriptor.'};$memberMap[[string]$member.Name]=$member}
    foreach($name in $expectedNames){Assert-WsmCancellationBoundary $CancellationToken 'DeltaTransportMemberHash';if(-not $memberMap.ContainsKey($name)){throw ('Delta transport missing member descriptor: '+$name)};$relative=$name.Replace('/','\');$path=Join-Path $Root $relative;Assert-WsmNoReparse $path;if(-not [IO.File]::Exists($path) -or (New-Object IO.FileInfo($path)).Length -ne $memberMap[$name].Bytes -or (Get-WsmDeltaFileHashCancellable $path $CancellationToken 'DeltaTransportMemberHash') -ine $memberMap[$name].SHA256){throw ('Delta transport member hash/size mismatch: '+$name)}}
    if((Get-WsmDeltaFileHashCancellable (Join-Path $Root 'delta\changes.jsonl') $CancellationToken 'DeltaTransportChangesHash') -ine $Transport.ChangesHash){throw 'Delta changes do not match transport binding.'}
    $baseManifest=Join-Path $Root 'base\manifest.json';$basePlan=Join-Path $Root 'base\plan.json';$currentManifest=Join-Path $Root 'current\manifest.json';$currentPlan=Join-Path $Root 'current\plan.json';$summary=Join-Path $Root 'delta\summary.json';$changes=Join-Path $Root 'delta\changes.jsonl'
    $base=Read-WsmTrustedJson $baseManifest $Transport.BaseManifestHash;$current=Read-WsmTrustedJson $currentManifest $Transport.CurrentManifestHash
    if($base.PlanHash -ine $Transport.PlanHash -or $current.PlanHash -ine $Transport.PlanHash -or $base.PairId -cne $Transport.PairId -or $current.PairId -cne $Transport.PairId){throw 'Transport manifest pair/plan binding mismatch.'}
    $currentApprovedPlan=Read-WsmTrustedJson $currentPlan $Transport.PlanHash
    if((Get-WsmDeltaFileHashCancellable (Join-Path $Root 'current\freeze.json') $CancellationToken 'DeltaTransportFreezeHash') -ine $current.FreezeHash){throw 'Final freeze record hash mismatch in delta transport.'}
    [void](Read-WsmFreezeRecord (Join-Path $Root 'current\freeze.json') $current.FreezeHash $currentApprovedPlan $Transport.PlanHash)
    $validated=Test-WsmArtifactDeltaManifest -SummaryPath $summary -SummaryHash $Transport.SummaryHash -ChangesPath $changes -BaseManifestPath $baseManifest -BaseManifestHash $Transport.BaseManifestHash -BasePlanPath $basePlan -BasePlanHash $Transport.PlanHash -CurrentManifestPath $currentManifest -CurrentManifestHash $Transport.CurrentManifestHash -CurrentPlanPath $currentPlan -CurrentPlanHash $Transport.PlanHash
    $recordsPath=Join-Path $Root 'delta\records.jsonl';$spoolRoot=Join-Path ([IO.Path]::GetTempPath()) ('wsm-delta-bounded-'+[Guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($spoolRoot);$changesSpool=$null;$recordsSpool=$null;$changesReader=$null;$recordsReader=$null
    $payloadRoot=Join-Path $Root 'current\payload'
    try{$changesSpool=New-WsmDeltaBoundedRowSpool $changes $Transport.ChangesHash $spoolRoot $CancellationToken 'DeltaTransportChangeSpool';$recordsSpool=New-WsmDeltaBoundedRowSpool $recordsPath $memberMap['delta/records.jsonl'].SHA256 $spoolRoot $CancellationToken 'DeltaTransportRecordSpool';$changesReader=New-Object IO.StreamReader($changesSpool,[Text.Encoding]::UTF8,$true);$recordsReader=New-Object IO.StreamReader($recordsSpool,[Text.Encoding]::UTF8,$true);$recordLine=$recordsReader.ReadLine();while($null -ne ($changeLine=$changesReader.ReadLine())){Assert-WsmCancellationBoundary $CancellationToken 'DeltaTransportChangeRow';$change=ConvertFrom-WsmJson $changeLine;$planItem=@($currentApprovedPlan.Items | Where-Object ItemId -CEQ $change.ItemId);$sendCertificate=($change.Change -eq 'Unchanged' -and $planItem.Count -eq 1 -and $planItem[0].MigrationSpec.Adapter -eq 'Certificate');if($change.Change -in @('Added','Modified','MetadataOnly') -or $sendCertificate){if($null -eq $recordLine){throw 'Transport omits a changed current artifact record.'};$recordEnvelope=ConvertFrom-WsmJson $recordLine;Assert-WsmFields $recordEnvelope @('Change','Record') @('Change','Record');if($recordEnvelope.Change -cne $change.Change){throw 'Transport record operation differs from delta.'};$row=$recordEnvelope.Record;$key=ConvertTo-WsmDeltaKeyHex $row.ItemId $row.RelativePath;if($key -cne (ConvertTo-WsmDeltaKeyHex $change.ItemId $change.RelativePath) -or (Get-WsmDeltaRecordParts $row).RecordHash -cne $change.CurrentRecordHash){throw 'Transport changed record does not match the delta/index binding.'};if(($change.Change -in @('Added','Modified') -or $sendCertificate) -and -not $row.Directory -and [IO.Directory]::Exists($payloadRoot)){foreach($chunk in $row.Data.Chunks){Assert-WsmCancellationBoundary $CancellationToken 'DeltaTransportChunk';$blob=Join-Path $payloadRoot ($chunk.Hash+'.blob');if(-not [IO.File]::Exists($blob) -or (New-Object IO.FileInfo($blob)).Length -ne $chunk.Bytes -or (Get-WsmDeltaFileHash $blob) -ine $chunk.Hash){throw 'Changed/certificate record references a missing/untrusted payload chunk.'}}};$recordLine=$recordsReader.ReadLine()}};if($null -ne $recordLine){throw 'Transport contains an unreferenced changed record.'}}
    finally{if($changesReader){$changesReader.Dispose()};if($recordsReader){$recordsReader.Dispose()};if($changesSpool -and [IO.File]::Exists($changesSpool)){[IO.File]::Delete($changesSpool)};if($recordsSpool -and [IO.File]::Exists($recordsSpool)){[IO.File]::Delete($recordsSpool)};if([IO.Directory]::Exists($spoolRoot)){[IO.Directory]::Delete($spoolRoot,$true)}}
    [pscustomobject]@{Valid=$true;Transport=$Transport;BaseManifest=$base;CurrentManifest=$current;Summary=$validated.Summary;ChangedRecords=$validated.Summary.Counts.Added+$validated.Summary.Counts.Modified+$validated.Summary.Counts.MetadataOnly;Root=[IO.Path]::GetFullPath($Root)}
}
function Import-WsmArtifactDeltaZip {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$TransportPath,[Parameter(Mandatory)][string]$ExpectedHash,[Parameter(Mandatory)][string]$OutputDirectory,$CancellationToken=$null)
    if($ExpectedHash -notmatch '^[a-fA-F0-9]{64}$' -or (Get-WsmDeltaFileHash $TransportPath) -ine $ExpectedHash){throw 'Independent delta transport SHA256 mismatch.'};Assert-WsmNoReparse $TransportPath
    $stream=[IO.File]::Open([IO.Path]::GetFullPath($TransportPath),'Open','Read','Read');$archive=$null;$root=$null
    try{Add-Type -AssemblyName System.IO.Compression;$archive=New-Object IO.Compression.ZipArchive($stream,[IO.Compression.ZipArchiveMode]::Read,$true);if($archive.Entries.Count -ne 13){throw 'Delta ZIP must contain the exact fixed member set.'};$entries=@{};foreach($entry in $archive.Entries){if($entry.FullName -match '[/\\]$' -or $entries.ContainsKey($entry.FullName) -or ($entry.ExternalAttributes -band 0xF000) -eq 0xA000){throw 'Delta ZIP has duplicate, directory or link entries.'};$entries[$entry.FullName]=$entry};if(-not $entries.ContainsKey('transport.json')){throw 'Delta ZIP lacks its binding record.'};if($entries['transport.json'].Length -gt 1MB){throw 'Delta transport record too large.'};$reader=New-Object IO.StreamReader($entries['transport.json'].Open(),[Text.Encoding]::UTF8,$true);try{$transport=ConvertFrom-WsmJson $reader.ReadToEnd()}finally{$reader.Dispose()}
        $baseExpected=@('base/manifest.json','base/plan.json','base/artifacts.jsonl','current/manifest.json','current/plan.json','current/artifacts.jsonl','current/freeze.json','delta/summary.json','delta/changes.jsonl','delta/records.jsonl','delta/blobs.jsonl','delta/blobs.bin');if($entries.Count -ne ($baseExpected.Count+1)){throw 'Delta ZIP entry set is not exact.'};foreach($name in $baseExpected){if(-not $entries.ContainsKey($name)){throw ('Delta ZIP member missing: '+$name)}}
        Assert-WsmEnvelope $transport 'ArtifactDeltaTransport';Assert-WsmId $transport.PairId;if($transport.PlanHash -notmatch '^[a-f0-9]{64}$' -or $transport.CurrentManifestHash -notmatch '^[a-f0-9]{64}$'){throw 'Delta ZIP transport lacks trusted plan/current-manifest bindings.'}
        $output=[IO.Path]::GetFullPath($OutputDirectory);Assert-WsmNoReparse $output
        if($CancellationToken){[void](Assert-WsmCancellationTokenBinding $CancellationToken $transport.PairId $transport.PlanHash $transport.CurrentManifestHash $output)}
        Assert-WsmCancellationBoundary $CancellationToken 'DeltaImportStart'
        if(-not [IO.Directory]::Exists($output)){[void][IO.Directory]::CreateDirectory($output);Protect-WsmDirectory $output}
        $root=Join-Path $output ('delta-'+[string]$transport.CurrentManifestHash);$maximumPayloadPath=Join-Path (Join-Path $root 'current\payload') (('f'*64)+'.blob');if($maximumPayloadPath.Length -gt 239){throw 'Delta import directory is too deep for the verified Windows PowerShell path limit; select a shorter local output directory.'};if([IO.Directory]::Exists($root)){throw 'Delta import root already exists; preserve and inspect previous import.'};[void][IO.Directory]::CreateDirectory($root);Protect-WsmDirectory $root
        $transportPathOut=Join-Path $root 'transport.json';$transportBytes=New-Object IO.MemoryStream;$transportInput=$entries['transport.json'].Open();try{$transportInput.CopyTo($transportBytes);[IO.File]::WriteAllBytes($transportPathOut,$transportBytes.ToArray())}finally{$transportInput.Dispose();$transportBytes.Dispose()}
        foreach($member in $transport.Members){Assert-WsmCancellationBoundary $CancellationToken 'DeltaImportMember';$entry=$entries[[string]$member.Name];$destination=Join-Path $root ([string]$member.Name.Replace('/','\'));Copy-WsmDeltaZipEntry $entry $destination ([string]$member.SHA256) ([long]$member.Bytes) $CancellationToken}
        $importResult=Test-WsmDeltaTransportContents $root $transport $CancellationToken
        $payloadRoot=Join-Path $root 'current\payload';[void][IO.Directory]::CreateDirectory($payloadRoot);Assert-WsmNoReparse $payloadRoot
        $blobIndex=Join-Path $root 'delta\blobs.jsonl';$blobData=Join-Path $root 'delta\blobs.bin';$data=[IO.File]::Open($blobData,'Open','Read','Read');$reader=New-Object IO.StreamReader($blobIndex,[Text.Encoding]::UTF8,$true);$expectedOffset=[long]0;$previousHash=''
        try{Read-WsmBoundedLines $reader 1048576 | ForEach-Object {Assert-WsmCancellationBoundary $CancellationToken 'DeltaImportBlobIndexRow';$row=ConvertFrom-WsmJson $_;if($row.Hash -notmatch '^[a-f0-9]{64}$' -or $row.Hash -cle $previousHash -or $row.Offset -ne $expectedOffset -or $row.Bytes -lt 1 -or $row.Bytes -gt $importResult.CurrentManifest.ChunkBytes){throw 'Delta blob index order/bounds invalid.'};$previousHash=$row.Hash;$dest=Join-Path $payloadRoot ($row.Hash+'.blob');$temp=Join-Path $payloadRoot ([Guid]::NewGuid().ToString('N')+'.partial');$output=[IO.File]::Open($temp,'CreateNew','Write','None');$sha=[Security.Cryptography.SHA256]::Create();$left=[long]$row.Bytes
                $moved=$false;try{$data.Position=[long]$row.Offset;$buffer=New-Object byte[] 65536;while($left -gt 0){Assert-WsmCancellationBoundary $CancellationToken 'DeltaImportBlobBytes';$take=[int][Math]::Min($buffer.Length,$left);$n=$data.Read($buffer,0,$take);if($n -le 0){throw 'Delta blob data truncated.'};[void]$sha.TransformBlock($buffer,0,$n,$buffer,0);$output.Write($buffer,0,$n);$left-=$n};[void]$sha.TransformFinalBlock((New-Object byte[] 0),0,0);$output.Flush($true);if([BitConverter]::ToString($sha.Hash).Replace('-','').ToLowerInvariant() -cne $row.Hash){throw 'Delta chunk hash mismatch.'};$output.Dispose();$sha.Dispose();[IO.File]::Move($temp,$dest);$moved=$true;$expectedOffset+=[long]$row.Bytes}finally{$output.Dispose();$sha.Dispose();if(-not $moved -and [IO.File]::Exists($temp)){[IO.File]::Delete($temp)}}
            }}
        finally{$reader.Dispose();$data.Dispose()}
    $validated=Test-WsmDeltaTransportContents $root $transport $CancellationToken
        [pscustomobject]@{Directory=$root;TransportPath=$transportPathOut;TransportHash=$ExpectedHash.ToLowerInvariant();PairId=$transport.PairId;BaseManifestHash=$transport.BaseManifestHash;CurrentManifestHash=$transport.CurrentManifestHash;Generation=$validated.CurrentManifest.Generation;ChangedRecords=$validated.ChangedRecords;Valid=$true;Mode='IsolatedPilot'}
    }catch{if($archive){$archive.Dispose()};$stream.Dispose();throw}finally{if($archive){$archive.Dispose()};$stream.Dispose()}
}
function Test-WsmDeltaTransportZipBinding([string]$TransportPath,[string]$ExpectedHash,[string]$ImportedRoot,$CancellationToken=$null) {
    if((Get-WsmDeltaFileHashCancellable $TransportPath $CancellationToken 'DeltaArchiveBindingHash') -ine $ExpectedHash){throw 'Delta transport archive changed after import.'}
    $file=[IO.File]::Open([IO.Path]::GetFullPath($TransportPath),'Open','Read','Read');$archive=$null
    try{Add-Type -AssemblyName System.IO.Compression;$archive=New-Object IO.Compression.ZipArchive($file,[IO.Compression.ZipArchiveMode]::Read,$true);$entry=@($archive.Entries | Where-Object FullName -CEQ 'transport.json');if($entry.Count -ne 1){throw 'Delta archive transport record missing/duplicate.'};$input=$entry[0].Open();$output=[IO.File]::OpenRead((Join-Path $ImportedRoot 'transport.json'));$sha=[Security.Cryptography.SHA256]::Create()
        try{$zipHash=[BitConverter]::ToString($sha.ComputeHash($input)).Replace('-','').ToLowerInvariant();$importHash=[BitConverter]::ToString($sha.ComputeHash($output)).Replace('-','').ToLowerInvariant();if($zipHash -cne $importHash){throw 'Imported delta binding record differs from trusted archive.'}}
        finally{$sha.Dispose();$input.Dispose();$output.Dispose()}
    }finally{if($archive){$archive.Dispose()};$file.Dispose()}
}
function Test-WsmDeltaVolumeTransportBinding([string]$TransportPath,[string]$ExpectedHash,[string]$ImportedRoot,$CancellationToken=$null) {
    if($ExpectedHash -notmatch '^[a-fA-F0-9]{64}$' -or (Get-WsmDeltaVolumeHash $TransportPath) -ine $ExpectedHash){throw 'Independent delta transport index hash mismatch.'};$transport=Read-WsmJson $TransportPath;if($transport.Kind -cnotin @('ArtifactDeltaVolumeTransport','ArtifactDeltaDirectoryTransport') -or $transport.FormatVersion -ne 1){throw 'Wrong delta transport kind/version.'};Assert-WsmNoReparse $ImportedRoot
    $record=Join-Path ([IO.Path]::GetFullPath($ImportedRoot)) 'transport.json';Assert-WsmNoReparse $record
    if(-not [IO.File]::Exists($record) -or (Get-WsmDeltaVolumeHash $record) -ine $ExpectedHash){throw 'Imported delta volume index differs from the independently trusted sidecar.'}
    Test-WsmDeltaVolumeTransportContents $ImportedRoot $transport $ExpectedHash $CancellationToken
}
function Invoke-WsmDeltaFaultPoint([string]$Name,$Context) {
    # Deterministic interruption seam used only by isolated recovery fixtures.
    # Production has no callback unless a caller deliberately sets the private
    # module-scoped test variable.
    if($script:DeltaFaultPointAction -is [scriptblock]){& $script:DeltaFaultPointAction $Name $Context}
}
function Get-WsmDeltaItemPath($Item,[string]$RelativePath) {
    $root=ConvertTo-WsmCanonicalPath ([string]$Item.MigrationSpec.TargetPath);Assert-WsmRelativePath $RelativePath -AllowRoot
    $path=$root;if($RelativePath){$path=[IO.Path]::GetFullPath((Join-Path $root $RelativePath))}
    if($path -ine $root -and -not $path.StartsWith($root.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Delta path escapes approved FileScope root.'}
    if($path.Length -gt 239){throw 'Delta target path exceeds qualified path limit.'};$path
}
function Copy-WsmDeltaOwnedScope([string]$Source,[string]$Destination,$MetadataMode,$CancellationToken=$null) {
    Assert-WsmNoReparse $Source;Assert-WsmNoReparse ([IO.Path]::GetDirectoryName($Destination));$watch=[Diagnostics.Stopwatch]::StartNew();$bytes=[long]0;$lastProgressSecond=0L
    try {
        if([IO.Directory]::Exists($Source)){
            [void][IO.Directory]::CreateDirectory($Destination);$stack=New-Object 'System.Collections.Generic.Stack[object]';$stack.Push([pscustomobject]@{Source=$Source;Destination=$Destination;Visited=$false})
            while($stack.Count){Assert-WsmCancellationBoundary $CancellationToken 'DeltaStageCopyEntry';$node=$stack.Pop();Assert-WsmNoReparse $node.Source
                if([IO.Directory]::Exists($node.Source)){
                    if($node.Visited){continue}
                    $stack.Push([pscustomobject]@{Source=$node.Source;Destination=$node.Destination;Visited=$true})
                    foreach($child in [IO.Directory]::EnumerateFileSystemEntries($node.Source)){Assert-WsmCancellationBoundary $CancellationToken 'DeltaStageCopyEntry';$name=[IO.Path]::GetFileName($child);$dest=Join-Path $node.Destination $name;Assert-WsmNoReparse $child;if([IO.Directory]::Exists($child)){[void][IO.Directory]::CreateDirectory($dest);$stack.Push([pscustomobject]@{Source=$child;Destination=$dest;Visited=$false})}else{$input=[IO.File]::Open($child,'Open','Read','Read');$output=[IO.File]::Open($dest,'CreateNew','Write','None');try{$buffer=New-Object byte[] 65536;while(($read=$input.Read($buffer,0,$buffer.Length)) -gt 0){Assert-WsmCancellationBoundary $CancellationToken 'DeltaStageCopyBytes';$output.Write($buffer,0,$read);$bytes+=$read;if($watch.Elapsed.TotalSeconds -ge ($lastProgressSecond+1)){$lastProgressSecond=[long][Math]::Floor($watch.Elapsed.TotalSeconds);[void](Set-WsmOperationProgress $CancellationToken 'DeltaStageCopyBytes' $bytes 0 ([long]$watch.Elapsed.TotalSeconds) (Get-WsmUtc))}};$output.Flush($true)}finally{$input.Dispose();$output.Dispose()}}}
                }else{throw 'Owned scope changed type while staging.'}
            }
        }elseif([IO.File]::Exists($Source)){$input=[IO.File]::Open($Source,'Open','Read','Read');$output=[IO.File]::Open($Destination,'CreateNew','Write','None');try{$buffer=New-Object byte[] 65536;while(($read=$input.Read($buffer,0,$buffer.Length)) -gt 0){Assert-WsmCancellationBoundary $CancellationToken 'DeltaStageCopyBytes';$output.Write($buffer,0,$read);$bytes+=$read;if($watch.Elapsed.TotalSeconds -ge ($lastProgressSecond+1)){$lastProgressSecond=[long][Math]::Floor($watch.Elapsed.TotalSeconds);[void](Set-WsmOperationProgress $CancellationToken 'DeltaStageCopyBytes' $bytes 0 ([long]$watch.Elapsed.TotalSeconds) (Get-WsmUtc))}};$output.Flush($true)}finally{$input.Dispose();$output.Dispose()}}
        else{throw 'Owned base scope disappeared before staging.'}
    } finally {Clear-WsmOperationProgress $CancellationToken}
}
function Get-WsmDeltaOwnedScopeBytes([string]$Root) {
    Assert-WsmNoReparse $Root;$total=[long]0
    if([IO.File]::Exists($Root)){return (New-Object IO.FileInfo($Root)).Length}
    if(-not [IO.Directory]::Exists($Root)){throw 'Owned scope disappeared during delta capacity preflight.'}
    $stack=New-Object 'System.Collections.Generic.Stack[string]';$stack.Push($Root)
    while($stack.Count){$directory=$stack.Pop();Assert-WsmNoReparse $directory;foreach($entry in [IO.Directory]::EnumerateFileSystemEntries($directory)){Assert-WsmNoReparse $entry;if([IO.Directory]::Exists($entry)){$stack.Push($entry)}else{$length=(New-Object IO.FileInfo($entry)).Length;if($total -gt ([long]::MaxValue-$length)){throw 'Owned scope byte count overflow.'};$total+=$length}}}
    $total
}
function Remove-WsmDeltaOwnedStagingRoot([string]$Path,[string]$ExpectedParent,[string]$ItemId) {
    $full=[IO.Path]::GetFullPath($Path);$parent=[IO.Path]::GetFullPath($ExpectedParent)
    if([IO.Path]::GetDirectoryName($full) -ine $parent -or [IO.Path]::GetFileName($full) -notmatch ('^\.wsm-delta-stage-'+[regex]::Escape($ItemId.Substring(0,12))+'-[a-f0-9]{32}$')){throw 'Pending staging path is not the exact generated sibling recorded for this delta.'}
    Assert-WsmNoReparse $full;if([IO.File]::Exists($full)){[IO.File]::SetAttributes($full,[IO.FileAttributes]::Normal);[IO.File]::Delete($full);return};if(-not [IO.Directory]::Exists($full)){return}
    $stack=New-Object 'System.Collections.Generic.Stack[object]';$stack.Push([pscustomobject]@{Path=$full;Visited=$false})
    while($stack.Count){$node=$stack.Pop();Assert-WsmNoReparse $node.Path;if([IO.Directory]::Exists($node.Path)){if($node.Visited){[IO.Directory]::Delete($node.Path,$false);continue};$stack.Push([pscustomobject]@{Path=$node.Path;Visited=$true});foreach($child in [IO.Directory]::EnumerateFileSystemEntries($node.Path)){Assert-WsmNoReparse $child;if([IO.Directory]::Exists($child)){$stack.Push([pscustomobject]@{Path=$child;Visited=$false})}else{[IO.File]::SetAttributes($child,[IO.FileAttributes]::Normal);[IO.File]::Delete($child)}}}else{[IO.File]::SetAttributes($node.Path,[IO.FileAttributes]::Normal);[IO.File]::Delete($node.Path)}}
}
function Get-WsmDeltaExistingScopeDigest([string]$Path,[string]$MetadataMode,$CancellationToken=$null) {
    Assert-WsmNoReparse $Path;if([IO.Directory]::Exists($Path) -or [IO.File]::Exists($Path)){return (Get-WsmFileScopeDigest $Path $MetadataMode $CancellationToken)};''
}
function Write-WsmDeltaChunkFromScope($Stream,[long]$Bytes,[string]$Hash,[string]$PayloadRoot,$CancellationToken=$null) {
    if($Bytes -lt 1 -or $Bytes -gt 64MB -or $Hash -notmatch '^[a-f0-9]{64}$'){throw 'Invalid full-package reconstruction chunk.'}
    $destination=Join-Path $PayloadRoot ($Hash+'.blob');if([IO.File]::Exists($destination)){Assert-WsmNoReparse $destination;if((New-Object IO.FileInfo($destination)).Length -ne $Bytes -or (Get-WsmDeltaFileHash $destination) -ine $Hash){throw 'Existing reconstructed chunk is corrupt.'};$Stream.Position+=$Bytes;return}
    $temp=Join-Path $PayloadRoot ([Guid]::NewGuid().ToString('N')+'.partial');$output=[IO.File]::Open($temp,'CreateNew','Write','None');$sha=[Security.Cryptography.SHA256]::Create();$left=$Bytes
    try{$buffer=New-Object byte[] 65536;while($left -gt 0){Assert-WsmCancellationBoundary $CancellationToken 'DeltaPackageRebuildChunk';$take=[int][Math]::Min($buffer.Length,$left);$read=$Stream.Read($buffer,0,$take);if($read -le 0){throw 'Base target file ended while rebuilding an unchanged current chunk.'};[void]$sha.TransformBlock($buffer,0,$read,$buffer,0);$output.Write($buffer,0,$read);$left-=$read};[void]$sha.TransformFinalBlock((New-Object byte[] 0),0,0);$output.Flush($true);if([BitConverter]::ToString($sha.Hash).Replace('-','').ToLowerInvariant() -cne $Hash){throw 'Live base chunk differs from trusted current index.'};$output.Dispose();[IO.File]::Move($temp,$destination)}finally{$output.Dispose();$sha.Dispose();if([IO.File]::Exists($temp)){[IO.File]::Delete($temp)}}
}
function Remove-WsmDeltaOwnedPackageRoot([string]$Path,[string]$ExpectedParent,[string]$ExpectedName) {
    $full=[IO.Path]::GetFullPath($Path);$parent=[IO.Path]::GetFullPath($ExpectedParent);if([IO.Path]::GetDirectoryName($full) -ine $parent -or [IO.Path]::GetFileName($full) -cne $ExpectedName){throw 'Incomplete local delta package escaped its durable transaction path.'};Assert-WsmNoReparse $full
    if(-not [IO.Directory]::Exists($full)){return};$stack=New-Object 'System.Collections.Generic.Stack[object]';$stack.Push([pscustomobject]@{Path=$full;Visited=$false})
    while($stack.Count){$node=$stack.Pop();Assert-WsmNoReparse $node.Path;if([IO.Directory]::Exists($node.Path)){if($node.Visited){[IO.Directory]::Delete($node.Path,$false);continue};$stack.Push([pscustomobject]@{Path=$node.Path;Visited=$true});foreach($child in [IO.Directory]::EnumerateFileSystemEntries($node.Path)){Assert-WsmNoReparse $child;if([IO.Directory]::Exists($child)){$stack.Push([pscustomobject]@{Path=$child;Visited=$false})}else{[IO.File]::SetAttributes($child,[IO.FileAttributes]::Normal);[IO.File]::Delete($child)}}}else{[IO.File]::SetAttributes($node.Path,[IO.FileAttributes]::Normal);[IO.File]::Delete($node.Path)}}
}
function New-WsmDeltaLocalPackage($ImportedRoot,$Paths,$Transaction,$CurrentPackage,$BasePackage,$CancellationToken=$null) {
    $name='delta-package-g'+$CurrentPackage.Manifest.Generation+'-'+$CurrentPackage.SHA256.Substring(0,12);$root=[IO.Path]::GetFullPath((Join-Path $Paths.Root $name));$expected=Join-Path $Paths.Root $name
    if($Transaction.PSObject.Properties['LocalPackageRoot'] -and $Transaction.LocalPackageRoot -and [IO.Path]::GetFullPath($Transaction.LocalPackageRoot) -ine $root){throw 'Delta transaction local package path differs from its exact generation/hash binding.'}
    $requiredPayloadPath=Join-Path (Join-Path $root 'payload') (('f'*64)+'.blob');if($requiredPayloadPath.Length -gt 239){throw 'Target state directory is too deep for a complete local package; select a shorter local state directory.'}
    if(-not $Transaction.PSObject.Properties['LocalPackageRoot']){$Transaction | Add-Member NoteProperty LocalPackageRoot ''};if(-not $Transaction.PSObject.Properties['LocalPackageManifestHash']){$Transaction | Add-Member NoteProperty LocalPackageManifestHash ''};if(-not $Transaction.PSObject.Properties['LocalPackagePhase']){$Transaction | Add-Member NoteProperty LocalPackagePhase ''};$Transaction.LocalPackageRoot=$root;$Transaction.LocalPackageManifestHash=$CurrentPackage.SHA256
    if([IO.Directory]::Exists($root)){
        try{$valid=Test-WsmMigrationPackage (Join-Path $root 'manifest.json') $CurrentPackage.SHA256;if($valid.Valid){$Transaction.LocalPackagePhase='Ready';return $valid}}catch{if($Transaction.LocalPackagePhase -cne 'Building'){throw 'Incomplete local delta package is not safely resumable; retain it and reconcile.'}}
        if($Transaction.LocalPackagePhase -cne 'Building'){throw 'Existing local delta package is not bound to a durable Building transaction.'};Remove-WsmDeltaOwnedPackageRoot $root $Paths.Root $name
    }
    if($Transaction.Phase -cne 'Building'){throw 'A switched delta cannot reconstruct its local package after target roots have moved.'}
    $Transaction.LocalPackagePhase='Building';Write-WsmJson (Join-Path $Paths.Root ('delta-transaction-g'+$CurrentPackage.Manifest.Generation+'.json')) $Transaction
    [void][IO.Directory]::CreateDirectory($root);Protect-WsmDirectory $root;Assert-WsmNoReparse $root
    foreach($file in @('manifest.json','plan.json','artifacts.jsonl','freeze.json')){Assert-WsmCancellationBoundary $CancellationToken 'DeltaPackageMetadata';$source=Join-Path $CurrentPackage.Root $file;if(-not [IO.File]::Exists($source)){throw ('Current package metadata member missing: '+$file)};Copy-WsmDeltaFileCancellable $source (Join-Path $root $file) $CancellationToken 'DeltaPackageMetadataBytes'}
    $payload=Join-Path $root 'payload';[void][IO.Directory]::CreateDirectory($payload)
    $importedPayload=Join-Path $CurrentPackage.Root 'payload';if([IO.Directory]::Exists($importedPayload)){foreach($blob in [IO.Directory]::EnumerateFiles($importedPayload)){Assert-WsmCancellationBoundary $CancellationToken 'DeltaPackagePayload';Assert-WsmNoReparse $blob;$leaf=[IO.Path]::GetFileName($blob);if($leaf -notmatch '^[a-f0-9]{64}\.blob$'){throw 'Imported delta payload has an unexpected filename.'};$hash=$leaf.Substring(0,64);if((Get-WsmDeltaFileHash $blob) -cne $hash){throw 'Imported changed payload chunk failed local package copy verification.'};$dest=Join-Path $payload $leaf;if(-not [IO.File]::Exists($dest)){Copy-WsmDeltaFileCancellable $blob $dest $CancellationToken 'DeltaPackagePayloadBytes'}}}
    $plan=$CurrentPackage.Plan;$baseItems=@{};foreach($item in $BasePackage.Plan.Items){$baseItems[[string]$item.ItemId]=$item};$currentItems=@{};foreach($item in $plan.Items){$currentItems[[string]$item.ItemId]=$item}
    $indexReader=New-Object IO.StreamReader((Join-Path $root 'artifacts.jsonl'),[Text.Encoding]::UTF8,$true)
    try{Read-WsmBoundedLines $indexReader 1048576 | ForEach-Object {Assert-WsmCancellationBoundary $CancellationToken 'DeltaPackageIndexRow';$row=ConvertFrom-WsmJson $_;if(-not $row.Directory -and $null -ne $row.Data){$item=$currentItems[[string]$row.ItemId];$missing=@($row.Data.Chunks | Where-Object {-not [IO.File]::Exists((Join-Path $payload ($_.Hash+'.blob'))) });if($missing.Count){if($item.MigrationSpec.Adapter -eq 'Certificate'){throw 'Full certificate payload chunk was omitted from the delta transport.'};if($item.MigrationSpec.Adapter -ne 'FileScope'){throw 'Cannot reconstruct unchanged payload for a non-FileScope adapter.'};$baseItem=$baseItems[[string]$row.ItemId];if(-not $baseItem -or $baseItem.Decision -ne 'Include' -or $baseItem.MigrationSpec.Adapter -ne 'FileScope' -or $baseItem.MigrationSpec.TargetPath -ine $item.MigrationSpec.TargetPath){throw 'Unchanged file content lacks an exact approved base target.'};$source=Get-WsmDeltaItemPath $item $row.RelativePath;if(-not [IO.File]::Exists($source) -or (New-Object IO.FileInfo($source)).Length -ne $row.Data.Bytes -or (Get-WsmDeltaFileHash $source) -ine $row.Data.Hash){throw 'Live base file does not match the current unchanged/metadata-only record.'};$stream=[IO.File]::Open($source,'Open','Read','Read');try{foreach($chunk in $row.Data.Chunks){Assert-WsmCancellationBoundary $CancellationToken 'DeltaPackageRebuildChunk';$blob=Join-Path $payload ($chunk.Hash+'.blob');if([IO.File]::Exists($blob)){Assert-WsmNoReparse $blob;if((New-Object IO.FileInfo($blob)).Length -ne $chunk.Bytes -or (Get-WsmDeltaFileHash $blob) -ine $chunk.Hash){throw 'Existing local package chunk is corrupt.'};$stream.Position+=[long]$chunk.Bytes}else{Write-WsmDeltaChunkFromScope $stream ([long]$chunk.Bytes) ([string]$chunk.Hash) $payload $CancellationToken}}}finally{$stream.Dispose()}}else{foreach($chunk in $row.Data.Chunks){Assert-WsmCancellationBoundary $CancellationToken 'DeltaPackageValidateChunk';$blob=Join-Path $payload ($chunk.Hash+'.blob');Assert-WsmNoReparse $blob;if(-not [IO.File]::Exists($blob) -or (New-Object IO.FileInfo($blob)).Length -ne $chunk.Bytes -or (Get-WsmDeltaFileHash $blob) -ine $chunk.Hash){throw 'Local package chunk does not match its current index reference.'}}}}}}finally{$indexReader.Dispose()}
    $verified=Test-WsmMigrationPackage (Join-Path $root 'manifest.json') $CurrentPackage.SHA256;if(-not $verified.Valid){throw 'Reconstructed local current package did not pass the existing package validator.'};$Transaction.LocalPackagePhase='Ready';Write-WsmJson (Join-Path $Paths.Root ('delta-transaction-g'+$CurrentPackage.Manifest.Generation+'.json')) $Transaction;$verified
}
function Remove-WsmDeltaStageFile([string]$Path) {
    Assert-WsmNoReparse $Path;if([IO.File]::Exists($Path)){[IO.File]::SetAttributes($Path,[IO.FileAttributes]::Normal);[IO.File]::Delete($Path)}
}
function Read-WsmDeltaStreamChanges([string]$Path,[scriptblock]$Action,$CancellationToken=$null) {
    $stream=[IO.File]::Open([IO.Path]::GetFullPath($Path),'Open','Read','Read');$reader=New-Object IO.StreamReader($stream,[Text.Encoding]::UTF8,$true)
    try{Read-WsmBoundedLines $reader 1048576 | ForEach-Object {Assert-WsmCancellationBoundary $CancellationToken 'DeltaChangeRow';& $Action (ConvertFrom-WsmJson $_)}}finally{$reader.Dispose();$stream.Dispose()}
}
function Read-WsmDeltaStreamRecords([string]$Path,[scriptblock]$Action,$CancellationToken=$null) {
    $stream=[IO.File]::Open([IO.Path]::GetFullPath($Path),'Open','Read','Read');$reader=New-Object IO.StreamReader($stream,[Text.Encoding]::UTF8,$true)
    try{Read-WsmBoundedLines $reader 1048576 | ForEach-Object {Assert-WsmCancellationBoundary $CancellationToken 'DeltaArtifactRecord';& $Action (ConvertFrom-WsmJson $_)}}finally{$reader.Dispose();$stream.Dispose()}
}
function Invoke-WsmApplyDeltaToScope([string]$DeltaRoot,$Item,[string]$Target,[string]$Staging,$CurrentPackage,$CancellationToken=$null) {
    $changePath=Join-Path $DeltaRoot 'delta\changes.jsonl';$recordPath=Join-Path $DeltaRoot 'delta\records.jsonl';$maxDepth=0;$stageSpec=ConvertFrom-WsmJson ($Item.MigrationSpec | ConvertTo-Json -Depth 40 -Compress);$stageSpec.TargetPath=$Staging;$stageItem=[pscustomobject]@{ItemId=$Item.ItemId;MigrationSpec=$stageSpec}
    $indexReader=New-Object IO.StreamReader((Join-Path $CurrentPackage.Root 'artifacts.jsonl'),[Text.Encoding]::UTF8,$true)
    try{Read-WsmBoundedLines $indexReader 1048576 | ForEach-Object {Assert-WsmCancellationBoundary $CancellationToken 'DeltaStageIndexRow';$row=ConvertFrom-WsmJson $_;if($row.ItemId -ceq $Item.ItemId -and $row.Directory){$depth=0;if($row.RelativePath){$depth=$row.RelativePath.Split([char]92).Length};$maxDepth=[Math]::Max($maxDepth,$depth)}}}finally{$indexReader.Dispose()}
    # Remove files first; an owned base verification precedes this mutation of the isolated staging clone.
    Read-WsmDeltaStreamChanges $changePath {param($c) if($c.ItemId -ceq $Item.ItemId -and $c.Change -eq 'Deleted'){if(-not $c.RelativePath){throw 'Delta cannot remove an owned FileScope root.'};$p=Get-WsmDeltaItemPath $stageItem $c.RelativePath;Remove-WsmDeltaStageFile $p}} $CancellationToken
    for($level=$maxDepth;$level -ge 0;$level--){Read-WsmDeltaStreamChanges $changePath {param($c) if($c.ItemId -ceq $Item.ItemId -and $c.Change -eq 'Deleted'){$p=Get-WsmDeltaItemPath $stageItem $c.RelativePath;if([IO.Directory]::Exists($p)){$depth=0;if($c.RelativePath){$depth=$c.RelativePath.Split([char]92).Length};if($depth -eq $level){Assert-WsmNoReparse $p;[IO.Directory]::Delete($p,$false)}}}} $CancellationToken}
    Invoke-WsmDeltaFaultPoint 'AfterStagedDeletes' ([pscustomobject]@{ItemId=$Item.ItemId;Staging=$Staging})
    Read-WsmDeltaStreamRecords $recordPath {param($recordEnvelope) $r=$recordEnvelope.Record;if($recordEnvelope.Change -in @('Added','Modified') -and $r.ItemId -ceq $Item.ItemId -and $r.Directory){$p=Get-WsmDeltaItemPath $stageItem $r.RelativePath;if([IO.File]::Exists($p)){Remove-WsmDeltaStageFile $p};[void][IO.Directory]::CreateDirectory($p)}} $CancellationToken
    Read-WsmDeltaStreamRecords $recordPath {param($recordEnvelope) $r=$recordEnvelope.Record;if($recordEnvelope.Change -in @('Added','Modified') -and $r.ItemId -ceq $Item.ItemId -and -not $r.Directory){$p=Get-WsmDeltaItemPath $stageItem $r.RelativePath;$parent=[IO.Path]::GetDirectoryName($p);if(-not [IO.Directory]::Exists($parent)){[void][IO.Directory]::CreateDirectory($parent)};if([IO.File]::Exists($p)){[IO.File]::SetAttributes($p,[IO.FileAttributes]::Normal)};if([IO.Directory]::Exists($p)){Assert-WsmNoReparse $p;[IO.Directory]::Delete($p,$false)};Restore-WsmPayloadBytes $r $CurrentPackage.Root $p $CancellationToken}} $CancellationToken
    $identityMap=Resolve-WsmIdentityMap $CurrentPackage.Plan @{}
    Read-WsmDeltaStreamRecords $recordPath {param($recordEnvelope) $r=$recordEnvelope.Record;if($r.ItemId -ceq $Item.ItemId -and -not $r.Directory){$p=Get-WsmDeltaItemPath $stageItem $r.RelativePath;Set-WsmFileMetadata $p $r.Metadata $identityMap}} $CancellationToken
    # Metadata is sourced from the complete current index so unchanged files retain exact ACL/times too.
    $indexReader=New-Object IO.StreamReader((Join-Path $CurrentPackage.Root 'artifacts.jsonl'),[Text.Encoding]::UTF8,$true)
    try{Read-WsmBoundedLines $indexReader 1048576 | ForEach-Object {Assert-WsmCancellationBoundary $CancellationToken 'DeltaStageMetadataRow';$row=ConvertFrom-WsmJson $_;if($row.ItemId -ceq $Item.ItemId -and -not $row.Directory){$p=Get-WsmDeltaItemPath $stageItem $row.RelativePath;Set-WsmFileMetadata $p $row.Metadata $identityMap}}}finally{$indexReader.Dispose()}
    for($level=$maxDepth;$level -ge 0;$level--){$indexReader=New-Object IO.StreamReader((Join-Path $CurrentPackage.Root 'artifacts.jsonl'),[Text.Encoding]::UTF8,$true);try{Read-WsmBoundedLines $indexReader 1048576 | ForEach-Object {Assert-WsmCancellationBoundary $CancellationToken 'DeltaStageMetadataRow';$row=ConvertFrom-WsmJson $_;if($row.ItemId -ceq $Item.ItemId -and $row.Directory){$depth=0;if($row.RelativePath){$depth=$row.RelativePath.Split([char]92).Length};if($depth -eq $level){$p=Get-WsmDeltaItemPath $stageItem $row.RelativePath;if(-not [IO.Directory]::Exists($p)){[void][IO.Directory]::CreateDirectory($p)};Set-WsmFileMetadata $p $row.Metadata $identityMap}}}}finally{$indexReader.Dispose()}}
}
function Assert-WsmDeltaStagedAdapters($CurrentPackage,$State,[string]$Phase,[bool]$RequireManualEvidence=$true) {
    $manualItems=@($CurrentPackage.Plan.Items | Where-Object {$_.Decision -eq 'Include' -and $_.MigrationSpec.Adapter -eq 'ManualWorkflow'})
    if(($manualItems.Count -gt 0) -ne ($State.Stage -eq 'ManualEvidenceRequired')){throw 'Delta base stage does not match the included ManualWorkflow contract.'}
    foreach($item in $CurrentPackage.Plan.Items){if($item.Decision -ne 'Include' -or $item.MigrationSpec.Adapter -eq 'FileScope'){continue};$spec=$item.MigrationSpec;$owners=@($State.Items | Where-Object ItemId -CEQ $item.ItemId)
        if($owners.Count -ne 1){throw ('Delta staged adapter has no unique durable ownership/status row: '+$item.ItemId)};$owner=$owners[0]
        if($spec.Adapter -eq 'ManualWorkflow'){
            if($owner.Status -cne 'ManualEvidenceRequired' -or $owner.CreatedByTool -ne $false -or ($RequireManualEvidence -and -not (Test-WsmEvidence $State $item.ItemId ManualRestore $State.ManifestHash))){throw ('Delta ManualWorkflow lacks current staged procedure evidence; it remains manual: '+$item.ItemId)}
            continue
        }
        if($owner.Status -notin @('Succeeded','RebootRequired')){throw ('Delta staged adapter ownership/status is not complete: '+$item.ItemId)}
        if($owner.Status -eq 'RebootRequired'){Assert-WsmRebootCompleted $owner}
        if($owner.CreatedByTool -ne $true -and $spec.Adapter -ne 'WindowsFeature'){throw ('Delta staged adapter lacks durable tool ownership: '+$item.ItemId)}
        $receipts=@();if($spec.Adapter -ceq 'ScheduledTask'){$allReceipts=Get-WsmTaskSecurityOwnershipReceipts $State;$receipts=Get-WsmTaskSecurityReceiptsForSpec $spec $allReceipts}
        $check=Test-WsmAdapterConfiguration $spec Staged $receipts
        if(-not $check.Passed){throw ('Delta staged adapter readback failed for '+$item.ItemId+': '+(@($check.Problems) -join '; '))}
        if($spec.Adapter -eq 'WindowsFeature' -and $owner.CreatedByTool){[void](Test-WsmInstallerConsumers $spec.Desired $owner.InstallerSafety Staged)}
    }
}
function Write-WsmDeltaOperationState($Paths,$CurrentPackage,$Transaction) {
    $state=Get-WsmOperationState $Paths $CurrentPackage;$alreadyPromoted=($state.ManifestHash -ieq $CurrentPackage.SHA256 -and $state.Generation -eq $CurrentPackage.Manifest.Generation);Assert-WsmDeltaStagedAdapters $CurrentPackage $state 'Promotion' (-not $alreadyPromoted);$updated=New-Object 'System.Collections.Generic.List[object]'
    foreach($operation in $Transaction.Operations){$item=@($CurrentPackage.Plan.Items | Where-Object ItemId -CEQ $operation.ItemId);if($item.Count -ne 1){throw 'Delta operation item missing from current plan.'};$target=$operation.Target;$actual=Get-WsmFileScopeDigest $target $item[0].MigrationSpec.Metadata
        if($operation.ExpectedCurrentHash -notmatch '^[a-f0-9]{64}$' -or $actual -cne $operation.ExpectedCurrentHash){throw ('Delta target changed after atomic exchange; preserve transaction for explicit repair: '+$operation.ItemId)}
        $verified=Test-WsmFileScope $item[0] $CurrentPackage $target @{};if(-not $verified.Passed -or $verified.ActualHash -cne $actual){throw ('Delta target no longer matches the exact staged current package; preserve transaction for explicit repair: '+$operation.ItemId)}
        $record=@($state.Items | Where-Object ItemId -CEQ $operation.ItemId);if($record.Count -gt 1){throw 'Duplicate target ownership state row.'};$new=[pscustomobject]@{ItemId=$operation.ItemId;Status='Succeeded';CreatedByTool=$true;ActualHash=$actual;Backup=$operation.Backup;Target=$target;Error='';NativeCode=0};$state.Items=@($state.Items | Where-Object ItemId -CNE $operation.ItemId)+@($new);$updated.Add($new)
    }
    $state.ManifestHash=$CurrentPackage.SHA256;$state.Generation=$CurrentPackage.Manifest.Generation;$state.Stage='Succeeded';if(@($CurrentPackage.Plan.Items | Where-Object {$_.Decision -eq 'Include' -and $_.MigrationSpec.Adapter -eq 'ManualWorkflow'}).Count){$state.Stage='ManualEvidenceRequired'};$packageManifestPath=Join-Path $Transaction.LocalPackageRoot 'manifest.json';if(-not $state.PSObject.Properties['DeltaPackageManifestPath']){$state | Add-Member NoteProperty DeltaPackageManifestPath ''};if(-not $state.PSObject.Properties['DeltaPackageManifestHash']){$state | Add-Member NoteProperty DeltaPackageManifestHash ''};$state.DeltaPackageManifestPath=$packageManifestPath;$state.DeltaPackageManifestHash=$CurrentPackage.SHA256
    foreach($record in $updated){Add-WsmJournal $Paths $state 'ItemCompleted' $record.ItemId $record}
    Add-WsmJournal $Paths $state 'RestoreCompleted' '' ([pscustomobject]@{Status='Succeeded';Generation=$CurrentPackage.Manifest.Generation;ManifestHash=$CurrentPackage.SHA256;Delta=$true})
    $state
}
function Invoke-WsmArtifactDeltaRestore {
    [CmdletBinding(SupportsShouldProcess)]param([Parameter(Mandatory)][string]$TransportPath,[Parameter(Mandatory)][string]$ExpectedTransportHash,[Parameter(Mandatory)][string]$ImportedDirectory,[Parameter(Mandatory)][string]$TargetStateDirectory,[object[]]$GeneralHostEvidence=@(),$CancellationToken=$null)
    $volumeTransport=$false
    if([IO.Path]::GetExtension($TransportPath) -ieq '.json'){$transport=Read-WsmJson $TransportPath;if($ExpectedTransportHash -notmatch '^[a-fA-F0-9]{64}$' -or (Get-WsmDeltaVolumeHash $TransportPath) -ine $ExpectedTransportHash -or $transport.Kind -cnotin @('ArtifactDeltaVolumeTransport','ArtifactDeltaDirectoryTransport') -or $transport.FormatVersion -ne 1){throw 'Delta restore requires a trusted versioned volume or directory delta transport.'};$volumeTransport=$true;$bundle=Test-WsmDeltaVolumeTransportBinding $TransportPath $ExpectedTransportHash $ImportedDirectory $CancellationToken}
    else{Test-WsmDeltaTransportZipBinding $TransportPath $ExpectedTransportHash $ImportedDirectory $CancellationToken;$transport=Read-WsmJson (Join-Path $ImportedDirectory 'transport.json');Assert-WsmEnvelope $transport 'ArtifactDeltaTransport';Assert-WsmId $transport.PairId;$bundle=Test-WsmDeltaTransportContents $ImportedDirectory $transport $CancellationToken}
    if($transport.PlanHash -notmatch '^[a-f0-9]{64}$' -or $transport.CurrentManifestHash -notmatch '^[a-f0-9]{64}$'){throw 'Imported delta transport lacks trusted plan/current-manifest bindings.'}
    if($CancellationToken){[void](Assert-WsmCancellationTokenBinding $CancellationToken $transport.PairId $transport.PlanHash $transport.CurrentManifestHash $TargetStateDirectory)}
    Assert-WsmCancellationBoundary $CancellationToken 'DeltaApplyStart'
    $identity=Get-WsmMachineIdentity;Assert-WsmMigrationHost $identity $bundle.CurrentManifest.Target.Fingerprint
    $currentRoot=Join-Path $ImportedDirectory 'current';$baseRoot=Join-Path $ImportedDirectory 'base';$currentPackage=[pscustomobject]@{Root=$currentRoot;Manifest=$bundle.CurrentManifest;Plan=(Read-WsmTrustedJson (Join-Path $currentRoot 'plan.json') $transport.PlanHash);SHA256=$transport.CurrentManifestHash};$basePackage=[pscustomobject]@{Root=$baseRoot;Manifest=$bundle.BaseManifest;Plan=(Read-WsmTrustedJson (Join-Path $baseRoot 'plan.json') $transport.PlanHash);SHA256=$transport.BaseManifestHash}
    if($currentPackage.Plan.SchemaVersion -eq 2 -and $currentPackage.Plan.ScopeMode -ceq 'GeneralHost'){$issues=@(Get-WsmGeneralHostIssues $currentPackage.Plan RestoreReady $currentPackage.Manifest.Target.Fingerprint '' $currentPackage.Manifest.PlanHash $GeneralHostEvidence);if($issues.Count){throw ('GeneralHost RestoreReady gate blocked delta restore: '+(($issues | ForEach-Object {[string]$_.Issue}) -join '; '))}}
    Assert-WsmWorkspaceSeparation $currentPackage.Plan $TargetStateDirectory TargetPath;$paths=Get-WsmOperationPaths $TargetStateDirectory $bundle.CurrentManifest.PairId
    if(-not $PSCmdlet.ShouldProcess($bundle.CurrentManifest.PairId,('Apply incremental FileScope delta generation '+$bundle.CurrentManifest.Generation))){return [pscustomobject]@{Preview=$true;PairId=$bundle.CurrentManifest.PairId;Generation=$bundle.CurrentManifest.Generation;ChangedRecords=$bundle.ChangedRecords;Mode='IsolatedPilot'}}
    Invoke-WsmLocked $paths.Root {
        if(-not [IO.File]::Exists($paths.State)){throw 'Incremental delta requires an existing target ownership checkpoint from the base generation.'}
        $state=Get-WsmOperationState $paths $currentPackage -AllowRecovery;$journal=Test-WsmJournal $TargetStateDirectory $bundle.CurrentManifest.PairId;if(-not $journal.Consistent){Restore-WsmJournalCheckpoint $paths $state;$state=Read-WsmJson $paths.State}
        # Bind the already durable base-generation checkpoint before any delta staging or target scope switch.
        Confirm-WsmOutputStateCheckpoint -StateDirectory $TargetStateDirectory -PairId $bundle.CurrentManifest.PairId -PlanHash $currentPackage.Manifest.PlanHash
        if(@($state.PendingOperations).Count -gt 0 -or $state.Cutover){throw 'Incremental delta requires a fully staged, quiescent target checkpoint before cutover.'}
        $transactionPath=Join-Path $paths.Root ('delta-transaction-g'+$bundle.CurrentManifest.Generation+'.json');$transaction=$null
        if([IO.File]::Exists($transactionPath)){$transaction=Read-WsmJson $transactionPath;Assert-WsmEnvelope $transaction 'ArtifactDeltaTransaction';if($transaction.PairId -cne $bundle.CurrentManifest.PairId -or $transaction.PlanHash -ine $transport.PlanHash -or $transaction.BaseManifestHash -ine $transport.BaseManifestHash -or $transaction.CurrentManifestHash -ine $transport.CurrentManifestHash -or $transaction.TransportHash -ine $ExpectedTransportHash){throw 'Pending delta transaction belongs to a different package; preserve and reconcile it.'}}
        if($state.Generation -eq $bundle.CurrentManifest.Generation -and $state.ManifestHash -ieq $transport.CurrentManifestHash){if(-not $transaction -or $transaction.Phase -eq 'Completed'){return $state};if($transaction.Phase -eq 'Switched'){$state=Write-WsmDeltaOperationState $paths $currentPackage $transaction;$transaction.Phase='Completed';$transaction.UpdatedUtc=Get-WsmUtc;Write-WsmJson $transactionPath $transaction;return $state};throw 'Operation state is current but delta transaction is incomplete; reconcile exact roots.'}
        if($state.Stage -cne 'Succeeded' -and $state.Stage -cne 'ManualEvidenceRequired'){throw 'Incremental delta requires a fully staged, quiescent target checkpoint before cutover.'}
        if($state.Generation -ne $bundle.BaseManifest.Generation -or $state.ManifestHash -ine $transport.BaseManifestHash){throw 'Target ownership state is not at the exact delta base generation.'}
        if(-not $transaction -or $transaction.Phase -eq 'Building'){
            Assert-WsmDeltaStagedAdapters $currentPackage $state 'Preflight'
        foreach($item in $currentPackage.Plan.Items){Assert-WsmCancellationBoundary $CancellationToken 'DeltaBaseScopePreflight';if($item.Decision -ne 'Include' -or $item.MigrationSpec.Adapter -ne 'FileScope'){continue};$baseItem=@($basePackage.Plan.Items | Where-Object {$_.ItemId -ceq $item.ItemId -and $_.Decision -eq 'Include' -and $_.MigrationSpec.Adapter -eq 'FileScope'});$owner=@($state.Items | Where-Object ItemId -CEQ $item.ItemId);if($baseItem.Count -ne 1 -or $baseItem[0].MigrationSpec.TargetPath -ine $item.MigrationSpec.TargetPath -or $owner.Count -ne 1 -or $owner[0].Status -cne 'Succeeded' -or $owner[0].CreatedByTool -ne $true){throw ('Full package reconstruction requires exact durable base ownership for every included FileScope: '+$item.ItemId)};$target=ConvertTo-WsmCanonicalPath $item.MigrationSpec.TargetPath;if($owner[0].Target -ine $target -or (Get-WsmFileScopeDigest $target $item.MigrationSpec.Metadata $CancellationToken) -cne $owner[0].ActualHash){throw ('Unchanged/current FileScope base drifted before delta package reconstruction: '+$item.ItemId)};$baseCheck=Test-WsmFileScope $baseItem[0] $basePackage $target @{} $CancellationToken;if(-not $baseCheck.Passed -or $baseCheck.ActualHash -cne $owner[0].ActualHash){throw ('Live base FileScope does not match its trusted package: '+$item.ItemId)}}
        }
        $changes=Join-Path $ImportedDirectory 'delta\changes.jsonl';$changedItems=@{};Read-WsmDeltaStreamChanges $changes {param($change) if($change.Change -ne 'Unchanged'){$changedItems[[string]$change.ItemId]=$true}}
        $operations=New-Object 'System.Collections.Generic.List[object]'
        foreach($id in $changedItems.Keys){$items=@($currentPackage.Plan.Items | Where-Object {$_.ItemId -ceq $id -and $_.Decision -eq 'Include' -and $_.MigrationSpec.Adapter -eq 'FileScope'});if($items.Count -ne 1){throw ('Delta apply supports only approved FileScope entries: '+$id)};$baseItem=@($basePackage.Plan.Items | Where-Object {$_.ItemId -ceq $id -and $_.Decision -eq 'Include' -and $_.MigrationSpec.Adapter -eq 'FileScope'});if($baseItem.Count -ne 1 -or $baseItem[0].MigrationSpec.TargetPath -ine $items[0].MigrationSpec.TargetPath){throw 'Delta scope is not an existing target-owned FileScope in the base plan.'}
            $owner=@($state.Items | Where-Object ItemId -CEQ $id);if($owner.Count -ne 1 -or $owner[0].Status -cne 'Succeeded' -or $owner[0].CreatedByTool -ne $true){throw ('Delta target scope is not durably owned: '+$id)}
            $target=ConvertTo-WsmCanonicalPath $items[0].MigrationSpec.TargetPath;if($owner[0].Target -ine $target){throw 'Durable ownership row points at a different FileScope target.'};Assert-WsmNoReparse $target;$digest=Get-WsmDeltaExistingScopeDigest $target $items[0].MigrationSpec.Metadata $CancellationToken
            $parent=[IO.Path]::GetDirectoryName($target);if(-not $parent -or [IO.Path]::GetPathRoot($target) -ieq $target){throw 'Volume root cannot be an atomic FileScope delta destination.'};Assert-WsmNoReparse $parent
            $recovery=$null;if($transaction -and $transaction.Phase -in @('Prepared','Switching','Switched')){
                $prior=@($transaction.Operations | Where-Object {$_.ItemId -ceq $id});if($prior.Count -ne 1 -or $prior[0].Target -ine $target -or $prior[0].BaseScopeHash -cne $owner[0].ActualHash -or $prior[0].ExpectedCurrentHash -notmatch '^[a-f0-9]{64}$'){throw 'Pending switched delta operation lacks the exact durable base/current hashes.'}
                $staging=[IO.Path]::GetFullPath([string]$prior[0].Staging);$backup=[IO.Path]::GetFullPath([string]$prior[0].Backup);if([IO.Path]::GetDirectoryName($staging) -ine $parent -or [IO.Path]::GetFileName($staging) -notmatch ('^\.wsm-delta-stage-'+[regex]::Escape($id.Substring(0,12))+'-[a-f0-9]{32}$') -or [IO.Path]::GetDirectoryName($backup) -ine $parent -or [IO.Path]::GetFileName($backup) -notmatch ('^\.wsm-delta-backup-'+[regex]::Escape($id.Substring(0,12))+'-[a-f0-9]{32}$')){throw 'Pending delta root path is not the exact generated sibling.'}
                $backupDigest=Get-WsmDeltaExistingScopeDigest $backup $items[0].MigrationSpec.Metadata $CancellationToken;$stageDigest=Get-WsmDeltaExistingScopeDigest $staging $items[0].MigrationSpec.Metadata $CancellationToken
                $baseRootReady=($digest -ceq $owner[0].ActualHash -and -not $backupDigest -and $stageDigest -ceq $prior[0].ExpectedCurrentHash)
                $oldMovedReady=(-not $digest -and $backupDigest -ceq $owner[0].ActualHash -and $stageDigest -ceq $prior[0].ExpectedCurrentHash)
                $newMovedReady=($digest -ceq $prior[0].ExpectedCurrentHash -and $backupDigest -ceq $owner[0].ActualHash -and -not $stageDigest)
                if(-not ($baseRootReady -or $oldMovedReady -or $newMovedReady)){throw 'Pending delta roots do not match a recoverable base/staging/backup state; preserve and reconcile manually.'}
                $recovery=$prior[0]
            }else{
                if($digest -cne $owner[0].ActualHash){throw 'Owned target scope drifted since its last verified generation.'};$baseCheck=Test-WsmFileScope $baseItem[0] $basePackage $target @{} $CancellationToken;if(-not $baseCheck.Passed -or $baseCheck.ActualHash -cne $owner[0].ActualHash){throw 'Live target does not exactly match the trusted base artifacts; delta blocked before changes.'}
            }
            if($recovery){$operations.Add($recovery)}else{$operations.Add([pscustomobject]@{ItemId=$id;Target=$target;Staging=(Join-Path $parent ('.wsm-delta-stage-'+$id.Substring(0,12)+'-'+[Guid]::NewGuid().ToString('N')));Backup=(Join-Path $parent ('.wsm-delta-backup-'+$id.Substring(0,12)+'-'+[Guid]::NewGuid().ToString('N')));BaseScopeHash=$digest;Phase='Building'})}
        }
        if($transaction -and $transaction.Phase -in @('Prepared','Switching','Switched')){if(@($transaction.Operations).Count -ne $operations.Count){throw 'Pending switched delta operation set differs from the trusted current delta.'};foreach($operation in $operations){if(@($transaction.Operations | Where-Object {$_.ItemId -ceq $operation.ItemId}).Count -ne 1){throw 'Pending switched delta operation set has an extra/missing item.'}}}
        if(-not $transaction -or $transaction.Phase -eq 'Building'){$volumeBytes=@{};foreach($operation in $operations){$volume=[IO.Path]::GetPathRoot($operation.Target);if(-not $volumeBytes.ContainsKey($volume)){$volumeBytes[$volume]=[long]0};$copyBytes=Get-WsmDeltaOwnedScopeBytes $operation.Target;if($volumeBytes[$volume] -gt ([long]::MaxValue-$copyBytes)){throw 'Delta staging capacity calculation overflow.'};$volumeBytes[$volume]+=$copyBytes};foreach($volume in $volumeBytes.Keys){$available=Get-WsmAvailableBytes $volume;if($available -lt ($volumeBytes[$volume]+256MB)){throw ('Target volume lacks free space to stage owned delta scopes safely: '+$volume)}}}
        if(-not $transaction -or $transaction.Phase -eq 'Building'){
            if($transaction -and $transaction.Phase -eq 'Building'){
                $recorded=@($transaction.Operations);if($recorded.Count -ne $operations.Count){throw 'Pending building delta operation set differs from current trusted delta.'}
                foreach($operation in $operations){$prior=@($recorded | Where-Object {$_.ItemId -ceq $operation.ItemId});if($prior.Count -ne 1 -or $prior[0].Target -ine $operation.Target -or $prior[0].BaseScopeHash -ine $operation.BaseScopeHash){throw 'Pending building delta operation does not match exact approved target/base.'};$parent=[IO.Path]::GetDirectoryName($operation.Target);$backupFull=[IO.Path]::GetFullPath([string]$prior[0].Backup);if([IO.Path]::GetDirectoryName($backupFull) -ine $parent -or [IO.Path]::GetFileName($backupFull) -notmatch ('^\.wsm-delta-backup-'+[regex]::Escape($operation.ItemId.Substring(0,12))+'-[a-f0-9]{32}$')){throw 'Pending delta backup path is not the exact generated sibling.'};Remove-WsmDeltaOwnedStagingRoot ([string]$prior[0].Staging) $parent $operation.ItemId;$operation.Staging=$prior[0].Staging;$operation.Backup=$prior[0].Backup}
                $transaction.Operations=@($operations.ToArray())
            }else{$transaction=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='ArtifactDeltaTransaction';PairId=$bundle.CurrentManifest.PairId;PlanHash=$transport.PlanHash;BaseManifestHash=$transport.BaseManifestHash;CurrentManifestHash=$transport.CurrentManifestHash;TransportHash=$ExpectedTransportHash;Generation=$bundle.CurrentManifest.Generation;Phase='Building';LocalPackageRoot='';LocalPackageManifestHash=$transport.CurrentManifestHash;LocalPackagePhase='';Operations=@($operations.ToArray());UpdatedUtc=(Get-WsmUtc)}}
            Write-WsmJson $transactionPath $transaction
            $currentPackage=New-WsmDeltaLocalPackage $ImportedDirectory $paths $transaction $currentPackage $basePackage $CancellationToken
            foreach($operation in $transaction.Operations){Assert-WsmCancellationBoundary $CancellationToken 'DeltaStageScopeStart';$item=@($currentPackage.Plan.Items | Where-Object ItemId -CEQ $operation.ItemId)[0];Copy-WsmDeltaOwnedScope $operation.Target $operation.Staging $item.MigrationSpec.Metadata $CancellationToken;Invoke-WsmApplyDeltaToScope $ImportedDirectory $item $operation.Target $operation.Staging $currentPackage $CancellationToken;$staged=Test-WsmFileScope $item $currentPackage $operation.Staging @{} $CancellationToken;if(-not $staged.Passed){throw ('Delta staged scope verification failed: '+($staged.Problems -join '; '))};$operation | Add-Member NoteProperty ExpectedCurrentHash $staged.ActualHash -Force;$operation.Phase='Prepared';$transaction.UpdatedUtc=Get-WsmUtc;Write-WsmJson $transactionPath $transaction}
            $transaction.Phase='Prepared';$transaction.UpdatedUtc=Get-WsmUtc;Write-WsmJson $transactionPath $transaction
        }else{$currentPackage=New-WsmDeltaLocalPackage $ImportedDirectory $paths $transaction $currentPackage $basePackage $CancellationToken}
        foreach($operation in $transaction.Operations){Assert-WsmCancellationBoundary $CancellationToken 'BeforeDeltaAtomicExchange';$promotionState=Get-WsmOperationState $paths $currentPackage -AllowRecovery;Assert-WsmDeltaStagedAdapters $currentPackage $promotionState 'BeforeTargetMutation';$metadataMode=(@($currentPackage.Plan.Items | Where-Object ItemId -CEQ $operation.ItemId)[0]).MigrationSpec.Metadata;$targetDigest=Get-WsmDeltaExistingScopeDigest $operation.Target $metadataMode $CancellationToken;$backupDigest=Get-WsmDeltaExistingScopeDigest $operation.Backup $metadataMode $CancellationToken
            if($operation.Phase -eq 'Prepared' -and -not $targetDigest -and $backupDigest -ceq $operation.BaseScopeHash){$operation.Phase='OldMoved';$transaction.Phase='Switching';$transaction.UpdatedUtc=Get-WsmUtc;Write-WsmJson $transactionPath $transaction}
            if($operation.Phase -in @('Prepared','OldMoved') -and $targetDigest -ceq $operation.ExpectedCurrentHash -and $backupDigest -ceq $operation.BaseScopeHash){$operation.Phase='NewMoved';$transaction.Phase='Switching';$transaction.UpdatedUtc=Get-WsmUtc;Write-WsmJson $transactionPath $transaction}
            if($operation.Phase -eq 'Prepared' -and $targetDigest -ceq $operation.BaseScopeHash){Assert-WsmCancellationBoundary $CancellationToken 'BeforeDeltaAtomicExchange';if([IO.Directory]::Exists($operation.Target)){[IO.Directory]::Move($operation.Target,$operation.Backup)}else{[IO.File]::Move($operation.Target,$operation.Backup)};Invoke-WsmDeltaFaultPoint 'AfterOldRootMoved' ([pscustomobject]@{ItemId=$operation.ItemId;Target=$operation.Target;Backup=$operation.Backup;Staging=$operation.Staging});$operation.Phase='OldMoved';$transaction.Phase='Switching';$transaction.UpdatedUtc=Get-WsmUtc;Write-WsmJson $transactionPath $transaction;$targetDigest=''}
            if($operation.Phase -eq 'OldMoved' -and -not $targetDigest){if([IO.Directory]::Exists($operation.Staging)){[IO.Directory]::Move($operation.Staging,$operation.Target)}elseif([IO.File]::Exists($operation.Staging)){[IO.File]::Move($operation.Staging,$operation.Target)}else{throw 'Prepared delta staging root missing; previous scope retained.'};Invoke-WsmDeltaFaultPoint 'AfterNewRootMovedBeforeJournal' ([pscustomobject]@{ItemId=$operation.ItemId;Target=$operation.Target;Backup=$operation.Backup;Staging=$operation.Staging});$operation.Phase='NewMoved';$transaction.Phase='Switching';$transaction.UpdatedUtc=Get-WsmUtc;Write-WsmJson $transactionPath $transaction;$targetDigest=Get-WsmFileScopeDigest $operation.Target (@($currentPackage.Plan.Items | Where-Object ItemId -CEQ $operation.ItemId)[0].MigrationSpec.Metadata)}
            if($operation.Phase -eq 'NewMoved' -and $targetDigest -cne $operation.ExpectedCurrentHash){throw 'Switched target differs from prepared delta hash; retain old root and reconcile.'}
            if($operation.Phase -eq 'Prepared' -and $targetDigest -cne $operation.BaseScopeHash){throw 'Target changed since delta preflight; retain staging and reconcile.'}
        }
        $transaction.Phase='Switched';$transaction.UpdatedUtc=Get-WsmUtc;Write-WsmJson $transactionPath $transaction
        $promotionState=Get-WsmOperationState $paths $currentPackage -AllowRecovery;Assert-WsmDeltaStagedAdapters $currentPackage $promotionState 'BeforeGenerationPromotion'
        $state=Write-WsmDeltaOperationState $paths $currentPackage $transaction;$transaction.Phase='Completed';$transaction.UpdatedUtc=Get-WsmUtc;Write-WsmJson $transactionPath $transaction
        [pscustomobject]@{PairId=$state.PairId;ManifestHash=$state.ManifestHash;Generation=$state.Generation;Stage=$state.Stage;ChangedItems=@($transaction.Operations | ForEach-Object ItemId);TransactionPath=$transactionPath;DeltaPackageManifestPath=$state.DeltaPackageManifestPath;DeltaPackageManifestHash=$state.DeltaPackageManifestHash;Mode='IsolatedPilot';ProductionVerified=$false}
    }
}
function Repair-WsmArtifactDeltaRestore {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$TransportPath,[Parameter(Mandatory)][string]$ExpectedTransportHash,[Parameter(Mandatory)][string]$ImportedDirectory,[Parameter(Mandatory)][string]$TargetStateDirectory,[object[]]$GeneralHostEvidence=@(),$CancellationToken=$null)
    Invoke-WsmArtifactDeltaRestore -TransportPath $TransportPath -ExpectedTransportHash $ExpectedTransportHash -ImportedDirectory $ImportedDirectory -TargetStateDirectory $TargetStateDirectory -GeneralHostEvidence $GeneralHostEvidence -CancellationToken $CancellationToken -Confirm:$false
}
