function Get-WsmMachineEnvironment { [Environment]::GetEnvironmentVariables('Machine') }
function Get-WsmHostsText { [IO.File]::ReadAllText((Join-Path $env:windir 'System32\drivers\etc\hosts')) }
function New-WsmComAdminCatalog { New-Object -ComObject COMAdmin.COMAdminCatalog }
function Get-WsmIisRedirectionText { $path=Join-Path $env:windir 'System32\inetsrv\config\redirection.config';if([IO.File]::Exists($path)){[IO.File]::ReadAllText($path)} }
function Get-WsmEnterpriseDiscovery([string]$HostId,[switch]$Deep) {
    function EnterpriseProbe([string]$Category,[string]$Name,[scriptblock]$Action){try{& $Action}catch{$status='Failed';if($_.Exception -is [UnauthorizedAccessException] -or $_.FullyQualifiedErrorId -match 'Unauthorized|PermissionDenied'){$status='PermissionDenied'};New-WsmItem $HostId $Category CollectorFailure $Name ('enterprise:'+ $Name) @{ErrorType=$_.Exception.GetType().FullName} @() $status}}
    EnterpriseProbe Roles 'role-matrix' {
        $features=@(Get-WindowsFeature -ErrorAction Stop);$map=[ordered]@{'AD'='AD-Domain-Services';'DNS'='DNS';'DHCP'='DHCP';'CA'='ADCS-Cert-Authority';'Cluster'='Failover-Clustering';'MSMQ'='MSMQ';'DFSNamespace'='FS-DFS-Namespace';'DFSReplication'='FS-DFS-Replication';'Print'='Print-Server';'RDS'='RDS-RD-Server';'WSUS'='UpdateServices';'HyperV'='Hyper-V'}
        foreach($entry in $map.GetEnumerator()){$feature=@($features | Where-Object Name -CEQ $entry.Value);if($feature.Count -ne 1){New-WsmItem $HostId Roles RolePresence $entry.Key ('role:'+ $entry.Key) @{FeatureName=$entry.Value;RequiresDedicatedProcedure=$true;Detection='Feature unavailable on this OS; not evidence of absence'} @() Unsupported}elseif($feature[0].Installed){New-WsmItem $HostId Roles RolePresence $entry.Key ('role:'+ $entry.Key) @{FeatureName=$entry.Value;RequiresDedicatedProcedure=$true;Installed=$true} @() Partial}else{New-WsmItem $HostId Roles RolePresence $entry.Key ('role:'+ $entry.Key) @{FeatureName=$entry.Value;Installed=$false;Detection='Successful installed-feature query'} @() NotInstalled}}
    }
    if(-not $Deep){New-WsmItem $HostId Roles DiscoveryRequirement 'Deep enterprise/security inventory not requested' 'deep-discovery-required' @{NextStep='Run inventory with -DeepDiscovery for COM+, role objects, shared IIS and service/task ACL evidence';NotEvidenceOfAbsence=$true} @() Unsupported;return}
    EnterpriseProbe Runtime 'complus' {
        $catalog=New-WsmComAdminCatalog;$apps=$catalog.GetCollection('Applications');$apps.Populate();foreach($app in $apps){$components=$catalog.GetCollection('Components',$app.Key);$components.Populate();$rows=@(foreach($component in $components){[pscustomobject]@{Name=$component.Name;Key=[string]$component.Key;CLSID=[string]$component.Value('CLSID');DLL=[string]$component.Value('DLL')}});New-WsmItem $HostId Runtime ComPlusApplication $app.Name ([string]$app.Key) @{Name=$app.Name;Identity=[string]$app.Value('Identity');Components=$rows;RequiresExportInstallAndIdentityProcedure=$true} @() Partial}
    }
    EnterpriseProbe Storage 'dfs-and-nfs' {
        foreach($command in @('Get-DfsnRoot','Get-DfsrMembership','Get-NfsShare')){if(Get-Command $command -ErrorAction SilentlyContinue){$parameters=@{ErrorAction='Stop'};if($command -eq 'Get-DfsnRoot'){$parameters.Path='\\'+$env:COMPUTERNAME+'\*'};if($command -eq 'Get-DfsrMembership'){$parameters.ComputerName=$env:COMPUTERNAME;$parameters.GroupName='*'};foreach($entry in (& $command @parameters)){New-WsmItem $HostId Storage StorageRoleObject $command ($command+'|'+($entry | ConvertTo-Json -Depth 8 -Compress)) @{Command=$command;Configuration=$entry;RequiresProductProcedure=$true} @() Partial}}else{New-WsmItem $HostId Storage UnsupportedCollector $command ('collector:'+ $command) @{RequiredCommand=$command;DoesNotEstablishRoleAbsence=$true} @() Unsupported}}
    }
    EnterpriseProbe Database 'queue-and-database-tools' {
        foreach($command in @('Get-MsmqQueue')){if(Get-Command $command -ErrorAction SilentlyContinue){foreach($entry in (& $command -ErrorAction Stop)){New-WsmItem $HostId Database ProductObject $command ($command+'|'+($entry | ConvertTo-Json -Depth 8 -Compress)) @{Command=$command;Metadata=$entry;Consistency='Requires native backup/export and actual restore rehearsal'} @() Partial}}else{New-WsmItem $HostId Database UnsupportedCollector $command ('collector:'+ $command) @{RequiredCommand=$command;DoesNotEstablishProductAbsence=$true} @() Unsupported}}
    }
    EnterpriseProbe Roles 'dns-dhcp' {
        foreach($command in @('Get-DnsServerZone','Get-DhcpServerv4Scope')){if(Get-Command $command -ErrorAction SilentlyContinue){foreach($entry in (& $command -ErrorAction Stop)){New-WsmItem $HostId Roles ProductObject $command ($command+'|'+($entry | ConvertTo-Json -Depth 8 -Compress)) @{Command=$command;Metadata=$entry;RequiresNativeExportAndAuthorization=$true} @() Partial}}else{New-WsmItem $HostId Roles UnsupportedCollector $command ('collector:'+ $command) @{RequiredCommand=$command;DoesNotEstablishRoleAbsence=$true} @() Unsupported}}
    }
    EnterpriseProbe Web 'iis-shared-and-http' {
        $text=Get-WsmIisRedirectionText;if($null -ne $text){[void](Read-WsmXml $text);New-WsmItem $HostId Web IisRedirection 'IIS shared config redirection' 'iis-redirection' @{Xml=$text;EncryptionKeyTransferRequiresDedicatedProcedure=$true} @() Partial}else{New-WsmItem $HostId Web IisRedirection 'IIS redirection file absent' 'iis-redirection' @{SuccessfulFilePresenceCheck=$true} @() NotInstalled}
        if(Get-Command Get-WebBinding -ErrorAction SilentlyContinue){foreach($b in Get-WebBinding){New-WsmItem $HostId Web IisBinding ([string]$b.bindingInformation) ([string]$b.ItemXPath+'|'+[string]$b.protocol+'|'+[string]$b.bindingInformation) ($b | Select-Object protocol,bindingInformation,certificateHash,certificateStoreName,sslFlags) }}else{New-WsmItem $HostId Web UnsupportedCollector 'IIS binding API' 'collector:iis-binding' @{RequiredCommand='Get-WebBinding';DoesNotEstablishIisAbsence=$true} @() Unsupported}
        New-WsmItem $HostId Network DiscoveryRequirement 'HTTP.sys / WinHTTP / SPN / external endpoints' 'http-sys-and-external-review' @{Checks=@('HTTP.sys SSL and URL ACL registrations','WinHTTP proxy','SPNs and Kerberos delegation','DNS/PTR/load-balancer/allowlists','SMTP/API/UNC/DB clients','Certificate private-key ACL','External consumers and long-cycle jobs');OwnerConfirmationRequired=$true} @() Unsupported
    }
    EnterpriseProbe Identity 'service-and-task-security' {
        foreach($s in Get-CimInstance Win32_Service){try{$sddl=Get-WsmServiceSecurity $s.Name;New-WsmItem $HostId Identity ServiceSecurity $s.Name ('service-security:'+ $s.Name) @{ServiceName=$s.Name;Sddl=$sddl;SidMappingRequired=$true}}catch{$status='Failed';if($_.Exception -is [UnauthorizedAccessException] -or $_.FullyQualifiedErrorId -match 'Unauthorized|PermissionDenied'){$status='PermissionDenied'};New-WsmItem $HostId Identity CollectorFailure $s.Name ('service-security:'+ $s.Name) @{ErrorType=$_.Exception.GetType().FullName} @() $status}}
        $scheduler=New-WsmTaskScheduler;$folders=New-Object 'System.Collections.Generic.Stack[object]';$folders.Push($scheduler.GetFolder('\'))
        while($folders.Count){$folder=$folders.Pop();New-WsmItem $HostId Identity TaskFolderSecurity $folder.Path ('task-folder:'+ $folder.Path) @{Path=$folder.Path;Sddl=$folder.GetSecurityDescriptor(7);SidMappingRequired=$true};foreach($t in $folder.GetTasks(1)){New-WsmItem $HostId Identity TaskSecurity $t.Path ('task-security:'+ $t.Path) @{Path=$t.Path;Sddl=$t.GetSecurityDescriptor(7);SidMappingRequired=$true}};foreach($f in $folder.GetFolders(0)){$folders.Push($f)}}
    }
    EnterpriseProbe System 'execution-deployment-policy' {
        $policies=@(Get-ExecutionPolicy -List | Select-Object Scope,ExecutionPolicy);$appLocker='CollectorUnavailable';if(Get-Command Get-AppLockerPolicy -ErrorAction SilentlyContinue){$appLocker=Get-AppLockerPolicy -Effective -Xml};New-WsmItem $HostId System ExecutionPolicy 'Execution policy / effective AppLocker' 'deployment-policy' @{ExecutionPolicies=$policies;AppLockerXml=$appLocker;LanguageMode=[string]$ExecutionContext.SessionState.LanguageMode;WdacRequiresSecurityOwnerValidation=$true;NeverAutoChangesPolicy=$true} @() Partial
    }
}
function Export-WsmRawEvidenceManifest {
    param([string]$InventoryPath,[string]$ExpectedHash,[string]$Path)
    $i=Read-WsmTrustedJson $InventoryPath $ExpectedHash;Assert-WsmInventory $i
    $position=0;$rows=@(foreach($item in $i.Items){[pscustomobject]@{ItemId=$item.ItemId;Category=$item.Category;Kind=$item.Kind;Status=$item.Status;SettingsHash=$item.SettingsHash;EvidenceFile=[IO.Path]::GetFileName($InventoryPath);EvidencePointer=('/Items/'+$position+'/Settings');Collector=$item.Adapter;RawMayContainSecrets=$true};$position++})
    Write-WsmJson $Path ([pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='RawEvidenceManifest';Source=$i.Source;InventoryRevision=$i.Revision;InventoryHash=$ExpectedHash;CreatedUtc=$i.CreatedUtc;Items=$rows;Scope='All collected objects and explicit failures/gaps; not proof every external dependency was discovered'})
    [pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path).Hash;Items=$rows.Count}
}
