function Get-WsmLabCheck([string]$Code,[string]$Status,[string]$ItemId='',[string]$Adapter='',[string]$Field='',[string]$ExpectedHash='',[string]$ObservedHash='',[string]$Hint='',[string]$FailureCategory='',$NativeCode=$null,[string]$HResult='') {
    [pscustomobject][ordered]@{Code=$Code;Status=$Status;ItemId=$ItemId;Adapter=$Adapter;Field=$Field;ExpectedSHA256=$ExpectedHash;ObservedSHA256=$ObservedHash;FailureCategory=$FailureCategory;NativeCode=$NativeCode;HResult=$HResult;Hint=$Hint}
}
function Get-WsmLabSafeFailure($Failure) {
    try{$details=Get-WsmFailureDetails $Failure;[pscustomobject]@{Category=[string]$details.Category;NativeCode=$details.NativeCode;HResult=[string]$details.HResult}}
    catch{[pscustomobject]@{Category='OperationFailure';NativeCode=$null;HResult=''}}
}
function Test-WsmLabPathOverlap([string]$Candidate,[string[]]$Scopes) {
    $path=(Get-WsmPhysicalPath $Candidate).TrimEnd('\');foreach($scopeValue in $Scopes){if([string]::IsNullOrWhiteSpace($scopeValue)){continue};$scope=(Get-WsmPhysicalPath $scopeValue).TrimEnd('\');if($path -ieq $scope -or $path.StartsWith($scope+'\',[StringComparison]::OrdinalIgnoreCase) -or $scope.StartsWith($path+'\',[StringComparison]::OrdinalIgnoreCase)){return $true}};$false
}
function Test-WsmLabFileScopeCheck($Item,$Package,[string]$Root) {
    $itemId=[string]$Item.ItemId;$adapter='FileScope'
    try{$result=Test-WsmFileScope $Item $Package $Root;if($result.Passed){Get-WsmLabCheck 'FileScopeExact' 'PASS' $itemId $adapter 'FileScopeContentAndMetadata' '' ([string]$result.ActualHash) 'Every selected file matched its approved artifact content and metadata.'}else{Get-WsmLabCheck 'FileScopeExact' 'FAIL' $itemId $adapter 'FileScopeContentAndMetadata' '' ([string]$result.ActualHash) 'Approved scope differs or is incomplete.'}}
    catch{$failure=Get-WsmLabSafeFailure $_;Get-WsmLabCheck 'FileScopeReadable' 'Blocked' $itemId $adapter 'ApprovedScope' '' '' 'Scope could not be safely read; inspect the host locally.' $failure.Category $failure.NativeCode $failure.HResult}
}
function Assert-WsmLabStateBinding($Manifest,[string]$ManifestHash,[string]$StateDirectory) {
    if(-not [IO.Directory]::Exists($StateDirectory)){throw (New-WsmContractError 'Target operation state directory is absent.')}
    $pairRoot=Join-Path ([IO.Path]::GetFullPath($StateDirectory)) ([string]$Manifest.PairId);Assert-WsmNoReparse $pairRoot
    $statePath=Join-Path $pairRoot 'state.json';$journalPath=Join-Path $pairRoot 'journal.jsonl'
    if(-not [IO.File]::Exists($statePath) -or -not [IO.File]::Exists($journalPath)){throw (New-WsmContractError 'Target operation state or journal is absent.')}
    Assert-WsmNoReparse $statePath;Assert-WsmNoReparse $journalPath;$state=Read-WsmJson $statePath;Assert-WsmEnvelope $state 'OperationState'
    if($state.PairId -cne $Manifest.PairId -or $state.TargetFingerprint -cne $Manifest.Target.Fingerprint -or $state.PlanHash -ine $Manifest.PlanHash -or $state.ManifestHash -ine $ManifestHash -or $state.Generation -ne $Manifest.Generation){throw (New-WsmContractError 'Target operation state is foreign or bound to another package generation.')}
    $journal=Test-WsmJournal $StateDirectory $Manifest.PairId;if(-not $journal.Consistent){throw (New-WsmContractError 'Target operation journal is inconsistent.')}
    [pscustomobject]@{State=$state;Journal=$journal;Root=$pairRoot}
}
function Export-WsmLabValidationReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$OutputDirectory,
        [Parameter(Mandatory)][ValidateSet('Source','Target')][string]$Role,
        [string]$ManifestPath,
        [string]$ExpectedHash,
        [string]$StateDirectory,
        [ValidateSet('Staged','Final')][string]$Phase='Staged',
        [ValidateRange(1,1000)][int]$TextCheckLimit=200
    )
    $operationLock=$null
    try {
    if([bool]$ManifestPath -ne [bool]$ExpectedHash){throw (New-WsmContractError 'ManifestPath and ExpectedHash must be supplied together.')}
    if($Role -eq 'Target' -and $ManifestPath -and -not $StateDirectory){throw (New-WsmContractError 'Target lab verification with a package requires its approved operation state directory.')}
    if($ExpectedHash -and $ExpectedHash -notmatch '^[A-Fa-f0-9]{64}$'){throw (New-WsmContractError 'ExpectedHash must be a SHA256 value.')}
    $languageMode=[string]$ExecutionContext.SessionState.LanguageMode
    if($languageMode -ceq 'FullLanguage'){$identity=Get-WsmMachineIdentity}else{$preflight=Get-WsmPreflight;$identity=[pscustomobject]@{Fingerprint='';Name='';OS=$preflight.OS;Version=$preflight.Version;IsServer=[bool]$preflight.IsServer;Administrator=[bool]$preflight.Administrator;Is64Bit=[bool]$preflight.Is64Bit}}
    Assert-WsmFields $identity @('Fingerprint','Name','OS','Version','IsServer','Administrator','Is64Bit') @('Fingerprint','OS','Version','IsServer','Administrator','Is64Bit');if(($identity.Fingerprint -and ($identity.Fingerprint -isnot [string] -or $identity.Fingerprint -notmatch '^[a-fA-F0-9]{64}$')) -or $identity.IsServer -isnot [bool] -or $identity.Administrator -isnot [bool] -or $identity.Is64Bit -isnot [bool]){throw (New-WsmContractError 'Host identity has an invalid environment shape.')};if($ManifestPath -and -not $identity.Fingerprint){throw (New-WsmContractError 'Trusted package verification requires FullLanguage machine identity checks.')};$toolFingerprint=Get-WsmToolFingerprint;if($toolFingerprint -isnot [string] -or $toolFingerprint -notmatch '^[a-fA-F0-9]{64}$'){throw (New-WsmContractError 'Installed tool fingerprint is invalid.')}
    $installationType='Unknown'
    try{$installationType=[string](Get-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name InstallationType -ErrorAction Stop).InstallationType}catch{}
    $uiCulture=[Globalization.CultureInfo]::CurrentUICulture.Name;$culture=[Globalization.CultureInfo]::CurrentCulture.Name
    $psEdition='Desktop';if($PSVersionTable.ContainsKey('PSEdition')){$psEdition=[string]$PSVersionTable.PSEdition}
    $manifest=$null;$package=$null;$stateBinding=$null
    if($ManifestPath){
        # Read package and identity bindings before creating any output, so wrong-host or tampered inputs leave no report artifact.
        $package=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;$manifest=$package.Manifest
        $expectedFingerprint=[string]$manifest.Source.Fingerprint;if($Role -eq 'Target'){$expectedFingerprint=[string]$manifest.Target.Fingerprint}
        if($identity.Fingerprint -cne $expectedFingerprint){throw (New-WsmContractError 'This host does not match the approved package role fingerprint.')}
        if($package.Plan.ToolFingerprint -ine $toolFingerprint){throw (New-WsmContractError 'Installed tool fingerprint differs from approved plan tool fingerprint.')}
        if($Role -eq 'Target'){
            $pairRoot=Join-Path ([IO.Path]::GetFullPath($StateDirectory)) $manifest.PairId;Assert-WsmNoReparse $pairRoot
            $lockPath=Join-Path $pairRoot '.wsm.lock';Assert-WsmNoReparse $lockPath
            if(-not [IO.File]::Exists($lockPath)){throw (New-WsmContractError 'Target operation lock is absent; no completed restore checkpoint can be adopted.')}
            try{$operationLock=[IO.File]::Open($lockPath,'Open','Read','None')}catch{throw (New-WsmContractError 'Target operation is busy or its lock cannot be read; retry the report after the local operation finishes.')}
            $stateBinding=Assert-WsmLabStateBinding $manifest $ExpectedHash $StateDirectory
        }
    }
    $included=@();$scopeRoots=New-Object 'System.Collections.Generic.List[string]'
    if($manifest){$included=@($package.Plan.Items | Where-Object Decision -CEQ Include);foreach($item in $included){if($item.MigrationSpec.Adapter -eq 'FileScope'){$scopeRoots.Add([string]$item.MigrationSpec.SourcePath);$scopeRoots.Add([string]$item.MigrationSpec.TargetPath)}}}
    $protectedPaths=@($scopeRoots.ToArray());if($StateDirectory){$protectedPaths+=@($StateDirectory)}
    $outputRoot=[IO.Path]::GetFullPath($OutputDirectory);Assert-WsmNoReparse $outputRoot;if(Test-WsmLabPathOverlap $outputRoot $protectedPaths){throw (New-WsmContractError 'Report output overlaps an approved file scope or operation state directory.')};if(-not [IO.Directory]::Exists($outputRoot)){[void][IO.Directory]::CreateDirectory($outputRoot)}
    $runRoot=Join-Path $outputRoot ('lab-validation-'+[Guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($runRoot);Protect-WsmDirectory $runRoot
    $checks=New-Object 'System.Collections.Generic.List[object]'
    $osDescription=[string]$identity.OS;$osVersion=[string]$identity.Version
    $checks.Add((Get-WsmLabCheck 'HostIsServer' $(if($identity.IsServer){'PASS'}else{'FAIL'}) '' '' 'WindowsServer' '' '' 'Host operating system role.'))
    $checks.Add((Get-WsmLabCheck 'Administrator' $(if($identity.Administrator){'PASS'}else{'FAIL'}) '' '' 'ElevatedAdministrator' '' '' 'Current token elevation.'))
    $checks.Add((Get-WsmLabCheck 'ProcessArchitecture' $(if($identity.Is64Bit){'PASS'}else{'FAIL'}) '' '' '64Bit' '' '' 'PowerShell process architecture.'))
    $checks.Add((Get-WsmLabCheck 'LanguageMode' $(if($languageMode -ceq 'FullLanguage'){'PASS'}else{'FAIL'}) '' '' 'FullLanguage' '' '' 'PowerShell language mode.'))
    $checks.Add((Get-WsmLabCheck 'InstalledToolFingerprint' 'PASS' '' '' 'ToolBytes' $toolFingerprint $toolFingerprint 'Fingerprint of locally installed migration tool files.'))
    $environmentCapabilities=New-Object 'System.Collections.Generic.List[object]'
    if($manifest){foreach($item in $included){$adapter=[string]$item.MigrationSpec.Adapter;$commands=@(Get-WsmAdapterRequiredCommands $adapter);if($adapter -eq 'FileScope'){$commands=@()};if($adapter -eq 'ManualWorkflow'){$commands=@()};foreach($command in $commands){if($environmentCapabilities -notcontains $command){$environmentCapabilities.Add($command)}}}}
    foreach($command in $environmentCapabilities){$available=$null -ne (Get-Command $command -ErrorAction SilentlyContinue);$checks.Add((Get-WsmLabCheck 'AdapterCommand' $(if($available){'PASS'}else{'FAIL'}) '' '' ([string]$command) '' '' $(if($available){'Required local command is available.'}else{'Required local command is unavailable.'})))}
    if(-not $manifest){$checks.Add((Get-WsmLabCheck 'ApprovedPackage' 'NotTested' '' '' 'ExactPackageBinding' '' '' 'No independently trusted package was supplied; this is environment readiness only.'))}
    else {
        $checks.Add((Get-WsmLabCheck 'ApprovedPackage' 'PASS' '' '' 'ManifestAndPlan' ([string]$ExpectedHash) ([string]$package.SHA256) 'Package, plan, artifact index and payload hashes validated.'))
        $checks.Add((Get-WsmLabCheck 'RoleFingerprint' 'PASS' '' '' $Role $expectedFingerprint ([string]$identity.Fingerprint) 'Machine identity matches the exact approved source or target binding.'))
        if($Role -eq 'Source'){
            $collectorRoot=Join-Path $runRoot 'collector';[void][IO.Directory]::CreateDirectory($collectorRoot);Protect-WsmDirectory $collectorRoot
            try {
                $inventoryResult=Export-WsmInventory -OutputDirectory $collectorRoot -DeepDiscovery:($package.Plan.Source.PSObject.Properties['DiscoveryDepth'] -and $package.Plan.Source.DiscoveryDepth -ceq 'Deep')
                $inventory=Read-WsmTrustedJson $inventoryResult.Path $inventoryResult.SHA256
                if($inventory.Source.Fingerprint -cne $manifest.Source.Fingerprint){throw 'Collector source binding differs.'}
                $checks.Add((Get-WsmLabCheck 'NativeInventoryCollected' 'PASS' '' '' 'CollectorSnapshot' '' ([string]$inventoryResult.SHA256) 'Read-only native collector snapshot is retained in the protected report directory.'))
                foreach($item in $included){if($item.PSObject.Properties['Kind'] -and $item.Kind -ceq 'ManualItem'){$checks.Add((Get-WsmLabCheck 'SourceInventoryBinding' 'NotTested' ([string]$item.ItemId) ([string]$item.MigrationSpec.Adapter) 'ManualInventoryItem' '' '' 'Owner-added manual inventory item requires separate evidence.'));$checks.Add((Get-WsmLabCheck 'BusinessEvidence' 'NotTested' ([string]$item.ItemId) ([string]$item.MigrationSpec.Adapter) 'OwnerBusinessChecks' '' '' 'Manual business procedure remains unverified.'));continue};$matches=@($inventory.Items | Where-Object ItemId -CEQ $item.ItemId);$status='PASS';$observed='';$hint='Native collector item identity and exact settings fingerprint matched the approved inventory.';if($matches.Count -ne 1){$status='FAIL';$hint='Native inventory item is missing or ambiguous.'}else{$observed=[string]$matches[0].SettingsHash;if($observed -ine [string]$item.SettingsHash){$status='FAIL';$hint='Native settings fingerprint differs from approved inventory.'};if($matches[0].Status -ne 'Success'){$status='FAIL';$hint='Native collector did not complete this item.'}};$checks.Add((Get-WsmLabCheck 'SourceInventoryBinding' $status ([string]$item.ItemId) ([string]$item.MigrationSpec.Adapter) 'SettingsHash' ([string]$item.SettingsHash) $observed $hint))
                    if($item.MigrationSpec.Adapter -eq 'FileScope'){$scopeResult=Test-WsmLabFileScopeCheck $item $package ([string]$item.MigrationSpec.SourcePath);$checks.Add($scopeResult)}elseif($item.MigrationSpec.Adapter -eq 'ManualWorkflow'){$checks.Add((Get-WsmLabCheck 'ManualWorkflow' 'NotTested' ([string]$item.ItemId) 'ManualWorkflow' 'BusinessProcedure' '' '' 'Manual procedure requires owner execution and separate business evidence.'))};$businessCount=0;if($item.MigrationSpec.PSObject.Properties['BusinessChecks']){$businessCount=@($item.MigrationSpec.BusinessChecks).Count};$checks.Add((Get-WsmLabCheck 'BusinessEvidence' 'NotTested' ([string]$item.ItemId) ([string]$item.MigrationSpec.Adapter) 'OwnerBusinessChecks' '' '' ('Business acceptance remains unsatisfied; checks recorded: '+$businessCount+'.')))
                }
            } catch {
                $failure=Get-WsmLabSafeFailure $_;$checks.Add((Get-WsmLabCheck 'NativeInventoryCollected' 'Blocked' '' '' 'CollectorSnapshot' '' '' 'Native collector could not complete safely; inspect the protected local output and rerun.' $failure.Category $failure.NativeCode $failure.HResult))
                foreach($item in $included){
                    if($item.MigrationSpec.Adapter -eq 'ManualWorkflow'){$checks.Add((Get-WsmLabCheck 'ManualWorkflow' 'NotTested' ([string]$item.ItemId) 'ManualWorkflow' 'BusinessProcedure' '' '' 'Manual procedure requires owner execution and separate business evidence.'))}
                    elseif($item.MigrationSpec.Adapter -eq 'FileScope'){$checks.Add((Get-WsmLabCheck 'FileScopeExact' 'NotTested' ([string]$item.ItemId) 'FileScope' 'FileScopeContentAndMetadata' '' '' 'Source collector did not complete.'))}
                    $checks.Add((Get-WsmLabCheck 'BusinessEvidence' 'NotTested' ([string]$item.ItemId) ([string]$item.MigrationSpec.Adapter) 'OwnerBusinessChecks' '' '' 'Business acceptance remains unsatisfied by this technical report.'))
                }
            }
        } else {
            $state=$stateBinding.State;$checks.Add((Get-WsmLabCheck 'OperationStateBinding' 'PASS' '' '' 'PairPlanManifestGeneration' ([string]$ExpectedHash) ([string]$state.ManifestHash) 'State and durable journal match the exact package generation and target.'))
            $checks.Add((Get-WsmLabCheck 'JournalConsistency' 'PASS' '' '' 'SequenceAndHashChain' ([string]$state.JournalHash) ([string]$stateBinding.Journal.JournalHash) 'Journal chain matches the state checkpoint.'))
            $validStages=@('Succeeded','ManualEvidenceRequired','RebootRequired');if($Phase -eq 'Final'){$validStages+=@('PostCutoverValidationRequired')};$stageStatus='PASS';if($state.Stage -notin $validStages -or @($state.PendingOperations).Count){$stageStatus='Blocked'};$checks.Add((Get-WsmLabCheck 'OperationStateStage' $stageStatus '' '' $Phase '' '' $(if($stageStatus -eq 'PASS'){'Operation is at a completed checkpoint for this phase.'}else{'Operation is incomplete, failed, cancelled, or has pending work; reconcile before treating readback as complete.'})))
            if($Phase -ceq 'Final'){$activationStatus='Blocked';if($state.Cutover -and $state.Cutover.Stage -ceq 'Activated' -and $state.Stage -ceq 'PostCutoverValidationRequired'){$activationStatus='PASS'};$checks.Add((Get-WsmLabCheck 'FinalActivation' $activationStatus '' '' 'CompletedActivationCheckpoint' '' '' 'Final phase requires the durable completed activation checkpoint.'))}
            if($state.Cutover -and $state.Cutover.NewTransactionsPossible){$checks.Add((Get-WsmLabCheck 'DataReconciliation' 'Blocked' '' '' 'PostActivationTransactions' '' '' 'New transactions may exist; owner reconciliation evidence remains required.'))}
            foreach($item in $included){$id=[string]$item.ItemId;$adapter=[string]$item.MigrationSpec.Adapter;$businessCount=0;if($item.MigrationSpec.PSObject.Properties['BusinessChecks']){$businessCount=@($item.MigrationSpec.BusinessChecks).Count};$checks.Add((Get-WsmLabCheck 'BusinessEvidence' 'NotTested' $id $adapter 'OwnerBusinessChecks' '' '' ('Business acceptance remains unsatisfied; checks recorded: '+$businessCount+'.')));if($adapter -eq 'ManualWorkflow'){$checks.Add((Get-WsmLabCheck 'ManualWorkflow' 'NotTested' $id $adapter 'BusinessProcedure' '' '' 'Manual procedure requires owner execution and separate business evidence.'));continue};$records=@($state.Items | Where-Object ItemId -CEQ $id);$ownedStatus='PASS';$ownershipHint='Exactly one successful tool-owned operation record claims this item.';if($records.Count -ne 1){$ownedStatus='FAIL';$ownershipHint='Expected exactly one durable operation record.'}elseif($records[0].Status -notin @('Succeeded','RebootRequired') -or -not $records[0].CreatedByTool){if($adapter -eq 'WindowsFeature' -and $records[0].Status -eq 'Succeeded'){$ownedStatus='NotTested';$ownershipHint='Feature was verified as pre-existing and has no tool ownership receipt.'}elseif($records[0].Status -eq 'RebootRequired' -and $records[0].CreatedByTool){$ownedStatus='PASS'}else{$ownedStatus='Blocked';$ownershipHint='Operation did not finish with a verified owned record.'}};$checks.Add((Get-WsmLabCheck 'TargetOwnershipReceipt' $ownedStatus $id $adapter 'UniqueOwnedOperationRecord' '' '' $ownershipHint))
                if($records.Count -eq 1 -and $records[0].Status -eq 'RebootRequired'){$bootPassed=$false;try{$bootAfter=Get-WsmBootStamp;$bootPassed=($records[0].BootBefore -and $bootAfter -and ([DateTime]::Parse($bootAfter).ToUniversalTime() -gt [DateTime]::Parse([string]$records[0].BootBefore).ToUniversalTime()))}catch{};$checks.Add((Get-WsmLabCheck 'RebootBarrier' $(if($bootPassed){'PASS'}else{'Blocked'}) $id $adapter 'PostBootObserved' '' '' $(if($bootPassed){'A later boot was observed.'}else{'Required reboot is not confirmed.'})))}
                if($adapter -eq 'FileScope'){$check=Test-WsmLabFileScopeCheck $item $package ([string]$item.MigrationSpec.TargetPath);$checks.Add($check);continue}
                try{$receipts=@();if($adapter -eq 'ScheduledTask'){$receipts=Get-WsmTaskSecurityReceiptsForSpec $item.MigrationSpec (Get-WsmTaskSecurityOwnershipReceipts $state)};$adapterCheck=Test-WsmAdapterConfiguration $item.MigrationSpec $Phase $receipts;$status='PASS';if(-not $adapterCheck.Passed){$status='FAIL'};$actualHash=Get-WsmHashText ($adapterCheck.Actual | ConvertTo-Json -Depth 20 -Compress);$desiredHash=Get-WsmHashText ($item.MigrationSpec | ConvertTo-Json -Depth 40 -Compress);$hint='Desired spec SHA256='+$desiredHash+'; observed state SHA256='+$actualHash+'; exact native field comparison '+$status+'.';$checks.Add((Get-WsmLabCheck 'AdapterConfiguration' $status $id $adapter 'DesiredSpecAndObservedStateDigests' '' $actualHash $hint))}catch{$failure=Get-WsmLabSafeFailure $_;$checks.Add((Get-WsmLabCheck 'AdapterConfiguration' 'Blocked' $id $adapter $Phase '' '' 'Native read-only adapter inspection failed; inspect the host locally.' $failure.Category $failure.NativeCode $failure.HResult))}
            }
        }
    }
    $counts=[ordered]@{PASS=@($checks | Where-Object Status -CEQ PASS).Count;FAIL=@($checks | Where-Object Status -CEQ FAIL).Count;Blocked=@($checks | Where-Object Status -CEQ Blocked).Count;NotTested=@($checks | Where-Object Status -CEQ NotTested).Count}
    $readiness='ReadyForReview';if($counts.FAIL -or $counts.Blocked){$readiness='AttentionRequired'}elseif($counts.NotTested){$readiness='NotTested'}
    $orderedTextChecks=@($checks | Sort-Object @{Expression={switch -Exact ($_.Status){FAIL{0}Blocked{1}NotTested{2}PASS{3}default{4}}}},@{Expression='ItemId'},@{Expression='Code'});$shownTextChecks=@($orderedTextChecks | Select-Object -First $TextCheckLimit);$omittedTextChecks=[Math]::Max(0,$orderedTextChecks.Count-$shownTextChecks.Count)
    $report=[pscustomobject][ordered]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='LabValidationReport';RunId=[Guid]::NewGuid().ToString();Role=$Role;Phase=$Phase;ObservedUtc=(Get-WsmUtc);OS=$osDescription;OSVersion=$osVersion;WindowsInstallationType=$installationType;UICulture=$uiCulture;Culture=$culture;PowerShellEdition=$psEdition;PowerShellVersion=$PSVersionTable.PSVersion.ToString();LanguageMode=$languageMode;ToolFingerprint=$toolFingerprint;ObservedMachineFingerprint=$identity.Fingerprint;PairId=$(if($manifest){$manifest.PairId}else{''});Generation=$(if($manifest){$manifest.Generation}else{$null});ManifestHash=$(if($manifest){$ExpectedHash.ToLowerInvariant()}else{''});PlanHash=$(if($manifest){$manifest.PlanHash}else{''});SourceFingerprint=$(if($manifest){$manifest.Source.Fingerprint}else{''});TargetFingerprint=$(if($manifest){$manifest.Target.Fingerprint}else{''});InventoryRevision=$(if($manifest){$manifest.InventoryRevision}else{$null});DecisionRevision=$(if($manifest){$manifest.DecisionRevision}else{$null});StateSequence=$(if($stateBinding){$stateBinding.State.Sequence}else{$null});JournalHash=$(if($stateBinding){$stateBinding.Journal.JournalHash}else{''});Readiness=$readiness;Counts=[pscustomobject]$counts;Checks=$checks.ToArray();TextCheckLimit=$TextCheckLimit;TextChecksShown=$shownTextChecks.Count;TextChecksOmitted=$omittedTextChecks;BusinessValidationRequired=$true;ProductionVerified=$false;TrustLimitations=@('Local machine identity is fingerprint-bound but the report is not signed.','The copied text block is an integrity checksum, not independent proof of who produced it.','Real product behavior and business acceptance require separate owner evidence.','This report never grants production qualification.')}
    $reportPath=Join-Path $runRoot 'lab-validation.json';$textPath=Join-Path $runRoot 'lab-validation.txt';$json=$report | ConvertTo-Json -Depth 12; $jsonBytes=(New-Object Text.UTF8Encoding($false)).GetBytes($json+[Environment]::NewLine);$stream=[IO.File]::Open($reportPath,'CreateNew','Write','None');try{$stream.Write($jsonBytes,0,$jsonBytes.Length);$stream.Flush($true)}finally{$stream.Dispose()};$reportHash=(Get-FileHash -LiteralPath $reportPath -Algorithm SHA256).Hash.ToLowerInvariant()
    $lines=New-Object 'System.Collections.Generic.List[string]';$lines.Add('WSM LAB VALIDATION REPORT');$lines.Add('Copy this complete block back to the migration reviewer.');$lines.Add(('Run ID: '+$report.RunId));$lines.Add(('Role: '+$Role+' | Phase: '+$Phase+' | Readiness: '+$readiness));$lines.Add(('Observed UTC: '+$report.ObservedUtc));$lines.Add(('OS: '+$osDescription+' | Version: '+$osVersion+' | PowerShell: '+$report.PowerShellVersion+' | LanguageMode: '+$languageMode));$lines.Add(('Windows installation type: '+$installationType+' | UI culture: '+$uiCulture+' | Culture: '+$culture+' | PowerShell edition: '+$psEdition));$lines.Add(('Tool fingerprint: '+$toolFingerprint+' | Machine fingerprint: '+$identity.Fingerprint));if($manifest){$lines.Add(('Pair: '+$manifest.PairId+' | Generation: '+$manifest.Generation+' | Manifest SHA256: '+$ExpectedHash.ToLowerInvariant()));$lines.Add(('Plan SHA256: '+$manifest.PlanHash+' | Decision revision: '+$manifest.DecisionRevision));if($stateBinding){$lines.Add(('State sequence: '+$stateBinding.State.Sequence+' | Journal hash: '+$stateBinding.Journal.JournalHash))};$lines.Add(('Source fingerprint: '+$manifest.Source.Fingerprint+' | Target fingerprint: '+$manifest.Target.Fingerprint))}else{$lines.Add('Package binding: none; environment readiness only.')};$lines.Add(('Counts: PASS={0}; FAIL={1}; Blocked={2}; NotTested={3}' -f $counts.PASS,$counts.FAIL,$counts.Blocked,$counts.NotTested));$lines.Add(('Checks shown: {0} / {1}; omitted from this text block: {2}; full list is in the JSON report.' -f $shownTextChecks.Count,$orderedTextChecks.Count,$omittedTextChecks));$lines.Add('Checks:');foreach($check in $shownTextChecks){$label=$check.ItemId;if(-not $label){$label='host'};$field=$check.Field;if(-not $field){$field=$check.Code};$detail=$check.Hint;if($check.ExpectedSHA256 -or $check.ObservedSHA256){$detail+=' expectedSHA256='+$check.ExpectedSHA256+' observedSHA256='+$check.ObservedSHA256};if($check.FailureCategory){$detail+=' failureCategory='+$check.FailureCategory};if($null -ne $check.NativeCode){$detail+=' nativeCode='+$check.NativeCode};if($check.HResult){$detail+=' hresult='+$check.HResult};$lines.Add(('[{0}] {1} | {2} | {3} | {4}' -f $check.Status,$label,$check.Adapter,$field,$detail))};$lines.Add('Business validation: required and not satisfied by this report.');$lines.Add('ProductionVerified: false');$lines.Add('Limitations: report is unsigned; local admin can alter the source state and report. Integrity hash alone does not prove producer identity.');$lines.Add(('JSON report SHA256: '+$reportHash));$text=[string]::Join("`r`n",$lines.ToArray())+"`r`n";$encoding=New-Object Text.UTF8Encoding($true);$textBytes=$encoding.GetPreamble()+$encoding.GetBytes($text);$writer=[IO.File]::Open($textPath,'CreateNew','Write','None');try{$writer.Write($textBytes,0,$textBytes.Length);$writer.Flush($true)}finally{$writer.Dispose()}
    $blocked=($counts.FAIL -gt 0 -or $counts.Blocked -gt 0 -or ($Role -eq 'Target' -and $counts.NotTested -gt 0))
    [pscustomobject][ordered]@{JSONPath=$reportPath;TextPath=$textPath;JSONSHA256=$reportHash;Role=$Role;Readiness=$readiness;Counts=[pscustomobject]$counts;Blocked=$blocked;ProductionVerified=$false;Report=$report}
    } finally {if($operationLock){$operationLock.Dispose()}}
}
