function Test-WsmJournal {
    param([string]$StateDirectory,[string]$PairId)
    $paths=Get-WsmOperationPaths $StateDirectory $PairId;$state=Read-WsmJson $paths.State;$hash='0'*64;$sequence=0
    $matched=($state.Sequence -eq 0 -and $state.JournalHash -ceq $hash)
    Read-WsmJournalEvents $paths | ForEach-Object {$row=$_.Row;if($row.Sequence -ne $sequence+1 -or $row.PreviousHash -cne $hash -or $row.PairId -cne $PairId -or $row.RunId -cne $state.RunId){throw 'Journal chain/sequence/identity mismatch; retain evidence.'};$sequence=$row.Sequence;$hash=$_.Hash;if($sequence -eq $state.Sequence){if($hash -cne $state.JournalHash){throw 'Checkpoint does not match its durable journal prefix.'};$matched=$true}}
    if(-not $matched){throw 'Checkpoint is absent from durable journal.'}
    [pscustomobject]@{JournalSequence=$sequence;JournalHash=$hash;StateSequence=$state.Sequence;StateHash=$state.JournalHash;Consistent=($sequence -eq $state.Sequence -and $hash -ceq $state.JournalHash);RecoveryRequired=($sequence -gt $state.Sequence);TamperResistance='Local administrator can rewrite journal and state; chain detects accidental corruption only'}
}
function Repair-WsmOperation {
    [CmdletBinding(SupportsShouldProcess)]param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[hashtable]$SidMap=@{})
    $p=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $p.Manifest.Target.Fingerprint;$paths=Get-WsmOperationPaths $StateDirectory $p.Manifest.PairId
    Invoke-WsmLocked $paths.Root {$s=Get-WsmOperationState $paths $p -AllowRecovery;$journal=Test-WsmJournal $StateDirectory $s.PairId;if(-not $journal.Consistent){if(-not $PSCmdlet.ShouldProcess($s.PairId,'Replay verified durable journal to checkpoint')){return};Restore-WsmJournalCheckpoint $paths $s};if($s.Cutover -and $s.Cutover.NewTransactionsPossible){throw 'Post-activation recovery requires data reconciliation.'};$repaired=@()
        foreach($op in @($s.PendingOperations)){$item=@($p.Plan.Items | Where-Object ItemId -CEQ $op.ItemId)[0];if($op.Phase -eq 'AdapterCreating'){if($op.ManifestHash -ine $ExpectedHash -or $op.Adapter -cne $item.MigrationSpec.Adapter -or -not $op.AbsentBefore){throw 'Adapter intent binding mismatch.'};$observed=Get-WsmAdapterState $item.MigrationSpec;if(-not $observed.Exists){if($PSCmdlet.ShouldProcess($item.ItemId,'Abandon absent interrupted adapter build')){$s.PendingOperations=@($s.PendingOperations | Where-Object ItemId -CNE $op.ItemId);$s.Items=@($s.Items | Where-Object ItemId -CNE $op.ItemId);Add-WsmJournal $paths $s 'AdapterBuildAbandoned' $op.ItemId ([pscustomobject]@{Absent=$true})};continue};$check=Test-WsmAdapterConfiguration $item.MigrationSpec;if(-not $check.Passed){throw 'Interrupted adapter exists but differs from exact staged spec; reconcile using retained intent before retry.'};if($PSCmdlet.ShouldProcess($item.ItemId,'Adopt verified staged adapter from durable absent-before intent')){$record=[pscustomobject]@{ItemId=$op.ItemId;Status='Succeeded';CreatedByTool=$true;ActualHash=(Get-WsmHashText ($check.Actual | ConvertTo-Json -Depth 15 -Compress));Backup='';Target='';Error='';NativeCode=0};$s.Items=@($s.Items | Where-Object ItemId -CNE $op.ItemId)+@($record);$s.PendingOperations=@($s.PendingOperations | Where-Object ItemId -CNE $op.ItemId);Add-WsmJournal $paths $s 'AdapterRecovered' $op.ItemId $record;$repaired+=$op.ItemId};continue};if($op.ManifestHash -ine $ExpectedHash -or $item.MigrationSpec.Adapter -ne 'FileScope'){throw 'Pending operation plan mismatch.'};$target=ConvertTo-WsmCanonicalPath $item.MigrationSpec.TargetPath;$parent=[IO.Path]::GetDirectoryName($target);if($op.Target -ine $target -or [IO.Path]::GetDirectoryName($op.Staging) -ine $parent -or [IO.Path]::GetDirectoryName($op.Backup) -ine $parent -or [IO.Path]::GetFileName($op.Staging) -notlike '.wsm-stage-*' -or [IO.Path]::GetFileName($op.Backup) -notlike '.wsm-backup-*'){throw 'Recovery path escapes approved parent.'};foreach($path in @($target,$op.Staging,$op.Backup)){Assert-WsmNoReparse $path};$actual=Get-WsmFileScopeDigest $target $item.MigrationSpec.Metadata
            if($op.Phase -eq 'Prepared' -and $actual -ceq $op.ExpectedHash){if(-not $PSCmdlet.ShouldProcess($target,'Adopt verified completed scope switch')){continue}}
            elseif($op.Phase -eq 'Prepared' -and -not $actual -and (Test-Path -LiteralPath $op.Staging)){$check=Test-WsmFileScope $item $p $op.Staging $SidMap;if(-not $check.Passed -or $check.ActualHash -cne $op.ExpectedHash){throw 'Staging differs from prepared checkpoint.'};if(-not $PSCmdlet.ShouldProcess($target,'Finish interrupted approved scope switch')){continue};if([IO.Directory]::Exists($op.Staging)){[IO.Directory]::Move($op.Staging,$target)}else{[IO.File]::Move($op.Staging,$target)};$actual=$check.ActualHash}
            elseif($actual -ceq $op.PreviousHash){if(-not $PSCmdlet.ShouldProcess($target,'Abandon interrupted build; keep staging evidence and retry fresh')){continue};$s.PendingOperations=@($s.PendingOperations | Where-Object ItemId -CNE $op.ItemId);$s.Items=@($s.Items | Where-Object ItemId -CNE $op.ItemId);if($op.PSObject.Properties['PreviousRecord'] -and $op.PreviousRecord){$s.Items+=@($op.PreviousRecord)};Add-WsmJournal $paths $s 'BuildAbandoned' $op.ItemId ([pscustomobject]@{RetainedStaging=$op.Staging});continue}
            else{throw 'Target/staging do not match a safe checkpoint; manual reconciliation required.'}
            $record=[pscustomobject]@{ItemId=$op.ItemId;Status='Succeeded';CreatedByTool=$true;ActualHash=$actual;Backup=$op.Backup;Target=$target;Error='';NativeCode=0};$s.Items=@($s.Items | Where-Object ItemId -CNE $op.ItemId)+@($record);$s.PendingOperations=@($s.PendingOperations | Where-Object ItemId -CNE $op.ItemId);$repaired+=$op.ItemId;Add-WsmJournal $paths $s 'ScopeRecovered' $op.ItemId $record
        };[pscustomobject]@{Repaired=$repaired;Remaining=$s.PendingOperations.Count;State=$s}
    }
}
function Get-WsmRollbackPreview {
    param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory)
    $p=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;$paths=Get-WsmOperationPaths $StateDirectory $p.Manifest.PairId;$s=Get-WsmOperationState $paths $p;$rows=@(foreach($item in $p.Plan.Items){$r=@($s.Items | Where-Object ItemId -CEQ $item.ItemId);if($r.Count -and $r[0].CreatedByTool){$spec=$item.MigrationSpec;$hash='';if($spec.Adapter -eq 'FileScope'){$hash=Get-WsmFileScopeDigest $spec.TargetPath $spec.Metadata}else{$hash=Get-WsmHashText ((Get-WsmAdapterState $spec) | ConvertTo-Json -Depth 15 -Compress)};[pscustomobject]@{ItemId=$item.ItemId;Adapter=$spec.Adapter;CurrentHash=$hash;Backup=$r[0].Backup;Action='RemoveCreatedOrRestorePreviousOwned';Blocked=($spec.Adapter -eq 'WindowsFeature')}}})
    $preview=[pscustomobject]@{PairId=$s.PairId;ManifestHash=$ExpectedHash;DataReconcileRequired=($s.Cutover -and $s.Cutover.NewTransactionsPossible);Rows=$rows;SourceRestart='Never automatic';NetworkRollback='Reviewed domain/network procedure; never automatic source restart'}
    $preview | Add-Member NoteProperty PreviewHash (Get-WsmHashText ($preview | ConvertTo-Json -Depth 15 -Compress));$preview
}
function Invoke-WsmRollback {
    [CmdletBinding(SupportsShouldProcess)]param([string]$ManifestPath,[string]$ExpectedHash,[string]$StateDirectory,[string]$PreviewHash,[string]$Acknowledgement)
    $p=Test-WsmMigrationPackage $ManifestPath $ExpectedHash;Assert-WsmMigrationHost (Get-WsmMachineIdentity) $p.Manifest.Target.Fingerprint;$paths=Get-WsmOperationPaths $StateDirectory $p.Manifest.PairId
    Invoke-WsmLocked $paths.Root {$s=Get-WsmOperationState $paths $p;$preview=Get-WsmRollbackPreview $ManifestPath $ExpectedHash $StateDirectory;if($PreviewHash -ine $preview.PreviewHash -or $Acknowledgement -cne ('ROLLBACK '+$s.PairId)){throw 'Rollback preview changed or pair acknowledgement missing.'};if($preview.DataReconcileRequired -and -not (Test-WsmEvidence $s '' RollbackReconcile $ExpectedHash)){throw 'New target transactions may exist; stop writers and reconcile data before rollback.'};if(@($preview.Rows | Where-Object Blocked).Count){throw 'Dedicated feature rollback required.'};if(-not $PSCmdlet.ShouldProcess($s.PairId,'Rollback exactly reviewed created objects/owned roots; keep displaced content')){return $preview}
        $reverse=@(Get-WsmRestoreOrder @($p.Plan.Items | Where-Object Decision -EQ Include));[array]::Reverse($reverse)
        foreach($item in $reverse){$record=@($s.Items | Where-Object ItemId -CEQ $item.ItemId);if(-not $record.Count -or -not $record[0].CreatedByTool){continue};$spec=$item.MigrationSpec;Invoke-WsmAdapterActivation $spec $false;Add-WsmJournal $paths $s 'RollbackStarted' $item.ItemId ([pscustomobject]@{Adapter=$spec.Adapter})
            if($spec.Adapter -eq 'FileScope'){$target=ConvertTo-WsmCanonicalPath $spec.TargetPath;$parent=[IO.Path]::GetDirectoryName($target);$retained=Join-Path $parent ('.wsm-rollback-retained-'+[Guid]::NewGuid().ToString('N'));if([IO.Path]::GetDirectoryName($retained) -ine $parent){throw 'Rollback path escapes approved parent.'};Assert-WsmNoReparse $target;if([IO.Directory]::Exists($target)){[IO.Directory]::Move($target,$retained)}elseif([IO.File]::Exists($target)){[IO.File]::Move($target,$retained)};$backup=$record[0].Backup;if($backup -and (Test-Path -LiteralPath $backup)){if([IO.Path]::GetDirectoryName($backup) -ine $parent -or [IO.Path]::GetFileName($backup) -notlike '.wsm-backup-*'){throw 'Untrusted rollback backup path.'};Assert-WsmNoReparse $backup;if([IO.Directory]::Exists($backup)){[IO.Directory]::Move($backup,$target)}else{[IO.File]::Move($backup,$target)}}}
            else{Remove-WsmCreatedAdapter $spec};$record[0].Status='RolledBack';Add-WsmJournal $paths $s 'RollbackCompleted' $item.ItemId ([pscustomobject]@{Status='RolledBack'})
        };$s.Stage='RolledBack';Add-WsmJournal $paths $s 'RollbackFinished' '' ([pscustomobject]@{SourceRestarted=$false});$s
    }
}
