function Assert-WsmServiceSupplementName([string]$Name) {if([string]::IsNullOrWhiteSpace($Name) -or $Name.Length -gt 256 -or $Name -match '[\\/\x00-\x1f]' -or $Name -in @('.','..')){throw 'Invalid service name for SCM/registry operations.'}}
function Assert-WsmServiceSupplement($Supplement) {
    Assert-WsmFields $Supplement @('ServiceType','ErrorControl','LoadOrderGroup','DelayedAutoStart','FailureActions','FailureActionsOnNonCrashFailures','ServiceSidType','RequiredPrivileges','Environment','Triggers') @('ServiceType','ErrorControl','LoadOrderGroup','DelayedAutoStart','FailureActions','FailureActionsOnNonCrashFailures','ServiceSidType','RequiredPrivileges','Environment','Triggers')
    if($Supplement.ServiceType -cne 'Win32OwnProcess'){throw 'Only Win32OwnProcess can be recreated by the generic Service adapter; shared-process and driver services require a dedicated installer/workflow.'}
    if($Supplement.ErrorControl -cnotin @('Ignore','Normal','Severe','Critical')){throw 'Unsupported service ErrorControl.'}
    if($Supplement.LoadOrderGroup -isnot [string] -or $Supplement.LoadOrderGroup.Length -gt 256 -or $Supplement.LoadOrderGroup -match '[\x00-\x1f]'){throw 'Invalid service load-order group.'}
    if($Supplement.DelayedAutoStart -isnot [bool] -or $Supplement.FailureActionsOnNonCrashFailures -isnot [bool]){throw 'Service delayed-start and failure-action flags must be explicit booleans.'}
    if($Supplement.DelayedAutoStart -and $Supplement.LoadOrderGroup){throw 'Delayed auto-start cannot be combined with a load-order group; use dedicated service review.'}
    if($Supplement.ServiceSidType -cnotin @('None','Unrestricted','Restricted')){throw 'Unsupported service SID type.'}
    if(@($Supplement.RequiredPrivileges).Count -gt 64){throw 'Service required privilege list exceeds 64 entries.'};$privileges=@{};foreach($privilege in $Supplement.RequiredPrivileges){if([string]$privilege -notmatch '^Se[A-Za-z0-9]{1,64}Privilege$' -or $privileges.ContainsKey(([string]$privilege).ToUpperInvariant())){throw 'Invalid or duplicate service privilege.'};$privileges[([string]$privilege).ToUpperInvariant()]=$true}
    if(@($Supplement.Environment).Count -gt 256){throw 'Service environment exceeds 256 entries.'};$environment=@{};foreach($entry in $Supplement.Environment){$pair=[string]$entry -split '=',2;if($pair.Count -ne 2 -or $pair[0] -notmatch '^[A-Za-z_][A-Za-z0-9_]{0,127}$' -or $pair[1] -match '[\x00-\x1f]' -or $environment.ContainsKey($pair[0].ToUpperInvariant())){throw 'Invalid or duplicate service environment entry.'};$environment[$pair[0].ToUpperInvariant()]=$true}
    Assert-WsmFields $Supplement.FailureActions @('ResetPeriodSeconds','RebootMessage','Command','Actions') @('ResetPeriodSeconds','RebootMessage','Command','Actions')
    $reset=$Supplement.FailureActions.ResetPeriodSeconds;if($reset -cne 'Infinite' -and (($reset -isnot [int] -and $reset -isnot [long] -and $reset -isnot [uint32]) -or $reset -lt 0 -or $reset -gt 31536000)){throw 'Invalid service failure-action reset period; use Infinite for the SCM no-reset sentinel.'}
    foreach($field in @('RebootMessage','Command')){if($Supplement.FailureActions.$field -isnot [string] -or $Supplement.FailureActions.$field.Length -gt 2048 -or $Supplement.FailureActions.$field -match '[\x00-\x1f]'){throw ('Invalid service failure-action '+$field+'.')}}
    if(@($Supplement.FailureActions.Actions).Count -gt 16){throw 'Service failure-action list exceeds 16 entries.'};foreach($action in $Supplement.FailureActions.Actions){Assert-WsmFields $action @('Type','DelayMilliseconds') @('Type','DelayMilliseconds');if($action.Type -cnotin @('None','Restart','Reboot','RunCommand') -or ($action.DelayMilliseconds -isnot [int] -and $action.DelayMilliseconds -isnot [long] -and $action.DelayMilliseconds -isnot [uint32]) -or $action.DelayMilliseconds -lt 0 -or $action.DelayMilliseconds -gt 2592000000){throw 'Invalid service failure action.'};if($action.Type -eq 'RunCommand' -and -not $Supplement.FailureActions.Command){throw 'A RunCommand failure action requires an explicit reviewed command.'}};if(@($Supplement.FailureActions.Actions).Count -eq 0 -and [string]$reset -cne '0'){throw 'SCM clears the failure-action reset period when its action array is empty; empty actions require ResetPeriodSeconds=0.'}
    if(@($Supplement.Triggers).Count -gt 128){throw 'Service trigger list exceeds 128 entries.'};$triggerIds=@(1,2,3,4,5,6,20);foreach($trigger in $Supplement.Triggers){Assert-WsmFields $trigger @('Type','Action','Subtype','DataItems') @('Type','Action','Subtype','DataItems');if(($trigger.Type -isnot [int] -and $trigger.Type -isnot [long] -and $trigger.Type -isnot [uint32]) -or [uint32]$trigger.Type -notin $triggerIds){throw 'Unsupported service trigger type.'};if($trigger.Action -cnotin @('Start','Stop')){throw 'Unsupported service trigger action.'};if($trigger.Subtype -isnot [string] -or $trigger.Subtype.Length -gt 64){throw 'Invalid service trigger subtype.'};$parsedGuid=[Guid]::Empty;if($trigger.Subtype -and -not [Guid]::TryParse($trigger.Subtype,[ref]$parsedGuid)){throw 'Service trigger subtype must be a GUID or empty.'};if(@($trigger.DataItems).Count -gt 128){throw 'Service trigger data list exceeds 128 entries.'};foreach($data in $trigger.DataItems){Assert-WsmFields $data @('Type','DataBase64') @('Type','DataBase64');if(($data.Type -isnot [int] -and $data.Type -isnot [long] -and $data.Type -isnot [uint32]) -or [uint32]$data.Type -notin @(1,2,3,4,5)){throw 'Unsupported service trigger data type.'};if($data.DataBase64 -isnot [string] -or $data.DataBase64.Length -gt 1368){throw 'Invalid or oversized service trigger data.'};try{$bytes=[Convert]::FromBase64String($data.DataBase64)}catch{throw 'Service trigger data must be valid base64.'};if([Convert]::ToBase64String($bytes) -cne $data.DataBase64){throw 'Service trigger data must use canonical base64.'};if($bytes.Length -gt 1024){throw 'Service trigger data exceeds 1024 bytes.'};switch([uint32]$data.Type){2{if(($bytes.Length -lt 2) -or ($bytes.Length % 2) -ne 0 -or $bytes[$bytes.Length-1] -ne 0 -or $bytes[$bytes.Length-2] -ne 0){throw 'Service trigger string data must be null-terminated UTF-16.'}};3{if($bytes.Length -ne 1){throw 'Service trigger level data must contain one byte.'}};4{if($bytes.Length -ne 8){throw 'Service trigger keyword data must contain eight bytes.'}};5{if($bytes.Length -ne 8){throw 'Service trigger keyword data must contain eight bytes.'}}}}}
    $Supplement
}
function Initialize-WsmServiceSupplementNative {
    if('WsmServiceSupplementNative' -as [type]){return}
    $source=@'
using System;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Text;
public static class WsmServiceSupplementNative {
  const uint SC_MANAGER_CONNECT=1, SERVICE_QUERY_CONFIG=1, SERVICE_CHANGE_CONFIG=2, SERVICE_NO_CHANGE=0xffffffff;
  const uint SERVICE_START=0x10, TOKEN_QUERY=0x8, TOKEN_ADJUST_PRIVILEGES=0x20, SE_PRIVILEGE_ENABLED=0x2, ERROR_NO_TOKEN=1008, ERROR_NOT_ALL_ASSIGNED=1300;
  [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)] struct QUERY_SERVICE_CONFIG { public uint ServiceType; public uint StartType; public uint ErrorControl; public IntPtr BinaryPathName; public IntPtr LoadOrderGroup; public uint TagId; public IntPtr Dependencies; public IntPtr StartName; public IntPtr DisplayName; }
  [StructLayout(LayoutKind.Sequential)] struct DELAYED { public int Enabled; }
  [StructLayout(LayoutKind.Sequential)] struct FAILURE_FLAG { public int Enabled; }
  [StructLayout(LayoutKind.Sequential)] struct SID_INFO { public uint Type; }
  [StructLayout(LayoutKind.Sequential)] struct FAILURE_ACTION { public int Type; public uint Delay; }
  [StructLayout(LayoutKind.Sequential)] struct FAILURE_ACTIONS { public uint Reset; public IntPtr RebootMessage; public IntPtr Command; public uint Count; public IntPtr Actions; }
  [StructLayout(LayoutKind.Sequential)] struct TRIGGER_INFO { public uint Count; public IntPtr Triggers; public IntPtr Reserved; }
  [StructLayout(LayoutKind.Sequential)] struct TRIGGER { public uint Type; public uint Action; public IntPtr Subtype; public uint DataCount; public IntPtr DataItems; }
  [StructLayout(LayoutKind.Sequential)] struct TRIGGER_DATA { public uint Type; public uint Size; public IntPtr Data; }
  [StructLayout(LayoutKind.Sequential)] struct LUID { public uint LowPart; public int HighPart; }
  [StructLayout(LayoutKind.Sequential)] struct LUID_AND_ATTRIBUTES { public LUID Luid; public uint Attributes; }
  [StructLayout(LayoutKind.Sequential)] struct TOKEN_PRIVILEGES { public uint PrivilegeCount; public LUID_AND_ATTRIBUTES Privileges; }
  [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern IntPtr OpenSCManager(string machine,string database,uint access);
  [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern IntPtr OpenService(IntPtr scm,string name,uint access);
  [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool QueryServiceConfig(IntPtr service,IntPtr buffer,uint size,out uint needed);
  [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool QueryServiceConfig2(IntPtr service,uint level,IntPtr buffer,uint size,out uint needed);
  [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool ChangeServiceConfig(IntPtr service,uint type,uint start,uint error,string binary,string group,IntPtr tag,string deps,string account,string password,string display);
  [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool ChangeServiceConfig2(IntPtr service,uint level,IntPtr info);
  [DllImport("advapi32.dll", SetLastError=true)] static extern bool CloseServiceHandle(IntPtr handle);
  [DllImport("kernel32.dll")] static extern IntPtr GetCurrentThread();
  [DllImport("advapi32.dll", SetLastError=true)] static extern bool OpenThreadToken(IntPtr thread,uint access,bool openAsSelf,out IntPtr token);
  [DllImport("advapi32.dll", SetLastError=true)] static extern bool OpenProcessToken(IntPtr process,uint access,out IntPtr token);
  [DllImport("kernel32.dll")] static extern IntPtr GetCurrentProcess();
  [DllImport("kernel32.dll", SetLastError=true)] static extern bool CloseHandle(IntPtr handle);
  [DllImport("advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] static extern bool LookupPrivilegeValue(string systemName,string name,out LUID luid);
  [DllImport("advapi32.dll", SetLastError=true)] static extern bool AdjustTokenPrivileges(IntPtr token,bool disableAll,ref TOKEN_PRIVILEGES newState,uint bufferLength,out TOKEN_PRIVILEGES previousState,out uint returnLength);
  static Exception Error(string operation) { return new Win32Exception(Marshal.GetLastWin32Error(),operation); }
  static IntPtr Open(string name,uint access) { IntPtr scm=OpenSCManager(null,null,SC_MANAGER_CONNECT);if(scm==IntPtr.Zero)throw Error("OpenSCManager");try{IntPtr svc=OpenService(scm,name,access);if(svc==IntPtr.Zero)throw Error("OpenService: "+name);return svc;}finally{CloseServiceHandle(scm);} }
  static void RequireRoot(IntPtr p,uint length,int size,string label) { if(p==IntPtr.Zero||length<(uint)size)throw new InvalidOperationException(label+" exceeds its query buffer."); }
  static IntPtr Query(IntPtr svc,uint level,out uint length) { uint needed;bool first=QueryServiceConfig2(svc,level,IntPtr.Zero,0,out needed);int err=Marshal.GetLastWin32Error();if(first||needed==0)throw new Win32Exception(err,"QueryServiceConfig2 size query level "+level);if(needed>1048576)throw new InvalidOperationException("QueryServiceConfig2 buffer exceeds 1 MiB.");IntPtr p=Marshal.AllocHGlobal((int)needed);try{if(!QueryServiceConfig2(svc,level,p,needed,out needed))throw Error("QueryServiceConfig2 level "+level);if(needed>1048576)throw new InvalidOperationException("QueryServiceConfig2 result exceeds 1 MiB.");length=needed;return p;}catch{Marshal.FreeHGlobal(p);throw;} }
  static int Offset(IntPtr p,IntPtr start,uint length) { long delta=p.ToInt64()-start.ToInt64();if(delta<0||delta>length)throw new InvalidOperationException("SCM returned an out-of-buffer pointer.");return (int)delta; }
  static string ReadString(IntPtr p,IntPtr start,uint length) { if(p==IntPtr.Zero)return "";int off=Offset(p,start,length);int max=(int)length-off;if(max<2)throw new InvalidOperationException("SCM string pointer has no buffer.");var b=new StringBuilder();for(int n=0;n+1<max;n+=2){char c=(char)Marshal.ReadInt16(p,n);if(c=='\0')return b.ToString();b.Append(c);}throw new InvalidOperationException("SCM returned an unterminated string."); }
  static string[] ReadMultiSz(IntPtr p,int maxBytes) { if(p==IntPtr.Zero)return new string[0];if(maxBytes<4||(maxBytes&1)!=0)throw new InvalidOperationException("Invalid MULTI_SZ bounds.");var values=new System.Collections.Generic.List<string>();var item=new StringBuilder();bool previousNull=false;for(int offset=0;offset<maxBytes;offset+=2){char c=(char)Marshal.ReadInt16(p,offset);if(c=='\0'){if(previousNull)return values.ToArray();if(item.Length>0){values.Add(item.ToString());item.Length=0;}previousNull=true;}else{item.Append(c);previousNull=false;}}throw new InvalidOperationException("SCM returned an unterminated MULTI_SZ."); }
  public static string[] ParseMultiSzFixture(byte[] bytes) { if(bytes==null)throw new ArgumentNullException("bytes");IntPtr p=Marshal.AllocHGlobal(bytes.Length);try{Marshal.Copy(bytes,0,p,bytes.Length);return ReadMultiSz(p,bytes.Length);}finally{Marshal.FreeHGlobal(p);} }
  static IntPtr AllocMultiSz(string[] values) { string text=(values==null||values.Length==0)?"\0\0":String.Join("\0",values)+"\0\0";return Marshal.StringToHGlobalUni(text); }
  static object[][] ReadTriggers(IntPtr p,uint length) { RequireRoot(p,length,Marshal.SizeOf(typeof(TRIGGER_INFO)),"SCM trigger-info root");var info=(TRIGGER_INFO)Marshal.PtrToStructure(p,typeof(TRIGGER_INFO));if(info.Count>128)throw new InvalidOperationException("SCM returned more than 128 service triggers.");int ts=Marshal.SizeOf(typeof(TRIGGER));int ds=Marshal.SizeOf(typeof(TRIGGER_DATA));int trigOff=info.Count==0?0:Offset(info.Triggers,p,length);if(info.Count>0&&(long)trigOff+(long)ts*info.Count>length)throw new InvalidOperationException("SCM trigger array exceeds its query buffer.");var result=new object[info.Count][];for(int i=0;i<info.Count;i++){var t=(TRIGGER)Marshal.PtrToStructure(new IntPtr(info.Triggers.ToInt64()+(long)i*ts),typeof(TRIGGER));if(t.DataCount>128)throw new InvalidOperationException("SCM returned more than 128 trigger data items.");string subtype="";if(t.Subtype!=IntPtr.Zero){int subtypeOff=Offset(t.Subtype,p,length);if((long)subtypeOff+16>length)throw new InvalidOperationException("SCM trigger subtype GUID exceeds its query buffer.");subtype=((Guid)Marshal.PtrToStructure(t.Subtype,typeof(Guid))).ToString("D");}var data=new object[t.DataCount][];if(t.DataCount>0){int dataOff=Offset(t.DataItems,p,length);if((long)dataOff+(long)ds*t.DataCount>length)throw new InvalidOperationException("SCM trigger data array exceeds its query buffer.");for(int j=0;j<t.DataCount;j++){var d=(TRIGGER_DATA)Marshal.PtrToStructure(new IntPtr(t.DataItems.ToInt64()+(long)j*ds),typeof(TRIGGER_DATA));if(d.Size>1024)throw new InvalidOperationException("SCM trigger data exceeds 1024 bytes.");byte[] bytes=new byte[d.Size];if(d.Size>0){int bytesOff=Offset(d.Data,p,length);if((long)bytesOff+d.Size>length)throw new InvalidOperationException("SCM trigger bytes exceed their query buffer.");Marshal.Copy(d.Data,bytes,0,(int)d.Size);}data[j]=new object[]{d.Type,Convert.ToBase64String(bytes)};}}result[i]=new object[]{t.Type,t.Action,subtype,data};}return result; }
  public static object[][] ParseTriggerFixture(byte[] data,bool truncate) { if(data==null||data.Length>1024)throw new ArgumentException("Fixture data must be at most 1024 bytes.");int infoSize=Marshal.SizeOf(typeof(TRIGGER_INFO)),triggerSize=Marshal.SizeOf(typeof(TRIGGER)),dataSize=Marshal.SizeOf(typeof(TRIGGER_DATA));int to=infoSize,doff=to+triggerSize,go=doff+dataSize,bo=go+16,length=bo+data.Length;IntPtr p=Marshal.AllocHGlobal(length);try{IntPtr trig=new IntPtr(p.ToInt64()+to),di=new IntPtr(p.ToInt64()+doff),guid=new IntPtr(p.ToInt64()+go),bytes=new IntPtr(p.ToInt64()+bo);Marshal.StructureToPtr(new TRIGGER_INFO{Count=1,Triggers=trig,Reserved=IntPtr.Zero},p,false);Marshal.StructureToPtr(new TRIGGER{Type=4,Action=1,Subtype=guid,DataCount=1,DataItems=di},trig,false);Marshal.StructureToPtr(new TRIGGER_DATA{Type=2,Size=(uint)data.Length,Data=bytes},di,false);Marshal.StructureToPtr(new Guid("b7569e07-8421-4ee0-ad10-86915afdad09"),guid,false);if(data.Length>0)Marshal.Copy(data,0,bytes,data.Length);return ReadTriggers(p,(uint)(truncate?length-1:length));}finally{Marshal.FreeHGlobal(p);} }
  public static object[][] ParseEmptyTriggerDataFixture() { int isz=Marshal.SizeOf(typeof(TRIGGER_INFO)),ts=Marshal.SizeOf(typeof(TRIGGER));IntPtr p=Marshal.AllocHGlobal(isz+ts);try{IntPtr t=new IntPtr(p.ToInt64()+isz);Marshal.StructureToPtr(new TRIGGER_INFO{Count=1,Triggers=t,Reserved=IntPtr.Zero},p,false);Marshal.StructureToPtr(new TRIGGER{Type=4,Action=1,Subtype=IntPtr.Zero,DataCount=0,DataItems=IntPtr.Zero},t,false);return ReadTriggers(p,(uint)(isz+ts));}finally{Marshal.FreeHGlobal(p);} }
  public static void ParseTruncatedTriggerGuidFixture() { int isz=Marshal.SizeOf(typeof(TRIGGER_INFO)),ts=Marshal.SizeOf(typeof(TRIGGER)),go=isz+ts,length=go+16;IntPtr p=Marshal.AllocHGlobal(length);try{IntPtr t=new IntPtr(p.ToInt64()+isz),g=new IntPtr(p.ToInt64()+go);Marshal.StructureToPtr(new TRIGGER_INFO{Count=1,Triggers=t,Reserved=IntPtr.Zero},p,false);Marshal.StructureToPtr(new TRIGGER{Type=4,Action=1,Subtype=g,DataCount=0,DataItems=IntPtr.Zero},t,false);Marshal.StructureToPtr(new Guid("b7569e07-8421-4ee0-ad10-86915afdad09"),g,false);ReadTriggers(p,(uint)(length-1));}finally{Marshal.FreeHGlobal(p);} }
  public static void ParseTruncatedTriggerRootFixture() { int isz=Marshal.SizeOf(typeof(TRIGGER_INFO));IntPtr p=Marshal.AllocHGlobal(isz);try{Marshal.StructureToPtr(new TRIGGER_INFO{Count=0,Triggers=IntPtr.Zero,Reserved=IntPtr.Zero},p,false);ReadTriggers(p,(uint)(isz-1));}finally{Marshal.FreeHGlobal(p);} }
  public static void ParseTruncatedFailureActionsRootFixture() { int size=Marshal.SizeOf(typeof(FAILURE_ACTIONS));IntPtr p=Marshal.AllocHGlobal(size);try{RequireRoot(p,(uint)(size-1),size,"SCM failure-actions root");}finally{Marshal.FreeHGlobal(p);} }
  static Action AcquireShutdownPrivilege() { IntPtr token=IntPtr.Zero;bool opened=OpenThreadToken(GetCurrentThread(),TOKEN_QUERY|TOKEN_ADJUST_PRIVILEGES,true,out token);int openError=opened?0:Marshal.GetLastWin32Error();if(!opened&&openError==ERROR_NO_TOKEN){opened=OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY|TOKEN_ADJUST_PRIVILEGES,out token);if(!opened)throw Error("Open process token for SeShutdownPrivilege");}else if(!opened)throw new Win32Exception(openError,"Open thread token for SeShutdownPrivilege");try{LUID luid;if(!LookupPrivilegeValue(null,"SeShutdownPrivilege",out luid))throw Error("LookupPrivilegeValue SeShutdownPrivilege");TOKEN_PRIVILEGES requested=new TOKEN_PRIVILEGES{PrivilegeCount=1,Privileges=new LUID_AND_ATTRIBUTES{Luid=luid,Attributes=SE_PRIVILEGE_ENABLED}},previous;uint returned;bool ok=AdjustTokenPrivileges(token,false,ref requested,(uint)Marshal.SizeOf(typeof(TOKEN_PRIVILEGES)),out previous,out returned);int err=Marshal.GetLastWin32Error();if(!ok)throw new Win32Exception(err,"Enable SeShutdownPrivilege");if(err==(int)ERROR_NOT_ALL_ASSIGNED)throw new Win32Exception((int)ERROR_NOT_ALL_ASSIGNED,"Token is not eligible for SeShutdownPrivilege (ERROR_NOT_ALL_ASSIGNED)");return delegate{try{bool restored=AdjustTokenPrivileges(token,false,ref previous,(uint)Marshal.SizeOf(typeof(TOKEN_PRIVILEGES)),out requested,out returned);int restoreError=Marshal.GetLastWin32Error();if(!restored||restoreError==(int)ERROR_NOT_ALL_ASSIGNED)throw new Win32Exception(restoreError,"Restore previous SeShutdownPrivilege state");}finally{CloseHandle(token);}};}catch{CloseHandle(token);throw;} }
  public static void ExecuteWithShutdownPrivilege(Action work,Func<Action> acquire) { if(work==null||acquire==null)throw new ArgumentNullException();Action restore=acquire();try{work();}finally{if(restore!=null)restore();} }
  static bool HasRestart(int[] types) { if(types==null)return false;for(int i=0;i<types.Length;i++)if(types[i]==1)return true;return false; }
  static bool HasReboot(int[] types) { if(types==null)return false;for(int i=0;i<types.Length;i++)if(types[i]==2)return true;return false; }
  public static uint RequiredServiceAccessFixture(int[] types) { return SERVICE_CHANGE_CONFIG|SERVICE_QUERY_CONFIG|(HasRestart(types)?SERVICE_START:0); }
  static object Query2(IntPtr svc,uint level) { uint length;IntPtr p=Query(svc,level,out length);try{if(level==2){RequireRoot(p,length,Marshal.SizeOf(typeof(FAILURE_ACTIONS)),"SCM failure-actions root");var x=(FAILURE_ACTIONS)Marshal.PtrToStructure(p,typeof(FAILURE_ACTIONS));if(x.Count>16)throw new InvalidOperationException("SCM returned more than 16 failure actions.");var list=new System.Collections.Generic.List<object>();int size=Marshal.SizeOf(typeof(FAILURE_ACTION));if(x.Count>0){Offset(x.Actions,p,length);if((long)(x.Actions.ToInt64()-p.ToInt64())+(long)size*x.Count>length)throw new InvalidOperationException("SCM failure-action array exceeds its query buffer.");}for(int i=0;i<x.Count;i++){var a=(FAILURE_ACTION)Marshal.PtrToStructure(new IntPtr(x.Actions.ToInt64()+(long)i*size),typeof(FAILURE_ACTION));list.Add(new object[]{a.Type,a.Delay});}return new object[]{x.Reset,ReadString(x.RebootMessage,p,length),ReadString(x.Command,p,length),list.ToArray()};}if(level==3){RequireRoot(p,length,Marshal.SizeOf(typeof(DELAYED)),"SCM delayed-start root");return ((DELAYED)Marshal.PtrToStructure(p,typeof(DELAYED))).Enabled!=0;}if(level==4){RequireRoot(p,length,Marshal.SizeOf(typeof(FAILURE_FLAG)),"SCM failure-flag root");return ((FAILURE_FLAG)Marshal.PtrToStructure(p,typeof(FAILURE_FLAG))).Enabled!=0;}if(level==5){RequireRoot(p,length,Marshal.SizeOf(typeof(SID_INFO)),"SCM SID-info root");return ((SID_INFO)Marshal.PtrToStructure(p,typeof(SID_INFO))).Type;}if(level==6){RequireRoot(p,length,IntPtr.Size,"SCM required-privileges root");IntPtr q=Marshal.ReadIntPtr(p);if(q==IntPtr.Zero)return new string[0];int off=Offset(q,p,length);return ReadMultiSz(q,(int)length-off);}if(level==8)return ReadTriggers(p,length);throw new ArgumentOutOfRangeException("level");}finally{Marshal.FreeHGlobal(p);} }
  public static object[] Read(string name) { IntPtr svc=Open(name,SERVICE_QUERY_CONFIG);try{uint needed;bool first=QueryServiceConfig(svc,IntPtr.Zero,0,out needed);int err=Marshal.GetLastWin32Error();if(first||needed==0)throw new Win32Exception(err,"QueryServiceConfig size query");if(needed>1048576)throw new InvalidOperationException("QueryServiceConfig buffer exceeds 1 MiB.");IntPtr p=Marshal.AllocHGlobal((int)needed);try{if(!QueryServiceConfig(svc,p,needed,out needed))throw Error("QueryServiceConfig");var q=(QUERY_SERVICE_CONFIG)Marshal.PtrToStructure(p,typeof(QUERY_SERVICE_CONFIG));return new object[]{q.ServiceType,q.ErrorControl,ReadString(q.LoadOrderGroup,p,needed),Query2(svc,3),Query2(svc,2),Query2(svc,4),Query2(svc,5),Query2(svc,6),Query2(svc,8)};}finally{Marshal.FreeHGlobal(p);}}finally{CloseServiceHandle(svc);} }
  static void Apply2(IntPtr svc,uint level,object data) { IntPtr p=IntPtr.Zero;var owned=new System.Collections.Generic.List<IntPtr>();try{if(level==3){p=Marshal.AllocHGlobal(Marshal.SizeOf(typeof(DELAYED)));Marshal.StructureToPtr(new DELAYED{Enabled=(bool)data?1:0},p,false);}else if(level==4){p=Marshal.AllocHGlobal(Marshal.SizeOf(typeof(FAILURE_FLAG)));Marshal.StructureToPtr(new FAILURE_FLAG{Enabled=(bool)data?1:0},p,false);}else if(level==5){p=Marshal.AllocHGlobal(Marshal.SizeOf(typeof(SID_INFO)));Marshal.StructureToPtr(new SID_INFO{Type=(uint)data},p,false);}else if(level==6){IntPtr multi=AllocMultiSz((string[])data);owned.Add(multi);p=Marshal.AllocHGlobal(IntPtr.Size);Marshal.WriteIntPtr(p,multi);}else if(level==2){object[] v=(object[])data;object[][] actions=(object[][])v[3];int size=Marshal.SizeOf(typeof(FAILURE_ACTION));IntPtr arr=Marshal.AllocHGlobal(size*Math.Max(1,actions.Length));owned.Add(arr);for(int i=0;i<actions.Length;i++)Marshal.StructureToPtr(new FAILURE_ACTION{Type=Convert.ToInt32(actions[i][0]),Delay=Convert.ToUInt32(actions[i][1])},new IntPtr(arr.ToInt64()+(long)i*size),false);IntPtr msg=Marshal.StringToHGlobalUni((string)v[1]);owned.Add(msg);IntPtr cmd=Marshal.StringToHGlobalUni((string)v[2]);owned.Add(cmd);var f=new FAILURE_ACTIONS{Reset=Convert.ToUInt32(v[0]),RebootMessage=msg,Command=cmd,Count=(uint)actions.Length,Actions=arr};p=Marshal.AllocHGlobal(Marshal.SizeOf(typeof(FAILURE_ACTIONS)));Marshal.StructureToPtr(f,p,false);}else throw new ArgumentOutOfRangeException("level");bool ok=ChangeServiceConfig2(svc,level,p);int err=Marshal.GetLastWin32Error();if(!ok)throw new Win32Exception(err,"ChangeServiceConfig2 level "+level);}finally{if(p!=IntPtr.Zero)Marshal.FreeHGlobal(p);foreach(IntPtr q in owned)if(q!=IntPtr.Zero)Marshal.FreeHGlobal(q);} }
  static void ApplyTriggers(IntPtr svc,object[][] triggers) { object[][] current=(object[][])Query2(svc,8);if(triggers.Length==0&&current.Length==0)return;var owned=new System.Collections.Generic.List<IntPtr>();IntPtr infoPtr=IntPtr.Zero;try{int ts=Marshal.SizeOf(typeof(TRIGGER));int ds=Marshal.SizeOf(typeof(TRIGGER_DATA));IntPtr triggerArray=triggers.Length==0?IntPtr.Zero:Marshal.AllocHGlobal(ts*triggers.Length);if(triggerArray!=IntPtr.Zero)owned.Add(triggerArray);for(int i=0;i<triggers.Length;i++){object[] item=triggers[i];uint type=Convert.ToUInt32(item[0]),action=Convert.ToUInt32(item[1]);string subtype=(string)item[2];object[][] data=(object[][])item[3];IntPtr subtypePtr=IntPtr.Zero;if(!String.IsNullOrEmpty(subtype)){subtypePtr=Marshal.AllocHGlobal(16);owned.Add(subtypePtr);Marshal.StructureToPtr(new Guid(subtype),subtypePtr,false);}IntPtr dataArray=data.Length==0?IntPtr.Zero:Marshal.AllocHGlobal(ds*data.Length);if(dataArray!=IntPtr.Zero)owned.Add(dataArray);for(int j=0;j<data.Length;j++){uint dataType=Convert.ToUInt32(data[j][0]);byte[] bytes=Convert.FromBase64String((string)data[j][1]);if(bytes.Length>1024)throw new InvalidOperationException("Trigger data exceeds 1024 bytes.");IntPtr bytesPtr=bytes.Length==0?IntPtr.Zero:Marshal.AllocHGlobal(bytes.Length);if(bytesPtr!=IntPtr.Zero){owned.Add(bytesPtr);Marshal.Copy(bytes,0,bytesPtr,bytes.Length);}Marshal.StructureToPtr(new TRIGGER_DATA{Type=dataType,Size=(uint)bytes.Length,Data=bytesPtr},new IntPtr(dataArray.ToInt64()+(long)j*ds),false);}Marshal.StructureToPtr(new TRIGGER{Type=type,Action=action,Subtype=subtypePtr,DataCount=(uint)data.Length,DataItems=dataArray},new IntPtr(triggerArray.ToInt64()+(long)i*ts),false);}infoPtr=Marshal.AllocHGlobal(Marshal.SizeOf(typeof(TRIGGER_INFO)));Marshal.StructureToPtr(new TRIGGER_INFO{Count=(uint)triggers.Length,Triggers=triggerArray,Reserved=IntPtr.Zero},infoPtr,false);bool ok=ChangeServiceConfig2(svc,8,infoPtr);int err=Marshal.GetLastWin32Error();if(!ok)throw new Win32Exception(err,"ChangeServiceConfig2 trigger info");}finally{if(infoPtr!=IntPtr.Zero)Marshal.FreeHGlobal(infoPtr);for(int i=owned.Count-1;i>=0;i--)Marshal.FreeHGlobal(owned[i]);} }
  public static void Apply(string name,uint error,string group,bool delayed,uint sid,string[] privileges,uint reset,string message,string command,int[] types,uint[] delays,bool failureFlag,object[][] triggers) { uint access=SERVICE_CHANGE_CONFIG|SERVICE_QUERY_CONFIG|(HasRestart(types)?SERVICE_START:0);IntPtr svc=Open(name,access);try{Action work=delegate{uint needed;bool first=QueryServiceConfig(svc,IntPtr.Zero,0,out needed);int err=Marshal.GetLastWin32Error();if(first||needed==0)throw new Win32Exception(err,"QueryServiceConfig size query");if(needed>1048576)throw new InvalidOperationException("QueryServiceConfig buffer exceeds 1 MiB.");IntPtr qptr=Marshal.AllocHGlobal((int)needed);try{if(!QueryServiceConfig(svc,qptr,needed,out needed))throw Error("QueryServiceConfig");var q=(QUERY_SERVICE_CONFIG)Marshal.PtrToStructure(qptr,typeof(QUERY_SERVICE_CONFIG));if(q.ServiceType!=0x10)throw new InvalidOperationException("Only an existing Win32 own-process service can receive generic supplement changes.");}finally{Marshal.FreeHGlobal(qptr);}bool changed=ChangeServiceConfig(svc,SERVICE_NO_CHANGE,SERVICE_NO_CHANGE,error,null,group,IntPtr.Zero,null,null,null,null);err=Marshal.GetLastWin32Error();if(!changed)throw new Win32Exception(err,"ChangeServiceConfig error-control/load-order-group");Apply2(svc,3,delayed);Apply2(svc,5,sid);Apply2(svc,6,privileges);object[][] actions=new object[types.Length][];for(int i=0;i<types.Length;i++)actions[i]=new object[]{types[i],delays[i]};Apply2(svc,2,new object[]{reset,message,command,actions});Apply2(svc,4,failureFlag);ApplyTriggers(svc,triggers);};if(HasReboot(types))ExecuteWithShutdownPrivilege(work,AcquireShutdownPrivilege);else work();}finally{CloseServiceHandle(svc);} }
}
'@
    Add-Type -TypeDefinition $source -Language CSharp -ErrorAction Stop
}
function ConvertTo-WsmServiceSupplementNativeInput($Supplement) {
    $errorControlCode=@{Ignore=0;Normal=1;Severe=2;Critical=3}[$Supplement.ErrorControl];$sid=@{None=0;Unrestricted=1;Restricted=3}[$Supplement.ServiceSidType];$action=@{None=0;Restart=1;Reboot=2;RunCommand=3};$types=[int[]]@($Supplement.FailureActions.Actions | ForEach-Object {$action[$_.Type]});$delays=[uint32[]]@($Supplement.FailureActions.Actions | ForEach-Object {[uint32]$_.DelayMilliseconds});$reset=[uint32]::MaxValue;if($Supplement.FailureActions.ResetPeriodSeconds -cne 'Infinite'){$reset=[uint32]$Supplement.FailureActions.ResetPeriodSeconds}
    $triggerList=New-Object 'System.Collections.Generic.List[object[]]';foreach($trigger in $Supplement.Triggers){$dataList=New-Object 'System.Collections.Generic.List[object[]]';foreach($data in $trigger.DataItems){$dataList.Add([object[]]@([uint32]$data.Type,[string]$data.DataBase64))};$triggerAction=1;if($trigger.Action -ceq 'Stop'){$triggerAction=2};$triggerList.Add([object[]]@([uint32]$trigger.Type,[uint32]$triggerAction,[string]$trigger.Subtype,$dataList.ToArray()))}
    [pscustomobject]@{ErrorControl=[uint32]$errorControlCode;LoadOrderGroup=[string]$Supplement.LoadOrderGroup;DelayedAutoStart=[bool]$Supplement.DelayedAutoStart;ServiceSidType=[uint32]$sid;RequiredPrivileges=[string[]]@($Supplement.RequiredPrivileges);Environment=[string[]]@($Supplement.Environment);ResetPeriodSeconds=$reset;RebootMessage=[string]$Supplement.FailureActions.RebootMessage;Command=[string]$Supplement.FailureActions.Command;ActionTypes=$types;ActionDelays=$delays;FailureActionsOnNonCrashFailures=[bool]$Supplement.FailureActionsOnNonCrashFailures;Triggers=$triggerList.ToArray()}
}
function Get-WsmServiceSupplementNativeState([string]$Name) {Initialize-WsmServiceSupplementNative;return ,([WsmServiceSupplementNative]::Read($Name))}
function Invoke-WsmServiceSupplementNative([string]$Name,$NativeConfig) {Initialize-WsmServiceSupplementNative;[WsmServiceSupplementNative]::Apply($Name,$NativeConfig.ErrorControl,$NativeConfig.LoadOrderGroup,$NativeConfig.DelayedAutoStart,$NativeConfig.ServiceSidType,$NativeConfig.RequiredPrivileges,$NativeConfig.ResetPeriodSeconds,$NativeConfig.RebootMessage,$NativeConfig.Command,$NativeConfig.ActionTypes,$NativeConfig.ActionDelays,$NativeConfig.FailureActionsOnNonCrashFailures,$NativeConfig.Triggers)}
function Get-WsmServiceEnvironment([string]$Name) {Assert-WsmServiceSupplementName $Name;$registry=[Microsoft.Win32.Registry]::LocalMachine.OpenSubKey(('SYSTEM\CurrentControlSet\Services\'+$Name),$false);if(-not $registry){throw 'Service registry key is unavailable.'};try{if($registry.GetValueNames() -contains 'Environment'){@($registry.GetValue('Environment',$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames))}else{@()}}finally{$registry.Dispose()}}
function Set-WsmServiceEnvironment([string]$Name,[string[]]$Values) {Assert-WsmServiceSupplementName $Name;$registry=[Microsoft.Win32.Registry]::LocalMachine.OpenSubKey(('SYSTEM\CurrentControlSet\Services\'+$Name),$true);if(-not $registry){throw 'Service registry key is unavailable.'};try{if($Values.Count){$registry.SetValue('Environment',[string[]]$Values,[Microsoft.Win32.RegistryValueKind]::MultiString)}elseif($registry.GetValueNames() -contains 'Environment'){$registry.DeleteValue('Environment',$false)}}finally{$registry.Dispose()}}
function ConvertFrom-WsmServiceSupplementState($Actual,[string[]]$Environment=@()) {
    if($Actual -is [array]){if($Actual.Count -lt 9){throw 'Native service supplement state is incomplete.'};$raw=$Actual;$Actual=[pscustomobject]@{ServiceType=$raw[0];ErrorControl=$raw[1];LoadOrderGroup=$raw[2];DelayedAutoStart=$raw[3];FailureActions=$raw[4];FailureActionsOnNonCrashFailures=$raw[5];ServiceSidType=$raw[6];RequiredPrivileges=$raw[7];Environment=$Environment;Triggers=$raw[8]}}
    $serviceTypes=@{'16'='Win32OwnProcess'};$errors=@{'0'='Ignore';'1'='Normal';'2'='Severe';'3'='Critical'};$sidTypes=@{'0'='None';'1'='Unrestricted';'3'='Restricted'};$actionTypes=@{'0'='None';'1'='Restart';'2'='Reboot';'3'='RunCommand'}
    $type=$serviceTypes[[string]([uint32]$Actual.ServiceType)];if(-not $type){$type='UnsupportedServiceType:'+([uint32]$Actual.ServiceType)};$error=$errors[[string]([uint32]$Actual.ErrorControl)];if(-not $error){$error='UnsupportedErrorControl:'+([uint32]$Actual.ErrorControl)};$sid=$sidTypes[[string]([uint32]$Actual.ServiceSidType)];if(-not $sid){$sid='UnsupportedServiceSidType:'+([uint32]$Actual.ServiceSidType)}
    $f=$Actual.FailureActions;$reset=[uint32]$f[0];if($reset -eq [uint32]::MaxValue){$reset='Infinite'};$actions=@(foreach($a in $f[3]){$name=$actionTypes[[string]([int]$a[0])];if(-not $name){$name='UnsupportedAction:'+([int]$a[0])};[pscustomobject][ordered]@{Type=$name;DelayMilliseconds=[long][uint32]$a[1]}})
    $triggers=@(foreach($t in $Actual.Triggers){$data=@(foreach($d in $t[3]){[pscustomobject][ordered]@{Type=[uint32]$d[0];DataBase64=[string]$d[1]}});$triggerAction='UnsupportedAction:'+([uint32]$t[1]);if([uint32]$t[1] -eq 1){$triggerAction='Start'}elseif([uint32]$t[1] -eq 2){$triggerAction='Stop'};[pscustomobject][ordered]@{Type=[uint32]$t[0];Action=$triggerAction;Subtype=[string]$t[2];DataItems=$data}})
    [pscustomobject][ordered]@{ServiceType=$type;ErrorControl=$error;LoadOrderGroup=[string]$Actual.LoadOrderGroup;DelayedAutoStart=[bool]$Actual.DelayedAutoStart;FailureActions=[pscustomobject][ordered]@{ResetPeriodSeconds=$reset;RebootMessage=[string]$f[1];Command=[string]$f[2];Actions=$actions};FailureActionsOnNonCrashFailures=[bool]$Actual.FailureActionsOnNonCrashFailures;ServiceSidType=$sid;RequiredPrivileges=@($Actual.RequiredPrivileges);Environment=@($Actual.Environment);Triggers=$triggers}
}
function Get-WsmServiceSupplementState([string]$Name) {
    Assert-WsmServiceSupplementName $Name;$native=Get-WsmServiceSupplementNativeState $Name;$typed=[pscustomobject][ordered]@{ServiceType=$native[0];ErrorControl=$native[1];LoadOrderGroup=$native[2];DelayedAutoStart=$native[3];FailureActions=$native[4];FailureActionsOnNonCrashFailures=$native[5];ServiceSidType=$native[6];RequiredPrivileges=$native[7];Environment=@(Get-WsmServiceEnvironment $Name);Triggers=$native[8]};ConvertFrom-WsmServiceSupplementState $typed
}
function Get-WsmServiceSupplementForPhase($Supplement,[ValidateSet('Staged','Final')][string]$Phase) {
    if($Phase -eq 'Final'){return $Supplement}
    $actions=@(foreach($nullAction in $Supplement.FailureActions.Actions){[pscustomobject][ordered]@{Type='None';DelayMilliseconds=[long]0}})
    $failure=[pscustomobject][ordered]@{ResetPeriodSeconds=$Supplement.FailureActions.ResetPeriodSeconds;RebootMessage='';Command='';Actions=$actions}
    [pscustomobject][ordered]@{ServiceType=$Supplement.ServiceType;ErrorControl=$Supplement.ErrorControl;LoadOrderGroup=$Supplement.LoadOrderGroup;DelayedAutoStart=$Supplement.DelayedAutoStart;FailureActions=$failure;FailureActionsOnNonCrashFailures=$false;ServiceSidType=$Supplement.ServiceSidType;RequiredPrivileges=@($Supplement.RequiredPrivileges);Environment=@($Supplement.Environment);Triggers=@()}
}
function Set-WsmServiceSupplement([string]$Name,$Supplement,[ValidateSet('Staged','Final')][string]$Phase='Staged') {
    Assert-WsmServiceSupplementName $Name;$null=Assert-WsmServiceSupplement $Supplement;$phaseSupplement=Get-WsmServiceSupplementForPhase $Supplement $Phase;$null=Assert-WsmServiceSupplement $phaseSupplement;$nativeInput=ConvertTo-WsmServiceSupplementNativeInput $phaseSupplement
    Invoke-WsmServiceSupplementNative $Name $nativeInput;Set-WsmServiceEnvironment $Name $nativeInput.Environment
    $state=Get-WsmServiceSupplementState $Name;$check=Test-WsmServiceSupplement $Supplement $state $Phase;if(-not $check.Passed){throw ('Service supplement '+$Phase+' read-back failed: '+($check.Problems -join '; '))};$check
}
function Test-WsmServiceSupplement($Supplement,$Actual,[ValidateSet('Staged','Final')][string]$Phase='Final') {
    $issues=New-Object 'System.Collections.Generic.List[string]';try{$null=Assert-WsmServiceSupplement $Supplement;$null=Assert-WsmServiceSupplement $Actual}catch{$issues.Add($_.Exception.Message);return [pscustomobject]@{Passed=$false;Problems=$issues.ToArray()}}
    $expected=Get-WsmServiceSupplementForPhase $Supplement $Phase
    foreach($field in @('ServiceType','ErrorControl','LoadOrderGroup','ServiceSidType')){if([string]$Actual.$field -cne [string]$expected.$field){$issues.Add(('Service '+$field+' mismatch'))}};if([bool]$Actual.DelayedAutoStart -ne [bool]$expected.DelayedAutoStart){$issues.Add('Service delayed-auto-start mismatch')};if((@($Actual.RequiredPrivileges | Sort-Object -CaseSensitive) -join "`n") -cne (@($expected.RequiredPrivileges | Sort-Object -CaseSensitive) -join "`n")){$issues.Add('Service required-privilege list mismatch')};if((@($Actual.Environment | Sort-Object -CaseSensitive) -join "`n") -cne (@($expected.Environment | Sort-Object -CaseSensitive) -join "`n")){$issues.Add('Service environment mismatch')}
    $observed=$Actual.FailureActions;if([string]$observed.ResetPeriodSeconds -cne [string]$expected.FailureActions.ResetPeriodSeconds -or [string]$observed.RebootMessage -cne [string]$expected.FailureActions.RebootMessage -or [string]$observed.Command -cne [string]$expected.FailureActions.Command){$issues.Add('Service failure-action reset/message/command mismatch')};if([bool]$Actual.FailureActionsOnNonCrashFailures -ne [bool]$expected.FailureActionsOnNonCrashFailures){$issues.Add('Service failure-actions flag mismatch')};$expectedActions=@($expected.FailureActions.Actions);$actualActions=@($observed.Actions);if($expectedActions.Count -ne $actualActions.Count){$issues.Add('Service failure-action count mismatch')}else{for($n=0;$n -lt $expectedActions.Count;$n++){if($expectedActions[$n].Type -cne $actualActions[$n].Type -or [long]$expectedActions[$n].DelayMilliseconds -ne [long]$actualActions[$n].DelayMilliseconds){$issues.Add(('Service failure action mismatch at '+$n));break}}}
    $expectedTriggers=@($expected.Triggers);$actualTriggers=@($Actual.Triggers);if($expectedTriggers.Count -ne $actualTriggers.Count){$issues.Add('Service trigger count mismatch')}else{for($t=0;$t -lt $expectedTriggers.Count;$t++){$et=$expectedTriggers[$t];$at=$actualTriggers[$t];$subtypeMatches=([string]$et.Subtype -ceq [string]$at.Subtype);if($et.Subtype -and $at.Subtype){$eg=[Guid]::Empty;$ag=[Guid]::Empty;if([Guid]::TryParse($et.Subtype,[ref]$eg) -and [Guid]::TryParse($at.Subtype,[ref]$ag)){$subtypeMatches=($eg -eq $ag)}};$triggerMatches=([uint32]$et.Type -eq [uint32]$at.Type -and $et.Action -ceq $at.Action -and $subtypeMatches);$ed=@($et.DataItems);$ad=@($at.DataItems);if($ed.Count -ne $ad.Count){$triggerMatches=$false}else{for($d=0;$d -lt $ed.Count;$d++){if([uint32]$ed[$d].Type -ne [uint32]$ad[$d].Type -or [string]$ed[$d].DataBase64 -cne [string]$ad[$d].DataBase64){$triggerMatches=$false;break}}};if(-not $triggerMatches){$issues.Add(('Service trigger mismatch at '+$t));break}}}
    [pscustomobject]@{Passed=($issues.Count -eq 0);Problems=$issues.ToArray()}
}
