function Merge-WsmSortedHashFiles([string[]]$Paths,[string]$OutputPath) {
    $readers=New-Object 'System.Collections.Generic.List[object]';$heads=New-Object 'System.Collections.Generic.List[string]';$writer=New-Object IO.StreamWriter($OutputPath,$false,[Text.Encoding]::ASCII)
    try{foreach($path in $Paths){$reader=New-Object IO.StreamReader($path,[Text.Encoding]::ASCII);$readers.Add($reader);$heads.Add($reader.ReadLine())};while($true){$best=-1;for($n=0;$n -lt $heads.Count;$n++){if($null -ne $heads[$n] -and ($best -lt 0 -or [StringComparer]::Ordinal.Compare($heads[$n],$heads[$best]) -lt 0)){$best=$n}};if($best -lt 0){break};$writer.WriteLine($heads[$best]);$heads[$best]=$readers[$best].ReadLine()}}finally{$writer.Dispose();foreach($reader in $readers){$reader.Dispose()}}
}
function Get-WsmStreamingScopeDigest([string]$Root,[string]$MetadataMode) {
    if(-not [IO.File]::Exists($Root) -and -not [IO.Directory]::Exists($Root)){return ''}
    $scratch=Join-Path ([IO.Path]::GetTempPath()) ('wsm-digest-'+[Guid]::NewGuid().ToString('N'));[void][IO.Directory]::CreateDirectory($scratch);Protect-WsmDirectory $scratch
    $parts=New-Object 'System.Collections.Generic.List[string]';$known=New-Object 'System.Collections.Generic.List[string]';$buffer=New-Object 'System.Collections.Generic.List[string]';$count=[long]0;$serial=0
    try{
        Get-WsmScopeEntries ([pscustomobject]@{SourcePath=$Root;ExcludedRelativePaths=@()}) $scratch | ForEach-Object {$e=$_;$fileHash='';if(-not $e.Directory){$fileHash=(Get-FileHash -LiteralPath $e.SourcePath).Hash.ToLowerInvariant()};$meta=Get-WsmFileMetadata $e.SourcePath $MetadataMode;$row=[pscustomobject][ordered]@{RelativePath=$e.RelativePath.ToLowerInvariant();Directory=$e.Directory;Hash=$fileHash;Sddl=$meta.Sddl;Attributes=$meta.Attributes};$buffer.Add((Get-WsmHashText ($row | ConvertTo-Json -Depth 8 -Compress)));$count++
            if($buffer.Count -ge 5000){$part=Join-Path $scratch ('part-'+$serial+'.txt');$serial++;[IO.File]::WriteAllLines($part,[string[]]@($buffer | Sort-Object),[Text.Encoding]::ASCII);$parts.Add($part);$known.Add($part);$buffer.Clear();Write-Progress -Activity 'Verifying owned scope (bounded memory)' -Status ($count.ToString()+' entries inspected')}
        }
        if($buffer.Count){$part=Join-Path $scratch ('part-'+$serial+'.txt');$serial++;[IO.File]::WriteAllLines($part,[string[]]@($buffer | Sort-Object),[Text.Encoding]::ASCII);$parts.Add($part);$known.Add($part);$buffer.Clear()}
        while($parts.Count -gt 1){$next=New-Object 'System.Collections.Generic.List[string]';for($n=0;$n -lt $parts.Count;$n+=64){$last=[Math]::Min($n+63,$parts.Count-1);$group=@(for($i=$n;$i -le $last;$i++){$parts[$i]});$merged=Join-Path $scratch ('merge-'+$serial+'.txt');$serial++;Merge-WsmSortedHashFiles $group $merged;$known.Add($merged);$next.Add($merged);foreach($path in $group){[IO.File]::Delete($path)}};$parts=$next}
        $sha=[Security.Cryptography.SHA256]::Create();try{$header=[Text.Encoding]::ASCII.GetBytes($count.ToString([Globalization.CultureInfo]::InvariantCulture)+':');[void]$sha.TransformBlock($header,0,$header.Length,$header,0);if($parts.Count){$file=[IO.File]::Open($parts[0],'Open','Read','Read');try{$bytes=New-Object byte[] 65536;while(($n=$file.Read($bytes,0,$bytes.Length)) -gt 0){[void]$sha.TransformBlock($bytes,0,$n,$bytes,0)}}finally{$file.Dispose()}};[void]$sha.TransformFinalBlock((New-Object byte[] 0),0,0);[BitConverter]::ToString($sha.Hash).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}
    }finally{foreach($path in $known){if([IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($path)) -cne $scratch){throw 'Digest cleanup path escaped generated workspace.'};if([IO.File]::Exists($path)){[IO.File]::Delete($path)}};if([IO.Directory]::Exists($scratch)){[IO.Directory]::Delete($scratch,$false)};Write-Progress -Activity 'Verifying owned scope (bounded memory)' -Completed}
}
function Read-WsmBoundedLines($Reader,[int]$MaximumCharacters=1048576) {
    $buffer=New-Object char[] 65536;$pending=New-Object Text.StringBuilder
    while(($length=$Reader.Read($buffer,0,$buffer.Length)) -gt 0){$chunk=New-Object string($buffer,0,$length);$start=0;while($start -lt $chunk.Length){$end=$chunk.IndexOf([char]10,$start);$finish=$chunk.Length;if($end -ge 0){$finish=$end};$size=$finish-$start;if($pending.Length+$size -gt $MaximumCharacters){throw 'Artifact/journal row exceeds bounded line limit.'};if($size){[void]$pending.Append($chunk,$start,$size)};if($end -lt 0){break};$line=$pending.ToString().TrimEnd([char]13);$pending.Clear() | Out-Null;if($line){$line};$start=$end+1}}
    if($pending.Length){$pending.ToString().TrimEnd([char]13)}
}
