function Get-WsmToolFingerprint {
    $files=@(Get-ChildItem -LiteralPath $PSScriptRoot -File | Where-Object Extension -In @('.ps1','.psm1','.psd1') | Sort-Object Name);$files+=@(Get-Item (Join-Path ([IO.Path]::GetDirectoryName($PSScriptRoot)) 'Start-ServerMigration.ps1'));$rows=@(foreach($f in $files){$f.Name+'|'+(Get-FileHash -LiteralPath $f.FullName).Hash.ToLowerInvariant()});Get-WsmHashText ($rows -join "`n")
}
function Export-WsmToolRelease {
    param([string]$Path)
    $root=[IO.Path]::GetDirectoryName($PSScriptRoot);if([IO.File]::Exists($Path)){throw 'Release archive already exists.'};$files=@(Get-Item (Join-Path $root 'Start-ServerMigration.ps1'))+@(Get-ChildItem -LiteralPath $PSScriptRoot -File | Where-Object Extension -In @('.ps1','.psm1','.psd1'))+@(Get-Item (Join-Path $root 'README.md'))+@(Get-ChildItem -LiteralPath (Join-Path $root 'docs') -Filter '*.md' -File)
    $index=[pscustomobject]@{SchemaVersion=1;ToolVersion=$script:ToolVersion;Kind='ToolRelease';ToolFingerprint=(Get-WsmToolFingerprint);Files=@(foreach($file in $files){[pscustomobject]@{Path=$file.FullName.Substring($root.Length+1).Replace('\','/');Bytes=$file.Length;SHA256=(Get-FileHash -LiteralPath $file.FullName).Hash.ToLowerInvariant();SignatureStatus=[string](Get-AuthenticodeSignature -LiteralPath $file.FullName).Status}});Runtime='Windows PowerShell 5.1 x64 FullLanguage; required roles/modules detected locally';ProductionVerified=$false;Deployment='Verify independent archive hash and exact byte release; apply enterprise signing/trust policy, never auto-change policy';CreatedUtc=(Get-WsmUtc)}
    Add-Type -AssemblyName System.IO.Compression.FileSystem;$temp=$Path+'.partial';$archive=$null
    try{$archive=[IO.Compression.ZipFile]::Open($temp,'Create');foreach($file in $files){[void][IO.Compression.ZipFileExtensions]::CreateEntryFromFile($archive,$file.FullName,$file.FullName.Substring($root.Length+1).Replace('\','/'))};$entry=$archive.CreateEntry('release.json');$writer=New-Object IO.StreamWriter($entry.Open(),(New-Object Text.UTF8Encoding($false)));try{$writer.Write(($index | ConvertTo-Json -Depth 10))}finally{$writer.Dispose()};$archive.Dispose();$archive=$null;[IO.File]::Move($temp,$Path)}finally{if($archive){$archive.Dispose()};if([IO.File]::Exists($temp)){[IO.File]::Delete($temp)}}
    [pscustomobject]@{Path=[IO.Path]::GetFullPath($Path);SHA256=(Get-FileHash -LiteralPath $Path).Hash;ToolFingerprint=$index.ToolFingerprint;ProductionVerified=$false;Signed=$false}
}
