@{
    RootModule = 'WindowsServerMigration.psm1'
    ModuleVersion = '0.3.0'
    GUID = 'f9a991e9-4a49-44d4-8633-e15e844ddc3b'
    PowerShellVersion = '5.1'
    FunctionsToExport = @('Get-WsmFailureDetails','Invoke-WsmSourceResume','Export-WsmMigrationSpecBundle','Get-WsmMigrationSpecBundlePreview','Import-WsmMigrationSpecBundle','Repair-WsmWorkspace','Export-WsmToolRelease','Export-WsmSourceStageResult','Set-WsmIdentityMap','Export-WsmRawEvidenceManifest','New-WsmMigrationSpecTemplate','Show-WsmMigrationWizard','Test-WsmJournal','Repair-WsmOperation','Get-WsmRollbackPreview','Invoke-WsmRollback','Get-WsmOperationActions','Invoke-WsmOperationRequest','Get-WsmOperationStatusCode','Show-WsmMigrationMenu','Export-WsmPackageZip','Import-WsmPackageZip','Export-WsmOperationReport','Export-WsmFreezeRecord','Set-WsmValidationEvidence','Invoke-WsmValidation','New-WsmCutoverPlan','Invoke-WsmCutover','Get-WsmAcceptanceGates','Export-WsmStageResult','Register-WsmTarget','Get-WsmAdapterMatrix','Set-WsmMigrationSpec','Approve-WsmMigrationPlan','Get-WsmPackageEstimate','Export-WsmMigrationPackage','Test-WsmMigrationPackage','Get-WsmRestorePreview','Invoke-WsmRestore','Initialize-WsmWorkspace','Get-WsmFleet','Get-WsmCatalog','New-WsmItem','New-WsmInventory','Import-WsmInventory','Import-WsmInventoryArchive','Get-WsmItems','Set-WsmDecision','Undo-WsmDecision','Export-WsmDecisions','Import-WsmDecisions','Get-WsmReviewIssues','Set-WsmMapping','Set-WsmEvidence','Export-WsmReport','Export-WsmTextReport','Export-WsmFleetReport','Approve-WsmPlan','Import-WsmApprovedPlan','Export-WsmInventory','Get-WsmPreflight','Get-WsmCapabilities','Export-WsmReviewTemplate','Get-WsmTemplatePreview','Invoke-WsmReviewTemplate','Set-WsmConsistencyGroup','Get-WsmCategorySummary','Get-WsmDecisionPreview','Get-WsmRulePreview','Invoke-WsmReviewRule','Add-WsmManualItem','Set-WsmReviewMetadata','Set-WsmDependencies','Set-WsmReviewView','Set-WsmPairPlan','Set-WsmCrossHostDependency','Export-WsmFleetGraph','Import-WsmStageResult')
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
}
